### ISSUE TITLE
cf service-key should exit with non-zero code if service-key is not found

### ISSUE THREAD

**Issue by andreasf** [cloudfoundry/cli#1001]
* Command  
`cf service-key existing-db missing-key`

* What occurred, incl. error and/or stack trace
Output:
```sh
$ cf service-key existing-db missing-key
Getting key missing-key for service instance existing-db as afleig@pivotal.io...
No service missing-key foo found for service instance existing-db
$ echo $?
0
```

* What you expected to occur
Same output, but non-zero exit code

* CLI Version  
cf version 6.22.2+a95e24c-2016-10-27

**Comment by dkoper** [comment]
This issue has now been resolved in cf CLI 6.23.0.
https://github.com/cloudfoundry/cli#downloads

Regards,
Dies Koper
CF CLI PM
