### ISSUE TITLE
`cf env app-name var-name` to get a single environment variable

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cli#1003]
When viewing environment variables for an app, it is often overwhelming to have to parse the entire collection of environment variables (e.g. to be able to pipe a single variable's value to another process). I find myself doing a `cf ssh` so I can `echo $ENV_VAR | my-other-process`. I would like to be able to do something like `cf env my-app var-name | my-other-process` to avoid the SSH step.

**Comment by dkoper** [comment]
Hi Dan,

What is the use case for wanting to pipe a single env var to another process? Why not several, or even the whole shebang? (E.g. to start an app locally with the same environment variables)

`cf env` currently prints system provided vars, user provided vars, staging and running env var groups, which I believe is not very scripting friendly, so I want to understand how we can improve it for all its users.

In your case, the CLI may not necessarily know which particular ENV_VAR. I'm sure the backend has rules that define which takes priority, but we'd prefer not to duplicate that business logic in the CLI.

Cheers,
Dies Koper
CF CLI PM

**Comment by wendorf** [comment]
The use case is usually to get a service binding's connection information so I can inspect it myself. I think the bigger problem about making it hard to grep is that the standard output has multiple JSON documents and plenty of plaintext. If STDOUT were a single JSON blob, I could pass that to something like jq and easily get the information I needed, without the CLI needing to include any additional business logic.

**Comment by sam-radiant** [comment]
Without being able to get a single env var with out put and having non json text in the output it is pretty much impossible to use with scripting in a clean way. Would love to be able to grab binded services variables using this command.

**Comment by stuaxo** [comment]
Have to agree with this, it makes scripting a pain, choose JSON or KEY=VALUE, don't output both at once.
Ideally there would be a switch to toggle between KEY=VALUE or JSON.

**Comment by warijo** [comment]
Agreed, the current mix of plaintext / JSON-objects makes scripting really hard if not impossible.

**Comment by stuaxo** [comment]
Indeed.

Here is what I needed to do to get some environment variables from the "User Provided" section

```sh
export $(cf env ${CFAPP} | \
  awk '/User-Provided:/{flag=1;next}/^$/{flag=0}flag' | \
  grep -e 'AWS_ACCESS_KEY_ID' -e 'AWS_SECRET_ACCESS_KEY' -e 'AWS_STORAGE_BUCKET_NAME' | sed "s/\: /\=/g")
```

Which is straightforward..ish, to grab variables from the system-provided part, you have to do a similar thing and pipe via jq, which is even more hassle.

There needs to a way to grab either or both sections in key=value.

**Comment by AnilReddy231** [comment]
Here is the small snippet to list all the environment variables of PCF: 

cf ssh <App_Name> -c "python -c 'import os, json; print(json.dumps({key:value for (key,value) in os.environ.items()}, indent = 2))'"

{
  "INSTANCE_GUID": "315c18fb-e031-4e6e-67c4-84d1",
  "CF_INSTANCE_PORT": "61064",
  "CF_INSTANCE_KEY": "/etc/cf-instance-credentials/instance.key",
  "USER": "vcap",
  "INSTANCE_INDEX": "0",
   .
   .
   .
   .
"PWD": "/home/vcap",
"VCAP_APP_PORT": "8080"
}
}

**Comment by abbyachau** [comment]
Related: https://github.com/cloudfoundry/cli/issues/1415

**Comment by heyjcollins** [comment]
With the GA of the v7 CLI, we're no longer actively developing against the v6 line.  With an interest the overall hygiene of the CLI project we're closing this  issue.
If this issue is still occurring in v7 please feel free to comment and re-open. Thank you!

**Comment by iDschepe** [comment]
### Please Re-Open.
It still outputs a mix of plain text and JSON which is still hard to extract values - even with regular expressions.

### Backward Compatibility - if needed
For backward compatibility reasons you may add this behaviour only by giving an additional parameter to get the JSON output. 
Meaning `--json` has to be given for STDOUT a JSON object: 

`cf env myappname --json`
 
#### Suggested solution - as already mentioned:
- use one single JSON as STDOUT
- and additionally give an option to get a single property value: 

`cf env myappname --json -p propertyname`

### Examples (with Backward Compatibility): 
Using:
```
$ cf env myappname --json
```
**must** return _valid_ JSON Object as STDOUT:
```
{
    VCAP_SERVICES: { 
        "application-logs": [ ... ],
        "connectivity": [ ... ],
        ...
    },
    VCAP_APPLICATION: {
        "application_id": "30051990-0000-0000-0000-33cf333e3f33",
        ...
    },
    "User-Provided": {
        TENANT_HOST_PATTERN: "xyz", 
        ...
    }
}
```

Specifying a property name:
```
$ cf env myappname --json -p VCAP_APPLICATION
```
**must** return given property value as _valid_ JSON STDOUT
```
{
    "application_id": "30051990-0000-0000-0000-33cf333e3f33",
    ...
}
```

⚠ Please Note: 
"..." in Example-JSON object stands for the remaining properties and values of the valid object.

**Comment by szymarcus** [comment]
> ### Please Re-Open.
> It still outputs a mix of plain text and JSON which is still hard to extract values - even with regular expressions.
> 
> ### Backward Compatibility - if needed
> For backward compatibility reasons you may add this behaviour only by giving an additional parameter to get the JSON output. Meaning `--json` has to be given for STDOUT a JSON object:
> 
> `cf env myappname --json`
> 
> #### Suggested solution - as already mentioned:
> * use one single JSON as STDOUT
> * and additionally give an option to get a single property value:
> 
> `cf env myappname --json -p propertyname`
> 
> ### Examples (with Backward Compatibility):
> Using:
> 
> ```
> $ cf env myappname --json
> ```
> 
> **must** return _valid_ JSON Object as STDOUT:
> 
> ```
> {
>     VCAP_SERVICES: { 
>         "application-logs": [ ... ],
>         "connectivity": [ ... ],
>         ...
>     },
>     VCAP_APPLICATION: {
>         "application_id": "30051990-0000-0000-0000-33cf333e3f33",
>         ...
>     },
>     "User-Provided": {
>         TENANT_HOST_PATTERN: "xyz", 
>         ...
>     }
> }
> ```
> 
> Specifying a property name:
> 
> ```
> $ cf env myappname --json -p VCAP_APPLICATION
> ```
> 
> **must** return given property value as _valid_ JSON STDOUT
> 
> ```
> {
>     "application_id": "30051990-0000-0000-0000-33cf333e3f33",
>     ...
> }
> ```
> 
> ⚠ Please Note: "..." in Example-JSON object stands for the remaining properties and values of the valid object.

This seems like a very helpful setting. Otherwise its quite tedious to get single values from the arbitrary response format.

**Comment by Fjaoos** [comment]
Hello, 
it would be very helpful if this issue would be reopened. Everytime we deploy something to the CloudFoundry Space, the environment variables change.
In order to develop locally but still have a connection to the CF Space (and the attached backends) we need one of those variables in our local .env file and change it a little bit before that.

For now we are using some js that does some nasty string operations so having a json output would be very helpful.

**Comment by AnilPonduri** [comment]
Hello friends, I am also facing the same issue, since some credentials of services expires and need to be regenerated often so want to retrive the env for Vcap_services>
Still this issue is not resolved ?
