### ISSUE TITLE
[Q] Single file

### ISSUE THREAD

**Issue by dnsBlah** [cloudfoundry/cli#1004]
Is there any option to push a single file?
Will this help me with pushing my app changes faster?

Currently I must provide the buildpack everytime as well :-( Resulting in downloading, extracting, compiling the package and extensions EVERY single time I make a small change.

**Comment by dkoper** [comment]
Hi @dnsBlah 

The CLI first uploads a list of your app files and their checksums and only uploads the files the Cloud Controller hasn't cached from a previous push, but even then the whole package is recompiled each time.
You may want to check out the [fastpush](https://github.com/xiwenc/cf-fastpush-plugin) plug-in & controller.

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Closing as resolved. Feel free to reopen if you have any follow-up questions, but you can also post questions to the CF Dev mailing list which is followed by a wider audience with expert CLI users.
