### ISSUE TITLE
Option to not assign roles on org/space creation

### ISSUE THREAD

**Issue by afeld** [cloudfoundry/cli#1007]
When creating an org or space, I was surprised to see that the OrgManager, SpaceManager, and SpaceDeveloper roles get assigned automatically. When I can understand the convenience for certain/most use cases, I don't think it works as well for others. Specifically: as an admin on our Cloud Foundry deployment, I create orgs for other teams (through [a script](https://github.com/18F/cg-scripts/blob/master/cf-create-org.sh), if you're curious). Since I don't want to be associated with these orgs (which has other implications for us), this means I then need to unassign the roles for myself. If the behavior wasn't there already, I would say there should be a flag on `cf create-org` and `create-space` to opt in to the automatic role assignment, but since it's there already, maybe a `--no-roles` or `--roles ''` (as opposed to `--roles 'SpaceDeveloper'`) flag?

Not a _huge_ deal, since I will just [undo the roles in the script](https://github.com/18F/cg-scripts/pull/30) - just a thought. Thanks!

---

* Command  

```sh
cf create-org test
```

* What occurred, incl. error and/or stack trace

```
Creating org test as aidan.feldman@gsa.gov...
OK

Assigning role OrgManager to user aidan.feldman@gsa.gov in org test ...
OK
```

* What you expected to occur

I wasn't expecting to be assigned the OrgManager role.

* CLI Version  

`cf version 6.22.2+a95e24c-2016-10-27`

* CC API Endpoint Version  

2.64.0

* CF Trace

(truncated version)

```
Creating org testagency-prototyping as aidan.feldman@gsa.gov...

REQUEST: [2016-11-22T17:05:10-05:00]
POST /v2/organizations HTTP/1.1
...

{"name":"testagency-prototyping"}

RESPONSE: [2016-11-22T17:05:10-05:00]
HTTP/1.1 201 Created
...

REQUEST: [2016-11-22T17:05:10-05:00]
GET /v2/config/feature_flags/set_roles_by_username HTTP/1.1
...

RESPONSE: [2016-11-22T17:05:11-05:00]
HTTP/1.1 200 OK
...

{
  "name": "set_roles_by_username",
  "enabled": true,
  "error_message": null,
  "url": "/v2/config/feature_flags/set_roles_by_username"
}

REQUEST: [2016-11-22T17:05:11-05:00]
GET /v2/organizations?q=name%3Atestagency-prototyping&inline-relations-depth=1 HTTP/1.1
...

RESPONSE: [2016-11-22T17:05:11-05:00]
HTTP/1.1 200 OK
...

Assigning role OrgManager to user aidan.feldman@gsa.gov in org testagency-prototyping ...

REQUEST: [2016-11-22T17:05:11-05:00]
PUT /v2/organizations/6eb5630f-660a-4c5d-b63a-161bff5dda4d/managers HTTP/1.1
...

RESPONSE: [2016-11-22T17:05:12-05:00]
HTTP/1.1 201 Created
...

REQUEST: [2016-11-22T17:05:12-05:00]
PUT /v2/organizations/6eb5630f-660a-4c5d-b63a-161bff5dda4d/users HTTP/1.1
...

RESPONSE: [2016-11-22T17:05:13-05:00]
HTTP/1.1 201 Created
...

OK

TIP: Use 'cf target -o testagency-prototyping' to target new org
```

* Platform & Shell Details  

Mac OS X 10.11 iTerm

**Comment by dkoper** [comment]
Hi @afeld 

Thanks for sharing this experience.
I assume as you pointed out the current behaviour is because most people actually do want to be associated with the org - I guess admins who regularly create orgs for others and don't want to be part of the org are using the API directly (through some script or plugin).
Although it's a valid request and I have no UX issues with adding such a flag, as you have an easy work-around, I'll leave it open for a while to see how many other people feel strongly about this, else I'd like to close it as a won't fix as we have plenty of other things to focus on. Fair?

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Closing. Thanks again for bringing this up. One of the design principles of the CLI was to keep commands simple, users can script them to build more complicated workflows, and I feel this command does not follow that. That said, it doesn't seem to bother enough people to address it.
