### ISSUE TITLE
"cf help" does not show all available cli commands

### ISSUE THREAD

**Issue by ebabani** [cloudfoundry/cli#1009]
High five for submitting a report!  
If you found an issue with the cf CLI, please visit the [releases page](https://github.com/cloudfoundry/cli/releases/) and confirm it's not fixed already in the latest release.  
To avoid additional back and forth, please include the following details as relevant:

* Command  
cf or cf help

* What occurred, incl. error and/or stack trace
Calling 'cf' or 'cf help' does not show all the commands available for the cli.

Example: 
```
Route and domain management:
  routes,r        delete-route    create-domain
  domains         map-route
  create-route    unmap-route
```
The delete-domain command is missing.

Running `cf help -a` shows the delete-domain command.
```
DOMAINS:
   domains                                List domains in the target org
   create-domain                          Create a domain in an org for later use
   delete-domain                          Delete a domain
   create-shared-domain                   Create a domain that can be used by all orgs (admin-only)
   delete-shared-domain                   Delete a shared domain

   router-groups                          List router groups
```
* CLI Version  
6.22.2+a95e24c-2016-10-27

* CC API Endpoint Version  
API endpoint: https://api.zeus.gcp.cf-app.com (API version: 2.58.0)

* CF Trace, if issue relates to HTTP requests or strange behavior  
none

* Platform & Shell Details  
iTerm on OSX

* Any other relevant information  
none

**Comment by dkoper** [comment]
That's as intended, to keep the output short. Use 'cf help -a' to see the full listing.

**Comment by ebabani** [comment]
Can we add a short line saying that  'cf help' does not list all commands then?

The current description of `'cf help -a' lists all commands with short descriptions.` is a bit ambiguous.

**Comment by dkoper** [comment]
Something like `The above are the most common commands; use 'cf help -a' to see all, with descriptions`?

**Comment by ebabani** [comment]
Yup, that sounds good to me. Just something that indicates -a has more entries.

**Comment by dkoper** [comment]
Done!
https://github.com/cloudfoundry/cli#downloads

Regards,
Dies Koper
CF CLI PM
