### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sourabhks** [cloudfoundry/cli#1010]
C:\Users\INDU\Desktop\chatbot\conversation-simple-master>cf push
Using manifest file C:\Users\INDU\Desktop\chatbot\conversation-simple-master\man
ifest.yml

Updating app GVT-chatbot in org SK123 / space EX1 as annuvikash@gmail.com...
OK

Uploading GVT-chatbot...
Uploading app files from: C:\Users\INDU\Desktop\chatbot\conversation-simple-mast
er
Uploading 1.3M, 99 files
Done uploading
OK
Binding service conversation-simple-demo-test1 to app GVT-chatbot in org SK123 /
 space EX1 as annuvikash@gmail.com...
OK

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x52330b]

goroutine 891 [running]:
panic(0xaf1900, 0x127a0030)
        /usr/local/go/src/runtime/panic.go:500 +0x331
sync/atomic.LoadUint64(0x12bfe56c, 0x12e02780, 0x12bfe4d0)
        /usr/local/go/src/sync/atomic/asm_386.s:159 +0xb
code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consumer.(*Consume
r).retryAction(0x12bfe4d0, 0x12b6a640, 0x12bd9a80)
        /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/vendor/github.c
om/cloudfoundry/noaa/consumer/async.go:269 +0xa2
code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consumer.(*Consume
r).streamAppDataTo(0x12bfe4d0, 0x12e02770, 0x12b401b0, 0x24, 0x127bce00, 0x312,
0x12b5e328, 0x12bd9a80, 0x79f401)
        /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/vendor/github.c
om/cloudfoundry/noaa/consumer/async.go:188 +0x10c
code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consumer.(*Consume
r).tailingLogs.func2(0x12bd9a80, 0x12bd9a40, 0x12bfe4d0, 0x12e02770, 0x12b401b0,
 0x24, 0x127bce00, 0x312, 0x12b5e328, 0x1)
        /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/vendor/github.c
om/cloudfoundry/noaa/consumer/async.go:163 +0xae
created by code.cloudfoundry.org/cli/vendor/github.com/cloudfoundry/noaa/consume
r.(*Consumer).tailingLogs
        /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/vendor/github.c
om/cloudfoundry/noaa/consumer/async.go:164 +0x106

Please help for this memory address error

**Comment by dkoper** [comment]
Hi @sourabhks 

Are you using the 32 bit release?
The noaa library bundled in the cf CLI 6.22.2 has a regression on 32 bit platforms.
We've addressed it for the next release.

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
We've posted a link to our edge build in #991, which reports the same issue.

**Comment by sourabhks** [comment]
@dkoper 

What should i do? Please if you could tell me the steps. I am new to CLI & Bluemix. Thanks

**Comment by dkoper** [comment]
Hi @sourabhks 

Please try the edge build posted in https://github.com/cloudfoundry/cli/issues/991#issuecomment-263337964 and report back whether it resolves the issue?
