### ISSUE TITLE
unable to push docker app

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry/cli#1011]
* Command  
`CF_TRACE=true cf push docker-nmap -o docker pull uzyexe/nmap`

* What occurred, incl. error and/or stack trace

```
FAILED
Incorrect Usage.
```

* What you expected to occur

To be able to push an app up, much like is officially [documented](http://docs.pivotal.io/pivotalcf/1-8/adminguide/docker.html#public).

* CLI Version  

`cf version 6.22.2+a95e24c-2016-10-27`

* CC API Endpoint Version  

2.58.0

* CF Trace, if issue relates to HTTP requests or strange behavior  

I've tried, but it doesn't get that far.

* Platform & Shell Details  

`Darwin joliet 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64`

**Comment by ematpl** [comment]
@jtarchie, try `cf push docker-nmap -o uzyexe/nmap`, without the `docker pull` part.

Thanks,
Eric

**Comment by jtarchie** [comment]
This is the end of a holiday weekend!

Sorry.
