### ISSUE TITLE
create-service does not fail on ongoing instance delete

### ISSUE THREAD

**Issue by hsiliev** [cloudfoundry/cli#1014]
Operations with asynchronous service instances may take several minutes. `create-service` command does not check for ongoing asynchronous operations, while `delete-service` on the other hand stops when there is an ongoing operation.

* Command 

   We create service, then delete it. While delete op is ongoing create operations succeed:
   ```bash
   cf create-service mongodb small mydb
   < ... wait for creation polling cf service db...>
   cf delete-service mydb
   cf create-service mongodb small mydb
   ```

* What occurred, incl. error and/or stack trace

   Create service command finished successfully with exit code 0. However the DB is being deleted and after several seconds/minutes the instance is no longer available.

   The current behavior means that users cannot rely on the response of `create-service`, nor the displayed `already exists` message. Even if the exit code is 0,  they still need to poll the service status and wait for **\*all\*** possible outcomes. For example in this script [snippet](https://github.com/cloudfoundry-incubator/cf-abacus/blob/ef4e40d1981783ee459eaa156115fe2033374cc5/etc/concourse/scripts/cf-deploy-infra#L112-L123) we need to wait for:
   * create successful
   * create failed
   * deleted / no longer present   
   
* What you expected to occur

   Fail with 409 and exit code different than 0. For example if we copy the behavior of `delete-service` we can have something like:
   ```
   cf create-service mongodb small mydb

   Creating service db in org orgz / space test as orgdmin...
   FAILED
   Server error, status code: 409, error code: 60016, message: An operation for service instance db is in progress.
   ```

* CLI Version  

   cf version 6.22.2+a95e24c-2016-10-27

* CC API Endpoint Version  

   API endpoint: https://api.cf.us10.hana.ondemand.com (API version: 2.63.0)

* Platform & Shell Details  

   Mac OS X 10.12.1 iTerm

**Comment by dkoper** [comment]
Hi @hsiliev 

Are you saying CC returns a 409 status code and the issue is that the CLI exits with status 0 as if no error occurred, or are you suggesting CC should return a 409 status code (in which case you submitted this to the wrong tracker)?

Note that there is a discussion in #976 for a CC API change to allow the CLI to poll for (async) service provisioning to complete.

Regards,
Dies Koper
CF CLI PM

**Comment by hsiliev** [comment]
To me the issue falls in-between. CC does the right thing from REST point of view - the service already exists and a call to create should be noop. But in the same time if there is an ongoing delete operation 409 would be more appropriate.

If you think CLI should not check for ongoing operations and this is CC responsibility please close the issue. I'll gladly move it to CC ground.
