### ISSUE TITLE
Error read/writing config:  invalid character 'N' after top-level value

### ISSUE THREAD

**Issue by katsar0v** [cloudfoundry/cli#1017]
High five for submitting a report!  
If you found an issue with the cf CLI, please visit the [releases page](https://github.com/cloudfoundry/cli/releases/) and confirm it's not fixed already in the latest release.  
To avoid additional back and forth, please include the following details as relevant:

* Command  
e.g. `cf push myapp -i 2 --no-route`
cf (basically anything with cf)

* What occurred, incl. error and/or stack trace
`Error read/writing config:  invalid character 'N' after top-level value
`
* What you expected to occur
Something else 

* CLI Version  
e.g. 6.13.0-dfba612 (see `cf -v` output)
cf -v not working, downloaded v6.22.2
* CC API Endpoint Version  
see `cf api` output

* CF Trace, if issue relates to HTTP requests or strange behavior  
run the command with `-v` and paste or attach the trace output

* Platform & Shell Details  
e.g. Mac OS X 10.11 iTerm, Windows 8.1 64-bit with PowerShell, Ubuntu 14.04.3 64-bit with gnome-terminal

* Any other relevant information  
e.g. details of an environment, cf CLI version, flag or value it does work with, DNS/network configuration, etc.
Happened during IBM Bluemix setup, but is in fact irrelevant. Uninstalling and installing did not help

**Comment by dkoper** [comment]
Can you share your config.json (see ~/.cf/)?
Did you have a cf CLI version installed on this machine before? If so what version?
What plugins if any were installed when the error started happening?

Cheers,
Dies Koper
CF CLI PM

**Comment by katsar0v** [comment]
Ah deleted everything there and it got fixed.. thanks 

I was using only the IBM Bluemix plugin

**Comment by dkoper** [comment]
Maybe next time you can send us a copy of config.json, maybe it'll help us determine what's corrupting it.

**Comment by Nilesh7756** [comment]
I'm face same issue.

ubuntu@bosh-stemcell:~$ cf --version
FAILED
Error read/writing config:  invalid character 'e' after top-level value
ubuntu@bosh-stemcell:~$

cf version: 6.34.1

config.json

############

{
  "ConfigVersion": 3,
  "Target": "",
  "APIVersion": "",
  "AuthorizationEndpoint": "",
  "DopplerEndPoint": "",
  "UaaEndpoint": "",
  "RoutingAPIEndpoint": "",
  "AccessToken": "",
  "UAAOAuthClient": "cf",
  "UAAOAuthClientSecret": "",
  "SSHOAuthClient": "",
  "RefreshToken": "",
  "OrganizationFields": {
    "GUID": "",
    "Name": "",
    "QuotaDefinition": {
      "name": "",
      "memory_limit": 0,
      "instance_memory_limit": 0,
      "total_routes": 0,
      "total_services": 0,
      "non_basic_services_allowed": false,
      "app_instance_limit": 0
    }
  },
  "SpaceFields": {
    "GUID": "",
    "Name": "",
    "AllowSSH": false
  },
  "SSLDisabled": false,
  "AsyncTimeout": 0,
  "Trace": "",
  "ColorEnabled": "",
  "Locale": "",
  "PluginRepos": null,
  "MinCLIVersion": "",
  "MinRecommendedCLIVersion": ""
}eout": 0,
  "Trace": "",
  "ColorEnabled": "",
  "Locale": "",
  "PluginRepos": [
    {
      "Name": "CF-Community",
      "URL": "https://plugins.cloudfoundry.org"
    }
  ],
  "MinCLIVersion": "6.23.0",
  "MinRecommendedCLIVersion": "6.23.0"
}

###############

Can you please help me on this.
