### ISSUE TITLE
cf orgs is showing duplicated entries

### ISSUE THREAD

**Issue by paolostivanin** [cloudfoundry/cli#1022]
* Command  
1. `cf orgs | sed '1,3d' | sort | wc -l`
2. `cf orgs | sed '1,3d' | sort -u | wc -l`

* What occurred, incl. error and/or stack trace
The first command gives back 129 org names, the second 94 and in both cases some orgs are missing.
```
CF_TRACE=true cf orgs| grep '^GET'
GET /v2/organizations?order-by=name HTTP/1.1
GET /v2/organizations?order-by=name HTTP/1.1
GET /v2/organizations?order-direction=asc&page=2&results-per-page=50 HTTP/1.1
GET /v2/organizations?order-direction=asc&page=3&results-per-page=50 HTTP/1.1
```

* CLI Version  
`6.22.2+a95e24c-2016-10-27`

* CC API Endpoint Version  
API endpoint: https://endpoint (API version: 2.65.0)

* Platform & Shell Details  
We are running Ubuntu 14.04 on our dev landscape and stemcell 3312 in our prod system

* Any other relevant information  
If we use `cf curl` as written below then everything is ok.
```
( cf curl '/v2/organizations?order-by=name&order-direction=asc&page=1&results-per-page=50' ; cf curl '/v2/organizations?order-by=name&order-direction=asc&page=2&results-per-page=50' ; cf curl '/v2/organizations?order-by=name&order-direction=asc&page=3&results-per-page=50' )
```

**Comment by paolostivanin** [comment]
Ok, the problem is *not* related to cf cli because I was able to reproduce it with a python script using requests.
I found out that if I take out the following params `order-by=name&order-direction=asc` everything works perfectly

**Comment by dkoper** [comment]
@paolostovanin [Cloud Controller](https://github.com/cloudfoundry/cloud_controller_ng/issues)?

**Comment by paolostivanin** [comment]
@dkoper I have opened the issue here[1] :) thanks though!

[1] https://github.com/cloudfoundry/cf-release/issues/1121
