### ISSUE TITLE
Check Route requires Host

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/cli#1024]
* Command  
`cf check-route example.com`

* What occurred, incl. error and/or stack trace
Error: `Incorrect Usage: the required argument `DOMAIN` was not provided`

* What you expected to occur
CLI indicates whether the route I created using `cf create-route pfcfdev-space example.com` exists

* CLI Version  
6.22.2+a95e24c-2016-10-27

* CC API Endpoint Version  
2.58.0

* Platform & Shell Details  
Mac OS X 10.11 stock Terminal

* Any other relevant information  
I don't know if this is a bug, but it seems odd that I can create a domain-only route that I can't then check the existence of.

**Comment by dkoper** [comment]
Closing - this doesn't seem to be a feature anyone is eagerly waiting for.
