### ISSUE TITLE
`cf apps` should list apps in an order humans can understand and use effectively

### ISSUE THREAD

**Issue by tjarratt** [cloudfoundry/cli#1026]
It seems like `cf apps` just prints out the applications in whichever order they came back from the API. While convenient and easy, this isn't the greatest experience (especially if you have 12+ apps with very similar names in a space).

In my case, my team is working in a shared space that has 15+ apps that all start with "CustomerService" and then have some word prepended at the end. It's always very hard to find which we care about without resorting to `grep`.

* Command  
e.g. `cf apps`

* What occurred, incl. error and/or stack trace

```
Getting apps in org ORG / space Dev as my-special-user...
OK

name                                                      requested state   instances   memory   disk   urls
Foo                                started           1/1         2G       1G     foo.bar.net
Bar                    started           1/1         2G       1G     bar.bar.net
Abracadra        started           1/1         2G       1G     abc.bar.net
```

* What you expected to occur
```
Getting apps in org ORG / space Dev as my-special-user...
OK

name                                                      requested state   instances   memory   disk   urls
Abracadra        started           1/1         2G       1G     abc.bar.net
Bar                    started           1/1         2G       1G     bar.bar.net
Foo                                started           1/1         2G       1G     foo.bar.net
```

* CLI Version  
`cf version 6.22.2+a95e24c-2016-10-27`

* Platform & Shell Details  
`Mac OS X 10.11 iTerm`

**Comment by dkoper** [comment]
Hi @tjarratt 

We've been wanting to do this for quite a while.
As CC is adding server-side sorting functionality (it's there for V3 apps, not sure about v2 apps), we don't want to do the sorting on the client side.

@SocalNick Assuming I'm correct that server side sorting by app name (GET /v2/spaces/<GUID>/summary) is not available at this moment and full V3 app support for the CLI seems to always take longer than we expect, would you consider adding this functionality for the above V2 API?

**Comment by SocalNick** [comment]
@dkoper can we add this to the desired UX for V3?

**Comment by dkoper** [comment]
@tjarratt Sounds okay with you?

**Comment by tjarratt** [comment]
That would be delightful!

Sent From A Very Small Keyboard

**Comment by dkoper** [comment]
Thanks. Closing - sorting of apps has been on our to do list and will be there from the start once we implement listing v3 apps.

**Comment by SocalNick** [comment]
V3 Story: https://www.pivotaltracker.com/story/show/136962495
