### ISSUE TITLE
[feature request] cf service should provide immediate feedback

### ISSUE THREAD

**Issue by glyn** [cloudfoundry/cli#1029]
It would be helpful if the command `cf service` gave immediate feedback followed by "OK" (in the successful case) like many of the other cf commands, such as `cf app`, do.

This is a low priority feature request, but I raise it simply because I noticed the inconsistency while developing a similar immediate feedback mechanism for a cli plugin.

Tested the current behaviour on cf cli 6.22.2+92b9ce0-2016-11-02.

**Comment by dkoper** [comment]
Hi @glyn 

Nice find.
While trying a few others, I noticed some other inconsistencies in this area (e.g. missing ansi colors in `cf quota`, some commands don't display the immediate text if the resource is not found, others do).
We are currently refactoring all our commands and will drive these inconsistencies out.
I'll leave this issue open so we don't miss it.

Regards,
Dies Koper
CF CLI PM

**Comment by glyn** [comment]
Thanks @dkoper. I appreciate my issue being left open as I'll be notified when it's fixed. Thanks!

**Comment by dkoper** [comment]
We have decided to phase out the use of `OK` in cases like this: after making the API calls, it displays the table straight away anyway with the results which indicates a successful response by itself.

**Comment by glyn** [comment]
Ok, thanks @dkoper.
