### ISSUE TITLE
Add "run-task" to main cf help page

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cli#1033]
* Running `cf` without arguments

* List of commands did not include new `run-task` command

* CLI Version  cf version 6.23.0+c7866be18-2016-12-22
* CC API Endpoint Version  https://api.run.pivotal.io
* Platform & Shell Details  Mac OS X 10.11.6 iTerm

**Comment by dkoper** [comment]
The main help page is for commonly used commands. Run-task is used by, so far, just you? ;)
I'd like to add it to the main help when we've gotten some feedback on the current functionality.

**Comment by drnic** [comment]
Lol. I think we've all been waiting on "run-task" for many years. Isn't that primarily why we replaced the old runtime with Diego? :)







On Fri, Dec 23, 2016 at 7:50 AM +1000, "Dies Koper" <notifications@github.com> wrote:












The main help page is for commonly used commands. Run-task is used by, so far, just you? ;)

I'd like to add it to the main help when we've gotten some feedback on the current functionality.

**Comment by dkoper** [comment]
Ah was that what that was all about?
In that case, if all those patiently waiting would now massively try tasks out, we'll have this feature request prioritised in no time!

**Comment by dkoper** [comment]
We have implemented this in the cf CLI 6.25.0 release.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM
