### ISSUE TITLE
cf-cli version (version.go) implementation is not SemVer compliant

### ISSUE THREAD

**Issue by svollath** [cloudfoundry/cli#1036]
As statet in the last comment of https://github.com/cloudfoundry/cli/issues/992 already, it's not possible to have a SemVer compliant version for cf-cli reported, that differs from your preset.
This is because the implementation for version is split the wrong way:

cf-cli: [0.0.0+SHA]-[DATE]
SemVer: [0].[0].[0]+[SHA-DATE].[WHATEVER]

So you need to group your build meta-data (SHA-DATE) and optionally append it to the version with a "+", in order to allow e.g. the usage of version only.
See https://github.com/cloudfoundry/cli/issues/992 for more details, please.

**Comment by dkoper** [comment]
Is your point that we have hyphens in our build metadata (e.g. `c7866be-2016-12-22`) while refering to [SemVer point 10](http://semver.org/#spec-item-10), metadata consists of a set of dot separated identifiers?
But identifiers can contain [0-9A-Za-z-] so we have one identifier and no need for dots:
`cf version 6.23.0+c7866be-2016-12-22`
`cf` version `6.23.0`+`c7866be-2016-12-22`

Or are you concerned about the current implementation in version.go?
I'm not sure SemVer was a goal when that file was written, and as the end result looks fine I'm not concerned.
That said, my team is planning to change this stuff, hopefully addressing your request in #992, so this file may change soon.

**Comment by dkoper** [comment]
I believe we have addressed this. Please check it out.
