### ISSUE TITLE
`cf create-app-manifest` does not preserve health-check-type

### ISSUE THREAD

**Issue by crstamps2** [cloudfoundry/cli#1038]
`cf create-app-manifest <app> -p manifest.yml`

When using the create-app-manifest command to copy a manifest of an already pushed app, if `health-check-type` was previously set, it did not carry over into the newly created manifest. This is particularly useful and needed when things like workers are blue-green deployed. 

cf version 6.23.0+c7866be18-2016-12-22

* CC API Endpoint Version  
API version:    2.54.0

**Comment by dkoper** [comment]
Hi @crstamps2 

Thanks for reporting this - I'll discuss with the team when we can implement this.

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
We have implemented this in cf CLI 6.24.0.
https://github.com/cloudfoundry/cli#downloads

Regards,
Dies Koper
CF CLI PM
