### ISSUE TITLE
CF command to list quotas space-wise?

### ISSUE THREAD

**Issue by rajk63411** [cloudfoundry/cli#1039]
High five for submitting a report!  
If you found an issue with the cf CLI, please visit the [releases page](https://github.com/cloudfoundry/cli/releases/) and confirm it's not fixed already in the latest release.  
To avoid additional back and forth, please include the following details as relevant:

* Command  
e.g. `cf push myapp -i 2 --no-route`

* What occurred, incl. error and/or stack trace

* What you expected to occur

* CLI Version  
e.g. 6.13.0-dfba612 (see `cf -v` output)

* CC API Endpoint Version  
see `cf api` output

* CF Trace, if issue relates to HTTP requests or strange behavior  
run the command with `-v` and paste or attach the trace output

* Platform & Shell Details  
e.g. Mac OS X 10.11 iTerm, Windows 8.1 64-bit with PowerShell, Ubuntu 14.04.3 64-bit with gnome-terminal

* Any other relevant information  
e.g. details of an environment, cf CLI version, flag or value it does work with, DNS/network configuration, etc.

**Comment by dkoper** [comment]
Hi @rajk63411 

Not sure I understand your question right.
The `cf space SPACE` command shows the space quota assigned to the specified space. You can loop through your spaces (e.g. with `cf spaces | tail -n +4`) and pass the name of each to `cf space` to retrieve them all.

HTH!
Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Closing as answered.
