### ISSUE TITLE
bind-route-service command

### ISSUE THREAD

**Issue by shik0912** [cloudfoundry/cli#1041]
## Command  
cf bind-route-service [domain.com] [service-name] --hostname [hostname]

## What occurred
Server Error, State Code: 400, Error Code: 130006, Message: This service does not support route binding.

## What you expected to occur
I want to expect that two apps use one service through one route for sharing DB (mysql)

## CLI Version  
cf version 6.20.0+25b1961-2016-07-04

## Platform & Shell Details  
ubuntu 16.04

===============================================================================

I've thought that service migrate command or bind route service.
But, I have to choice brs bcuz service migrate command can't use for cf version.
So, I trying brs command. But I saw the error message.

**Comment by dkoper** [comment]
Hi @shik0912 

It seems you passed in a name of a service that is not a Route Service. This is the case referred to [here](https://docs.cloudfoundry.org/services/route-services.html#catalog): Note that route services are a special type of service.
Detailed documentation is [here](https://docs.cloudfoundry.org/services/route-services.html#introduction).

Regards,
Dies Koper
CF CLI PM
