### ISSUE TITLE
Using curl inside plugin with CF_TRACE=true causes output to be empty

### ISSUE THREAD

**Issue by ojhughes** [cloudfoundry/cli#1043]
## Command  

Inside of a CLI plugin that uses `CliCommandWithoutTerminalOutput("curl", "/v2/apps/[guid]/summary")`

## What occurred
When CF_TRACE=true is set - the response from the curl command is empty.

## What you expected to occur
A response the same as when CF_TRACE is not set

## CLI Version  
6.22.2+a95e24c-2016-10-27

## CC API Endpoint Version  
2.58.0

## CF Trace
REQUEST: [2017-01-04T12:05:11Z]
GET /v2/apps/55df235b-b57a-4503-909b-169bd3435744/summary HTTP/1.1
Host: api.indigo.springapps.io
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.22.2+a95e24c / darwin

RESPONSE: [2017-01-04T12:05:11Z]
HTTP/1.1 200 OK
Connection: close
Content-Length: 2697
Content-Type: application/json;charset=utf-8
Date: Wed, 04 Jan 2017 12:05:11 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 435b3de5-348c-4907-591d-452a1cdfb186
X-Vcap-Request-Id: 435b3de5-348c-4907-591d-452a1cdfb186::d330a7e3-4598-4930-b7e4-a53b1f8342fc

{"guid":"55df235b-b57a-4503-909b-169bd3435744","name":"provision-sr-1","routes":[{"guid":"25636e44-59ac-4235-80c1-f8821898bf82","host":"provision-sr-1-semibelted-caponizer","port":null,"path":"","domain":{"guid":"1113b8e4-2583-445a-96df-47e0efa34b9d","name":"indigo.springapps.io"}}],"running_instances":2,"services":[{"guid":"31b1c4f7-92b1-44af-9034-13bc0ebb2d81","name":"provision-service-registry","bound_app_count":3,"last_operation":{"type":"update","state":"succeeded","description":"","updated_at":"2016-12-22T14:08:14Z","created_at":"2016-12-22T14:06:12Z"},"dashboard_url":"https://spring-cloud-broker.indigo.springapps.io/dashboard/p-service-registry/31b1c4f7-92b1-44af-9034-13bc0ebb2d81","service_plan":{"guid":"a31c7673-f000-459c-9431-51d20dcc03a8","name":"standard","service":{"guid":"d397b927-eff9-4cfd-b5af-2b5ebea3fd29","label":"p-service-registry","provider":null,"version":null}}}],"available_domains":[{"guid":"1113b8e4-2583-445a-96df-47e0efa34b9d","name":"indigo.springapps.io","router_group_guid":null,"router_group_type":null}],"production":false,"space_guid":"c63c23ed-133d-498e-b8bd-52f656c1ed98","stack_guid":"981121cf-8da7-4fdb-9829-5154e2816475","buildpack":null,"detected_buildpack":"java-buildpack=v3.8.1-offline-https://github.com/cloudfoundry/java-buildpack.git#29c79f2 java-main open-jdk-like-jre=1.8.0_91-unlimited-crypto open-jdk-like-memory-calculator=2.0.2_RELEASE spring-auto-reconfiguration=1.10.0_RELEASE","detected_buildpack_guid":"ed0aa64e-2141-4252-a610-de696104036d","environment_json":{"CF_TARGET":"https://api.indigo.springapps.io"},"memory":1024,"instances":2,"disk_quota":1024,"state":"STARTED","version":"81cac07b-0b2f-4eb6-a3ac-6fa7dabca538","command":null,"console":false,"debug":null,"staging_task_id":"a3dcfff9007a4706b5ac7a00fb13be2a","package_state":"STAGED","health_check_type":"port","health_check_timeout":null,"staging_failed_reason":null,"staging_failed_description":null,"diego":true,"docker_image":null,"package_updated_at":"2016-12-09T14:38:39Z","detected_start_command":"CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-2.0.2_RELEASE -memorySizes=metaspace:64m..,stack:228k.. -memoryWeights=heap:65,metaspace:10,native:15,stack:10 -memoryInitials=heap:100%,metaspace:100% -stackThreads=300 -totMemory=$MEMORY_LIMIT) && JAVA_OPTS=\"-Djava.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh $CALCULATED_MEMORY\" && SERVER_PORT=$PORT eval exec $PWD/.java-buildpack/open_jdk_jre/bin/java $JAVA_OPTS -cp $PWD/. org.springframework.boot.loader.JarLauncher","enable_ssh":true,"docker_credentials_json":{"redacted_message":"[PRIVATE DATA HIDDEN]"},"ports":null}
Output from curl command: []
FAILED

## Platform & Shell Details  

macOs 10.12.2

**Comment by dkoper** [comment]
Hi @ojhughes 

Can you check if you may be hitting the 2nd listed [known issue here](https://github.com/cloudfoundry/cli/blob/master/README.md#known-issues)?
In particular, does it work fine when sending API logs to file, or to /dev/stdout?

Cheers,
Dies Koper
CF CLI PM

**Comment by ojhughes** [comment]
Hi @dkoper 

Yes it does fall under the known issue list. 
In this case, I was able to use `GetApps` to retrieve the summary info, and this works fine with `CF_TRACE` enabled.

Many thanks
Ollie Hughes
Pivotal Spring Cloud Services
