### ISSUE TITLE
No Way to Stage an Application Without First Starting it

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cli#1045]
Currently, the only way to stage an application is to attempt to start it at least once.  Doing a `cf push --no-start` is not sufficient to cause staging (which is a good thing!).  In addition, `cf restage` will not restage an application that has not been staged once before.  This was reasonable in a world where there was only a single process type (`web`) that was tied to start.

With the addition of tasks, we now need a way to stage a droplet, but since that code may not start the `web` process type successfully (or may not even have a `web` process type), we need a way to do it without requiring a start of the `web` process type.

A couple of non-binding suggestions are either a `cf stage` command, or expanding `cf restage` so that it works against applications that have not been staged before.

**Comment by dkoper** [comment]
I don't think there is a (non-experimental) API to stage an app? @SocalNick 
`cf restage` returns an error if the app hadn't been staged before because the API call does.

**Comment by SocalNick** [comment]
@nebhale staging without starting can be done with the V3-API, we are beginning our next epic to put these APIs in the hands of the CLI to start developing V3 commands: https://www.pivotaltracker.com/epic/show/3189929

**Comment by dkoper** [comment]
The `v3-stage` command in 6.31.0 calls the V3 API Nick referred to.
