### ISSUE TITLE
`cf help <alias>` should work for commands contributed by plugins

### ISSUE THREAD

**Issue by glyn** [cloudfoundry/cli#1048]
`cf help r` prints the help for `cf routes` since `r` is an alias for the `routes` command.

If a CLI plugin contributes a command with an alias `xxx`, `cf help xxx` fails with:
```
'xxx' is not a registered command. See 'cf help'
``` 
We are developing a plugin with a number of commands which have fairly long, descriptive names (e.g., `service-registry-list`) and short aliases (e.g., `srl`) and it would save some typing and improve usability for users who are familiar with an alias if they were able to get help via the alias (e.g., `cf help srl`).

**Comment by glyn** [comment]
Please note the this is an enhancement (and is labelled as such) so story #137086223 should be a feature rather than a bug (unless the current behaviour is unintentional!).

**Comment by dkoper** [comment]
Hi @glyn 

Thanks for reporting this!
I can't remember whether this was a limitation we defered for later, or we just forgot to test.

Our current command line parser library is statically populated with command info so certain features provided by this library do not work out of the box for plugins (which are discovered dynamically when the CLI process starts).
I'll ask the team to look into it. (and leave it as an enhancement)

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
We have addressed this in the cf CLI 6.25.0 release.
https://github.com/cloudfoundry/cli#downloads

Regards,
Dies Koper
CF CLI PM

**Comment by glyn** [comment]
Thanks @dkoper! I'm really pleased to see this.
