### ISSUE TITLE
Unable to run cf allow-access command

### ISSUE THREAD

**Issue by aerondeepak** [cloudfoundry/cli#1049]
I am trying to use the netman release, executing the [dog-cat](https://github.com/cloudfoundry-incubator/netman-release/tree/develop/src/example-apps/cats-and-dogs) example which required to run cf allow-access command.
I am executing on the latest release of cf-cli v6.23, but its giving a error message "'allow-access' is not a registered command".

Anyone can please help.

Thanks

**Comment by ematpl** [comment]
Hi, @aerondeepak,

You'll need to install the [network policy CLI plugin](https://github.com/cloudfoundry-incubator/netman-release/blob/develop/docs/CLI.md) for those commands. You may want to [raise an issue on the netman-release repo](https://github.com/cloudfoundry-incubator/netman-release/issues/new) to point out that the cats-and-dogs example should be explicit about requiring that CLI plugin to be installed before proceeding, although it is mentioned [in the repo README](https://github.com/cloudfoundry-incubator/netman-release/blob/develop/README.md).

/cc @rusha19 @jaydunk

Best,
Eric

**Comment by aerondeepak** [comment]
Hi @ematpl,
Issue resolved, Thanks.
