### ISSUE TITLE
cfignore including files "!"

### ISSUE THREAD

**Issue by lukaslehmann** [cloudfoundry/cli#105]
At this point it is not possible to do something like this to include some folders on excluded folders :)
application/*
!application/language/

Is it planned to add support for "!" on https://github.com/cloudfoundry/cli/blob/master/src/cf/app_files.go#L153 ?

Thanks and Bests
Lukas

**Comment by mfeltscher** [comment]
Hello everyone

I know that's a very old issue but I stumbled upon it while working with `.cfignore` files. I have a similar use case to the one @lukaslehmann mentioned: I have a directory (A) inside which I want to ignore all subdirectories except one (B):

```
- A
  - B (not ignored)
  - X (ignored)
  - Y (ignored)
  - Z (ignored)
  - ... (ignored)
```

I tried different approaches for `.cfignore` but none of these worked:

```
/A/
!/A/B/
```

```
/A
!/A/B
```

```
/A/**
!/A/B/**
```

```
/A/*
!/A/B/*
```

Could you please tell me what I'm doing wrong?

I might have to mention that this scenario works in `.gitignore` just fine.


Thanks.

**Comment by pks90** [comment]
@mfeltscher , So how did you fix your issue ? I am also facing the same situation in a project .
