### ISSUE TITLE
add password masking when cf login

### ISSUE THREAD

**Issue by boyang9527** [cloudfoundry/cli#1053]
## Command  

cf login

## What occurred

Email> xxx@example.com
Password> 

## What you expected to occur

Email> xxx@example.com
Password> ******

**Comment by dkoper** [comment]
Hi @boyang9527 

I like that suggestion. Let me check with my team if it's possible with the library we use.

Regards,
Dies Koper
CF CLI PM

**Comment by boyang9527** [comment]
thanks @dkoper

**Comment by dkoper** [comment]
Hi @boyang9527 

We decided against doing this for security reasons.
I noticed [`dialog`](https://linux.die.net/man/1/dialog) has an `--insecure` option for this:

```
--insecure
    Makes the password widget friendlier but less secure, by echoing asterisks for each character.
```

I agree at times it's useful to get keypress feedback, but prefer not to add an insecure feature to `cf login`.

Regards,
Dies Koper
CF CLI PM

**Comment by boyang9527** [comment]
@dkoper  that is fine, thanks for your update.
