### ISSUE TITLE
Create-org missing from cf --help

### ISSUE THREAD

**Issue by ahevenor** [cloudfoundry/cli#1055]
## Command  

cf --help

## What occurred

As expected, it gave me a list of commands. But the one I was looking for was missing - `create-org`

## What you expected to occur
I expected it to be in the Org management section

## CLI Version  

cf version 6.22.2+a95e24c-2016-10-27

**Comment by dkoper** [comment]
Hi @ahevenor 

This is intentional. `cf help` only returns the most commonly used commands. Use `cf help -a` to see the full list.

Regards,
Dies Koper
CF CLI PM
