### ISSUE TITLE
cf add-plugin-repo command does not respect URL case specified

### ISSUE THREAD

**Issue by shouah** [cloudfoundry/cli#1058]
## Command  

cf add-plugin-repo [name] [url]

## What occurred

when [url] contains lowercase and uppercase letters in the path, which is required by the repository server, then the command fails to add the repository with this error:

FAILED
[url]/list is not responding. Please make sure it is a valid plugin repo.

We noticed that the "[url]/list" text returned by the error doesn't match the case we specified in the command. A check on the server's access log show the GET request was using all lowercase path which indeed doesn't match any path that the server can serve.

## What you expected to occur

Successfully added the repository using the specified [url] syntax, including lower and uppercase case

## CLI Version  

cf version 6.23.0+c7866be-2016-12-22

## CC API Endpoint Version  

API version:    2.54.0

## CF Trace

executing "cf -v add-plugin-repo [xxx]" or "cf add-plugin-repo -v [xxx]" yields no additional trace.

## Platform & Shell Details  

Windows 7 Enterprise 64-bits

## Any other relevant information  

1. Manually updating the CLI's config.json in the ".cf" home directory with the correct case for the URL allows the CLI to interact with the repository server properly:

 "PluginRepos": [
   {
     "Name": "****",
     "URL": "****correct case here ****"
   }

2. Note that our repository server is case sensitive for the URL so if you need to reproduce the issue, setup one that fails if the case doesn't match exactly.

**Comment by dkoper** [comment]
Hi @shouah 

The CLI is changing the url to lowercase. I'm not sure why, it seems it has been doing so since the command was introduced.
We'll investigate.

Regards,
Dies Koper
CF CLI PM

**Comment by shouah** [comment]
I see the status was changed to 'scheduled' on 1/13/2017. Any idea on the target date or CLI release for the fix?

**Comment by dkoper** [comment]
I scheduled it together with a number of other plugin related improvements and bug fixes. As we're going to expose isolation segments first, I'd say it's 2 months away. Is that too far out for you?

**Comment by shouah** [comment]
Given our low usage rate and the fact that we've identified a hack to workaround the issue then I believe we can wait for another 2 months. I just needed to know for sure that it is being addressed so we can tell our internal CF users that a fix is coming.

**Comment by dkoper** [comment]
Resolved in 6.27.0. Thanks for reporting.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM
