### ISSUE TITLE
`target` should expire state if it fails with `-s` or `-o`

### ISSUE THREAD

**Issue by staylor14** [cloudfoundry/cli#1061]
The `login` command clears your creds and target when it fails. This is an intentional feature to help avert pushes to mistaken targets.

The `target` command should do the same, if and only if `-o` or `-s` are called, for the same reasons.

Currently, `target -s hoped-for-but-unavailable-space` does not invalidate my existing target, `space-i-definitely-don't-want-to-accidentally-delete-apps-in`. I wish it would.

This was seen in cf version 6.23.1+a70deb38f.2017-01-13.

**Comment by dkoper** [comment]
Hi @staylor14 

Not saying that I don't agree, but I wonder how far to go with "clears your target when *fails*":
* For any HTTP/API error?
  * network error
  * proxy setting error
* For any CLI error?
  * org/space not found (API retuns empty array in response with HTTP status 200 )
  * error while parsing JSON response (super rare I hope)
  * parsing error (`cf t -o org -t space` <- expecting to enter space 'space' but typo in flag name)

Any thoughts?

**Comment by dkoper** [comment]
We have implemented this in cf CLI 6.24.0.
https://github.com/cloudfoundry/cli#downloads

Regards,
Dies Koper
CF CLI PM
