### ISSUE TITLE
feature request: `cf whoami`

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry/cli#1063]
As the title suggests

**Comment by dkoper** [comment]
Hi @jadekler 

Your username is returned by every command that interacts with the CF API server, as well as the `cf target` command that tells you as whom you have targetted what and where. Why the need for having its own command?

**Comment by jadekler** [comment]
@dkoper This is a utility request; `cf whoami` is my first thought to figure out who I'm logged into. Myself and another engineer had no thought to use `cf target` - we simply ended up re-logging in in lieu of finding a way to check user.

Secondly, I believe that since the cf cli manages login sessions (from UAA/login server) it is reasonable to expect to be able to behave similarly to how [many linux shells manage login sessions (in this case, providing me a `whoami` command)](http://www.linfo.org/whoami.html).

**Comment by dkoper** [comment]
Thanks for the background. As a Linux user, not too familiar with the `cf` command set, `whoami` was the first thing that came to your mind. Me, as a Windows user, although I just discovered there now is a `whoami` command, I would have never thought of it.

Given that we print current user atop most command feedback, and most users are familiar with the `target` command, it seems overkill to have yet another separate command to return this information.

**Comment by jtuchscherer** [comment]
Just as an FYI, a while ago, I created a whoami cf cli plugin: https://github.com/jtuchscherer/whoami-plugin

**Comment by dkoper** [comment]
Thanks for sharing, @jtuchscherer!
Care to publish it on the CF-Community plugin repository to make it easier for people to find?

**Comment by jtuchscherer** [comment]
@dkoper Just created the PR. 

I haven't published it before, since it is not adding any functionality to the CLI. But if there are a few people out there who might find it helpful...

**Comment by dkoper** [comment]
Thanks @jtuchscherer. Closing this issue.
