### ISSUE TITLE
rolling restart of an app 

### ISSUE THREAD

**Issue by NaveenRajaMarri** [cloudfoundry/cli#1064]
If i have a app with 5 instance ,due to some issue/any other reason i have to do rolling restart .... instead of below method ( running one after the other for 5 times)
cf app-restart-instance 0
cf app-restart-instance 1
cf app-restart-instance 2
cf app-restart-instance 3
cf app-restart-instance 4

 how can i run a command for doing rolling restart by running a command in single line/ only onetime execution?.

**Comment by XenoPhex** [comment]
May I ask why you need to do a rolling restart of your application?

**Comment by NaveenRajaMarri** [comment]
To avoid consumer impact I Prefer to do rolling restart during the case if there is any live traffic ..

**Comment by dkoper** [comment]
@NaveenRajaMarri I suppose the question is, what is the issue that you need to restart all your instances?
Are you changing any environment variables or bindings that need a restart (and no restage) to take affect?

The CC API team (and backend components) are making improvements in this area to make this easier, so we're reluctant to introduce such a feature now before we fully understand what this command will look like once the related V3 APIs are ready for our use.

In the meantime, you can either restart the instances one by one manually (or in a script) with `cf restart-app-instance`) or search for a CLI plugin (e.g. https://github.com/Comcast/cf-recycle-plugin) to do it for you.

Regards,
Dies Koper
CF CLI PM

**Comment by lbeaufort** [comment]
Hi, I came across this issue while researching rolling restarts, so in case anyone comes across it - rolling app restarts were added with [cf cli v7](https://docs.cloudfoundry.org/cf-cli/v7.html). Feel free to remove this comment if you feel it's not helpful.
