### ISSUE TITLE
GetApp_RouteSummary struct does not have a field for context path

### ISSUE THREAD

**Issue by holly-cummins** [cloudfoundry/cli#1066]
We're trying to use the API defined in https://github.com/cloudfoundry/cli/blob/master/plugin/models/get_app.go, which has a Host field and a Domain field.

The docs at https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html says "HTTP routes include a domain, an optional hostname, and an optional context path." It looks like the context field is missing from GetApp_RouteSummary. Is this right? 

(It would also be handy to have a method of initializing a GetApp_RouteSummary from a route string, instead of breaking the route down into its host, domain, and context path parts in our code. Is there an API for this available?). The equivalent internal usage of this function is here: https://github.com/cloudfoundry/cli/blob/14f6dd00ab0332e00cc8da8735d46b731a599ae6/cf/manifest/manifest.go#L500

Thanks!

**Comment by nickwei84** [comment]
Hi @holly-cummins. May I ask how you would use an initializer method for GetApp_RouteSummary? I ask because the cloud controller does not return a route entity as a fully qualified URL in a single string; instead a route is returned broken down into "host", "domain", "path", "port", etc. from the [/v2/apps/_guid/summary endpoint](http://apidocs.cloudfoundry.org/251/apps/get_app_summary.html).

**Comment by holly-cummins** [comment]
Hi @nickwei84 - the use case is parsing a manifest. We don't really want to be in the business of parsing manifests, to be honest, but the CF CLI API for parsing them is internal, so we've switched to only using what's available in the /plugin package (the context for this switch is described in https://github.com/cloudfoundry/cli/issues/1018). The plugin is a blue-green-deploy plugin so it's active before an application is pushed, which is why it has a requirement to understand what's in the manifest.

**Comment by nickwei84** [comment]
@holly-cummins That sounds reasonable. Would you like to submit a pull request for this?

**Comment by dkoper** [comment]
We have added the path, as well as the port, to this API.
https://github.com/cloudfoundry/cli#downloads

Regards,
Dies Koper
CF CLI PM

**Comment by holly-cummins** [comment]
Looks good - thanks so much for the speedy fix.
