### ISSUE TITLE
Feature request: version flag for install-plugin

### ISSUE THREAD

**Issue by dcarley** [cloudfoundry/cli#1067]
We'd like the ability to specify the version of a plugin to be installed, for example:
```
cf install-plugin -r CF-Community -v 1.1.0 blue-green-deploy
```

The reason for this is that we use cf-cli from a container in our build pipelines. The containers are often rebuilt, but we don't want all of the dependencies to automatically upgrade each time. So we pin the versions of significant dependencies (like cf-cli) and review/test them when appropriate.

We can currently achieve what we want by specifying the binary URL directly and not using the plugin repo, but we lose some features like checksum validation and discovery (if the plugin author wants to change the URL).

Depending on the implementation, it looks like [cloudfoundry-incubator/cli-plugin-repo](https://github.com/cloudfoundry-incubator/cli-plugin-repo) may need extending to report more than a single version of a plugin.

**Comment by dkoper** [comment]
Hi @dcarley 

I remember reading an (old) feature request conversation recently on allowing multiple versions of a plugin in the cli-plugin-repo. From you findings I understand it was never implemented.

I understand your use case, and the UX looks reasonable and low-impact.
Let's see how many other users chime in here to help us schedule such work.

Regards,
Dies Koper
CF CLI PM

**Comment by dcarley** [comment]
> I remember reading an (old) feature request conversation recently on allowing multiple versions of a plugin in the cli-plugin-repo. From you findings I understand it was never implemented.

Ah, yes. I overlooked that: cloudfoundry-incubator/cli-plugin-repo#31

> Let's see how many other users chime in here to help us schedule such work.

That sounds good. As I said, we have something for the timebeing, so it's not urgent. Thanks.

**Comment by XenoPhex** [comment]
Hi @dcarley we are closing this issue because we are unable to access previous versions of plugins. We only keep track of latest. We would have to add a lot of infrastructure, as well as require the plugin developers to keep track of previous plugins.

Let us know if you have any feedback/questions by reopening or creating a new issue.
