### ISSUE TITLE
Health check type http with endpoint with spring boot application

### ISSUE THREAD

**Issue by rauizab** [cloudfoundry/cli#1068]
## Command  
cf set-health-check providersapi http --endpoint /-system/health
cf restage appName

## What occurred
The health check is still happening on port

## What you expected to occur
I expect that when spring boot health check, listening in /-system/health, reports "DOWN" and sends a 503 the instance is recreated

## CLI Version  
cf version 6.24.0+c7a32d3.2017-02-10

## CC API Endpoint Version  
2.74.0

## CF Trace

[health.txt](https://github.com/cloudfoundry/cli/files/774457/health.txt)

## Platform & Shell Details  
Centos 7

## Any other relevant information  
On bosh-lite vagrant image

**Comment by dkoper** [comment]
@zrob Trace shows CC returning the health check type http and endpoint set correctly. Any ideas?

**Comment by zrob** [comment]
@rauizab I am unable to reproduce this. do you have a sample app that I can try to recreate this behavior with?

**Comment by rauizab** [comment]
Hi

We are trying to deploy to aws. If I can not reproduce in amazon I will close the ticket.

**Comment by rauizab** [comment]
Hi
In amazon deployment it works as expected. I must have deployed an older version in my bosh-lite.

**Comment by dkoper** [comment]
@rauizab Thanks for getting back to us about it!
