### ISSUE TITLE
FAILED Error read/writing config:  unexpected end of JSON input

### ISSUE THREAD

**Issue by thestevenbell** [cloudfoundry/cli#1071]
## Command  

` cf `  

## What occurred
Attempts to use the utility fail.  Does not accept any command, even ` cf ` with no params.  Gives the following error:
` FAILED
Error read/writing config:  unexpected end of JSON input `

## What you expected to occur
standard output from call to cf cli app
## CLI Version  
6.24

## CC API Endpoint Version  
not applicable

## CF Trace
not given

## Platform & Shell Details  
bash terminal, Sierra 10.12.3, MacBookPro 2016

## Any other relevant information  
I have been trying to use Python scripting to interact with the CLI.  Tried various inputs to the cli using the pexpect module.  CLI was working normally before attempting to programmatically login.  did a full uninstall via homebrew.  Still not working after a fresh install.

**Comment by thestevenbell** [comment]
Ok, so I figured out a solution. The .cf/config.json file was empty.  I added ` {} ` to it.  The ran $ ` cf ` .  The cli acted as normal and repopulated the config.json file.

**Comment by dkoper** [comment]
Do you have any idea what the last thing was you did before it stopped working? What could have broken the file? Is it possible you executed `cf` concurrently from different shells?

**Comment by thestevenbell** [comment]
It is very likely that there were multiple shell instances attempting a cf login at the same time.  I was working out how to interact with the utility through Pythons pexpect module.

**Comment by dkoper** [comment]
Ah. So that's not supported, set CF_HOME to different locations when invoking it concurrently.
We will try to address this issue, or at least reduce the likelihood of the config file getting corrupted and `cf` not being able to recover from it.

**Comment by thestevenbell** [comment]
Thank you.

**Comment by pbleuse-orange** [comment]
Hello,

I have got this error on Windows 7 64bit + cf-cli 6.25+
Resolve it by create CF_HOME environment var

**Comment by dkoper** [comment]
We have greatly reduced the changes of config.json corrupting in cf CLI 6.29.1.
Thank you for providing details to help us pinpoint the issue.

Regards,
Dies Koper
CF CLI PM

**Comment by muly** [comment]
this error happened to me just recently. the `.cf/config.json` was empty. I added `{}`, and restarted to fix the error. Thanks @thestevenbell for the workaround.
```
cf version
cf version 6.27.0+d26b32d.2017-06-08
```

**Comment by ramanaleon** [comment]
Hi Everyone,

I am using CF Version 6.27. I had the similar issue while performing CF Login
**Error read/writing config:  unexpected end of JSON input**

This is the setup we have done:-

We have one Generic account in linux which is used to cater the Cloud Foundry calls. A Batch scheduling tool is used with that account and performs CF Login.

Because there are multiple users who tries to login ( with different process each but access same config file) and my guess is the .cf/config,json is unable to cope the load because there are simultaneous parallel calls being made.

Could someone please assist here.

Regards,
Venkat

**Comment by Rhea222** [comment]
Tried deleting config.js file, but still getting the error ←[31;1mFAILED←[0m
Error read/writing config:  unexpected end of JSON input
Can you'll help resolve it.
