### ISSUE TITLE
Executing `cf ssh` over `CliConnection.CliCommand` mixes `stdout` and `stderr`

### ISSUE THREAD

**Issue by michele-mancioppi** [cloudfoundry/cli#1074]
When executing `cf ssh my_app -c '>&2 echo Ciao'`, "Ciao" is printed correctly to `stderr`.

When executing `cliConnection.CliCommand("ssh", "my_app", "-c", ">&2 echo Ciao")`, "Ciao" is printed to `stdout`, which makes it fundamentally impossible to write good wrappers around `cf ssh` for non-trivial commands.

**Comment by dkoper** [comment]
Hi @michele-mancioppi 

I hear from my anchor that architecturally the plugin code dumps everything it captures in stdout and stderr, it does not separate the two, and it would be a bit of work to separate stderr and stdout. And that could potentially be a breaking change for existing plugins.
We'd like to improve the plugin architecture after the command refactor. I'll keep an eye out on this issue and see if we cover it then or can address it sooner.

Regards,
Dies Koper
CF CLI PM

**Comment by michele-mancioppi** [comment]
Hi @dkoper,

Thanks for the answer. Do you have a timeline about the command refactoring? Could you also please keep  #1069 in mind for the refactoring? Is there anything I could have a look at about refactoring ideas & directions?

Best,
Michele

**Comment by dkoper** [comment]
Here's a link to the epic for command refactoring: https://www.pivotaltracker.com/epic/show/3307969, , it's huge so will take a long time.
`cf ssh` came originally from a plugin. It may be most efficient for now to include ssh functionality in your own plugin and massage it for your needs.

**Comment by dkoper** [comment]
Hi @michele-mancioppi,

We did an exploration around the behaviour you mentioned in this issue, and our findings do not match what you wrote. Can you take a look at the comments in https://www.pivotaltracker.com/story/show/141913339 and compare with your understanding?

Cheers,
Dies Koper
CF CLI PM

**Comment by michele-mancioppi** [comment]
I will run the tests again when I am back from vacations and update the issue accordingly. Cheers.

**Comment by michele-mancioppi** [comment]
Sorry, issue was between keyboard and chair :-)

It is indeed the case that the `stderr` output of a plugin goes to the `stderr` of the enveloping `cf [my_plugin] ...` command, uncaught by the plugin itself.
