### ISSUE TITLE
Not an issue - Does CLI support cfpush by getting an artifact(jar/war) from a repo like artifactory? For example, ```cf push sample-app -p https://artifactory.com/com/sample/app/sample-app.jar -b <build-pack url>``` instead of ```cf push -p ./build/sample-app.jar -b <build-pack url>```

### ISSUE THREAD

**Issue by rguruju** [cloudfoundry/cli#1075]

**Comment by dkoper** [comment]
No.
You can do `wget https://artifactory.com/com/sample/app/sample-app.jar && cf push sample-app -p sample-app.jar -b <build-pack url>` to achieve the same thing with only a few more keystrokes.

Regards,
Dies Koper
CF CLI PM

**Comment by rguruju** [comment]
Yeah, thats exactly what I am doing right now, but I am looking for a
solution where I can directly push the artifact to cloud from artifactory.
Thank you.

Ratnasri

**Comment by dkoper** [comment]
Sure!
