### ISSUE TITLE
panic report

### ISSUE THREAD

**Issue by zrob** [cloudfoundry/cli#1077]
Command
		cf p dora

		CLI Version
		6.24.0+c7a32d3a7.2017-02-10

		Error
		runtime error: index out of range

		Stack Trace
			goroutine 1 [running]:
	code.cloudfoundry.org/cli/util/panichandler.HandlePanic()
		/Users/worker/concourse/containers/00000trlk2d/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/util/panichandler/handler.go:19 +0xb5
	panic(0x78fd40, 0xc420010140)
		/usr/local/Cellar/go/1.7.5/libexec/src/runtime/panic.go:458 +0x243
	code.cloudfoundry.org/cli/cf/api/appinstances.CloudControllerAppInstancesRepository.updateInstancesWithStats(0x1a67590, 0xc420297740, 0x1a67880, 0xc42011ab00, 0x90ff58, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, ...)
		/Users/worker/concourse/containers/00000trlk2d/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/cf/api/appinstances/app_instances.go:103 +0x596
	code.cloudfoundry.org/cli/cf/api/appinstances.CloudControllerAppInstancesRepository.GetInstances(0x1a67590, 0xc420297740, 0x1a67880, 0xc42011ab00, 0x90ff58, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, ...)
		/Users/worker/concourse/containers/00000trlk2d/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/cf/api/appinstances/app_instances.go:77 +0x43e
	code.cloudfoundry.org/cli/cf/api/appinstances.(*CloudControllerAppInstancesRepository).GetInstances(0xc42053a3c0, 0xc420280510, 0x24, 0x0, 0xc4205c8600, 0x90d88e, 0xc41fff03f9, 0x0)
		<autogenerated>:1 +0x9e
	code.cloudfoundry.org/cli/cf/commands/application.Start.fetchInstanceCount(0xc59ac0, 0xc420297700, 0x1a67590, 0xc420297740, 0x1c179d0, 0xc42016e1c0, 0x0, 0x0, 0xc586c0, 0xc42053a280, ...)
		/Users/worker/concourse/containers/00000trlk2d/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/cf/commands/application/start.go:409 +0xf1
	code.cloudfoundry.org/cli/cf/commands/application.(*Start).waitForOneRunningInstance(0xc4202c7cb0, 0xc420280510, 0x24, 0xc4203ef3e0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
		/Users/worker/concourse/containers/00000trlk2d/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/cf/commands/application/start.go:371 +0xc5
	code.cloudfoundry.org/cli/cf/commands/application.(*Start).WatchStaging(0xc4202c7cb0, 0xc420589260, 0x24, 0xc420217dc0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
		/Users/worker/concourse/containers/00000trlk2d/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/cf/commands/application/start.go:194 +0x369
	code.cloudfoundry.org/cli/cf/commands/application.(*Start).ApplicationStart(0xc4202c7cb0, 0xc420589260, 0x24, 0xc420217dc0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
		/Users/worker/concourse/containers/00000trlk2d/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/cf/commands/application/start.go:157 +0x15a
	code.cloudfoundry.org/cli/cf/commands/application.(*Push).restart(0xc42026d560, 0xc420589260, 0x24, 0xc420217dc0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
		/Users/worker/concourse/containers/00000trlk2d/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/cf/commands/application/push.go:582 +0x3cb
	code.cloudfoundry.org/cli/cf/commands/application.(*Push).Execute(0xc42026d560, 0xc5a200, 0xc4204de0c0, 0xc5a200, 0xc4204de0c0)
		/Users/worker/concourse/containers/00000trlk2d/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/cf/commands/application/push.go:319 +0x1037
	code.cloudfoundry.org/cli/cf/cmd.Main(0x0, 0x0, 0xc42000c1b0, 0x3, 0x3)
		/Users/worker/concourse/containers/00000trlk2d/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/cf/cmd/cmd.go:120 +0xd02
	code.cloudfoundry.org/cli/command/v2.PushCommand.Execute(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
		/Users/worker/concourse/containers/00000trlk2d/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/command/v2/push_command.go:42 +0x76
	code.cloudfoundry.org/cli/command/v2.(*PushCommand).Execute(0xd48b28, 0xc420164bc0, 0x1, 0x2, 0xc420297600, 0x0)
		<autogenerated>:167 +0xb1
	main.executionWrapper(0x1c12878, 0xd48b28, 0xc420164bc0, 0x1, 0x2, 0x0, 0x0)
		/Users/worker/concourse/containers/00000trlk2d/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/main.go:161 +0x254
	code.cloudfoundry.org/cli/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc4201dbf20, 0xc42000c1c0, 0x2, 0x2, 0x5, 0x5, 0xc420225d58, 0x45fee, 0xc42036f660)
		/Users/worker/concourse/containers/00000trlk2d/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/vendor/github.com/jessevdk/go-flags/parser.go:314 +0x89f
	main.parse(0xc42000c1c0, 0x2, 0x2)
		/Users/worker/concourse/containers/00000trlk2d/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/main.go:35 +0xba
	main.main()
		/Users/worker/concourse/containers/00000trlk2d/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/main.go:29 +0x86

	goroutine 17 [syscall, locked to thread]:
	runtime.goexit()
		/usr/local/Cellar/go/1.7.5/libexec/src/runtime/asm_amd64.s:2086 +0x1

	goroutine 5 [syscall]:
	os/signal.signal_recv(0x0)
		/usr/local/Cellar/go/1.7.5/libexec/src/runtime/sigqueue.go:116 +0x157
	os/signal.loop()
		/usr/local/Cellar/go/1.7.5/libexec/src/os/signal/signal_unix.go:22 +0x22
	created by os/signal.init.1
		/usr/local/Cellar/go/1.7.5/libexec/src/os/signal/signal_unix.go:28 +0x41

	goroutine 1358 [chan receive]:
	code.cloudfoundry.org/cli/cf/api/logs.(*NoaaLogsRepository).TailLogsFor.func3(0xc420201180, 0xc420532000, 0xc4201cfe60)
		/Users/worker/concourse/containers/00000trlk2d/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/cf/api/logs/noaa_logs_repository.go:117 +0x67
	created by code.cloudfoundry.org/cli/cf/api/logs.(*NoaaLogsRepository).TailLogsFor
		/Users/worker/concourse/containers/00000trlk2d/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/cf/api/logs/noaa_logs_repository.go:120 +0x2ec

		Your Platform Details
                Mac OS X 10.12

		Shell
		iTerm

**Comment by dkoper** [comment]
Thanks for the report.
It looks the same as #1050. @nickwei84 can confirm.
If so, it's addressed in the refactored code, but that will not show up in a release until `push` is completely refactored.

**Comment by zrob** [comment]
cool, feel free to close if you're satisfied it has been addressed

**Comment by nickwei84** [comment]
@zrob @dkoper 
This is the same panic that was encountered in #1050.
