### ISSUE TITLE
cf push myapp --random-route does not create a random route

### ISSUE THREAD

**Issue by TimGerlach** [cloudfoundry/cli#1078]
I am pushing an app that has a manifest.yml declaring hostname _my-app_. When calling ``cf push`` I use ``--random-route`` to create an ad-hoc route for testing purposes. The cli, however, seems to ignore the ``--random-route`` flag.

## Command  

`cf push myapp-dev --random-route`

## What occurred
```
$ cf push myapp-dev --random-route
Using manifest file /Users/d060497/Documents/dev/myapp/manifest.yml

Creating app myapp-dev in org playground / space production as d060497...
OK

Using route myapp.cfapps.<...>.com
Binding myapp.cfapps.<...>.com to myapp...
FAILED
The route myapp.cfapps.<...>.com is already in use.
TIP: Change the hostname with -n HOSTNAME or use --random-route to generate a new route and then push again.

```
## What you expected to occur

Use a random route.

## CLI Version  

``cf version 6.24.0+c7a32d3a7.2017-02-10``

## Platform & Shell Details  

MacOS Sierra

**Comment by dkoper** [comment]
Hi @TimGerlach 

I can reproduce this with an app in my manifest with "host" attribute set. Neither the "random-route: true" attribute nor the `--random-route` flag seem to override it.
Trying some older CLI releases (6.16.0), it seems this has never worked!

It does however work for me when the app's route in the app manifest is set using the "route" attribute:
```
  routes:
  - route: myapp.cfapps.<...>.com
```

Can you try that?

Cheers,
Dies Koper
CF CLI PM

**Comment by TimGerlach** [comment]
Hi @dkoper 

You're right, omitting the ``host`` attribute in the manifest and using ``routes`` instead it generates a random route as expected. Thanks for that!

I think it'd make sense, though, that ``--random-route`` should override ``host`` as it is part of the route creation. When using ``host`` and ``random-route: true`` simultaneously it should raise an error as it already happens when you use ``host`` and ``routes`` at the same time.

What do you think?

Cheers,
Tim

**Comment by dkoper** [comment]
Hi Tim,

I think the `--random-route` option was originally introduced to make it easier to push simple sample apps without domain or host settings, like in a classroom setting where the same app is presented to all students. In this case the host would default to the app's name, so after the first person in the classroom pushed the app, all other students would see an error that the route was already in use.
The option changed what the hostname defaults to, making it unique. Hence it doesn't override app manifest attributes.

We don't do any validation of entries in the app manifest, like checking whether the attributes together makes sense. I'm not sure why. But I don't want to introduce that now, potentially breaking existing app manifests.
Generally, app manifests are used by experienced users automating an existing workflow, so they would confirm their app manifest would work the same way as the manual workflow so there is no strong need for advanced validation.

We introduced the "routes" attribute in the app manifest to address limitations with the host and domain attributes. At this time I thought it would be useful to be able to override the routes, also for TCP routes, in case you for example receive someone else's app manifest and want to use it in your environment, where certain domains and hosts are or are not available. So `--random-route` is supported here.

Although the suggestion from the current error message is confusing, I prefer not to spend too much effort on the "host" app manifes attribute, as I prefer recommending people to move to using the "route" attributes.

**Comment by TimGerlach** [comment]
Hi Dies,

thanks so much for your comprehensive answer.

Actually, according to the [documentation](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#routes) there is some entry validation happening already, which is good. 

I can understand, that you don't want to change behavior for the moment. Also, knowing that you see the `host` property slowly being superseded, we'll start to replace it, too. I'd suggest, however, to add a small remark in the [`random-route` docs](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#random-route) that it's not supported in conjunction with `host` but works well with `routes`. This would have saved me some time :-)

If you agree I'll file a PR to the docs.

Cheers,
Tim

**Comment by dkoper** [comment]
Yes, an update to the docs would be nice. Please do so, or let me know if you want me to do it.

**Comment by dkoper** [comment]
Closing as fixed: the docs have been updated (just need a bit more fine-tuning). Thanks again for raising this issue!
