### ISSUE TITLE
cf push with Bash on Ubuntu on Windows 10 500 error

### ISSUE THREAD

**Issue by kimpellikaan** [cloudfoundry/cli#1079]
## Command  
cf push <APP_NAME> -b <CUSTOM_BUILDPACK> -p <PACKAGE>

## What occurred
After the app is updated the uploading stage starts. After uploading 258.9k there is no more progress. 

## What you expected to occur
When I execute the same command on my Mac with the same env, user, etc it works fine.

## CLI Version  
cf version 6.24.0+c7a32d3.2017-02-10

## CC API Endpoint Version  
https://api.eu-gb.bluemix.net

## CF Trace
```
Uploading app files from: /tmp/unzipped-app845507490
Uploading 40M, 1565 files

REQUEST: [2017-02-24T22:12:06+01:00]
PUT /v2/apps/10703120-3abc-4de8-b70e-a7a09aee6867/bits?async=true HTTP/1.1
Host: api.eu-gb.bluemix.net
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: multipart/form-data; boundary=f44d9e57d6a6a2935da51ab54d157c0aea24a457b2f49becc411d44ba468
User-Agent: go-cli 6.24.0+c7a32d3.2017-02-10 / linux


[MULTIPART/FORM-DATA CONTENT HIDDEN]
258.9K uploaded...
RESPONSE: [2017-02-24T22:14:09+01:00]
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Type: text/xml; charset="utf-8"
X-Backside-Transport: FAIL FAIL

500 Error: Network error
FAILED
Error processing app files: Error uploading application.
Server error, status code: 500, error code: 0, message:
```

## Platform & Shell Details  
Windows 10 64-bit with Bash on Ubuntu (Subprocess)

**Comment by dkoper** [comment]
The trace shows the backend encountered an error. I don't see anything wrong with the API request.
Can you ask the platform operator for more information?

**Comment by dkoper** [comment]
FYI, I installed Bash on Windows 10 Home and ran `cf p dummy --no-start --no-route -b staticfile_buildpack` and that completed fine.

**Comment by dkoper** [comment]
Closing. It's working fine for me and the trace seems to indicate a server side problem.
Feel free to re-open or submit a new issue if you can provide any more information that indicates there is a CLI issue we can investigate.

**Comment by kimpellikaan** [comment]
@dkoper I was not able to reply faster. I found that I am also unable to `git push`. So clearly this seems to be a network issue on my end. 

I will post my solution once I got it.

**Comment by kimpellikaan** [comment]
It seems that the issues is caused by the networking setup which is not completely implemented in the current stable build (14393). In the insider builds it's supposed to be fixed, https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14965. So right now you can wait or run on insider builds.

**Comment by mrudolphi88** [comment]
@kimpellikaan Have you found a solution to this?

**Comment by kimpellikaan** [comment]
@mrudolphi88, please read my previous comment.

**Comment by mrudolphi88** [comment]
Yep, I just downloaded the insider build, and it corrected it. Just didn't know if there was any other route before doing that. Thanks.

**Comment by dkoper** [comment]
@kimpellikaan @mrudolphi88 Thanks for sharing all of this!
