### ISSUE TITLE
Feature request: show consequences of deleting an org

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/cli#1082]
At the moment, it's easy to accidentally delete private domains by deleting the org that owns them--operators intuitively except that deleting an org will delete its spaces and apps, but forget that deleting an org deletes associated domains. I'm making this claim because this has happened on my team a few times in the last few months alone 😓.

It would be helpful for the confirmation prompt for `cf delete-org` to be more explicit about what's going to be deleted, for example: "This will delete the private domains foo.com, baz.com". Even changing the current "delete the org and everything associated with it" to "delete the org and its associated spaces, apps, services, private domains, ..." would be more clear.

**Comment by wslack** [comment]
Seconding @jmcarp, I think because private domains are so much "less managed" than spaces/apps, it can be easy to miss that they are there. A reminder/cue would be very helpful given the user behavior I've observed. Thank y'all!

**Comment by brittag** [comment]
Related suggestion: the `cf delete-shared-domain` command should warn when there are existing routes, and request confirmation for deleting them before actually performing the deletion. Like `cf delete-org`, it's easy for operators to incorrectly predict the effect of `cf delete-shared-domain` - [see this explanation of 18F site downtime from December for an example](https://cloudgov.statuspage.io/incidents/y6fng1dk47rt).

**Comment by dkoper** [comment]
@brittag About `cf delete-shared-domain`, it currently displays:
```
D:\Users\koperd\Downloads\bin>cf delete-shared-domain my-domain.com
Deleting domain mydomain.com as admin...

This domain is shared across all orgs.
Deleting it will remove all associated routes, and will make any app with this domain unreachable.
Are you sure you want to delete the domain mydomain.com? >
```

It already warns about removing existing routes and asks confirmation?

**Comment by wslack** [comment]
@dkoper I am not sure that's entirely clear. I would suggest changing the language to:

`This action impacts all orgs using this domain. Deleting it will remove associated routes and make any app with this domain, in any org, unreachable.
Are you sure you want to delete the domain mydomain.com?`

**Comment by brittag** [comment]
Could `cf delete-shared-domain` list the associated routes as well?

`This action impacts all orgs using this domain. Deleting it will remove associated routes and make any app with this domain, in any org, unreachable. (Routes to be deleted: x.example.com, y.example.com, z.example.com) Are you sure you want to delete the domain mydomain.com?`

**Comment by dkoper** [comment]
I'd like to squeeze in a message improvement now as listing impacted resources requires more development & testing work that will have to compete with other feature work and issues.

About @wslack's message, apps can have multiple routes so deleting one doesn't necessarily make all apps inaccessible. Such a message would be worrying when you're trying to change your apps from one domain to another and just added new routes to your apps. OK if I add "could"?

```
This action impacts all orgs using this domain. Deleting it will remove associated routes and could 
make any app with this domain, in any org, unreachable. Are you sure you want to delete the 
domain mydomain.com?
```

**Comment by dkoper** [comment]
And for `delete-org`, would (for now) the following do?
```
Really delete the org myorg, incl. its spaces, apps, services, routes and private domains? [yN]:
```

**Comment by mogul** [comment]
I notice this issue was mentioned in the release notes for [v6.26.0](https://github.com/cloudfoundry/cli/releases/tag/v6.26.0)!

> - `delete-org` and `delete-shared-domain` now display in more detail what else gets deleted in their confirmation messages. (#1082)

First of all: Huzzah! 
Second: Should we be closing this issue?

**Comment by dkoper** [comment]
@mogul I'm fine with closing it if you are.
I left it open as we only did the "quick" solution of improving the static message of what other (type of) resources would be deleted (see my comment above), and not actually producing a full list of resource names. Which would be a lot more work on this command.

**Comment by XenoPhex** [comment]
Closing this issue as complete as the CLI now warns users with a more verbose output when deleting an org `Really delete the org banana, including its spaces, apps, service instances, routes, private domains and space-scoped service brokers? `.

Please feel free to open a new issue if you have comments/feedback. Thanks.
