### ISSUE TITLE
Add support for --ca-cert flag for self-signed CC certs

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/cli#1084]
As CloudFoundry gets more and more security focused, it would be great to stop skipping SSL verification in many of our CI environments. While it looks like we could add a custom CA cert into containers in CI at runtime ([doc](https://docs.cloudfoundry.org/cf-cli/self-signed.html)), it would be much nicer to have a `--ca-cert` flag or similar that allows us to point to a given cert.

Thanks!

Lyle && Tim - CF CAPI team

**Comment by dkoper** [comment]
Hi @ljfranklin 

I've been exploring this feature in https://www.pivotaltracker.com/story/show/139887077.
One of the issues with implementing this, and we have some high-priority stories preventing us from exploring this deeper, is that our current (pre-refactor) code does not easily let us pass a cert to the HTTP libraries.
Also, we'll need the noaa library to support this too.

About the UX, would it really be nice to have to specify such a flag on each and every cf CLI command? As opposed to e.g. a config or `cf api` option to set it once?

Cheers,
Dies Koper
CF CLI PM

**Comment by ematpl** [comment]
Makes sense to me for `cf api` and other target-setting commands (maybe only `cf login`?) to take an optional `--ca-cert` flag and to store the supplied certificate data in the config state file. That's also similar to how the `alias-env` command on the [new BOSH CLI](https://github.com/cloudfoundry/bosh-cli) stores that per-environment state in the BOSH CLI config file. For example, aliasing the Diego team's "ketchup" environment:

```
$ bosh alias-env ketchup -e bosh.ketchup.cf-app.com --ca-cert ~/workspace/deployments-diego/ketchup/certs/bosh-ca.crt

$ cat ~/.bosh/config
environments:
- url: https://bosh.ketchup.cf-app.com
  ca_cert: |
    -----BEGIN CERTIFICATE-----
    MIIDEzCCAfugAwIBAgIQSpmPYKB/QxdZcA/GT8v0zzANBgkqhkiG9w0BAQsFADAz
    MQwwCgYDVQQGEwNVU0ExFjAUBgNVBAoTDUNsb3VkIEZvdW5kcnkxCzAJBgNVBAMT
    AmNhMB4XDTE3MDEyMDIyMjAwMFoXDTE4MDEyMDIyMjAwMFowMzEMMAoGA1UEBhMD
    VVNBMRYwFAYDVQQKEw1DbG91ZCBGb3VuZHJ5MQswCQYDVQQDEwJjYTCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBAPGlVN5SJZiOoppIpJRtiQH2oi8rU7/G
    kw0NH3UUDAiZgwKA1MsqeGt9o/7g/DJQcYnPp5Awe9cQoYcO2cUiazpMqQAiyZcQ
    uQV8ULOIBYjiDP59x7ukHOE0IBOSeAJZRRzegLGbGOWn4k/pR+5Ox8fPL7GZIiuO
    bA2g2/qIx72cw263SHWzVpSwwc7Ny8mWbLXX9BadrFocLzY5sG1YLx4m4djVNnwH
    C9nYB15SLNjqWhmfpJQmQVX9JQnZR7n59XoRMOL4TaSRUHCYspX3tlWlA1X4bCwx
    dc7YJsiMEbBHUGwu+mayPFkUEB6/zNt9rm+SU/b8nVPG6cCcQwpNK8MCAwEAAaMj
    MCEwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQEL
    BQADggEBAJMnAxZza2JYjZoa7i0+9/CkZKdKurJ1XXaITR6Jm3BTCAq+K/G/5sA6
    FCKRje00laeTHhxyi8mk87miK41DN/rTsAnW/yVM18YxyTr1uYi1OR2chbOSfEAs
    5Y+DenXNghz3so4trmtWFvnJ6dZhbwzygBjxvXLukgJ5EWRhLcTgFVDJ2SB3PhIv
    MADI4LUIAf38Ij79xGOIJOvDbsGAvBtL8HnHHEMtSsvC7ats8JrrBTD1ZQQnkDKK
    XoCWMnqUU6Lxfvvd2AZLTzNgE7if6hrCM6jARt2tuayM1P7vnnECxbiXiDBMVltY
    Ev62WIlDEvwdP4vWn4cLlvNiROcmX1A=
    -----END CERTIFICATE-----
  alias: ketchup
```

Another convenient feature of the `--ca-cert` flag on `alias-env` is that it will accept either a path to a file containing PEM-encoded certificate data or that same certificate data inline as an argument, so that one can do something like `bosh alias-env --ca-cert "$(bosh interpolate creds.yml --path /director_ssl/ca)"` to alias an environment with the CA certificate pulled from the deployment credential store (or some other YAML file).

Thanks,
Eric

**Comment by dkoper** [comment]
Thanks for chiming in @ematpl, great feedback.

@cppforlife How does the Bosh CLI store the aliased cert data? In a separate pem file?
Having it in a `curl` compatible format would make it easier for people debugging network issues to use `curl` with the same cert file.

Also, I would assume people would want to use this feature for any cf CLI  endpoint, i.e. also for self-hosted plugin repos. Hence `cf` commands should trust this ca cert in addition to the system truststore. Not sure if `curl` and the Bosh cli work that way?

**Comment by drnic** [comment]
@dkoper the bosh cli data is stored in the same ~/.bosh/config yaml config file with the other alias info

**Comment by dkoper** [comment]
Thanks @drnic. And do you happen to know whether the bosh cli still uses the system truststore in addition to the aliased cert data, or only the aliased cert data (when set)?

**Comment by ljfranklin** [comment]
Adding on to this, we've had several users in the CAPI slack get bitten by SSL errors when CC talks to a broker. A `cf create-service-broker --ca-cert` or similar would be helpful (probably requires work on CAPI side as well though).

**Comment by dkoper** [comment]
@ljfranklin @drnic @ematpl @cppforlife
I've put together a proposal, please take a look:
https://docs.google.com/document/d/1Hacd-akn6Wy6qswY1mXAGlwlHHfMnJQIcjijpKi7o4c/edit?usp=sharing

**Comment by ematpl** [comment]
Thanks, @dkoper, sounds good to me! I piled onto the flag-name bike-shed with a preference for `--ca-cert`.

**Comment by menicosia** [comment]
+1 for this functionality. I didn't add this to the doc, but note that it's nice when the certificate supplied can be either a string or a filename.

**Comment by dkoper** [comment]
Note that cf CLI 6.31.0 was built with Golang 1.9 which added `SSL_CERT_FILE` and `SSL_CERT_PATH` support on Unix systems.
```
diesk@cloud-cf:~/workspace/cf-deployment$ export SSL_CERT_FILE=~/workspace/cf-deployment/ca.pem
diesk@cloud-cf:~/workspace/cf-deployment$ cf api api.bosh-lite.com
Setting api endpoint to api.bosh-lite.com...
OK

api endpoint:   https://api.bosh-lite.com
api version:    2.85.0
Not logged in. Use 'cf login' to log in.
```

**Comment by drnic** [comment]
Awesome!

**Comment by dkoper** [comment]
We've added this to the docs: https://docs.cloudfoundry.org/cf-cli/self-signed.html#linux.
