### ISSUE TITLE
update-buildpack error when passed a url

### ISSUE THREAD

**Issue by gokeefe** [cloudfoundry/cli#1085]
## Command  

    cf update-buildpack java_buildpack_offline -p https://github.com/cloudfoundry/java-buildpack/releases/download/v3.14/java-buildpack-offline-v3.14.zip

## What occurred

    Incorrect Usage: The specified path 'https://github.com/cloudfoundry/java-buildpack/releases/download/v3.14/java-buildpack-offline-v3.14.zip' does not exist.

## What you expected to occur

    Updating buildpack java_buildpack_offline...

## CLI Version  

    cf version 6.25.0+787326d.2017-02-28

## CC API Endpoint Version  

    API endpoint:   https://api.x.x.x.com
    API version:    2.58.0

## CF Trace

N/A, argument parsing error so no trace is generated.

## Platform & Shell Details  

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 16.04.2 LTS
    Release:        16.04
    Codename:       xenial

    $ bash --version
    GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu)

## Any other relevant information  

cf update-buildpack works as expected using previous cf cli version 6.24 in Windows

**Comment by dkoper** [comment]
Thanks, I see what went wrong here. We'll resolve this soon.

**Comment by dkoper** [comment]
Fixed in the 6.26.0 release. Thanks again for reporting!
https://github.com/cloudfoundry/cli#downloads

Regards,
Dies Koper
CF CLI PM
