### ISSUE TITLE
Help text does not say a password is required when setting up a user with an external origin

### ISSUE THREAD

**Issue by henrytk** [cloudfoundry/cli#1087]
## Command  

```
cf create-user henry@example.com --origin google
```

## What occurred

```
Error Code: 400
Raw Response: {"error_description":"Password must be at least 8 characters in length.","error":"invalid_password","message":"Password must be at least 8 characters in length."}
FAILED
```

## What you expected to occur

A user to be created, because the `cf create-user -h` output says:

```
USAGE:
   cf create-user USERNAME PASSWORD
   cf create-user USERNAME --origin ORIGIN

EXAMPLES:
   cf create-user j.smith@example.com S3cr3t                  # internal user
   cf create-user j.smith@example.com --origin ldap           # LDAP user
   cf create-user j.smith@example.com --origin provider-alias # SAML or OpenID Connect federated user
```

which doesn't say anything about having to supply a password, but when I supply a password as the second argument it works.

## CLI Version  

cf version 6.23.0+c7866be18-2016-12-2

## Platform & Shell Details  

Mac OSX 10.11.6

**Comment by dkoper** [comment]
Hi @henrytk 

I thought the password should not be mandatory, as you are creating a user on CF that is already existing in the origin. UAA team will investigate. Thanks for bringing this up.

Regards,
Dies Koper
CF CLI PM

**Comment by henrytk** [comment]
I am closing this as I have done some investigation and raised a new issue: https://github.com/cloudfoundry/cli/issues/1092

It appears to be the request being sent to UAA is wrong. Please see the issue for full details.
