### ISSUE TITLE
cf cli fails if the first dns from /etc/resolv.conf is not responding

### ISSUE THREAD

**Issue by giner** [cloudfoundry/cli#1089]
## Command  
```
cf api api.mydomain.net
```
## What occurred

```
Setting api endpoint to api.mydomain.net...
Request error: Get https://api.mydomain.net/v2/info: dial tcp: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
FAILED
```

## What you expected to occur

Should not fail

## CLI Version  
```
$ cf -v
cf version 6.25.0+787326d.2017-02-28
```

## Platform & Shell Details  
Linux

## Any other relevant information
In order to reproduce the issue just add non-existent IP as a first nameserver to /etc/resolv.conf
Switching to `GODEBUG=netdns=cgo` does not help.

Default for `CF_DIAL_TIMEOUT` is defined as 5 seconds and default DNS timeout (for both libc and golang resolvers) is also 5 seconds. This results in failure when the first dns server is not responding or the response can't be processed. What about changing `CF_DIAL_TIMEOUT` to 15 seconds to make sure that the second and the third DNS servers work as a fall-back?

**Comment by dkoper** [comment]
Hi @giner 

Feel free to tune `CF_DIAL_TIMEOUT`'s value to your circumstances.
The issue with changing its default value, is that it affects everybody. There can be various reasons for network issues causing a timeout. For example, take a user who is sometimes behind an HTTP proxy and sometimes not (like using the same laptop in the office and at home). Forgetting to update their proxy settings can cause a network timeout. We retry twice in case of a network error as with some network glitches a retry fixes it), so it takes the CLI 5s x 3 is 15 sec to display a timeout. Increasing the default timeout to 15 sec, which may benefit your situation, causes a 45 second wait for others.
So any value change improves the situation for some, but makes it worse for others. So to prevent any unpleasant surprises, I think it's better to leave it unchanged.

Regards,
Dies Koper
CF CLI PM

**Comment by giner** [comment]
I would agree if cli was returning clear message that it was dns server failure. In that case we know what to do right away. Current situation is that when it happens it takes quite a while to understand the issue is related to DNS.

Even increasing it to 6 seconds would improve situation for the most common case.

**Comment by giner** [comment]
At the same time increasing timeout would be just a work around. What about splitting looking up and dialing? In such a case we would be able to:
- set 15 seconds timeout for DNS resolution
- keep 5 seconds timeout for Dial
- receive a more explicit error message in case of DNS failure, something like:
```
Mar 12 11:29:34 api.domain.net [] lookup api.domain.net on 15.15.15.15:53: read udp 100.10.10.10:55386->15.15.15.15:53: i/o timeout
```

**Comment by jaresty** [comment]
We've also seen this come up a lot, especially when running the CLI on IaaSs and similar cloud platforms, which often have their own special DNS issues.

A default of 6 seconds would radically improve the experience of lots of mid-grade users without costing many other users _too_ much time.

Alternatively, _shortening_ the timeout to 4 seconds would prevent a race. This would make the whole thing less infuriating and mysterious, as it would at least fail consistently.

Key to making this latter alternative work, of course, would be a better error message and a useful tip about setting the timeout environment variable.

**Comment by dkoper** [comment]
@giner 
I thought the current Dial timeout we are configuring is already the smallest in scope, referring to [this illustration](https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/#clienttimeouts). How can we separate it into domain resolution and establishing TCP connection?

Also, not sure how we're retrieving the current "dial tcp: i/o timeout" (on my Windows box I have seen `dial tcp <IPv4 address>:443: i/o timeout`), but what API are you getting that DNS failure message from?

**Comment by giner** [comment]
> How can we separate it into domain resolution and establishing TCP connection?

What about overriding http transport, similar to what they do on the link https://github.com/viki-org/dnscache/blob/master/readme.md ?

> Also, not sure how we're retrieving the current "dial tcp: i/o timeout" (on my Windows box I have seen dial tcp <IPv4 address>:443: i/o timeout), but what API are you getting that DNS failure message from?

With CF_DIAL_TIMEOUT set to low value it cuts "Dial" itself before it exits with DNS error. To see DNS error returned from DIal you can increase CF_DIAL_TIMEOUT to something big, so that Dial is not cut by timeout:
```
$ echo nameserver 15.15.15.15 | sudo tee /etc/resolv.conf
$ time CF_DIAL_TIMEOUT=300 cf api my.api.net
Setting api endpoint to my.api.net...
FAILED
Error performing request: Get https://my.api.net/v2/info: dial tcp: lookup my.api.net on 15.15.15.15:53: read udp 100.73.4.228:43271->15.15.15.15:53: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

real    0m30.217s
user    0m0.120s
sys     0m0.088s
```

**Comment by giner** [comment]
friendly ping

**Comment by CAFxX** [comment]
I fear this depends on https://github.com/golang/go/issues/12503 being implemented and merged. Unfortunately the go1.9 ship has almost sailed, so I guess this won't be possible before go1.10 (6+ months)

**Comment by abbyachau** [comment]
Thanks for all these comments and pings. We'll review whether changing the time out to `6s` might be a good path forward and on the dependencies that were mentioned in this thread. Thanks.

**Comment by ericpromislow** [comment]
Thank you everybody for the contributions to these investigations. 

We resolved to increase the timeout from 5s to 6s to avoid the race condition between the DNS and GoLang timeouts. 

This has been fixed in https://github.com/cloudfoundry/cli/commit/a759ff73817898fc0e02839b7697f7cdaceb42a7 and will be available in the next release. 

Eric and @bwasmith
