### ISSUE TITLE
User provided service -p option or Bind route service -c option - unable to get the information.

### ISSUE THREAD

**Issue by pktippa** [cloudfoundry/cli#1091]
I have created two applications in cloud foundry

1. Actual application "node-consist-app" with business logic.
2. Application "cf-node-route-service" which routes request to application (1)
 
The second application is used as user provided service and binds it as route service to application one.

## Command  
> cf cups cf-node-route-service -p '{"username": "user", "password": "pass", "domain": "run.pivotal.io"}' -r https://cf-node-route-service.cfapps.io
> cf brs cfapps.io cf-node-route-service --hostname node-consist-app -c '{"hashalgorithm": "md5"}'

## What occurred
User defined service got created and i am able to see the credential parameters in the PWS console UI -> Service -> User provided Service -> Configuration. This is good.

## What you expected to occur
As per the documentation the credentials are available as environment variables, but i am not able to get any of the credential parameters in either of two applications. Please help.
## CLI Version  

cf version 6.23.1+a70deb3.2017-01-13
## CC API Endpoint Version  
API endpoint:   https://api.run.pivotal.io
API version:    2.75.0

## Platform & Shell Details  
Ubuntu 14.04.3 64-bit with gnome-terminal

**Comment by shalako** [comment]
Hello @pktippa 
Could you describe what it is you'd like to accomplish? We can then suggest the best way to solve your problem.

If you look at the help file for the `create-user-provided-service` command, you'll see that the `-p` option is used when binding the service instance to an application. As route services are bound to routes, the options you've provided with `-p` are not being used. 

```
   -p      Credentials, provided inline or in a file, to be exposed in the VCAP_SERVICES environment variable for bound applications
```

Otherwise, the commands you have executed will cause requests for `node-consist-app.cfapps.io` to be proxied to `https://cf-node-route-service.cfapps.io`. It is expected that the app `cf-node-route-service` will execute some processing on the request and optionally forward the request to `http://node-consist-app.cfapps.io` if it passes some condition. The responsibilities of your route service app are described in [Route Services - Service Instance Responsibilities](http://docs.cloudfoundry.org/services/route-services.html#service-instance-responsibilities); as you are using `cf cups` instead of a brokered service, you can ignore the bits about the broker returning `route_service_url`. In your case this url is configured with `cf cups`.

**Comment by pktippa** [comment]
I want some credentials to be sent into the user defined service while creating it and use it in the service. The workaround i am following now as for my case, since the user defined service is also an application in PWS I am setting the environment variables using `cf set-env`. Even after binding the application to the user defined service, I am not able to see the information sent via `-p` option for `cf cups` or `-c` option for `cf brs` in the VCAP_SERVICES environment variable in the bounded application.

**Comment by shalako** [comment]
If you would like to use a user-provided service instance to make credentials available to an app instead of using `cf set-env`:
 
```
cf cups my-upsi -p '{"username": "user", "password": "pass"}'
cf bind-service my-app my-upsi
```

**Comment by dkoper** [comment]
@pktippa 
Can you provide your full CLI output? It's working for me:
```
D:\>cf bs jsp cup -c "{\"permissions\":\"read-only\"}"
Binding service cup to app jsp in org test / space test as admin...
OK
TIP: Use 'cf restage jsp' to ensure your env variable changes take effect

D:\>cf restart jsp
Stopping app jsp in org test / space test as admin...
OK

Starting app jsp in org test / space test as admin...

0 of 1 instances running, 1 starting
1 of 1 instances running

App started


OK

App jsp was started using this command `CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator
-2.0.2_RELEASE -memorySizes=metaspace:64m..,stack:228k.. -memoryWeights=heap:65,metaspace:10,native:15,stack:10 -memoryInitials=he
ap:100%,metaspace:100% -stackThreads=300 -totMemory=$MEMORY_LIMIT) &&  JAVA_HOME=$PWD/.java-buildpack/open_jdk_jre JAVA_OPTS="-Dja
va.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh $CALCULATED_MEMORY -Djavax.net.ssl.t
rustStore=$PWD/.java-buildpack/container_certificate_trust_store/truststore.jks -Djavax.net.ssl.trustStorePassword=java-buildpack-
trust-store-password -Djava.endorsed.dirs=$PWD/.java-buildpack/tomcat/endorsed -Daccess.logging.enabled=false -Dhttp.port=$PORT" e
xec $PWD/.java-buildpack/tomcat/bin/catalina.sh run`

Showing health and status for app jsp in org test / space test as admin...
OK

requested state: started
instances: 1/1
usage: 256M x 1 instances
urls:
last uploaded: Tue May 16 02:28:01 UTC 2017
stack: cflinuxfs2
buildpack: container-certificate-trust-store=2.1.0_RELEASE java-buildpack=v3.15-https://github.com/cloudfoundry/java-buildpack.git
#a3a9e61 open-jdk-like-jre=1.8.0_131 open-jdk-like-memory-calculator=2.0.2_RELEASE tomcat-access-logging-support=2.5.0_RELEASE tom
cat...

     state     since                    cpu    memory          disk           details
#0   running   2017-05-16 05:21:50 PM   0.0%   90.1M of 256M   130.6M of 1G

D:\Users\koperd\Downloads\bin>cf env jsp
Getting env variables for app jsp in org test / space test as admin...
OK

System-Provided:
{
 "VCAP_SERVICES": {
  "user-provided": [
   {
    "credentials": {
     "password": "pa55woRD",
     "username": "admin"
    },
    "label": "user-provided",
    "name": "cup",
    "syslog_drain_url": "",
    "tags": [],
    "volume_mounts": []
   }
  ]
 }
}
...
```

**Comment by pktippa** [comment]
@dkoper thanks for taking time to look into issue, I have moved on to docker from cf, my current work is not getting delayed because of this, so I am closing this issue.
