### ISSUE TITLE
Cannot create users with external authentication without supplying a password

### ISSUE THREAD

**Issue by henrytk** [cloudfoundry/cli#1092]
## Command  

```
cf create-user henry@example.com --origin google
```

## What occurred

```
Error Code: 400
Raw Response: {"error_description":"Password must be at least 8 characters in length.","error":"invalid_password","message":"Password must be at least 8 characters in length."}
FAILED
```

## What you expected to occur

A user to be created.

## Investigation

This appears to be an issue with the CF CLI passing an empty JSON string as a password, instead of omitting the password field entirely from the request. Using `curl` you can demonstrate this. The following command creates a user (externally authenticated with Google) successfully:

```
curl -k 'https://<REDACTED>/Users' -i -X POST -H 'Accept: application/json' -H "Authorization: $BEARER" -H 'Content-Type: application/json' -d '{
  "externalId" : "henry@example.com",
  "meta" : {
    "version" : 0,
    "created" : "2017-02-28T23:54:48.604Z"
  },
  "userName" : "henry@example.com",
  "name" : {
    "formatted" : "given name family name",
    "familyName" : "family name",
    "givenName" : "given name"
  },
  "emails" : [ {
    "value" : "henry@example.com",
    "primary" : true
  } ],
  "phoneNumbers" : [ {
    "value" : "5555555555"
  } ],
  "active" : true,
  "verified" : true,
  "origin" : "google",
  "schemas" : [ "urn:scim:schemas:core:1.0" ]
}'
```

Note the origin field is set to 'google' and the password field is omitted. The success of the above request confirms you can create an externally authenticated user without a password, despite the fact the [UAA API documentation](https://docs.cloudfoundry.org/api/uaa/#create64) says it is a required field.

The following command, however, doesn't work:

```
curl -k 'https://<REDACTED>/Users' -i -X POST -H 'Accept: application/json' -H "Authorization: $BEARER" -H 'Content-Type: application/json' -d '{
  "externalId" : "henry@example.com",
  "meta" : {
    "version" : 0,
    "created" : "2017-02-28T23:54:48.604Z"
  },
  "userName" : "henry@example.com",
  "name" : {
    "formatted" : "given name family name",
    "familyName" : "family name",
    "givenName" : "given name"
  },
  "emails" : [ {
    "value" : "henry@example.com",
    "primary" : true
  } ],
  "phoneNumbers" : [ {
    "value" : "5555555555"
  } ],
  "active" : true,
  "verified" : true,
  "origin" : "google",
  "password": "",
  "schemas" : [ "urn:scim:schemas:core:1.0" ]
}'
```

It produces the same error when using the CF CLI command stated above:

```
Error Code: 400
Raw Response: {"error_description":"Password must be at least 8 characters in length.","error":"invalid_password","message":"Password must be at least 8 characters in length."}
FAILED
```

This investigation seems to imply the CF CLI is sending an empty JSON string, instead of stripping the `password` field from the request.

## CLI Version  

cf version 6.23.0+c7866be18-2016-12-2

## Platform & Shell Details  

Mac OSX 10.11.6

**Comment by dkoper** [comment]
@sreetummidi CLI trace seems to indicate we are indeed sending the mandatory "password" field. What should we be sending?

```
D:\Users\koperd\Downloads\bin>cf create-user me@example.com --origin google -v
...
POST /Users HTTP/1.1
...
User-Agent: cf/6.25.0+929952c.2017-03-08 (go1.7.5; amd64 windows)
{
...
  "origin": "google",
  "password": "[PRIVATE DATA HIDDEN]",
  "userName": "me@example.com"
}
```

**Comment by sreetummidi** [comment]
@dkoper The password should be required only when the origin is UAA.
We will investigate further

**Comment by dkoper** [comment]
@sreetummidi Do you have a UAA tracker story we can follow?

**Comment by sreetummidi** [comment]
Yes, https://www.pivotaltracker.com/story/show/141419737
The fix will be part of UAA 4.0

Thanks,
Sree Tummidi
Staff Product Manager
Identity - Pivotal Cloud Foundry

**Comment by henrytk** [comment]
@dkoper any update on what CF CLI version will include the fix? Thanks.

**Comment by dkoper** [comment]
@henrytk It is my understanding that the issue was on the UAA side, not CLI side. Are you still seeing this with UAA 4.0?

**Comment by henrytk** [comment]
@dkoper ah okay, so you intend to continue sending an empty string when passwords aren't required. That's fine, disregard my last comment.

**Comment by dkoper** [comment]
Well, docs still say it's a required field, so I don't see how we have a choice.

**Comment by dkoper** [comment]
Closed as there is nothing to do on our side. Feel free to re-open if the issue persists with UAA 4.0 and more investigation is required on our side.
