### ISSUE TITLE
Bug in cf-cli: " Something unexpected happened."

### ISSUE THREAD

**Issue by megaboy2** [cloudfoundry/cli#1093]
## Command  

cf app app-name

## What occurred

Stack Trace
        goroutine 1 [running]:
        code.cloudfoundry.org/cli/utils/panichandler.generateBacktrace(0xc042044180, 0x3)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/utils/panichandler/handler.go:68 &#43;0xa4
        code.cloudfoundry.org/cli/utils/panichandler.HandlePanic()
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/utils/panichandler/handler.go:54 &#43;0x33a
        panic(0xb7bf20, 0xc042004070)
                /usr/local/go/src/runtime/panic.go:458 &#43;0x251
        code.cloudfoundry.org/cli/cf/api/appinstances.CloudControllerAppInstancesRepository.updateInstancesWithStats(0x3db4eb0, 0xc0421391d0, 0x3db5170, 0xc0420751e0, 0xcf5238, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, ...)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/api/appinstances/app_instances.go:103 &#43;0x59d
        code.cloudfoundry.org/cli/cf/api/appinstances.CloudControllerAppInstancesRepository.GetInstances(0x3db4eb0, 0xc0421391d0, 0x3db5170, 0xc0420751e0, 0xcf5238, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, ...)
                /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/cf/api/appinstances/ap

## What you expected to occur
I created a while true loop with the above command to be executed. Then i got this problem.

## CLI Version  

6.22.2&#43;a95e24c

## CC API Endpoint Version  

API version: 2.74.0

## Platform & Shell Details  

Windows 8.1 64-bit

**Comment by dkoper** [comment]
This looks like the same issue reported in #1050. We have a fix in our code, will be part of our upcoming release.
