### ISSUE TITLE
cf m is not workinig in a proxy environment

### ISSUE THREAD

**Issue by verystrongjoe** [cloudfoundry/cli#1095]
## Command  

cf m

## What occurred

It didn't bring services in the marketplace for long time without printing.

## What you expected to occur

I want to get available services in the marketplace.

## CLI Version  

6.25.0+787326d95.2017-02-28, 

## CC API Endpoint Version  

2.54.0

## CF Trace

I added the parameter -v as the guide

## Platform & Shell Details  

Mac OS X 10.11.2 iTerm

## Any other relevant information  

I have a proxy in my company. I tried adding environmental variables and giving some parameters but i failed to solve this.

**Comment by dkoper** [comment]
Hi @verystrongjoe 

I'm behind a corporate proxy and it's working fine for me. Actually, I'm behind an NTLM proxy so I have a local proxy [cntlm](http://cntlm.sourceforge.net/) installed.
Please provide more details, such as your full terminal output and CF trace output.

```
D:\Users\koperd\Downloads\bin>set https_proxy
https_proxy=http://localhost:3128

D:\Users\koperd\Downloads\bin>cf m
Getting services from marketplace in org dies-test / space development as dies...
OK

service                       plans                                                                                description
3scale                        free_appdirect, basic_appdirect*                                                     API Management
Platform
app-autoscaler                standard                                                                             Scales bound ap
plications in response to load (beta)
...
```

**Comment by dkoper** [comment]
Closing as we have not enough details to investigate.
