### ISSUE TITLE
tab completion of paths no longer works for cf install-plugin

### ISSUE THREAD

**Issue by zrob** [cloudfoundry/cli#1099]
`cf install-plugin ~/Do [tab]` no longer completes paths

± zr |develop {3} U:2 ?:2 ✗| → cf -v
cf version 6.25.0+787326d95.2017-02-28

**Comment by dkoper** [comment]
By handling tab completion ourselves we lost bash' built-in tab completion.
We implemented path completion for most commands, but not this one.
Also, our path completion doesn't support tilde expansion. I have an exploration in the icebox to look into that.
Will look at addressing both.

**Comment by dkoper** [comment]
Resolved in 6.27.0. Thanks for reporting.
https://github.com/cloudfoundry/cli#downloads
