### ISSUE TITLE
include vcap request id in the error message

### ISSUE THREAD

**Issue by youreddy** [cloudfoundry/cli#1101]
it would be helpful to include request id or some other identifying information eg request url? headers?) for debugging problems like below. we dont know which component is returning following error.

```
Setting api endpoint to https://xxx.com...
Error Code: 502
Raw Response: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
```

adding CF_TRACE=true unfortunately isnt useful because we may not be able to repro this problem.

cc @cppforlife

**Comment by dkoper** [comment]
@youreddy I believe we're doing this already, but only for refactored commands. `cf api` is, `cf login` is not.
What command were you using?

**Comment by youreddy** [comment]
@dkoper this was setting the endpoint, so `cf api`

**Comment by dkoper** [comment]
Thanks, we'll investigate!

**Comment by mmb** [comment]
@youreddy Was this deployed on GCP? This looks like an error from the GCP load balancer.

If that's the case it never makes it to cloud controller so there is no VCAP request id.

**Comment by dkoper** [comment]
Closing. If the Cloud Controller is indeed returning a request id, we should be displaying it. From the information you have provided, it seems the response did not come from the Cloud Controller.
