### ISSUE TITLE
Request: Support for environment variables in `cf login`

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/cli#1102]
It would be convenient for CI and local development if the CF CLI could detect environment variables like `CF_ADMIN_USERNAME` and `CF_ADMIN_PASSWORD` during `cf login` rather than having to enter them into the terminal as flags or in a prompt.

**Comment by dkoper** [comment]
The recommended, more secure way for CI environments would be to use long-lived tokens (see #919).
We are exploring environment variables to provide credentials for private docker registries. We can learn from that.

**Comment by dkoper** [comment]
The feedback I received from both UAA PM and the Security team is to not support this.
We expect to add support to authenticate with a (non-user) service account. This may not be exactly what you're looking for, but would help people who find this story looking for how to authenticate in CI scripts.
