### ISSUE TITLE
Replace instead of add property

### ISSUE THREAD

**Issue by JohannesAtGit** [cloudfoundry/cli#1103]
## Command  
`cf push`
Change value of e.g. host or services in manifest.yml
`cf push`

## What occurred
The url is not replaced, but rather there are now two urls for my app now.
Same with services.

Is this behavior really intended?

## What you expected to occur
I expect that the values are replaced and not added.

## CLI Version  
`cf --version
cf version 6.25.0+787326d.2017-02-28`

## CC API Endpoint Version  
API version:    2.75.0

## Platform & Shell Details  
Ubuntu 16.10

**Comment by dkoper** [comment]
Hi @JohannesAtGit 

Changes to "collections" (routes, environment variables, service bindings, ...) are additive.

Regards,
Dies Koper
CF CLI PM

**Comment by JohannesAtGit** [comment]
Ok thank you for your quick response.
Frankly speaking, I don't like this behavior and it is also not documented. At least after skimming the documentation.

Is there a parameter for `push` to replace instead of add?
Or do I have to delete the app before pushing the app again?

**Comment by dkoper** [comment]
There is currently no parameter. The idea of introducing declarative app manifests has come up (18 months ago) but other more important things have always come up.
App manifests in their current form are useful to keep settings that don't change often with your source code.
If your app is undergoing bigger changes, you can use commands like `cf unmap-route`, `cf unset-env` and `cf unbind-service` to explicitly remove the links to resources it no longer needs.

**Comment by JohannesAtGit** [comment]
Thanks. For me the issue is resolved maybe you would like to convert this issue into an enhancement request.
Kind regards.
Johannes
