### ISSUE TITLE
Request: cf run-task --wait

### ISSUE THREAD

**Issue by gajwani** [cloudfoundry/cli#1104]
## Request:
AS a user of the CF CLI,
GIVEN that I have run a task
THEN the CLI waits for the task to complete

## Proposed API
`cf run-task <APP_NAME> <COMMAND> --wait`

Since the CLI already polls in other cases, and also is able to talk to the API to get the app/task status, it seems reasonable that polling for it's status and telling a user about completeness would be desirable.

/cc @tjgrathwell

**Comment by gajwani** [comment]
@mpivotal We were told you might also have some thoughts about this.

**Comment by dkoper** [comment]
We considered this when exposing tasks and decided to wait and let people try it out as is to see what direction to take with this feature. So thanks for submitting the issue!

I understand it's not uncommon for tasks to take a long time (their default timeout I believe is something like 48hrs for that reason), so an alternative considered was to "attach" the terminal to the task, like an ssh session as Heroku does. That requires feature work on Diego and CC, so curious to know whether @zrob and @ematpl already have something on their roadmap.

**Comment by tjgrathwell** [comment]
Attaching to the task would be ideal if streamed the output as it happened.

In our polling implementation, we do a `cf logs --recent` after the task enters `FINISHED` state and print out the lines that look like they match our task, but we're at the whim of however well `cf logs --recent` feels like treating us. Sometimes that command has even crashed with a mysterious cloud controller error.

But if it takes a significant amount of extra work to do the attach thing, I wouldn't want it hold up a simpler waiting technology. The lack of a wait makes it hard to do simple things like run a series of tasks one after another.

I don't know how much it makes sense to optimize for extremely long running tasks, if I were to do something long running in my application I would probably only use `cf run-task` to feed something into a worker queue.

**Comment by aeijdenberg** [comment]
In case it's helpful, we wrote an experimental CLI plug-in called `run-and-wait` to do some of this, ie start the task, poll it, exit with 0 or 1 depending on success or failure. We're beginning to use this in some of our CI tasks:

<https://github.com/govau/cf-run-and-wait>

**Comment by oppegard** [comment]
We (Tracker team) would appreciate something like this as well for use in automation/CI scenarios. It'd be even better if there were a `--logs` option in addition to `--wait`, so that logs would be streamed to stdout until the task either succeeds or fails.

**Comment by kelapure** [comment]
This story is critical and needed; in the interim we wrote a workaround for it here https://gist.github.com/kelapure/ef79419796e35a68629a4e772e4646e4

**Comment by abbyachau** [comment]
Thanks for all the comments. I've marked this issue as contributions-welcome. We hope to support this flag but unfortunately will not be able to get to this in the near term.

**Comment by heyjcollins** [comment]
We'll be adding this to the v7 CLI. Thanks @zrob for the PR (Please follow progress on #1861).
As such, I'm going to close this issue.

**Comment by mohan519** [comment]
Is this available now ? according to the documentation, there is no mention of this --wait switch: https://cli.cloudfoundry.org/en-US/v6/run-task.html

**Comment by mohan519** [comment]
Is this switch available now ? there was no mention of this in the documentation: https://cli.cloudfoundry.org/en-US/v7/run-task.html

**Comment by sunglim** [comment]
"--wait" is available cf CLI versoin 8.
