### ISSUE TITLE
`cf restage` fails with unrelated error when authentication has expired

### ISSUE THREAD

**Issue by kylegearhart** [cloudfoundry/cli#1105]
## Command  

```
$ cf restage our-app
Restaging app  in org our-org / space our-space as us@pivotal.io...
Warning: error tailing logs
Timed out waiting for connection to Loggregator (wss://doppler.run.pivotal.io:443).
```

## What occurred

We immediately asked for recent logs, and got the good old expired auth failure message:

```
$ cf logs our-app --recent
FAILED
Authentication has expired.  Please log back in to re-authenticate.
```

## What you expected to occur

We would have expected to see the auth expired error message when running the `restage` command.

## CLI Version  

cf version 6.23.1+a70deb38f.2017-01-13

## CC API Endpoint Version  

API endpoint:   https://api.run.pivotal.io
API version:    2.75.0

## Platform & Shell Details  

Mac OS X 10.12.3 
iTerm2

**Comment by dkoper** [comment]
Apologies - I failed to update this issue.
Thank you for your report! We fixed this in cf CLI 6.29.0. You should now see:
```
D:\>cf restage testapp
Restaging app testapp in org dies-test / space dev as admin...
The token expired, was revoked, or the token ID is incorrect. Please log back in to re-authenticate.
FAILED
```

Regards,
Dies Koper
CF CLI PM
