### ISSUE TITLE
cf delete does not provide correct prompt

### ISSUE THREAD

**Issue by sreenivasmrpivot** [cloudfoundry/cli#1109]
## Command  
cf delete myapp

## What occurred
Returns "Really delete the app myapp?>" in the command prompt.

## What you expected to occur
It does not say if the user should type "y" or "yes" and then hit enter.

**Comment by dkoper** [comment]
It never has. It's a simple yes/no question though, I have never heard of people confused before?

We are refactoring our commands and using another library for displaying the prompts. Once `cf delete` has been refactored, it will include `[yN]`. (You can already see that in refactored commands like `cf delete-org`.)

**Comment by dkoper** [comment]
Closing as I believe my comment above addresses the point raised.
