### ISSUE TITLE
cf help does not include uninstall-plugin in list of subcommands

### ISSUE THREAD

**Issue by jenspinney** [cloudfoundry/cli#1111]
## Command  

`cf help`

## What occurred

The following output shows up related to plugins:
```
CLI plugin management:
  plugins           add-plugin-repo      repo-plugins
  install-plugin    list-plugin-repos
```

## What you expected to occur

Include the `uninstall-plugin` subcommand in the help output.

## CLI Version  

6.25.0+787326d95.2017-02-28

Thanks,
@jenspinney and @ScarletTanager

**Comment by dkoper** [comment]
It's under `ch help -a`: `cf help` only lists commonly used app developer commands, and people tend to install plugins more often than uninstalling them. (Especially once we allow install-plugin to update a plugin).
