### ISSUE TITLE
Support forced password expiry

### ISSUE THREAD

**Issue by dcarley** [cloudfoundry/cli#1112]
## Command  

`cf login` after a user's password has been forced to expire in UAA: https://docs.cloudfoundry.org/api/uaa/#force-user-password-to-expire

I suspect the same happens when a user's password has an expiry time set, but I haven't tested that because we don't use the functionality.

## What occurred

I was told that my credentials were incorrect and prompted to try again:
```
Authenticating...
Credentials were rejected, please try again.

Password>
```

## What you expected to occur

The CLI should parse the `error_description` from the body, tell me that my password has expired, and prompt me to set a new password.

It seems that this may not be supported by UAA yet: cloudfoundry/uaa#584

## CLI Version  

`cf version 6.25.0+787326d95.2017-02-28`

## CC API Endpoint Version  

`API version:    2.75.0`

## CF Trace

```
Authenticating...

REQUEST: [2017-04-04T17:17:36+01:00]
POST /oauth/token HTTP/1.1
Host: REDACTED
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/x-www-form-urlencoded
User-Agent: go-cli 6.25.0+787326d95.2017-02-28 / darwin

grant_type=password&password=[PRIVATE DATA HIDDEN]&scope=&username=REDACTED

RESPONSE: [2017-04-04T17:17:36+01:00]
HTTP/1.1 401 Unauthorized
Connection: close
Transfer-Encoding: chunked
Cache-Control: no-store
Content-Type: application/json;charset=UTF-8
Date: Tue, 04 Apr 2017 16:17:36 GMT
Pragma: no-cache
Server: Apache-Coyote/1.1
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Www-Authenticate: Basic realm="UAA/client", error="unauthorized", error_description="User password needs to be changed"
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block

50
{"error":"unauthorized","error_description":"User password needs to be changed"}
0


Credentials were rejected, please try again.

Password>
```

## Platform & Shell Details  

N/A

## Any other relevant information  

N/A

**Comment by dkoper** [comment]
Hi @dcarley 

I'd like to expose any error descriptions that are meaningful to CLI users, so I have asked the UAA PM to provide a list of possible error descriptions to verify whether we can just display all or whether we need to whitelist the appropriate ones.
https://www.pivotaltracker.com/story/show/121183595

Regards,
Dies Koper
CF CLI PM

**Comment by mjseid** [comment]
👍

**Comment by abbyachau** [comment]
This should be handled once we complete the `cf login` refactor. We'll circle back when that refactor is completed. Thanks.

**Comment by acrmp** [comment]
Hi @dcarley,

As @abbyachau says issue has been resolved by the recent work re-implementing the `cf login` command. This change is currently in the edge binary and we expect it to be in the next released version of the CF CLI.

We followed the following steps to confirm the behaviour:

1. We used the old `uaac` UAA client to require a password change for a specific user:

```
$ uaac curl -k -H 'Content-type: application/json' -H 'Accept: application/json' -X PATCH -d '{"passwordChangeRequired" : true}' /Users/a22aeffe-60d0-440c-a347-949149ee843c/status
```

2. When we attempted to then login as this user we saw the following output:

```
$ cf login -u some-user
API endpoint: https://api.example.com

Password:
Authenticating...
password change required


Password:
```

@abbyachau We noticed that we were re-prompted for the password here, rather than exiting after displaying that message. Not sure if that is the desired behaviour?

Thanks,

@acrmp && @bwasmith

**Comment by abbyachau** [comment]
It's not desired @acrmp, ideally the command exits before we print the `Password`. I'm not sure how much of a priority (since it does not heavily impact the user experience) it is to update this but we can look into how it fits into our current priorities. Thanks.

**Comment by abbyachau** [comment]
@dcarley thanks again for creating this issue, and sorry it took so long to resolve. We are nearly finished with refactoring the `login` command and as Andrew mentions above, we intend to release that work, along with this fix, soon. Although the re-prompting Andrew mentions is not ideal, I'm closing this issue as done and have created a separate [story](https://www.pivotaltracker.com/story/show/168788442) to track the ux for not re-prompting if the password requires a change. Please let us know if you have any questions/feedback. Thanks again.
