### ISSUE TITLE
Incorrect error when binding a route service with a non-existent route

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/cli#1117]
## Command  

cf brs example.com testdb --hostname test

## What occurred

FAILED
Route test not found

## What you expected to occur

FAILED
Route test.example.com not found

## CLI Version  

cf version 6.26.0+9c9a261fd.2017-04-06

## CC API Endpoint Version  

api endpoint:   https://api.local.pcfdev.io
api version:    2.75.0

## Platform & Shell Details  

Mac OS X 10.12.4 Terminal

## Any other relevant information  

An error is expected as the route does not exist, but the wording is incorrect - 'test' isn't a route.

**Comment by dkoper** [comment]
Nice catch!
We'll take a look.

**Comment by heyjcollins** [comment]
With the GA of the v7 CLI, we're no longer actively developing against the v6 line.  With an interest the overall hygiene of the CLI project we're closing this  issue.
If this issue is still occurring in v7 please feel free to comment and re-open. Thank you!
