### ISSUE TITLE
Usage of set-org-role/set-space-role incorrect

### ISSUE THREAD

**Issue by gowrisankar22** [cloudfoundry/cli#1118]
Hi Developers,

Once after the org and space target is set, why should explicitly specify org/space name to set the roles?

Usage currently:(I agree if the the org/space target is not set the current usage pattern is correct)

cf set-org-role USERNAME ORG ROLE

cf set-space-role USERNAME ORG SPACE ROLE

but it should be like this,

cf set-org-role USERNAME ROLE

cf set-space-role USERNAME ROLE

Also if only the org target is set, during the set-space-role ORG not required mention explicitly because we are already into the org.

Usage currently:
cf set-space-role USERNAME ORG SPACE ROLE

but it should be like this,
cf set-space-role USERNAME SPACE ROLE

Thanks and Best Regards,
Gowrisankar

**Comment by dkoper** [comment]
Hi @gowrisankar22 

These commands were introduced to the cf CLI way before any of the current CLI team members were on the team, so I can't say for sure why they were designed this way.
I assume that it is more common for the person who assigns roles to not also be an app developer, so they would likely not have targetted a specific space.
Also, when a new person is created (admin operation), the next tasks would be to assign this new person the right org and space roles for all relevant orgs and spaces. That is less tedious to do with the current UX than if the admin would need to `cf target` the relevant org & space before each role assignment.

Hope that helps!
Regards,
Dies Koper
CF CLI PM
