### ISSUE TITLE
Cannot uninstall sample plugin CliCmd (call_cli_cmd)

### ISSUE THREAD

**Issue by diegovinas** [cloudfoundry/cli#1120]
## Command  

cf uninstall-plugin CliCmd

## What occurred

Uninstalling plugin CliCmd...
panic: runtime error: index out of range

goroutine 865 [running]:
panic(0xbd15c0, 0xc04200c030)
        /usr/local/go/src/runtime/panic.go:500 +0x1af
code.cloudfoundry.org/cli/plugin/rpc.(*CliRpcCmd).CallCoreCommand(0xc04214d200, 0x0, 0x0, 0x0, 0xc042396030, 0x0, 0x0)
        /tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/plugin/rpc/cli_rpc_server.go:179 +0x4f3
reflect.Value.call(0xc04249be00, 0xc04213e048, 0x13, 0xcb85a3, 0x4, 0xc042235ed0, 0x3, 0x3, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:434 +0x5cf
reflect.Value.Call(0xc04249be00, 0xc04213e048, 0x13, 0xc042235ed0, 0x3, 0x3, 0xc0425e6e40, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:302 +0xab
net/rpc.(*service).call(0xc0421eb0c0, 0xc0421eae40, 0xc0423f8030, 0xc0425fe200, 0xc042200c80, 0xb84340, 0xc042203da0, 0x197, 0xb63c40, 0xc042396030, ...)
        /usr/local/go/src/net/rpc/server.go:383 +0x14f
created by net/rpc.(*Server).ServeCodec
        /usr/local/go/src/net/rpc/server.go:477 +0x428
PLUGIN ERROR: Error from CliCommand:  read tcp 127.0.0.1:56984->127.0.0.1:56980: wsarecv: An existing connection was forcibly closed by the remote host.

---------- Command output from the plugin ----------
----------              FIN               -----------

## What you expected to occur

Uninstalling plugin CliCmd...
OK

## CLI Version  

6.25.0+787326d.2017-02-28

## CC API Endpoint Version  

API endpoint:   https://api.run.pivotal.io
API version:    2.78.0

## Platform & Shell Details  
Windows 101 64-bit

**Comment by dkoper** [comment]
Thanks for reporting this. This plugin seems to have never uninstalled well.
We have removed it and updated the documentation to point to the plugin that should work.

Cheers,
Dies Koper
CF CLI PM
