### ISSUE TITLE
Push fails because resource-match times out

### ISSUE THREAD

**Issue by nicregez** [cloudfoundry/cli#1123]
## Command  

cf push

## What occurred

Timeout on `PUT /v2/resource_match`

## What you expected to occur

As a space developer, I want to be able to push my app to Cloud Foundry, even if resource matching takes too long

## CLI Version  

6.23.1

## CC API Endpoint Version  

2.80.0

## CF Trace

Pretty obvious...

## Platform & Shell Details  

Mac OSX

## Any other relevant information  

Suggestions (list not exhaustive, discussed within the CAPI team)

1. Introduce a switch or additional parameter to the push command which allows me to skip resource matching, e.g. `--skip-resource-match`
2. Add a reference to the following article to `cf help push`: https://discuss.pivotal.io/hc/en-us/articles/235994967-Pivotal-Cloud-Foundry-Error-Error-Performing-Request-Put-v2-resource-match-net-http-Request-Canceled-
3. There are currently two environment variables mentioned in `cf help push`: CF_STAGING_TIMEOUT and CF_STARTUP_TIMEOUT. You could also mention CF_DIAL_TIMEOUT, because in a recent case, increasing this value to 20 fixed the problem as well.

**Comment by dkoper** [comment]
I thought we fixed this already in #1042 (which went into 6.23.1). Can you share more details? Full CLI output, details of app that's failing, CF trace..

**Comment by nicregez** [comment]
The resource-match request times out, so there is no HTTP code returned to the CLI...
Trace looks totally as expected until the resource-match request is sent to the CLI and there is no response at all in the trace.

**Comment by dkoper** [comment]
Gotcha, we're only checking for server side timeouts, also need to check for timeouts between CLI and server (fronting LB).

**Comment by nicregez** [comment]
Did you read through our suggestion list? What do you think especially about suggesion number 1?

**Comment by dkoper** [comment]
As a user I want to push my app. If it times out, how does the user make a decision how to proceed? Under what condition would they go like, well if the resource matching doesn't work I won't want to push my app anymore and I'll do something else, vs. I want to push my app regardless so I'll try again with the flag.
I think it'll be the latter in 80-100% of cases, hence feel the CLI should deal with this automatically and not overload the push command with another flag of doubtful  value.
Or am I missing something?

**Comment by nicregez** [comment]
When the CLI times out on resource matching, it currently just silently fails. Running the push command with `-v` does not help in analysing the cause because the request details is displayed, but nothing is written about the response and that it is missing. I would appreciate if you would give the CLI user some guidance in such a situation and maybe even let him circumvent the issue by skipping resource matching.

In my eyes, a useful error message would sound like "The step 'resource-match' failed during the push of your application. Please report this issue to your system administrator using (/v2/info --> support). As a workaround, retry using the switch --skip-resource-match".

**Comment by mastertinner** [comment]
@dkoper, after discussing the suggestions above, what would be the optimal solution from your point of view? As I see it, we either need a flag for the `cf push` command to skip resource matching or the CLI needs to skip it automatically when it times out.

As I understand it, skipping resource matching will only have one implication (from the user's perspective): pushing their app may take a lot longer. Is this assumption correct? If so, the CLI could simply log something like `Resource matching timed out. Skipping it which may result in longer uploading times.` and then skip resource matching for this push.

**Comment by dkoper** [comment]
@mastertinner Right. This is the approach we took in #1123. I believe all we need to do is ensure we do this for TCP timeouts (i.e. when there is no HTTP response code).

**Comment by nicregez** [comment]
@dkoper Thanks for your reply. You are referencing the present issue in your statement above, I guess, you wanted to reference another issue, right? Would you please let us know which other issue you were referring to?

**Comment by dkoper** [comment]
Doh! Fixed: It was #1042.

**Comment by dkoper** [comment]
This is should now be resolved in cf CLI 6.34.0.

Regards,
Dies Koper
CF CLI PM
