### ISSUE TITLE
cf-cli should retry iaas issues

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry/cli#1125]
## Command  

`cf create-space -o boop-smoke-tests loggregator-smoke-tests_20170424T161631UTC_31732`

## What occurred

```
Creating space loggregator-smoke-tests_20170424T161631UTC_31732 in org boop-smoke-tests as smoke-test-admin...
FAILED
Server error, status code: 502, error code: 0, message:
```
## What you expected to occur

I would like the CLI to retry on iaas specific issues. In any software where a connection failure can occur, you'll usually right retry logic. Since the `cf` CLI is the main interface to CC, it makes sense to add it there.

## Other

Created an issue on [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests/issues/200) to see if they can weigh in.

**Comment by dkoper** [comment]
The CLI does retry on various 5xx errors, but there are a number of http status codes for which retry is not recommended (cf. would you like your browser retry three times when submitting a purchase order?).

**Comment by jtarchie** [comment]
@dkoper, I get the example of the purchase order, but we are not worrying about credit card purchases here.

Most of these operations are idempotent, right? I'd like to rely on that behaviour of the CC.

**Comment by dkoper** [comment]
Gotcha: depending on the command, retries may be safe. Currently retry logic is in the api layer - will check with the team the impact of making this command specific.

**Comment by dkoper** [comment]
@jtarchie I have discussed this with the CAPI PM and my anchor and they have advised me against it.

The retry logic in the CLI architecture is around the HTTP call, several layers away from the command layer.
If we were to make retrying dependent on the command, we'd need to pass such indication through those layers. 163 commands x several layers - that is a lot of work.

If we were to make retrying dependent on the API method, there would be less layers to update, but adds complexity if there are APIs that are OK to retry for certain commands, but not for others.
