### ISSUE TITLE
Tab completion for directories adds a space

### ISSUE THREAD

**Issue by ebabani** [cloudfoundry/cli#1126]
## Command  

cf push push-analytics -p push-analytics/targe[TAB]

## What occurred

Autocompleted to 'cf push push-analytics -p push-analytics/target/ '
It auto completed the directory name but added a space after, so autocomplete can't continue with files inside the directory.

## What you expected to occur

Autocomplete to the directory and list files inside it.

## CLI Version  

cf version 6.26.0+9c9a261fd.2017-04-06

## CC API Endpoint Version  

api version:    2.75.0 - pcfdev

## CF Trace

N/A

## Platform & Shell Details  

 Mac OS X 10.12 iTerm

## Any other relevant information  

none

**Comment by dkoper** [comment]
Hi @ebabani 

With our support for bash tab completion, we rely on the support provided by our command parser library (Goflags) and its interaction with the Bash completion package itself.
Our CLI returns the list of e.g. files and directories, and Bash completion is adding the space automatically.
There is nothing we can do about that from within our CLI.

We'll explore if we can enhance our Bash completion script to make this work.

Regards,
Dies Koper
CF CLI PM

**Comment by oppegard** [comment]
We run across this annoyance a fair bit as well. It'd be nice to get a fix. For now we've disabled bash completion for the cf CLI.

**Comment by dkoper** [comment]
@oppegard thanks for the feedback. We welcome a PR on this, or even just the details how anyone got it to work.

**Comment by heyjcollins** [comment]
With the GA of the v7 CLI, we're no longer actively developing against the v6 line.  With an interest the overall hygiene of the CLI project we're closing this  issue.
If this issue is still occurring in v7 please feel free to comment and re-open. Thank you!
