### ISSUE TITLE
Forbidden character for service instance name prevents deletion/purge of the instance

### ISSUE THREAD

**Issue by SVasilev** [cloudfoundry/cli#1127]
## Command  

cf cs service-1 default ;whatever

## What occurred

Server error, status code: 400, error code: 10005, message: The query parameter is invalid: whatever
After that, I see that the service is created, but cannot be deleted/purged.

## What you expected to occur

Maybe if ";" is forbidden character for a service name, an error message should be displayed

## CLI Version  

6.25.0+787326d.2017-02-28

## CF Trace

REQUEST: [2017-04-25T13:03:32+03:00]
GET /v2/spaces/a9381e46-4066-49fb-a6fe-7c31ff75817a/service_instances?return_user_provided_service_instances=true&q=name%3A%3Bwharever&inline-relations-depth=1 HTTP/1.1

RESPONSE: [2017-04-25T13:03:33+03:00]
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 121
Content-Type: application/json;charset=utf-8
Date: Tue, 25 Apr 2017 10:03:33 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 17ac7a58-50b6-4dea-6d39-9e9167f78cbe
X-Vcap-Request-Id: 17ac7a58-50b6-4dea-6d39-9e9167f78cbe::ef699ee9-c8ed-49e1-8d70-16c4d19d1700

{
  "description": "The query parameter is invalid: wharever",
  "error_code": "CF-BadQueryParameter",
  "code": 10005
}

## Platform & Shell Details  

Windows 10 64-bit with PowerShell

**Comment by heyjcollins** [comment]
With the GA of the v7 CLI, we're no longer actively developing against the v6 line.  With an interest the overall hygiene of the CLI project we're closing this  issue.
If this issue is still occurring in v7 please feel free to comment and re-open. Thank you!
