### ISSUE TITLE
Misleading error message when `cf ssh` is used with too-large `-i` value

### ISSUE THREAD

**Issue by davwards** [cloudfoundry/cli#1130]
## Command  

Given I've deployed `my-app` with 2 instances:

`cf ssh my-app -i 2`

## What occurred

Command fails with:

"Error opening SSH connection: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain"

## What you expected to occur

An error message letting me know that I referenced an app instance that doesn't exist

## CLI Version  

`cf version 6.26.0+9291ea37e.2017-05-02`

## CC API Endpoint Version  

`api version:    2.80.0`

**Comment by dkoper** [comment]
I believe what adds to the confusion is that the help text doesn't specify what the `-i` value defaults to, which would clarify the index starts at 0, not 1. We'll look at improving that after reviewing your PR.

**Comment by dkoper** [comment]
Resolved in 6.27.0. Thanks for your contribution.
https://github.com/cloudfoundry/cli#downloads
