### ISSUE TITLE
cf unset-space-role takes wrong api hostname and fails

### ISSUE THREAD

**Issue by ssurenr** [cloudfoundry/cli#1134]
## Command  

cf unset-space-role xxx sampleorg samplespace SpaceDeveloper

## What occurred

Error performing request: dial tcp: lookup api.sys.us1.covapp.iodevelopers: no such host

## What you expected to occur
After deleting user, I expected a OK message. 

## CLI Version  

cf version 6.22.2+a95e24c-2016-10-27 and cf version 6.26.0+9c9a261fd.2017-04-06

## CC API Endpoint Version  

2.36.0

## CF Trace

REQUEST: [2017-05-08T12:40:22+05:30]
DELETE /?async=true HTTP/1.1
**_Host: api.sys.us1.covapp.iodevelopers_**
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.22.2+a95e24c / darwin

## Platform & Shell Details  

Mac OS X Sierra Terminal

## Any other relevant information  

The URL construction is wrong. Appending "developer" to API URL

**Comment by dkoper** [comment]
Hi @ssurenr 

I was able to reproduce it. We'll investigate. Thanks for the report!

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Resolved in 6.27.0. Thanks for reporting.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM
