### ISSUE TITLE
CF logs problems with 6.26.0

### ISSUE THREAD

**Issue by StBurcher** [cloudfoundry/cli#1135]
Hi Guys,

Í'm facing a problem with the new release of CF CLI (6.26.0). The most commands are working, but cf logs returns an error. However, If I using 6.25.0 it works. 
If have read in the changelog that the proxy variables are ignored. I'm behind a proxy but no variables are set in my consoles. 

## Command  

> cf logs spring-music-demo --recent

## What occurred

> Retrieving logs for app spring-music-demo in org ct-china / space sphere as admin...
> 
> Post https://uaa.de.cloudlab.com/oauth/token: read tcp 10.0.0.3:41146->139.25.25.233:443: read: connection reset by peer
> FAILED
> 

```
CF_TRACE=true cf logs spring-music-demo --recent
REQUEST: [2017-05-08T12:38:26+02:00]
GET /v2/info HTTP/1.1
Host: api.de.cloudlab.com
Accept: application/json
Content-Type: application/json
User-Agent: cf/6.26.0+9c9a261.2017-04-06 (go1.7.5; amd64 linux)

RESPONSE: [2017-05-08T12:38:27+02:00]
HTTP/1.1 200 OK
Content-Length: 560
Content-Type: application/json;charset=utf-8
Date: Mon, 08 May 2017 10:35:34 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 121d95fd-a804-4dcb-6427-47ca17ddb599
X-Vcap-Request-Id: d2329e25-5f19-49bc-646d-f4da1fa0ff18::69ef4e50-b90c-45d3-b24a-64c45e4c4835
{
  "api_version": "2.80.0",
  "app_ssh_endpoint": "ssh.de.cloudlab.com:2222",
  "app_ssh_host_key_fingerprint": null,
  "app_ssh_oauth_client": "ssh-proxy",
  "authorization_endpoint": "http://login.de.cloudlab.com",
  "build": "",
  "description": "",
  "doppler_logging_endpoint": "wss://doppler.de.cloudlab.com:4443",
  "logging_endpoint": "wss://loggregator.de.cloudlab.com:4443",
  "min_cli_version": null,
  "min_recommended_cli_version": null,
  "name": "",
  "support": "http://support.cloudfoundry.com",
  "token_endpoint": "[PRIVATE DATA HIDDEN]",
  "version": 0
}


Retrieving logs for app spring-music-demo in org ct-china / space sphere as admin...

REQUEST: [2017-05-08T12:38:27+02:00]
GET /v2/apps?q=name%3Aspring-music-demo&q=space_guid%3Ab5c6d824-42b7-4ea4-95a0-387eef5d45eb HTTP/1.1
Host: api.de.cloudlab.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: cf/6.26.0+9c9a261.2017-04-06 (go1.7.5; amd64 linux)

RESPONSE: [2017-05-08T12:38:27+02:00]
HTTP/1.1 401 Unauthorized
Content-Length: 97
Content-Type: application/json;charset=utf-8
Date: Mon, 08 May 2017 10:35:34 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: f01bf9fb-975c-4059-7685-eb3e0ae69378
X-Vcap-Request-Id: 2fcdcb5c-0ca1-4637-558f-7882d764c23c::eade2c29-61ea-447c-bf74-a12a707cdf38
{
  "code": 1000,
  "description": "Invalid Auth Token",
  "error_code": "CF-InvalidAuthToken"
}


REQUEST: [2017-05-08T12:38:27+02:00]
POST /oauth/token HTTP/1.1
Host: uaa.de.cloudlab.com
Accept: application/json
Connection: close
Content-Type: application/x-www-form-urlencoded
User-Agent: cf/6.26.0+9c9a261.2017-04-06 (go1.7.5; amd64 linux)
[PRIVATE DATA HIDDEN]

Post https://uaa.de.cloudlab.com/oauth/token: read tcp 10.0.0.3:41148->139.25.25.233:443: read: connection reset by peer
FAILED
```

## CLI Version  

6.26.0

## CC API Endpoint Version  
api endpoint:   https://api.de.cloudlab.com
api version:    2.80.0

## Platform & Shell Details  
Issue on Windows 7 and Ubuntu 14.04

## Any other relevant information  
CF-254 with Diego 1.14 on OpenStack Liberty

**Comment by dkoper** [comment]
Hi @StBurcher 

The API calls look correct but your UAA is dropping the connection. Could you try with our edge binary? It's built with Golang 1.8.1, which may offer a more detailed error message. 
https://github.com/cloudfoundry/cli#edge-binaries

Regards,
Dies Koper
CF CLI PM

**Comment by StBurcher** [comment]
Here is the edge output

> ./cf-edge logs spring-music-demo --recent
> REQUEST: [2017-05-08T13:07:50+02:00]
> GET /v2/info HTTP/1.1
> Host: api.de.cloudlab.com
> Accept: application/json
> Content-Type: application/json
> User-Agent: cf-edge/6.26.0+882c165.2017-05-05 (go1.8.1; amd64 linux)
> 
> RESPONSE: [2017-05-08T13:07:50+02:00]
> HTTP/1.1 200 OK
> Content-Length: 560
> Content-Type: application/json;charset=utf-8
> Date: Mon, 08 May 2017 11:04:58 GMT
> Server: nginx
> X-Content-Type-Options: nosniff
> X-Vcap-Request-Id: 78163563-3d31-42ec-7c71-de5870a56fdf
> X-Vcap-Request-Id: d75f8ce1-7047-4e99-5af2-748bddf02991::7fe65543-08e5-44b7-b6e8-19b5b332616a
> {
>   "api_version": "2.80.0",
>   "app_ssh_endpoint": "ssh.de.cloudlab.com:2222",
>   "app_ssh_host_key_fingerprint": null,
>   "app_ssh_oauth_client": "ssh-proxy",
>   "authorization_endpoint": "http://login.de.cloudlab.com",
>   "build": "",
>   "description": "",
>   "doppler_logging_endpoint": "wss://doppler.de.cloudlab.com:4443",
>   "logging_endpoint": "wss://loggregator.de.cloudlab.com:4443",
>   "min_cli_version": null,
>   "min_recommended_cli_version": null,
>   "name": "",
>   "support": "http://support.cloudfoundry.com",
>   "token_endpoint": "[PRIVATE DATA HIDDEN]",
>   "version": 0
> }
> 
> 
> Retrieving logs for app spring-music-demo in org ct-china / space mindsphere as admin...
> 
> REQUEST: [2017-05-08T13:07:51+02:00]
> GET /v2/apps?q=name%3Aspring-music-demo&q=space_guid%3Ab5c6d824-42b7-4ea4-95a0-387eef5d45eb HTTP/1.1
> Host: api.de.cloudlab.com
> Accept: application/json
> Authorization: [PRIVATE DATA HIDDEN]
> Content-Type: application/json
> User-Agent: cf-edge/6.26.0+882c165.2017-05-05 (go1.8.1; amd64 linux)
> 
> RESPONSE: [2017-05-08T13:07:51+02:00]
> HTTP/1.1 200 OK
> Content-Length: 2330
> Content-Type: application/json;charset=utf-8
> Date: Mon, 08 May 2017 11:04:58 GMT
> Server: nginx
> X-Content-Type-Options: nosniff
> X-Vcap-Request-Id: cb51816f-0e37-4263-40ed-04da29d7507f
> X-Vcap-Request-Id: bb307789-caf2-438c-52e8-47f9d952c29c::01a3f192-4293-4e72-939c-e539563162e7
> {
>   "next_url": null,
>   "prev_url": null,
>   "resources": [
>     {
>       "entity": {
>         "buildpack": null,
>         "command": null,
>         "console": false,
>         "debug": null,
>         "detected_buildpack": null,
>         "detected_buildpack_guid": null,
>         "detected_start_command": "",
>         "diego": true,
>         "disk_quota": 1024,
>         "docker_credentials_json": {
>           "redacted_message": "[PRIVATE DATA HIDDEN]"
>         },
>         "docker_image": null,
>         "enable_ssh": true,
>         "environment_json": {
>           "JAVA_OPTS": "-Djava.security.egd=file:///dev/urandom",
>           "JBP_CONFIG_APP_DYNAMICS_AGENT": "{repository_root:https://java-buildpack.cloudfoundry.org/app-dynamics}"
>         },
>         "events_url": "/v2/apps/f1d4ee1b-14a2-4a14-b17c-ab0f4a14d74f/events",
>         "health_check_http_endpoint": null,
>         "health_check_timeout": null,
>         "health_check_type": "port",
>         "instances": 1,
>         "memory": 1024,
>         "name": "spring-music-demo",
>         "package_state": "FAILED",
>         "package_updated_at": "2017-05-03T02:22:44Z",
>         "ports": [
>           8080
>         ],
>         "production": false,
>         "route_mappings_url": "/v2/apps/f1d4ee1b-14a2-4a14-b17c-ab0f4a14d74f/route_mappings",
>         "routes_url": "/v2/apps/f1d4ee1b-14a2-4a14-b17c-ab0f4a14d74f/routes",
>         "service_bindings_url": "/v2/apps/f1d4ee1b-14a2-4a14-b17c-ab0f4a14d74f/service_bindings",
>         "space_guid": "b5c6d824-42b7-4ea4-95a0-387eef5d45eb",
>         "space_url": "/v2/spaces/b5c6d824-42b7-4ea4-95a0-387eef5d45eb",
>         "stack_guid": "f5cedc1f-affa-4aeb-8c4d-b11a243c25ad",
>         "stack_url": "/v2/stacks/f5cedc1f-affa-4aeb-8c4d-b11a243c25ad",
>         "staging_failed_description": "An app was not successfully detected by any available buildpack",
>         "staging_failed_reason": "NoAppDetectedError",
>         "staging_task_id": "e2bc7539-d20a-4dc4-b021-d38927fbe3ee",
>         "state": "STOPPED",
>         "version": "46ea7e70-c13a-408f-8fda-fade2f11cfb3"
>       },
>       "metadata": {
>         "created_at": "2017-05-03T02:22:19Z",
>         "guid": "f1d4ee1b-14a2-4a14-b17c-ab0f4a14d74f",
>         "updated_at": "2017-05-08T11:01:51Z",
>         "url": "/v2/apps/f1d4ee1b-14a2-4a14-b17c-ab0f4a14d74f"
>       }
>     }
>   ],
>   "total_pages": 1,
>   "total_results": 1
> }
> 
> 
> REQUEST: [2017-05-08T13:07:51+02:00]
> POST /oauth/token HTTP/1.1
> Host: uaa.de.cloudlab.com
> Accept: application/json
> Connection: close
> Content-Type: application/x-www-form-urlencoded
> User-Agent: cf-edge/6.26.0+882c165.2017-05-05 (go1.8.1; amd64 linux)
> [PRIVATE DATA HIDDEN]
> 
> Post https://uaa.de.cloudlab.com/oauth/token: read tcp 10.0.0.3:41178->139.25.25.233:443: read: connection reset by peer
> FAILED
>

**Comment by StBurcher** [comment]
Additional comment.
If have switched off HM9000 and DEA last week.

**Comment by nickwei84** [comment]
@StBurcher Can you try running the `cf login` and `cf auth` command to obtain a valid token. If this work's it may make it easier for us to track down where the problem is.

Can you confirm that you do not have a proxy set up in your environment? In 6.26.0 of CF CLI, the loggregator, uaa, and cloudcontroller clients all read the proxy from the environment for the `logs` command.

**Comment by StBurcher** [comment]
@nickwei84 
Sure.
Here are the output for cf login

```
CF_TRACE=true cf login -a api.de.cloudlab.com --skip-ssl-validation
API endpoint: api.de.cloudlab.com

REQUEST: [2017-05-09T07:58:50+02:00]
GET /v2/info HTTP/1.1
Host: api.de.cloudlab.com
Accept: application/json
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.26.0+9c9a261.2017-04-06 / linux

RESPONSE: [2017-05-09T07:58:50+02:00]
HTTP/1.1 200 OK
Connection: close
Content-Length: 560
Content-Type: application/json;charset=utf-8
Date: Tue, 09 May 2017 05:55:56 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 4933330f-5231-44cc-7ba0-692f72c1de7c
X-Vcap-Request-Id: 8c025493-c2de-47f9-6b28-5514a67bf062::3de93aa0-5078-418c-b355-7608c73820bf

{"name":"","build":"","support":"http://support.cloudfoundry.com","version":0,"description":"","authorization_endpoint":"http://login.de.cloudlab.com","token_endpoint":"[PRIVATE DATA HIDDEN]","min_cli_version":null,"min_recommended_cli_version":null,"api_version":"2.80.0","app_ssh_endpoint":"ssh.de.cloudlab.com:2222","app_ssh_host_key_fingerprint":null,"app_ssh_oauth_client":"ssh-proxy","logging_endpoint":"wss://loggregator.de.cloudlab.com:4443","doppler_logging_endpoint":"wss://doppler.de.cloudlab.com:4443"}

REQUEST: [2017-05-09T07:58:50+02:00]
GET /login HTTP/1.1
Host: login.de.cloudlab.com
Accept: application/json
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.26.0+9c9a261.2017-04-06 / linux



RESPONSE: [2017-05-09T07:58:50+02:00]
HTTP/1.1 200 OK
Connection: close
Content-Length: 478
Cache-Control: no-store
Content-Language: en-US
Content-Type: application/json;charset=UTF-8
Date: Tue, 09 May 2017 05:55:56 GMT
Server: Apache-Coyote/1.1
Set-Cookie: X-Uaa-Csrf=Ajf7hftkyfWWjk8NyYcm48; Expires=Thu, 08-Jun-2017 05:55:56 GMT; HttpOnly
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Vcap-Request-Id: cbee6e3b-67e9-4ee2-67d3-9e246de45384
X-Xss-Protection: 1; mode=block

{"app":{"version":"3.15.0"},"links":{"uaa":"https://uaa.de.cloudlab.com","passwd":"https://login.de.cloudlab.com/forgot_password","login":"https://login.de.cloudlab.com","register":"https://login.de.cloudlab.com/create_account"},"zone_name":"uaa","entityID":"login.de.cloudlab.com","commit_id":"2051aec","idpDefinitions":{},"prompts":{"username":["text","Email"],"password":["password","Password"]},"timestamp":"2017-04-18T01:50:13+0000"}

Email> admin

Password>
Authenticating..

REQUEST: [2017-05-09T07:58:55+02:00]
POST /oauth/token HTTP/1.1
Host: login.de.cloudlab.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/x-www-form-urlencoded
User-Agent: go-cli 6.26.0+9c9a261.2017-04-06 / linux

grant_type=password&password=[PRIVATE DATA HIDDEN]&scope=&username=admin

RESPONSE: [2017-05-09T07:58:56+02:00]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Cache-Control: no-store
Content-Type: application/json;charset=UTF-8
Date: Tue, 09 May 2017 05:56:02 GMT
Pragma: no-cache
Server: Apache-Coyote/1.1
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Vcap-Request-Id: 8031b01f-3bfb-4b5c-60a1-274cd4c745e6
X-Xss-Protection: 1; mode=block

94f
{"access_token":"[PRIVATE DATA HIDDEN]","token_type":"[PRIVATE DATA HIDDEN]","refresh_token":"[PRIVATE DATA HIDDEN]","expires_in":599,"scope":"openid scim.read cloud_controller.admin uaa.user cloud_controller.read password.write cloud_controller.write doppler.firehose scim.write","jti":"7d2c16e0c5aa4ee7ad3e1af30024d40b"}
0
OK

REQUEST: [2017-05-09T07:58:56+02:00]
GET /v2/organizations?order-by=name HTTP/1.1
Host: api.de.cloudlab.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.26.0+9c9a261.2017-04-06 / linux



RESPONSE: [2017-05-09T07:58:56+02:00]
HTTP/1.1 200 OK
Connection: close
Content-Length: 5959
Content-Type: application/json;charset=utf-8
Date: Tue, 09 May 2017 05:56:02 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 6de5016c-2fcc-4019-6c66-a40f48854088
X-Vcap-Request-Id: 7d9400fc-2972-4dfe-5958-2d16b45bb4b1::29fc981f-23ef-4b91-a28b-0d95a205e94e

{
  "total_results": 4,
  "total_pages": 1,
  "prev_url": null,
  "next_url": null,
  "resources": [
    {
      "metadata": {
        "guid": "bc0ed3e9-eb83-4b2b-9568-8783c847526d",
        "url": "/v2/organizations/bc0ed3e9-eb83-4b2b-9568-8783c847526d",
        "created_at": "2017-03-22T11:58:34Z",
        "updated_at": "2017-03-22T11:58:34Z"
      },
      "entity": {
        "name": "admin",
        "billing_enabled": false,
        "quota_definition_guid": "a2827239-5ac3-4902-a609-1bd5751ecb0f",
        "status": "active",
        "default_isolation_segment_guid": null,
        "quota_definition_url": "/v2/quota_definitions/a2827239-5ac3-4902-a609-1bd5751ecb0f",
        "spaces_url": "/v2/organizations/bc0ed3e9-eb83-4b2b-9568-8783c847526d/spaces",
        "domains_url": "/v2/organizations/bc0ed3e9-eb83-4b2b-9568-8783c847526d/domains",
        "private_domains_url": "/v2/organizations/bc0ed3e9-eb83-4b2b-9568-8783c847526d/private_domains",
        "users_url": "/v2/organizations/bc0ed3e9-eb83-4b2b-9568-8783c847526d/users",
        "managers_url": "/v2/organizations/bc0ed3e9-eb83-4b2b-9568-8783c847526d/managers",
        "billing_managers_url": "/v2/organizations/bc0ed3e9-eb83-4b2b-9568-8783c847526d/billing_managers",
        "auditors_url": "/v2/organizations/bc0ed3e9-eb83-4b2b-9568-8783c847526d/auditors",
        "app_events_url": "/v2/organizations/bc0ed3e9-eb83-4b2b-9568-8783c847526d/app_events",
        "space_quota_definitions_url": "/v2/organizations/bc0ed3e9-eb83-4b2b-9568-8783c847526d/space_quota_definitions"
      }
    },
    {
      "metadata": {
        "guid": "c5c33301-a13a-4839-aba6-fc5511800065",
        "url": "/v2/organizations/c5c33301-a13a-4839-aba6-fc5511800065",
        "created_at": "2017-02-03T11:35:21Z",
        "updated_at": "2017-02-03T11:35:21Z"
      },
      "entity": {
        "name": "cloudlab",
        "billing_enabled": false,
        "quota_definition_guid": "a2827239-5ac3-4902-a609-1bd5751ecb0f",
        "status": "active",
        "default_isolation_segment_guid": null,
        "quota_definition_url": "/v2/quota_definitions/a2827239-5ac3-4902-a609-1bd5751ecb0f",
        "spaces_url": "/v2/organizations/c5c33301-a13a-4839-aba6-fc5511800065/spaces",
        "domains_url": "/v2/organizations/c5c33301-a13a-4839-aba6-fc5511800065/domains",
        "private_domains_url": "/v2/organizations/c5c33301-a13a-4839-aba6-fc5511800065/private_domains",
        "users_url": "/v2/organizations/c5c33301-a13a-4839-aba6-fc5511800065/users",
        "managers_url": "/v2/organizations/c5c33301-a13a-4839-aba6-fc5511800065/managers",
        "billing_managers_url": "/v2/organizations/c5c33301-a13a-4839-aba6-fc5511800065/billing_managers",
        "auditors_url": "/v2/organizations/c5c33301-a13a-4839-aba6-fc5511800065/auditors",
        "app_events_url": "/v2/organizations/c5c33301-a13a-4839-aba6-fc5511800065/app_events",
        "space_quota_definitions_url": "/v2/organizations/c5c33301-a13a-4839-aba6-fc5511800065/space_quota_definitions"
      }
    },
    {
      "metadata": {
        "guid": "ee0e0d08-13ab-443d-bcda-087babf42b62",
        "url": "/v2/organizations/ee0e0d08-13ab-443d-bcda-087babf42b62",
        "created_at": "2017-03-15T08:46:49Z",
        "updated_at": "2017-03-15T08:46:49Z"
      },
      "entity": {
        "name": "ct-china",
        "billing_enabled": false,
        "quota_definition_guid": "a2827239-5ac3-4902-a609-1bd5751ecb0f",
        "status": "active",
        "default_isolation_segment_guid": null,
        "quota_definition_url": "/v2/quota_definitions/a2827239-5ac3-4902-a609-1bd5751ecb0f",
        "spaces_url": "/v2/organizations/ee0e0d08-13ab-443d-bcda-087babf42b62/spaces",
        "domains_url": "/v2/organizations/ee0e0d08-13ab-443d-bcda-087babf42b62/domains",
        "private_domains_url": "/v2/organizations/ee0e0d08-13ab-443d-bcda-087babf42b62/private_domains",
        "users_url": "/v2/organizations/ee0e0d08-13ab-443d-bcda-087babf42b62/users",
        "managers_url": "/v2/organizations/ee0e0d08-13ab-443d-bcda-087babf42b62/managers",
        "billing_managers_url": "/v2/organizations/ee0e0d08-13ab-443d-bcda-087babf42b62/billing_managers",
        "auditors_url": "/v2/organizations/ee0e0d08-13ab-443d-bcda-087babf42b62/auditors",
        "app_events_url": "/v2/organizations/ee0e0d08-13ab-443d-bcda-087babf42b62/app_events",
        "space_quota_definitions_url": "/v2/organizations/ee0e0d08-13ab-443d-bcda-087babf42b62/space_quota_definitions"
      }
    },
    {
      "metadata": {
        "guid": "b81e40c4-e514-4647-ba9a-da13c279f7f1",
        "url": "/v2/organizations/b81e40c4-e514-4647-ba9a-da13c279f7f1",
        "created_at": "2017-03-28T12:52:19Z",
        "updated_at": "2017-03-28T12:52:19Z"
      },
      "entity": {
        "name": "sphere-in",
        "billing_enabled": false,
        "quota_definition_guid": "a2827239-5ac3-4902-a609-1bd5751ecb0f",
        "status": "active",
        "default_isolation_segment_guid": null,
        "quota_definition_url": "/v2/quota_definitions/a2827239-5ac3-4902-a609-1bd5751ecb0f",
        "spaces_url": "/v2/organizations/b81e40c4-e514-4647-ba9a-da13c279f7f1/spaces",
        "domains_url": "/v2/organizations/b81e40c4-e514-4647-ba9a-da13c279f7f1/domains",
        "private_domains_url": "/v2/organizations/b81e40c4-e514-4647-ba9a-da13c279f7f1/private_domains",
        "users_url": "/v2/organizations/b81e40c4-e514-4647-ba9a-da13c279f7f1/users",
        "managers_url": "/v2/organizations/b81e40c4-e514-4647-ba9a-da13c279f7f1/managers",
        "billing_managers_url": "/v2/organizations/b81e40c4-e514-4647-ba9a-da13c279f7f1/billing_managers",
        "auditors_url": "/v2/organizations/b81e40c4-e514-4647-ba9a-da13c279f7f1/auditors",
        "app_events_url": "/v2/organizations/b81e40c4-e514-4647-ba9a-da13c279f7f1/app_events",
        "space_quota_definitions_url": "/v2/organizations/b81e40c4-e514-4647-ba9a-da13c279f7f1/space_quota_definitions"
      }
    }
  ]
}
Select an org (or press enter to skip):
```

and for cf auth
```
CF_TRACE=true cf auth admin password

REQUEST: [2017-05-09T08:00:35+02:00]
GET /login HTTP/1.1
Host: login.de.cloudlab.siemens.com
Accept: application/json
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.26.0+9c9a261.2017-04-06 / linux



RESPONSE: [2017-05-09T08:00:35+02:00]
HTTP/1.1 200 OK
Connection: close
Content-Length: 478
Cache-Control: no-store
Content-Language: en-US
Content-Type: application/json;charset=UTF-8
Date: Tue, 09 May 2017 05:57:41 GMT
Server: Apache-Coyote/1.1
Set-Cookie: X-Uaa-Csrf=I6qxcT3G9X8HeB6n8uD6F3; Expires=Thu, 08-Jun-2017 05:57:41 GMT; HttpOnly
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Vcap-Request-Id: 81b98192-f227-4075-6b1e-6ecb97f345c2
X-Xss-Protection: 1; mode=block

{"app":{"version":"3.15.0"},"links":{"uaa":"https://uaa.de.cloudlab.siemens.com","passwd":"https://login.de.cloudlab.siemens.com/forgot_password","login":"https://login.de.cloudlab.siemens.com","register":"https://login.de.cloudlab.siemens.com/create_account"},"zone_name":"uaa","entityID":"login.de.cloudlab.siemens.com","commit_id":"2051aec","idpDefinitions":{},"prompts":{"username":["text","Email"],"password":["password","Password"]},"timestamp":"2017-04-18T01:50:13+0000"}
API endpoint: https://api.de.cloudlab.siemens.com
Authenticating...

REQUEST: [2017-05-09T08:00:35+02:00]
POST /oauth/token HTTP/1.1
Host: login.de.cloudlab.siemens.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/x-www-form-urlencoded
User-Agent: go-cli 6.26.0+9c9a261.2017-04-06 / linux

grant_type=password&password=[PRIVATE DATA HIDDEN]&scope=&username=admin

RESPONSE: [2017-05-09T08:00:36+02:00]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Cache-Control: no-store
Content-Type: application/json;charset=UTF-8
Date: Tue, 09 May 2017 05:57:41 GMT
Pragma: no-cache
Server: Apache-Coyote/1.1
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Vcap-Request-Id: e5f91967-e79f-471f-51e8-70079924006f
X-Xss-Protection: 1; mode=block

94f
{"access_token":"[PRIVATE DATA HIDDEN]","token_type":"[PRIVATE DATA HIDDEN]","refresh_token":"[PRIVATE DATA HIDDEN]","expires_in":599,"scope":"openid scim.read cloud_controller.admin uaa.user cloud_controller.read password.write cloud_controller.write doppler.firehose scim.write","jti":"cb2fe56afd1748da8c457eb86dcd4d67"}
0


OK
Use 'cf target' to view or set your target org and space
```
I can confirm there is no proxy in my bash or windows console for my user.  Other user has proxy settings. Also, no proxy in the manifest.

**Comment by melnikalex** [comment]
@StBurcher We're looking into your bug. A few questions to help us debug though: 

In our newest release, does `cf logs` fail consistently?

Aso, in the newest release, `cf logs` uses a newer uaa client to communicate with the uaa. To narrow down whether the issue is with this client or somewhere else in the command could you run `cf get-health-check` (which also uses the newer client) with an invalidated access token and paste the verbose output here?  (You can invalidate the token by opening up .cf/config.json in CF_HOME and changing the last character under AccessToken. To revert the changes simply logout and login.)

**Comment by StBurcher** [comment]
@melnikalex 
To be sure. Newest release is CF 258? I have to update my installation to that.

**Comment by dkoper** [comment]
@StBurcher No, cf CLI 6.26.0 (newest release) vs 6.25.0 (older version).

**Comment by mmb** [comment]
* Is port 443 blocked (perhaps by your proxy)? We're thinking that your `token_endpoint` might be redirecting to 443 which might be blocked.

* What is `token_endpoint` in `cf curl /v2/info` set to?

**Comment by StBurcher** [comment]
@mmb  and @dkoper 
Our Token Endpoind is https://uaa.de.cloudlab.com 
According to our Manifest. The UAA Port is 8080 or 8443

  ```
  port: 8080
    require_https: false
    scim:
      external_groups: null
      groups: null
      userids_enabled: true
      users:
      - groups:
        - scim.write
        - scim.read
        - openid
        - cloud_controller.admin
        - doppler.firehose
        name: admin
        password: password
    ssl:
      port: 8443
    token_endpoint: null
    url: https://uaa.de.cloudlab.com
```

**Comment by dkoper** [comment]
@StBurcher Can you invalidate your token (as described by Matt above) and run `cf get-health-check spring-music -v`, with the `-v` option to capture the *verbose* output and share that with us?

**Comment by StBurcher** [comment]
@dkoper I have invalidate the token is looks good now.

**Comment by mmb** [comment]
@StBurcher If you lookup the IP address of uaa.de.cloudlab.com is it 139.25.25.233?

What happens if you `curl -v https://uaa.de.cloudlab.com/`? It should return a 302 redirect to https://uaa.de.cloudlab.com/login.

**Comment by StBurcher** [comment]
Cf logs works now, after invalidate the token.
CF curls -v https://uaa.de.cloudlab.com returns a 404.

**Comment by dkoper** [comment]
@StBurcher The check was to run `curl -v https://uaa.de.cloudlab.com`, not `cf curl -v https://uaa.de.cloudlab.com`.
But if you're saying it's working now, we're guessing something went wrong with UAA or your access token, possibly during the bosh deployment when removing DEAs, and we'll not likely be able to investigate further on our side.
Glad to hear it's working again!

**Comment by StBurcher** [comment]
with curl it works. Thank you. This problem is solved
