### ISSUE TITLE
Plugins misbehave if $CF_HOME is set but $CF_PLUGIN_HOME is not set

### ISSUE THREAD

**Issue by glyn** [cloudfoundry/cli#1137]
I found the following behaviour with cf version 6.22.2+a95e24c-2016-10-27.

Attempt to get help for one my [my plugin's](https://github.com/pivotal-cf/spring-cloud-services-cli-plugin) commands:
```
$ CF_HOME=/tmp/tmpcfhome cf help config-server-encrypt-value
'config-server-encrypt-value' is not a registered command. See 'cf help'
FAILED
```
So it appears that the plugin is not installed. If I attempt to install it:
```
$ CF_HOME=/tmp/tmpcfhome cf install-plugin -f /path/to/spring-cloud-services-cli-plugin
Installing plugin spring-cloud-services-cli-plugin...
FAILED
The file spring-cloud-services-cli-plugin already exists under the plugin directory.
```
then it appears that the plugin is already installed.

I can work around this problem by setting $CF_PLUGIN_HOME.

**Comment by dkoper** [comment]
The plugin commands (and help) are now consistently falling back to $CF_HOME when $CF_PLUGIN_HOME is not set. Thanks for reporting.
https://github.com/cloudfoundry/cli#downloads
