### ISSUE TITLE
Enable cf curl to handle pagination

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/cli#1138]
I find myself very often with the need of a wrapper for cf curl calls that automatically fetches all/part of the paginated results and merges them in a single result structure, i.e. something like the following:

```ruby
#!/usr/bin/env ruby
require 'json'

url = ARGV.shift
res = []
while url do
  cfres = `cf curl '#{url}'` or throw "empty response from cf"
  cfres = JSON.load(cfres) or throw "broken response from cf"
  res += cfres["resources"]
  url = cfres["next_url"]
end

puts JSON.pretty_generate({
  "total_results" => res.length,
  "total_pages" => 1,
  "prev_url" => nil,
  "next_url" => nil,
  "resources" => res
})
```

It would be very useful if cf curl gained the ability to do the same thing.

## Command  

```
# behave like the snippet above 
cf curl -p /v2/apps 
# (optional) behave like the snippet above, but stop after downloading the N-th page (N=20 in this example)
cf curl -p 20 /v2/apps
```

## What occurred

Currently not supported

## What you expected to occur

cf curl to return a single result structure containing non-paginated results

## CLI Version  

6.26

## CC API Endpoint Version  

cf248

**Comment by dkoper** [comment]
Hi @CAFxX 

Currently, `cf curl`, like `curl`, is not "CC API  aware" beyond setting the api domain and defaulting the content-type to json. It just returns the HTTP response as is.

Are you suggesting that the curl command should become "smart" and parse the response, figure out that it is paginated (the mechanism of which is different between CC API versions) and merge them into some new json structure?

What is the original use case? Sounds like you're just after `cf apps` output in json format?

Regards,
Dies Koper
CF CLI PM

**Comment by CAFxX** [comment]
> Are you suggesting that the curl command should become "smart" and parse the response, figure out that it is paginated (the mechanism of which is different between CC API versions) and merge them into some new json structure?

It should be aware of the "first-level" of the object, i.e. the   "total_results", "total_pages", "prev_url", "next_url" and "resources". Also, this behavior would be opt-in via the -p flag.

> What is the original use case? Sounds like you're just after cf apps output in json format?

When you start to have many hundreds of apps, ~100 orgs, few hundreds spaces, ~1000 routes and instances, this becomes a hard requirement - because almost every time you need to use cf curl you really need the behavior I'm describing. See e.g. https://github.com/rakutentech/cf-tools/

**Comment by abbyachau** [comment]
Hi @CAFxX thanks for creating this issue. `cf curl` is designed to be a simple debugging mechanism, and is not meant for complex operations. 

We believe your use case could better be solved by using a cf CLI API client, which we plan on offering to users at some point. We are closing this issue but please feel free to reach out if you have additional feedback/comments.

**Comment by CAFxX** [comment]
@matt-royal I still agree it would totally make sense to have this in the CLI, since it would be relatively simple to implement and it would help in most non-toy cases (how many production CF foundations have less than 100 apps/routes/users/orgs?). But since we couldn't wait we simply went ahead and wrapped the CF CLI: https://github.com/rakutentech/cf-tools
