### ISSUE TITLE
Installing CF Cli on Docker Image

### ISSUE THREAD

**Issue by avirkar** [cloudfoundry/cli#1139]
I am using the following docker script
#RUN wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo  apt-key add -
#RUN sudo apt-get update
#RUN sudo apt-get install cf-cli
#RUN cf --version

Getting error 

Step 6/9 : RUN wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo  apt-key add -
 ---> Running in 0c290a5cc70b
OK
 ---> a2905a236e1e
Removing intermediate container 0c290a5cc70b
Step 7/9 : RUN sudo apt-get update
 ---> Running in 53da9bc1cc44
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Ign http://deb.debian.org jessie InRelease
Get:2 http://deb.debian.org jessie-updates InRelease [145 kB]
Get:3 http://deb.debian.org jessie-backports InRelease [166 kB]
Get:4 http://deb.debian.org jessie Release.gpg [2373 B]
Get:5 http://deb.debian.org jessie Release [148 kB]
Get:6 http://security.debian.org jessie/updates/main amd64 Packages [509 kB]
Get:7 http://deb.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Get:8 http://deb.debian.org jessie-backports/main amd64 Packages [1150 kB]
Get:9 http://deb.debian.org jessie/main amd64 Packages [9065 kB]
Fetched 11.3 MB in 9s (1230 kB/s)
Reading package lists...
 ---> f57e46791f37
Removing intermediate container 53da9bc1cc44
Step 8/9 : RUN sudo apt-get install cf-cli
 ---> Running in 6fd97ac8c004
Reading package lists...
Building dependency tree...
Reading state information...
# _E: Unable to locate package cf-cli_
The command '/bin/sh -c sudo apt-get install cf-cli' returned a non-zero code: 100

**Comment by dkoper** [comment]
Hi @avirkar 

I don't see this step in your log:
```
echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
```

That's the step that makes `apt-get` aware of our CFF repo. If it were missing, I would expect the output you shared. Please check.

Regards,
Dies Koper
CF CLI PM

**Comment by reddymadhavi** [comment]
Hello,

I am also getting same error : 

E: Unable to locate package cf-cli
The command '/bin/sh -c apt-get install cf-cli' returned a non-zero code: 100

Can someone please help me with solution ?

**Comment by avirkar** [comment]
I think @reddymadhavi  you should try to execute the step mentioned by @dkoper. That should make it work.

**Comment by shitalb358** [comment]
Hi all ,
I am facing same issue , here below is my dockerfile


FROM ubuntu
RUN  apt-get update \
  && apt-get install -y wget
RUN wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
RUN  echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
RUN sudo apt-get update
RUN sudo  apt-get install cf-cli
RUN cf --version

**Comment by avirkar** [comment]
Are you sure you are able to run commands with sudo on your VM.
