### ISSUE TITLE
can not map route

### ISSUE THREAD

**Issue by lordnox** [cloudfoundry/cli#1141]
## Command  

`cf create-route mySpace mydomain.net --hostname ${subdomain}`
`cf map-route myApp mydomain.net --hostname ${subdomain}`

## What occurred

Create-Route works fine, I'm running these commands with about 120 subdomains each.
First 120x create-route, then 120x map-route.
Map-route will start to throw error from domain 29 and onwards.
* A few days ago it only started to stop working at domain 112, I cleaned the list to stay under 112.

```
cf map-route myApp mydomain.net --hostname subdomain29 
----------------- OUT ----------------- 
Creating route subdomain29.mydomain.net for...
OK
Route subdomain29.mydomain.net already exists
Adding subdomain29.mydomain.net to app myApp in...
FAILED
Server error, status code: 500, error code: 170016, message: Runner error: Invalid field: routes
```

I tried to ask some search engine for the string `Invalid field: routes` but I could not get any results.

## What you expected to occur

I expected that the commands work just fine, I see no reason that there is a limit to the subdomain count. Since then I found this article [Migrating-Applications-from-DEAs-to-Diego](https://discuss.pivotal.io/hc/en-us/articles/230433388-Migrating-Applications-from-DEAs-to-Diego), so I checked if I reached the 4kb limit, but this is not the case. It might have been with the 120 earlier though.

## CLI Version  

cf version 6.22.2+a95e24c-2016-10-27

## CC API Endpoint Version  

API endpoint: https://api.run.pivotal.io (API version: 2.81.0)

## CF Trace

´´´
[...]
OK
Route subdomain29.mydomain.net already exists
Adding route subdomain29.mydomain.net to app ui in...

REQUEST: [2017-05-12T11:20:28+02:00]
PUT /v2/apps/b5b98dbd-1da9-4472-b708-6a4f7a6cd0e1/routes/861f2ccb-d5b7-4f94-82be-2d7df59ed9dc HTTP/1.1
Host: api.run.pivotal.io
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.22.2+a95e24c / darwin

RESPONSE: [2017-05-12T11:20:28+02:00]
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Length: 111
Content-Type: application/json;charset=utf-8
Date: Fri, 12 May 2017 09:20:28 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Ratelimit-Limit: 20000
X-Ratelimit-Remaining: 18518
X-Ratelimit-Reset: 1494582284
X-Vcap-Request-Id: 9dd1ce60-af6b-4f52-47ca-172336fc29fc
X-Vcap-Request-Id: 60b63949-7623-4480-6a10-8840c87ba252::0e29c183-f9e9-4567-b1ba-3b49c69768e6

{
  "description": "Runner error: Invalid field: routes",
  "error_code": "CF-RunnerError",
  "code": 170016
}

FAILED
Server error, status code: 500, error code: 170016, message: Runner error: Invalid field: routes
```

## Platform & Shell Details  

macOS 10.12.4
Terminal 2.7.2 (388.1)

**Comment by dkoper** [comment]
@zrob any idea what this error means?

**Comment by zrob** [comment]
As @lordnox mentions this is likely related to the size constraints on the diego router info.

Per @ematpl recent post to the cf-dev mailing list: "This routes payload limit is increased to 128KiB in Diego v1.16.1."

Please bump this issue after testing on that version.

**Comment by dkoper** [comment]
Closing as Diego 1.16.1 has been out for some weeks now and as this issue hasn't been bumped I'm assuming it resolved it.
