### ISSUE TITLE
Issue with services: being an empty array in the manifest.yml

### ISSUE THREAD

**Issue by dfedde-pivotal** [cloudfoundry/cli#1142]
Command
		cf push -f ops/cf/manifests/trackerplatinum.yml web-blue

		CLI Version
		6.26.0+9c9a261fd.2017-04-06

		Error
		interface conversion: interface is nil, not []interface {}

		Stack Trace
			goroutine 1 [running]:
	code.cloudfoundry.org/cli/util/panichandler.HandlePanic()
		/Users/worker/concourse/containers/00003i0tfte/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/util/panichandler/handler.go:19 +0xb5
	panic(0x7d7ba0, 0xc4205ff680)
		/usr/local/Cellar/go/1.7.5/libexec/src/runtime/panic.go:458 +0x243
	code.cloudfoundry.org/cli/util/generic.mergeReducer(0x789940, 0xc4202926c0, 0x77baa0, 0xc42068a1e0, 0xcb9bc0, 0xc420412648, 0xcb9bc0, 0xc420412648)
		/Users/worker/concourse/containers/00003i0tfte/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/util/generic/merge_reduce.go:34 +0x478
	code.cloudfoundry.org/cli/util/generic.Reduce(0xc4206bfff8, 0x2, 0x2, 0xcb9bc0, 0xc420412648, 0x957a40, 0x7c3c01, 0xc42024bcf0)
		/Users/worker/concourse/containers/00003i0tfte/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/util/generic/merge_reduce.go:48 +0x155
	code.cloudfoundry.org/cli/util/generic.DeepMerge(0xc4206bfff8, 0x2, 0x2, 0xcb9bc0, 0xc420412640)
		/Users/worker/concourse/containers/00003i0tfte/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/util/generic/merge_reduce.go:18 +0x82
	code.cloudfoundry.org/cli/cf/manifest.Manifest.getAppMaps(0x7fff5fbfeac3, 0x24, 0xcb9bc0, 0xc420412628, 0xcb9bc0, 0xc420412598, 0x0, 0x0, 0x95519c, 0xc4206c00a0, ...)
		/Users/worker/concourse/containers/00003i0tfte/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/cf/manifest/manifest.go:81 +0x400
	code.cloudfoundry.org/cli/cf/manifest.Manifest.Applications(0x7fff5fbfeac3, 0x24, 0xcb9bc0, 0xc420412628, 0x0, 0x0, 0xcac720, 0xc42017c500, 0xcac760)
		/Users/worker/concourse/containers/00003i0tfte/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/cf/manifest/manifest.go:35 +0x191
	code.cloudfoundry.org/cli/cf/commands/application.(*Push).getAppParamsFromManifest(0xc4205c5e60, 0xcbad40, 0xc4205ff380, 0xc4200c1040, 0xcb7ce0, 0xc4200c1360, 0xcb0a60, 0xc42068d450)
		/Users/worker/concourse/containers/00003i0tfte/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/cf/commands/application/push.go:615 +0x4c7
	code.cloudfoundry.org/cli/cf/commands/application.(*Push).Execute(0xc4205c5e60, 0xcbad40, 0xc4205ff380, 0xcbad40, 0xc4205ff380)
		/Users/worker/concourse/containers/00003i0tfte/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/cf/commands/application/push.go:181 +0xa7
	code.cloudfoundry.org/cli/cf/cmd.Main(0xc420010009, 0x4, 0xc420096000, 0x5, 0x5)
		/Users/worker/concourse/containers/00003i0tfte/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/cf/cmd/cmd.go:120 +0xd02
	code.cloudfoundry.org/cli/command/v2.PushCommand.Execute(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
		/Users/worker/concourse/containers/00003i0tfte/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/command/v2/push_command.go:43 +0x76
	code.cloudfoundry.org/cli/command/v2.(*PushCommand).Execute(0xdae090, 0xc4205fe4c0, 0x1, 0x4, 0xc4203a0070, 0x0)
		<autogenerated>:192 +0xb1
	main.executionWrapper(0x13afd98, 0xdae090, 0xc4205fe4c0, 0x1, 0x4, 0x0, 0x0)
		/Users/worker/concourse/containers/00003i0tfte/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/main.go:161 +0x254
	code.cloudfoundry.org/cli/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc4205da840, 0xc420096010, 0x4, 0x4, 0xda7fc0, 0xc4205f0fc0, 0xf69000, 0x0, 0x4)
		/Users/worker/concourse/containers/00003i0tfte/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/vendor/github.com/jessevdk/go-flags/parser.go:314 +0x89f
	main.parse(0xc420096010, 0x4, 0x4)
		/Users/worker/concourse/containers/00003i0tfte/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/main.go:35 +0xba
	main.main()
		/Users/worker/concourse/containers/00003i0tfte/tmp/build/254d4083/gopath/src/code.cloudfoundry.org/cli/main.go:29 +0x86

	goroutine 17 [syscall, locked to thread]:
	runtime.goexit()
		/usr/local/Cellar/go/1.7.5/libexec/src/runtime/asm_amd64.s:2086 +0x1

	goroutine 19 [syscall]:
	os/signal.signal_recv(0x0)
		/usr/local/Cellar/go/1.7.5/libexec/src/runtime/sigqueue.go:116 +0x157
	os/signal.loop()
		/usr/local/Cellar/go/1.7.5/libexec/src/os/signal/signal_unix.go:22 +0x22
	created by os/signal.init.1
		/usr/local/Cellar/go/1.7.5/libexec/src/os/signal/signal_unix.go:28 +0x41

		Your Platform Details
		Mac OS X 10.11

		Shell
		 iTerm

this looks to be an issue with services: being an empty array in the manifest.yml

**Comment by dkoper** [comment]
Hi @dfedde-pivotal 

Thanks for the report.
We're in the middle of refactoring `cf push`. We'll make sure we test this case when we get to the manifest feature to ensure this won't happen again.

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
This is now resolved in cf CLI 6.34.0.

Regards,
Dies Koper
CF CLI PM
