### ISSUE TITLE
cf router-groups command does not refresh expired auth token

### ISSUE THREAD

**Issue by jberkhahn** [cloudfoundry/cli#1143]
## Command  

cf router-groups 

## What occurred
```
± ex+jb |master {2} U:1 ?:1 ✗| → cf router-groups -v
Getting router groups as admin ...


REQUEST: [2017-05-17T14:26:06-07:00]
GET /routing/v1/router_groups HTTP/1.1
Host: api.batman-lite.cf-app.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.26.0+9c9a261fd.2017-04-06 / darwin



RESPONSE: [2017-05-17T14:26:08-07:00]
HTTP/1.1 401 Unauthorized
Connection: close
Content-Length: 57
Content-Type: text/plain; charset=utf-8
Date: Wed, 17 May 2017 21:26:08 GMT
X-Vcap-Request-Id: adadf83e-b479-4b89-41bc-c065b2f94901
X-Vcap-Request-Id: 2fb3c0d3-7b45-40cf-518b-1b680a4c6c2c

{"name":"UnauthorizedError","message":"token is expired"}
FAILED
Failed fetching router groups.
Server error, status code: 401, error code: UnauthorizedError, message: token is expired
```

## What you expected to occur
I expected the cli to silently refresh the auth token with the uaa, and then resubmit the original request to the routing api.

## CLI Version  
6.26.0+9c9a261fd.2017-04-06

## routing API Endpoint Version  
routing api commit c8d190ac4869b149b81430256362b209718cb793

## Platform & Shell Details  
OSX 10.10.5 iterm2

## Additional Details
after running router-groups and getting the 401, I ran orgs and it got a 401 from the cc, refreshed the auth token like normal, and then resubmitted the request to CC.

**Comment by abbyachau** [comment]
Spoke to the Networking Program team and they confirmed it's ok to close this issue as `won't-do`. Thanks.
