### ISSUE TITLE
Missing command for creating space-scoped staging security groups

### ISSUE THREAD

**Issue by jtuchscherer** [cloudfoundry/cli#1144]
This is a feature request.

Why can't we create space-scoped staging security groups via the CLI, e.g.
`cf bind-staging-security-groups GROUP_NAME ORG SPACE` 

The [documentation](https://docs.cloudfoundry.org/concepts/asg.html#binding-groups) is a little awkward - it tells you to use the CC API directly. It would be nice to have this baked into the CLI.

**Comment by dkoper** [comment]
Take a look at our tracker - that is exactly what we'll be working on for the next release!

**Comment by jtuchscherer** [comment]
Thanks Dies. That is awesome. And sorry for not checking Tracker. I guess I could have done that before opening the ticket.

Closing this issue to avoid duplication.
