### ISSUE TITLE
Unfriendly error message for unquoted wildcard hostname: interpreted as yml alias node

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#1146]
## Command  

```
$ cat manifest-line.yml
applications:
- name: nifty-gui
  memory: 512M
  host: *

$ cf push -f manifest-line.yml
```

## What occurred

``
FAILED
Error reading manifest file:
yaml: line 3: did not find expected alphabetic or numeric character
``
Reports on line 3 instead of line 4. 
This makes it harder to spot in this case that the issue is related to the wildcard missing a quote (see https://github.com/cloudfoundry/docs-dev-guide/pull/182)

## What you expected to occur

``
FAILED
Error reading manifest file:
yaml: line 4: did not find expected alphabetic or numeric character
``

## CLI Version  

cf version 6.26.0+9c9a261.2017-04-06

## Platform & Shell Details  

Ubuntu 16.04.3 64-bit with gnome-terminal

**Comment by dkoper** [comment]
Thanks @gberche-orange! We'll try addressing this in the current refactor of `push`.

**Comment by gberche-orange** [comment]
Rethinking about this, this might be specific to the ``*`` syntax which the yml parser would interpret as an [alias node](http://yaml.org/spec/1.2/spec.html#id2786196) and searching for the reference name up to the next line. It's may be not a generic off-by-one line number issue.

Might be better to rename the issue as ``Unfriendly error message for unquoted wildcard hostname: interpreted as yml alias node``, (I'm lacking permissions to do so), and potentially see if a nicer message would be worth or the documentation hint is sufficient.

Sorry for my initial likely mis-diagnostic, and associated noise.

**Comment by XenoPhex** [comment]
Hi @gberche-orange thanks for creating this issue. We believe we fixed this issue - please upgrade to the latest cf CLI version to see this resolved.
