### ISSUE TITLE
cli do not support $ character in password

### ISSUE THREAD

**Issue by yhjhoo** [cloudfoundry/cli#1150]
## Command  

cf login -u test -p Pass$123  -o testorg -s testspace

## What occurred

Credentials were rejected, please try again

## What you expected to occur
I provided the correct password, I should login successfully.

## CLI Version  

cf version 6.26.0+9c9a261.2017-04-06

## CC API Endpoint Version  

api version:    2.65.0

**Comment by dkoper** [comment]
Hi @yhjhoo,

What platform/shell are you in?
When I run that in bash as follows, it shows the password is not being passed to the cf CLI unless I enclose it in single quotes:
```
diesk@cloud-cf:~$ echo cf login -u test -p Pass$123 -o testorg -s testspace
cf login -u test -p Pass23 -o testorg -s testspace
diesk@cloud-cf:~$ echo cf login -u test -p 'Pass$123' -o testorg -s testspace
cf login -u test -p Pass$123 -o testorg -s testspace
```

Regards,
Dies Koper
CF CLI PM

**Comment by yhjhoo** [comment]
Hi @dkoper 

Thanks for getting back, I was using MAC at the time. I tried double quote. Yes, single quote is working file.
