### ISSUE TITLE
Feature Request : Global Command to display routes

### ISSUE THREAD

**Issue by mitulsheth** [cloudfoundry/cli#1151]
It would be great to have a command to search for all the routes globally across all spaces and / or Orgs. It certainly makes administration easier specially when random routes are not on for App and routes are already consumed by other app.

**Comment by mitulsheth** [comment]
There seems to be cf plgin that exists "do-all" however it is not stable and is buggy at this point and hence not ready to be used in Production.

**Comment by dkoper** [comment]
Hi @mitulsheth 

What do you mean by "when random routes are not on for App"?
I am concerned that in many production systems the total number of routes (over all orgs) is a huge number so this command would take a long time to return.
So having this in a plugin would be our recommendation.
Have you reached out to the plugin author to report the stability issues you've encountered?

Regards,
Dies Koper
CF CLI PM
