### ISSUE TITLE
support NTLM Authorization Proxy Server 

### ISSUE THREAD

**Issue by boyang9527** [cloudfoundry/cli#1153]
The current http_proxy environment variable setting does not work with a proxy server using NTLM protocol. Can we add support to this?

**Comment by boyang9527** [comment]
close this issue since it is the same as https://github.com/cloudfoundry/cli/issues/577

**Comment by gogolok** [comment]
I think this won't work with the default Go http transport (proxy returns 407, doesn't support multiple http rounds).
You will need to extend Go's net/http/transport.go file, e.g. WIP:
https://gist.github.com/gogolok/018443687392ea4682bd82ac8712b363
