### ISSUE TITLE
CLI does not indicate that there insufficient resources to run my app

### ISSUE THREAD

**Issue by jvshahid** [cloudfoundry/cli#1155]
## Command  

assuming I have a dora app that is pushed and running and have large enough memory quota (e.g. 99999G). If I run `cf scale -m 999G dora` I don't get an InsufficientResource error

## What occurred

```
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
```

## What you expected to occur

Some error indicating that there aren't sufficient resources to run my app, e.g. `InsufficientResourceError`.

## CLI Version  

`cf version 6.21.0+dff2cf8-2016-07-27`

## CC API Endpoint Version  

`API version: 2.83.0`

## app instances

Running `cf curl /v2/apps/$(cf app dora --guid)/instances` returns the following:

```
{
   "0": {
      "state": "DOWN",
      "uptime": 33,
      "since": 1496154367,
      "details": "insufficient resources: memory"
   }
}
```

**Comment by dkoper** [comment]
Looks like we're simply waiting for a status RUNNING and not notice other statuses like DOWN or CRASHED. Will investigate, thanks!

**Comment by dkoper** [comment]
@zrob Is there a way we can (reliably) determine the app instance start is failing for a reason that is not likely going to be solved by the health check restarting?
I noticed [the API](http://apidocs.cloudfoundry.org/258/apps/get_the_instance_information_for_a_started_app.html) lists states `DOWN` and `CRASHED` but they are not defined.

I wonder if, while waiting for `RUNNING`, we should abort if the API returns either of these states for all its instances.

**Comment by zrob** [comment]
@dkoper hmm i don't think there is, one option would be to display `details` next to the line if it is reporting down or crashed...but not sure what all messages may exist their or if they would be confusing.

**Comment by dkoper** [comment]
@ematpl Can you shed more light on this? Share some wisdom?

**Comment by ematpl** [comment]
@dkoper Placement-error messages would come primarily from the errors defined in https://github.com/cloudfoundry/auction/blob/master/auctiontypes/types.go. I don't think they would be particularly confusing, and in any case CC and the CLI likely display these details for other instance-detail commands, such as `cf app APP_NAME`. One thing that could complicate the display would be aggregating relevant details in the case where several instances are down, but perhaps the CLI could de-duplicate and then joint the distinct placement-error details together with commas.

Best,
Eric

**Comment by dkoper** [comment]
@ematpl Do you know the difference between `CRASHED` and `DOWN`? Is it safe for the CLI to abort polling the app status and assume it'll never start with both of these states, or could these be returned while the health checker may still be restarting the app?

**Comment by ematpl** [comment]
I don't recall all the details about how CC presents the states of the Diego ActualLRPs, but I think CC's `CRASHED` comes from the ActualLRP `CRASHED` state and `DOWN` comes from either an `UNCLAIMED` ActualLRP with a placement error or a missing ActualLRP record at that index. Maybe someone on CAPI can point out where the correspondence happens in CC?

**Comment by dkoper** [comment]
@zrob @ematpl Can either of you clarify whether for a starting app CC could initially return state `CRASHED` or `DOWN` at first for an app instance, but later change to `RUNNING` without any user action (due to e.g. retry logic)?

**Comment by ematpl** [comment]
@dkoper Yes, that could happen.

**Comment by dkoper** [comment]
@jvshahid 

Would the following behaviour address the issue for you?
*Solution pending a feasibility exploration.*

```
$ cf start flailingapp
Starting app flailingapp in org dies-test / space dev as admin...

Waiting for app to start...
3 instances reported: insufficient resources: memory
```

I.e., instead of a repetitive polling message, an (inline updating) list of errors and number of instances affected.
This allows you to choose to ctrl-c and address the error immediately, or wait longer to see if CF manages to recover the issue (by restarting the app, etc.).

**Comment by XenoPhex** [comment]
Hi @jvshahid the bug is no longer an issue:
