### ISSUE TITLE
Add message when cups -p <file> finds a file but fails parsing.

### ISSUE THREAD

**Issue by norman-abramovitz** [cloudfoundry/cli#1163]
## Command  

cf ... cups -p /home/xyzzy/dir/dir/file 
The create user provided service command should generate a warning message if the -p option finds a file and fails parsing.   

## What occurred

The cf command prompted because their was syntax error in the file.   It prompted without an warning message.  

## What you expected to occur

A warning message that a parsing error occurred before prompting.

**Comment by dkoper** [comment]
Hi @norman-abramovitz 

Thanks for reporting. We'll look at aborting with an error message when we refactor the `cups` and `uups` commands.

Cheers,
Dies Koper
CF CLI PM

**Comment by norman-abramovitz** [comment]
I was actually thinking that warning would be better in for the case where a file exists in the local directory and it matches the string prompt.  In this way, the user has the choice to decide which the correct method he was expecting.

Yes, if the string looks like path then of course fail.   but if it is 

cf ... p="example"

Should you fail because the example exists and fails or should you also prompt.

**Comment by heyjcollins** [comment]
With the GA of the v7 CLI, we're no longer actively developing against the v6 line.  With an interest the overall hygiene of the CLI project we're closing this  issue.
If this issue is still occurring in v7 please feel free to comment and re-open. Thank you!
