### ISSUE TITLE
Running plugin with -v option affects command behaviour

### ISSUE THREAD

**Issue by georgeharley** [cloudfoundry/cli#1164]
## Command  

Calling `cliConnection.CliCommandWithoutTerminalOutput("curl", "/v2/info")` from inside some custom plugin code.   

## What occurred

When the plugin was run with the `-v` option the response from `cliConnection.CliCommandWithoutTerminalOutput("curl", "/v2/info")` was empty. Re-running the plugin _without_ the `-v` option results in the expected response from the call.

## What you expected to occur

Expected the response from the `cliConnection.CliCommandWithoutTerminalOutput("curl", "/v2/info")` call to be the same irrespective of whether `-v` is used.

## CLI Version  

6.27.0+d26b32dcc.2017-06-08

## CC API Endpoint Version  

2.75.0

## CF Trace

Use of the `-v` option seems to be the problem here :-)

## Platform & Shell Details  

Mac OS X 10.12.5 Terminal 

## Any other relevant information  

I've written a very simple plugin (based off the sample basic plugin) that hopefully demonstrates the problem. See https://github.com/georgeharley/basic-plugin

**Comment by dkoper** [comment]
Your description sounds like one of our limitations:
https://github.com/cloudfoundry/cli#known-issues

If so, this requires a lot of work to fix. We have no plans to start this any time soon.

**Comment by dkoper** [comment]
Closing. I think you hit a known limitation with a workable work-around.
