### ISSUE TITLE
Inconsistency in ports between domains and routes

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/cli#1166]
## Command  

`cf push -o cloudfoundry/test-app -f manifest.yml`

## What occurred
If the manifest is:
```
---
applications:
- name: test
  memory: 128M
  routes:
  - route: tcp.com
```
Then the following error is given: `Server error, status code: 400, error code: 210001, message: The route is invalid: For TCP routes you must specify a port or request a random one.`

If the manifest is:
```
---
applications:
- name: test
  memory: 128M
  domain: tcp.com
```
Then the application is pushed with a random port

## What you expected to occur
Both manifests specify the same thing, but result in very different behaviour. The fact that I expressed the same request in different ways shouldn't make a difference to the result, so either both should error or both should succeed.

## CLI Version  

cf version 6.27.0+d26b32dcc.2017-06-08

## CC API Endpoint Version  

api endpoint:   https://api.local.pcfdev.io
api version:    2.75.0

## Platform & Shell Details  
macOS 10.12.5, Apple Terminal.

**Comment by twoseat** [comment]
(Note for me: depending on outcome may need to change DefaultApplications/getRouteIdForTcpRoute)

**Comment by dkoper** [comment]
Both should error.
I went back to the original stories and can only assume we didn't test the `cf push -d tcp.example.com` case without `--random-route`.

**Comment by till** [comment]
This still seems to be a case. Anything TCP lacks some documentation. E.g. I think it's currently **not** possible to keep this info in the manifest. Instead you need to add a CLI options when you push your app, or use cf-cli to create the route and map it to the app after the fact.

Putting all this in the manifest would be great.

**Comment by abbyachau** [comment]
cc @shalako

**Comment by shalako** [comment]
A couple of weeks ago I went looking for docs that describe how to use the application manifest to specify routes for an app. I couldn't find any. @abbyachau if you know where to find them, please point them out? I expect to find it here: https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html, but that doc doesn't mention routes at all. I created an Aha card (internal) https://pcf.aha.io/features/NTWRK-70 and will reference this evidence there.

More specifically, I hear the ask as "How to map a TCP route to my app using a manifest?" I'll have to look into it.

**Comment by dkoper** [comment]
Hi Shannon,
I noticed the attributes have been moved to a separate reference page, referenced from the page you linked, under "App Manifest Attribute Reference". That lists the attributes related to routes, with an example of a TCP route.

**Comment by till** [comment]
@dkoper the example only works when you have a port to reserve. E.g., a random port, not sure what to do for that. How to even know which port I can reserve 🤷‍♂? So many questions.

**Comment by shalako** [comment]
Right, it looks like @till wants the manifest equivalent of `cf map-route APP_NAME DOMAIN_NAME --random-port`

**Comment by shalako** [comment]
From the docs at https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#random-route
It appears that the following manifest snippet will generate a TCP route with a random port:

```
---
applications:
- name: test
  memory: 128M
  domain: tcp.com
random-route: true
```

**Comment by heyjcollins** [comment]
With the GA of the v7 CLI, we're no longer actively developing against the v6 line.  With an interest the overall hygiene of the CLI project we're closing this  issue.
If this issue is still occurring in v7 please feel free to comment and re-open. Thank you!
