### ISSUE TITLE
cf curl to support -d @- like curl does

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cli#1167]
In `curl` you can pass thru STDIN using `-d @-` (see https://curl.haxx.se/mail/archive-2002-01/0093.html) but I tried this with `cf curl` and the error is:

```
cf curl /v2/apps/5ce9f4b7-7485-464d-bdaa-d683fc994f00/droplet/upload -X PUT -d @-
FAILED
open -: no such file or directory
```

Could we add support for `-d @-` syntax to read from STDIN?

**Comment by dkoper** [comment]
If the purpose is to upload a droplet, we have a story for push to support droplet upload, which is scheduled before a `curl` themed release.

**Comment by abbyachau** [comment]
Hi @drnic thanks for creating this issue. Could you let us know what your use case is for this feature request? That information would help us prioritise github issues. Thanks!

**Comment by drnic** [comment]
Uploading a droplet.

I think this still isn't possible via 1st class subcommands?

```
$ cf help -a | grep droplet
   v3-stage                           Create a new droplet for an app
   v3-droplets                        List droplets of an app
   v3-set-droplet                     Set the droplet used to run an app
```

**Comment by heyjcollins** [comment]
With the GA of the v7 CLI, we're no longer actively developing against the v6 line.  With an interest the overall hygiene of the CLI project we're closing this  issue.
If this issue is still occurring in v7 please feel free to comment and re-open. Thank you!
