### ISSUE TITLE
Allow import in manifest.yml

### ISSUE THREAD

**Issue by alfanse** [cloudfoundry/cli#1170]
`
map: []interface {}
13:10:58 	Aww shucks.

13:10:58 	Something completely unexpected happened. This is a bug in cf.

13:10:58 	Please file this bug : https://github.com/cloudfoundry/cli/issues

13:10:58 	Tell us that you ran this command:

13:10:58 		cf push -f classes/manifest-cert.yml

13:10:58 	using this version of the CLI:

13:10:58 		6.12.4-b4b6af1

13:10:58 	and that this error occurred:

13:10:58 		NewMap called with unexpected argument

and this stack trace:

13:10:58 		goroutine 1 [running]:
13:10:58 	main.generateBacktrace(0xc21000a000, 0x4)
13:10:58 		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:117 +0xa9
13:10:58 	main.handlePanics(0x7f39cf8b73a0, 0xc2101885c0)
13:10:58 		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:101 +0x123
13:10:58 	runtime.panic(0x89fc80, 0xc2101e9bc0)
13:10:58 		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
13:10:58 	github.com/cloudfoundry/cli/generic.NewMap(0xc2101e9aa0, 0x1, 0x1, 0x886160, 0xc210272d60)
13:10:58 		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/generic/map.go:56 +0x79b
13:10:58 	github.com/cloudfoundry/cli/generic.mergeReducer(0x89fc80, 0xc2101fc520, 0x89b480, 0xc2102b04b0, 0x7f39cf8badb0, ...)
13:10:58 		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/generic/merge_reduce.go:28 +0x1f7
13:10:58 	github.com/cloudfoundry/cli/generic.Reduce(0x7f39cf70a190, 0x2
`
Background, manifest-cert.yml imports manifest.yml (in same directory).
is that the problem?

**Comment by alfanse** [comment]
this might be a duplicate of https://github.com/cloudfoundry/cli/issues/895

**Comment by dkoper** [comment]
The trace seems to indicate you are using a cf CLI release of almost 2 years ago. Can you try on our latest? It's likely we have fixed this already.

**Comment by dkoper** [comment]
Closing. Feel free to reopen if reproducible on the latest cf CLI release.
