### ISSUE TITLE
CF CLI commands in no tty mode

### ISSUE THREAD

**Issue by rjain-pivotal** [cloudfoundry/cli#1172]
## Command  

I am using the `cf cli` in non tty mode, in `concourse` build pipelines as an `task` which executes a `shell` script

`cf login` 

## What occurred

If the cli command like `cf login` is supplied with wrong credentials, it doesn't fail but prompts for new password. In `non tty` env, like `concourse` tasks, this stalls the task and the pipeline

## What you expected to occur
`cf login` in non tty should exit, if there is a failure mode. 

## CLI Version  

all versions of cf cli

**Comment by dkoper** [comment]
Please use `cf api` and `cf auth` for non-interactive mode scripts. `cf login ` orchestrates those two (and `cf target`) for a more (beginning) user friendly experience with prompting.

**Comment by rjain-pivotal** [comment]
thanks. I will close this issue.
