### ISSUE TITLE
`/oauth/token` with refresh token does not set authorization header

### ISSUE THREAD

**Issue by aeijdenberg** [cloudfoundry/cli#1175]
Recent versions of the CLI seem to fail against older versions of the API for some operations, specifically those that require getting a new access token for a refresh token.

This appears to be fixed by supplying an `Authorization` header per <https://tools.ietf.org/html/rfc6749#section-2.3.1>.

## Command  

To demonstrate:

```
cf logs --recent  APPNAME
```

## What occurred

```
An Authentication object was not found in the SecurityContext
```

## What you expected to occur

Recent logs for application to be shown

## CLI Version  

```
cf version 6.27.0+d26b32dcc.2017-06-08
```

## CC API Endpoint Version  

```
api version:    2.43.0
```

## CF Trace

```
REQUEST: [2017-06-30T11:17:34+10:00]
POST /oauth/token HTTP/1.1
Host: uaa.system.[hidden]
Accept: application/json
Connection: close
Content-Type: application/x-www-form-urlencoded
User-Agent: cf/6.27.0+d26b32dcc.2017-06-08 (go1.8.3; amd64 darwin)
[PRIVATE DATA HIDDEN]

RESPONSE: [2017-06-30T11:17:34+10:00]
HTTP/1.1 401 Unauthorized
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Cache-Control: no-store
Content-Length: 108
Content-Type: application/json
Date: Fri, 30 Jun 2017 01:17:34 GMT
Expires: 0
Pragma: no-cache
Pragma: no-cache
Server: Apache-Coyote/1.1
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Www-Authenticate: Basic realm="UAA/client", error="unauthorized", error_description="An Authentication object was not found in the SecurityContext"
X-Cf-Requestid: d29d3687-8fb5-4b8f-76aa-d3f8da0cae03
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
{
  "error": "unauthorized",
  "error_description": "An Authentication object was not found in the SecurityContext"
}


An Authentication object was not found in the SecurityContext
```

## Platform & Shell Details  

Not relevant

## Any other relevant information  

The same cli tool works fine against another one of our environments that has a newer API:

```
api version:    2.75.0
```

**Comment by dkoper** [comment]
@aeijdenberg Would you mind downloading an edge release and confirm the issue is resolved?
https://github.com/cloudfoundry/cli#edge-binaries

Cheers,
Dies Koper
CF CLI PM

**Comment by aeijdenberg** [comment]
Hi @dkoper - the new binary appears to work, thanks.

**Comment by dkoper** [comment]
Incorporated in cf CLI 6.29.0. Thanks again for reporting it and submitting the PR.

Cheers,
Dies Koper
CF CLI PM
