### ISSUE TITLE
add-plugin-repo does not work if specified URL contains a path value

### ISSUE THREAD

**Issue by bsvihovec** [cloudfoundry/cli#1178]
## Command  

cf add-plugin-repo FOO https://< hostname >/cli

## What occurred

Could not add repository 'FOO' from https://< hostname >/cli: HTTP Response: 404 Not Found
HTTP Response Body: {"message":"","statusCode":404}
FAILED

## What you expected to occur

The plugin repository should have been added correctly.  (Insert a valid hostname for your plugin repository)

## CLI Version  

cf version 6.28.0+9e024bdbd.2017-06-27

## CF Trace

REQUEST: [2017-07-07T14:44:33-04:00]
GET /list HTTP/1.1
Host: < hostname >
Accept: application/json
Content-Type: application/json
User-Agent: cf/6.28.0+9e024bdbd.2017-06-27 (go1.8.3; amd64 darwin)

RESPONSE: [2017-07-07T14:44:33-04:00]
HTTP/1.1 404 Not Found
Connection: Keep-Alive
Content-Type: application/json
Date: Fri, 07 Jul 2017 18:44:33 GMT
Strict-Transport-Security: max-age=31536000
X-Backside-Transport: FAIL FAIL
X-Frame-Options: SAMEORIGIN
X-Global-Transaction-Id: 2096987929
{
  "message": "",
  "statusCode": 404
}

## Platform & Shell Details  

Mac OS X 10.12.4 iTerm

## Any other relevant information  

It looks like the command is removing the path (i.e. /cli) from the specified repository and then appending '/list' to the hostname.  This results in a 404 because https://< hostname >/cli/list exists, but https://< hostname >/list does not.

I believe I confirmed this by changing the protocol to 'http1s://' which results in the following being printed by cli/cf/commands/pluginrepo/add_plugin_repo.go :: verifyURL 

Could not add repository 'FOO' from http1s://< hostname >/cli: Get http1s://< hostname >/list: unsupported protocol scheme "http1s"

This same command works in version 6.26

**Comment by dkoper** [comment]
Addressed in cf CLI 6.29.0. Thanks again for reporting it.

Cheers,
Dies Koper
CF CLI PM
