### ISSUE TITLE
'cf help' should show 'unset-env' command

### ISSUE THREAD

**Issue by tjarratt** [cloudfoundry/cli#1179]
## Command  

cf help

## What occurred

It prints a few things, but not 'unset-env'

## What you expected to occur

It should totally print this command, because I forgot how to do it.

## CLI Version  

cf version 6.28.0+9e024bdbd.2017-06-27

**Comment by dkoper** [comment]
Hi @tjarratt 

We intentionally don't display all commands. You probably remember what help looked like a year ago, several pages of text scrolling over the screen and without grep it was impossible to find anything fast.

We addressed that by reducing `cf help` to only show the most commonly used app developer commands. The rest is available under `cf help -a`.

I image you would agree that in general `set-env` is used more than `unset-env`, just like `push` is used more than `delete` and `run-task` more than `terminate-task`. That is why we left `unset-env` out and are able to keep `cf help` to a concise list of no more than a single page.

Regards,
Dies Koper
CF CLI PM

**Comment by tjarratt** [comment]
Ah, I see. It's still a little hard to find, I think I had to run through the following commands in order to find it.

```
cf help
cf help set-env
cf help --all
cf --help
```

Would it be possible to maybe add a note to the help page for `set-env` that `unset-env` exists ? That would greatly increase the ability for me to remember how to find that command's help.

**Comment by dkoper** [comment]
We can look into that.
But if the first command you ran was `cf help`, which displays `These are commonly used commands. Use 'cf help -a' to see all, with descriptions.` at the end, which I assume you missed, would you have picked up anything at the end of `cf help set-env`?

**Comment by dkoper** [comment]
We have added `unset-env` to `set-env`'s SEE ALSO in cf CLI 6.29.0.
