### ISSUE TITLE
Request for Clarification: manifest.yml format

### ISSUE THREAD

**Issue by dannmartens** [cloudfoundry/cli#1180]
The CLI currently allows manifests without an applications: block. This does not align with the documentation which tells us that a minimal manifest always contains an applications: block in the yaml.

The CLI might allow this on account of a documented feature which “promotes” duplicate content, but does so even if an applications: block is missing. That way an application name: value gets promoted to the name value of a single and only application, regardless of the presence of an applications: block.

This "allowed" syntax breaks other clients, e.g. the Java client which does require an actual applications: block to be present. In turn, that breaks the Atlassian Bamboo Cloud Foundry add-on.

Would it be possible to clarify whether this is intended? None of the test fixtures support this. Yet, unfortunately, I see users thinking this is proper syntax and causing a lot of support requests.

**Comment by dkoper** [comment]
Hi @dannmartens 
CC: @nebhale 

Apologies for the delayed response - it took a while to find out the history of this.

Originally when the app manifest file was first supported, there was no `applications:` field: the app manifest catered for only one app.
At some point (way before my time), multi-app support was added with `applications:` and the root level fields became the "promoted content" feature, so as not to break things for existing users.

I'll discuss the inconsistency with the Java client library with Ben.

Regards,
Dies Koper
CF CLI PM

**Comment by dannmartens** [comment]
Hi Dies,

Thanks for the feedback!

Part of the confusion stems from a 'base' test fixture like https://github.com/cloudfoundry/cli/blob/master/fixtures/manifests/base-manifest.yml using the applications: block. Since there doesn't appear to be any regression protection test for the legacy situation, I had no indication this should be supported.  

Cheers,
 Dann

**Comment by nebhale** [comment]
Looking over our code, we require and `applications` block _in the resolved manifest_ only.  We treated the [documentation](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html) as a spec and it makes allowances for an [inherited manifest to have content at the root](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-operations/src/test/resources/fixtures/manifest-charlie.yml) which is then included in all items in a `applications` block and then vice-versa, allowing [overrides at the root to apply to all included `applications`](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-operations/src/test/resources/fixtures/manifest-delta.yml).

I'm not totally sure how you can reconcile an "inheritable" definition for an application with a "root" application definition though, so I'm not a huge fan of updating the spec to support it, historical precedent or not.

**Comment by dkoper** [comment]
@dannmartens Based on the results from the recent app manifest simplification feedback, we have decided to deprecate promoted content above the `applications:` block. You should now see a deprecation warning message when using such manifest file. See cf CLI 6.34.0's [release notes](https://github.com/cloudfoundry/cli/releases/tag/v6.34.0) for details.
