### ISSUE TITLE
cf tasks <app-name> very slow when app has a large number of tasks

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cli#1182]
## Command  

`cf tasks myapp`

## What occurred

When an app has a large number of tasks (some apps have hundreds of thousands), the command appears to hang indefinitely.  When run with the `-v` flag it reveals that it is continuously fetching pages of tasks from CC and won't finish until there are no longer any pages left.

I tested it locally against a bosh-lite with an app that had ~12500 tasks under it and the CLI took around thirty seconds to return.  In the past I've run it against a real deployment for an app with ~400,000 tasks and it took around thirty minutes.

In production CF environments I've noticed that users are scheduling frequent short running tasks and amassing pretty large numbers of tasks for their apps.  Cloud Controller does prune old tasks ([default is every 31 days](https://github.com/cloudfoundry/cloud_controller_ng/blob/5c5f429768a6824c95f090d6c8b879b76d7d17aa/bosh/jobs/cloud_controller_clock/spec#L119-L121)), but if a user runs just one task a minute for the month they'll hit ~45,000 tasks and start having issues.

## What you expected to occur

I expected to be able to view recent tasks for the app in a reasonable amount of time.

## CLI Version  

`cf version 6.28.0+820a06044.2017-06-30`

## CC API Endpoint Version  

* v2: `2.89.0`
* v3: `3.24.0`

Thanks!

**Comment by johngrogg** [comment]
Having encountered this issue in our production environment, can I suggest that two new options would be most useful:

1. A `Running` option that only displays tasks that are currently running
2. A `Recent` option that displays tasks within some time window?

Alternatively to the second option, a way to put in a start and end time that filters tasks out based on the task's `created_at` attribute could be more flexible and meet the same need.

**Comment by dkoper** [comment]
@tcdowney @johngrogg With the environments/cases you have seen, how many tasks would have returned if filtered by "running"? What would be a reasonable time window and how many tasks would that return?

**Comment by tcdowney** [comment]
@dkoper @mpivotal
I've personally only needed to run `cf tasks` when troubleshooting why a task failed or to see what I have running when I've hit my resource quotas (:+1: to @johngrogg's suggestion for a `recent` option and perhaps even a `failed` option).  

The vast majority of the tasks I've used usually succeed and are short lived so there have never been more than a few dozen failures a day or a handful running at the same time for a given app.

As to a reasonable time window, I've seen apps that use tasks for nearly everything (spawning one every second or more) and apps that use them quite sparingly.  I'm not sure if there is a one-size-fits-all time window, but it seems like a `--recent` flag could return like the last 500 or something.  It would just be nice for it to finish in under a second or two.

**Comment by JamesClonk** [comment]
Has there been any progress on this issue?
I'm facing the same problems currently with some of my apps, as I'm running a task every minute. The CLI hangs up and freezes when running `cf tasks` for my app. 😢

**Comment by abbyachau** [comment]
Hey @JamesClonk thanks for this. Sorry this issue's been open so long. I'm interested in whether there could be CC API changes that might help us fetch information without continuously querying. @ssisil or @selzoc @Gerg?

There's a host of CF CLI performance related issues that have cropped up recently (services, routes on v7, apps on v7) which, if no changes can be made on the CC API side, then it would be good, if it is possible, to converge on a way to handle list commands that may return many resources.  cc @ewrenn8 @acrmp any thoughts?

**Comment by selzoc** [comment]
It looks like you can already filter on state of a task: http://v3-apidocs.cloudfoundry.org/version/3.75.0/index.html#list-tasks-for-an-app

Perhaps the CLI could offer the option of retrieving only tasks in a particular state?  Also, maybe display just the first _n_ results, and have the user override to query for all of them?

**Comment by JamesClonk** [comment]
I'm mostly interested in something like `--recent` to display the most recent task runs, and `--failed` or `--state FAILED` or something like that. Maybe even the possibility to combine these. I think it'd certainly be useful to be able to view just the last *n* tasks, the most recent tasks. Maybe even make that the default behaviour to avoid accidental CLI freezes.

**Comment by emalm** [comment]
There might be something to learn from the filtering and recent-history options on `bosh tasks`, along with common-case defaults.

**Comment by abbyachau** [comment]
Hi all thanks, we'll take a look at this at pre-ipm and will report back.

**Comment by heyjcollins** [comment]
With the GA of the v7 CLI, we're no longer actively developing against the v6 line.  With an interest the overall hygiene of the CLI project we're closing this  issue.
If this issue is still occurring in v7 please feel free to comment and re-open. Thank you!
