### ISSUE TITLE
GET to resource_match

### ISSUE THREAD

**Issue by mkljakubowski** [cloudfoundry/cli#1183]
## Command  

cf push -f manifest.yaml

## What occurred

404 while resource match, getting error code 10000
cf-cli tries to do GET in an URL that seems to accept only PUTs

## CLI Version  
`cf version 6.28.0+9e024bdbd.2017-06-27`

## CC API Endpoint Version  
`API version: 2.69.0`

## CF Trace

```
POST /oauth/token HTTP/1.1
HTTP/1.1 200 OK
GET /v2/spaces/d52f39eb-6e37-4c4d-9d6b-7f9bd911b679/apps?q=name%3Ared0&inline-relations-depth=1 HTTP/1.1
GET /v2/spaces/d52f39eb-6e37-4c4d-9d6b-7f9bd911b679/apps?q=name%3Ared0&inline-relations-depth=1 HTTP/0.0
HTTP/1.1 200 OK
PUT /v2/apps/31ecf51a-4970-4177-b9f9-051c95c9712f?async=true&inline-relations-depth=1 HTTP/1.1
GET /v2/apps/31ecf51a-4970-4177-b9f9-051c95c9712f?async=true&inline-relations-depth=1 HTTP/0.0
HTTP/1.1 200 OK
GET /v2/organizations/0927e0db-a1dd-4aae-9bbf-022035c00a19/private_domains HTTP/1.1
GET /v2/organizations/0927e0db-a1dd-4aae-9bbf-022035c00a19/private_domains HTTP/0.0
HTTP/1.1 200 OK
GET /v2/shared_domains?inline-relations-depth=1 HTTP/1.1
GET /v2/shared_domains?inline-relations-depth=1 HTTP/0.0
HTTP/1.1 200 OK
GET /v2/routes?inline-relations-depth=1&q=host%3Ared0%3Bdomain_guid%3Aca592235-5612-47f6-88c8-031a42d40f27 HTTP/1.1
GET /v2/routes?inline-relations-depth=1&q=host%3Ared0%3Bdomain_guid%3Aca592235-5612-47f6-88c8-031a42d40f27 HTTP/0.0
HTTP/1.1 200 OK
PUT /v2/resource_match HTTP/1.1

--- and then ---

REQUEST: [2017-07-20T16:28:55+02:00]
GET /v2/resource_match HTTP/0.0
Host: company-cf-instance.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Referer: http://company-cf-instance.com/v2/resource_match
User-Agent: go-cli 6.28.0+9e024bdbd.2017-06-27 / darwin


RESPONSE: [2017-07-20T16:28:55+02:00]
HTTP/1.1 404 Not Found
Connection: close
Content-Length: 86
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/json;charset=utf-8
Date: Thu, 20 Jul 2017 14:28:55 GMT
Expires: 0
Pragma: no-cache
Server: nginx
Strict-Transport-Security: max-age=15768000; includeSubDomains
X-Cascade: pass
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Vcap-Request-Id: 970a9a3d-3a0d-450d-560d-d04ff073312a::c5278654-093c-41f2-8ff9-60fac3e187d3
X-Vcap-Request-Id: 970a9a3d-3a0d-450d-560d-d04ff073312a
X-Xss-Protection: 1; mode=block

{
  "code": 10000,
  "description": "Unknown request",
  "error_code": "CF-NotFound"
}
FAILED
Error processing app files: Error uploading application.
Server error, status code: 404, error code: 10000, message: Unknown request
```
## Platform & Shell Details  
Mac OS terminal

## Any other relevant information  
There is a proxy between me and CF. About 50 different requests pass and then this one breaks.

**Comment by nickwei84** [comment]
@mkljakubowski Hi, could you please include more of your trace log around the GET request to "/v2/resource_match". It would help us in our efforts to recreate this scenario. Could you also show us the contents of your manifest.yaml? Thanks.

**Comment by mkljakubowski** [comment]
[Trace from whole process](https://gist.github.com/mkljakubowski/994183e2c8c77372ab6b4b5c6f4b696b)
[Manifest](https://gist.github.com/mkljakubowski/8c6d9619c011dbe4df5a6a34b11f92cd)

**Comment by mariash** [comment]
Hi @mkljakubowski, we are suspecting there is an issue with redirect/proxy server in between cloud controller and cli. We pushed a possible solution to branch https://github.com/cloudfoundry/cli/tree/handle-redirect-better. If you don't mind could you test this version? You need to clone this repo, checkout `handle-redirect-better` and run `bin/build` and run it from `./out/cf`. Let us know if that would work for you? And could you provide trace logs with the new version?

**Comment by nickwei84** [comment]
@mkljakubowski Could you please also include any logs from your proxy server? Thanks.

**Comment by mariash** [comment]
@mkljakubowski we suspect that your server that is running between cloud controller and cli is returning incorrect response code. It looks like it is sending the redirect back to any request (GET and POST). If it needs to repeat POST request it needs to send 307 status code. See https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection
Because looking at the trace logs you can see that CLI sends PUT request to /v2/resource_match and then getting redirected to /v2/resource_match and is trying to make a GET request which cloud controller cannot handle.

**Comment by mkljakubowski** [comment]
The problem was that I was doing cf login over http not over https. Proxy wasn't actually on the way.
Thanks for help!
