### ISSUE TITLE
File is not a valid cf CLI plugin binary

### ISSUE THREAD

**Issue by sorvis** [cloudfoundry/cli#1184]
## Command  
cf install-plugin .\pcfdev-v0.26.0+PCF1.10.0-windows.exe

## What occurred
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to install the plugin .\pcfdev-v0.26.0+PCF1.10.0-windows.exe? [yN]: y
y
dial tcp 127.0.0.1:43004: socket: An invalid argument was supplied.
exit status 1
File is not a valid cf CLI plugin binary.
FAILED

## What you expected to occur
The plugin to install

## CLI Version  
6.28.0+9e024bd.2017-06-27

## CC API Endpoint Version  
No api set

## CF Trace
dial tcp 127.0.0.1:12130: An invalid argument was supplied.
exit status 1
File is not a valid cf CLI plugin binary.
FAILED

## Platform & Shell Details  
Wndows 7 64 bit Enterprise
* Powershell
* normal command prompt
* MINGW32

## Any other relevant information  
I've seen the issue with both a plugin I downloaded and a different one that it automatically downloaded from the CF-Community repository. I already submitted an [issue to CF-Dev](https://github.com/pivotal-cf/pcfdev/issues/248) but then realized its broader then that extension.

In searching through other issues it sounds like [this one is similar](https://github.com/cloudfoundry/cli/issues/1162).

**Comment by dkoper** [comment]
Hi @sorvis 

Yes, that issue looks the same. And our issue is the same: we were not able to reproduce it and without access to the source code we were not able to investigate deeper.
Can you provide the full output of this issue with a plugin that source code is available for, such as one from the CF-Community plugin repository?

Cheers,
Dies Koper
CF CLI PM

**Comment by sorvis** [comment]
Hi Dies,

I am able to reproduce this with other plugins:

`PS C:\Users\sorvis\Downloads\pcfdev-v0.26.0+PCF1.10.0-windows> cf install-plugin -r CF-Community "Live Stats"
Searching CF-Community for plugin Live Stats...
Plugin Live Stats 1.0.0 found in: CF-Community
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to install the plugin Live Stats? [yN]: y
y
Starting download of plugin binary from repository CF-Community...
 7.64 MiB / 7.64 MiB [=====================================================================================] 100.00% 0s
dial tcp 127.0.0.1:44194: An invalid argument was supplied.
exit status 1
File is not a valid cf CLI plugin binary.
FAILED`

**Comment by mariash** [comment]
@sorvis I suspect this is some kind Windows firewall issue?.. I would check the firewall rules to allow connections to `127.0.0.1` from your CLI process.

This is the output of the command in my Windows environment:
```
PS C:\Users\IEUser\Downloads> .\cf.exe install-plugin -r CF-Community "Live Stats"
Searching CF-Community for plugin Live Stats...
Plugin Live Stats 1.0.0 found in: CF-Community
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to install the plugin Live Stats? [yN]: y
y
Starting download of plugin binary from repository CF-Community...
 7.64 MiB / 7.64 MiB [=====================================================================================] 100.00% 0s
Installing plugin Live Stats...
OK
Plugin Live Stats N/A successfully installed.
PS C:\Users\IEUser\Downloads> .\cf.exe  -v
cf.exe version 6.28.0+9e024bd.2017-06-27
```

**Comment by AubieDawg92** [comment]
@mariash Can you explain what port(s)/protocols would possibly need to be open to install a plug-in?  Every time it fails, the port number reported in the error is different.  I setup a simple tcp socket application on the box which is failing to listen and make a connection on "localhost".  This worked without issue.  So I really have trouble with the concept of the issue being some kind of "firewall" issue.  What is the plugin installation trying to communicate with?

**Comment by dkoper** [comment]
@AubieDawg92 Please take a look at the [plugin architecture documentation here](https://github.com/cloudfoundry/cli/blob/master/plugin/plugin_examples/README.md#architecture-overview).
My understanding here is:
1. `cf install-plugin` downloaded the plugin binary and now wants to execute it to retrieve its metadata (plugin name, commands, command help, minimum CLI version, ...) to complete the installation process.
2. To retrieve this metadata, the CLI starts a (Golang) RPC server on a random port on localhost and invokes the plugin binary. To the plugin binary it passes the RPC server connection details.
3. I'm assuming the cf CLI is failing to start the RPC server because it cannot open a socket to the port, hence failing to complete plugin installation.

Googling around, a common cause is the existance of a program on Windows (Firewall, etc.) blocking this access. There are also various reports of Golang bugs, hence first trying to rule out any environment issues.

BTW, do you get the same issue on every installation attempt? Does each attempt display a different port number in the error message? If you have managed to install any CLI plugins successfully, do any fail ever with a similar error when executing a plugin command?

**Comment by AubieDawg92** [comment]
@dkoper Every installation attempt fails and displays a different port number.  I have not managed to install a plugin.  I tried monitoring the process with netsh and I do see a number of ports being opened; however, the ultimate reported port number in the error message is not one of the ports which gets opened.

**Comment by dkoper** [comment]
Thanks for that. We made a lot of improvements to the plugin experience in cf CLI 6.27.0. Have you tried an older version, see if we broke something?

**Comment by nickwei84** [comment]
@AubieDawg92 Can you please try installing this plugin on a different machine? One without windows firewall enabled? Also can you attempt the same on a non-Windows machine? Hopefully we can narrow down if this is an environment/platform, CLI code, or plugin code issue.

**Comment by dkoper** [comment]
@sorvis @AubieDawg92 @tryingT

As we can't reproduce the issue locally, we're flying blind.
Issues reported in the Golang tracker indicate causes could be a Windows firewall, or possibly a Golang issue on Windows where ports are not closed properly (hence the request above to try on another machine, or when it occurs, reboot your machine and try again straight after (ensuring ports are closed)).

Based on those results, we could try writing a small test application that does the bare minimum of starting an RPC server using the same APIs the cf CLI uses and see if we can pinpoint the issue, perhaps even find a simple reproducible test case we can share with the Golang developers.

Regardless, we'll need some effort, and patience, on your side to help us with that.

Closing this issue for now for lack of response.
I invite anyone who can reproduce this issue and has the time to investigate this with us, to re-open this issue and reach out. Thanks!

**Comment by rowland66** [comment]
Has any progress been made on this issue? I am experiencing the same on Windows.

**Comment by dkoper** [comment]
@rowland66 @clazarrr We couldn't reproduce it. If you can reproduce this on the latest cf CLI release and have the time to investigate this with us, please re-open this issue and reach out to us.
