### ISSUE TITLE
cf push with invalid hostname should lead to an error

### ISSUE THREAD

**Issue by jsievers** [cloudfoundry/cli#1185]
## Command  

`cf push --hostname test_underbar`

## What occurred

cf push succeeds and the app can be accessed, but the route registered

`urls: test_underbar.<APPS_DOMAIN>`

is using an invalid hostname according to
https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_hostnames

because it contains an underbar character.
This can lead to problems with clients that validate the URL.
E.g. 
`new java.net.URI("https://test_underbar.sample.com").getHost()`

returns null

## What you expected to occur

cf push should fail with an error message. Actually if you try using other invalid characters like e.g. % (percent), you get an error message:
```
FAILED
Server error, status code: 400, error code: 210001, message: The route is invalid: host format
```
I would expect a similar error message for hostnames containing the underbar character.

If you try to push e.g. a hostname containing spaces,
```
$ cf push --hostname 'a b'
Creating route a%20b.<APP_DOMAIN>
OK

FAILED
Server error, status code: 400, error code: 210001, message: The route is invalid: host format
```

you see that it tries to URL-encode the hostname 'a b' to 'a%20b' which would be correct for the path segment of a URL, but not for a hostname.

By contrast, if you specify underbars in the app name (not the host), the route created will automatically have underbars (or spaces for that matter) replaced by dashes to form a valid hostname:

```
$ cf push test_underbar

Creating route test-underbar.<APP_DOMAIN>
OK

Binding test-underbar.<APP_DOMAIN> to test_underbar...

```

The docs for cf push hosts
https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#hosts

even use an example with underbars in the hostnames.

Since 'host' can also be used to specify a subdomain, not sure how to distinguish this scenario because for subdomain names, underbar is allowed according to

https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_hostnames
and 
https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it

## CLI Version  

cf version 6.28.0+9e024bdbd.2017-06-27

## CC API Endpoint Version  

$ cf api
api endpoint:   <REDACTED>
api version:    2.89.0

## Platform & Shell Details  

Mac OS 10.12.6, iTerm, bash

**Comment by dkoper** [comment]
Hi @jsievers 

I don't think it's the cf CLI's job to enforce the naming convention here. If there is to be validation (and it appears there is for `%`), it should be on the server side so all clients are prevented from creating such hostnames. I suggest you open an issue on the cloud controller repo.
That said, our documentation should not use example hostnames that could cause issues.

Regards,
Dies Koper
CF CLI PM

**Comment by jsievers** [comment]
created https://github.com/cloudfoundry/cloud_controller_ng/issues/859

**Comment by dkoper** [comment]
Closing this one in favour of that one. Your output shows that the CLI properly displays the server error if any.
