### ISSUE TITLE
cf auth & cf login behave different depending if the api target has a trailing slash

### ISSUE THREAD

**Issue by dprotaso** [cloudfoundry/cli#1186]
## Command  

First flow
```
cf api https://some.domain.com/ --skip-ssl-validation
cf auth [username] [password]
cf orgs
```

Second flow
```
cf api https://some.domain.com/ --skip-ssl-validation
cf login (then enter a user name and password)
cf orgs
```

## What occurred

The first flow utilizing `cf auth` fails when calling `cf orgs` with a HTTP 404

## What you expected to occur

Both flows list the orgs the user has access to

## CLI Version  

Experienced this issue with the following versions
cf version 6.26.0+9c9a261.2017-04-06
cf version 6.28.0+9e024bdbd.2017-06-27

## Any other relevant information  

The `~/.cf/config.json` produced when calling `cf auth` is missing a lot of `*Endpoint` values

**Comment by dkoper** [comment]
We have fixed this in cf CLI 6.29.1. Thanks again for the report.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM
