### ISSUE TITLE
terminal.WarningColor prints messy code on windows platform

### ISSUE THREAD

**Issue by wenchma** [cloudfoundry/cli#1187]
## Command  

```
C:\Users\IBM_ADMIN>cf uninstall-plugin IBM-ActivityTracker
Uninstalling plugin IBM-ActivityTracker...
[35;1mThanks for using IBM-ActivityTracker plugin![0m
OK
```

## What occurred

messy code occurs

## What you expected to occur

colorful print without messy code

## CLI Version  

cf version 6.29.0+ff886fa.2017-07-24

**Comment by nickwei84** [comment]
@wenchma the `terminal` package was not written as a library for external use. We recommend that you use this repo to colorize your plugin output: https://github.com/fatih/color 

We are in the process of refactoring large portions of the code base and we are moving away from the `terminal` package in favor of the above library.

**Comment by dkoper** [comment]
Closing, I believe the question's been answered.
