### ISSUE TITLE
Windows installer select destination folder does not shown on already cli installed system

### ISSUE THREAD

**Issue by ibakirov** [cloudfoundry/cli#1188]
## Command  
Download latest Windows x64 installer

## What occurred
Select destination folder does not shown on system where cli is already installed

## What you expected to occur
Select destination folder should be always shown on installing cli

## CLI Version  
cf version 6.29.0+ff886fa.2017-07-24

## CC API Endpoint Version  
api endpoint:   https://api.run.pivotal.io
api version:    2.89.0

## Platform & Shell Details  
Windows 10 Eng 64-bit

## Any other relevant information  
Steps for reproduce:

1. Download latest Windows cli installer
2. Install cli to default or desired folder (Select destination folder appears)
3. Ensure cli -v is working
4. Run cli installer again (Case when you want upgrade old cli version with new one)
5. Installer automatically installs cli to C:\Program Files\Cloud Foundry folder without asking destination folder (Select destination folder does not appear)

**Comment by dkoper** [comment]
Hi @ibakirov 

The idea of an update install (which is what you get when the installer detects an existing cf CLI (there is a registry setting it checks) is that it updates the CLI in place.
If you want to change the installation folder, please uninstall and then run the installer.

Regards,
Dies Koper
CF CLI PM

**Comment by ibakirov** [comment]
@dkoper 
I understand the idea, but whenever you install cli for example to D:\apps\cli and then you when you try to install again, installer won't detect installed path and installs automatically C:\Program Files\Cloud Foundry

I think there might something wrong with detection and you got two different installations of cli.

**Comment by dkoper** [comment]
ah sorry, I misunderstood. I could reproduce the issue - we'll investigate. Thanks for the report!

**Comment by abbyachau** [comment]
Hi @ibakirov thanks, sorry this issue has been unresolved for so long. We are going to try to reproduce this first and will provide an update soon. Thanks.

**Comment by JenGoldstrich** [comment]
Hey @ibakirov, @a-b and I were able to reproduce this issue on a Windows 10 machine, using the current CF installer (6.47.2) for 64 bit Windows, the installer detects somehow if you ran it before, and installs Program Files regardless of where you put the original installation, would it make sense for it to just always prompt for a install location?

**Comment by ibakirov** [comment]
@JenGoldstrich I agree, to always prompt for a installation location.

**Comment by ericpromislow** [comment]
Hi @ibakirov

You can download an "edge" installer with this fix from:

[32-bit](https://s3-us-west-1.amazonaws.com/cf-cli-releases/master/cf-cli-installer_edge_win32.zip)

[64-bit](https://s3-us-west-1.amazonaws.com/cf-cli-releases/master/cf-cli-installer_edge_winx64.zip)

This doesn't support changing the destination directory on subsequent installs; you'll still need to uninstall the package to do that.

We'll appreciate if you could test this out and let us know the results.

Thanks,
Eric Promislow and @acrmp

**Comment by ibakirov** [comment]
@ericpromislow thanks!

Tested 64-bit version, on fresh install it prompts for installation directory and on upgrade/reinstall installer automatically finds previous installation directory.
