### ISSUE TITLE
Problem with CF event lifecycle

### ISSUE THREAD

**Issue by JuergenFrank** [cloudfoundry/cli#1190]
I intend to inspect the events defined in the Cloud Foundry API https://apidocs.cloudfoundry.org/268/ in order to verify that the deletion of an org or a space including all service instances has been successful. The defined CF events should in principle provide most of the information. (Organization lifecycle events are still missing, cf. https://github.com/cloudfoundry/cloud_controller_ng/issues/758)

## Command  

```
cf curl "/v2/events?q=space_guid:<my-space-guid>"
cf curl "/v2/spaces/<my-space-guid>?recursive=true&async=true" -X DELETE
cf curl "/v2/events?q=space_guid:<my-space-guid>"
```

## What occurred

I had created a space with a few deployed apps and service instances bound to the apps. The first command showed me the corresponding audit. The third command, after deletion of the space and everything contained therein, did not yield any event. 

## What you expected to occur
I had expected to see all events for the space I had ssen previously plus the ones resulting from the deletion of all entities in the space including the space deletion event itself. 

## CLI Version  

6.29.0+ff886fa.2017-07-24

## CC API Endpoint Version  

2.89.0

## CF Trace
./.

## Platform & Shell Details  

Windows 10 64-bit with PowerShell

## Any other relevant information  
./.

**Comment by dkoper** [comment]
Hi @JuergenFrank 
This sounds like a question about the APIs, not about the CLI itself? If so, the [CAPI team](https://github.com/cloudfoundry/cloud_controller_ng/issues) would be the better team to ask.

**Comment by JuergenFrank** [comment]
Hi @dkoper, you are probably right. Afaik, there is no means for moving the issue in GitHub. Should I close this and open another one on CAPI?

**Comment by dkoper** [comment]
Yes please. I could move over the linked tracker story, but I'd prefer to close this issue as there's not much our team can help with.

**Comment by JuergenFrank** [comment]
Closing issue and creating new one on CAPI.
