### ISSUE TITLE
cf restage should return non-zero exit code when it fails

### ISSUE THREAD

**Issue by TimGerlach** [cloudfoundry/cli#1195]
## Command  

```shell
cf push myapp
cf bind-service myapp my-service # service that will lead to staging errors
cf restage myapp # fails
echo $? # 0
```

## What occurred

`cf restage` fails due to problems with newly bound service. CLI command returns 0 though.

## What you expected to occur

To allow proper scripting around the CF CLI inlcuding error handling the expected behaviour is a non-zero exit code.

## CLI Version  

`cf version 6.28.0+9e024bd.2017-06-27`

## CC API Endpoint Version  

`api version:    2.89.0`

## Platform & Shell Details  

Mac OS X 10.12.6 iTerm

**Comment by dkoper** [comment]
Hi @TimGerlach 

We refactored the restage command in cf CLI 6.29.0. Can you confirm you still encounter the issue with the latest release, and if so, provide more details on how to reproduce (what kind of service should I bind to cause the staging error)? I tried with a local app and could not reproduce the issue.

Cheers,
Dies Koper
CF CLI PM

**Comment by TimGerlach** [comment]
Hi @dkoper 

Just verified that `cf restage` works as expected with the latest version ` 6.29.0+ff886fa93.2017-07-24`. With this version, the command returns a non-zero exit code if restaging fails.

Thanks for pointing this out.

Feel free to close.

Cheers,
Tim

**Comment by dkoper** [comment]
Thanks for checking and reporting back!
