### ISSUE TITLE
Getting the following error whenever I am trying to execute any cf command.

### ISSUE THREAD

**Issue by agishita** [cloudfoundry/cli#1199]
←[31;1mFAILED←[0m
Error read/writing config:  unexpected end of JSON input

**Comment by dkoper** [comment]
Please delete your $HOME/.cf/config.json and target your endpoint & log in again (`cf login -a ...`).
There are rare cases that we haven't all been able to address yet where this file (which the CLI uses to store your targeted endpoint, space, etc.) can get corrupted.

**Comment by agishita** [comment]
Thanks for the response..
But I don't see .cf folder anywhere. Can u help me locate this folder?

**Comment by dkoper** [comment]
What platform are you on?
It defaults to `~/.cf`, `$CF_HOME/.cf`, `$HOME/.cf` or e.g. `c:\users\you\.cf`.

**Comment by agishita** [comment]
I am working on Windows-7 64-bit.
I am unable to see it at any of the above mentioned places. :( 

I also tried re-installing cloudfoundary, still the can't see the folder

**Comment by dkoper** [comment]
What do `dir %HOME%\.cf` and `dir %HOMEDRIVE%%HOMEPATH%\.cf` return?

**Comment by agishita** [comment]
I am in c:\users\you\ directory 
then ran the two commands as you have mentioned above

 dir %HOME%\.cf
The system cannot find the file specified.


dir %HOMEDRIVE%%HOMEPATH%\.cf
Volume in drive C is Windows
 Volume Serial Number is 78D6-ABB2

 Directory of C:\Users\212612243\.cf

08/10/2017  10:21 AM                 0 config.json
               1 File(s)              0 bytes
               0 Dir(s)  200,279,760,896 bytes free

**Comment by dkoper** [comment]
Do a `del %HOMEDRIVE%%HOMEPATH%\.cf\config.json` and you should be able to use `cf login` and start again.

**Comment by agishita** [comment]
This works :) 
Can u please explain what was the issue?

**Comment by dkoper** [comment]
Your config file got truncated to 0 bytes, causing the CLI to fail to read it's contents (an empty file is not valid JSON). We've seen the file getting truncated in a number of timing related circumstances:
- CLI run simultaneously in different terminals, where both processes try to save to the same file
- Aborting the CLI (with ctrl-c) while it was writing to the file

Glad to hear you got it working again!

Regards,
Dies Koper CF CLI PM
There may be other conditions as well that we haven't identified yet.

**Comment by dkoper** [comment]
FYI, we have made the window for this issue to occur much smaller in cf CLI 6.29.1. Thanks again for the report.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM

**Comment by ilovejs** [comment]
> Do a `del %HOMEDRIVE%%HOMEPATH%\.cf\config.json` and you should be able to use `cf login` and start again.

works in Command Prompt not in Powershell i believe
