### ISSUE TITLE
`cf help` doesn't show all the help.

### ISSUE THREAD

**Issue by sjolicoeur** [cloudfoundry/cli#1200]
## Command  

`cf help`

## What occurred

it only showed a subset of the commands.

## What you expected to occur

I would have expected to see all of the help options and text.

## CLI Version  

`cf version 6.29.0+ff886fa93.2017-07-24`

## CC API Endpoint Version  

`api version:    2.92.0`
 

## Any other relevant information  

I know the output is long and unwieldily, but unix has a nice way of dealing with such output: `grep`. As a new user it just looks like the command is broken and out of date with what can be found on the web, and diminishes the trust I have that the command actually works as I may be using bleeding edge features. 

The `-a`  modifier should be the option to show a reduced set. I do not believe there is much precedent for a help  command to only show abridged data.

Alternatively, a man file would be great.

**Comment by dkoper** [comment]
Hi @sjolicoeur,

Thanks for the feedback.
The decision to limit `cf help` output to be less wieldy was made after over a year of discussions and many years of complaints about its unwieldiness and people having to resort to using tools like grep to find anything.

We did a lot of research, approached the CF community for feedback and this is the result of that.

Displaying a subset and introducing a flag for a full list was modeled after `git`, which we believe most cf CLI users are very familiar with.

Also, we have explored introducing man pages and actually have stories in the backlog to implement them (we changed to a different command parsing library that helps generating them), but unfortunately higher priority stories keep coming up so not sure when we'll get to them.

Regards,
Dies Koper
CF CLI PM

**Comment by sjolicoeur** [comment]
@dkoper what about  making it more evident? 

*Before getting started:*
  config    login,l      target,t
  help,h    logout,lo

*Application lifecycle:*
  apps,a        run-task,rt    events
  push,p        logs           set-env,se
  start,st      ssh            create-app-manifest
  stop,sp       app
  restart,rs    env,e
  restage,rg    scale

*Services integration:*
  marketplace,m        create-user-provided-service,cups
  services,s           update-user-provided-service,uups
  create-service,cs    create-service-key,csk
  update-service       delete-service-key,dsk
  delete-service,ds    service-keys,sk
  service              service-key
  bind-service,bs      bind-route-service,brs
  unbind-service,us    unbind-route-service,urs

*Route and domain management:*
  routes,r        delete-route    create-domain
  domains         map-route
  create-route    unmap-route

*Space management:*
  spaces         create-space    set-space-role
  space-users    delete-space    unset-space-role

*Org management:*
  orgs,o       set-org-role
  org-users    unset-org-role

*CLI plugin management:*
  plugins           add-plugin-repo      repo-plugins
  install-plugin    list-plugin-repos

*Commands offered by installed plugins:*

*Global options:*
  --help, -h                         Show help
  -v                                 Print API request diagnostics to stdout

*Continued...*
*Use 'cf help -a' to see _all commands_,  and their descriptions.

See 'cf help <command>' to read about a specific command.

**Comment by dkoper** [comment]
@sjolicoeur 

I will discuss your suggestion with my designers. My first impression was that you truncated the beginning of the last sentence using *[...]*.

For my reference, `git` ends with the following and does not use different styling.
```
'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
```

**Comment by dkoper** [comment]
Ran it by my designer: he recommended we reduce clutter, in line with your suggestion, and reduce the final text to simply read:
```
Use 'cf help -a' to see all commands.
```

**Comment by sjolicoeur** [comment]
@dkoper good to hear there will be less clutter!  Thank you!

**Comment by aayushgc** [comment]
When I do cf help -a , it gives me an error 

$ cf help -a
FAILED
Incorrect Usage

Invalid flag: -a

NAME:
   help - Show help

USAGE:
   cf help [COMMAND]

ALIAS:
   h
can somebody help

**Comment by dkoper** [comment]
@aayushgc Looks like you may be using a (very) old cf CLI release. Try `cf -v`. Current release is 6.30.0.

**Comment by dkoper** [comment]
Suggestion was incorporated in our 6.29.2 release last week. Thank you for your feedback!
