### ISSUE TITLE
Something completely unexpected happened. This is a bug in cf.

### ISSUE THREAD

**Issue by thecomputerguyjeff** [cloudfoundry/cli#1202]
Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		cf push -f ./cts-leela-server-prod_manifest.yml -p ./build/libs/leela-0.0.1-SNAPSHOT.jar

	using this version of the CLI:

		6.12.2-24abed3

	and that this error occurred:

		runtime error: index out of range

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x6)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xa9
	main.handlePanics(0x116b9a0, 0xc210187570)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x123
	runtime.panic(0x5a3660, 0xf08d17)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc21026ba80, 0xc210413b70, 0x24, 0xc210b7d3c0, 0x1, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x275
	github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc21006d2a0, 0xc210413b70, 0x24, 0xc21046a3e0, 0x1a, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:179 +0x6e0
	github.com/

**Comment by dkoper** [comment]
Cf cli 6.12.2 is almost 2 years old. I believe this issue has been fixed. Please upgrade to the latest release.
