### ISSUE TITLE
cloning repo takes an inordinate amount of time

### ISSUE THREAD

**Issue by perdasilva** [cloudfoundry/cli#1205]
Hi,

I'm developing a cli plugin. Doing go get -u code.cloudfoundry.org/cli takes a _very_ long time to finish. Is is possible to just pull the dependencies for creating the plugins themselves, without pulling a whole massive repository? Maybe I'm doing something wrong. It would also be good to add the ```go get``` command in the cli plugin development README.

Thanks in advance,

Per da Silva

**Comment by melnikalex** [comment]
Hey Per da Silva,
Downloading our repository does take a long time (it's a little over 200MiB with with git history and all). For plugin development purposes you likely don't need all the history, so you could just clone the repository with a shorter depth.

Ex:
```
mkdir -p "${GOPATH}/src/code.cloudfoundry.org"
cd "${GOPATH}/src/code.cloudfoundry.org"
git clone --depth 1 "https://github.com/cloudfoundry/cli"
```

**Comment by melnikalex** [comment]
If you still want to use `go get`, but running with the `-d` instead of the `-u` option ([the -u flag instructs get to use the network to update the named packages and their dependencies](https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies)) would save you about a minute.

**Comment by perdasilva** [comment]
Thank you!

**Comment by dkoper** [comment]
Added it here, thanks for the suggestion!
https://github.com/cloudfoundry/cli/blob/master/plugin/plugin_examples/README.md#development-requirements
