### ISSUE TITLE
Can we have support for specifying cf bind-route-service in manifest.yml

### ISSUE THREAD

**Issue by arghya88** [cloudfoundry/cli#1206]

**Comment by dkoper** [comment]
FYI, exploring this in https://www.pivotaltracker.com/story/show/139912115.

**Comment by XenoPhex** [comment]
Hey @arghya88 we are going to close out this issue and will be tracking the pivotal tracker story instead. Please feel free to reach out should you have feedback or require any further information. This is a feature which we have no immediate plans on implementing but will be leaving the story as a potential enhancement in the future.
