### ISSUE TITLE
Add ability to stage app without starting

### ISSUE THREAD

**Issue by keeganwitt** [cloudfoundry/cli#1207]
#1045 is to be able to stage without starting first.  This feature would be to perform restage without starting app (for example to set Java memory without starting app in an environment you needed the app to be inactive).  Syntax would probably be like `cf restage --no-start my-app` or maybe `cf stage --no-start my-app`.

**Comment by dkoper** [comment]
How is what you're asking different from #1045? Both ask for a way to stage app bits without starting it, don't they?

**Comment by keeganwitt** [comment]
My understanding of 1045 was he wanted to stage without starting _before_ the staging, I wanted to stage without starting _after_ the staging.

**Comment by dkoper** [comment]
Ah I get it now. `cf restage` also starts the app. You want it not to do that.
In that case, we have implemented that using the V3 API and will have a release in the next few weeks with details about the changes.

**Comment by dkoper** [comment]
The `v3-stage` command in 6.31.0 calls the V3 API Nick referred to.
