### ISSUE TITLE
CLI for AIX systems

### ISSUE THREAD

**Issue by mehrotra-prateek** [cloudfoundry/cli#1211]
Hello,

Do we have a package available for AIX systems? I have tried both binary and installers they don't work for AIX architecture.

**Comment by XenoPhex** [comment]
Hey there @mehrotra-prateek,

We currently do not provide an AIX package for the CLI, and have no future plans to. We have some instructions on how to compile the CLI yourself in the [contribution guide](https://github.com/cloudfoundry/cli/blob/master/.github/CONTRIBUTING.md) to help you compile your own, but I'm pretty sure [GoLang does not easily support AIX](https://github.com/golang/go/issues/19200).

**Comment by mehrotra-prateek** [comment]
thanks for info and link about golang support on aix. let me check alternatives as this requirement came up as some automations had to be done between aix and cf platform.

i will also check with ibm if they have done something internally
