### ISSUE TITLE
cf restart should not cause downtime (by default)

### ISSUE THREAD

**Issue by shakuzen** [cloudfoundry/cli#1213]
## Command  

`cf restart myapp`

## What occurred

As documented:
> Stop all instances of the app, then start them again. This may cause downtime.

## What you expected to occur

I would expect the default behavior to be safe - that is, have no downtime.
(Perhaps a nit-pick, but the wording of the current documentation should probably be "This WILL cause downtime" because by its self-stated procedure, there will be time during which all instances are stopped)

## Enhancement request

In order of preference, I think it would be better for users if one of the following happened:

1. add an option to restart with downtime (current behavior); change default to zero downtime restart
2. maintain existing behavior (causing downtime); add an option to restart without downtime

The second option would likely be easy for people to forget even if they know about the option, so it is not as safe as the first.

Specifically, to avoid downtime and maintain (most) capacity, a rolling restart would be the most obvious option that comes to mind. There are plugins that provide this (see the other relevant info section below), but as mentioned above, my expectations are that the official cf CLI would have safe behavior wherever possible.

### Use case

To give a specific use case we have, some of our applications are Spring applications that use [Spring Cloud Config](https://cloud.spring.io/spring-cloud-config/). Therefore, those applications retrieve their configuration from the config server on startup. If not using the [push notifications and Spring Cloud Bus feature](https://cloud.spring.io/spring-cloud-config/single/spring-cloud-config.html#_push_notifications_and_spring_cloud_bus), then application instances need to be refreshed (`POST` request to an endpoint) or restarted to receive configuration changes. Restarting them without downtime to effectively apply configuration changes is desirable in this case.

## CLI Version  

`cf version 6.29.2+c66d0f342.2017-08-25`

## CC API Endpoint Version  

`2.74.0`

## Any other relevant information  

Previously requested but closed related issues #524 and #1064
Related plugins:
* https://github.com/Comcast/cf-recycle-plugin
* https://github.com/dan-kirberger/cf-rolling-restart

**Comment by dkoper** [comment]
Hi @shakuzen 

You write a great report!

Diego and CAPI backends have started working on supporting zero-downtime restarts natively.
Instead of us copying functionality from existing plugins and introduce new flags that we can deprecate in a few months when we support the new backend functionality, I'd rather point people to those plugins for now.
Note that we have various commands that perform restarts (`cf restart`, `cf push`, `cf scale`) so this is something we'd want to introduce consistently.

The wording "MAY" is indeed misleading. I'll try to figure out why we used that and consider changing that until we do support actual zero-downtime restart.

Cheers,
Dies Koper
CF CLI PM

**Comment by shakuzen** [comment]
Hello @dkoper 

Thank you for the information. Your plan of action sounds reasonable to me.

Is there anything I could follow/subscribe to in order to get notifications of when the groundwork is laid in Diego/CAPI for this? Or at least something to get an idea of the progress/timeframe.

**Comment by zrob** [comment]
@shakuzen 

Zero downtime deploys can be accomplished today using the [blue-green deployment strategy](https://docs.cloudfoundry.org/devguide/deploy-apps/blue-green.html)

As Dies noted, there is work underway to support zero downtime natively. Here is the [community proposal](https://docs.google.com/document/d/116I_mOWjZcPeIbUvvsh-jAcwpoE_mGPD_SkCel5xXuU/edit#) if you'd like to take a look or add comments.

**Comment by dkoper** [comment]
Addressed the wording for now:
```
D:\>cf h restart
NAME:
   restart - Stop all instances of the app, then start them again. This causes downtime.
...
```
