### ISSUE TITLE
CF subordinate commands should support --skip-ssl-validation

### ISSUE THREAD

**Issue by gradinDotCom** [cloudfoundry/cli#1215]
e.g. `cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org`

Error: Get https://plugins.cloudfoundry.org/list: x509: certificate signed by unknown authority

`cf version` cf version 6.28.0+9e024bd.2017-06-27
api version:    2.65.0

When using a security device - especially within an enterprise environment - that enforces SSL interception, it's possible that the client does not trust the resultant certificate. Instead of adding keys to the trusted root, it would be convenient to include ssl validation at each level of CF command that could use it.

**Comment by dkoper** [comment]
Hi @gradinDotCom 

I'd like to learn more about the use case. You are in an enterprise environment, use a security device, but don't want ssl validation? Why don't you want to add a proper cert as trusted root?

**Comment by cppforlife** [comment]
> Instead of adding keys to the trusted root, it would be convenient to
include ssl validation at each level of CF command that could use it.

i would imagine that in an enterprise production setting it's _especially_
important to verify the certificates by whatever means possible.

would --ca-cert option resolve your concern?

**Comment by gradinDotCom** [comment]
To be frank, adding trusted certificates to everything all the time is a) a hassle and b) a bad habit to get yourself into. You're generally correct that I *should* be adding those certificates, but even in enterprise environments you have ephemeral systems and pockets of "trusted" vulnerability. Proxies are the bane of most of our existence in corporate environments; I'm just asking that the tools function consistently in their design. If you would allow us to skip SSL validation when connecting to your server, why not also allow to others'?

**Comment by dkoper** [comment]
Hi @gradinDotCom 

I believe the skip SSL validation flag when communicating with the API endpoint was introduced to ease initial adoption of Cloud Foundry, in particular for developers with local bosh-lite environments.

Now that Cloud Foundry is widely adopted, and documentation and tooling around how to register the trusted certificates  has been made available, we want to discourage use of this flag - even consider removing it at a next major version bump.

I'm not sure I understand your situation exactly,  but it sounds like you're asking for a new intermediate level of security (https without ssl validation, in between https with ssl validation and http), and I'm not convinced of its value to all our users, especially compared to other values on our roadmap.

Regards,
Dies Koper
CF CLI PM
