### ISSUE TITLE
Enable plugins to support $CF_TRACE=path/to/trace.log

### ISSUE THREAD

**Issue by glyn** [cloudfoundry/cli#1218]
Currently, any output produced by a plugin appears on the console. So to hono(u)r `$CF_TRACE` being set to the path of a log file, the plugin needs some means of writing to the log file.

I suggest providing the plugin with a couple of methods, probably on `CliConnection`:
* `cfTraceEnabled() bool` which returns true if and only if `$CF_TRACE` is set
* `cfLog(message string)` which logs a message if and only if `$CF_TRACE` is set and logs it to standard output or the correct log file, depending on the value of `$CF_TRACE`.

The first method is only useful if the cost of creating a log message is significant, which it might be sometimes. In general, plugins which aren't too concerned about performance can simply use the second method to do their debug logging.

**Comment by XenoPhex** [comment]
Hi @glyn many thanks for creating this issue. Although we would like to make this enhancement, our current plug-in architecture currently requires a review and possible overhaul.  For now, we are closing this issue, but feel free to provide input [here](https://www.pivotaltracker.com/story/show/157201049) where you can provide feedback.

**Comment by glyn** [comment]
Thanks @XenoPhex. Why not add a link to this issue to the tracker story about a new plugin architecture for posterity?

**Comment by XenoPhex** [comment]
Haha, great minds, we did that a few minutes after we commented! Thanks for the reminder though.
