### ISSUE TITLE
SSH connect error 

### ISSUE THREAD

**Issue by JenneyJ** [cloudfoundry/cli#1219]
Hi,

I use the CLI  version cf version 6.29.0+ff886fa93.2017-07-24 and I try to connect via ssh command to my app, `cf ssh myapp` im getting the following error:

`FAILED
Error opening SSH connection: ssh: handshake failed: ssh: unable to authenticate, attempted methods [password none], no supported methods remain`

when I run command `cf allow-space-ssh myspace`
im getting the following response:
`ssh support is already enabled in space 'myspace'`

we are using CF version 2.9.2 , and im working on MAC ver `10.12.6`

On other landscape I was able to do it...

**Comment by dkoper** [comment]
Is ssh enabled for your app?
http://cli.cloudfoundry.org/en-US/cf/ssh-enabled.html

**Comment by r1s** [comment]
Hi,
I've the same problem:
>cf space-ssh-allowed ***
>ssh support is enabled in space '***'

>cf ssh-enabled *****
>ssh support is enabled for '*****'

>cf ssh *****
>FAILED
>Error opening SSH connection: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

>cf -v cf.exe version 6.39.1+efdd631d2.2018-09-18
