### ISSUE TITLE
"cf target -s <space_name>" masks API errors, all errors appear as 404s

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/cli#1220]
## Command  

`cf target -s <space_name>`

## What occurred

Probably some API error, but `cf` CLI made it seem like the space was not found.  A previous command that was run clearly shows the space existed.

## What you expected to occur

A more accurate error message.

## CLI Version  

Bug appears to be there in current codebase.  Actually saw this on `6.22.2+a95e24c`.

## CC API Endpoint Version  

API version: 2.75.0

## CF Trace

Would've been nice to have, unfortunately not available.

## Platform & Shell Details  

N/A

## Any other relevant information  

Relevant code:

* `ListPaginatedResources` method returns API error before executing callback on found resources: https://github.com/cloudfoundry/cli/blob/4c1097453bc62fadbb01a48d654edba997fd2c2d/cf/net/gateway.go#L142-L158
* `FindByNameInOrg` method masks API error with "NotFound" error if callback isn't executed: https://github.com/cloudfoundry/cli/blob/ffee70cca68ab15df71f48641f6fa3bb007c4a2b/cf/api/spaces/spaces.go#L66-L78

**Comment by dkoper** [comment]
Hi @Amit-PivotalLabs !

Can you actually reproduce this issue on the latest cf CLI?
We refactored `target` in 6.24.0. Old code might still be there as we're not sure it may still be used in certain cases (like when invoked from a plugin?).

Cheers,
Dies Koper
CF CLI PM

**Comment by Amit-PivotalLabs** [comment]
Just spoke with @XenoPhex, this may not be an issue with 6.24.0.  I would not be able to test reproduction at this time, I'll go ahead and close the issue, and re-open if it recurs with a newer version of the CLI.
