### ISSUE TITLE
Issue with install PCF CLI

### ISSUE THREAD

**Issue by Arvinder777** [cloudfoundry/cli#1221]

**Comment by dkoper** [comment]
Hi @Arvinder777 

Can you provide details of your issue?

**Comment by Arvinder777** [comment]
Hi DKoper,

While loading the package using "**sudo apt-get update**" am getting below error -

Ign http://old-releases.ubuntu.com quantal-security/restricted Translation-en_SG
Ign http://old-releases.ubuntu.com quantal-security/universe Translation-en_SG
W: Failed to fetch http://packages.cloudfoundry.org/debian/dists/stable/main/binary-amd64/Packages  302  Found [IP: 34.193.240.80 80]

W: Failed to fetch http://packages.cloudfoundry.org/debian/dists/stable/main/binary-i386/Packages  302  Found [IP: 34.193.240.80 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.


Regards,
AS

**Comment by Arvinder777** [comment]
resolved it by switching to https in sources.list
