### ISSUE TITLE
cf push of buildpack tag of branch doesn't work

### ISSUE THREAD

**Issue by keeganwitt** [cloudfoundry/cli#1232]
## Command 
`cf push myapp -b https://github.com/myfork/java-buildpack.git#v3.8.1-1`

## What occurred

`Failed to clone git repository at https://github.com/myfork/java-buildpack.git`

## What you expected to occur

Tag on branch to be located and used for push.

## CLI Version

6.29.0+ff886fa.2017-07-24

## CC API Endpoint Version

2.75.0

## Any other relevant information

In this scenario, let's assume I forked java-buildpack at _myfork_, and created a _v3.8.1-1_ tag on a branch called mybranch that added some changes to 3.8.1.  There is no way to allow a push to happen from this branch with that specific tag.  This is relevant for organizations who maintain their own branch that they periodically tag for internal consumption.  It's common practice to have the forked master track the upstream master.  Currently the only way you could use that forked buildpack is to just take the latest version on the branch (with `https://github.com/myfork/java-buildpack.git#mybranch`).  There's no way to pin it to a tag (or if there is, the syntax is not documented).

**Comment by XenoPhex** [comment]
@keeganwitt can we have the full CLI output? I suspect this might be a backend issue given the error message you provided.

**Comment by dkoper** [comment]
Hi @keeganwitt 

Just FYI, here's my output of it working on Windows:
```
D:\Users\koperd\Downloads\bin>cf push mytag -p t\s -b https://github.com/cloudfoundry/java-buildpack#3.x --no-route
Creating app mytag in org dies-test / space dev as admin...
OK

App mytag is a worker, skipping route creation
Uploading mytag...
Uploading app files from: D:\Users\koperd\Downloads\bin\t\s
Uploading 14.5K, 12 files
Done uploading
OK

Starting app mytag in org dies-test / space dev as admin...
Creating container
Successfully created container
Downloading app package...
Downloaded app package (397.1K)
Staging...
-----> Java Buildpack Version: 727297d | https://github.com/cloudfoundry/java-buildpack#727297d
...

D:\Users\koperd\Downloads\bin>cf app mytag
Showing health and status for app mytag in org dies-test / space dev as admin...
...
buildpack:         https://github.com/cloudfoundry/java-buildpack#3.x
```

You can confirm the commit `id  727297d` matches the tag here https://github.com/cloudfoundry/java-buildpack/tree/3.x the conforming.

As Anand suggested, your shell may need certain characters escaped.

Regards,
Dies Koper
CF CLI PM

**Comment by keeganwitt** [comment]
It looks like there must be some issue in my client's pipeline that is invoking the CLI, I was able to use the tag manually.  Sorry for the noise.

**Comment by dkoper** [comment]
Thanks for reporting back here!
