### ISSUE TITLE
GetCurrentSpace() and GetCurrentOrg() should return error if no target

### ISSUE THREAD

**Issue by mastertinner** [cloudfoundry/cli#1233]
## Functions

`plugin.CliConnection.GetCurrentSpace()` and `plugin.CliConnection.GetCurrentOrg()`

## What occurred

Calling `GetCurrentSpace()` without having a space targeted returns an empty `SpaceFields` but no error. The same goes for `GetCurrentOrg()` without having an org targeted.

## What you expected to occur

I think it should also return an error like `no space targeted` (or `no org targeted`). This would imply a simple check for an empty value at https://github.com/cloudfoundry/cli/blob/734a1633fabc33121dccae9239d12bc97b2c457f/plugin/rpc/cli_rpc_server.go#L220 and https://github.com/cloudfoundry/cli/blob/734a1633fabc33121dccae9239d12bc97b2c457f/plugin/rpc/cli_rpc_server.go#L213. I can create a PR if you guys agree.

## CLI Version  

6.31.0

**Comment by XenoPhex** [comment]
Hi @mastertinner thanks for creating this issue. Although this change is sensible, we are afraid that this would break functionality for existing users. Closing this issue but please feel free to reach out or create a new issue if you have any feedback. 

We'll add this as feedback for the overall enhancement for the plugin architecture in the future. Feel free to comment on [this tracker story](https://www.pivotaltracker.com/story/show/157201049) in the future.
