### ISSUE TITLE
cf login fails if no stty binary is available

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/cli#1234]
## Command  

cf login

## What occurred

As soon the email is entered (`guy@esample.com<return>`) the following happens:

```
[guy@example.com ~]$ cf login

API endpoint> api.cf.example.com

Email> guy@example.com

Password> Authenticating...
Credentials were rejected, please try again.

Password> Authenticating...
Credentials were rejected, please try again.

Password> Authenticating...
Credentials were rejected, please try again.


API endpoint:   https://api.cf.example.com (API version: 2.77.0)
Not logged in. Use 'cf login' to log in.
FAILED
Unable to authenticate.
```

## What you expected to occur

Being prompted for the password and then correctly login.

## CLI Version  

cf version 6.27.0+d26b32d.2017-06-08

## CC API Endpoint Version  

2.77.0

## Platform & Shell Details  

host is missing stty

## Any other relevant information  

it would maybe ideal to replace the current implementation (https://github.com/cloudfoundry/cli/blob/c2bbe3259e62feb8f9e633d67f41b7bd0d327ba2/cf/terminal/ui_unix.go) with https://godoc.org/golang.org/x/crypto/ssh/terminal#Terminal.ReadPassword

**Comment by CAFxX** [comment]
Could potentially sole #1056 and the cygwin known issue (https://github.com/cloudfoundry/cli#known-issues)

**Comment by dkoper** [comment]
Thanks! I wasn't aware of this use case of missing stty.

We tried replacing the current prompting with [go-interact](https://github.com/vito/go-interact), which uses the crypto ssh function you mentioned, but ran into various issues when testing it on Windows.

We are planning to pick this up again when we refactor the `login` command. I'll add this story to that to ensure we test for missing stty as well.

**Comment by giner** [comment]
Here is workaround I use for Linux without stty:
```
cf login -a API -u USERNAME -p "$(read -sp "Password: " pass; echo "$pass")"
```

**Comment by dkoper** [comment]
@CAFxX Do you see the same issue when using `cf v2-push` with a private Docker repo (i.e. `cf v2-push APP -o docker-image X --docker-username Y`?
When we refactor `cf login`, we plan to use the same library as is currently used for `v2-push` with the interactive Docker repo password prompt.

**Comment by XenoPhex** [comment]
@CAFxX thanks for creating this issue. Could you let us know what platform you are running to help us triage this issue.

**Comment by CAFxX** [comment]
@xenophex Linux (see https://github.com/cloudfoundry/cli/issues/1234#issuecomment-333432644)

**Comment by giner** [comment]
See also https://github.com/golang/go/issues/31180

**Comment by abbyachau** [comment]
Hi @norman-abramovitz thanks for creating this issue. As Brendan mentioned, we are currently [refactoring](https://www.pivotaltracker.com/epic/show/4186886) the `cf login` command and believe this issue might be fixed after the refactor.  We hope to release a CLI with the refactoring work soon.

**Comment by bwasmith** [comment]
Hello @giner and @CAFxX,

I have confirmed that this issue does not arise in the rewritten `cf login` command. The stty will no longer be necessary. 

[Old prompting code where stty is necessary](https://github.com/cloudfoundry/cli/blob/afa7edfedc4f16251eb549ebd0d5fea30c3a5c25/cf/terminal/ui_unix.go#L74)
[Rewritten prompting code](https://github.com/cloudfoundry/cli/blob/afa7edfedc4f16251eb549ebd0d5fea30c3a5c25/util/ui/prompt.go#L66) -- We use the [go-interact to resolve the prompting](https://github.com/cloudfoundry/cli/blob/afa7edfedc4f16251eb549ebd0d5fea30c3a5c25/vendor/github.com/vito/go-interact/interact/interaction.go#L58)

Please expect a fix in an upcoming release.
