### ISSUE TITLE
cli releases should work with the github concourse resource

### ISSUE THREAD

**Issue by utako** [cloudfoundry/cli#1235]
## Command  
All of 'em.

## What occurred

When we try to use the github concourse resource to get a CLI release binary, we can't do this because of the way CLI binaries are linked on the github release page.

## What you expected to occur

We expect the concourse github-release resource to successfully retrieve a published CF CLI release binary.

## CLI Version  

All

## Any other relevant information  

This is important for any team that is consuming and using the CF CLI binary programmatically, or in their CI. Compiling the CF CLI against certain versions of Go will cause failures with regards to headers, so getting the [github-release Concourse Resource](https://github.com/concourse/github-release-resource) to work with the CF CLI release publishing process would be ideal for us.

**Comment by abbyachau** [comment]
Hi @utako thanks for creating this and apologies for the lack of response. We published support for a [CF CLI Bosh release](https://github.com/bosh-packages/cf-cli-release) last year which may help with your use case.  Are there any particular resources that you know of which you believe we should consider?

**Comment by JenGoldstrich** [comment]
Closing this since its fairly stale, please feel free to re-open @utako !
