### ISSUE TITLE
Improve cf service-key user experience

### ISSUE THREAD

**Issue by JohannesRudolph** [cloudfoundry/cli#1236]
I frequently find working with service-keys to be very frustrating on the cf cli. 

Let me give you some typical examples along with suggestions on how to improve. 

A) creating a new service key and displaying it: 

```
cf create-service-key meshfed-mysql remote
cf service-key meshfed-mysql remote
```

This requires two commands right now with lots of redundant typing. 

**Request no. 1)**: Make cf-create-service-key display the created service-key

B) looking up a service, service key and displaying it
```
cf services
cf service-keys meshfed-mysql
cf service-key meshfed-mysql remote
```

This requires three commands with lots of keystrokes to either fully retype them or edit & adapt the last command (especially between step 2 and 3). 

**Request no. 2)**:  Allow commands to be easily "specialized" for common workflows. E.g. so that I can do `cf service-keys xxx` followed by `cf service-keys xxx keyxxx` to display the key. On a normal shell, this involves just typing up arrow, space and then appending the key name to the last run command. 

The same would e.g. apply to `cf apps`, which could also benefit from this easy command "specializiation". I know this is an entirely new pattern probably for cf cli, so any thoughs re this proposal are welcome.

**Comment by abbyachau** [comment]
@matthewmcnew for visibility

**Comment by mattmcneeney** [comment]
Thanks @abbyachau. Having `cf create-service-key` display the service key info would only work in the synchronous workflow, and not the upcoming asynchronous workflow.

The subtle syntax difference between `cf service-keys` and `cf service-key` has confused me a few times too, so I'd be supportive of improving this, but I'm guessing this would be difficult in a backwards compatible way.

**Comment by heyjcollins** [comment]
With the GA of the v7 CLI, we're no longer actively developing against the v6 line.  With an interest the overall hygiene of the CLI project we're closing this  issue.
If this issue is still occurring in v7 please feel free to comment and re-open. Thank you!
