### ISSUE TITLE
DNS resolution different between version 6.20 and 6.25

### ISSUE THREAD

**Issue by petergtz** [cloudfoundry/cli#1239]
Hi,

We noticed that `cf api api.<my-systen-domain>` resolves the hostname under our specific network configuration differently when using CLI version 6.20 and 6.25. Version 6.20 resolves it the same as `curl`, but version 6.25 resolves it to a different IP (which then doesn't work down the line).

I suspect it's due to Go's default domain name resolver, which is configured during build time (if at all). To troubleshoot this issue further, could someone please help me find the build command used to build the binary versions 6.20 and 6.25 for Linux 64bit which are available on https://github.com/cloudfoundry/cli/releases?

Other ideas are of course also appreciated.

Thanks,
Peter

**Comment by dkoper** [comment]
@petergtz Please check out https://github.com/cloudfoundry/cli/blob/master/ci/cli/tasks/build-binaries.yml#L43.

**Comment by petergtz** [comment]
@dkoper Thanks for your quick response! Your link is what I looked at earlier, but then was surprised, that the two versions still give different results for DNS resolution. Hence, I was wondering if version 6.20 was potentially built differently.

Especially, because https://github.com/cloudfoundry/cli/commit/66d3f5da28f76d08872f5a90f9be678929b841a6 says that the build command was changed with version 6.19, so only slightly before 6.20 was released. Is it possible that somehow this build task was not used just yet for version 6.19 and 6.20 even though it was there already?

Or is there some string baked into the binary who could tell me that?

Really fishing for explanations here, because the results that I see do not make sense to me.

**Comment by vitreuz** [comment]
> Or is there some string baked into the binary who could tell me that?

Nope.

> Really fishing for explanations here, because the results that I see do not make sense to me.

Could it be your OS? These old versions of CLI were built with Go 1.7.x and now we have moved on to Go 1.9.x. 

I would suggest that you try the latest and if this is still occurring to reopen this issue and mention what OS and what CLI version you used.

Max and Sebastian

**Comment by dkoper** [comment]
@petergtz You can use `strings ./cf | grep 'go1\.'` to determine the Golang version a binary was built with.
I am not sure if there is a way with Golang to enable DNS resolving trace output to see what resolver is used.
We reported a change in DNS resolution in the 6.22.0 release notes due to the upgrade to Golang 1.7.1 that resolved some issues introduced around Golang 1.5.
https://github.com/cloudfoundry/cli/releases/tag/v6.22.0

**Comment by petergtz** [comment]
@dkoper I haven't gotten the chance yet to pick up this work again, but your 2 pointers about grepping for strings and also the change in DNS resolution in 6.22 are very helpful. Will dig into that and see if I can find something. Thanks a lot!
