### ISSUE TITLE
Version 269814d4746c5f53ec1de5ecb9c5eb3c289c8750 has changed.

### ISSUE THREAD

**Issue by stiggity** [cloudfoundry/cli#1240]
In the glide.yaml of a project I'm using there is specified:

- package: code.cloudfoundry.org/cli
  version: 269814d4746c5f53ec1de5ecb9c5eb3c289c8750

This has worked for some time. Within the last few days, anybody that clears their glide cache and tries to install anew will receive the following error when trying to run a subsequent glide install:

[ERROR]    Failed to set version on code.cloudfoundry.org/cli to 269814d4746c5f53ec1de5ecb9c5eb3c289c8750: Unable to update checked out version

This included me. The above was the reliable outcome for any glide install attempted. However, anybody who had not cleared their cache was immune to the problem. So I copied the ~/.glide/cache/src/https-code.cloudfoundry.org-cli folder from a colleague and placed it in my folder and I was again able to run glide install. 

I compared the two directories (the failing one that is the result of any recent glide install and the working one that was obtained before this problem arose) and I was surprised to see deltas, given that the commit was from Nov 28 2016. In the attached image, the one on the left is the working copy.

<img width="832" alt="screen shot 2017-10-05 at 2 16 21 pm" src="https://user-images.githubusercontent.com/13751117/31246350-20ee5622-a9db-11e7-9ca9-5717706aba2c.png">

## Command  

Specify:

- package: code.cloudfoundry.org/cli
  version: 269814d4746c5f53ec1de5ecb9c5eb3c289c8750
  subpackages:
  - cf/configuration
  - cf/configuration/confighelpers
  - cf/configuration/coreconfig
  - cf/models

in glide.yaml.

glide cc
glide install

## What occurred

[ERROR]    Failed to set version on code.cloudfoundry.org/cli to 269814d4746c5f53ec1de5ecb9c5eb3c289c8750: Unable to update checked out version

## What you expected to occur

[INFO]	--> Setting version for code.cloudfoundry.org/cli to 269814d4746c5f53ec1de5ecb9c5eb3c289c8750.

## Platform & Shell Details  

Mac OS X 10.12.6 iTerm

## Any other relevant information  

glide version v0.12.3

GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/shonuff/go"
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cv/j7lfzjxj5cg5wr0ssch72r_h0000gn/T/go-build850644459=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"

**Comment by stiggity** [comment]
[DEBUG]	Output was: fatal: reference is not a tree: 269814d4746c5f53ec1de5ecb9c5eb3c289c8750[DEBUG]	Unlocking https-code.cloudfoundry.org-cli

**Comment by stiggity** [comment]
I've just realized that the version I've referenced doesn't appear to be part of the master branch. When I go back in time to the same date, the commit above doesn't show up, but it appears the following commit has the same change (but this one is in master):  https://github.com/cloudfoundry/cli/commit/8d5a0c303e2729e0a67be039314fd14883b7f03a

When I tried to switch to use 8d5a0c303e2729e0a67be039314fd14883b7f03a I immediately get complaints about the absence of: code.cloudfoundry.org/cli/cf/resources   (which is in 269... but is not in 8d5...). So it seems that the branch that contains 269.. is the one we need. Does anybody know the history here? What branch is/was that? Is it still available?

**Comment by dkoper** [comment]
See https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/YUNYHH7EOD3MGULUMCDCTJVZF2RZLPOC/

It is still available here: https://github.com/cloudfoundry-attic/cli-with-i18n

**Comment by chriskirkland** [comment]
@stiggity did you find a resolution?  I'm trying to work through the same issue.

**Comment by stiggity** [comment]
@chriskirkland Yes - courtesy of @dkoper, I just indicated the repo he specified.
