### ISSUE TITLE
E: Unable to locate package cf-cli

### ISSUE THREAD

**Issue by reddymadhavi** [cloudfoundry/cli#1241]
Hello,

I am trying to get cf installed on docker with dockerfile but getting error : 

E: Unable to locate package cf-cli
The command '/bin/sh -c apt-get install cf-cli' returned a non-zero code: 100

Dockerfile content : 

From ubuntu:16.04
MAINTAINER  Madhavi Reddy
RUN apt-get update
RUN apt-get install cf-cli

**Comment by dkoper** [comment]
Hi @reddymadhavi 

Our `apt-get` download instructions include two more steps that I don't see in your Dockerfile - could that be the issue?
https://github.com/cloudfoundry/cli#installing-using-a-package-manager

```
# ...first add the Cloud Foundry Foundation public key and package repository to your system
wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
# ...then, update your local package index, then finally install the cf CLI
sudo apt-get update
sudo apt-get install cf-cli
```

The cf CLI is in a CFF repository, so that needs to be added to your system.

Regards,
Dies Koper
CF CLI PM

**Comment by reddymadhavi** [comment]
Getting Below error if I add package repository : 

/bin/sh: 1: wget: not found
gpg: no valid OpenPGP data found.


Now content of my docker file 

From ubuntu:16.04
MAINTAINER  Madhavi Reddy
RUN wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
RUN echo "deb http://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
RUN apt-get update
RUN apt-get install cf-cli

**Comment by reddymadhavi** [comment]
@dkoper 
what is correct command to get wget ?
apt-get install wget ?

**Comment by reddymadhavi** [comment]
Tried to get wget but got below error: 
RUN apt-get -y install wget

E: Unable to locate package wget

**Comment by dkoper** [comment]
You should do `RUN apt-get update` before `RUN apt-get -y install wget`. Are you?
You may get better help from the community maintaining your Docker image.

**Comment by reddymadhavi** [comment]
Tried , now getting below error:

E: The method driver /usr/lib/apt/methods/https could not be found.


Dockerfile content are:
From ubuntu
MAINTAINER  Madhavi Reddy
RUN apt-get update
RUN apt-get -y install wget
RUN wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
RUN echo "deb http://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
RUN apt-get update
RUN apt-get install cf-cli

**Comment by dkoper** [comment]
Try adding `RUN apt-get install apt-transport-https`?

**Comment by reddymadhavi** [comment]
yes, tried , it fails with abort . 

Sending build context to Docker daemon  2.048kB
Step 1/8 : FROM ubuntu
latest: Pulling from library/ubuntu
9fb6c798fa41: Pull complete
3b61febd4aef: Pull complete
9d99b9777eb0: Pull complete
d010c8cf75d7: Pull complete
7fac07fb303e: Pull complete
Digest: sha256:d45655633486615d164808b724b29406cb88e23d9c40ac3aaaa2d69e79e3bd5d
Status: Downloaded newer image for ubuntu:latest
 ---> 2d696327ab2e
Step 2/8 : MAINTAINER Madhavi Reddy
 ---> Running in 8e8161fa53e8
 ---> f5b11995356d
Removing intermediate container 8e8161fa53e8
Step 3/8 : RUN apt-get update
 ---> Running in 0eb5fd7015b8
Get:1 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:4 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [49.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Get:6 http://archive.ubuntu.com/ubuntu xenial/universe Sources [9802 kB]
Get:7 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [456 kB]
Get:8 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [12.8 kB]
Get:9 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [212 kB]
Get:10 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [2928 B]
Get:11 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1558 kB]
Get:12 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]
Get:13 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9827 kB]
Get:14 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [176 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [220 kB]
Get:16 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [823 kB]
Get:17 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [13.5 kB]
Get:18 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [689 kB]
Get:19 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [17.5 kB]
Get:20 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [5176 B]
Get:21 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [6354 B]
Fetched 24.4 MB in 1min 39s (246 kB/s)
Reading package lists...
 ---> 0ac69c281e9d
Removing intermediate container 0eb5fd7015b8
Step 4/8 : RUN apt-get -y install wget
 ---> Running in 757badaf7dbd
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  ca-certificates libidn11 libssl1.0.0 openssl
The following NEW packages will be installed:
  ca-certificates libidn11 libssl1.0.0 openssl wget
0 upgraded, 5 newly installed, 0 to remove and 2 not upgraded.
Need to get 2085 kB of archives.
After this operation, 6023 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libidn11 amd64 1.32-3ubuntu1.2 [46.5 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libssl1.0.0 amd64 1.0.2g-1ubuntu4.8 [1081 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 openssl amd64 1.0.2g-1ubuntu4.8 [492 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 ca-certificates all 20170717~16.04.1 [168 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 wget amd64 1.17.1-1ubuntu1.2 [298 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 2085 kB in 10s (199 kB/s)
Selecting previously unselected package libidn11:amd64.
(Reading database ... 4768 files and directories currently installed.)
Preparing to unpack .../libidn11_1.32-3ubuntu1.2_amd64.deb ...
Unpacking libidn11:amd64 (1.32-3ubuntu1.2) ...
Selecting previously unselected package libssl1.0.0:amd64.
Preparing to unpack .../libssl1.0.0_1.0.2g-1ubuntu4.8_amd64.deb ...
Unpacking libssl1.0.0:amd64 (1.0.2g-1ubuntu4.8) ...
Selecting previously unselected package openssl.
Preparing to unpack .../openssl_1.0.2g-1ubuntu4.8_amd64.deb ...
Unpacking openssl (1.0.2g-1ubuntu4.8) ...
Selecting previously unselected package ca-certificates.
Preparing to unpack .../ca-certificates_20170717~16.04.1_all.deb ...
Unpacking ca-certificates (20170717~16.04.1) ...
Selecting previously unselected package wget.
Preparing to unpack .../wget_1.17.1-1ubuntu1.2_amd64.deb ...
Unpacking wget (1.17.1-1ubuntu1.2) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Setting up libidn11:amd64 (1.32-3ubuntu1.2) ...
Setting up libssl1.0.0:amd64 (1.0.2g-1ubuntu4.8) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Setting up openssl (1.0.2g-1ubuntu4.8) ...
Setting up ca-certificates (20170717~16.04.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Setting up wget (1.17.1-1ubuntu1.2) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Processing triggers for ca-certificates (20170717~16.04.1) ...
Updating certificates in /etc/ssl/certs...
148 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
 ---> f674d8993ae5
Removing intermediate container 757badaf7dbd
Step 5/8 : RUN wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
 ---> Running in 17c7f1fd0d5e
OK
 ---> c5e235660d9f
Removing intermediate container 17c7f1fd0d5e
Step 6/8 : RUN echo "deb http://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
 ---> Running in 2b2fe49dc66b
deb http://packages.cloudfoundry.org/debian stable main
 ---> 237df0899b92
Removing intermediate container 2b2fe49dc66b
Step 7/8 : RUN apt-get install apt-transport-https
 ---> Running in 7b6db77de8eb
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  krb5-locales libasn1-8-heimdal libcurl3-gnutls libffi6 libgmp10 libgnutls30
  libgssapi-krb5-2 libgssapi3-heimdal libhcrypto4-heimdal libheimbase1-heimdal
  libheimntlm0-heimdal libhogweed4 libhx509-5-heimdal libk5crypto3
  libkeyutils1 libkrb5-26-heimdal libkrb5-3 libkrb5support0 libldap-2.4-2
  libnettle6 libp11-kit0 libroken18-heimdal librtmp1 libsasl2-2
  libsasl2-modules libsasl2-modules-db libsqlite3-0 libtasn1-6
  libwind0-heimdal
Suggested packages:
  gnutls-bin krb5-doc krb5-user libsasl2-modules-otp libsasl2-modules-ldap
  libsasl2-modules-sql libsasl2-modules-gssapi-mit
  | libsasl2-modules-gssapi-heimdal
The following NEW packages will be installed:
  apt-transport-https krb5-locales libasn1-8-heimdal libcurl3-gnutls libffi6
  libgmp10 libgnutls30 libgssapi-krb5-2 libgssapi3-heimdal libhcrypto4-heimdal
  libheimbase1-heimdal libheimntlm0-heimdal libhogweed4 libhx509-5-heimdal
  libk5crypto3 libkeyutils1 libkrb5-26-heimdal libkrb5-3 libkrb5support0
  libldap-2.4-2 libnettle6 libp11-kit0 libroken18-heimdal librtmp1 libsasl2-2
  libsasl2-modules libsasl2-modules-db libsqlite3-0 libtasn1-6
  libwind0-heimdal
0 upgraded, 30 newly installed, 0 to remove and 2 not upgraded.
Need to get 3441 kB of archives.
After this operation, 13.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] Abort.
The command '/bin/sh -c apt-get install apt-transport-https' returned a non-zero code: 1


It is not even allowing me to enter Y or N , it just abort session and exit with code .

Is it all about having correct apt-get packages ? If so is there any way I can download package and then update apt-get but via dockerfile .

**Comment by dkoper** [comment]
I suppose with a Dockerfile you need to suppress prompting, so `RUN apt-get install -y apt-transport-https`.

Alternatively, you can download our deb package and install that using `dpkg`, but you'd still need curl or wget to download the package.

**Comment by reddymadhavi** [comment]
Yes, after having -y it gave me different error about again " enable to locate package cf " which is start of this thread . But it got resolved after updating apt-get .
