### ISSUE TITLE
restage help text should warn that it causes downtime

### ISSUE THREAD

**Issue by bleach** [cloudfoundry/cli#1244]
## Command  

cf help restage

## What occurred

Help text did not explain whether or not there would be downtime:

```$ cf help restage
NAME:
   restage - Recreate the app's executable artifact using the latest pushed app files and the latest environment (variables, service bindings, buildpack, stack, etc.)

USAGE:
   cf restage APP_NAME
```

## What you expected to occur

The help text to tell me if there would be app downtime.

## CLI Version  

`cf version 6.32.0+0191c33d9.2017-09-26`

## CF Trace

N/A

## Platform & Shell Details  

N/A

## Any other relevant information  

See also #922

**Comment by abbyachau** [comment]
Hi @bleach thanks again for raising this issue. Sorry it took so long for us to be able to get to it. We've updated the help text to warn users that this command incurs downtime. We've also added a line to the beginning of the command output to print the same warning - we hope if users see the message in time, they can control c to stop the command before the app goes down. Please see the tracker story if you want more details. This change will be in our next release. Closing this story as done but please do not hesitate to get in touch if you have any questions.
