### ISSUE TITLE
unable to see the folder after installation of CLI

### ISSUE THREAD

**Issue by sankeerthnarsina** [cloudfoundry/cli#1246]
After installing CLI, I don't see the folder Cloud foundry in Program files. Please help.!

Thanks in advance.

--
Sankeerth

**Comment by dkoper** [comment]
Hi @sankeerthnarsina 

The installation location depends on whether you install the CLI for "Anyone who uses this computer" or "Only for me".
In the case of "Only for me", you should look under `"%APPDATA%\Cloud Foundry"`, e.g. `D:\Users\sankeerth\AppData\Roaming\Cloud Foundry`.
The installer also adds this folder to your PATH. If you open a new command prompt and run `set path`, you should be able to find an entry with `Cloud Foundry` in there that has the full path to the `cf` binary.

Does that help?

Regards,
Dies Koper
CF CLI PM
