### ISSUE TITLE
Is it possible to limit some CLI commands?

### ISSUE THREAD

**Issue by jiangchuan1220** [cloudfoundry/cli#1248]
My requirement is to **limit CLI commands such as cf push is not available, cf apps is also not available, .etc**. 
I know assign roles can satisfy part of the requirement, but it is not enough because I can not create my own roles and combine different operations.  
**Can I delete some commands from the CLI commands?**

**Comment by dkoper** [comment]
Hi @jiangchuan1220 

It's open source, you can delete whatever you want and rebuild the CLI.

There is no way to limit specific commands of your choosing from e.g. `cf help` output, nor to disable them.
All you can do is disable feature flags to disable certain operations/commands, affecting all users on your platform, or set/unset a user's role.

Recently, the CF Permissions project was started to introduce permission control that is finer-grained than what the current roles offer, but that's still early days.

Regards,
Dies Koper
CF CLI PM

**Comment by jiangchuan1220** [comment]
@dkoper , Thanks for your reply. It is useful for me. 
Is there any guide which describes **how to rebuild the CLI and deploy it to Cloud Foundry**?

**Comment by dkoper** [comment]
Here's our documentation on how to build the CLI. https://github.com/cloudfoundry/cli/blob/master/.github/CONTRIBUTING.md

Not sure what you mean by "deploing it to Cloud Foundry"? It's a client to CF.

**Comment by jiangchuan1220** [comment]
@dkoper , I think we can not truly disable the commands by rebuild the CLI. If the users use a standard CLI instead of our custom CLI, they can still use the disabled commands.

**Comment by dkoper** [comment]
Correct.

I know of one CF provider who has disabled the `cf passwd` command by blocking the corresponding API call on their L1 FW. Could that be an option to explore?

**Comment by jiangchuan1220** [comment]
Yes, that can be an option. Another opinion is we add some interceptor between CLI and the server API, in which we can do some validation. Does Cloud Foundry support such kind of interceptor?

**Comment by dkoper** [comment]
@shalako As a CF admin, is there a way to install a route service in front of the CC API?

**Comment by maoyi8212** [comment]
@dkoper Does L1 FW means the layer 1 firewall, so that means setting some blocking rules for the specific API entries in the hardware gateway?

**Comment by shalako** [comment]
@dkoper It is possible to add a route service to route for CAPI, but it involves modifying the manifest for the `route_registrar` job.

**Comment by dkoper** [comment]
@maoyi8212 Correct.
