### ISSUE TITLE
pivotal cloud foundry throwing error with node

### ISSUE THREAD

**Issue by texirv0203** [cloudfoundry/cli#1249]
- I am trying to include node agent in my pcf.
- but I am getting below error after I execute this command cf restage webcomponent
   Failed to compile droplet: Failed to run all supply scripts: exit status 14
   Exit status 223
   Staging failed: STG: Exited with status 223
- can you tell me how to fix it.
- am I doing anything wrong with my environment variables of pcf

**refrence link** https://docs.appdynamics.com/display/PRO42/Install+the+Node.js+Agent
https://docs.pivotal.io/pivotalcf/1-12/buildpacks/node/node-tips.html#env-var

**User Provided Environment Variables**

    GRANT_TYPE                   implicit
    OPTIMIZE_MEMORY              true
    SSO_IDENTITY_PROVIDERS       uaa
    http_proxy                   http://proxy.blanket.com:80
    https_proxy                  http://proxy.blanket.com:80
    Name                         Value

**environment variables**

    {
      "staging_env_json": {},
      "running_env_json": {},
      "system_env_json": {
        "VCAP_SERVICES": {
          "p-identity": [
            {
              "credentials": {
                "client_id": "788787878723232323873287",
                "client_secret": "ewqyueyuewuwi87323287ejhwweiu",
                "auth_domain": "https://app-luagh.com"
              },
              "syslog_drain_url": null,
              "volume_mounts": [],
              "label": "p-identity",
              "provider": null,
              "plan": "app-auth",
              "name": "sso",
              "tags": []
            }
          ],
          "user-provided": [
            {
              "credentials": {
                "uri": "http://we.laugh.com"
              },
              "syslog_drain_url": "",
              "volume_mounts": [],
              "label": "user-provided",
              "name": "crystalreports",
              "tags": []
            }
          ],
          "appdynamics": [
            {
              "credentials": {
                "account-name": "technology-blanket",
                "port": "78787878",
                "account-access-key": "fdae8266e8b3",
                "host-name": "technology-blanket.saas.appdynamics.com",
                "ssl-enabled": "true"
              },
              "syslog_drain_url": null,
              "volume_mounts": [],
              "label": "appdynamics",
              "provider": null,
              "plan": "AppDynamics",
              "name": "appdynamics",
              "tags": [
                "appdynamics",
                "apm",
                "mobile real-user monitoring",
                "browser real-user monitoring",
                "database monitoring",
                "server monitoring",
                "application analytics"
              ]
            }
          ]
        }
      },
      "application_env_json": {
        "VCAP_APPLICATION": {
          "cf_api": "https://api.wdhjhj.laugh.com",
          "limits": {
            "fds": 16384,
            "mem": 8192,
            "disk": 2048
          },
          "application_name": "webcomponent",
          "application_uris": [
            "here.laugh.com"
          ],
          "name": "webcomponent",
          "space_name": "app-DEV",
          "space_id": "aeryuryw2872jk32iuk",
          "uris": [
            "here.laugh.com"
          ],
          "users": null,
          "application_id": "jkdsjkdsjk89989889",
          "version": "yuwrhjyuwuyw-237823878723kj",
          "application_version": "yhjjhhjhj-yuyuuy877887"
        }
      }
    }

**$ cf restage webcomponent**

    Restaging app webcomponent in org example-app / space sublime-text as 788781287...
    
    Staging app and tracing logs...
       Downloading build artifacts cache...
       Downloaded app package (6M)
       Downloaded build artifacts cache (26.2M)
       Staging...
       -----> Download go 1.9
       -----> Running go build supply
       -----> Nodejs Buildpack version 1.6.8
       -----> Installing binaries
              engines.node (package.json): unspecified
              engines.npm (package.json): unspecified (use default)
       -----> Installing node 4.8.4
              Download [https://buildpacks.cloudfoundry.org/dependencies/node/node-4.8.4-linux-x64-230101ff.tgz]
              **WARNING** Node version not specified in package.json. See: http://docs.cloudfoundry.org/buildpacks/node/node-tips.html
              Using default npm version: 2.15.11
       -----> Installing yarn 1.1.0
              Download [https://buildpacks.cloudfoundry.org/dependencies/yarn/yarn-v1.1.0-26588f71.tar.gz]
              Installed yarn 1.1.0
       -----> Creating runtime environment
              NODE_HOME=/tmp/contents811454074/deps/0/node
              PRO TIP: It is recommended to vendor the application's Node.js dependencies
              Visit http://docs.cloudfoundry.org/buildpacks/node/index.html#vendoring
              NODE_ENV=production
              NODE_MODULES_CACHE=true
              NODE_VERBOSE=false
              NPM_CONFIG_LOGLEVEL=error
              NPM_CONFIG_PRODUCTION=true
              - .npm
       -----> Restoring cache
              Loading 3 from cacheDirectories (default):
              - bower_components (not cached - skipping)
              - .cache/yarn (not cached - skipping)
              Installing node modules (package.json)
       -----> Building dependencies
       > uglifyjs-webpack-plugin@0.4.6 postinstall /tmp/app/node_modules/uglifyjs-webpack-plugin
       > node lib/post_install.js
       > SPORTS@1.0.0 postinstall /tmp/app
       > webpack -p --config ./webpack.prod.js --progress --profile --bail
        10% building modules 0/1 modules 1 active ...der/src/index.js!/tmp/app/app/main.ts
       [at-loader] Using typescript@2.5.3 from typescript and "tsconfig.json" from /tmp/app/tsconfig.json.
     30% building modules 174/183 modules 9 active .../app/app/services/animalsService.ts
     49% building modules 333/374 modules 41 active ...ar/http/src/backends/browser_jsonp.js
     67% building modules 519/537 modules 18 active ...ar/router/src/routlib/zlib/adler32.js
     69% building modules 698/707 modules 9 active ...mponents/title/titles-allocation.html
    54382ms building modules
       37ms sealing
       0ms basic module optimization
       1ms optimizing
       1ms chunk optimization
       42ms module optimization
       0ms advanced chunk optimization
       0ms basic chunk optimization
       0ms advanced module optimization
       0ms chunk modules optimization
       0ms module and chunk tree optimization
       0ms advanced chunk modules optimization
       12ms module reviving
       8ms module order optimization
       5ms module id optimization
       0ms chunk order optimization
       0ms chunk reviving
       20ms chunk id optimization
       88ms hashing
       1ms module assets processing
       164ms chunk assets processing
       238ms additional chunk assets processing
       0ms recording
       95741ms additional asset processing
        94% asset optimization
       [at-loader] Checking started in a separate process...
       1ms chunk asset optimization
       [at-loader] Checking finished with 4 errors
    7885ms asset optimization
       198ms emitting
           app.js  6.48 MB       0  [emitted]  [big]  app
       index.html  2.38 kB          [emitted]
          [6] ./app/mobile/mobile.service.ts 2.38 kB {0} [built]
          [7] ./app/services/nailService.ts 3.19 kB {0} [built]
              [] -> factory:9141ms building:209ms dependencies:674ms = 10024ms
              [] -> factory:92ms building:1167ms dependencies:9284ms = 10543ms
              [] -> factory:3595ms building:118ms dependencies:755ms = 4468ms
        [497] ./app/main.ts 7.37 kB {0} [built]
              [] -> factory:35ms building:756ms dependencies:42213ms = 43004ms
        [625] ./app/app.component.ts 53.9 kB {0} [built]
              [] -> factory:47ms building:1654ms dependencies:26464ms = 28165ms
           + 817 hidden modules
       ERROR in [at-loader] ./app/components/swimming-birds/playing-birds-laughing.ts:8316:50
           TS2341: Property 'allData' is private and only accessible within class 'playingrcap'.
              [0] ./node_modules/html-webpack-plugin/lib/loader.js!./app/index.html 2.52 kB {0} [built]
       Hash: 6ad9b11d2fa7af59bf00
       Version: webpack 3.7.1
       Time: 158876ms
              [] -> factory:10654ms building:378ms dependencies:85ms = 11117ms
              [] -> factory:16964ms building:327ms dependencies:8106ms = 25397ms
              [] -> factory:14883ms building:371ms dependencies:57ms = 15311ms
            Asset     Size  Chunks                    Chunk Names
          [1] ./app/services/SPORTS.service.ts 19.4 kB {0} [built]
         [35] ./app/services/decodeService.ts 3.25 kB {0} [built]
              [] -> factory:7496ms building:440ms dependencies:1ms = 7937ms
              [] -> factory:19193ms building:1177ms dependencies:0ms = 20370ms
              [] -> factory:8435ms building:188ms dependencies:0ms = 8623ms
              [] -> factory:9147ms building:832ms dependencies:7129ms = 17108ms
         [59] ./app/services/egplayingService.ts 3.57 kB {0} [built]
        [304] ./app/mobile/mobilions.ts 563 bytes {0} [built]
        [375] ./app/services/clipboard.service.ts 3.78 kB {0} [built]
         [18] ./app/services/playingService.ts 15 kB {0} [built]
         [70] ./app/services/animalsService.ts 968 bytes {0} [built]
        [133] ./app/services/canDeactivate.service.ts 2.91 kB {0} [built]
               factory:27ms building:6978ms = 7005ms
        [594] ./app/app.module.ts 35 kB {0} [built]
        [789] ./app/app.routing.ts 42.1 kB {0} [built]
              [] -> factory:29907ms building:4964ms dependencies:0ms = 34871ms
        [827] ./app/services/CanActivateViaAuthGuard.ts 1.42 kB {0} [built]
              [] -> factory:29945ms building:5159ms dependencies:2681ms = 37785ms
       45:15-36 Critical dependency: the request of a dependency is an expression
       WARNING in ./node_modules/@angular/core/src/linker/system_js_ng_module_factory_loader.js
       WARNING in ./node_modules/@angular/core/src/linker/system_js_ng_module_factory_loader.js
       57:15-102 Critical dependency: the request of a dependency is an expression
       ERROR in [at-loader] ./app/components/swimming-birds/playing-birds-laughing.ts:8330:43
       ERROR in [at-loader] ./app/components/swimming-birds/playing-birds-laughing.ts:8319:61
       ERROR in [at-loader] ./app/components/swimming-birds/playing-birds-laughing.ts:8370:43
           TS2341: Property 'allData' is private and only accessible within class 'playingrcap'.
           TS2341: Property 'allData' is private and only accessible within class 'playingrcap'.
           TS2341: Property 'allData' is private and only accessible within class 'playingrcap'.
                   factory:7018ms building:13ms = 7031ms
            1 asset
       Child html-webpack-plugin for "index.html":
       npm ERR! not with npm itself.
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!
       npm ERR!     npm owner ls SPORTS
       npm ERR! Linux 4.4.0-96-generic
       npm ERR! npm  v2.15.11
       npm ERR! node v4.8.4
       npm ERR!
       npm ERR! argv "/tmp/contents811454074/deps/0/node/bin/node" "/tmp/contents811454074/deps/0/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/app/.npmrc" "--cache" "/tmp/app/.npm"
       npm ERR! code ELIFECYCLE
       npm ERR! Exit status 2
       npm ERR!     npm bugs SPORTS
       npm ERR! There is likely additional logging output above.
       npm ERR! This is most likely a problem with the SPORTS package,
       npm ERR! Tell the author that this fails on your system:
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR! SPORTS@1.0.0 postinstall: `webpack -p --config ./webpack.prod.js --progress --profile --bail`
       npm ERR! Failed at the SPORTS@1.0.0 postinstall script 'webpack -p --config ./webpack.prod.js --progress --profile --bail'.
       npm ERR!     webpack -p --config ./webpack.prod.js --progress --profile --bail
       npm ERR!     /tmp/app/npm-debug.log
       npm ERR! Please include the following file with any support request:
              **ERROR** Unable to build dependencies: exit status 1
       Failed to compile droplet: Failed to run all supply scripts: exit status 14
       Exit status 223
       Staging failed: STG: Exited with status 223
       Stopping instance affd069e-bf48-4ab4-b613-54913c3abf23
       Destroying container
       Successfully destroyed container
    Error staging application: App staging failed in the buildpack compile phase
    FAILED

**Comment by dkoper** [comment]
Hi @texirv0203 

I've shared this issue with the Buildpacks PM, who suggested you submit this issue to their tracker at https://github.com/cloudfoundry/nodejs-buildpack/issues.

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Submitted to https://github.com/cloudfoundry/nodejs-buildpack/issues/110, thanks!
