### ISSUE TITLE
What is the interface used by CF CLI to interact with Cloud Foundry?

### ISSUE THREAD

**Issue by jasonkoo** [cloudfoundry/cli#1252]
I want to know what kind of interface used by CF CLI to talk to Cloud Foundry.
Is it the REST API or some other interfaces?
Thank you.

**Comment by dkoper** [comment]
Some are REST APIs. Some are web sockets. Set environment variable `CF_TRACE` to `true`, or to a filepath, to have the CLI output what API calls it makes when it invokes commands.

**Comment by jasonkoo** [comment]
Thank you @dkoper . This is of great help to me.

**Comment by dkoper** [comment]
You're welcome!
