### ISSUE TITLE
A question about implementation detail of cf push command

### ISSUE THREAD

**Issue by jasonkoo** [cloudfoundry/cli#1253]
The official CloudFoundry documentation describes the whole process of the cf push command in the following link.
https://docs.cloudfoundry.org/concepts/how-applications-are-staged.html

I want to know an implementation detail of the process in step 2, 4 and 6. All these three steps involve the interaction between the CF Command Line and Cloud Controller.  My question is in all these three steps does the CF Command Line communicate directly with Cloud Controller? Or for each step, the CF Command Line get the location of Cloud Controller from the router component first and then talk to Cloud Controller?

Thank you!

**Comment by dkoper** [comment]
For all those three steps the CLI makes API calls to the Cloud Controller API endpoint directly.
The Cloud Controller API endpoint is the same as the API endpoint you specify to `cf api` or `cf login -a`, so the CLI does not need to look it up from a server component.

That said, the API endpoint generally resolves to a load balancer fronting the Gorouters, or to a Gorouter directly, which forwards the request on to the Cloud Controller's web server. But that's transparent to the CLI.

**Comment by jasonkoo** [comment]
So all the API calls made by CLI will go through a Gorouter, although it's transparent to the CLI. Am I right?

**Comment by jasonkoo** [comment]
So the API endpoint is actually the address of a load balancer or a Gorouter and all the API calls made by CLI will go through a Gorouter and then arrive at Cloud Controller, although it's transparent to the CLI. Am I right?

**Comment by dkoper** [comment]
Right.

**Comment by jasonkoo** [comment]
@dkoper I am now clear. Thank you very much.
