### ISSUE TITLE
A question about the customization of "CF push" process

### ISSUE THREAD

**Issue by maoyi8212** [cloudfoundry/cli#1254]
Now I have some requirements to do some customizations to the ”CF push” process. The idea is that we still use "CF push"command to deploy our applications, but we want to do some validation(by validate the MD5 of the binary file or  by  some signature way) before being deployed to Diego cell. Now We plan to implement by different appraches:

Approach 1: by implement a customized CF CLI plugin and implement the validation logic in the plugin, the disadvantages is I need to use another syntax to do the validated push other than “CF push”
Approach 2: Is it possible to develop an interceptor before calling CF API, the interceptor will listen to events to indicate some milestones of the push process such as the app files has been stored completely in Blobstore. But the question is that I do not know whether this kind of interceptor is reasonable. Whether Cloud Foundry exposes the events I need?
![cfpush](https://user-images.githubusercontent.com/10125858/31750011-f6ce1e2e-b4af-11e7-8bb7-e3e54b1f4fed.JPG)
Approach 3:  I am not sure whether the CF API calls go through some  proxy/gateway or not, Is it possible to implement it by customizing the gateway? 
Approach 4: I am are not sure whether there are some other way to implement our requirement. So it is open to give more options.

**Comment by dkoper** [comment]
Hi @maoyi8212 

If your requirement is to do validation on app bits before allowing it to be staged and started, I believe there is a proposal to support mandatory buildpacks that would be run before any other buildpack to support this use case.
@sclevine Do you have more information on this proposal and its current state?

**Comment by sclevine** [comment]
I am considering writing a proposal to add functionality to CC that would allow the operator to create buildpack groups. These groups would represent a multi-buildpack series of system buildpacks. System buildpacks specified in a group could be individually disabled, so that they could only run as part of the group. This should provide a more flexible version of mandatory buildpacks.

I don't have a timeline for this proposal yet.

**Comment by maoyi8212** [comment]
@sclevine Thank you for your information. Currently do you have a buildpack which can do the validation to app bits already? Or I need to develop a buildpack to implement the logic by myself ? If there is sourcecode to do the validation already, could you please share the link with me?

**Comment by sclevine** [comment]
I am not aware of a buildpack that does this already. I think the common workflow would be validate your app bits before running `cf push`, and I'm not sure I understand your motivation for doing this in the platform. How would the validating buildpack know the checksums of the app files? Do you plan to sign the app files using a private key and have the buildpack validate them using public key?

**Comment by maoyi8212** [comment]
@sclevine Now we plan to store the checksums of the app files in a artifact repository with the app bits. When we push the application, maybe upload the validation information(checksums, signed keys) together with the the app bits to the blob store. Then we implement the validation logic in buildpack to make the integrity and consistency of the app bits

**Comment by sclevine** [comment]
If you're validating the app bits for security reasons, pushing the app bits with checksums would be vulnerable to a malicious user modifying the checksums at the same time that they modify the app bits. I would definitely encourage you to include a public key in the buildpack and use that to verify signatures.

**Comment by maoyi8212** [comment]
@sclevine Make sense. Thanks a lot for your suggestions!
