### ISSUE TITLE
That 70s Bug

### ISSUE THREAD

**Issue by henrytk** [cloudfoundry/cli#1255]
We run open source CloudFoundry and one of our users provided a screenshot of a potential bug. We thought it may be of use to you.

## Command  

`cf app APP_NAME`

## What occurred

![that-70s-bug](https://user-images.githubusercontent.com/8709339/31777536-2acbd8a2-b4e6-11e7-98f4-75d29bc822d9.png)

## What you expected to occur

A sensible date to be displayed, or no date at all.

## CLI Version  

cf version 6.29.0+ff886fa93.2017-07-24

## CC API Endpoint Version  

2.96.0

## CF Trace

Not available.

## Platform & Shell Details  

```
$ uname -a
Darwin gds3936.local 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64
```

**Comment by dkoper** [comment]
Thanks! This is unexpected. But the CLI is just displaying what's returned by the Cloud Controller API.
The CF trace should show what it returned. If that's not returning a valid date, please submit an issue to their tracker (https://github.com/cloudfoundry/cloud_controller_ng/issues).

**Comment by henrytk** [comment]
Closed because it was transient and we don't have access to `CF_TRACE` output.
