### ISSUE TITLE
cf v3-push missing --random-route

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cli#1257]
`cf push` has a wonderfully useful `--random-route` flag. `cf v3-push` does not yet have this.

**Comment by dkoper** [comment]
We haven't implemented anything more than the basic for now as the V3 APIs to create and map routes were not ready yet. They are still not ready yet.
This is good feedback to help us prioritize remaining work. Thanks!

**Comment by tjvman** [comment]
We don't plan on adding `--random-route` to `v3-push` in any v6.* versions of the cf CLI. However, CLI v7's `push` *is* currently planned to support random route. The story for tracking `--random-route` in v7 is [here](https://www.pivotaltracker.com/story/show/159808908).

Closing this issue.
