### ISSUE TITLE
Failed to curl v2/organizaitons/:guid/spaces while a deletion of app under this spaces is happening

### ISSUE THREAD

**Issue by zongzw** [cloudfoundry/cli#1258]
https://github.com/cloudfoundry/cli/blob/ffee70cca68ab15df71f48641f6fa3bb007c4a2b/cf/api/spaces/spaces.go#L43

I encountered a problem that the curl to `v2/organizaitons/:guid/spaces?q=name%3A<space name>&inline-relations-depth=1` fails with message:

`REQUEST: [2017-10-26T11:54:54+08:00]
GET /v2/organizations/5a484fd3-7d07-4688-a86a-1217dd740cfa/spaces?q=name%3Auptime&inline-relations-depth=1 HTTP/1.1^M
Host: api.cn.bluemix.net^M
Accept: application/json^M
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json^M
User-Agent: go-cli 6.20.0+25b1961 / linux^M
^M

RESPONSE: [2017-10-26T11:54:55+08:00]
HTTP/1.1 500 Internal Server Error^M
Transfer-Encoding: chunked^M
Connection: Keep-Alive^M
Content-Type: application/json;charset=utf-8^M
Date: Thu, 26 Oct 2017 03:54:55 GMT^M
Server: nginx^M
Set-Cookie: DPJSESSIONID=PBC5YS:655520496; Path=/; Domain=.cn.bluemix.net^M
X-Backside-Transport: FAIL FAIL^M
X-Client-Ip: 172.17.0.60^M
X-Content-Type-Options: nosniff^M
X-Global-Transaction-Id: 79849829^M
X-Vcap-Request-Id: 8532ee00-aae0-41da-4987-835bc7c490ef,8532ee00-aae0-41da-4987-835bc7c490ef::1912d90a-2e3f-4cd2-bb3e-7dc30dddd99c^M
^M
63^M
{
  "error_code": "UnknownError",
  "description": "An unknown error occurred.",
  "code": 10001
}`

and logs from cc:

`{\"description\"=>\"undefined method `name' for nil:NilClass\", \"error_code\"=>\"CF-name\", \"backtrace\"=>`

It is occasionally when there is another thread doing an app deletion under that space. 

Why should we extend the queries with inline-relations-depth=1?

**Comment by dkoper** [comment]
That query parameter is not required here and was removed for the `spaces` command in cf CLI 6.32.0.
