### ISSUE TITLE
Improve error message if calling `cf install-plugin` with a directory

### ISSUE THREAD

**Issue by 46bit** [cloudfoundry/cli#1259]
I've been writing a CF plugin. I tried installing the plugin from a local directory and received a surprising error. 

## Command  

```
cf install-plugin paas-cf-app-push -f
```

## What occurred

```
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
mkdir /Users/michaelmokrysz/.cf/plugins/temp949400214/548287741: not a directory
FAILED
```

## What you expected to occur

I expected the plugin to install successfully. As I now know from debugging the `cf` source, one installs binaries rather than directories, so it should have failed. In that case I'd expect a descriptive error message rather than the unclear one currently output.

## CLI Version  

cf version 6.32.0+0191c33d9.2017-09-26 (the latest at time of writing)

## Platform & Shell Details  

Mac OS X 10.11 iTerm

**Comment by 46bit** [comment]
I'd be quite happy to submit a PR for this if you'd be likely to review and accept it?

**Comment by dkoper** [comment]
I can reproduce it on Windows as well:
```
D:\Users\koperd\Downloads\bin>cf install-plugin t -f
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
mkdir D:\Users\koperd\.cf\plugins\temp038681339\214968862.exe: The system cannot find the path specified.
FAILED
```

We'd definitely review your PR!

**Comment by dkoper** [comment]
@46bit Were you still planning to submit a PR or shall I schedule this story for my team to take a look? (No guarantees we'll get to it soon though).

**Comment by 46bit** [comment]
@dkoper Thanks for the reminder, I'm working on a patch. 👍

**Comment by heyjcollins** [comment]
With the GA of the v7 CLI, we're no longer actively developing against the v6 line.  With an interest the overall hygiene of the CLI project we're closing this  issue.
If this issue is still occurring in v7 please feel free to comment and re-open. Thank you!
