### ISSUE TITLE
SSL_CERT_FILE only works for Linux, not for OSX

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cli#1263]
```
export SSL_CERT_FILE=/path/to/cert
cf login -a https://api.mything.com
```

This works on linux, but on osx it doesn't seem to know about `SSLCERT_FILE` and I get:

```
Invalid SSL Cert for api.18-220-97-61.sslip.io
TIP: Use 'cf login --skip-ssl-validation' to continue with an insecure API endpoint
```

**Comment by dkoper** [comment]
That's as [documented](https://docs.cloudfoundry.org/cf-cli/self-signed.html).
We rely on Golang for this functionality, and unfortunately they only support it on Linux.
