### ISSUE TITLE
cf logs text is not visible

### ISSUE THREAD

**Issue by mrsideshowjack** [cloudfoundry/cli#1264]
## Command  

`cf logs my-app --recent`

## What occurred

The text from the logs is usually invisible on cmd or [hyper terminal](https://hyper.is), doesn't occur on git bash mintty 2.0.3

![screenshot](https://puu.sh/yid9v/ded29121c7.png)
screenshot

![screenshot](https://puu.sh/yidab/6c41bd0763.png)
visible when highlighted

## CLI Version  
`cf version 6.21.0+dff2cf8-2016-07-27`

## CC API Endpoint Version  
`API endpoint: https://api.eu-gb.bluemix.net (API version: 2.92.0)`

## CF Trace

```
REQUEST: [2017-11-09T13:32:14Z]
GET /v2/spaces/e5337677-b4f9-4d12-86d7-6f3eb26a2523/apps?q=name%3Aentelligently-v2&inline-relations-depth=1 HTTP/1.1
Host: api.eu-gb.bluemix.net
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.21.0+dff2cf8 / windows



RESPONSE: [2017-11-09T13:32:15Z]
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Cache-Control: max-age=0, no-cache, no-store
Content-Type: application/json;charset=utf-8
Date: Thu, 09 Nov 2017 13:32:13 GMT
Expires: Thu, 09 Nov 2017 13:32:13 GMT
Pragma: no-cache
Server: nginx
X-Backside-Transport: OK OK
X-Content-Type-Options: nosniff
X-Global-Transaction-Id: 2972850621
```

## Platform & Shell Details  

Windows 10 64, Using Hyper Terminal, also happens on cmd 

## Any other relevant information  

n/a

**Comment by dkoper** [comment]
Hi @mrsideshowjack 

Do you also get this on a recent cf CLI release? (yours seems more than a year old)
Have you customized your command prompt/Windows colors in any way?

**Comment by mrsideshowjack** [comment]
updated to `cf version 6.32.0+0191c33d9.2017-09-26`, problem doesn't persist
sorry for the false report, feel free to close this issue

**Comment by dkoper** [comment]
Thanks for the prompt check!
