### ISSUE TITLE
Inheriting manifest to override a single app and using the -p option causes "Incorrect Usage"

### ISSUE THREAD

**Issue by JohnAJimenez** [cloudfoundry/cli#1266]
## Command  
`cf push -f ./deploy-info/dev.manifest.yml -p ./artifacts/app.jar`

## What occurred
FAILED
Incorrect Usage. Command line flags (except -f) cannot be applied when pushing multiple apps from a manifest file.

## What you expected to occur
A proper deploy using my dev overrides instead of the prod

## CLI Version  
6.30.0+decf883.2017-09-01

## CC API Endpoint Version  
Private Enterprise

## Platform & Shell Details  
Concourse CF Resource
https://github.com/concourse/cf-resource

## Any other relevant information 
Dir Structure:
```
. <cf run here>
├── artifacts
│   └── app.jar <this might change per build, so need to pass as param>
└── deploy-info
    ├── dev.manifest.yml
    └── manifest.yml
```

manifest.yml:
```
---
memory: 1G
instances: 1
buildpack: https://github.com/cloudfoundry/java-buildpack.git
timeout: 180

applications:
- name: feature-java-hello-world
```

dev.manifest.yml
```
---
inherit: manifest.yml
applications:
- name: feature-java-hello-world
  host: fjhw
```

**Comment by dkoper** [comment]
Hi @JohnAJimenez 

I would have also expected that to work.

We'd like to better understand people's use of app manifest and sent out a survey just now.
Please take a look:
https://lists.cloudfoundry.org/g/cf-dev/message/7552

If/how we address this particular issue greatly depends on the feedback we get from this survey.

Cheers,
Dies Koper
CF CLI PM

**Comment by JohnAJimenez** [comment]
Responded. Thank you for reaching out.

**Comment by dkoper** [comment]
Thank you for responding to the survey.
Based on the survey results, we decided to deprecate inheritance and will therefore no longer address issues with it.
See these release notes for details on the deprecated app manifest features: https://github.com/cloudfoundry/cli/releases/tag/v6.34.0
