### ISSUE TITLE
Push buildpack from github using commit id

### ISSUE THREAD

**Issue by amiramw** [cloudfoundry/cli#1268]
## Command  

cf push buildpack-hash -b https://github.com/cloudfoundry/java-buildpack.git#96dac92cbcbd365d81959d9130de2f97cb688093

## What occurred

2017-11-16T15:21:12.61+0200 [STG/0] ERR Failed to clone git repository at https://github.com/cloudfoundry/java-buildpack.git

## What you expected to occur

In the past this way of pulling buildpack using a specific commit id used to work. See: https://github.com/cloudfoundry/cli/issues/215#issuecomment-62853478

Is it intentional that it doesn't work anymore?

## CLI Version  

cf version 6.26.0+9c9a261.2017-04-06

## CC API Endpoint Version  

2.98.0

## Platform & Shell Details  

Windows 8.1 cmd.exe

**Comment by dkoper** [comment]
Ah interesting!
@sclevine and I were looking at that a few months ago, found that it didn't work, had the impression it could have never worked, and removed the related article on docs.cloudfoundry.org about it.

The CLI just passes the specified value to the backend, so nothing changed on the CLI side.
The backend, in a component that I believe is now maintained by the Buildpacks team, simply invokes `git clone -b` command to check out the right branch, and doesn't support commit sha's.

@emalm I believe Diego owned this code before Buildpacks. Do you remember anything about this?

**Comment by emalm** [comment]
@dkoper Looks like Diego did work to support custom git buildpacks in https://www.pivotaltracker.com/story/show/76320826, and was intended to match the functionality in the DEAs (presumably from https://github.com/cloudfoundry-attic/dea_ng/pull/90/files). I don't see any discussion on either side of intentionally supported cloning from a particular commit SHA, just branch heads and tags.

**Comment by dkoper** [comment]
@emalm It was on docs.cloudfoundry.org, which I [recently removed](https://github.com/cloudfoundry/docs-buildpacks/commit/5eb40c4435ad442206dd79eae15eb809e52315a0#diff-2a811ebf8ac8987bec3d53aef09cb6fb) after a discussion with Stephen.

**Comment by emalm** [comment]
Yeah, but that functionality isn't covered in any of the tests in those code bases.

**Comment by sclevine** [comment]
I believe this was erroneously added to the docs here:
https://github.com/cloudfoundry/docs-buildpacks/commit/16906e1d3fa804e14212d4ff610bcf60b05af6a7

We have never supported specifying a commit SHA, to the best of my knowledge.

**Comment by dkoper** [comment]
@aminjam I hope that answer your question?

**Comment by amiramw** [comment]
Thanks for the answers.
