### ISSUE TITLE
CF CLI only upload parts of the origin packages

### ISSUE THREAD

**Issue by jiangchuan1220** [cloudfoundry/cli#1269]
## Issue
When using cf push, the package uploaded from cf cli is not the origin package.

## Context
We need to validate the integrity of packages uploaded from cf push. Our current idea is put a Nginx between cfcli and CC API and validate the package uploaded to Nginx.  But we found the package is not complete because the Cloud Controller has a resource cache. If a file is cached, it will not be uploaded. We want to know more detailed information about the resource cache. When will a file be cached and remove from the cache? Is it possible to close the cache function?
Thanks,
Jiang Chuan.

**Comment by dkoper** [comment]
During the `cf push` process, just before uploading the app bits, the CLI sends a list of all app bits and their checksums to the [resource matching API](http://apidocs.cloudfoundry.org/272/resource_match/list_all_matching_resources.html). Whatever is returned is excluded from the archive of app bits it subsequently uploads.

The cache is a CC feature, please send your questions about it to their tracker. I believe it has configurable minimum and maximum file sizes that are cached. Maybe you can set the minimum very big or the maximum to 0 to disable it?

**Comment by jiangchuan1220** [comment]
A possible solution is to return empty body ("[]") for resource match API from interceptor. Then the resource cache will not take effect without modifying CF configuration.
