### ISSUE TITLE
cf logs and http proxy

### ISSUE THREAD

**Issue by igm** [cloudfoundry/cli#127]
Currently there seems to be no way to specify HTTP proxy for "cf logs" command. Usual symptom is this error message:
"websocket.Dial wss://loggregator.run.pivotal.io:4443/tail/?app=7da5e11b-8190-4474-b93d-af3de716104c: dial tcp 54.236.172.232:4443: connection timed out."

**Comment by debu66er** [comment]
Hello, today I suffered this issue again using CF CLI v 6.10.0. Was this feature removed recently? Or, do we have any specific requirement from Proxy side to get it working? Thanks!

Error msg: Error dialing loggregator server: Proxy Authentication Required.
Please ask your Cloud Foundry Operator to check the platform configuration (logg
regator endpoint is wss://loggregator.xxxxx.xxxx:443

**Comment by charyorde** [comment]
Reporting this error as well:
```
09-Jun-2015 12:52:39 	Warning: error tailing logs
09-Jun-2015 12:52:39 	Error dialing loggregator server: dial tcp: lookup loggregator.10.244.0.34.xip.io: no such host.
09-Jun-2015 12:52:39 	Please ask your Cloud Foundry Operator to check the platform configuration (loggregator endpoint is wss://loggregator.10.244.0.34.xip.io:443).
09-Jun-2015 12:52:39 	Starting app socialgraph in org yookos / space dev as admin...
09-Jun-2015 12:52:49 	
09-Jun-2015 12:52:49 	FAILED
09-Jun-2015 12:52:49 	StagingError
```
