### ISSUE TITLE
Difference in help dcoumentation for how to provide json data as string in cli of different OS  

### ISSUE THREAD

**Issue by deepaksrgm2010** [cloudfoundry/cli#1274]
There is a difference in documentation as to how to provide a json data as string for a cli command in help documentation of various commands.
For example one sees the _**difference in docs**_ when one run
`cf cup -h`
and when one run
` cf update-service --help`

**Comment by dkoper** [comment]
Hi @deepaksrgm2010 

Can you be more precise?
I am for example comparing the following two:
> cf update-service mydb -c '{"ram_gb":4}'
> cf create-user-provided-service my-db-mine -p '{"username":"admin","password":"pa55woRD"}'

and from a JSON point of view both look valid?

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Closing due to lack of details. Feel free to reopen or submit a new issue if you can help us understand the issue.
