### ISSUE TITLE
Commands shouldn't return an error with a copy of the password if `-` is at the start of a password

### ISSUE THREAD

**Issue by brittag** [cloudfoundry/cli#1288]
This is a suggestion for improving parsing for more predictable behavior.

## Command

In the following scenario, the password starts with a `-` (dash):

`cf login -u username -p -my-password`

## What occurred

`cf login` returned an error, which can be logged (and cause a security incident) if you're using it in an automated script with a CI/CD tool:

```
Incorrect Usage: expected argument for flag `-p', but got option `-my-password'
```

## What you expected to occur

This shouldn't return an error that prints the password. Likely, the parser shouldn't treat `-` specially if it follows an option flag that is expected to take an argument.

## CLI Version  

cf version 6.33.1+c77e55743.2017-12-15

## CC API Endpoint Version  

api version:    2.100.0

## Platform & Shell Details  

macOS 10.13.2, Terminal app

## Any other relevant information  

`cf auth` also gives results I didn't expect for passwords that start with a dash. It doesn't print the whole password though, just a character:

```
cf auth username -password
Incorrect Usage: unknown flag `p'
```

**Comment by nickwei84** [comment]
Hi @brittag. The error you are seeing is from the [library](https://github.com/jessevdk/go-flags) we are using to parse command line arguments. In my humble opinion, I don't think the author will change this behavior. You could try making a feature request.

As an alternative, if you put quotes around the password, that will be properly parsed as a value to the -p flag. Please use single quotes because bash will evaluate special characters otherwise (ie. if you use double quotes).

Please let us know if there's anything else we can help you with.

**Comment by brittag** [comment]
Thank you @nickwei84! I'll file a suggestion in the upstream library in case they would like to consider this.

Do you think the docs pages at http://cli.cloudfoundry.org/en-US/cf/login.html and http://cli.cloudfoundry.org/en-US/cf/auth.html should be updated to note when using single quotes may be helpful? They document double quotes but not single quotes.

Feel free to close this issue since there isn't work to be done in the CF CLI itself. :)

**Comment by nickwei84** [comment]
@brittag Thanks for the suggestion to the docs. The single quotes are for bash shells only. Maybe there is a better place to document this. I'll also check and see where that should go.

**Comment by dkoper** [comment]
Hi @brittag 

Thanks for filing the feature request with goflags. I'll also keep an eye out for a response and chime in if need be.
In a related issue, it was mentioned that the following notation should work: `cf login -u user -p=-my-password`. I have tested this on Windows and it works for me.
I would still like to recommend `cf auth` for scripts, which I understand should work when using single quotes in bash shells, but am not aware of a work around for batch scripts on Windows.

Regards,
Dies Koper
CF CLI PM
