### ISSUE TITLE
update-service-broker is unable to use USERNAME starting with `-`

### ISSUE THREAD

**Issue by bkrannich** [cloudfoundry/cli#1289]
## Command  

```
cf update-service-broker my-broker -myusernamestartingwithdash pass https://my.brokerurl.com
```
```
cf update-service-broker my-broker '-myusernamestartingwithdash' pass https://my.brokerurl.com
```
```
cf update-service-broker my-broker "-myusernamestartingwithdash" pass https://my.brokerurl.com
```

## What occurred

```
Incorrect Usage: unknown flag `m'
```

## What you expected to occur

I was expecting that I can specify a username starting with ```-``` 

## CLI Version  

```
cf version 6.33.1+c77e55743.2017-12-15
```

## CC API Endpoint Version  

```
api version:    2.99.0
```

## CF Trace

n/a

## Platform & Shell Details  

macOS High Sierra 10.13.2
iTerm Build 3.1.5

## Any other relevant information  

To me, the issue sounds similar to #1277.

**Comment by dkoper** [comment]
And #1288!

**Comment by XenoPhex** [comment]
@bkrannich thanks for creating this issue. We've looked into this issue previously and we believe since it is standard not to use `-` in username/password values, we will be closing this issue as a won't fix. Feel free to create a new issue or add a comment here if you have any additional feedback.
