### ISSUE TITLE
64bit RPMS won't install on RHEL 6.4 or Fedora 19

### ISSUE THREAD

**Issue by hardillb** [cloudfoundry/cli#129]
I tried to install the CF cli tools on 2 64bit RPM based distros and got the following message.

```
# yum localinstall http://go-cli.s3-website-us-east-1.amazonaws.com/releases/latest/cf-cli_amd64.rpm
Loaded plugins: product-id, security, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Repository 'MyISORepository' is missing name in configuration, using id
Setting up Local Package Process
cf-cli_amd64.rpm                                         | 3.2 MB     00:04 ... 
Examining /var/tmp/yum-root-PIC6Np/cf-cli_amd64.rpm: cf-cli-6.0.2_0bba99f-1.amd64
Cannot add package http://go-cli.s3-website-us-east-1.amazonaws.com/releases/latest/cf-cli_amd64.rpm to transaction. Not a compatible architecture: amd64
Nothing to do
```

The error infers the arch flag in the spec file for the rpm is wrong, I suspect is should be 'x86_64' not 'amd64'

**Comment by yogananda-muthaiah** [comment]
Hi I
I am still facing the issue... 

[ec2-user@ip-XXXXXXXXXXX~]$ sudo yum install cf-cli
Last metadata expiration check: 1:46:38 ago on Sun 22 Mar 2020 08:13:57 AM UTC.
No match for argument: cf-cli
Error: Unable to find a match

**Comment by yogananda-muthaiah** [comment]
even this command

[ec2-user@ip-XXXXXXX ~]$ sudo yum localinstall http://go-cli.s3-website-us-east-1.amazonaws.com/releases/latest/cf-cli_amd64.rpm
Last metadata expiration check: 1:49:23 ago on Sun 22 Mar 2020 08:13:57 AM UTC.
[MIRROR] cf-cli_amd64.rpm: Status code: 404 for http://go-cli.s3-website-us-east-1.amazonaws.com/releases/latest/cf-cli_amd64.rpm
[FAILED] cf-cli_amd64.rpm: Status code: 404 for http://go-cli.s3-website-us-east-1.amazonaws.com/releases/latest/cf-cli_amd64.rpm
Status code: 404 for http://go-cli.s3-website-us-east-1.amazonaws.com/releases/latest/cf-cli_amd64.rpm
