### ISSUE TITLE
CF_TRACE fails with plugin.CliConnection.CliCommandWithoutTerminalOutput

### ISSUE THREAD

**Issue by mastertinner** [cloudfoundry/cli#1290]
## Command  

`CF_TRACE=true cf invitations` (with [Swisscom Application Cloud cf CLI Plugin](https://github.com/swisscom/appcloud-cf-cli-plugin) installed). Any plugin command which uses `plugin.CliConnection.CliCommandWithoutTerminalOutput` will do though.

## What occurred

The `plugin.CliConnection.CliCommandWithoutTerminalOutput` method doesn't generate any output if used with the `CF_TRACE=true` flag.

## What you expected to occur

I expect the behavior of the method not to change if `CF_TRACE=true` is used. It woks well with `CF_TRACE=false`.

## CLI Version  

6.33.0

## CC API Endpoint Version  

2.99

## Platform & Shell Details  

macOS 10.13.2 with iTerm 3.1.5

**Comment by dkoper** [comment]
Hi @mastertinner 

This is an issue that would take too much effort to fix so we've declared it a known limitation:
https://github.com/cloudfoundry/cli#known-issues

Regards,
Dies Koper
CF CLI PM

**Comment by mastertinner** [comment]
Thanks, @dkoper. Sorry for not looking there before creating an issue.
