### ISSUE TITLE
"invalid memory address or nil pointer dereference" if using terminal.UI.Ok() 

### ISSUE THREAD

**Issue by mastertinner** [cloudfoundry/cli#1291]
## Command  

Any CLI command coming from a plugin that uses `terminal.UI.Ok()`

## What occurred

Example error output:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12f1117]

goroutine 1 [running]:
code.cloudfoundry.org/cli/cf/terminal.(*terminalUI).Ok(0xc42005ba40)
        /Users/taafuto1/go/src/code.cloudfoundry.org/cli/cf/terminal/ui.go:154 +0x57
main.(*AppCloudPlugin).Invitations(0xc42012e110, 0x1644640, 0xc42012e120, 0xb, 0xffffffffffffffff)
        /Users/taafuto1/go/src/github.com/swisscom/appcloud-cf-cli-plugin/invitations.go:23 +0x1a2
main.(*AppCloudPlugin).Run(0xc42012e110, 0x1644640, 0xc42012e120, 0xc4200101d0, 0x1, 0x1)
        /Users/taafuto1/go/src/github.com/swisscom/appcloud-cf-cli-plugin/main.go:270 +0xafd
code.cloudfoundry.org/cli/plugin.Start(0x163db20, 0xc42012e110)
        /Users/taafuto1/go/src/code.cloudfoundry.org/cli/plugin/plugin_shim.go:34 +0x2a0
main.main()
        /Users/taafuto1/go/src/github.com/swisscom/appcloud-cf-cli-plugin/main.go:475 +0x3d
```

## What you expected to occur

No errors

## CLI Version  

6.33

## CC API Endpoint Version  

2.99

## Platform & Shell Details  

macOS 10.13.2 with iTerm 3.1.5

**Comment by dkoper** [comment]
`cf.terminal` is legacy code that is planned for deprecation. For more up to date consistency with the CF CLI, please look at the [util/ui package](https://github.com/cloudfoundry/cli/tree/master/util/ui).
Also worth noting, neither of these libraries have been designed to be publicly vendored and are subject to sudden changes without notice, though not likely.
