### ISSUE TITLE
terminal.UI.Failed() doesn't match CLI styling

### ISSUE THREAD

**Issue by mastertinner** [cloudfoundry/cli#1292]
## Command  

Any CLI plugin which uses the `terminal.UI.Failed()` method.

## What occurred

`terminal.UI.Failed()` prints the following output:

```
FAILED
My error message
```

(all in white letters)

whereas failed messages of native CLI commands print the following:

```

My error message
FAILED
```

(where "FAILED" is in the `terminal.FailedColor` color).

## What you expected to occur

I would expect the two messages to be styled in the same way.

## CLI Version  

6.33

## CC API Endpoint Version  

2.99

## Platform & Shell Details  

macOS 10.13.2 with iTerm 3.1.5

**Comment by dkoper** [comment]
`cf.terminal` is legacy code that is planned for deprecation. For more up to date consistency with the CF CLI, please look at the [util/ui package](https://github.com/cloudfoundry/cli/tree/master/util/ui).
Also worth noting, neither of these libraries have been designed to be publicly vendored and are subject to sudden changes without notice, though not likely.

In the next few weeks we'll try to respond to the question on https://github.com/cloudfoundry/cli/pull/1287#issuecomment-352228510 about preparing guidelines that plugins can follow.
