### ISSUE TITLE
Display cost and meta-data from a given service

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#1298]
## Command  

```
$ cf m -s cassandra 
```

## What occurred

```
$ cf m -s cassandra 
Getting service plan information for service cassandra as gberche...
OK

service plan   description                                                            free or paid
default        This is a default cassandra plan.  All services are created equally.   paid
```

## What you expected to occur

I would like to have details on the plans metadata in particular the costs detailed into https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#plan-metadata-fields

Currently AFAIK, a CLI user has to trace the CLI API calls to infer the service cost:

```
$ (master) CF_TRACE=true cf m -s cassandra | grep description -A4
        "description": "A simple cassandra service broker implementation",
        "long_description": null,
        "version": null,
        "info_url": null,
        "active": true,
        "bindable": true,
--
        "description": "This is a default cassandra plan.  All services are created equally.",
        "service_guid": "04b432cb-995e-4b1e-a3ef-2c973402d333",
        "extra": "{\"costs\":[{\"amount\":{\"usd\":0.0},\"unit\":\"MONTHLY\"}],\"bullets\":[\"Shared cassandra server\",\"100 MB Storage (not enforced)\",\"40 concurrent connections (not enforced)\"]}",
        "unique_id": "cassandra-plan",
        "public": true,
--

```

It would be great if a more user friendly option was given to dump the associated meta data (in plain json or tabular format)

## CLI Version  

cf version 6.33.1+c77e55743.2017-12-15

**Comment by shalako** [comment]
Reach out to Matt McNeeney; he’s PM for the marketplace and OSBAPI now.

**Comment by gberche-orange** [comment]
@XenoPhex the metadata fields are still recommended in the OSB API "Service metadata" profile, see https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#service-metadata

**Comment by abbyachau** [comment]
Hi @gberche-orange thanks, we spoke to SAPI team (@mattmcneeney) about this feature request yesterday. We'll be looping back to let you know if this is something we plan on supporting, thanks.

**Comment by heyjcollins** [comment]
With the GA of the v7 CLI, we're no longer actively developing against the v6 line.  With an interest the overall hygiene of the CLI project we're closing this  issue.
If this issue is still occurring in v7 please feel free to comment and re-open. Thank you!

**Comment by gberche-orange** [comment]
thanks @heyjcollins, I notice this indeed has been addressed in v7

```
$ cf m -e cleardb
Getting service plan information for service offering cleardb in org bercheg-org / space gberche-dev-box as bercheg@gmail.com...

broker: appdirect
   plan    description                                                                     free or paid   costs                available
   spark   Great for getting started and developing your apps                              free           USD 0.00/MONTHLY     yes
   boost   Best for light production or staging your applications                          paid           USD 10.00/MONTHLY    yes
   amp     For apps with moderate data requirements                                        paid           USD 50.00/MONTHLY    yes
   shock   Designed for apps where you need real MySQL reliability, power and throughput   paid           USD 100.00/MONTHLY   yes

$ cf version 
cf version 7.0.1+fb3f929c2.2020-06-24
$ cf t
API endpoint:   https://api.run.pivotal.io
API version:    3.86.0
```
