### ISSUE TITLE
6.34 breaks .cfignore

### ISSUE THREAD

**Issue by mastertinner** [cloudfoundry/cli#1300]
## Command  

`cf push`

## What occurred

`No app files found in '/.../my-app'`

## What you expected to occur

The app should be pushed.

## CLI Version  

6.34

## CC API Endpoint Version  

2.99

## Platform & Shell Details  

Mac OS X 10.13.2, iTerm 3.1.5

## Any other relevant information  

I usually add `.cfignore` files like the one [here](https://github.com/mastertinner/s3manager/blob/master/.cfignore) to my apps. So far this has worked fine. With CLI 6.34 however, this doesn't work anymore. Adding `/*` at the beginning of a `.gitignore` file and then specifying the files I don't want to ignore with `!/...` should be possible according to [the Git docs](https://git-scm.com/docs/gitignore). However, when I do it with `.cfignore`, the `cf push` command fails. Specifically:

```txt
/*

!/mybinary
```

fails. But 

```txt
/*

!mybinary
```

works.

The second choice can push unwanted files and folders which are called `mybinary` but aren't at the root level of my project.

**Comment by rlk833** [comment]
For me it actually ignored completely the entire .cfignore. I had many ignores in it and everything was pushed. None of the ignores were honored.

This happened as soon as I stepped up to this cf cli. The previous release worked perfectly with no changes to the .cfignore file.

I don't know if it is significant, but all of the entries are of the form `/yada` to denote only from the current directory should `yada` be ignored, not if found somewhere else.

**Comment by dkoper** [comment]
Hi @mastertinner 

Nice catch! Thanks for those details. I believe we've just fixed it. Can you try with our edge binary and confirm it's all working as expected for you now?
https://github.com/cloudfoundry/cli#edge-binaries

Cheers,
Dies Koper
CF CLI PM

**Comment by mastertinner** [comment]
@dkoper, with the edge binary it does indeed work as expected. Many thanks for the quick fix!

**Comment by mastertinner** [comment]
@dkoper, can we get a release with this fix?

**Comment by jbpivotal** [comment]
@mastertinner Yes. We're working on that today.
