### ISSUE TITLE
Unable to deploy a simple hello world spring boot aap on CF deployed using bosh

### ISSUE THREAD

**Issue by nishanthmehta** [cloudfoundry/cli#1303]
Trying to deploy a simple hello world application my locally deployed CF instance
Unable to download the java buildpack

## Command  

 `cf push'

## What occurred

Using manifest file /home/ubuntu/workspace/hello-spring-cloud/manifest.yml

Updating app hello-spring-cloud in org mycloud / space dev as admin...
OK

Creating route hello-spring-cloud-unpredicting-sluicegate.bosh-lite.com...
OK

Binding hello-spring-cloud-unpredicting-sluicegate.bosh-lite.com to hello-spring-cloud...
OK

Uploading hello-spring-cloud...
Uploading app files from: /tmp/unzipped-app033693953
Uploading 462.7K, 99 files
Done uploading
OK

Starting app hello-spring-cloud in org mycloud / space dev as admin...
Downloading binary_buildpack...
Downloading go_buildpack...
Downloading python_buildpack...
Downloading nodejs_buildpack...
Downloading php_buildpack...
Downloaded binary_buildpack
Downloading java_buildpack...
Downloaded go_buildpack
Downloading java-buildpack...
Downloaded nodejs_buildpack
Downloading staticfile_buildpack...
Downloaded java_buildpack
Downloading ruby_buildpack...
Downloaded python_buildpack
Downloading dotnet_core_buildpack...
Downloaded php_buildpack
Downloaded staticfile_buildpack
Downloaded ruby_buildpack
Downloaded java-buildpack
Downloaded dotnet_core_buildpack
Creating container
Successfully created container
Downloading app package...
Downloaded app package (30.7M)
[DownloadCache]                  WARN  Unable to download https://java-buildpack.cloudfoundry.org/jvmkill/trusty/x86_64/index.yml into cache /tmp: Failed to open TCP connection to java-buildpack.cloudfoundry.org:443 (getaddrinfo: Name or service not known)
[Buildpack]                      ERROR Detect failed with exception #<RuntimeError: Jvmkill Agent error: Unable to find cached file for https://java-buildpack.cloudfoundry.org/jvmkill/trusty/x86_64/index.yml>
Jvmkill Agent error: Unable to find cached file for https://java-buildpack.cloudfoundry.org/jvmkill/trusty/x86_64/index.yml
[DownloadCache]                  WARN  Unable to download https://java-buildpack.cloudfoundry.org/jvmkill/trusty/x86_64/index.yml into cache /tmp: Failed to open TCP connection to java-buildpack.cloudfoundry.org:443 (getaddrinfo: Name or service not known)
[Buildpack]                      ERROR Detect failed with exception #<RuntimeError: Jvmkill Agent error: Unable to find cached file for https://java-buildpack.cloudfoundry.org/jvmkill/trusty/x86_64/index.yml>
Jvmkill Agent error: Unable to find cached file for https://java-buildpack.cloudfoundry.org/jvmkill/trusty/x86_64/index.yml
None of the buildpacks detected a compatible application
Exit status 222
Stopping instance 5895c511-7732-4eb0-885b-2bbd56f7ca7d
Destroying container
Successfully destroyed container

FAILED

## CLI Version  

cf version 6.33.1+c77e55743.2017-12-15

## CC API Endpoint Version  

api endpoint:   https://api.bosh-lite.com
api version:    2.100.0

## Platform & Shell Details  

Ubuntu 16.04.3 LTS

**Comment by dkoper** [comment]
Hi @nishanthmehta 

The Java Buildpack running in your staging container seems to have an issue resolving a domain name pointing to a Java Buildpack assets site, from which it needs to download a dependencies.
The CLI is just reporting the server side error, so we on the CLI side don't know well what's wrong with it.

@nebhale Do you have any suggestions?

**Comment by nebhale** [comment]
Without knowing much about the system that it's running on, it would appear that you're trying to run the online buildpack in a setting where it cannot make contact with the internet.  If you are in that case, you'll need to use an offline buildpack.

**Comment by jbpivotal** [comment]
Hi @nishanthmehta 
Let us know if you still have an issue. Otherwise, I'm inclined to close this issue.

**Comment by Deekshit51** [comment]
Hi, I am facing the similar issue... in my machine..

1. Deployed cloudfoundry using bosh-lite
2. unable to deploy the apps
3. getting the above jvm tcp error.. 

Can you kindly let me know any resolution ?

**Comment by XenoPhex** [comment]
Without knowing the specifics of your individual machines/how you're deploying these apps we cannot help debug these problems. In general it's not this team's responsibility to debug how apps are deployed, try reaching out to some of the Java teams on the Cloud Foundry slack for more help.
