### ISSUE TITLE
Repo docs link does not reference HTTPS version and docs site does not redirect to HTTPS

### ISSUE THREAD

**Issue by jonathaningram** [cloudfoundry/cli#1306]
I just visited https://github.com/cloudfoundry/cli and directly clicked the repo link which is not the HTTPS version: `http://docs.cloudfoundry.org/cf-cli`.

Also when visiting that link it does not redirect to HTTPS even though a HTTPS version of the docs site exists: https://docs.cloudfoundry.org/cf-cli/

Not sure if there's any reason why HTTPS couldn't or shouldn't be enforced?

**Comment by dkoper** [comment]
I have updated the repo link to use https. Does that address the concern or was there another one?

**Comment by jonathaningram** [comment]
@dkoper thanks. Also http://docs.cloudfoundry.org/cf-cli does not automatically redirect to HTTPS.

```
$ curl -I http://docs.cloudfoundry.org/cf-cli/
HTTP/1.1 200 OK
...
```

Expected something like:

```
$ curl -I http://www.cloudfoundry.org/
HTTP/1.1 301 Moved Permanently
Content-Type: text/html; charset=UTF-8
Location: https://www.cloudfoundry.org/
...
```

**Comment by dkoper** [comment]
Our team has no control over the documentation site and its redirect rules. You could try submitting an issue to https://github.com/cloudfoundry/docs-book-cloudfoundry.

**Comment by jonathaningram** [comment]
Thanks @dkoper - apologies for opening here, I just assumed this repo had control of the site.
