### ISSUE TITLE
Not able to set API endpoint to http://api.run.pivotal.io

### ISSUE THREAD

**Issue by tejasraval** [cloudfoundry/cli#1310]
## Command  
C:\Users\tejas_raval>cf api https://api.run.pivotal.io

Setting api endpoint to https://api.run.pivotal.io...
Request error: Get https://api.run.pivotal.io/v2/info: proxyconnect tcp: dial tcp: lookup proxy.dell.com: no such host
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
FAILED

## What you expected to occur
To set the API value

## CLI Version  
6.34.1+bbdf81482.2018-01-17

## Platform & Shell Details  
Windows 10 64 bit - 1607.14393.2007

## Any other relevant information  
Trying first time my hand to setup CF and login. But not able to set API endpoint to proceed to login. I have tried increasing the CF_DIAL_TIMEOUT=15 but that has not helped. Any suggestions to help resolve this would be great. I am a newbie to Cloud Foundry and Pivotal. I am trying this out on my company laptop that I use for my day to day work.

**Comment by dkoper** [comment]
Without further details, I wonder if you have a proxy configured to `proxy.dell.com` but trying this command while you are not on your corporate network, so the proxy is not accessible.
Please try again while you are on the Dell corporate network that has access to that proxy, or clear your proxy configuration as follows and try again:
```
C:\Users\tejas_raval>set https_proxy=

C:\Users\tejas_raval>set http_proxy=

C:\Users\tejas_raval>cf api https://api.run.pivotal.io
...
```

**Comment by tejasraval** [comment]
Hi dkoper,

I tried what you instructed me. But still I guess its expecting a correct proxy.

C:\WINDOWS\system32>set https_proxy=

C:\WINDOWS\system32>set http_proxy=

C:\WINDOWS\system32>cf api  https://api.run.pivotal.io

Setting api endpoint to https://api.run.pivotal.io...
Request error: Get https://api.run.pivotal.io/v2/info: proxyconnect tcp: dial tcp :0: connectex: The requested address is not valid in its context.
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
FAILED

I guess I need to find out the correct value to get going. If you have got any further ideas would help. Thank you so much.

**Comment by XenoPhex** [comment]
Hi @tejasraval thanks, closing out this issue due to inactivity.
