### ISSUE TITLE
GetServices() ([]plugin_models.GetServices_Model, error) does not return a guid

### ISSUE THREAD

**Issue by Benjamintf1** [cloudfoundry/cli#1312]
## Command  
any plugin command that uses the cli-connection to GetServices()

## What occurred

the GetServices_model has a field "guid" but is never filled in. 

## What you expected to occur
if there is a field on an object like `guid` it should be returned(if such field has a value, which it does).

## CLI Version  

cf version 6.33.1+c77e55743.2017-12-15

## CC API Endpoint Version  

2.100.0

## Platform & Shell Details  

mac osx 1.12.6 siera

**Comment by XenoPhex** [comment]
@Benjamintf1 To confirm, are you seeing the lack of GUID for all types of services? Or does it display the GUID for Managed or User Provided services?

**Comment by Benjamintf1** [comment]
We dont use user provided services, absolutly none of our services are showing guids for getservices(), they shpw when we use getservice(name)

**Comment by nickwei84** [comment]
@Benjamintf1 We may have fixed the issue. Can you please confirm with the latest edge build from here:
https://github.com/cloudfoundry/cli#edge-binaries

**Comment by Benjamintf1** [comment]
confirmed
