### ISSUE TITLE
LICENSE has placeholder values for copyright year and owner

### ISSUE THREAD

**Issue by pivotal-dk** [cloudfoundry/cli#1313]
## Command  

N/A

## What occurred

LICENSE has placeholder line with contents

```
Copyright [yyyy] [name of copyright owner]
```

## What you expected to occur
LICENSE should contain information about the copyright owner and year (as in NOTICE).
## CLI Version  
N/A

## CC API Endpoint Version  
N/A

## CF Trace
N/A

## Platform & Shell Details  
N/A

## Any other relevant information  
N/A

**Comment by dkoper** [comment]
I assume you're referring to [`Copyright [yyyy] [name of copyright owner]`](https://github.com/cloudfoundry/cli/blob/255fcaf396c770b845fbda97c66ea24aebcbdbf7/LICENSE#L190)?

This section of the LICENSE file is not part of the terms and conditions, and is part of an appendix referred to from [the definition of `work`](https://github.com/cloudfoundry/cli/blob/master/LICENSE#L39) as an example of a copyright notice to attach or include in this work. The Cloud Foundry Foundation (@christopherclark) however, has prescribed [this format](https://github.com/cloudfoundry/cli/blob/master/NOTICE) to describe the copyright notice (which is equivalent to how many Apache Foundation projects do it).

**Comment by pivotal-dk** [comment]
Ah, I see. In that case, I will assume this issue is safe to close.
