### ISSUE TITLE
bind-route-service fails with "411" error from Akamai as content-type set but no content-length

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/cli#1318]
## Command  

cf bind-route-service stage0.mybluemix.net mylogger --hostname ae-spring-music-refreshful-advisableness

## What occurred

The error occurs if you have (as we do) a system validating the request (Akamai) as this is sent back with a "411" which means no content length.

## What you expected to occur

No error to occur as the request would have valid information

## CLI Version  

cf version 6.33.1+c77e55743.2017-12-15
But also still exists in MASTER branch as I tested with the latest code from github

## CC API Endpoint Version  

 2.92.0

## CF Trace

```
REQUEST: [2018-02-01T14:29:19+01:00]
PUT /v2/user_provided_service_instances/3f64eaf8-f6f2-4d06-8277-cfea98d6fa17/routes/2ad90452-0a61-465b-8d0d-00074809aecf HTTP/1.1
Host: api.stage0.ng.bluemix.net
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.33.1+c77e55743.2017-12-15 / darwin



RESPONSE: [2018-02-01T14:29:20+01:00]
HTTP/1.1 411 Length Required
Connection: close
Content-Length: 222
Cache-Control: max-age=0, no-cache, no-store
Content-Type: text/html
Date: Thu, 01 Feb 2018 13:29:20 GMT
Expires: Thu, 01 Feb 2018 13:29:20 GMT
Mime-Version: 1.0
Pragma: no-cache
Server: AkamaiGHost

<HTML><HEAD>
<TITLE>Bad Request</TITLE>
</HEAD><BODY>
<H1>Bad Request</H1>
Your browser sent a request that this server could not understand.<P>
Reference&#32;&#35;7&#46;b7921602&#46;1517491760&#46;3a3a69d
</BODY>
</HTML>

FAILED
Server error, status code: 411, error code: 0, message:
```

## Platform & Shell Details  

MACOS but failed on also Linux

## Any other relevant information  

We have Akamai between the user and the endpoint which will validate requests and enforce https:

So I looked into this and found the issue occurs because the CLI is setting content-type to be application/json but in this request the body is empty and since it is empty the ContentLength is not sent.

I found several ways to fix this.   
1) https://github.com/cloudfoundry/cli/blob/master/cf/api/route_service_binding_repository.go#L55
This is setting an empty string.  If you set "{}" instead (which is valid JSON) and would then cause the content-length to be set to 2 then this solves the problem.

2) https://github.com/cloudfoundry/cli/blob/master/cf/net/gateway.go#L202
This is ALWAYS setting the content-type to "application/json" but if we have an empty body we should not set the content-type.  But this needs to be matched with a change in 1) to set the rs = nil instead of sending a dummy empty string.

I think some of this is due to the fact that the http code will also not set the ContentLength = 0 as this is not quite right since it means "unknown".

This only occurs it seems on "PUT" (and possibly) "POST" requests.   Can you validate other requests which might send an empty body on a PUT or a POST.

This occurs when we tested the "sample" creation of route-services in the CF documentation where there are NO parameters in the route-service.   We can get around it also by sending -c "{}" on the CLI which in fact sends parameters but empty ones.

**Comment by abbyachau** [comment]
Hi @andrew-edgar thanks for creating this. @jberkhahn created this [pull request](https://github.com/cloudfoundry/cli/pull/1404) to fix this issue however after speaking to him and a few other folks from IBM, we've decided to close the pull request until further notice. Given we've closed the pull request, I'm going to close this issue. I've tagged you on the pull request so that you can track if we decide to resuscitate the pull request. Please do not hesitate to reach out if you have any feedback, questions, or prefer this issue to remain open. Thanks again.
