### ISSUE TITLE
Existing routes with custom hosts ignored on push

### ISSUE THREAD

**Issue by nebhale** [cloudfoundry/cli#1321]
Given an existing application that has a single route that uses a custom host, subsequent pushes of the same application, ignore the existing route and attempt to bind the "default" (based on application name) route.  So for example:

```
$ cf push test-application -n alternate-test-application
$ cf push test-application
```

In the least offensive result, this will result in two routes (`alternate-test-application.domain` and `test-application.domain`) bound to the application, when that was not desired.  In the most offensive result, the "default" route is occupied by another application and the second `push` fails.  Previously (say three months ago, but I'm not sure about specific versions), the result was a single bound route (`alternate-test-application.domain`) in all cases.  I've noticed this for the last couple of releases, but specifically on `cf version 6.34.1+bbdf81482.2018-01-17` today.

**Comment by nickwei84** [comment]
Hi @nebhale, thanks for catching this. This is a regression from previous push behavior. Our PM is currently out of the office. Is this urgent or can it wait until our PM is back for prioritization?

**Comment by nebhale** [comment]
I'm living with it for now, but it's annoying.  Next release would be great, but I don't have any urgent need for when the next release is.

**Comment by jbpivotal** [comment]
Closing as accepted.
