### ISSUE TITLE
cf push -n allows underscores in hostnames

### ISSUE THREAD

**Issue by edshee** [cloudfoundry/cli#1326]
## Command

`cf push -n host_with_underscore`

## What occurred

Creates route with underscores in it and then route can't be reached because the router doesn't support underscores. 

## What you expected to occur

Either an error or a warning and the CLI to automatically change underscores `_` to dashes `-`. (It does this already if you do `cf push name_with_underscores`).

## CLI Version  

6.32.0+0191c33d9.2017-09-26
(also tested with other versions and still happens)

## CC API Endpoint Version  

2.92.0

## Platform & Shell Details  

Same behaviour on multiple OS

## Any other relevant information  

I suspect this will need to be fixed in the cloud controller and/or router but I'm raising an issue on the CLI as it's probably the easiest quick fix.

**Comment by edshee** [comment]
@arlemi

**Comment by jbpivotal** [comment]
Closing as wontfix.
