### ISSUE TITLE
cf curl on Bash for Windows returns an error

### ISSUE THREAD

**Issue by abh1kg** [cloudfoundry/cli#1330]
## Command  
`cf curl "/v2/service_instances/<service_instance_id>"`

## What occurred
```
GET /C:/Program%20Files/Git/v2/service_instances/5c6b56d4-53d6-4130-9a4e-f57fb9f7f718 HTTP/1.1
Host: api.cf.mydomain.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.34.1+bbdf81482.2018-01-17 / windows



RESPONSE: [2018-02-19T06:09:42+05:30]
HTTP/1.1 404 Not Found
Connection: close
Content-Length: 86
Content-Type: application/json;charset=utf-8
Date: Mon, 19 Feb 2018 00:39:42 GMT
Server: nginx
X-Cascade: pass
X-Content-Type-Options: nosniff
X-Ratelimit-Limit: 40000
X-Ratelimit-Remaining: 39978
X-Ratelimit-Reset: 1519004009
X-Vcap-Request-Id: afee2a4c-5f13-4f86-466b-944bc3fb6450::04c6b221-21fe-43a5-ae88-75287c890541

{
  "description": "Unknown request",
  "error_code": "CF-NotFound",
  "code": 10000
}
```

## What you expected to occur
I would expect the `cf curl` to work smoothly on Bash on Windows.

## CLI Version  
```
 cf -v
cf.exe version 6.34.1+bbdf81482.2018-01-17
```

## CC API Endpoint Version  
api version:    2.101.0

## CF Trace
See above

## Platform & Shell Details  
Windows 10, with Bash Shell for Windows

## Any other relevant information  
As can be seen in the `cf curl` debug output, the CLI wrongly sends the CC request to a path, which contains the filesystem path prefixed.

**Comment by vitreuz** [comment]
Hey @abh1kg ,

We don't currently have support WSL namely because go doesn't support WSL. We'll keep this issue open, should golang's support change. Our current supported terminals on Windows are command prompt and Powershell.

**Comment by jbpivotal** [comment]
Closing as the CF CLI doesn't support this.
