### ISSUE TITLE
Push fails because of random route length

### ISSUE THREAD

**Issue by elgohr** [cloudfoundry/cli#1331]
## Command  

cf push the-over-40-character-very-long-app-name --random-route

## What occurred

In https://github.com/cloudfoundry/cloud_controller_ng/issues/581 a limited length of the app-name was introduced.
Our app-name has 43 characters. The app uses the random-route feature.
In this way the route _can_ become longer than the limit of 63 characters.

This results in
`Server error, status code: 400, error code: 210001, message: The route is invalid: host must be no more than 63 characters`

## What you expected to occur

CF push must be reproducible.

### Possible fix
a) Use shorter suffix names in case of longer app-names.
b) Define a max-length for app-names, so they don't conflict with random-routes. (Didn't see documentation which defines the max-length of the suffix).

## CLI Version  

6.34.1+bbdf81482.2018-01-17

## CC API Endpoint Version  

2.102.0

## Platform & Shell Details  

Linux (Bash)

## Any other relevant information  

Original issue https://github.com/cloudfoundry/cloud_controller_ng/issues/1098

**Comment by jbpivotal** [comment]
Hi, @elgohr . Can you give me more background on why you want app names over 40 characters plus a random route? Why would shortening app names not work?

**Comment by elgohr** [comment]
We have many Java apps. In this way developers tend to be super expressive (at least there are no factories ;-)).
We're using random routes because we also have a service registry and don't need a fixed one.
It would totally work. What's the max length of the suffix? How short do they have to be?

**Comment by jbpivotal** [comment]
@elgohr According to my math, the longest app name is 34 characters, assuming:
- a max combined hostname length of 63 characters for app name and random route
- random route value 1 is up to 12 characters ("appreciative")
- random route value 2 is up to 14 characters ("tasmaniandevil")
- 2 dashes (between app and rr value 1 plus rr value 1 and value 2)

**Comment by elgohr** [comment]
@jbpivotal if this is known, it would be good to check it in the client, before pushing.

**Comment by elgohr** [comment]
I mean today the longest values are 12 and 14. As a user I would not like to check every value in this list on every update.
Furthermore the length is not constantly 12 and 14. In this way the push might work sometimes, sometimes it doesn't.

**Comment by elgohr** [comment]
Ping

**Comment by abbyachau** [comment]
Hey @elgohr thanks again for reaching out and thanks for the ping - apologies it's taken so long to respond. We don't have current plans to prioritise this work in the near future - wondered if you've found a suitable workaround with the information provided to you above.

**Comment by elgohr** [comment]
Hi @abbyachau , the solution was: don't use it and do it yourself

**Comment by abbyachau** [comment]
Hey @elgohr sorry we didn't provide a solution but great to hear you were able to provide one internally. We can leave this issue open to see if it garners any other reactions but unfortunately we are unlikely able to prioritise the work in the near future. Here is a [comment](https://github.com/cloudfoundry/cli/issues/1503#issuecomment-441813110) to give you information on our current priorities.

**Comment by abbyachau** [comment]
Hi @elgohr thanks again for creating this issue. Please see the link issue #1360 above. We've received community feedback that there is increasing name collision whilst pushing with `--random-route` and will likely be moving forward with a fix,  to extend the random name that we generate. As mentioned in the issue, we are also looking at a more future-proof solution. We wanted to give you a heads up about related but separate issues in case it affects your workflows. Please reach out if you have any questions.

**Comment by abbyachau** [comment]
Hi again @elgohr, we decided to go with a different solution for [#1360](https://github.com/cloudfoundry/cli/issues/1360), one where we just changed the app name instead of adding an additional word to `--random-route`. 

However, given our current workload, we don't have any immediate plans to delve into your use case. It sounds like you have a workaround so I'm going to close this issue. Please do not hesitate to get in touch if you have any questions/feedback.

**Comment by elgohr** [comment]
Sorry, I don't get why bugs go away with workarounds. It's called workaround, not fix

**Comment by abbyachau** [comment]
Hi @elgohr sorry we couldn't help here, it's more of a priority issue - we unfortunately have a fairly large workload and so cannot help even where we would like to. Please do not hesitate to reach out to us again though. Best.
