### ISSUE TITLE
cf push should use a .env file when present

### ISSUE THREAD

**Issue by sr229** [cloudfoundry/cli#1332]
Using .env file for config variables specific for an app is a more convenient way while still maintaining security (assuming the developer ignores the .env file during commit to a public repository)

So it would be nice if : 

- cf push would be able to read a .env file if present, and set variables on deploy.

**Comment by jbpivotal** [comment]
@sr229 Looks like a duplicate of https://github.com/cloudfoundry/cli/issues/1012, which is still open.  If similar enough, please add any additional comments there. That story is not currently prioritized.
