### ISSUE TITLE
Web action flag not working on CLI 0.6.5

### ISSUE THREAD

**Issue by hanxue** [cloudfoundry/cli#1337]
## Command  
```
$ bx wsk action udpate my_action --web yes
Error: unknown flag: --web
unknown flag: --web
```

## What you expected to occur
Web action should be enabled  for `my_action`

## CLI Version  

Bluemix CLI: 0.6.5
cf version 6.32.0+0191c33d9.2017-09-26

## CC API Endpoint Version  

CC API version:                2.92.0   
API endpoint: https://api.ng.bluemix.net (CF API version: 2.92.0)

## CF Trace

N/A

## Platform & Shell Details  

MacOS 10.10, bash

**Comment by XenoPhex** [comment]
@hanxue we don't control the `bx` CLI, only the `cf` cli. Please contact IBM for more help.

**Comment by XenoPhex** [comment]
Closing since the `bx` CLI is not owned by this team.
