### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by DevasiaThomas** [cloudfoundry/cli#1338]
For any CF CLI command (cf create-service, etc) that takes a json message can you have it accept yaml files too (it's neater to maintain) and convert them to json internally? 

Thanks

**Comment by jbpivotal** [comment]
@DevasiaThomas Can you help me better understand what problem this feature would solve?

**Comment by DevasiaThomas** [comment]
So when I am creating a service instance or binding one and there are a huge number of parameters that are required - Maintaining a huge json file is problematic. Moreover, I can provide a prebuilt YAML file to customers/users for them to customize, based on the comments I have in the YAML file.. something one cannot do with json files.

**Comment by gururajsh** [comment]
Hi @DevasiaThomas ,

At this time, we will not be able to pursue this. If this issue is still relevant, please open a new GH Issue.
