### ISSUE TITLE
Cannot delete a service instance if shared

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cli#1341]
## Command  

```
$ cf ds shared-kafka -f
Deleting service shared-kafka in org system / space dev as admin...
FAILED
Server error, status code: 422, error code: 390002, message: Service instances must be unshared before they can be deleted. Unsharing shared-kafka will automatically delete any bindings that have been made to applications in other spaces.
```

I also cannot just unshare the service:

```
$ cf unshare-service shared-kafka
Incorrect Usage: the required flag `-s' was not specified
```

## What occurred

I have shared a service instance with another space. Or a hundred spaces. Across many orgs. I'd now like to delete that service instance. I'd expect `cf ds shared-kafka -f` to do this; but it fails, instead complaining I must first unshare the service instance.

And `cf unshare-service` doesn't work without explicitly iterating across all space/org combinations.

So you have to run `cf unshare-service` for all the permutations; but the CLI doesn't have a way to find all the places you've shared the service afaict.

```
$ cf help -a | grep share
   create-shared-domain                   Create a domain that can be used by all orgs (admin-only)
   delete-shared-domain                   Delete a shared domain
   share-private-domain                   Share a private domain with an org
   unshare-private-domain                 Unshare a private domain with an org
   share-service                      Share a service instance with another space
   unshare-service                    Unshare a shared service instance from a space
```

**Comment by jbpivotal** [comment]
@drnic You can see where a service is shared in the updated output of the `service` command. Example:
```
$ cf service sharing-service1
D:\Users\koperd\Downloads\bin>cf service service1
Showing info of service service1 in org org1 / space dev as admin...

name:            sharing-service1
service:         postgres
bound apps:      myapp
tags:
plan:            small
description:     Dummy addon that is cool
documentation:
dashboard:

shared with spaces:
org    space     bindings
org2   space2    2
org3   spaceB    1
...

Showing status of last operation from service service1...

status:    create succeeded
```

**Comment by Samze** [comment]
@drnic This is desired behaviour. We wanted users to explicitly unshare a service instance before they delete it. This was to avoid a user unknowingly deleting a shared service instance and removing the application bindings. This is the same behaviour for when you try to delete a service that has existing same-space bindings.

As @jbpivotal mentioned, you can use `cf service` to discover locations of share and then you can unshare the service by passing the space name to the command.

e.g.

```
$ cf service sharing-service1
Showing info of service service1 in org org1 / space dev as admin...

name:            sharing-service1
service:         postgres
bound apps:      myapp
tags:
plan:            small
description:     Dummy addon that is cool
documentation:
dashboard:

shared with spaces:
org    space     bindings
org2   space2    2
...

Showing status of last operation from service service1...

status:    create succeeded
$ cf unshare-service sharing-service1 -s space2
OK
```

**Comment by rboykin** [comment]
Does the ?recursive=true query parameter when deleting a service instance also delete shared service instances and their bindings/keys similarly to how it deletes related service bindings/keys?

**Comment by Samze** [comment]
@rboykin Not at the moment. As share & unshare were added as experimental features to the CC v3 API we did not follow the V2 pattern to support the `recursive` query parameter. This may be something we support in the future though.

**Comment by drnic** [comment]
Thanks for answers!
