### ISSUE TITLE
cf services broken in 6.3.5

### ISSUE THREAD

**Issue by choffm** [cloudfoundry/cli#1342]
Hello,

with 6.3.5, the command `cf services` is broken.

## Command  

Execute `cf s` or `cf services` 

## What occurred
```
 ❯ cf s                                                                                                                                                                                                   [18:12:07]
Getting services in org *** / space *** as ***...

Invalid JSON content from server: unexpected end of JSON input
FAILED
>>> elapsed time 21s
```

## What you expected to occur

A list of CF backing services.

## CLI Version  

Command is broken on:

`6.35.0+5c7de3e32.2018-03-08`on MacOS High Sierra and Ubuntu 16.04

But works still fine with:
`6.34.1+bbdf81482.2018-01-17` on Ubuntu 16.04 

## CC API Endpoint Version  

`api version:    2.101.0`

## Platform & Shell Details  

Platform 1: Mac OS X 10.13.2, iTerm2 3.1.5
Platform 2: Ubuntu 16.04 64-bit with gnome-terminal

**Comment by jbpivotal** [comment]
@choffm Thanks for reporting this issue. It looks identical to [this bug](https://www.pivotaltracker.com/story/show/155925336) we're working on now. We're aiming to have a patch release today or tomorrow.

**Comment by jbpivotal** [comment]
@choffm We fixed this issue in today's release, 6.35.1. Let us know if you have any issues.

**Comment by abdallahokasha** [comment]
CF version  was upgraded from `version 6.42` to `cf version 6.43.0+815ea2f3d.2019-02-20`

I'd a problem when i try to run `cf push My_container_Name` using Ubuntu 18.04

The ERROR was:
```
Invalid JSON content from server: invalid character '<' looking for beginning of value
FAILED
```

The solution was to delete the `config.json` as follows:
`cd ~/.cf` and run `ls` we can see `config.json` file
Now, run `rm -rf config.json`

If we try to run cf push now it should work, but we need to login again using `cf login`

[Here](https://docs.cloudfoundry.org/cf-cli/getting-started.html "https://docs.cloudfoundry.org/cf-cli/getting-started.html") is the guide for `config.json` default directory.

**Comment by ivyxiao123** [comment]
I'm still having same issue with version 7.2.0+be4a5ce2b.2020-12-10 when using cf login, tried to remove the `config.json` as mentioned by abdallahokasha, but didn't help
`cf login -a https://test.com -u xxxx -p xxxx -o xxxx -s xxxx --skip-ssl-validation
API endpoint: https://test.com
Invalid JSON content from server: invalid character '<' looking for beginning of value
FAILED
`
Any idea how to fix it?
