### ISSUE TITLE
Not able to Login with CF-CLi version 6.35

### ISSUE THREAD

**Issue by jprateekvmware** [cloudfoundry/cli#1345]
cf version 6.35.1+bfbe5f0e8.2018-03-14

Hi All,
While trying to login to PCF version 1.12 with the above CLI version its throwing below error
Not logged in. Use 'cf login' to log in.
FAILED
Error performing request: Get https://login.us07-5-pcf444-apps.test.mydomain.com/login: tls: failed to parse certificate from server: x509: cannot parse dnsName "*. us07-5-pcf444-apps.test.mydomain.com"   working fine with the lower version of cf-cli.

**Comment by XenoPhex** [comment]
Hey there @jprateekvmware,

CF 6.35 upgraded to GoLang 1.10. As part of this update the [x509 package was updated](https://golang.org/doc/go1.10#crypto/x509) with the following:

> `Certificate.Verify` now enforces the name constraints for all names contained in the certificate, not just the one name that a client has asked about. Extended key usage restrictions are similarly now checked all at once.

Can you confirm if your certificates for your Load Balancer are setup correctly?

**Comment by XenoPhex** [comment]
After poking around a bit, we believe this is a certificate issue as the error that's being returned is deep inside the GoLang SSL libraries and is high-lighting that there's an extra space in your dnsName: `"*. us07-5-pcf444-apps.test.mydomain.com"`. 

Your certificate needs to be updated with a valid DNS Name and then you need to update your CF instance with the fixed certificate.

Let us know if this appears to be the issue, otherwise we're going to need more information to help.

**Comment by jprateekvmware** [comment]
Thanks Anand, we would have the certificate validated for the space issue and let you know how it goes post fixing it.

**Comment by XenoPhex** [comment]
This utility might help: https://github.com/square/certigo

**Comment by foxg** [comment]
Hi all,

I updated the cert, and it seems to be working fine on Linux and Windows, but not on OSX (Sierra).

The cert is signed by our internal CA, and the root cert is in the trust store of all 3 OSes. I can connect to cf via the browser without any errors. It just seems to be OSX shell clients that can't validate the certificate chain (I tried with both certigo and cf). This happens for me an for a colleague, so I don't think it's specific to me.

I'll see if I can track down a High Sierra box to test from.

Cheers,

Greg

**Comment by jantonacci** [comment]
No changes observed, still seeing original failure message as captured by jprateekvmware.

**Comment by XenoPhex** [comment]
@foxg @jantonacci Are you all following the [official documentation on how to install custom certs locally](https://docs.cloudfoundry.org/cf-cli/self-signed.html) or are you setting them up in a different way?

**Comment by XenoPhex** [comment]
We believe a lot of these issues came in with the upgrade to GoLang 1.10.0. CF CLI 6.36.* upgraded to GoLang 1.10.1 [which fixed some issues around certificate validation](https://github.com/golang/go/issues?q=milestone%3AGo1.10.1). If people are still seeing issues after upgrade to 6.36+, please feel free to reopen or file a new issue.

**Comment by jantonacci** [comment]
@XenoPhex , I am using cf option '--skip-ssl-validation' from Windows or Linux (no OSX).  Appears this is resolved now.  Many thanks!
