### ISSUE TITLE
Bluemix push through cf failing!

### ISSUE THREAD

**Issue by soul-coder** [cloudfoundry/cli#1350]
## Command 
bluemix app push ForBluepoints

## What occurred
C:\treasurebox>bluemix app push ForBluepoints
Invoking 'cf push ForBluepoints'...

FAILED
fork/exec C:\Program Files\IBM\Bluemix\bin\cfcli\cf.exe: %1 is not a valid Win32 application.

## What you expected to occur
The same command was working till 2 days ago and it was pushing my application to bluemix Cloud foundry app.
## CLI Version  
cf version 6.27.0+d26b32d.2017-06-08

## CC API Endpoint Version  

api version:    2.75.0

## Platform & Shell Details  

Windows 7 Professional 64-bit 

## Any other relevant information  

size of C:\Program Files\IBM\Bluemix\bin\cfcli\cf.exe became zero after an update

**Comment by XenoPhex** [comment]
@soul-coder There are several issues that I perceive from your ticket:
1. You are running on **64 bit** windows, but the error claims you're running the a **32 bit** binary, so you probably downloaded the wrong binary of the CF CLI. Make sure you get the correct binary for your architecture.
1. The version of the CF CLI you are using is *significantly* out of date, can you try updating the the [latest](https://github.com/cloudfoundry/cli/releases) version. The CF CLI is fully backwards compatible to CAPI `2.29.0`, so always being on the latest version will usually fix most people's issues.
1. If the size of the CF CLI is `0`, whatever update you ran probably failed. Not sure how you updated, let us know if it was though the [official installers](https://github.com/cloudfoundry/cli#downloads). All other update mechanisms are owned by other people and we don't have control over them.
1. This team is not responsible for **anything** Bluemix related, please reach out to the Bluemix support team for help prior to contacting this team. If you're paying for Bluemix, you're already paying for their support, so you don't want that to go to waste!

**Comment by jbpivotal** [comment]
@soul-coder I'm closing this issue as wont-fix. After you take the steps recommended by @XenoPhex, letus know if you have any more information that would suggest re-opening the issue.
