### ISSUE TITLE
cf s command very slow since 6.35

### ISSUE THREAD

**Issue by choffm** [cloudfoundry/cli#1353]
Hello,
the `cf s` command is much slower in version 6.35.2, compared to 6.34.1.

## Command  

`cf s`

## What occurred

With version 6.34.1: `cf s  0.18s user 0.04s system 4% cpu 4.647 total`
With version 6.35.2: `cf s  0.26s user 0.10s system 1% cpu 30.341 total`

## CLI Version  

cf version 6.34.1+bbdf81482.2018-01-17
cf version 6.35.2+88a03e995.2018-03-15

## CC API Endpoint Version  

`api version:    2.101.0`

## Platform & Shell Details  

MacOS 10.13.3 (also occured on Windows 10 x64) 

## Any other relevant information  

Also occurred with CF CLI version 6.35.0, however the command resulted in an error message (see https://github.com/cloudfoundry/cli/issues/1342).

**Comment by XenoPhex** [comment]
Yup! In CF 6.35.0, the CF CLI switched from using a single `/spaces/summary` API call to individual `/service`, `/service_instance`, etc. API calls. Due to the increased number of API calls, the `services` request is much slower.

Why did it switch? The `/services/summary` API call breaks when there are more than 50 services or apps. Additionally, the break returns back a successful status code, so the CLI can't tell the difference between 51+ services/apps and 0 services/apps. So it would appear that all your services are gone!

There might be a way to cache some of these requests if they happen to be looking up duplicate objects, but overall the speed increase may be negligible.

**Comment by abbyachau** [comment]
Hi @choffm thanks for creating this issue. We are closing this issue but please do not hesitate to reach out if this issue becomes too problematic. Thanks.

**Comment by abbyachau** [comment]
Reopening because we've received feedback that this command was actually returning the correct number of services/apps if there are more than 50. And the change we made introduced higher latency.

**Comment by choffm** [comment]
Hi,

as @abbyachau  stated, the change which slowed down the `cf s` command wasn't even necessary, but it is a real pain for people who use the cli on a daily basis. In some of my spaces, it takes up to 90 seconds for the command to return the list of services.

Can you please revert the changes or provide another fix for the performance degradation?

Thanks

**Comment by laurzca** [comment]
Hi @choffm thanks for your note! For now, we're planning to fix this (and  `cf m` which can also become quite slow) in V3 of the API and not V2.

**Comment by laurzca** [comment]
Following up on this - we've decided to take a look at how much effort would be required to improve the performance for `cf s` in V2. We'll update with what we find.

**Comment by youngm** [comment]
We have noticed this recently as well.  Cannot track it to a particular cli change or CF upgrade.  But we did notice that `cf s` is significantly slower for non admins when compared with users who are `cloud_controller.admin`s.

**Comment by abbyachau** [comment]
@tcdowney @ssisil @mkenyon  for reference (CLI will be discussing implications of moving away from the summary endpoint)

**Comment by AartiKriplani** [comment]
@abbyachau : We've [currently working on ](https://www.pivotaltracker.com/story/show/163052467https://www.pivotaltracker.com/story/show/163052467) re-introducing the use of summary endpoint to speed up the `cf s` command
cc: @laurzca

**Comment by henryaj** [comment]
I'll close this out for now. :)

**Comment by Kiemes** [comment]
Are you planning to release this soon?

**Comment by abbyachau** [comment]
Hi @Kiemes this is slated for the next release which we hope to release soon.
