### ISSUE TITLE
Add option to wait for async operation completion until timeout

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#1354]
## Command  

cf create-service, cf delete-service, soon cf bind-service cf unbind-service

## What occurred

Currently, when the underlying broker supports [async operations](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#asynchronous-operations), the command returns with an "operation in progress" message.

Users/scripts/[tests](https://github.com/cloudfoundry/cf-acceptance-tests/blob/94b167988bb2666edbaef3c8364225de54e336d8/services/service_instance_lifecycle.go#L322-L327) have to repeatedly poll for completion of the operation using the status command such as `cf-service`. 

## What you expected to occur

Add an option to the CLI command such as ``--poll-until timeoutInSeconds`` that would periodically poll the status of the async command, and return until the command completes or the specified timeout (in seconds) triggers

## CLI Version  

cf version 6.35.2+88a03e995.2018-03-15

**Comment by XenoPhex** [comment]
Hey @gberche-orange, I believe there's a separate team on CF handling the work around this and will be providing the CF CLI team a pull request/cross-team with changes for the new broker features.

/cc @matthewmcnew for comment?

**Comment by gberche-orange** [comment]
@XenoPhex are you referring to the [services API ](https://www.cloudfoundry.org/projects/) team (part of application runtime PMC) run by  @mattmcneeney ?

**Comment by mattmcneeney** [comment]
The Services API team are dealing with adding support for asynchronous bindings, but this is the first time we've heard about this CLI UX request.

@gberche-orange - can the tests/scripts you talk about just ask for synchronous bindings only using the CF API?

**Comment by gberche-orange** [comment]
> can the tests/scripts you talk about just ask for synchronous bindings only using the CF API?

@mattmcneeney seems difficult:

Parts of these tests such (e.g. [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests/blob/94b167988bb2666edbaef3c8364225de54e336d8/services/service_instance_lifecycle.go#L322-L327))  exercise the user paths using the CF CLI which does not yet support setting the [accepts_incomplete=false](http://apidocs.cloudfoundry.org/1.29.0/service_instances/creating_a_service_instance.html) flag in the CC API. 

Also, I guess the CC max service provisionning timeout would be often hit by service brokers that have specifically opted for async response to work around this.

**Comment by mattmcneeney** [comment]
That makes sense. Are there any commands not related to services that this would benefit? Looping in @abbyachau as this sounds like a more cross-cutting CLI issue

**Comment by gberche-orange** [comment]
@abbyachau thanks for the update. This github issue is rather suggesting a opt-in option to provide a  synchronous UX hiding async operations, similar to the `Solution 3: The bind service command blocks until the binding has been created` in the [CLI Design: Supporting Asynchronous Bindings](https://docs.google.com/document/d/1nFnfIs-PT5HQHuyx8_rre_KgxS8AXcMfpP0daHSvOIc/edit?ts=5b102d19#) document

**Comment by Samze** [comment]
*Taking my CC developer hat off and putting my App developer hat on*. 

A wait mechanism is a feature I would love to see. It would stop us having to write scripts like [this](https://github.com/Samze/services-demo-basel-2018/blob/master/scripts/setup-cf.sh#L3-L6).

The Services on K8s `svcat` tool has something similar e.g:

`svcat unbind --name vision-binding --wait`

**Comment by gberche-orange** [comment]
Related issue https://github.com/cloudfoundry/cli/issues/976 was closed after long thread for CAPI response inactivity

**Comment by TonyK59** [comment]
We have an issue right now where a wait command/option would be great. As it stands the script bogs down working on 40 instances (ya, the app is that large) the cf delete command fails to run and then we are left with a mess to clean up. 

At this time before we can allow the app to deploy, we have to manually delete the old and stopped version of our application in a blue/green deployment. 

Is there an ETA for a wait feature to be added?

**Comment by XenoPhex** [comment]
@TonyK59 from what I've gathered (and it's been a while since I talked to some of these folks) it's unlikely that this feature will be implemented in the CCV2/CF6 time frame. The non-critical V2 API and V6 CLI are not as high of a priority as transitioning the V7 CLI to a fully V3 backed API.

_BUT_ there is hope. Because the V3 API / V7 CLI is still in flux, I'd recommend reaching out to the VAT team / providing feedback to them around the services work so that they might be able to incorporate this change into the new V3 API / V7 CLI.

In the V2/CF6 world, this would require a bunch of retooling that I don't believe would be prioritized any time soon; in the V3/CF7 world, depending on how it's planned out, it _might_ be prioritized within the transition effort. Although this depends on if the VAT / Services API team has planned/completed this work yet. So the sooner you reach out the better!

**Comment by FelisiaM** [comment]
Hi all, 

Apologies for getting back to this story to late.
With the implementation of v3 API we have introduced jobs that related to every async operation. This made it possible to have a reliable way to follow operations in the CLI.

With the new major release of the CLI (that should be available soon), you should be able to specify `--wait` flag to wait for the completion of an operation.This is implemented for `cf create-service`,  `cf update-service`,  `cf delete-service` and `cf bind-route-service` and `cf unbind-route-service` as well.

You can follow the next set of stories relating [bind-service]( https://www.pivotaltracker.com/story/show/175334831) and [unbind-service](https://www.pivotaltracker.com/story/show/175356884)

We look forward to feedback on these commands once they are available.

Thanks,
Felisia

**Comment by gberche-orange** [comment]
thanks @FelisiaM , I'm looking forward to test the new --wait option !

ps: testing with the [latest edge binaries](https://github.com/cloudfoundry/cli/wiki/V7-CLI-Installation-Guide#edge-binaries) I can't yet see the the `--wait` flag.

```
./cf7 -v
cf7 version 7.1.0+524581c07.2020-10-22
./cf7 cs --help | grep -i wait
```

**Comment by kirederik** [comment]
@gberche-orange The `--wait` will be available only for the cli v8 (given that a bump in the minimum required version of CAPI is considered a breaking change in the CLI). 

We hope to get a beta for it soon (or you can build it from the master branch for the time being :)).
