### ISSUE TITLE
cf auth with credentials from env vars

### ISSUE THREAD

**Issue by cobyrne-pivot** [cloudfoundry/cli#1358]
## Command  

`cf auth`

## What it supports

`cf auth user password`

## What I'd like

`CF_USERNAME=user CF_PASSWORD=password cf auth`

or maybe

`CF_USERNAME=user CF_PASSWORD=password cf auth --from-env`

## Why

I'm doing this whole continuous integration thing, using this cool Concourse tool, and trying to push my app to CF (in this case PWS).

At the start of my scripts I generally do a "set -x" so I can see what commands concourse is running, which is often necessary for productive debugging.

Unfortunately, this means my `cf auth $CF_USERNAME $CF_PASSWORD` call (right before my `cf push` call) prints my password in plain text. It would be great if I could have the cf cli read the username and password from the environment, instead of having to pass them as arguments.

For now I'll probably `set +x` around my auth call, but it would be nice to have real support for this.

Thanks!

**Comment by abbyachau** [comment]
Hi @cobyrne-pivot thanks for creating this enhancement request, which is in CF CLI release [`v.6.37.0`](https://github.com/cloudfoundry/cli/releases/tag/v6.37.0). Please do not hesitate to reach out with feedback by creating a new issue.
