### ISSUE TITLE
X-Cf-Warnings not being unescaped when presented to user

### ISSUE THREAD

**Issue by jenspinney** [cloudfoundry/cli#1361]
## Problem summary  

It seems that there are two code paths for processings the `X-Cf-Warnings` HTTP header from the cloud controller, and only one of them is correctly unescaping the value of that header.

Code path 1 (unescaping):
https://github.com/cloudfoundry/cli/blob/4961689f6d1d9fa9388664e611459002d8fcbba9/cf/net/gateway.go#L437-L442

Code path 2 (missing the unescaping):
https://github.com/cloudfoundry/cli/blob/4961689f6d1d9fa9388664e611459002d8fcbba9/api/cloudcontroller/cloud_controller_connection.go#L88-L94

We're working on [a story](https://www.pivotaltracker.com/story/show/154667172) to display warnings to a user when they try to bind a user provided service instance and provide paramters. It seems the `cf bind-service` code is using code path 2, which I believe is the refactored/new code area for CLI if I'm reading the git history correctly.

The problem is that if we add `X-Cf-Warnings: this+is+a+warning` (all warnings from the CC are escaped like this), it's being displayed to the user as "this+is+a+warning".

I've tried to find a repro case with warnings that exist today and do this, but a lot of the v2 warnings are very difficult to reproduce. The only warning from v2 I could easily cause was to create a user provided service instance as a route service, after having turned off route services at the bosh manifest level. But those warnings do display correctly. I'm guessing that's because that command goes through code path 1, but I haven't verified that myself.

## What occurred

Note: this is using CC code that is not yet on master, so you won't be able to repro with this exact command. I didn't find a command I could use to repro this with the current CC, but that's just because there aren't too many places where warnings get returned.
```
> cf bind-service dora ups -c '{"foo": "bar"}'
Binding service ups to app dora in org o / space s as admin...
Configuration+parameters+are+ignored+for+bindings+to+user+provided+service+instances.

OK
TIP: Use 'cf restage dora' to ensure your env variable changes take effect
```

If I run the same command with `-v`, you can see the value of the `X-Cf-Warnings` header is:
```
X-Cf-Warnings: Configuration+parameters+are+ignored+for+bindings+to+user+provided+service+instances.
```

## What you expected to occur

The message should read "Configuration parameters are ignored for bindings to user provided service instances." and ideally be colored nicely like the warnings are when warnings are correctly displayed.

For example, this works well:
```
> cf cups test -r  https://testing.<domain>
Creating user provided service test in org o / space s as admin...
OK
Support for route services is disabled. This service instance cannot be bound to a route.
```

That last line is a warning that came from `X-Cf-Warnings` and is shown to the user is bold pink/purple. The literal value of `X-Cf-Warnings` in this case is:

```
X-Cf-Warnings: Support+for+route+services+is+disabled.+This+service+instance+cannot+be+bound+to+a+route.
```
Same style as above. It just seems that the two commands are using different ways to interpret and present the warnings.

## CLI Version  

cf version 6.35.1+bfbe5f0e8.2018-03-14

## CC API Endpoint Version  

2.107.0

This API version is only relevant for the route services warning mentioned above, since the warning on binding user provided services with params is not in any official CC API yet.

## Platform & Shell Details  

Mac OS X 10.13.3 running tmux in iTerm.

**Comment by XenoPhex** [comment]
<strike>Make your warning better!</strike>

I mean, thanks for the catch! Didn't know we had to unescape these, we'll add a fix for this ASAP. (unless you beat us to a pull)

Also, thanks for finding the issue in both places!

**Comment by jenspinney** [comment]
@XenoPhex We built the cf binary off the master branch and confirmed that the commit you made fixes the problem :). Thanks for the super quick response!

Would still be nice to have the warning show up a little more obviously, like with different colors or bolding (or maybe prefaced with `WARNING:`, if that's more accessible than colors/bolding). But I think that's a separate concern, and what you've done addresses our main problem.

I'll leave the issue open so you guys can close it yourselves once you have PM acceptance, but it all looks good from our end.

**Comment by XenoPhex** [comment]
Hi @jenspinney, thanks again for submitting this. We'e applied a fix and it should be in the next release of the CLI. 

Thanks for your feedback regarding improving the warning message. We've made a note to add your feedback to both a style guide we are developing and we've also added a story in our backlog to improve the warning display in the CLI output. 

Please let us know if you have any other feedback by opening a new issue.
