### ISSUE TITLE
Command cf services leads to Unknown request FAILED

### ISSUE THREAD

**Issue by bensteinert** [cloudfoundry/cli#1362]
Since cf cli 6.36 we are facing issues when executing 'cf services'.

## Command  

cf services

## What occurred

High-level output:
Getting services in org *** as ***...

Unknown request
FAILED

## What you expected to occur

List of my services in the space

## CLI Version  

cf/6.36.1+e3799ad7e.2018-04-04

## CC API Endpoint Version  

api version:    2.65.0

## CF Trace

CF CLI 6.35 does:
REQUEST: [2018-04-11T13:50:28+02:00][0m
GET /v2/services/d0ee2aea-6952-4f26-a6dd-ef23fca6740a HTTP/1.1
Host: ***
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.35.0+5c7de3e32.2018-03-08 (go1.10; amd64 darwin)

RESPONSE: [2018-04-11T13:50:28+02:00][0m
HTTP/1.1 200 OK
Connection: keep-alive ...

----

CF CLI 3.36.1 does:
REQUEST: [2018-04-11T13:51:57+02:00]
GET /v2/services/ HTTP/1.1
Host: ***
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.36.1+e3799ad7e.2018-04-04 (go1.10.1; amd64 darwin)

RESPONSE: [2018-04-11T13:51:58+02:00]
HTTP/1.1 404 Not Found
Connection: keep-alive ...

So looks like the new version leaves out the resource id in the path? 

## Platform & Shell Details  

any as far as I can see

**Comment by XenoPhex** [comment]
@bensteinert Can you provide us a full CF trace? We think one of the prior requests we're making might be missing data, but without the full trace it'll be difficult to debug on our end.

**Comment by bensteinert** [comment]
@XenoPhex here it comes. That's the full trace of the request snippet you saw above:

REQUEST: [2018-04-11T13:51:57+02:00]
GET /v2/info HTTP/1.1
Host: api.eu-west-1.***
Accept: application/json
User-Agent: cf/6.36.1+e3799ad7e.2018-04-04 (go1.10.1; amd64 darwin)

RESPONSE: [2018-04-11T13:51:57+02:00]
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 596
Content-Type: application/json;charset=utf-8
Date: Wed, 11 Apr 2018 11:51:59 GMT
Server: nginx
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Vcap-Request-Id: 6cf0d474-dc2b-435f-6f83-86ec7ce9a864
X-Vcap-Request-Id: 6cf0d474-dc2b-435f-6f83-86ec7ce9a864::6a5dafa7-b066-4610-a004-d71fe201e914
X-Xss-Protection: 1; mode=block
{
  "api_version": "2.65.0",
  "app_ssh_endpoint": "ssh.eu-west-1.***:2222",
  "app_ssh_host_key_fingerprint": "3c:7f:07:62:e0:d9:a0:c5:72:52:f4:31:b8:59:e8:ea",
  "app_ssh_oauth_client": "ssh-proxy",
  "authorization_endpoint": "https://login.***",
  "build": "",
  "description": "",
  "doppler_logging_endpoint": "wss://doppler.eu-west-1.***:4443",
  "logging_endpoint": "wss://loggregator.eu-west-1.***:4443",
  "min_cli_version": null,
  "min_recommended_cli_version": null,
  "name": "",
  "support": "http://support.cloudfoundry.com",
  "token_endpoint": "https://uaa.***",
  "version": 0
}


REQUEST: [2018-04-11T13:51:57+02:00]
GET /login HTTP/1.1
Host: login.***
Accept: application/json
Connection: close
User-Agent: cf/6.36.1+e3799ad7e.2018-04-04 (go1.10.1; amd64 darwin)

RESPONSE: [2018-04-11T13:51:57+02:00]
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Cache-Control: no-store
Cache-Control: no-cache="set-cookie"
Content-Language: en-US
Content-Length: 426
Content-Type: application/json;charset=UTF-8
Date: Wed, 11 Apr 2018 11:51:59 GMT
Expires: 0
Pragma: no-cache
Server: nginx/1.9.12
Set-Cookie: AWSELB=2FAF3F290CA04F28DC12AE881CE106046F78C36AB54CF24C4BB5910CC025C93C64A1EDD2B973C60CC8C4ED07993D6C194FC0388686D909B12C688625F76205764348F1DCA4;PATH=/;MAX-AGE=1800
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
{
  "app": {
    "version": "3.3.0.1"
  },
  "commit_id": "14f748e",
  "entityID": "login.***",
  "idpDefinitions": {},
  "links": {
    "login": "https://login.***",
    "passwd": "https://console.***/password_resets/new",
    "register": "https://console.***/register",
    "uaa": "https://uaa.***"
  },
  "prompts": {
    "password": [
      "password",
      "Password"
    ],
    "username": [
      "text",
      "Email"
    ]
  },
  "timestamp": "2017-04-06T12:44:53+0200",
  "zone_name": "uaa"
}


Getting services in org *** / space DEV as *** ...

REQUEST: [2018-04-11T13:51:57+02:00]
GET /v2/spaces/1790155f-03d4-43e9-8308-f283bf9e5fe3/service_instances?return_user_provided_service_instances=true HTTP/1.1
Host: api.eu-west-1.***
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.36.1+e3799ad7e.2018-04-04 (go1.10.1; amd64 darwin)

RESPONSE: [2018-04-11T13:51:57+02:00]
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 12457
Content-Type: application/json;charset=utf-8
Date: Wed, 11 Apr 2018 11:51:59 GMT
Server: nginx
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Vcap-Request-Id: ead7ccbc-8119-4a81-5ace-5f472ea7937c
X-Vcap-Request-Id: ead7ccbc-8119-4a81-5ace-5f472ea7937c::d77f89b1-f67d-4b3a-83a1-b1827ba5149d
X-Xss-Protection: 1; mode=block
{
  "next_url": null,
  "prev_url": null,
  "resources": [
    {
      "entity": {
        "credentials": {},
        "dashboard_url": null,
        "gateway_data": null,
        "last_operation": {
          "created_at": "2017-04-19T14:39:13Z",
          "description": "DB Instance 'cf-93f4c8d7-a146-4786-af35-586a2303de86' status is 'available'",
          "state": "succeeded",
          "type": "create",
          "updated_at": "2017-04-19T14:54:22Z"
        },
        "name": "***",
        "routes_url": "/v2/service_instances/93f4c8d7-a146-4786-af35-586a2303de86/routes",
        "service_bindings_url": "/v2/service_instances/93f4c8d7-a146-4786-af35-586a2303de86/service_bindings",
        "service_keys_url": "/v2/service_instances/93f4c8d7-a146-4786-af35-586a2303de86/service_keys",
        "service_plan_guid": "4a5a5ebc-6db6-4a89-8a41-e7b99884bb67",
        "service_plan_url": "/v2/service_plans/4a5a5ebc-6db6-4a89-8a41-e7b99884bb67",
        "space_guid": "1790155f-03d4-43e9-8308-f283bf9e5fe3",
        "space_url": "/v2/spaces/1790155f-03d4-43e9-8308-f283bf9e5fe3",
        "tags": [],
        "type": "managed_service_instance"
      },
      "metadata": {
        "created_at": "2017-04-19T14:39:13Z",
        "guid": "93f4c8d7-a146-4786-af35-586a2303de86",
        "updated_at": "2017-04-19T14:39:13Z",
        "url": "/v2/service_instances/93f4c8d7-a146-4786-af35-586a2303de86"
      }
    },
    {
      "entity": {
        "credentials": {},
        "name": "***",
        "route_service_url": "",
        "routes_url": "/v2/user_provided_service_instances/098ae299-a841-4f56-88c1-207339137b68/routes",
        "service_bindings_url": "/v2/user_provided_service_instances/098ae299-a841-4f56-88c1-207339137b68/service_bindings",
        "service_keys_url": "/v2/user_provided_service_instances/098ae299-a841-4f56-88c1-207339137b68/service_keys",
        "space_guid": "1790155f-03d4-43e9-8308-f283bf9e5fe3",
        "space_url": "/v2/spaces/1790155f-03d4-43e9-8308-f283bf9e5fe3",
        "syslog_drain_url": "",
        "type": "user_provided_service_instance"
      },
      "metadata": {
        "created_at": "2017-05-09T08:27:39Z",
        "guid": "098ae299-a841-4f56-88c1-207339137b68",
        "updated_at": "2017-08-02T13:34:11Z",
        "url": "/v2/user_provided_service_instances/098ae299-a841-4f56-88c1-207339137b68"
      }
    },
    {
      "entity": {
        "credentials": {
          "host": "tcp:listeners.eu-west-1.***",
          "port": 12201,
          "token": "adf74497-364f-4b3f-a574-cee91bd0f210_1790155f-03d4-43e9-8308-f283bf9e5fe3"
        },
        "name": "***",
        "route_service_url": "",
        "routes_url": "/v2/user_provided_service_instances/68e84b5b-f719-4c2a-91aa-fd065a7a383d/routes",
        "service_bindings_url": "/v2/user_provided_service_instances/68e84b5b-f719-4c2a-91aa-fd065a7a383d/service_bindings",
        "service_keys_url": "/v2/user_provided_service_instances/68e84b5b-f719-4c2a-91aa-fd065a7a383d/service_keys",
        "space_guid": "1790155f-03d4-43e9-8308-f283bf9e5fe3",
        "space_url": "/v2/spaces/1790155f-03d4-43e9-8308-f283bf9e5fe3",
        "syslog_drain_url": "",
        "type": "user_provided_service_instance"
      },
      "metadata": {
        "created_at": "2017-05-17T13:00:48Z",
        "guid": "68e84b5b-f719-4c2a-91aa-fd065a7a383d",
        "updated_at": "2017-05-17T13:00:48Z",
        "url": "/v2/user_provided_service_instances/68e84b5b-f719-4c2a-91aa-fd065a7a383d"
      }
    },
    {
      "entity": {
        "credentials": {
          "url": "https://***/2/users/me/permissions"
        },
        "name": "***",
        "route_service_url": "",
        "routes_url": "/v2/user_provided_service_instances/cfffd106-f632-495e-9825-62b2b2a6696e/routes",
        "service_bindings_url": "/v2/user_provided_service_instances/cfffd106-f632-495e-9825-62b2b2a6696e/service_bindings",
        "service_keys_url": "/v2/user_provided_service_instances/cfffd106-f632-495e-9825-62b2b2a6696e/service_keys",
        "space_guid": "1790155f-03d4-43e9-8308-f283bf9e5fe3",
        "space_url": "/v2/spaces/1790155f-03d4-43e9-8308-f283bf9e5fe3",
        "syslog_drain_url": "",
        "type": "user_provided_service_instance"
      },
      "metadata": {
        "created_at": "2017-06-30T13:13:02Z",
        "guid": "cfffd106-f632-495e-9825-62b2b2a6696e",
        "updated_at": "2017-06-30T13:13:02Z",
        "url": "/v2/user_provided_service_instances/cfffd106-f632-495e-9825-62b2b2a6696e"
      }
    },
    {
      "entity": {
        "credentials": {},
        "name": "***",
        "route_service_url": "",
        "routes_url": "/v2/user_provided_service_instances/bd6eada8-3389-4551-b778-a77ff55cf276/routes",
        "service_bindings_url": "/v2/user_provided_service_instances/bd6eada8-3389-4551-b778-a77ff55cf276/service_bindings",
        "service_keys_url": "/v2/user_provided_service_instances/bd6eada8-3389-4551-b778-a77ff55cf276/service_keys",
        "space_guid": "1790155f-03d4-43e9-8308-f283bf9e5fe3",
        "space_url": "/v2/spaces/1790155f-03d4-43e9-8308-f283bf9e5fe3",
        "syslog_drain_url": "",
        "type": "user_provided_service_instance"
      },
      "metadata": {
        "created_at": "2017-11-16T12:45:06Z",
        "guid": "bd6eada8-3389-4551-b778-a77ff55cf276",
        "updated_at": "2018-01-17T15:51:31Z",
        "url": "/v2/user_provided_service_instances/bd6eada8-3389-4551-b778-a77ff55cf276"
      }
    },
    {
      "entity": {
        "credentials": {},
        "name": "syslog-drain",
        "route_service_url": "",
        "routes_url": "/v2/user_provided_service_instances/0c26b8a4-d2a8-4651-b299-38b273d869a6/routes",
        "service_bindings_url": "/v2/user_provided_service_instances/0c26b8a4-d2a8-4651-b299-38b273d869a6/service_bindings",
        "service_keys_url": "/v2/user_provided_service_instances/0c26b8a4-d2a8-4651-b299-38b273d869a6/service_keys",
        "space_guid": "1790155f-03d4-43e9-8308-f283bf9e5fe3",
        "space_url": "/v2/spaces/1790155f-03d4-43e9-8308-f283bf9e5fe3",
        "syslog_drain_url": "https://listeners.eu-west-1.***/?token=adf74497-364f-4b3f-a574-cee91bd0f210_1790155f-03d4-43e9-8308-f283bf9e5fe3",
        "type": "user_provided_service_instance"
      },
      "metadata": {
        "created_at": "2018-02-14T13:47:51Z",
        "guid": "0c26b8a4-d2a8-4651-b299-38b273d869a6",
        "updated_at": "2018-02-14T13:47:51Z",
        "url": "/v2/user_provided_service_instances/0c26b8a4-d2a8-4651-b299-38b273d869a6"
      }
    },
    {
      "entity": {
        "credentials": {},
        "dashboard_url": null,
        "gateway_data": null,
        "last_operation": {
          "created_at": "2018-03-05T18:14:25Z",
          "description": "The instance was created",
          "state": "succeeded",
          "type": "create",
          "updated_at": "2018-03-05T18:14:25Z"
        },
        "name": "***",
        "routes_url": "/v2/service_instances/4f93922b-1345-42c0-b16d-b1d751c7fafb/routes",
        "service_bindings_url": "/v2/service_instances/4f93922b-1345-42c0-b16d-b1d751c7fafb/service_bindings",
        "service_keys_url": "/v2/service_instances/4f93922b-1345-42c0-b16d-b1d751c7fafb/service_keys",
        "service_plan_guid": "56b217c1-0797-4581-8c29-f353e99f023e",
        "service_plan_url": "/v2/service_plans/56b217c1-0797-4581-8c29-f353e99f023e",
        "space_guid": "1790155f-03d4-43e9-8308-f283bf9e5fe3",
        "space_url": "/v2/spaces/1790155f-03d4-43e9-8308-f283bf9e5fe3",
        "tags": [],
        "type": "managed_service_instance"
      },
      "metadata": {
        "created_at": "2018-03-05T18:14:25Z",
        "guid": "4f93922b-1345-42c0-b16d-b1d751c7fafb",
        "updated_at": "2018-03-05T18:14:25Z",
        "url": "/v2/service_instances/4f93922b-1345-42c0-b16d-b1d751c7fafb"
      }
    }
  ],
  "total_pages": 1,
  "total_results": 7
}


REQUEST: [2018-04-11T13:51:57+02:00]
GET /v2/service_plans/4a5a5ebc-6db6-4a89-8a41-e7b99884bb67 HTTP/1.1
Host: api.eu-west-1.***
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.36.1+e3799ad7e.2018-04-04 (go1.10.1; amd64 darwin)

RESPONSE: [2018-04-11T13:51:57+02:00]
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 1027
Content-Type: application/json;charset=utf-8
Date: Wed, 11 Apr 2018 11:51:59 GMT
Server: nginx
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Vcap-Request-Id: 0408a546-729a-41b7-7a27-38f2825a24b8
X-Vcap-Request-Id: 0408a546-729a-41b7-7a27-38f2825a24b8::3bacda61-8332-4f9e-9c40-5baa21001203
X-Xss-Protection: 1; mode=block
{
  "entity": {
    "active": true,
    "description": "RDS PostgreSQL 9.4 (10GB Storage, Maximum ~238 Connections)",
    "extra": "{\"bullets\":[\"Dedicated PostgreSQL Server (db.m3.medium)\",\"PostgreSQL v9.4\",\"10GB of Storage\",\"Maximum ~238 Connections\",\"Automatically Upgrade Minor Version\",\"Multiple Availability Zone - High Availability\",\"Backup and Recovery\"],\"costs\":[{\"amount\":{\"usd\":0.18},\"unit\":\"HOUR\"}]}",
    "free": false,
    "name": "9.4-medium",
    "public": true,
    "service_guid": "d0ee2aea-6952-4f26-a6dd-ef23fca6740a",
    "service_instances_url": "/v2/service_plans/4a5a5ebc-6db6-4a89-8a41-e7b99884bb67/service_instances",
    "service_url": "/v2/services/d0ee2aea-6952-4f26-a6dd-ef23fca6740a",
    "unique_id": "d03b544e-3be5-4aca-bb3b-11544247f313"
  },
  "metadata": {
    "created_at": "2016-06-24T15:47:34Z",
    "guid": "4a5a5ebc-6db6-4a89-8a41-e7b99884bb67",
    "updated_at": "2017-07-27T13:01:42Z",
    "url": "/v2/service_plans/4a5a5ebc-6db6-4a89-8a41-e7b99884bb67"
  }
}


REQUEST: [2018-04-11T13:51:57+02:00]
GET /v2/services/ HTTP/1.1
Host: api.eu-west-1.***
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.36.1+e3799ad7e.2018-04-04 (go1.10.1; amd64 darwin)

RESPONSE: [2018-04-11T13:51:58+02:00]
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 86
Content-Type: application/json;charset=utf-8
Date: Wed, 11 Apr 2018 11:51:59 GMT
Server: nginx
X-Cascade: pass
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 32179c88-c572-41ae-675f-1703631e050d
X-Vcap-Request-Id: 32179c88-c572-41ae-675f-1703631e050d::90c1fef6-5569-4da2-9d97-5a2f7ece737f
{
  "code": 10000,
  "description": "Unknown request",
  "error_code": "CF-NotFound"
}


FAILED

**Comment by anyu** [comment]
Hi @bensteinert, is this easily reproducible on your side in a clean environment? If so, could you send us steps to reproduce (eg. which services you pushed, org/spaces setup, etc). Thanks!

**Comment by abbyachau** [comment]
Thanks we were able to verify that this is indeed broken in CF API v2.65.  Please see our support [policy](https://github.com/cloudfoundry/cli/wiki/Versioning-Policy#compatibility-cf-cli-with-cf-releasescc-api-versions) for supported versions of CF CLI and CF APIs. Because your version of CF API falls just behind the window for deprecated versions, we do not plan on applying a fix. 

If you upgrade to a version of CF API v2.68 or higher, then it should resolve the issues as well as fall in our support window (if for whatever reason upgrading does not resolve things).
