### ISSUE TITLE
6.36.1 marked as 6.36.0 in deb/rpm

### ISSUE THREAD

**Issue by petermarko** [cloudfoundry/cli#1364]
## Command  

n/a

## What occurred

`deb` and `rpm` packages show wrong version.
```
$ cf --version
cf version 6.36.1+e3799ad7e.2018-04-04
$ dpkg -l | grep cf-cli
ii  cf-cli                                        6.36.0
```

## What you expected to occur

```
$ cf --version
cf version 6.36.1+e3799ad7e.2018-04-04
$ dpkg -l | grep cf-cli
ii  cf-cli                                        6.36.1
```
## CLI Version  

`cf version 6.36.1+e3799ad7e.2018-04-04`

## CC API Endpoint Version  

n/a

## CF Trace

n/a

## Platform & Shell Details  

Debian Stretch
`Linux dev-6 4.14.0-0.bpo.3-amd64 #1 SMP Debian 4.14.13-1~bpo9+1 (2018-01-14) x86_64 GNU/Linux`

## Any other relevant information  
`cf-cli-installer_6.36.1_x86-64.deb` has following in control file:
```
Package: cf-cli
Version: 6.36.0
```

`cf-cli-installer_6.36.1_x86-64.rpm` has following in info file:
```
NAME:         cf-cli
VERSION:      6.36.0
```

**Comment by XenoPhex** [comment]
Looks like our build scripts were not updated to look in the new location of our version file. I've verified that it now works correctly on our edge release.

Thanks again for letting us know!
