### ISSUE TITLE
CF push with manifest does not honor the order of service bindings

### ISSUE THREAD

**Issue by madevr** [cloudfoundry/cli#1367]
Hi,

Using most recent CF CLI version.

The order of the service bindings in a manifest is not honored when doing a cf push.

For example:
I have an app that needs to be bound to serviceA and serviceB. serviceB requires that serviceA is already bound, and it also checks this when the binding to it happens. Therefore, I define the following service bindings in my manifest:
- serviceA
- serviceB

I expect that first, serviceA is bound, and then serviceB is bound to my app.

However, when executing cf push, it can happen that serviceB is bound first, resulting in an error.

Would it be possible to honor the order of the services? Or to provide an option for this?

Thanks and kind regards

**Comment by XenoPhex** [comment]
We can look into this, but it's possible our yaml library is reading them out of order. If that is the case, there's not much we can do.

**Comment by abbyachau** [comment]
hey @selzoc @ssisil do you know if this is still an issue using v3 server side manifests?

**Comment by selzoc** [comment]
It looks like we do them in the order that they appear in the manifest using server side manifests.
