### ISSUE TITLE
Document recommendations for programmatically interacting with the CF CLI

### ISSUE THREAD

**Issue by mcwumbly** [cloudfoundry/cli#1368]
Currently, there are a number of things that interact programmatically with the CF CLI, for example the [CF Acceptance Tests (CATs)](https://github.com/cloudfoundry/cf-acceptance-tests), other test suites, and other automations.

In some cases, we have seen these integrations break when new CLI features are added.

Here are a few commits to illustrate:

- [CATs: repair breaking changes from cf-cli](https://github.com/cloudfoundry/cf-acceptance-tests/commit/568efc86780ae09e6d40049268e6b7d6e0bf61eb)
- [CATs: make service instance tests compatible with refactored CLI service command](https://github.com/cloudfoundry/cf-acceptance-tests/commit/63c7bf2a72357abd7ab98a431e45a32774e2af7d)
- [CATs: error message regex is backwards compatible with different cf cli versions](https://github.com/cloudfoundry/cf-acceptance-tests/commit/d218dfd3a24907a367b9f183d1caeddbd8f76519)

As noted by @dsabeti in another thread:

> CATs makes a lot of assertions about CLI output, and the CLI team has to make PRs to CATs any time a story updates that copy -- even worse, the assertions need to be backwards compatible, because we don't know which version of the CLI the user has.

One suggestions has been to add something like a `--json` flag to the CLI commands that might include output designed to be consumed programmatically. However, @dsabeti also noted that:

> although I'd still want CATs to mostly use the "normal" CLI features in order to mimic user workflows

So perhaps that point could be discussed further.

Regardless of the specific solution the team lands on here, I think it would be helpful to have documented guidance about what is recommended / safe to do for scripts that want to remain compatible with different versions of the CF CLI.

In another conversation, @abbyachau also pointed to these three related issues, which have since been closed (https://github.com/cloudfoundry/cli/issues/604, https://github.com/cloudfoundry/cli/issues/1060, https://github.com/cloudfoundry/cli/issues/851), and noted:

> We have plans working to improve script-ability and will circle back regarding this issue soon.

I think this issue would be a good "canonical home" for this discussion (unless you'd like to direct it elsewhere). In lieu of any alternative, please any updates here. Thanks!

**Comment by abbyachau** [comment]
Hi @mcwumbly I'm closing this issue as done, please do not hesitate to get in touch with feedback/questions. Thanks.
