### ISSUE TITLE
CF cli not displaying the documentation url when running `cf service <service_name>`

### ISSUE THREAD

**Issue by Jammy-Louie** [cloudfoundry/cli#1369]
## Command  

cf service <service_name>

## What occurred

 cli not displaying the documentation url

![screen shot 2018-04-23 at 12 53 47 pm](https://user-images.githubusercontent.com/8474965/39204579-277a5b2e-47c6-11e8-9c96-a006392a3d6c.png)

## What you expected to occur

I expect to see the documentation url

<img width="1277" alt="screen shot 2018-04-24 at 10 25 07 am" src="https://user-images.githubusercontent.com/8474965/39204610-3ca862c0-47c6-11e8-9f01-1292f35222a0.png">

## CLI Version  

6.36.1+e3799ad7e.2018-04-04

## CC API Endpoint Version  

api version:    2.103.0

## Platform & Shell Details  

Mac OS X 10.11 iTerm

## Any other relevant information  

this appears to be working on 6.29.0+ff886fa93.2017-07-24

**Comment by mattmcneeney** [comment]
Hey @Jammy-Louie 
Apologies for the very delayed response! Is/was your service broker exposing the documentation URL in the `service[n].metadata.documentationUrl` field as described in the [spec](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#service-metadata)?

**Comment by mattmcneeney** [comment]
I've just verified that this is a real bug. We will look to resolve this. Thanks @Jammy-Louie and @gberche-orange, and sorry again for the slow reply!

**Comment by abbyachau** [comment]
Pull request to follow: https://github.com/cloudfoundry/cli/pull/1480

**Comment by jenspinney** [comment]
This should be fixed by #1480 (thanks Services API team!). If this continues to be a problem, please let us know.
