### ISSUE TITLE
Plugin API does not provide a way of refreshing tokens

### ISSUE THREAD

**Issue by henrytk** [cloudfoundry/cli#1372]
In developing the CF CLI plugin [Conduit](https://github.com/alphagov/paas-cf-conduit/) we have encountered a problem with refreshing access tokens (https://github.com/alphagov/paas-cf-conduit/issues/18).

The plugin is used for interactive database shells and as a result may need to be used for longer than a typical access token lasts. The most reasonable method of accessing a service instance via a shell is to use an ephemeral app which is deleted after the session. Because the shell may be opened for a long period of time users have noticed the ephemeral application is not deleted after using Conduit.

We are currently implementing a fix for this. However, [the Plugin API](https://github.com/cloudfoundry/cli/blob/master/plugin/plugin_examples/DOC.md) doesn't seem to support getting a refresh token, so we have had to use an unpleasant workaround (executing `cf oauth-token` as a system command).

Would you consider allowing plugins to get a refresh token?

## Command  

```bash
cf conduit service-instance-name -- psql
# Wait 10+ minutes
\q
```

## What occurred

The ephemeral app is not deleted.

## What you expected to occur

The ephemeral app is deleted.

## CLI Version  

All

## CC API Endpoint Version  

All

## CF Trace

N/A

## Platform & Shell Details  

N/A

**Comment by XenoPhex** [comment]
Hey @henrytk thanks for reaching out. We are aware of this issue but unfortunately due to the nature of the code, implementing a fix for this issue is non-trivial. We do plan on revisiting and enhancing the plugin architecture and hope to address this specific issue when we do. What you are currently doing is the established method of refreshing the token - again, we hope to improve upon this at some point down the line.

**Comment by henrytk** [comment]
Thanks @XenoPhex. Any timeline on the re-architecture?

**Comment by abbyachau** [comment]
Hey @henrytk thanks again for creating this issue. We are tracking your feedback here: https://www.pivotaltracker.com/story/show/157201049, which is our tracker story for researching pain points related to the current plugin architecture. Please provide any additional feedback you may have there, or create/reopen a new issue. Thanks again.
