### ISSUE TITLE
PCF LOGIN ISSUE

### ISSUE THREAD

**Issue by MdKamranUddin** [cloudfoundry/cli#1388]
When I am trying to login to cf cli, I am getting the below error:
Error performing request: Get https://api.run.pivotal.io/v2/info: read tcp 10.159.116.73:56349->52.205.108.189:443: wsarecv: An existing connection was forcibly closed by the remote host.

Can somebody assist immediately

**Comment by abbyachau** [comment]
Hi @MdKamranUddin, what version of the cli are you on? How are you attempting to log in? Thanks.

**Comment by MdKamranUddin** [comment]
I am using the latest version. I am attempting to login through cf login -a https://api.run.pivotal.io
Thanks.

**Comment by abbyachau** [comment]
Hey @MdKamranUddin could you give us a trace of the issue? Might help us triage, thanks.

**Comment by abbyachau** [comment]
Great @MdKamranUddin thanks for the update.
