### ISSUE TITLE
Network commands not available on Debian/Ubuntu

### ISSUE THREAD

**Issue by antechrestos** [cloudfoundry/cli#1392]
Hi,

I installed [the last version](https://github.com/cloudfoundry/cli/releases/tag/v6.37.0) for ubuntu. 

I have strange behaviour; first one is this:

```
❯❯❯ sudo dpkg -i cf-cli-installer_6.37.0_x86-64.deb         ⏎
Sélection du paquet cf-cli précédemment désélectionné.
(Lecture de la base de données... 313305 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de cf-cli-installer_6.37.0_x86-64.deb ...
Dépaquetage de cf-cli (6.37.0) ...
Paramétrage de cf-cli (6.37.0) ...
❯❯❯ cf version
cf version 6.22.2+a95e24c-2016-10-27
```

Apparently pagnage 6.37 contains an old binary (6.22).

Yet my problem is somewhere else:

```
❯❯❯ cf network-policies
'network-policies' n'est pas une commande enregistrée. Voir 'cf help'
❯❯❯ cf add-network-policy                                   ⏎
'add-network-policy' n'est pas une commande enregistrée. Voir 'cf help'
```

For those not french fluent, the command does not exist.

I even tried to run it with a user having the `network.write` and `network.admin` UAA scope.

Did I miss something?

Thank you

**Comment by XenoPhex** [comment]
Hey there @antechrestos before we start debugging this - I verified that the debian package you listed has the correct cf cli version:
```
$ dpkg -x cf-cli-installer_6.37.0_x86-64.deb . # this extracts the content of the deb file
$ tree .
.
├── cf-cli-installer_6.37.0_x86-64.deb
└── usr
    ├── bin
    │   └── cf
    └── share
        ├── bash-completion
        │   └── completions
        │       └── cf
        └── doc
            └── cf-cli
                ├── copyright
                ├── LICENSE
                └── NOTICE

7 directories, 6 files
$ ./usr/bin/cf -v
cf version 6.37.0+a40009753.2018-05-25
```
From the look of it the `cf` binary in the deb (that's linked to via our download page)  does contain the correct version.

This leads me to believe this may be a path issue. The default deb install location of the `cf` binary appears to be `/usr/bin/cf` - make sure that's the one you're running. You can run `which cf` to verify which binary is ran when you use the `cf` command.

Try that first and let me know what comes up. If it's not `/usr/bin/cf` then you have a different binary taking precedence above the deb installed version.

**Comment by antechrestos** [comment]
@XenoPhex Looks like it was that! I had did at two different time the following actions
- one version installed with `dpkg -i`
- on in a specific placed added to the `PATH`

When I tried to upgrade, I uninstalled the one installed with packet manager, and totally missed the second one.


My mistake!

Please excuse me for this silly issue!
