### ISSUE TITLE
cf cli 6.37.0: cf push calls GET  /v3

### ISSUE THREAD

**Issue by stephanme** [cloudfoundry/cli#1394]
## Command  

CF_TRACE=true cf push --no-start test -p /tmp/test -m 64M

## What occurred

cf push calls /v3 endpoint 

## What you expected to occur

No cloud controller /v3 calls unless I use v3-* commands.

## CLI Version  

cf version 6.37.0+a40009753.2018-05-25

## CC API Endpoint Version  

api version:    2.113.0

## CF Trace

````
...
REQUEST: [2018-06-12T07:16:31Z]
GET /v3 HTTP/1.1
Host: api.cf.stagingsc7.hanavlab.ondemand.com
Accept: application/json
User-Agent: cf/6.37.0+a40009753.2018-05-25 (go1.9.6; amd64 linux)

RESPONSE: [2018-06-12T07:16:31Z]
HTTP/1.1 200 OK
Content-Length: 1173
Content-Type: application/json; charset=utf-8
Date: Tue, 12 Jun 2018 07:16:31 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Ratelimit-Limit: 500
X-Ratelimit-Remaining: 483
X-Ratelimit-Reset: 1528791096
X-Runtime: 0.001366
X-Vcap-Request-Id: 6b0ddca8-072a-4913-6f4d-284518573cf4::61d7612f-50b4-40ab-af5f-0defea158098
X-Xss-Protection: 1; mode=block
{
  "links": {
    "apps": {
      "href": "https://api.cf.stagingsc7.hanavlab.ondemand.com/v3/apps"
    },
  ...
````

See also attached log.

## Platform & Shell Details  

Ubuntu 16.04.4 LTS

## Any other relevant information  

The problem is related to https://github.com/cloudfoundry/cloud_controller_ng/issues/1161
GET /v3 is currently counted on CC unauthenticated rate limit. This leads to failed cf push calls due to 429 responses by the CC. Especially problematic is that it hits the global and rather low unauthenticated rate limit (in contrast to the per user rate limit).

cf cli 6.36.2 doesn't call GET /v3.

**Comment by abbyachau** [comment]
Hi @stephanme could you show us the actual error that you received? Thanks.

**Comment by stephanme** [comment]
The error that I see for cf push with 6.37.0:

````
Unexpected Response
Response Code: 429
Request ID:    bfa7060e-f74c-4b41-4c61-bb87f5d75815::1ea8af53-7f61-4d8f-a0c2-0f98ac7dda03
Code: 10013, Title: CF-RateLimitExceeded, Detail: Rate Limit Exceeded
````

See also the related CC bug https://github.com/cloudfoundry/cloud_controller_ng/issues/1161. A fix for one of the two bugs (this one or the CC one) would solve the problem. Still I think that the CC v3 api should only be used by v3-* cf cli commands. 

The [CC v3 doc](http://v3-apidocs.cloudfoundry.org/version/3.49.0/index.html) is sort vague regarding its status: 
- there is no explicit status described like beta, experiemental or GA - so I have to assume it is GA
- there are some resources marked as experimental - so I assume that the other ones are GA
- "The Cloud Foundry V2 API is still the primary API for interacting with Cloud Foundry." - Don't know what I shall learn from this statement. Is the v3 api beta?

Anyway, cf push is broken with cf cli 6.37.0 on landscapes with heavy usage because the unauthenticated rate limit is reached very soon. Switching off the rate limit is not an option for productive landscapes.

**Comment by tjvman** [comment]
Hi @stephanme! Calls to the `v3` API are not limited to the commands prefixed with `v3-`; in fact, there are already commands that use the v3 API and are not prefixed (`tasks`, for example). 

You're correct in assuming that V3 is GA'ed; v2 is still the primary API for interacting with CloudFoundry because v3 does not yet support all of the functionality in v2. 

From what I can see, the proposed fix for the rate-limiting issue in CAPI makes sense. In the interval, reaching out to the CAPI team may be worthwhile to see if they have a workaround.

**Comment by stephanme** [comment]
CC removed /v3 calls from rate limiting (https://github.com/cloudfoundry/cloud_controller_ng/issues/1161). So I close this ticket.

Thanks,
Stephan
