### ISSUE TITLE
Flask app on Cloud Foundry - Command “python setup.py egg_info” failed with error code 1

### ISSUE THREAD

**Issue by pruthvishetty** [cloudfoundry/cli#1396]
I am trying to push a Python (3.6.5) app via Flask to Cloud Foundry (cf version 6.36.1+e3799ad7e.2018-04-04). The application takes a POST request (text file), does some text transformation, saves the new file, and returns a confirmation message. It works locally (tested via Postman). However, when attempting to push it to CF, it gives the following error -

`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ygzuah5g/logging/`

Could you please let me know how I can go about solving this issue? Thanks in advance. The entire files together are ~ 350 MB. I am using a manifest.yml 

    ```
    applications:
    - name: textsum
      memory: 512M
      command: python server.py
      buildpack: https://github.com/cloudfoundry/buildpack-python.git```

PS - Not sure if this is helpful/relevant, I do have ` import queue` in one of my files. If I change it to `import Queue` (Py 2x compatible) and use Py 2.7.15 runtime, the cf push is successful, but it throws runtime errors 

   ```ERROR in app: Exception on / [POST]
    File "/home/vcap/deps/0/python/lib/python2.7/subprocess.py", line 1047, in _execute_child
    ERR   raise child_exception
    ERR OSError: [Errno 2] No such file or directory
    ERR 10.0.65.11 - - [12/Jun/2018 20:56:16] "POST / HTTP/1.1" 500 -```

**Comment by abbyachau** [comment]
Hey @pruthvishetty closing this issue as this does not appear to be a CLI-related issue.  It looks like you've created an [issue](https://github.com/cloudfoundry/python-buildpack/issues/111) in a more appropriate place. Thanks.
