### ISSUE TITLE
CONTRIBUTING.md instructions recommend use of deprecated repo

### ISSUE THREAD

**Issue by willmurphyscode** [cloudfoundry/cli#1408]
## What occurred

When trying to set up for local development on the CLI, I saw that this paragraph:
https://github.com/cloudfoundry/cli/blob/master/.github/CONTRIBUTING.md#install-bosh-lite-and-deploy-cloud-foundry
links to [bosh-lite](https://github.com/cloudfoundry/bosh-lite#deploy-cloud-foundry) which is deprecated.

## What you expected to occur

I think CONTRIBUTING.md should link to current, supported steps.

## Any other relevant information
It looks like the link for setting up BOSH for use with local integration tests should point to the [BOSH quick start docs](http://bosh.io/docs/quick-start/) based on the deprecation [notice on bosh-lite](https://github.com/cloudfoundry/bosh-lite/blob/master/README.md)

**Comment by abbyachau** [comment]
Thanks @willmurphyscode we'll update the page with new links.

**Comment by abbyachau** [comment]
Hi @willmurphyscode thanks for creating this issue, we've updated the contribution [documentation](https://github.com/cloudfoundry/cli/blob/master/.github/CONTRIBUTING.md#install-bosh-lite-and-deploy-cloud-foundry). Thanks again.
