### ISSUE TITLE
Tab complete commands and application names

### ISSUE THREAD

**Issue by berlin-ab** [cloudfoundry/cli#1416]
Feature request: 

It would be nice if the cf-cli were able to help us at the command line. 

If I have an application named `my-app` it would be nice if `cf logs my-` would complete to `cf logs my-app` when I press tab.

**Comment by XenoPhex** [comment]
We currently support tab completion for command names/flags. If you look in the README on the main page, we have different instructions depending on the platform.

As for names, that can be tricky as they would require making network requests every time one would hit the TAB key. We spiked this out at some point and it was 1) way too chatty and 2) caused command line to be extremely slow. This was especially problematic on large orgs/spaces.

**Comment by joaopapereira** [comment]
Thank you for your submission. If this feature is still something that you think is important please open a new ticket.
