### ISSUE TITLE
Request - App to app policy between spaces

### ISSUE THREAD

**Issue by pvaramballypivot** [cloudfoundry/cli#1419]
## Context

Currently users can add/delete an app to app policy between multiple spaces using the API. However the CLI only allows users to add/delete app to app policies in the space they are targeted to.

This is a show stopper for a couple of customers and we would like to update the CLI commands to allow adding/removing app-to-app policies between spaces

### Add network policy
Existing: 
``` cf add-network-policy SOURCE_APP --destination-app DESTINATION_APP [(--protocol (tcp | udp) --port RANGE)] ```
Proposed: 
``` cf add-network-policy SOURCE_APP [SOURCE_SPACE_NAME] --destination-app DESTINATION_APP [DESTINATION_SPACE_NAME] [(--protocol (tcp | udp) --port RANGE)] ```

### Remove network policy
Existing: 
``` cf remove-network-policy SOURCE_APP --destination-app DESTINATION_APP --protocol (tcp | udp) --port RANGE```
Proposed: 
``` cf remove-network-policy SOURCE_APP [SOURCE_SPACE_NAME] --destination-app DESTINATION_APP [DESTINATION_SPACE_NAME] --protocol (tcp | udp) --port RANGE ```

### Remove network policy
Existing: 
```
cf network-policies [--source SOURCE_APP]
Listing network policies in org o / space s as admin...
source               destination             protocol              ports
proxy                   proxy2                     tcp                  8080
app_cat               10.0.3.6                    tcp                  8080-8089
```
Proposed: 
```
cf network-policies [--source SOURCE_APP]
Listing network policies in org o / space s as admin...
source              source space              destination               destination space              protocol              ports
proxy                s                          proxy2                    s2                                tcp                  8080
app_cat             space                       10.0.3.6                  s3                           tcp                  8080-8089
```

## Permission
- User must have either network.admin scope OR network.write + space.developer scope in all spaces they are trying to add/delete policies in (Both source and destination)

## Notes
- One option is to only allow adding/deleting policies from apps in the space they are in. If we did this, we wouldn't need the [SOURCE_SPACE_NAME] optional argument
- Note that we are planning to allow adding/deleting "space to space" and "org to org" policies in the future. This is just an FYI as it may play into the CLI design

## Doc updates required
- https://docs.cloudfoundry.org/devguide/deploy-apps/cf-networking.html#create-policies

**Comment by pvaramballypivot** [comment]
@abbyachau 
Amelia had a great idea on the CLI command format to ensure it is scalable.
So this is an example for add network policy. We will let your team decide on it however. This is just a suggestion.


```cf add-network-policy SOURCE_APP -s [SOURCE_SPACE_NAME] -o [SOURCE_ORG_NAME] --destination-app DESTINATION_APP -s [DESTINATION_SPACE_NAME] -o [DESTINATION_ORG_NAME] [(--protocol (tcp | udp) --port RANGE)]```

OR if we decide to only allow them to create policies from the org and space they are already in ->

```cf add-network-policy SOURCE_APP --destination-app DESTINATION_APP -s [DESTINATION_SPACE_NAME] -o [DESTINATION_ORG_NAME] [(--protocol (tcp | udp) --port RANGE)]```

**Comment by ameowlia** [comment]
## CF Networking Prioritization

We've been creating a lot of issues with you all to cover our current and upcoming work. I just wanted to share how we have prioritized these stories within our team. 

1. BUG: CLI shouldn't use internal domains as the default external domain: https://github.com/cloudfoundry/cli/issues/1420
1. FEATURE: app to app policy within a space: https://github.com/cloudfoundry/cli/issues/1419
1. FEATURE: cli support for internal domains https://github.com/cloudfoundry/cli/issues/1423 (this issue)
1. FEATURE: support for egress policies (no issue created yet, but we will be working on this soon)

**Comment by pvaramballypivot** [comment]
We have a different solution that would perhaps require changes to the APIs, underlying databases and CLI. However it handles a lot of use cases and is also less cumbersome with respect to the CLI command format as compared to what we have proposed here. I will close this issue for now and connect with your team offline when the actual solution work gets prioritized
