### ISSUE TITLE
Feature Proposal: Optionally specify org and space in manifest

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cli#142]
We're currently working on ci deployment automation for our organization.  We're trying to orient this automation around manifests.

As part of our automated deploy we need to know the org and space this manifest is targeted to.  We could use mechanisms in our ci tool to specify org and space for builds.  But we think we could gain some flexibility and simplicity for our customers if we supported optionally specifying an org and space in the manifest.

These values should support inheritance and defaulting like all the other application level  properties.

Implementation detail thoughts:
- If an org is specified and no space then an error would occur.
- If a space is specified and no org then an error would occur.
- If either the org or space is invalid then an error would occur.
- Pushing an app with a manifest where org and space is specified wouldn't actually change the org and space configured in .cf/config.json

**Comment by Rylon** [comment]
Hi!

Is there any possibility of reconsidering this proposal at all? We use manifests with a range of applications, across multiple organisations and spaces, and sometimes we've had users run `cf push` when targeting a different space, and it causes issues in the workflow.

If you could specify org and space in the manifest, the CLI could run `cf target` for you if you aren't already targeting the correct one, which would be quite nice for useability I think. If you didn't specify them then the push could proceed as it does now.

Thanks,
Ryan

**Comment by youngm** [comment]
@Rylon The team is different now so perhaps we'll have a chance. :)

**Comment by dkoper** [comment]
I believe the app manifest is and should remain scoped to the app: the env vars and bindings it needs, the size of container, the number and types of routes it listens to, and should have minimal details on where it is deployed to. Also, I believe for many the idea is that spaces are divided in dev, staging and prod environments, so an app is not tied to only one. Introducing a way to specify a target space name in the app manifest makes it confusing how to take advantage of the separation in spaces.

I have recently heard some requests for a way to specify more in a manifest. This related to services (creating a service), maybe even space creation. I believe it would not be wise to expand the scope of the app manifest in this direction, instead it would be better to explore a new type of descriptor which is scoped to the target environment (that could possibly pull in app manifests).
I would be supportive of people developing CLI plug-ins to explore such ideas.

Regards,
Dies Koper
CF CLI PM

**Comment by youngm** [comment]
@dkoper Just a little insight into our environment.  In practice most of our applications end up having a manifest for each environment (dev, test, prod) anyway.  So, for our custom org/space property we use the manifest inheritance and make it another thing specified for the specific environment.

Anyway, thanks for taking the time to look at the request again.

**Comment by Rylon** [comment]
Yeah, @dkoper we pretty much have the same setup as @youngm - we already end up with a manifest for each environment, `manifest.dev.yml`, `manifest.prod.yml` etc, and just use the right one when pushing, as the required env vars and service bindings differ between environments.

Furthermore, aren't service instances for binding created within specific spaces? So deploying to the correct space is important, if you want to be able to access all the services listed within the manifest.

**Comment by amalagaura** [comment]
If the goal is to put deployment in source control we need a way to do that. Maybe there is objection to putting it in the `manifest.yml`. But there should be a place to specify a deployment target. Maybe a lot of splitting of manifest.dev.yml and so on that people are doing needs to be separate?  But having 2 different YML files would probably be counter productive. I think this needs to be looked at in detail.
