### ISSUE TITLE
Feature Request: switches for cf commands in addition to inline positioning

### ISSUE THREAD

**Issue by carefreepineapple** [cloudfoundry/cli#1422]
## Command
There are a variety of cf commands that use inline positioning to define variable types.  _Some_ of these are:
`cf create-user
cf delete-user
cf org-users
cf set-org-role
cf unset-org-role
cf space-users
cf set-space-role
cf unset-space-role`

## What occurred

All of the above commands, and more, expect the required variables to be delivered inline with the command based on positioning. 

## What you expected to occur

All commands would benefit from the ability to define the variable type with a switch rather than just inline positioning.  This would allow for cleaner scripting and a more explicit definition of the variable type, as well as falling in line with the command structure that we see expressed with `cf login`.

Allow for inline positioning to still define variables if switches are not defined for backwards compatibility.

ie. `cf set-space-user  -u USERNAME -o ORG -s SPACE -r ROLE`

## CLI Version

`cf version 6.36.1+e3799ad7e.2018-04-04`

## Any other relevant information

This builds upon the other feature request for `cf push`, #1413

**Comment by tjvman** [comment]
Closing - Per the [CF CLI Style Guide](https://github.com/cloudfoundry/cli/wiki/CF-CLI-Style-Guide), required arguments are always given as positional arguments, while flags are used for optional arguments (all of login's flags are optional). We have no intention, at this time, of changing this convention and thus it is unlikely that we will implement this feature request.

**Comment by carefreepineapple** [comment]
@tjvman really?  so that's why _cf login_ has required arguments with flags instead of positional arguments.... 
And it took almost a year to respond? wow, pretty telling.

**Comment by abbyachau** [comment]
Hey @carefreepineapple I've just seen this and wanted to reach out to say thanks for this, and sorry we are not always quick to respond to issues. We have a ton of legacy GitHub issues (some date back to 2014) which we were cautious to close, which coupled with our limited resources but heavy support burden, leads to inconsistent and sometimes horrid response times. 

To add to what Tom said, the change you've mentioned would have been a breaking change for the v6 cf CLI. We've been very cautious about introducing changes to args and flag options which would breaking existing legacy scripts on the v6 CLI, and even as we are developing the v7 cf CLI as we want to make the upgrade as seamless as possible. 

We've made exceptions to this rule on the v7 cf CLI, which is currently in beta, and we will review your request and I will reopen this issue in hopes others in the Community will comment.

Thanks again and we appreciate you reaching out. Take care.

**Comment by joaopapereira** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket with the necessary information mentioned in our issue template.
