### ISSUE TITLE
cf set-env command is failing

### ISSUE THREAD

**Issue by kvkadakia** [cloudfoundry/cli#1424]
## Command

cf set-env dflow-server SPRING_APPLICATION_JSON {"maven": { "remote-repositories": { "repo": { "url": "https://repo.spring.io/libs-release" } } } }` 

## What occurred

FAILED
Incorrect Usage. Requires 'app-name env-name env-value' as arguments

NAME:
   set-env - Set an env variable for an app

USAGE:
   cf set-env APP_NAME ENV_VAR_NAME ENV_VAR_VALUE

ALIAS:
   se

## What you expected to occur
I expect it to take in the value of the maven repository link that I have specified and then set it as the environment.

## CLI Version
cf version 6.36.2+18ceab10f.2018-05-16

## Platform & Shell Details

Windows 10 64-bit

## Additional info
dflow-server is the name of my dataflow server on PCF

**Comment by tjvman** [comment]
I think your issue stems from the `=` in your command, which shouldn't be needed; the way the command is written now would be interpreted as 4 arguments by the CLI, instead of 3.

The command should look like:
`cf set-env dflow-server SPRING_APPLICATION_JSON  '{"maven": { "remote-repositories": { "repo": { "url": "https://repo.spring.io/libs-release" } } } }'`

**Comment by kvkadakia** [comment]
Hello,

Thanks for the update. I tried it without the = sign as well but it gives me the same error.

Then I found this on another website where they did cf set-env dataflow-server MAVEN_REMOTE_REPOSITORIES_REPO1_URL https://repo.spring.io/libs-snapshot

This command worked out, so I think it's some issue with the SCDF tutorial.

**Comment by abbyachau** [comment]
Thanks @kvkadakia for updating us, we can reach out to SCDF about your feedback. Closing this issue.

**Comment by csterwa** [comment]
I work on the Spring team. @kvkadakia could you point to where you saw the JSON without a `'` in the Spring Cloud Data Flow OSS docs so we can update? I was not able to find it when searching. Thank you.

**Comment by kvkadakia** [comment]
Hi @csterwa this is the link where I found it https://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/current-SNAPSHOT/reference/htmlsingle/ 

The command that I have mentioned above is given in section 2.2. Deploying using environment variables is incorrect as it does not work.

It should be updated to cf set-env dataflow-server MAVEN_REMOTE_REPOSITORIES_REPO1_URL https://repo.spring.io/libs-snapshot
