### ISSUE TITLE
Stream deployment in PCF

### ISSUE THREAD

**Issue by kvkadakia** [cloudfoundry/cli#1428]
## Command
Deploying a stream on PCF:  stream create --name time-to-log --definition 'time-source | time-processor | time-sink'

## What occurred
I have deployed source processor and sink applications on PCF(they work perfectly in local machine). So I am able to register the apps but when I register and run the stream using : stream create --name time-to-log --definition 'time-source | time-processor | time-sink'

I get the following error: File /home/vcap/tmp/spring-cloud-deployer4056042586536102709/5be9d0378f0da774c5e6dcf52a7bd5f337fb7e93 must exist 

And the stream does not deploy

## What you expected to occur
The stream should deploy 

## CC API Endpoint Version
https://api.run.pivotal.io

## Any other relevant information

I don't understand why is the cloud foundry server trying to create logs in a local machine path. Seems like a bug to me

**Comment by abbyachau** [comment]
Hey @kvkadakia thanks closing this issue as this is a Spring Cloud Services CLI Plugin question -  open a github issue here: https://github.com/pivotal-cf/spring-cloud-services-cli-plugin.
