### ISSUE TITLE
Help is missing rename and delete

### ISSUE THREAD

**Issue by adamsiemion** [cloudfoundry/cli#1429]
## Command

`cf help`

## What occurred

`help` output  does not mentioned the `rename` and `delete` command, which is available in CLI.

## What you expected to occur

The `rename` and `delete` command should be available in the `Application lifecycle` section of `help` output.

## CLI Version

6.37.0+a40009753.2018-05-25

## CC API Endpoint Version

2.116.0

## CF Trace

N/A

## Platform & Shell Details

Mac OS X 10.13.5 iTerm

## Any other relevant information

N/A

**Comment by abbyachau** [comment]
Hey @adamsiemion thanks for creating this issue. If you `cf h -a ` you'll see the `delete` and `rename` help text:
```
APPS:
   apps                                   List all apps in the target space
   app                                    Display health and status for an app

   push                                   Push a new app or sync changes to an existing app
   scale                                  Change or view the instance count, disk space limit, and memory limit for an app
   delete                                 Delete an app
   rename                                 Rename an app
```

**Comment by adamsiemion** [comment]
@abbyachau thanks for the reply, I did not know the `-a` option, maybe `help` could return one more line like `-a to see all the available commands`?

**Comment by abbyachau** [comment]
Hey @adamsiemion we do return that text - when you `cf --help`, at the end of the help text, we output `Use 'cf help -a' to see all commands.` I'm closing this issue as resolved but please do not hesitate to create a new issue or reopen if you have further feedback/comments. Thanks.
