### ISSUE TITLE
Feature Request: Add support for binding-name to manifest

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cli#1438]
## Command

cf push -f manifest.yml

## What occurred

Application was pushed and services bound without any binding-name.

## What you expected to occur

Expected the cli to know about binding-names and provide a way for me to specify those so they'd get setup when I deployed with my manifest.

## CLI Version

6.38.0+7ddf0aadd.2018-08-07

## CC API Endpoint Version

2.116.0

## Any other relevant information

I know work is ongoing to move manifest processing to the CC.  Not sure if it would be best to surface this feature request with them or not so I started here.

**Comment by abbyachau** [comment]
cc @zrob

**Comment by zrob** [comment]
i've created this story to track this request for server side manifests https://www.pivotaltracker.com/story/show/159749565

**Comment by youngm** [comment]
Thanks @zrob I'll just follow the tracker story,

**Comment by kw-s** [comment]
Why has this issue been closed? When I look at other tickets, they get closed after beeing implemented or rejected, but none of this happend to this issue. Also, the tracker story 159745140 looks pretty abandoned to me. 

I am afraid this feature request is not tracked anymore. Or is it already possible to define named service bindings within the manifest? The docs does not mention anything like that (https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#services-block).

**Comment by youngm** [comment]
Reopening to try and get some attention.

**Comment by bwasmith** [comment]
Hello @kw-s and @youngm , thank you for reopening this PR. 

There has been work done since then to process server side manifests on the API side. I believe you can access through v6's `v3-push` or our v7 beta's `push` commands. 

I have notified our Services API team to see if they can answer your specific questions about whether it is possible to specify binding-name via manifest: 
https://cloudfoundry.slack.com/archives/CJ8UUQWCU/p1579038105003000

Hope this helps!
Brendan and @JenGoldstrich

**Comment by FelisiaM** [comment]
> Is it possible to specify binding-name via manifest?

No, not yet. We should look into implementing it on v3.

**Comment by FelisiaM** [comment]
Hi all!

We are happy to let you know that binding name is now supported when creating a binding on push. This is available on v3 in the latest [CAPI release  v1.106.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.106.0). 

To assign a binding name when creating a binding the app manifest should look like this:
```
version: 1
applications:
- name: app1
  services:
  - name: my-service-instance
    binding_name: my-binding
    parameters:
      key1: value1
      key2: value2
```

I will now close this issue. 
Let us know if you have any more feedback.

Thanks,
Felisia

**Comment by IkaroSales** [comment]
`yaml: unmarshal errors:
  line 80: cannot unmarshal !!map into string`

**Comment by JenGoldstrich** [comment]
@IkaroSales we'll need a bit more information to diagnose your problem, I suggest opening another github issue, and listing what versions of the cf CLI and CAPI you are using and then linking to this issue in your new issue.
