### ISSUE TITLE
Feature Request: cf cli to return a different status code whenever network errors occur

### ISSUE THREAD

**Issue by ishustava** [cloudfoundry/cli#1439]
## Description 
CF Release Integration team is looking to improve stability of CF Acceptance Tests (aka CATs). 

Sometimes we see that commands fail due to network problems. Usually they are commands that are performing a `POST` request under the hood, and we know that CF CLI does not retry those requests.
It does make sense to retry them in CATs though to make the test suite more resilient to network errors. 

It would be great if CF CLI returned a different exit code in such a case, so that we can easily detect them and retry.

## Open Questions:
- What is an appropriate exit code for network errors? Is there a convention for this already?

**Comment by abbyachau** [comment]
hey @ishustava thanks for creating this. i have a story written for this request already: https://www.pivotaltracker.com/story/show/159828965. Let me know if you have any questions, I plan on reviewing this story in IPM today.

**Comment by abbyachau** [comment]
Hey @ishustava closing this issue, please follow https://www.pivotaltracker.com/story/show/159828965 to track progress on this request. Thanks.
