### ISSUE TITLE
Homebrew formula is broken

### ISSUE THREAD

**Issue by aaronjwood** [cloudfoundry/cli#1443]
```
brew install cf-cli
==> Installing cf-cli from cloudfoundry/tap
==> Downloading https://packages.cloudfoundry.org/stable?release=macosx64-binary&version=6.38.0&source=homebrew
Already downloaded: /Users/woodaaron/Library/Caches/Homebrew/cf-cli--6.38.0
Error: No such file or directory - cf
```

Upgrading from an already existing install also hits the same error.

**Comment by abbyachau** [comment]
Hi @aaronjwood thanks, closing this issue as a dupe. Please see: https://www.pivotaltracker.com/story/show/159645341. Thanks and let us know if you have any questions.

**Comment by aaronjwood** [comment]
Yup, all good now. Thanks!
