### ISSUE TITLE
CF appName and url error

### ISSUE THREAD

**Issue by rahuldeepattri** [cloudfoundry/cli#1448]
## Command

cf push

with manifestfile as

    host: root_123456
    instance: 1
    name: root
    path: "./root.war"

## What occurred

It created a url for me -> root_123456.abc.abc.abc.abc.com

And in CloudFoundary docs we have -> Note: CF ​allows​ app names, but not app URLs, to include underscores. CF converts underscores to hyphens when setting a default app URL from an app name. 

https://docs.cloudfoundry.org/devguide/deploy-apps/deploy-app.html

## What you expected to occur
Correct url name like -> root-123456.abc.abc.abc.abc.com

## CLI Version

cf.exe version 6.38.0+7ddf0aadd.2018-08-07

## CC API Endpoint Version

api version:    2.115.0
## Any other relevant information
Possible duplicate of #1326  #1185

**Comment by XenoPhex** [comment]
Hey there @rahuldeepattri,
When CF generates a route from the name of an app, it will automatically substitute use hyphens in place of underscores. However, the manifest you provided specifies a `host`, not just an app name. Host names are assumed to be correct when explicitly provided, so no modifications occur.

We apologize if the documentation is ambiguous, we'll try and correct it for the future.

**Comment by abbyachau** [comment]
Hi @rahuldeepattri thanks again for creating this issue. I'm closing this as resolved but please do not hesitate to reopen/create a new issue if you have any questions/additional feedback.

**Comment by rahuldeepattri** [comment]
@abbyachau okay and thanks :)
