### ISSUE TITLE
cf curl shoud add trailing new line to the output

### ISSUE THREAD

**Issue by giner** [cloudfoundry/cli#1450]
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
The output of `cf curl ... > /some/file` and `cf curl ... --output /some/file` differs.

**Expected behavior**
I would expect the the output of both `cf curl ... > /some/file` and `cf curl ... --output /some/file` being the same. While it is not a big problem for json (still can be confusing though) this is a problem when you download binary blobs (such as app bits or droplet).

**To Reproduce**
```
cf curl /v2/apps/$(cf app myapp --guid)/droplet/download --output /tmp/droplet.out.tgz
cf curl /v2/apps/$(cf app myapp --guid)/droplet/download > /tmp/droplet.redir.tgz
$ diff -u <(xxd /tmp/droplet.out.tgz) <(xxd /tmp/droplet.redir.tgz)
--- /dev/fd/63	2018-08-31 10:21:24.355472752 +0900
+++ /dev/fd/62	2018-08-31 10:21:24.355472752 +0900
@@ -186977,4 +186977,4 @@
 02da600: 2be3 95e6 f565 dcef fff9 d2e4 7fe9 ff95  +....e..........
 02da610: 8ff7 b556 ab72 d5ff 88fe 03c9 fa0f 4208  ...V.r........B.
 02da620: 2184 1042 0821 8490 42d8 03b9 48f6 6d00  !..B.!..B...H.m.
-02da630: 4060 00                                  @`.
+02da630: 4060 000a                                @`..
```
```
$ gunzip -vt /tmp/droplet.out.tgz
/tmp/droplet.out.tgz:	 OK

$ gunzip -vt /tmp/droplet.redir.tgz 
/tmp/droplet.redir.tgz:	
gzip: /tmp/droplet.redir.tgz: unexpected end of file
```

```
$ cf -v
cf version 6.38.0+7ddf0aadd.2018-08-07
```

**Comment by Ema93sh** [comment]
@giner Thanks for reporting this. We can see how it would be confusing, since regular `curl` does not do append a new line. We are in the process of improving and refactoring the `cf curl` command, and will try to incorporate a fix to this in those changes.

As an aside, in situations where `cf curl` is missing some functionality that ordinary curl has, we have had some luck using `curl -H "Authorization: $(cf oauth-token)" ...`.

**Comment by willmurphyscode** [comment]
@giner We are not planning to make this change right now. 

If you need to pipe binary output, you can use`curl -H "Authorization: $(cf oauth-token)"...`, and if you are saving a file, the `cf curl --output` flag is available.

There are two reasons for this decision. First, we don't want to prioritize an issue when easy workarounds are readily available.

Second, users with default PS1 who want to manually inspect a JSON document returned from CC API, which is the primary use case of `cf curl`, will be annoyed to see the last `}` of the JSON run into their prompt, as in:

```
cloudfoundry@host:~$cf curl /v2/info
{
   "name": "",
   "build": "",
   ....
}cloudfoundry@host:~$
```

While I agree being able to pipe binary files directly would be cool, users who wish to do that can use regular `curl` without much difficulty.

We are closing the issue for now. In general, `cf curl` is not meant to provide feature parity with `curl`, but rather just an easier-to-use command for common use cases. Feel free to open new issues in the future. Thanks!
