### ISSUE TITLE
Issues running integration tests on Go 1.11

### ISSUE THREAD

**Issue by henryaj** [cloudfoundry/cli#1454]
We think there's been a change to the formatting directives in Go 1.11 which is causing integration tests to fail when we run them. Specifically, we get errors like this:

`integration/isolated/restage_command_test.go:198: Say format %.*o reads arg #1, but call has 0 args`

which refers to this test:

```go
Eventually(session).Should(Say("#1\\s+(running|starting)\\s+\\d{4}-[01]\\d-[0-3]\\dT[0-2][0-9]:[0-5]\\d:[0-5]\\dZ\\s+\\d+\\.\\d+%.*of 128M.*of 128M"))
```

It seems like `%.*o` is some kind of new formatting directive in Go 1.11. We've been unable to fix but wanted to flag it up.

Thanks,

Henry and Luis (@lurraca)

---

**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Integration tests

**What happened**
When running the integration tests on Go 1.11, we see compiler errors.

**Expected behavior**
We expected the tests to pass :B

**To Reproduce**
Run e.g. `ginkgo -r integration`

**Provide more context**
CLI at master, Go 1.11

**Comment by abbyachau** [comment]
Hey @henryaj @lurraca we haven't updated the CLI to Golang 1.11.1 yet. We are currently on Golang `1.10.3`, see our [release notes](https://github.com/cloudfoundry/cli/releases). Could you please run the integration tests again with that version of Golang and let us know if you run into any issues. I'm closing this issue but please create a new issue if you run into any problems, thanks.
