### ISSUE TITLE
Brew search returns misleading suggestion to tap pivotal/tap

### ISSUE THREAD

**Issue by ab-pivot** [cloudfoundry/cli#1455]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
As a brand new CF user I'm trying to find and install CLI on my mac using homebrew

**What happened**
I've got a message suggesting to `brew tap pivotal/tap`

**Expected behavior**
The message suggests me to `brew tap cloudfoundry/tap`

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `brew search  cloudfoundry-cli`
2. See
```
brew search cloudfoundry-cli
It was migrated from homebrew/core to pivotal/tap.
You can access it again by running:
  brew tap pivotal/tap
And then you can install it by running:
  brew install cloudfoundry-cli
```

**Provide more context**
- Mac OS X 10.13.6 iTerm

**Comment by abbyachau** [comment]
Hi @ab-pivot  you can run `$ brew tap cloudfoundry/tap` then `brew install cf-cli`; see [here](https://docs.run.pivotal.io/cf-cli/install-go-cli.html). If you want to search by cloud foundry, you can run `brew search cloudfoundry`.

**Comment by abbyachau** [comment]
Reopening this so that the CLI eng team can review, thanks @ab-pivot

**Comment by abbyachau** [comment]
Hi @ab-pivot thank you for creating this - this issue's been fixed, please let us know if you have any feedback. I'm closing this issue as fixed but do not hesitate to get in touch if you have any questions.
