### ISSUE TITLE
CLI often passes `inline-relations-depth` query param to CAPI, which is deprecated

### ISSUE THREAD

**Issue by willmurphyscode** [cloudfoundry/cli#1456]
It looks like we use the query parameter `inline-relations-depth` in a [number of places](https://github.com/cloudfoundry/cli/search?q=%22inline-relations-depth%22&unscoped_q=%22inline-relations-depth%22). According the docs on at least the [spaces endpoint](https://apidocs.cloudfoundry.org/199/spaces/list_all_spaces.html) this parameter is deprecated, and I believe it is generally deprecated.

We should make chores to find out whether we depend on this parameter's behavior, and to remove use of it.

**Comment by abbyachau** [comment]
hey @willmurphyscode thanks for creating this issue. something also to perhaps consider for vat. cc @zrob @mkenyon

**Comment by abbyachau** [comment]
Hi @willmurphyscode could you please let us know if you want to keep this issue around? I think this has been removed from V3 but is not actionable for V6/V2. Thanks.

**Comment by willmurphyscode** [comment]
@abbyachau You are correct. This issue will be automatically resolved by the switch to V3, and is not actionable otherwise. Thanks for following up!
