### ISSUE TITLE
Blockchain Samples 

### ISSUE THREAD

**Issue by Erikadue** [cloudfoundry/cli#1457]
- I tried to deploy the delivery Pipeline in Perishable Goods Clause but no succsess, please i need a help. 

+ cf create-service ibm-blockchain-5-prod ibm-blockchain-plan-v1-ga1-starter-prod Blockchain Duisburg
FAILED
Incorrect Usage. Requires service, service plan, service instance as arguments

NAME:
   create-service - Create a service instance

USAGE:
   cf create-service SERVICE PLAN SERVICE_INSTANCE [-c PARAMETERS_AS_JSON] [-t TAGS]

   Optionally provide service-specific configuration parameters in a valid JSON object in-line:

   cf create-service SERVICE PLAN SERVICE_INSTANCE -c '{"name":"value","name":"value"}'

   Optionally provide a file containing service-specific configuration parameters in a valid JSON object.
   The path to the parameters file can be an absolute or relative path to a file:

   cf create-service SERVICE PLAN SERVICE_INSTANCE -c PATH_TO_FILE

   Example of valid JSON object:
   {
      "cluster_nodes": {
         "count": 5,
         "memory_mb": 1024
      }
   }

TIP:
   Use 'cf create-user-provided-service' to make user-provided services available to CF apps

EXAMPLES:
   Linux/Mac:
      cf create-service db-service silver mydb -c '{"ram_gb":4}'
   
   Windows Command Line:
      cf create-service db-service silver mydb -c "{\"ram_gb\":4}"
   
   Windows PowerShell:
      cf create-service db-service silver mydb -c '{\"ram_gb\":4}'
   
   cf create-service db-service silver mydb -c ~/workspace/tmp/instance_config.json
   
   cf create-service db-service silver mydb -t "list, of, tags"

ALIAS:
   cs

OPTIONS:
   -c      Valid JSON object containing service-specific configuration parameters, provided either in-line or in a file. For a list of supported configuration parameters, see documentation for the particular service offering.
   -t      User provided tags

Finished: FAILED

**Comment by abbyachau** [comment]
Hi @Erikadue we can't triage this issue based on the information you've given us. We also would prefer these types of questions (help versus reporting an actual issue) in our slack channel rather than in github issues. From a quick look, it looks like you may be missing one of the required arguments. I'm closing this issue based on the aforementioned points, please reach out to us or the SAPI team at #cli or #sapi on Cloud Foundry Slack.
