### ISSUE TITLE
GPG Key for Debian Package Install doesn't match

### ISSUE THREAD

**Issue by unamuno** [cloudfoundry/cli#1459]
- [ ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
**It's a pre installation problem**
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
I tried to install the cli but the GPG Key doesn't match according to apt:

```
# wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
OK
# echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
deb https://packages.cloudfoundry.org/debian stable main

# apt-get update
Hit:1 http://de.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://de.archive.ubuntu.com/ubuntu bionic-updates InRelease        
Hit:3 http://de.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                      
Hit:4 http://de.archive.ubuntu.com/ubuntu bionic-security InRelease                                                       
Get:5 https://cf-cli-debian-repo.s3.amazonaws.com stable InRelease [2,665 B]                                              
Err:5 https://cf-cli-debian-repo.s3.amazonaws.com stable InRelease
  The following signatures were invalid: EXPKEYSIG 5733FEC050C212B6 CF CLI Team <cf-cli-eng@pivotal.io>
Reading package lists... Done
W: GPG error: https://cf-cli-debian-repo.s3.amazonaws.com stable InRelease: The following signatures were invalid: EXPKEYSIG 5733FEC050C212B6 CF CLI Team <cf-cli-eng@pivotal.io>
E: The repository 'https://packages.cloudfoundry.org/debian stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

**Expected behavior**
A valid key that matches the repo.

**To Reproduce**
Redo the  commands above.

**Provide more context**
- Ubuntu 18.04 LTS, zsh

**Comment by BM201809** [comment]
The key is expired yesterday
pub   rsa4096 2016-09-12 [SC] [expired: 2018-09-12]
      56EF F915 1B51 ACD9 A211  A5A3 5733 FEC0 50C2 12B6
uid           [ expired] CF CLI Team <cf-cli-eng@pivotal.io>

**Comment by abbyachau** [comment]
Hi thanks all @unamuno this is a [known issue](https://github.com/cloudfoundry/cli/releases/tag/v6.39.0). We have a [story](https://www.pivotaltracker.com/story/show/160470508) to update the key; please follow the aforementioned story for updates to this issue.

**Comment by tjvman** [comment]
This has been fixed for the Debian artifacts. Please update your copy of our public GPG key and retry the installation. If you're uncertain of what exactly needs to be done, the [Debian and Ubuntu based Linux distributions section](https://github.com/cloudfoundry/cli#downloads) of our main README has the needed commands.

**Comment by rstumpe** [comment]
Hi, I tried this and it did not work:
 # ...first add the Cloud Foundry Foundation public key and package repository to your system
wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
# ...then, update your local package index, then finally install the cf CLI
sudo apt-get update

sudo apt-get update thwows an error that the key 6B05F25D762E315 is not found.

"NO_PUBKEY 6B05F25D762E315"
