### ISSUE TITLE
Provide github release notes in parsable way

### ISSUE THREAD

**Issue by thardeck** [cloudfoundry/cli#1469]
We have a Concourse pipeline to package cf-cli and bosh-cli automatically whenever there is a new version.

For [bosh-cli](https://github.com/cloudfoundry/bosh-cli/releases) it works great but for `cf` the release notes are huge, with binary links and even the bottom part about the changes always differ.

So it would be great if the changelog can be more consistent or in the best case similar to [bosh-cli](https://github.com/cloudfoundry/bosh-cli/releases).

Thanks in advance.

**Comment by abbyachau** [comment]
Hi @thardeck thank you for creating this issue. It would help us understand your issue if you could please use one of our [templates](https://github.com/cloudfoundry/cli/issues/new/choose) which asks for additional information. I'm unable to gauge why the change log itself is an issue for you, for example

**Comment by thardeck** [comment]
Thanks for your quick reply. I thought since this is not a software feature request I can skip the complete template but here it is:

**What's the user value of this feature request?**
openSUSE gets and automatically generated RPM each time there is a new `cf` release with a proper changelog so it gets accepted when submitted to the distribution.

**Who is the functionality for?**
The Concourse pipeline to generate rpms from each new `cf` github release.

**How often will this functionality be used by the user?**
Every time there is new `cf` release.

**Who else is affected by the change?**
People who are used to the current changelog format might miss some information.

**Is your feature request related to a problem? Please describe.**
At moment we create an rpm package from each new `cf` release automatically but are unable to add an automatically generated changelog because the github release notes are not really parsable by a non human, at least not without much effort.

**Describe the solution you'd like**
Format the github release notes similar to [https://github.com/cloudfoundry/bosh-cli/releases](bosh-cli).

**Describe alternatives you've considered**
* Continue to not provide a changelog in our rpm, but then it does not get accepted anymore.
* Manually extract the changelog each time and reduce it so it can be part of an rpm changelog.

**Comment by tjvman** [comment]
@thardeck I'm curious as to why you're repackaging the CLI into an RPM as opposed to using the RPMs that are published as part of each release.

**Comment by abbyachau** [comment]
@thardeck we've updated the release notes for the [cf cli bosh release](https://github.com/bosh-packages/cf-cli-release/releases). Let us know if you have any feedback. Thanks.

**Comment by thardeck** [comment]
@tjvman for our Linux distribution openSUSE we have to build packages from source.

@abbyachau for rpm packaging only the cli release is relevant. From my perspective the easiest to parse and even read was something like https://github.com/cloudfoundry/bosh-cli/releases/tag/v4.0.1 or even https://github.com/cloudfoundry/bosh-cli/releases/tag/v5.2.1 although of course not as detailed as the newer changelogs .

**Comment by abbyachau** [comment]
Hi @thardeck made changes to the [release notes](https://github.com/bosh-packages/cf-cli-release/releases/tag/v1.10.0), please let us know if that works. Thanks.

**Comment by thardeck** [comment]
@abbyachau Thanks for your response and help.

I should have been more clear. The only repos we monitor are https://github.com/cloudfoundry/cli and https://github.com/cloudfoundry/bosh-cli.
If there is a new github release in one of them we create a new rpm and also try to update the changelog.

So only the changelog of these repos are relevant for us. If the changelog should be the same of course we can extend the pipeline to parse the bosh release repo changelog but of course it would be better to only have one github release resource per release.

Thanks again for your help.

**Comment by abbyachau** [comment]
Hey @thardeck, thanks. We don't plan on changing the format of https://github.com/cloudfoundry/cli unfortunately. We may remove the plugin updates in the future as we are uncertain how helpful those are for our users but even so, it doesn't sound like that would help. We were open to changing it in the CF CLI bosh release but would like to retain the formatting for the main repo. If there's anything else we can do to help/any other ideas, please let us know.

**Comment by thardeck** [comment]
No problem, I just wanted to ask. Thanks for helping.

**Comment by abbyachau** [comment]
Thanks @thardeck - if you can think of alternative solution at some point, then please don't hesitate to create a new ticket.

**Comment by thardeck** [comment]
@abbyachau Thanks. I have adapted our script to look for Markdown headings starting with `Bug Fix`, `Feature`,  or `Enhancement`.
If you will continue to provide the changelog in the current format it should be ok.
