### ISSUE TITLE
command `delete` not listed in usage report

### ISSUE THREAD

**Issue by poy** [cloudfoundry/cli#1471]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ ] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**

`cf help` does not list the `delete` command.

**What happened**

`cf help` does not describe or list the `delete` command.

**Expected behavior**
I expected to see the `delete` command in the `Application lifecycle` section.

**To Reproduce**
`$ cf help`

**Provide more context**
Linux Machine
```
$ cf version
cf version 6.39.1+efdd631d2.2018-09-18
```

**Comment by XenoPhex** [comment]
I've gotten similar feedback from several labs pivots as well. I think we should add this to the main help.

**Comment by abbyachau** [comment]
Hi @poy many thanks for this. We have a pull request to make this change, I'm closing this issue - please track progress on the update [here](https://github.com/cloudfoundry/cli/pull/1487).
