### ISSUE TITLE
Extract a CC API V3 golang client used by CLI and CF ecosystem

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#1481]
This issue suggests for extraction of a library out of the CF CLI codebase for V3 api mentionned into [cf-dev@ thread](https://lists.cloudfoundry.org/g/cf-dev/topic/cc_api_v3_and_cli_v7/26659245?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,26659245), similar to the [cf-java-client](https://github.com/cloudfoundry/cf-java-client) with two levels of apis:
- a low-level api, mapping to the [cloudfoundry V3 REST APIs](http://v3-apidocs.cloudfoundry.org/)
- a high-level api, mapping to the CF CLI concepts

CF CLI would use the high level api.

**What's the user value of this feature request?**

* A consistent, quality experience for CF users when using CF CLI and other tools in the ecosystem written in go-lang
* A way to speed up CC API V3 and sunset the CC API V2 earlier
* A way to reduce/optimize maintenance effort for the CLI team by sharing work with the rest of the CF golang community

**Who is the functionality for?**

* CLI team
* Cf go-lang eco system
   * https://github.com/mevansam/terraform-provider-cf : provides programmatic UI to provision, CF and apps. See related https://github.com/mevansam/terraform-provider-cf/issues/56
   * https://github.com/cloudfoundry-incubator/stratos: web ui
   * current users of https://github.com/cloudfoundry-community/go-cfclient see related https://github.com/cloudfoundry-community/go-cfclient/issues/151

**Comment by gberche-orange** [comment]
Maybe something @christineyyeh could consider as part of 2019 CAPI [UX survey](https://goo.gl/forms/A01pcE5Y7UFxsYNf2)

**Comment by gberche-orange** [comment]
An example of a pivotal product that could leverage a standard cf golang client, instead of building its own:
https://github.com/pivotal-cf/on-demand-service-broker/blob/master/cf/client.go
https://github.com/pivotal-cf/on-demand-service-broker/tree/master/service

**Comment by abbyachau** [comment]
cc @ssisil @tcdowney
