### ISSUE TITLE
Unable to create spaces in 6.40.0 when user exists in multiple origins

### ISSUE THREAD

**Issue by teancom** [cloudfoundry/cli#1483]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [X] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
When running cf-rabbitmq-smoke-tests, it automatically creates a space. With previous versions of the cf-cli, tested up to 6.39.1, it works great. When using 6.40.0, it fails with the following error:

```
Creating space rmq-smoke-tests-1-SPACE-0ae293d643719c8f in org system as admin...
OK
Assigning role SpaceManager to user admin in org system / space rmq-smoke-tests-1-SPACE-0ae293d643719c8f as admin...
The user exists in multiple origins. Specify an origin for the requested user from: 'uaa', 'ldap'
```

**Expected behavior**
I would expect that it would continue to allow us to create orgs and spaces as the admin user, even though we have both an admin user in the `uaa` as well as in our Active Directory LDAP tree (which is out of our control).

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Have a PCF foundation with two or more origins.
2. Duplicate a user between two origins.
3. Try to create a space as that user, with cf-cli 6.40.0.

**Comment by abbyachau** [comment]
Hi @teancom could you give more details on the exact commands you are running (please flesh out the steps to reproduce your issue)? Thanks.

**Comment by teancom** [comment]
Sure! It looks like the command being run is:
```
$ cf create-space -o system rmq-smoke-tests-1-SPACE-884de97c639a73fe
```
These are the standard `cf-rabbitmq-smoke-tests` that come from https://github.com/pivotal-cf/cf-rabbitmq-smoke-tests-release.

Other than that, the only thing necessary should be having two users of the same name, in two different auth sources (origins).

**Comment by abbyachau** [comment]
Hi @teancom just want to confirm that you are not logged in with client credentials?

**Comment by teancom** [comment]
I believe I am, if by "client credentials" you mean "using a username and password". Here is a full manual recreation:
```
$ uname -a
Darwin My-Laptop 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin
$ cf --version
cf version 6.40.0+07673feb9.2018-10-08
$ cf login -a api.cf.XXXXXX.com --skip-ssl-validation
API endpoint: api.cf.sXXXXXXX.com

Username> admin

Password> <INSERT PASSWORD RETRIEVED FROM VAULT FOR THE ELASTIC-RUNTIME/UAA.ADMIN_CREDENTIALS>
Authenticating...
OK

Select an org (or press enter to skip):
1. exampleorg
2. system

Org> 2
Targeted org system

Select a space (or press enter to skip):
1. autoscaling
2. DEV
3. system

Space> 3
Targeted space system



API endpoint:   https://api.cf.XXXXXX.com (API version: 2.112.0)
User:           admin
Org:            system
Space:          system
$ cf create-space test-creating-space
Creating space test-creating-space in org system as admin...
OK
Assigning role SpaceManager to user admin in org system / space test-creating-space as admin...
The user exists in multiple origins. Specify an origin for the requested user from: 'uaa', 'ldap'
FAILED
```
* note, I have snipped a bunch of our orgs and spaces from the output for being irrelevant.

This is using *PAS v2.2.8*. Interestingly, as I went to recreate this bug, I was **UNABLE** to, using *PAS v2.2.2.*, but with the same version of the `cf-cli` (6.40.0). As I mentioned in the original report, downgrading the `cli` to 6.39.0 makes it work with both versions.

**Comment by abbyachau** [comment]
Hi @teancom thanks, can you pls confirm -  the aforementioned workflow:
 - PAS v2.2.8 and CF CLI 6.40.0 - DOES NOT WORK
- PAS v2.2.2 and CF CLI 6.40.0 - WORKS
- - PAS v2.2.2 and - PAS v2.2.8 and CF CLI 6.39.0 - WORKS

**Comment by teancom** [comment]
Correct, that is exactly right.

**Comment by abbyachau** [comment]
Hi @teancom I'm closing this issue but please feel free to reach out if you have any questions. To reiterate, reaching out to support@pivotal.io would be the best avenue if you are a PCF customer or review https://content.pivotal.io/support. Thanks.
