### ISSUE TITLE
Connection refused cf -api - AWS

### ISSUE THREAD

**Issue by xavier007009** [cloudfoundry/cli#1484]
I have deployed cf on to bosh,--trying to see if cf api works atleast rest of the components are in deployed

**_ERROR_ START**

ubuntu@ip-10-0-0-173:~/bosh$ cf api 34.239.203.121
Setting api endpoint to 34.239.203.121
Request error: Get https://34.239.203.121/v2/info: dial tcp 34.239.203.121:443: connect: connection refused
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
**_ERROR_ END**

***deployed components***
ubuntu@ip-10-0-0-173:~/bosh$ bosh -e vbox deployments
Using environment '34.239.203.121' as client 'admin'

Name  Release(s)                   Stemcell(s)                                        Team(s)  Cloud Config
cf    binary-buildpack/1.0.27      bosh-warden-boshlite-ubuntu-xenial-go_agent/97.28  -        latest
      bosh-dns-aliases/0.0.3
      bpm/0.13.0
      capi/1.70.0
      cf-cli/1.9.0
      cf-mysql/36.15.0
      cf-networking/2.17.0
      cf-smoke-tests/40.0.13
      cf-syslog-drain/7.1
      cflinuxfs2/1.242.0
      credhub/2.1.1
      diego/2.19.0
      dotnet-core-buildpack/2.1.5
      garden-runc/1.16.7
      go-buildpack/1.8.28
      java-buildpack/4.16.1
      log-cache/2.0.0
      loggregator/104.0
      loggregator-agent/2.3
      nats/26
      nodejs-buildpack/1.6.32
      php-buildpack/4.3.61
      python-buildpack/1.6.21
      routing/0.182.0
      ruby-buildpack/1.7.24
      silk/2.17.0
      staticfile-buildpack/1.4.32
      statsd-injector/1.4.0
      uaa/62.0

1 deployments

**Comment by henryaj** [comment]
Hi @xavier007009. This isn't really a CLI issue per se – you might have more luck posting on the [CF mailing list](https://lists.cloudfoundry.org/g/announce).

In terms of your issue: it looks like your BOSH Director and your CF API address are the same, so you must be running BOSH Lite. You won't be able to connect to the CF API using an IP – you need to hit a fully-qualified domain name. [This guide](https://medium.com/@nikhiljee/deploying-bosh-lite-v2-and-cloud-foundry-on-aws-ab02ef19693b) describes using sslip.io to get an FQDN from the Director's elastic IP.
