### ISSUE TITLE
Non-interactive password change

### ISSUE THREAD

**Issue by spookyboo** [cloudfoundry/cli#1485]
It is currently not possible to change the password non-interactive (cf passwd). I've tried things in bash to pipe the old password and new password (2x), but failed.
We use an Azure DevOps CI/CD pipeline to deploy an application to production, but to make it more secure, we want to use a generated password (using CyberArk), that nobody is allowed to see. The idea is that before the actual push is done, the old password is replaced by the pipeline. By frequently changing the password an additional security measure is applied, so in case someone is able to retrieve the password, it may have become invalid. 
We don't have any management authorization, so we are stick to using the CF CLI.

The proposal is to optionally add arguments to cf passwd
**cf passwd [old_password new_password]**

The exact values are masked in our pipeline log, so no one is able to view them

**Comment by metskem** [comment]
Will this ever be fixed?
Or is a workaround available?
