### ISSUE TITLE
NodeJS not installed with a custom buildpack

### ISSUE THREAD

**Issue by johnwen84** [cloudfoundry/cli#1486]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [ ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x ] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
I need to install some extra libraries for puppeteer to work with my NodeJS application. I created a custom buildpack in attempt to accomplish that. I added this to my yaml,
  buildpacks:
    - https://github.com/johnwen84/bluemix-puppeteer-buildpack
When I pushed the app I see this in the console:
    https://github.com/cloudfoundry/nodejs-buildpack
    https://github.com/johnwen84/bluemix-puppeteer-buildpack
with the line for nodejs-buildpack in red. The CLI obviously detected that this is a NodeJS app, but not sure what it means when the nodejs-buildpack is in red. See results below.

**What happened**
My buildpack runs successfully, but NodeJS is not installed. The app fails with a npm not found error (The app command is npm start)

**Expected behavior**
I expected that my app runs with my buildpack installing the libraries correctly

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `cf ...`
2. Bind a service `cf bind-service`
3. See error

**I also tried**
I tried to include this in the yaml file:
  buildpacks:
    - https://github.com/johnwen84/bluemix-puppeteer-buildpack
    - https://github.com/cloudfoundry/nodejs-buildpack
NodeJS will be installed but my buildpack will not run. I can see the supply script being called but somehow it didn't call the finalize script which installs the libraries

If I put this in the yaml file,
  buildpacks:
    - https://github.com/cloudfoundry/nodejs-buildpack
    - https://github.com/johnwen84/bluemix-puppeteer-buildpack
My buildpack will run and NodeJS will be installed, but the app still fails with an "npm not found" error.

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm)
   Windows 10
- version of the CLI you are running
   6.39
- version of the CC API Release you are on

Note: As of January 2018, we no longer support API versions older than 2.69.0/3.4.0 (CF Release: 251 / CAPI Release: 1.15.0)

**Comment by johnwen84** [comment]
I have figured this out. I think I can do,

buildpacks:
- https://github.com/johnwen84/bluemix-puppeteer-buildpack
- https://github.com/cloudfoundry/nodejs-buildpack
and include the script that installs the libraries in supply instead of finalize in my buildpack.
My question now is that is it necessary to explicitly include nodejs-buildpack here? Or should the CLI automatically include it?

**Comment by abbyachau** [comment]
Hi @johnwen84 please if you could hop on to Slack at Cloud Foundry either at #cli or #buildpacks for these types of questions - that would be helpful. After trying with the aforementioned solution, please pop by either of those channels should you require additional help. Thanks.
