### ISSUE TITLE
`refresh-token` call to avoid client recreation

### ISSUE THREAD

**Issue by johannaratliff** [cloudfoundry/cli#1488]
**What's the user value of this feature request?**
As a cli plugin developer who has client credentials, I am currently unable to make the CAPI `refresh_token` call through the cli. I can get a new token with `cf oauth-token`, but if I want a command to run longer than the default 10m, I need to make `refresh-token` calls. 

**Who is the functionality for?**
Cli plugin developers.

**How often will this functionality be used by the user?**
On any plugin feature that requires long running connection (e.g. `cf tail -f my-app` for log-cache plugin)

**Who else is affected by the change?**
Does this feature cause a breaking change? Are other users affected by this change?

Not to my knowledge.

**Is your feature request related to a problem? Please describe.**
Whenever we have a long running connection, after 10m our token expires and we get `404`s. We often have to call CAPI directly to `refresh_token`, which means we have to make the original `token` call through our own CAPI client so that we have the refresh token.

**Describe the solution you'd like**
I would like a configurable time on my token as a flag to `oauth-token` that, in the background, calls `refresh_token` for me until my timeout *OR* I would accept a `cf refresh-token` functionality so that, as plugin developers, we can stay within the cli functionality for long running connections.

/cc @toddboom

**Comment by johannasmith** [comment]
[Slack conversation](https://cloudfoundry.slack.com/archives/C032824SM/p1540831135013600?thread_ts=1540830548.011700&cid=C032824SM) for reference.

**Comment by abbyachau** [comment]
Hey @johannasmith thanks for creating this - appreciate the details. Which plugin do you work on?

**Comment by johannaratliff** [comment]
@abbyachau at the time, the [log cache cli](https://github.com/cloudfoundry/log-cache-cli).

**Comment by gururajsh** [comment]
Thank you for your submission. If this issue is still relevant with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
