### ISSUE TITLE
CLI should provide a way to view the start command for an app

### ISSUE THREAD

**Issue by keeganwitt** [cloudfoundry/cli#1494]
In the UI, there's a "Start Command" on the "Settings" tab that shows the entrypoint for the container.  But I don't see that this information can be viewed from the CLI.  Probably the most logical place to add this would be the `cf app` command.

**Comment by gururajsh** [comment]
Thank you for your submission. If this issue is still relevant with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
