### ISSUE TITLE
is there a way to move apps into different space without cf push?

### ISSUE THREAD

**Issue by emailtowalter** [cloudfoundry/cli#1498]
We use org to map to application, and space for different env. e.g. dev/QA/prod. Wonder if there is a way to move the application from dev space to QA space, and further to prod? 

Now we use dev-ops to cf-push when we move to different spaces. but it results a recompilation of the code. So technically, it is NOT the same binary get deployed from the previous env, , and it can be a audit issue.  

I guess I can use docker, or binary build-pack as a workaround. It would be nice to have a native support from platform, something like "cf move myapp -s targetspace"

Thought?

**Comment by aegershman** [comment]
Hm, can you elaborate more on your delivery process? Do you *have* to recompile each time? Ideally you could compile or bundle your source code up once, store the compiled/bundled artifact in a place like Nexus (or artifactory, in a github release, etc.) && then `cf push` your code to each environment using the same compiled artifact in each environment.

**Comment by emailtowalter** [comment]
We have process similar to what you suggested. But feel more natural to “move” the app inside cf.

**Comment by tjvman** [comment]
@emailtowalter If you want to use the exact same staged bits, you could try the following:
1. `cf app source-app --guid` to get your source app guid
1. `cf curl /v2/apps/:source-guid/droplet/download --output /tmp/droplet.tgz` to download the source app's droplet to your local machine (note that if your Cloud Controller is configured to use a remote blobstore this command will return a redirect to the actual location of the droplet)
1. `cf target -s destination-space` to target the space you want to push the copied droplet to
1. `cf push --droplet /tmp/droplet.tgz destination-app-name`

**Comment by emailtowalter** [comment]
That is what I am thinking. Plus need a new manifest file if possible. 

Walter Wu

**Comment by emailtowalter** [comment]
I am good. Thanks

Walter Wu
