### ISSUE TITLE
Expose CF_DIAL_TIMEOUT and other CF specific env vars to CLI plugins

### ISSUE THREAD

**Issue by kitemongerer** [cloudfoundry/cli#1499]
**What's the user value of this feature request?**
Plugin creators will have easy access to CF specific settings and will be more aware of their existence. 

**Who is the functionality for?**
CLI plugin authors

**How often will this functionality be used by the user?**
At least once for any CLI plugin that talks to a CF component other than CAPI.

**Who else is affected by the change?**
Should be non breaking

**Is your feature request related to a problem? Please describe.**
Sort of... We write CLI plugins and got complaints that we weren't respecting CF_DIAL_TIMEOUT. We can get the variable from the environment but it would really help if there was a built in function so that CLI plugin authors would know about it before a customer has an unexpected experience.

**Describe the solution you'd like**
Either a function added to the cli connection to get dial timeout specifically. Or a function that returns some configuration struct with things like CF_DIAL_TIMEOUT and CF_COLOR on it.

**Comment by abbyachau** [comment]
Hi @kitemongerer thanks for reaching out, apologies for taking so long to respond. We don't currently have plans to support this unfortunately. I'm closing this issue but feel free to get in touch if you have any comments or feedback.

**Comment by kitemongerer** [comment]
Hi @abbyachau I think this would be a very useful feature to create a uniform experience between individual plugins and the main CLI. I'd love for this to stay open until we solve the underlying issue

**Comment by abbyachau** [comment]
Hey @kitemongerer thanks for the feedback. Could you elaborate on why getting the variable from the environment is insufficient/painful? Thanks.

**Comment by kitemongerer** [comment]
Yes. It is insufficient because there are several important environment variables for plugin authors to be aware of and there is no easy way to find out about them or what their defaults should be if they are not set. This means that every plugin author needs to learn about these variables through experience and then handle getting them from the environment and picking reasonable defaults (which are potentially different from the main CLI). If there were a uniform place to get important environment variables from with reasonable defaults chosen, it would create a more unified experience for plugin users because authors would be aware of the knobs users expect to be able to turn.

**Comment by abbyachau** [comment]
Thanks, reopening so we can track your concern.

**Comment by gururajsh** [comment]
Thank you for your submission. If this issue is still relevant with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
