### ISSUE TITLE
Cannot set instance count to 0 with `-i` on Windows

### ISSUE THREAD

**Issue by hiremaga** [cloudfoundry/cli#1501]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue. (wasn't 
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**

Setting the instance count to 0 as a command line argument does not work on Windows but works on OS X. Setting the instance count to 0 via the manifest works on Windows and OSX as expected.

**What happened**

`cf push -i 0` fails with the following validation error on Windows: 

> Invalid instance count: 0
> Instance count must be a positive integer

**Expected behavior**

No validation error, a successful run of the command.

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:

1. Ensure you're on Windows
1. Run `cf push -i 0`
1. See validation error
1. Add `instances: 0` to `manifest.yml`
1. Run `cf push`
1. See it work as expected.

**Provide more context**
- Windows 8.1
- CF CLI 6.40.1+85d04488a.2018-10-31
- CC API 2.125.0 (PWS)

**Comment by abbyachau** [comment]
Hey @hiremaga thanks very much for reporting this. We will try to reproduce and will give you a update on this soon. Thanks again.

**Comment by Ema93sh** [comment]
Hey @hiremaga 

I am unable to reproduce your issue in windows 7. 

Are you getting any deprecated warning when you run `cf push`? It would be great if you could share your manifest file. Thanks!

**Comment by hiremaga** [comment]
Looks like I was actually using Windows 8.1 when I reproduced this issue. It was on a Windows 8.1 VM on VMware Fusion from here: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

I did see a deprecation warning from `cf push`: "Deprecation Warning: Specifying app manifest attributes at the top level is deprecated. Found: env."

I've attached a screenshot below:

![screen shot 2018-11-13 at 2 23 54 pm](https://user-images.githubusercontent.com/7970/49398500-72e69500-f6f3-11e8-9e34-adee4bc27e07.png)

The manifest file that produced the error can be found here: https://github.com/18F/cf-hello-worlds/blob/master/go-hello/manifest.yml. This identical app & manifest file pushed fine on OS X with the same version of the `cf` CLI.

**Comment by Ema93sh** [comment]
Hi @hiremaga,
This looks like a bug in our legacy CLI code base. If you fix the deprecation warning, it should allow you to push with 0 instances. The following manifest with the same app works:
```
---
  applications:
    - name: hello
      env:
        GOPACKAGENAME: go-hello
```
