### ISSUE TITLE
CF cli not displaying route service url on "cf service <service name>"

### ISSUE THREAD

**Issue by jeffleecoffee** [cloudfoundry/cli#1506]
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
I was attempting to debug my user-provided-service route. However, I found that I could not see which route_service_url was already set.
![result](https://user-images.githubusercontent.com/14160064/48977543-0f080080-f051-11e8-8d7a-a2b4d571baa2.png)

**Expected behavior**
the CLI should display the route_service_url

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `cf cups authz -r <some https://URL>`
2. Bind a route-service `cf bind-route-service <domain> authz --hostname <host url>`
3. 'cf service authz' route_service_url should be <some https://URL>

**Provide more context**
- I am running Ubuntu 18.04.1 LTS
- cf version 6.40.1+85d04488a.2018-10-31

**Comment by georgi-lozev** [comment]
Hey @jeffleecoffee thank you for the issues. We've dragged this to our Icebox and it should get prioritized soon.

**Comment by willmurphyscode** [comment]
Also @jeffleecoffee if you pass `-v` you can see the `route_service_url` in the JSON that gets printed. I know reading JSON is no fun, but it might help you in the meantime to at least be able to access the information you need.

@georgi-lozev It looks like CC API already returns the information we need, but we're just not displaying it for some reason, so this story shouldn't be a heavy lift.

**Comment by jeffleecoffee** [comment]
@georgi-lozev and @willmurphyscode thank you for the prompt response and the suggestion.

**Comment by jeffleecoffee** [comment]
Hello @georgi-lozev and @willmurphyscode,
I've been looking forward to making a contribution for the CLI, is it cool if I work on this bug as my first commit?

**Comment by nmaslarski** [comment]
Hello @jeffleecoffee,
We'd be delighted if you contribute the fix.
Please make sure you have  read the [contributors guide](https://github.com/cloudfoundry/cli/blob/master/.github/CONTRIBUTING.md).

**Comment by laurzca** [comment]
Thanks for your contribution @jeffleecoffee! This is now in.

**Comment by jeffleecoffee** [comment]
Thanks @laurzca, it was fun to confirbute. I am looking forward to doing more in the future!
