### ISSUE TITLE
cf uninstall-plugin can be blocked forever

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cli#1512]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [X] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
On plugin uninstall, the CLI [invokes the plugin with special args](https://github.com/cloudfoundry/cli/tree/master/plugin/plugin_examples#uninstalling-a-plugin) to notify it of the uninstall. If a plugin which blocks (e.g. waiting for user input or for streaming data) does not handle this case, it will be impossible to uninstall via `cf uninstall-plugin`.

**Expected behavior**
The CLI should always be able to uninstall a plugin. Maybe it should take a force flag.

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Build the following plugin:
  ```go
package main

import (
	"time"

	"code.cloudfoundry.org/cli/plugin"
)

func main() {
	plugin.Start(new(PluginDemonstratingParams))
}

type PluginDemonstratingParams struct{}

func (pluginDemo *PluginDemonstratingParams) Run(cliConnection plugin.CliConnection, args []string) {
	time.Sleep(time.Hour)
}

func (pluginDemo *PluginDemonstratingParams) GetMetadata() plugin.PluginMetadata {
	return plugin.PluginMetadata{
		Name: "BugDemo",
		Version: plugin.VersionType{
			Major: 0,
			Minor: 0,
			Build: 1,
		},
		Commands: []plugin.Command{
			{
				Name:     "test",
				Alias:    "",
				HelpText: "A test for a plugin uninstall bug",
				UsageDetails: plugin.Usage{
					Usage: "cf test",
				},
			},
		},
	}
}
  ```
2. Install the plugin
3. Try to uninstall the plugin
4. See the hang and ctrl +c out
5. `cf plugins` still shows the plugin

**Comment by tjvman** [comment]
Seems like the solution here would be to add new functionality that either:
1. Allows the user to override/ignore the cleanup behavior (e.g., the `--force` flag that you mentioned)
2. Change `uninstall-plugin` so that it will timeout if cleanup takes too long and then remove the plugin forcefully, maybe also printing a warning that cleanup didn't succeed.

pinging @abbyachau for input on how to move forward/prioritize.

**Comment by abbyachau** [comment]
Hi @tjvman @gcapizzi thanks for this. Please could you let me know if there is a current workaround for this bug?

**Comment by gcapizzi** [comment]
@abbyachau hi! Removing the executable from `~/.cf/plugins` and then running `cf uninstall-plugin` will show failure but work 😉

**Comment by abbyachau** [comment]
Thanks @gcapizzi appreciate that. We'll try to get to this but unlikely to make it to the top of our backlog in the near term.

**Comment by joaopapereira** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket with the necessary information mentioned in our issue template.
