### ISSUE TITLE
v3-apps integration tests fail with recent cf-deployment release

### ISSUE THREAD

**Issue by georgi-lozev** [cloudfoundry/cli#1516]
Run `make integration-experimental` with the latest version of the CLI develop branch against a bosh-lite environment with latest cf-deployment [release-candidate](https://github.com/cloudfoundry/cf-deployment/tree/release-candidate) branch.

**What happened**
```
• Failure [91.549 seconds]
v3-apps command
/Users//go/src/code.cloudfoundry.org/cli/integration/shared/experimental/v3_apps_command_test.go:15
  when the environment is set up correctly
  /Users//go/src/code.cloudfoundry.org/cli/integration/shared/experimental/v3_apps_command_test.go:81
    with existing apps
    /Users//go/src/code.cloudfoundry.org/cli/integration/shared/experimental/v3_apps_command_test.go:102
      displays apps in the list [It]
      /Users//go/src/code.cloudfoundry.org/cli/integration/shared/experimental/v3_apps_command_test.go:114

      No future change is possible.  Bailing out early after 0.000s.
      Got stuck at:

          app1-f13737ef-524b-47bf-5053-e340d2ef0ada   started           web:1/1, console:0/0   app1-f13737ef-524b-47bf-5053-e340d2ef0ada.jungle-gargoyle.sapi.cf-app.com
          app2-5ca4e1ab-af8c-4eee-7acf-7dfa5150d97d   started           web:1/1, console:0/0   app2-5ca4e1ab-af8c-4eee-7acf-7dfa5150d97d.jungle-gargoyle.sapi.cf-app.com

      Waiting for:
          app1-f13737ef-524b-47bf-5053-e340d2ef0ada\s+started\s+web:1/1, console:0/0, rake:0/0\s+app1-f13737ef-524b-47bf-5053-e340d2ef0ada\.jungle-gargoyle.sapi.cf-app.com

      /Users//go/src/code.cloudfoundry.org/cli/integration/shared/experimental/v3_apps_command_test.go:118
```

We tried with an older version of cf-deployment(~2 weeks ago) and the same test is passing.
For more context have a look into the following [slack conv](https://cloudfoundry.slack.com/archives/CDVP0651P/p1543490235237200).

**Expected behavior**
Integration test not to fail.
I guess we should either change the test or find the root cause of the failure.

**Comment by tjvman** [comment]
Confirmed as an issue, seems that between versions 1.7.24 and 1.7.27 of the ruby buildpack, it stopped creating a `rake` process for apps using `v3-push`. We've pushed changes (see above story) that we believe will fix this issue, just waiting for CI.

**Comment by abbyachau** [comment]
Hi @georgi-lozev accepting this story based on the fact that our pipelines are green but do not hesitate to reach out if you continue to see issues. Thanks.
