### ISSUE TITLE
Uploaded buildpack stack (cflinuxfs3) does not match cflinuxfs3

### ISSUE THREAD

**Issue by ivandavidov** [cloudfoundry/cli#1518]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [*] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [*] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [*] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**

I have one buildpack with two stacks and I found out that when I try to update the buildpack and I use the ``-s`` option along with the ``-p`` option and the stack is already defined in the buildpack's manifest file, the command fails with very strange and very interesting error message (see below).

```
apama@vmbgcloudf06:~/Downloads/ivan/cf-update-buildpack-issue$ cf update-buildpack dummy_buildpack -p dummy_buildpack -s cflinuxfs3
Updating buildpack dummy_buildpack with stack cflinuxfs3 as admin...
OK
Uploading buildpack dummy_buildpack as admin...
 0 B / 836 B [---------------------------------------------------------------------------------------]   0.00%
Uploaded buildpack stack (cflinuxfs3) does not match cflinuxfs3
FAILED
apama@vmbgcloudf06:~/Downloads/ivan/cf-update-buildpack-issue$
```

**What happened**
The ``cf update-buildpack`` command always fails if there is a buildpack with 2 or more different stacks and the buildpack folder contains ``manifest.yml`` file in which the stack has been specified.

Brief summary of the error:

```
$ cf update-buildpack dummy_buildpack -p dummy_buildpack -s cflinuxfs3
...
Uploaded buildpack stack (cflinuxfs3) does not match cflinuxfs3
FAILED
apama@vmbgcloudf06:~/Downloads/ivan/cf-update-buildpack-issue$
```

Here is the corresponding ``manifest.yml`` which is really simple and specifies only the stack:

```
---
stack:
  - cflinuxfs3
```

**Expected behavior**

* When the stack is defined in the manifest file, the ``-s`` option should be optional. If the ``-s`` option is used, then the ``-s`` option should take precedence and should override the stack that has been defined in the manifest file.

**To Reproduce**

I have created a sample dummy buildpack and a test script which clearly demonstrates the issue.

https://github.com/ivandavidov/cf-update-buildpack-issue

Execute the following commands in order to reproduce the issue:

1. Clone the repo:
  ``git clone https://github.com/ivandavidov/cf-update-buildpack-issue.git``
2. `Navigate to the repo folder:
  ``cd cf-update-buildpack-issue``
3. Optionally set trace mode:
  ``export CF_TRACE=1``
4. Run the [script](https://github.com/ivandavidov/cf-update-buildpack-issue/blob/master/updateBuildpackFail.sh) which demonstrates the issue:
  ``./updateBuildpackFail.sh``
5. Examine the output and pay attention to the ``FAILED`` actions. Optionally, edit the script and comment the ``-x`` flag for clearer output. I have provided extensive comments in the script which should be clear enough.

[Sample output with trace disabled](https://github.com/ivandavidov/cf-update-buildpack-issue/blob/master/output_without_debug.txt)

[Sample output with trace enabled](https://github.com/ivandavidov/cf-update-buildpack-issue/blob/master/output_with_debug.txt) (much larger file)

**Provide more context**

- Ubuntu 16.04.4 LTS
- GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
- CF CLI version 6.41.0+dd4c76cdd.2018-11-28
- CAPI version 1.74.0
- The CF deployment is the latest available ''master'' branch from 2 days ago

**Comment by abbyachau** [comment]
cc @sclevine

**Comment by sclevine** [comment]
The correct syntax for the buildpack `manifest.yml` is:
```
stack: cflinuxfs3
```
Currently, CC can only associate a buildpack with a single stack. You can use the [buildpack-packager](https://github.com/cloudfoundry/libbuildpack/blob/master/packager/README.md) to create a buildpack package for each desired stack from buildpack source code that doesn’t have the `stack` key.

**Comment by ivandavidov** [comment]
Thank you for the input, but the issue is not related to creating buildpacks. If you have buildpack ``b`` with stacks ``s1`` and ``s2``, then you get two entries when you issue ``cf buildstacks`` with one entry for each stack.  And when you try to issue ``cf update-buildpack -p <folder> -i 2``, you get nicely formatted error that the action cannot be applied, because you have to use the ``-s`` option in order to target explicitly one of the buildpack/stack configurations. And when you add the ``-s`` option, the whole world falls apart, as I have explained above.

The sample dummy buildpack that I have described in the issue creates 2 buildpack/stack configurations and in both cases the manifest format seems to be OK (nevertheless, I'll revise the format as soon as I get back to work). What we would like to achieve now is to be able to update the buildpack configurations in the CF environment, preferably without using ``cf delete-buildpack`` and then ``cf create-buildpack``. We would like to rely on the already existing ``cf update-buildpack`` but in our case this doesn't work, exactly as I have demonstrated in the project with the dummy buildpack.

**Comment by sclevine** [comment]
I suspect (but haven't confirmed) that this error:
```
Uploaded buildpack stack (cflinuxfs3) does not match cflinuxfs3
```
Is because CC is comparing an array to a string. 

See: https://github.com/cloudfoundry/cloud_controller_ng/blob/c74a9bf37443428a1a4d32bed159ae7e0f00e7e0/lib/cloud_controller/buildpacks/stack_name_extractor.rb#L13
https://github.com/cloudfoundry/cloud_controller_ng/blob/65a75e6c97f49756df96e437e253f033415b2db1/spec/unit/lib/cloud_controller/buildpacks/stack_name_extractor_spec.rb#L31

Let me know if `cf update-buildpack -p <folder> -s <stack>` continues to fail after you fix the manifest format.

**Comment by ivandavidov** [comment]
The proposed modification in the manifest file completely resolved the issue. Thank you for your kind support on this matter.

Regards,
Ivan Davidov
