### ISSUE TITLE
cf login should error if '-a' flag missing but API endpoint provided

### ISSUE THREAD

**Issue by bruxelles86** [cloudfoundry/cli#1522]
**What's the user value of this feature request?**

Users with multiple platforms won't inadvertently try to login to the wrong one when they forget to use the '-a' flag.

**Who is the functionality for?**

Forgetful people.

**Is your feature request related to a problem? Please describe.**

I'm logged in to Platform Foo, and want switch to login to Platform Bar. Unfortunately, I and my colleagues frequently forget to use the '-a' flag t specify Platform Bar's API endpoint. This is what happens:

```
$ cf login api.sys.bar
API endpoint: https://api.sys.foo

Email> admin

Password>
Authenticating...
Credentials were rejected, please try again.

Password>
Authenticating...
Credentials were rejected, please try again.
```

**Describe the solution you'd like**

```
$ cf login api.sys.bar
API endpoint: https://api.sys.foo

Error: argument "api.sys.bar" not recognized
```

Thanks!

**Comment by aegershman** [comment]
Out of curiosity, in which ways does the `-a` make a difference? If you're targeting the incorrect API endpoint, does it matter if you've specified `-a` or not?

**Comment by bruxelles86** [comment]
If you're already logged in to api.sys.foo, and you run 'cf login api.sys.bar' - forgetting the '-a', then the CLI ignores the 'api.sys.bar' and tries to log you in to api.sys.foo. 
It doesn't error, and it's very easy not to notice that you're trying to login to a different platform from the one you thought you were trying to access.

Sent from Yahoo Mail on Android 
 
  On Mon, 10 Dec 2018 at 20:08, Aaron Gershman<notifications@github.com> wrote:   
Out of curiosity, in which ways does the -a make a difference? If you're targeting the incorrect API endpoint, does it matter if you've specified -a or not?

**Comment by abbyachau** [comment]
Hi @bruxelles86 thanks for creating this issue. Since we print the api `API endpoint: https://api.sys.foo` immediately after running `login`, this gives our users an explicit indication of which API endpoint they are targeting. I'm closing this issue as `won't-implement` but please don't hesitate to get in touch if you have any questions/feedback. Thanks.
