### ISSUE TITLE
Provide better error message if CF deployment fails due to missing authorization

### ISSUE THREAD

**Issue by fwilhe** [cloudfoundry/cli#1523]
## Context

I'm working on [SAP S/4HANA Cloud SDK Pipeline](https://github.com/sap/cloud-s4-sdk-pipeline) where we make use of the cf cli to push applications to SAP Cloud Platform. We use the cli via a [Docker image](https://hub.docker.com/r/s4sdk/docker-cf-cli/~/dockerfile/).

## Observation

If you configure a **valid user** for deployment that is **not a member of the target subaccount**, the error message is not descriptive of the misconfiguration. 

Log excerpt:

```
Error finding org myorg
Organization myorg not found
...
Could not load apps in space, are you logged in? - No org and space targeted, use 'cf target -o ORG -s SPACE' to target an org and space
```

## Improvement

I think the message as it is now is misleading in this case, and will make it quite hard for the user to find the error, which is very frustrating. An easy solution could be to mention this (and maybe other) possible error conditions in the message. The better, but more complex solution would be to include such information dynamically in the error message.

This is where the message comes from https://github.com/cloudfoundry/cli/blob/b6a3695a5db06d6628428067e0a78e63041ea1ca/cf/requirements/targeted_space.go#L24

**Comment by tjvman** [comment]
Could you tell us the exact command (or series of commands) that you're running that's causing this failure? Also, I'm not sure what you mean by  "subaccount"; could you clairfy that? 

At a glance, though, this seems like it may be a problem with one of the plugins that are installed in that Docker image - the `Could not load apps in space` part of that error message isn't coming from the core CLI.

**Comment by tjvman** [comment]
So, the org *isn't* targeted in this case - we don't save off its identifying info if the current user isn't able to access it. That `No org or space targeted` (and the API endpoint and User info right above it) is an accurate representation of the current state.

The actual error here is ```Error finding org Cloud Apps
Organization CloudApps not found``` - which, I agree, does not indicate that there was a permissions issue. We could modify the error message to also mention that the user may have had insufficient permissions - something like `Organization CloudApps not found, or missing permissions`, for example. Would that make the output more clear?

**Comment by fwilhe** [comment]
> Would that make the output more clear?

Hey @tjvman, yes, I think that is better. Thank you for taking the time for this issue.

**Comment by abbyachau** [comment]
Hi @fwilhe thanks again for reaching out. We are currently rewriting the `cf login` command. After we complete the rewrite, we would be happy to take contributions for this update. Thanks again.

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
