### ISSUE TITLE
Plugin cli output does not colorize properly on Windows

### ISSUE THREAD

**Issue by spinfooser** [cloudfoundry/cli#1524]
**Checklist**

- [ x ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ ] I am reporting a bug that others will be able to reproduce.

**Defect Description**
Using a Windows 10 Enterprise workstation machine, and I am seeing issues colorizing CF CLI output for a specific plugin. I am using the PCF Scheduler CLI Plugin as an example.

This occurs in Git Bash, Powershell, and CMD:

```
$ cf calls
Listing calls for org ?[33;1mGOPC-POWOrg?[0m / space ?[33;1mPowder?[0m as ?[33;1mspinfooser?[0m
?[38;1mCall Name?[0m   ?[38;1mApp Name?[0m     ?[38;1mURL?[0m
?[36;1mtest-call?[0m   powder-time   https://example.com/webhook
?[32;1mOK?[0m
```

The workaround we are using is CF_COLOR=false before our commands, but it is cumbersome for sure.

**Expected behavior**
I expect output similar to this:

```
$ cf calls
Listing calls for org GOPC-POWOrg / space Powder as spinfooser
Call Name   App Name     URL
test-call   powder-time   https://example.com/webhook
OK
```

**To Reproduce**
1. Install PCF Scheduler CLI Plugin. https://network.pivotal.io/products/p-scheduler/
2. `cf login` to a test org/space.
2. Run `cf calls`.
3. See output with BASH colorized control characters, but output is not colorized.

**Machine context**
- Windows 10 Enterprise
- Powershell and Git Bash
- CLI Version 6.41.0
- Scheduler for PCF CLI Plugin 1.1.0

**Comment by tjvman** [comment]
Are you seeing the issues with color for core cf commands, or is it only this plugin?

**Comment by spinfooser** [comment]
This is specific to the plugin itself, I haven't tried other plugins to verify if its a broader issue for more than this plugin. If you have another plugin I should try to test this, let me know of one and I can try it.

When I went to talk to the Scheduler for PCF team, they said said this may be a known issue with the plugin system in CF CLI.

**Comment by tjvman** [comment]
Was able to reproduce this on a Windows 10 VM in Virtualbox. Interestingly, we also saw that plugins (e.g. `doctor`) which use the CLI's `terminal` package to colorize their own output also exhibited the same behavior. Commands in the core CLI do not seem to have the same issue.

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
