### ISSUE TITLE
`cf create-buildpack` error seeking a stream on retry: Invalid Auth Token

### ISSUE THREAD

**Issue by jnpacker** [cloudfoundry/cli#1544]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ ] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Provide details on what you were trying to do (and why).
Loading 4 large buildpacks, 250MB-1000MB in size.

**What happened**
Uploading a number of large buildpacks with a single `cf login` results in Invalid Auth Token error.

**Expected behavior**
All for buildpacks previously uploaded successfully with a single `cf login` session.

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
A clear and concise description of what happen.
1. Connect to Cloud Foundry API with cf-cli. 
1. Run `cf create-buildpack` upload the first buildpack 758MB, takes about 6min.
1. Run `cf create-buildpack` upload the second buildpack 550MB, takes about 4min.
1. Run `cf create-buildpack` upload the third buildpack 170MB, Upload output shows 100%, but then error occurs:
```
Uploading buildpack nodejs_buildpack as user...
 160.74 MiB / 160.74 MiB  100.00%B   78.64% 24.40%

error seeking a stream on retry: Invalid Auth Token
FAILED
```
This problem does not occur with CF-CLI 6.38 or lower.
This problem does occur with 6.39.0+

**Provide more context**
- platform and shell details Ubuntu 16 Xneial
- version of the CLI you are running 6.41.0
- version of the CC API Release you are on 1.72.0

Note: As of January 2018, we no longer support API versions older than 2.69.0/3.4.0 (CF Release: 251 / CAPI Release: 1.15.0)

**Comment by tjvman** [comment]
Was able to repro this by creating a large dummy buildpack and uploading it as my current token was about to expire. 

The API-layer code that handles buildpack upload wraps the request body in a 
 [`Pipebomb`](https://github.com/cloudfoundry/cli/blob/master/api/cloudcontroller/pipebomb.go). The purpose of Pipebomb is to defer handling retries to a higher level in the code instead of letting the Connection and ConnectionWrappers handle it. The token is still [getting refreshed](https://github.com/cloudfoundry/cli/blob/master/api/cloudcontroller/wrapper/uaa_authentication.go#L55), but the wrapper returns early because of the Pipebomb.

Seems like we should be retrying the upload.

**Comment by zhanggbj** [comment]
Same here
```
REQUEST: [2019-09-11T07:06:17Z]
PUT /v2/buildpacks/238bfc30-2c5f-4d92-b850-d48002d4b306/bits HTTP/1.1
Host: api.bcfd-vpc-szr-440802.us-south.containers.appdomain.cloud
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: multipart/form-data; boundary=727bb58e73d9210807e28a6a3491869dda1df8420381b3fd351efa49fd84
User-Agent: cf/6.46.1+4934877ec.2019-08-23 (go1.12.9; amd64 linux)
[multipart/form-data Content Hidden]

 1.11 GiB / 1.11 GiB [=============================================================================================================================================================================================================] 100.00%

error seeking a stream on retry: Put https://api.bcfd-vpc-szr-440802.us-south.containers.appdomain.cloud/v2/buildpacks/238bfc30-2c5f-4d92-b850-d48002d4b306/bits: EOF
```

# cf version
**cf version 6.46.1+4934877ec.2019-08-23**

**Comment by bwasmith** [comment]
Permalink for Tom's previous comment: 
https://github.com/cloudfoundry/cli/blob/815ea2f3d41a98d7a7e4e520509160ba8b355725/api/cloudcontroller/wrapper/uaa_authentication.go#L55

New refresh logic appears to be here: 
https://github.com/cloudfoundry/cli/blob/a759ff73817898fc0e02839b7697f7cdaceb42a7/api/cloudcontroller/wrapper/uaa_authentication.go#L59

**Comment by abbyachau** [comment]
Hi @jnpacker thanks for creating this issue. We've applied a fix and plan to include it in our next release. Please do not hesitate to get in touch if you have any questions or feedback.
