### ISSUE TITLE
`cf app APP_NAME` displays the stack from the current droplet instead of the app

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cli#1545]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
This was uncovered by a CATS (`capi_experimental` suite) failure after `cf-deployment` changed the default stack from `cflinuxfs2` to `cflinuxfs3`. Specifically, [this CAT fails](https://github.com/cloudfoundry/cf-acceptance-tests/blob/fd656f0af4c1d966566b98c30bbd4b2882e1b0d5/capi_experimental/manifest.go#L169).

The issue was that after applying a manifest that specified that the app use the `cflinuxfs2` stack, the `cf app APP_NAME` command continued displaying the app's previous stack, which was `cflinuxfs3`.

Example test failure output:
```
• Failure [164.341 seconds]
[capi_experimental]
/go/src/github.com/cloudfoundry/cf-acceptance-tests/cats_suite_helpers/cats_suite_helpers.go:245
  apply_manifest
  /go/src/github.com/cloudfoundry/cf-acceptance-tests/cats_suite_helpers/cats_suite_helpers.go:251
    Applying manifest to existing app
    /go/src/github.com/cloudfoundry/cf-acceptance-tests/capi_experimental/manifest.go:89
      routing
      /go/src/github.com/cloudfoundry/cf-acceptance-tests/capi_experimental/manifest.go:103
        when routes are specified
        /go/src/github.com/cloudfoundry/cf-acceptance-tests/capi_experimental/manifest.go:104
          successfully completes the job [It]
          /go/src/github.com/cloudfoundry/cf-acceptance-tests/capi_experimental/manifest.go:154

          No future change is possible.  Bailing out early after 0.000s.
          Got stuck at:
              
              last uploaded:     Tue 15 Jan 02:25:53 UTC 2019
              stack:             cflinuxfs3
              buildpacks:        ruby
              
              type:           web
              instances:      0/2
              memory usage:   300M
                   state      since                  cpu    memory          disk          details
              #0   starting   2019-01-15T02:27:42Z   0.0%   19.1M of 300M   87.8M of 1G   
              #1   starting   2019-01-15T02:27:37Z   0.0%   0 of 300M       0 of 1G       
              
              type:           worker
              instances:      0/0
              memory usage:   256M
              
              There are no running instances of this process.
              
          Waiting for:
              stack:\s+cflinuxfs2

          /go/src/github.com/cloudfoundry/cf-acceptance-tests/capi_experimental/manifest.go:169
```

**What happened**
We found that the manifest application was working as expected and that the app was reporting the correct stack when observed through `cf curl /v3/apps/<app-guid>`. However, while running `cf app APP_NAME -v` we saw that the CLI appeared to take the stack from `/v3/apps/<app-guid>/droplets/current`.

This means that the CLI command displays the stack of the app's current droplet (usually what it was using when it was last staged) and matches up with the stack that will be used when the app next starts (i.e. a new Desired LRP is created on Diego). However, this also means that the displayed stack may not align with what is actually set on the app itself (what it will use the next time it is stages) and can cause confusion.

More information can be found in [CAPI Story #163210854](https://www.pivotaltracker.com/story/show/163210854)

**Expected behavior**
Not sure which is most helpful for the end user, but right now it can be confusing trying to disambiguate these two sources of stack -- especially since `cf app` implies it is reporting app state versus droplet state.

**To Reproduce**
Easiest way is to checkout `v2.7.0` of CATS and run the `capi_experimental/manifest.go` suite.

A manual way is to:
1. `cf push APP_NAME`
1. Observe that the stack is `cflinuxfs3` using `cf curl /v3/apps/<app-guid>`
1. Apply a manifest `cf v3-apply-manifest -f <manifest-file-path>`

An example manifest for a `staticfile_buildpack` is:
```
applications:
- name: APP_NAME
  stack: cflinuxfs2
  buildpacks:
  - staticfile_buildpack
  env:
    foo: qux
    snack: walnuts
  processes:
  - disk_quota: 1024M
    instances: 2
    memory: 300M
    timeout: 75
    type: web
  - disk_quota: 1024M
    health-check-type: process
    instances: 0
    memory: 256M
    type: worker
```

4. Observe that `cf app APP_NAME` still returns `cflinuxfs3` as the stack and that  `cf curl /v3/apps/<app-guid>` returns `cflinuxfs2`.

**Provide more context**
- Mac OS X 10.13 iTerm
- `cf version 6.42.0+0cba12168.2019-01-10`
- capi-release `1.75.0`

Thank you! 🎉 
Tim && @monamohebbi

**Comment by abbyachau** [comment]
cc @sclevine

**Comment by shanks3012** [comment]
Hey there, I'm noticing a similar issue occurring but when we attempt to change the stack of a **stopped app** through the curl command:

```
"curl", "/v2/apps/"+appGuid, "-X", "PUT", -d={"stack_guid":"+stackGuid+","state":"STOPPED"}
```

a cf app myapp results in the stack being blank. This is slightly different that showing the old stack.

**Comment by tcdowney** [comment]
@shanks3012 does the app still have a current droplet associated with it?

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
