### ISSUE TITLE
Publish as Chocolatey package for Windows users

### ISSUE THREAD

**Issue by dazinator** [cloudfoundry/cli#1548]
**What's the user value of this feature request?**
To allow windows users to install the package more easily using a popular package manager for windows systems.

**Who is the functionality for?**
Windows users.

**How often will this functionality be used by the user?**
Whenever it's needed in order to manage the installed version of the CI 

**Who else is affected by the change?**
No one.

**Is your feature request related to a problem? Please describe.**
I'm frustrated on windows, when I have to install by downloading a zip file and adding things to PATH, rather than using a package manager.

**Describe the solution you'd like**
I'd like to be able to `choco install` the CF cli.

**Describe alternatives you've considered**
Other package managers supported on windows - such as `npm` are alternatives. I'm open to alternatives, chocolatey is one credible suggestion on Windows.

**Additional context**
-

**Comment by gururajsh** [comment]
Thank you for your submission. CLI is now published as Chocolatey package. So will be closing the issue.
