### ISSUE TITLE
Creating internal users specifying username and email separately

### ISSUE THREAD

**Issue by kinjelom** [cloudfoundry/cli#1554]
**What's the user value of this feature request?**
-----
I want to create many accounts with different access to the orgs/spaces for one real user with one email.
This is for security reasons, the fire area has to be limited.
Users have to use different accounts to different tasks/context.

**Who is the functionality for?**
**How often will this functionality be used by the user?**
-----
Everyone / everyday work

**Who else is affected by the change?**
**Is your feature request related to a problem? Please describe.**
**Describe alternatives you've considered**
**Additional context**
-----
This is normal `uaa` feature covered/reduced by `cf-cli`.
Now I can do it in the following way:
```bash
cf create-user user.dev  S3cr3t 
# result: username==email==user.dev
cf create-user user.prod  S3cr3t 
# result: username==email==user.prod

uaac user update user.dev  --emails user@example.com 
# result: username==user.dev, email==user@example.com
uaac user update user.prod  --emails user@example.com
# result: username==user.prod, email==user@example.com
```
After that everything works great: sign-in, access, reset password...
But to do it I have to use two tools: `cf-cli` and `uaa-cli`, that is not very comfortable.

**Describe the solution you'd like**
----
```
USAGE:
   cf create-user USERNAME EMAIL PASSWORD

EXAMPLES:
   cf create-user j.smith j.smith@example.com S3cr3t         # internal user
```

**Comment by abbyachau** [comment]
cc @cwang-pivotal

**Comment by abbyachau** [comment]
cc @dbeneke

**Comment by bwasmith** [comment]
From my searching on the CLI side, it looks like it would be straightforward to implement. 

Our current post to UAA for `create-user`:
```
$ cf -v
cf version 7.0.0-beta.29+947eaab38.2020-01-16

$ cf create-user -v username password
...
Creating user username...
REQUEST: [2020-01-16T10:33:47-08:00]
POST /Users HTTP/1.1
Host: uaa.example.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: cf/7.0.0-beta.29+947eaab38.2020-01-16 (go1.13.5; amd64 linux)
{
  "emails": [
    {
      "primary": true,
      "value": "username"
    }
  ],
  "name": {
    "familyName": "username",
    "givenName": "username"
  },
  "origin": "",
  "password": "[PRIVATE DATA HIDDEN]",
  "userName": "username"
}
```

We would need to pass through the given email information.

[UAA Create User](https://docs.cloudfoundry.org/api/uaa/version/74.4.0/index.html#create-4) Doc for reference.

I am not sure whether adding this functionality is desirable for the CLI. We might need to get more push on this use-case from the community.

**Comment by gururajsh** [comment]
Thank you for your submission. If this issue is still relevant with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
