### ISSUE TITLE
Feature Request: Fast cf services option 

### ISSUE THREAD

**Issue by Kiemes** [cloudfoundry/cli#1557]
**Please provide details on the following items. Failure to do so may result in deletion of your feature request.** 
We would be interested in a faster `cf services` command. The output should just be basic services information excluding any related app data. This is especially useful if you have a space with many services and apps.

**What's the user value of this feature request?**
A clear and concise description of what the user value is.
A more performant `cf s` command for specific use-cases.

**Who is the functionality for?**
Who will use this feature? 
We in i.e. our CI/CD pipelines to create services if not existing. At that point in time, I am not interested in apps. Also every user using the CLI to list all services not being interested in app data.

**How often will this functionality be used by the user?**
How often will they use this feature?
At least on every pipeline run.

**Who else is affected by the change?**
Does this feature cause a breaking change? Are other users affected by this change?
Introducing an option would not break any existing behavior.

**Is your feature request related to a problem? Please describe.**
I investigated when we had the issue [#1353](https://github.com/cloudfoundry/cli/issues/1353#issuecomment-458926924). This actually improved the performance already quite good, but for our purpose, the new option would increase the performance even more. Also the resiliency could be improved because of the paging safety-net.

**Describe the solution you'd like**
Introducing an option like `--fast` or `--skip-app-data` or `--brief` or `--plain` (as non native speaker, I am not sure what fits best) which uses `/v2/service_instances?q=space_guid:<guid>` API and `/v2/user_provided_service_instances?q=space_guid:<guid>` API. 

**Describe alternatives you've considered**
As soon as #1353 is fixed, we could also live with it at the moment with our current numbers of spaces and apps.

Wdyt?

**Comment by henryaj** [comment]
Thanks for the suggestion, @Kiemes – I'll chat to our PM and get back to you.

**Comment by laurzca** [comment]
Thanks for your feedback @Kiemes! We're planning to pick up the work to fix this soon. It's in our backlog: https://www.pivotaltracker.com/story/show/163819858

We've decided to move forward with `--no-apps`. Do  you think that makes sense for the flag?

**Comment by blgm** [comment]
This improvement has been committed to `master` branch here: ba729f508886152aa0e4f56228c419dbbd26521e

At the moment it's in the `v3-services` command which is planned to become the `services` command for v8 of the CLI, talking to V3 Cloud Controller API endpoints. We don't have a precise timeline for V8, but there is a plan to start releasing betas soon. That work can be followed here: https://www.pivotaltracker.com/story/show/174216659

I'm going to close this issue as the work is done, and it's just a question of waiting for it to be released. But please feel free to re-open and/or give us feedback via Slack.
