### ISSUE TITLE
set-org-role support for plain OrgUser

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#1565]
**What's the user value of this feature request?**

As a paas-admin, I need a way to add users to an org (as org users without any additional org role), in order for space admins to be able to add these users to their space.

See related documentation
https://community.pivotal.io/s/article/Server-Error-Error-Code--1002-Error-Message-cannot-set-space-role-because-user-is-not-part-of-the-org-is-seen-when-Using-CF-set-space-role
https://docs.cloudfoundry.org/concepts/roles.html#users 
> Before you assign a space role to a user, you must assign an org role to the user. The error message Server error, error code: 1002, message: cannot set space role because user is not part of the org occurs when you try to set a space role before setting an org role for the user

**Who is the functionality for?**

CF org admins

**How often will this functionality be used by the user?**

Each time a new user needs to be added to an org without additional role

**Who else is affected by the change?**
> Does this feature cause a breaking change? 

No

> Are other users affected by this change?

No 

**Describe the solution you'd like**

`cf set-org-role user org OrgUser`  triggers a `PUT /v2/organizations/:guid/users/:user_guid`
`cf unset-org-role user org OrgUser`  triggers a `DELETE /v2/organizations/:guid/users/:user_guid?recursive=false`

**Describe alternatives you've considered**

 I'm using a sequence of `cf set-org-role user org OrgAuditor` and `cf unset-org-role user org OrgAuditor` which as a side effect makes a [PUT /v2/organizations/:guid/users/:user_guid](http://apidocs.cloudfoundry.org/7.2.0/organizations/associate_user_with_the_organization.html) call

**Comment by bwasmith** [comment]
@gberche-orange , Thank you for creating this Issue.

I believe this is fixed with the recent v7 roles work. [Tracker Epic for Users and Roles](https://www.pivotaltracker.com/epic/show/4243301) 

```
$ cf -v
cf version 7.0.0-beta.29+947eaab38.2020-01-16


$ cf create-user brendan brendan
Creating user brendan...
OK


$ cf set-space-role brendan org space SpaceManager
Assigning role SpaceManager to user brendan in org org / space space as admin...
OK
```
And the associated info for Org `org` and Space `space`:

```
$ cf org-users org
Getting users in org org as admin...

ORG MANAGER
  admin (uaa)

BILLING MANAGER
  No BILLING MANAGER found

ORG AUDITOR
  No ORG AUDITOR found


$ cf space-users org space
Getting users in org org / space space as admin...

SPACE MANAGER
  admin (uaa)
  brendan (uaa)
...
```
 Please reopen if you believe this is insufficient.
