### ISSUE TITLE
cf update-service behavior is inconsistent

### ISSUE THREAD

**Issue by henryaj** [cloudfoundry/cli#1575]
Moving https://github.com/cloudfoundry/cloud_controller_ng/issues/1286 over here as it's a CLI issue.

> When we do a `cf update-service service-name`, it says no changes are made. But when we pass same plan name, like `cf update-service service-name -p same-plan-name`, then it says OK, even though no call is made to the broker.

```
$ cf update-service test
OK
No changes were made

$ cf update-service test -p <same-plan>
Updating service instance test as admin_cf...
OK
```

We should make these two operations behave consistently.

**Comment by williammartin** [comment]
We've fixed this in https://www.pivotaltracker.com/n/projects/2105761/stories/163974651 so hopefully it will be resolved in the next release of CAPI. Thanks!
