### ISSUE TITLE
'cf unset-env' is not documented when typing 'cf' or 'cf --help' to see the options

### ISSUE THREAD

**Issue by odupuy** [cloudfoundry/cli#1576]
**Please provide details on the following items. Failure to do so may result in deletion of your feature request.** 
THE OPTION IS NOT LISTED WHEN TYPING 'cf'. YOU HAVE TO GOOGLE TO FIND IT. IT IS A COMMON OPTION.
I have the latest version 6.42.0+0cba12168.2019-01-10

Add as well this URL in the help output http://cli.cloudfoundry.org/en-US/cf/

**What's the user value of this feature request?**
A clear and concise description of what the user value is.
DON'T GOOGLE

**Who is the functionality for?**
Who will use this feature? 
ANYONE

**How often will this functionality be used by the user?**
How often will they use this feature?
OFTEN

**Who else is affected by the change?**
Does this feature cause a breaking change? Are other users affected by this change?
NO IMPACT

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
JUST LIST THE OPTION UNDER '

**Describe alternatives you've considered**
JUST LIST IT

**Additional context**

**Comment by abbyachau** [comment]
Hi @odupuy thanks for creating this issue. Sorry about the confusion. We've had similar [issues](https://github.com/cloudfoundry/cli/issues/1429) in the past - when you run `cf --help` it only shows you a subset of the help text. Running `cf h -a` will display the full help text. Given this comes up once in a while we can either add a `TIP` to `cf --help` to indicate the option to run `-a`, or we could just display the entire help text when users run `cf --help`. If the latter, we'll need to dig into what type of design decisions were made and whether that's a good avenue to pursue.

**Comment by odupuy** [comment]
@abbyachau then if you do not want to display all the options or their groupings (names slightly different between the CLI and the help page BTW) then you could simply display at the bottom of the page "This was a subset of the commands. Many more are listed at http://cli.cloudfoundry.org/en-US/cf".

With that, you still save time to the user. 

Thanks

**Comment by abbyachau** [comment]
Hi @odupuy thanks for creating this issue. We've made an update so that the `TIP` is more prominent now. This update will be in the next release of the CLI. I'm closing this issue but please don't hesitate to reach out if you have any questions/feedback. Thanks.
