### ISSUE TITLE
cf cli fails on most commands when access token expired and unauthenticated rate limit of CF API is reached

### ISSUE THREAD

**Issue by stephanme** [cloudfoundry/cli#1582]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**

When the [unauthenticated rate limit](https://bosh.io/jobs/cloud_controller_ng?source=github.com/cloudfoundry/capi-release&version=1.77.0#p%3dcc.rate_limiter.unauthenticated_limit) is reached (which is measured per calling IP), cf cli can't be used anymore when the access token expired 10 min after login:

```
$ cf logout
# assumes cc.rate_limiter.unauthenticated_limit = 100 (default)
$ for i in {1..101}; do cf curl -v v2/organizations/x | grep X-Ratelimit-Remaining; done
...
X-Ratelimit-Remaining: 1
X-Ratelimit-Remaining: 0
X-Ratelimit-Remaining: 0
# = unauthenticated rate limit hit

$ cf login
...
# wait > 10 min so that access token expires
$ cf orgs
Getting orgs as stephan.merker@sap.com...

Unexpected Response
Response code: 429
CC code:       10013
CC error code: CF-RateLimitExceeded
Request ID:    cf19b8e0-d39a-41a4-41fe-ce8009bf5976::f12bfdab-fa2c-4c73-a92d-b1122d97ac16
Description:   Rate Limit Exceeded
FAILED
```

**What happened**

cf cli fails with CF-RateLimitExceeded on the unauthenticated limit (500 in our test CF installation, the authenticated limit is larger).

Verbose log:

```
$ cf -v orgs
REQUEST: [2019-02-25T16:04:39+01:00]
GET /v2/info HTTP/1.1
Host: api.cf.stagingsc7.hanavlab.ondemand.com
Accept: application/json
User-Agent: cf/6.38.0+7ddf0aadd.2018-08-07 (go1.10.3; amd64 linux)

RESPONSE: [2019-02-25T16:04:39+01:00]
HTTP/1.1 200 OK
Content-Length: 681
Content-Type: application/json;charset=utf-8
Date: Mon, 25 Feb 2019 15:04:39 GMT
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload;
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: bb9d2db0-120f-4805-7a0d-376b3a43c3c4::a5ac3215-cbdb-4927-af0a-14c95146a912
{
  "api_version": "2.128.0",
  "app_ssh_endpoint": "ssh.cf.stagingsc7.hanavlab.ondemand.com:2222",
  "app_ssh_host_key_fingerprint": "fa:e8:74:82:eb:39:6e:a3:7c:88:9a:e9:cc:1c:da:99",
  "app_ssh_oauth_client": "ssh-proxy",
  "authorization_endpoint": "https://login.cf.stagingsc7.hanavlab.ondemand.com",
  "bits_endpoint": "https://bits.cf.stagingsc7.hanavlab.ondemand.com",
  "build": "",
  "description": "Cloud Foundry at SAP Cloud Platform",
  "doppler_logging_endpoint": "wss://doppler.cf.stagingsc7.hanavlab.ondemand.com:443",
  "min_cli_version": null,
  "min_recommended_cli_version": null,
  "name": "",
  "osbapi_version": "2.14",
  "support": "",
  "token_endpoint": "https://uaa.cf.stagingsc7.hanavlab.ondemand.com",
  "version": 0
}


REQUEST: [2019-02-25T16:04:39+01:00]
GET /login HTTP/1.1
Host: login.cf.stagingsc7.hanavlab.ondemand.com
Accept: application/json
Connection: close
User-Agent: cf/6.38.0+7ddf0aadd.2018-08-07 (go1.10.3; amd64 linux)

RESPONSE: [2019-02-25T16:04:39+01:00]
HTTP/1.1 200 OK
Cache-Control: no-store
Content-Language: en-US
Content-Length: 763
Content-Type: application/json;charset=UTF-8
Date: Mon, 25 Feb 2019 15:04:39 GMT
Set-Cookie: X-Uaa-Csrf=GlMT3ci1auaBRNRgRlpfSO; Max-Age=86400; Expires=Tue, 26-Feb-2019 15:04:39 GMT; Path=/; Secure; HttpOnly
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload;
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Vcap-Request-Id: 94d9b5ec-72b1-49aa-4491-d4e5353de305
X-Xss-Protection: 1; mode=block
{
  "app": {
    "version": "4.27.0"
  },
  "commit_id": "76e960d",
  "entityID": "login.cf.stagingsc7.hanavlab.ondemand.com",
  "idpDefinitions": {},
  "links": {
    "login": "https://login.cf.stagingsc7.hanavlab.ondemand.com",
    "passwd": "https://accounts.sap.com/ui/createForgottenPasswordMail?spName=cf.us10.stagingaws.hanavlab.ondemand.com",
    "register": "https://accounts.sap.com/ui/public/showRegisterForm?spName=cf.us10.stagingaws.hanavlab.ondemand.com",
    "uaa": "https://uaa.cf.stagingsc7.hanavlab.ondemand.com"
  },
  "prompts": {
    "passcode": [
      "password",
      "Temporary Authentication Code ( Get one at https://login.cf.stagingsc7.hanavlab.ondemand.com/passcode )"
    ],
    "password": "[PRIVATE DATA HIDDEN]",
    "username": [
      "text",
      "Email"
    ]
  },
  "showLoginLinks": true,
  "timestamp": "2019-01-25T17:50:24+0000",
  "zone_name": "uaa"
}


Getting orgs as stephan.merker@sap.com...

REQUEST: [2019-02-25T16:04:39+01:00]
GET /v2/organizations?order-by=name HTTP/1.1
Host: api.cf.stagingsc7.hanavlab.ondemand.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.38.0+7ddf0aadd.2018-08-07 (go1.10.3; amd64 linux)

RESPONSE: [2019-02-25T16:04:39+01:00]
HTTP/1.1 429 Too Many Requests
Content-Length: 99
Content-Type: text/plain; charset=utf-8
Date: Mon, 25 Feb 2019 15:04:39 GMT
Retry-After: 1551108525
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload;
X-Ratelimit-Limit: 500
X-Ratelimit-Remaining: 0
X-Ratelimit-Reset: 1551108525
X-Vcap-Request-Id: 00b31acc-335b-4581-7e5d-086ce3227dc1::3a69412d-4611-4e8f-b240-fdfaa1d9bdab
{
  "code": 10013,
  "description": "Rate Limit Exceeded",
  "error_code": "CF-RateLimitExceeded"
}


Unexpected Response
Response code: 429
CC code:       10013
CC error code: CF-RateLimitExceeded
Request ID:    00b31acc-335b-4581-7e5d-086ce3227dc1::3a69412d-4611-4e8f-b240-fdfaa1d9bdab
Description:   Rate Limit Exceeded
FAILED
```

**Expected behavior**

cf orgs returns the list of my orgs. Before doing so cf cli has to refresh my access token because it expired.

**To Reproduce**

See script above in bug description.

**Provide more context**
- platform and shell details: Win10 + WSL, also on Linux Ubuntu 18.04
- version of the CLI you are running: 6.38.0+7ddf0aadd.2018-08-07, also seen with 6.41.0
- version of the CC API Release you are on: 2.128.0, cf-deployment 7.2.0

Note: As of January 2019, we no longer support API versions older than CF Release v284/CF Deployment v1.7.0 (CAPI Release: 1.46.0 (APIs 2.100.0 and 3.35.0).

**Our explanation and Possible Solutions**

`cf orgs` calls /v2/organizations with an exipred access token. If CF API would respond with a 401, cf cli would refresh the access token and retry the call. However, CF API responds with 429 because the unauthenticated rate limit is already exceeded for the IP of the PC running `cf orgs`. This case is not handled and `cf orgs` fails with 'rate limit exceeded'.

This is not so much a problem for individual users but we have seen this issue for CF API calls made from CF applications or from Concourse. These calls come all from the same IP (or a small group of IPs) due to NAT.

I could think of the following solutions:
- cf cli could treat a 429 similar to 401, i.e. refresh the access token and retry the api call. This would solve the described scenario. However cf cli can't distinguish between authenticated and unauthenticated rate limit. For an authenticated rate limit, a retry is not a good idea as it would just increase the rate limit counter for the user.
- cf cli could check the expiration time of the access token. If the remaining life time is e.g. less than 1 min, cf cli could refresh the token before calling CF API. This way, unauthenticated calls could be avoided altogether.

In the cf cli coding I see that for some commands the token is refreshed unconditionally before the excution (e.g. https://github.com/cloudfoundry/cli/blob/master/cf/commands/serviceaccess/service_access.go#L69). I guess this was done for long running commands to avoid expired tokens.

**Comment by willmurphyscode** [comment]
Hey @stephanme, thank you for submitting this issue.

We have successfully reproduced this scenario and will talk with our PM about getting it prioritized. 

@abbyachau, @stephanme mentions a specific approach:

> * cf cli could check the expiration time of the access token. If the remaining life time is e.g. less than 1 min, cf cli could refresh the token before calling CF API. This way, unauthenticated calls could be avoided altogether.

I think we should take this approach. First, because it avoids a network request that we know will fail. Second, because it avoids making a request that counts against the unauthenticated rate limit. Third, because being coupled to how OAuth tokens are parsed seems more stable than being couple to particular error responses from CC API, and fourth because it will automatically fix https://github.com/cloudfoundry/cli/issues/1143, which other methods of addressing this issue will not.

This would require changes both in the new and legacy code (or would affect only some commands), but seems like the right approach.

**Comment by abbyachau** [comment]
Hi @stephanme thank you again for raising this concern and for the pull request. This fix will be in the next release, closing this issue - thanks again!
