### ISSUE TITLE
Env vars not easily distinguishable from UPS in `cf env` output

### ISSUE THREAD

**Issue by mogul** [cloudfoundry/cli#1585]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
I was trying to unset an environment variable for an app, and I wasn't sure if it was supplied as an environment variable or via a bound user-provided-service-instance. I ran `cf env` to look at the environment for the app.

**What happened**
In the `cf env` output, I saw what are actually environment variables, including the one I was looking for, listed under the heading `User-Provided:`. This led me to believe that I needed to update the content of the user-provided service.  I then carefully ran `cf uups` to update the service with all of the existing variable values from that list except for the one I wanted to get rid of... and oops, that blew away the existing content of the (entirely unrelated) UPS, which happened to include secrets for the app!

This confusing UX was the proximal contributing factor for the resulting outage I incurred last night for cloud.gov:
https://cloudgov.statuspage.io/incidents/sm00znvqp33y

**Expected behavior**
This was super-confusing because environment variables are totally unrelated to user-provided-service-instances, which _also_ appear in the `cf env` output, but buried in the `VCAP_SERVICES` variable above. They should be listed under a different heading, eg `User-set environment variables`.

**To Reproduce**
* Bind a user-provided service containing field A to an app 
* Set an environment variable B on the same app
* Run `cf env` on the app, and see that B is listed under `User-Provided:`

**Comment by mogul** [comment]
Sorry, I accidentally hit submit before I was done writing. I edited my post, but I think `cf-gitbot` propagated the incomplete report to Pivotal Tracker, so it'll need updating there! @abbyachau

**Comment by willmurphyscode** [comment]
Hi @mogul 

Thank you so much for opening an issue, and I'm sorry to hear that our CLI was one of the steps on the way to an outage.

We set up a user provided service, bound it to an app, set some extra environment variables with `cf set-env`, and then ran `cf env` to take a look. We see that the string `User-Provided` does appear twice and  where your confusion arose.

As you probably know now, environment variables that appear under "System-Provided" are managed by Cloud Foundry itself, and should not be directly edited; the environment variables under "User-Provided" were created by CF users running `cf set-env`.

While we appreciate the suggestion, we're not able to change the text of the two headings produced by `cf env` at this time. Many people script with the CF CLI, and renaming a section of output is considered a breaking change that would require a major version.

**Comment by mogul** [comment]
Wow, I'm really sorry to hear that; this could have been such an easy
improvement!

Will you consider adding `cf env --json` so that people writing scripts
have a well-formed output format to build on, and you can have regain
freedom to improve the UX of the human-intended version of the output?

**Comment by abbyachau** [comment]
Hey @mogul sorry we couldn't help with changing the name of the headings in V6 CLI, making this type of change has a chance of breaking existing scripts - something we always try to avoid, even if it means, historically an inferior user experience. We hope to start releasing major releases (once we are done with V7 CLI) more often, and offer a scripting solution at the same time, so to allow us to make command line ux changes without affecting our scripting users. 

However in the meantime:

1. We will review your feedback for V7 CLI beta, and I've logged your feedback in this story (https://www.pivotaltracker.com/story/show/164352271). The VAT tracker, is the V3 Acceleration Team's tracker (we are tasked with building the V3 CC API and a V7 CLI that supports it). Currently our priorities is to build basic functionality so it's unlikely we will be able to prioritise this work in the immediate future. 

1. I've added your feedback to https://github.com/cloudfoundry/cli/issues/1415, which is where we are tracking the `--json` flag feedback. 

Please do not hesitate to reach out if you have any feedback or any suggestions. Happy to discuss. Thanks again.

**Comment by mogul** [comment]
Terrific, thanks Abby!
