### ISSUE TITLE
'cf config --color=false' does not turn off all the colors

### ISSUE THREAD

**Issue by STiago** [cloudfoundry/cli#1587]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
When running `cf push -f manifest.yml`  after run `cf config --color=false` it still shows some all the output colors.

**What happened**
When turning --color=false, only the light blue color would get turned off.  The dark blue, green and red colors were still shown.

1. Color false:

<img width="958" alt="cf-color-false" src="https://user-images.githubusercontent.com/5521874/53813045-9fa98300-3f54-11e9-8f4d-cccdd4f7ef58.png">

2. Color true:

<img width="959" alt="cf-color-true" src="https://user-images.githubusercontent.com/5521874/53813066-ac2ddb80-3f54-11e9-8ab2-494cd80efcc8.png">

**Expected behavior**
'cf config --color=false' should removes all the output colors.

**To Reproduce**

1. Run `cf config --color=false`
2. Run `cf push -f manifest.yml`

**Provide more context**
- platform and shell details: Ubuntu 16.04.5 LTS
- version of the CLI you are running: 6.38.0+7ddf0aadd.2018-08-07, also seen with 6.41.0
- version of the CC API Release you are on: 2.128.0, cf-deployment 7.2.0

Note: As of January 2019, we no longer support API versions older than CF Release v284/CF Deployment v1.7.0 (CAPI Release: 1.46.0 (APIs 2.100.0 and 3.35.0).

**Comment by bwasmith** [comment]
Hey! Thanks for reporting this issue to us - we reproduced it locally on our machines and we will talk with our PM about prioritizing this issue. Just a heads-up, our PM is on holiday currently.

We think the issue has to do with where each of these sections are coming from. Where you see the colors stripped, this is output from the CLI. Though, anything after "Staging app and tracing logs..." is directly streamed from CAPI. And, it looks like we are not properly removing colored output. 

**Dev Notes**
We reproduced this on our stations with the following steps:
1. `$ claim_bosh_lite`
2. Pushed dora -- saw intended colors in output
`$ cf push dora`
3. Disabled CF CLI colors
`$ cf config --color=false`
4. Pushed Dora again -- saw colors in output still. Colors located under logs we stream from CAPI
``` 
Staging app and tracing logs...
   Downloading r_buildpack...
   Downloading nodejs_buildpack...
...
```
![image](https://user-images.githubusercontent.com/5668660/53828087-880cd300-3f31-11e9-88ce-72ce3371bce5.png)

**Comment by bwasmith** [comment]
Confirmed this is still an issue in v7 
```
$ cf -v
cf version 7.0.0-beta.29+947eaab38.2020-01-16
```

**Comment by krismarc** [comment]
@bwasmith any progress on this? it's open since 5 years 😄

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
