### ISSUE TITLE
Docs give wrong example for create-service-key

### ISSUE THREAD

**Issue by NickyBobby** [cloudfoundry/cli#1590]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
This isn't a bug per se but a mismatch of information from what the docs say and what the cli does

**What happened**
Docs give the example of `cf create-service-key mydb mykey -c '{"permissions":"read-only"}'` for the create-service-key command but we get the following response.

`Creating service key read-only-test-key for service instance mydb as uXXXXXX...
Service broker error: Invalid arbitrary parameter syntax. Please check the documentation for supported arbitrary parameters.
FAILED`

**Expected behavior**
When we run the command like this `cf create-service-key mydb mykey -c '{"read-only":true}'` the key gets created as expected.

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `cf create-service-key mydb mykey -c '{"permissions":"read-only"}'`
2. See the error message
3. Run `cf create-service-key mydb mykey -c '{"read-only":true}'`
4. See the key created successfully

**Provide more context**
- macOD High Sierra 10.13.6 iTerm
- cf version 6.43.0+815ea2f3d.2019-02-20

**Comment by bwasmith** [comment]
Hey @NickyBobby , 

Thanks for submitting this issue. Perhaps we can rope in @ljarzynski from the Docs team to see if he knows how we can handle this. 

[The doc mentioned](https://docs.cloudfoundry.org/devguide/services/service-keys.html)

**Comment by ljarzynski** [comment]
Thanks @NickyBobby for bringing this to our attention, and @bwasmith for contacting the docs team. 
Looks like that page is outdated. 
I'm going to go ahead and replace it with the correct parameters. 
This change should be reflected on the site momentarily.

**Comment by NickyBobby** [comment]
Thanks for the quick response and fix! My team and I had been struggling with this for a few days, so when we figured out that the params in the docs were bad, we thought it would be a good idea to let y'all know.
Thanks again!

**Comment by NickyBobby** [comment]
Hi, I know this issue was close but I found the example mistake on another doc site. https://cli.cloudfoundry.org/en-US/cf/create-service-key.html . Can this example be updated as well?

**Comment by nmaslarski** [comment]
Hi @NickyBobby
The JSON configuration parameters provided to the `create-service-key` command are broker dependant, i.e. one broker might accept `permissions`, another broker might accept `read-only`, and another might accept any arbitrary JSON.

Where did you get the broker from, that you are trying to run this command against ?
Was it mentioned at the docs ?
Otherwise I don't think it makes any sense to update the document, because whatever we do will only work for one particular broker.

Best,
@williammartin  and @nmaslarski

**Comment by nmaslarski** [comment]
We going to close this issue because we don't think this is issue with the CLI. If you still think it's a issue or you have any more questions, please don't hesitate to ask.

**Comment by godenlion** [comment]
When I try to connect and write default-env.json via the service key, below error message is always happened.
May I can get any help from you?


`user: CustomUIForCapex $ hana-cli serviceKey capexdatamodel-db default
⠋ 
ERROR: Error: Command failed: xs service-key capexdatamodel-db default
/bin/sh: 1: xs: not found`
