### ISSUE TITLE
cf update-buildpack --assign-stack fails with 'already exists without a stack'

### ISSUE THREAD

**Issue by ansergit** [cloudfoundry/cli#1597]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Adding a new buildpack and assign it to a new stack

**What happened**
`cf update-buildpack --assign-buildpack` fails with `Buildpack dotnet-newrelic already exists without a stack` if the unassigned buildpack has lower position than the already assigned buildpack:

**Expected behavior**
The null-stack buildpack's position relative to other buildpacks of the same name shouldn't prevent assigning its stack

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Add a new buildpack to the last position with same name to an already existing buildpack with older stack, say `cflinuxfs2`:
```
$ cf buildpacks
...
dotnet-newrelic                 25         true      false    newrelic_dotnetcore_extension_buildpack-cached-v1.0.1.zip   cflinuxfs2
dotnet-newrelic                 26         true      false    newrelic_dotnetcore_extension_buildpack-cached-v1.0.1.zip
```
2. Try to assign stack to the newly added buildpack with same name using update-buildpack
```
$ cf update-buildpack dotnet-newrelic --assign-stack cflinuxfs3
Assigning stack cflinuxfs3 to dotnet-newrelic as admin...
Buildpack dotnet-newrelic already exists without a stack
FAILED
```
3. If you change the position of the unassigned buildpack to higher than the one with stack, it works fine:
```
$ cf update-buildpack dotnet-newrelic -s cflinuxfs2 -i 26
Updating buildpack dotnet-newrelic with stack cflinuxfs2 as admin...
OK
```
```
$ cf update-buildpack dotnet-newrelic --assign-stack cflinuxfs3
Assigning stack cflinuxfs3 to dotnet-newrelic as admin...
OK
```
```
$ cf buildpacks
...
dotnet-newrelic                 25         true      false    newrelic_dotnetcore_extension_buildpack-cached-v1.0.1.zip   cflinuxfs3
dotnet-newrelic                 26         true      false    newrelic_dotnetcore_extension_buildpack-cached-v1.0.1.zip   cflinuxfs2
```

**Comment by abbyachau** [comment]
Thanks @ansergit we will look into this.

**Comment by tjvman** [comment]
Was able to reproduce both the happy and sad cases by following the provided steps. Marking as a bug.

**Comment by cf-cli-pools** [comment]
Hi @ansergit thanks for creating this bug report. We've fixed this issue and it will be in the next CF CLI release. Thanks again.
