### ISSUE TITLE
"Authorization" header is not attached within the command "cf auth client_id client_secret --client-credentials"

### ISSUE THREAD

**Issue by zyjiaobj** [cloudfoundry/cli#1598]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
```
$ cf auth my_client_id my_client_secret --client-credentials
API endpoint: https://api.ng.bluemix.net
Authenticating...
No authorization header available
FAILED
```
**What happened**
`Authorization` header is not attached in the request to `/UAALoginServerWAR/oauth/token` to get oauth-token:
```
$ CF_TRACE=true cf auth my_client_id my_client_secret --client-credentials
REQUEST: [2019-04-02T09:32:04+08:00]
GET /v2/info HTTP/1.1
Host: api.ng.bluemix.net
Accept: application/json
User-Agent: cf/6.43.0+815ea2f3d.2019-02-20 (go1.11.4; amd64 darwin)

RESPONSE: [2019-04-02T09:32:06+08:00]
HTTP/1.1 200 OK
Cache-Control: max-age=0, no-cache, no-store
Connection: keep-alive
Connection: Transfer-Encoding
Content-Type: application/json;charset=utf-8
Date: Tue, 02 Apr 2019 01:32:06 GMT
Expires: Tue, 02 Apr 2019 01:32:06 GMT
Pragma: no-cache
Server: nginx
X-Backside-Transport: OK OK
X-Content-Type-Options: nosniff
X-Global-Transaction-Id: 3992966455
{
  "api_version": "2.106.0",
  "app_ssh_endpoint": "ssh.us-south.cf.cloud.ibm.com:2222",
  "app_ssh_host_key_fingerprint": "c7:1f:89:2a:62:3b:78:a9:08:c9:33:81:fb:39:26:da",
  "app_ssh_oauth_client": "ssh-proxy",
  "authorization_endpoint": "https://login.us-south.cf.cloud.ibm.com/UAALoginServerWAR",
  "bits_endpoint": "https://bits-service.us-south.cf.cloud.ibm.com",
  "build": "1.19",
  "description": "IBM Bluemix",
  "doppler_logging_endpoint": "wss://doppler.us-south.cf.cloud.ibm.com:443",
  "min_cli_version": null,
  "min_recommended_cli_version": null,
  "name": "IBM Cloud",
  "support": "http://ibm.biz/bluemix-supportinfo",
  "token_endpoint": "https://uaa.us-south.cf.cloud.ibm.com",
  "version": 0
}


REQUEST: [2019-04-02T09:32:06+08:00]
GET /UAALoginServerWAR/login HTTP/1.1
Host: login.us-south.cf.cloud.ibm.com
Accept: application/json
Connection: close
User-Agent: cf/6.43.0+815ea2f3d.2019-02-20 (go1.11.4; amd64 darwin)

RESPONSE: [2019-04-02T09:32:07+08:00]
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store, max-age=0, must-revalidate,no-store
Content-Language: en-US
Content-Security-Policy: default-src 'self' www.ibm.com 'unsafe-inline';
Content-Type: application/json;charset=UTF-8
Date: Tue, 02 Apr 2019 01:32:06 GMT
Expires: 0
Pragma: no-cache
Set-Cookie: X-Uaa-Csrf=Kar7iw4fhc4CDiDVG4XT3y; Max-Age=86400; Expires=Wed, 03-Apr-2019 01:32:07 GMT; Path=/; HttpOnly
Strict-Transport-Security: max-age=31536000
X-Backside-Transport: OK OK,OK OK
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Global-Transaction-Id: 57150831
X-Powered-By: Servlet/3.1
X-Xss-Protection: 1; mode=block
{
  "app": {
    "version": "4.11.0"
  },
  "commit_id": "git-metadata-not-found",
  "entityID": "login.us-south.cf.cloud.ibm.com",
  "idpDefinitions": {},
  "links": {
    "login": "https://login.us-south.cf.cloud.ibm.com/UAALoginServerWAR",
    "passcode": "https://login.us-south.cf.cloud.ibm.com/UAALoginServerWAR/passcode",
    "passwd": "/forgot_password",
    "register": "/create_account",
    "uaa": "https://uaa.us-south.cf.cloud.ibm.com"
  },
  "prompts": {
    "passcode": [
      "password",
      "One Time Code ( Get one at https://login.us-south.cf.cloud.ibm.com/UAALoginServerWAR/passcode )"
    ],
    "password": "[PRIVATE DATA HIDDEN]",
    "username": [
      "text",
      "Email"
    ]
  },
  "timestamp": "2018-07-24T13:06:46+0000",
  "zone_name": "uaa"
}


API endpoint: https://api.ng.bluemix.net
Authenticating...
REQUEST: [2019-04-02T09:32:07+08:00]
POST /UAALoginServerWAR/oauth/token HTTP/1.1
Host: login.us-south.cf.cloud.ibm.com
Accept: application/json
Connection: close
Content-Type: application/x-www-form-urlencoded
User-Agent: cf/6.43.0+815ea2f3d.2019-02-20 (go1.11.4; amd64 darwin)
[PRIVATE DATA HIDDEN]

RESPONSE: [2019-04-02T09:32:09+08:00]
HTTP/1.1 401 Unauthorized
Cache-Control: no-store
Content-Language: en-US
Content-Security-Policy: default-src 'self' www.ibm.com 'unsafe-inline';
Content-Type: application/json;charset=UTF-8
Date: Tue, 02 Apr 2019 01:32:09 GMT
Pragma: no-cache
Strict-Transport-Security: max-age=2592000 ; includeSubDomains
X-Backside-Transport: FAIL FAIL
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Global-Transaction-Id: 3563098399
X-Powered-By: Servlet/3.1
X-Xss-Protection: 1
{
  "error": "unauthorized",
  "error_description": "No authorization header available"
}


No authorization header available
FAILED
```

**Expected behavior**
I should auth the endpoint with correct client_id and client_secret.

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `cf api xx` to target your cf endpoint
2. Then use your client id and secret pair to auth the endpoint `cf auth my_client_id my_client_secret --client-credentials`
3. See error

**Provide more context**
- platform and shell details
`Mac OS 10.14.4 iTerm`
- version of the CLI you are running
`cf version 6.43.0+815ea2f3d.2019-02-20`
- version of the CC API Release you are on

Note: As of January 2019, we no longer support API versions older than CF Release v284/CF Deployment v1.7.0 (CAPI Release: 1.46.0 (APIs 2.100.0 and 3.35.0).

**Comment by tjvman** [comment]
Was not able to reproduce this. Followed the provided steps and was successfully able to authenticate with client credentials. Per the [UAA documentation for client-credentials grants](http://docs.cloudfoundry.org/api/uaa/version/4.30.0/index.html#client-credentials-grant), it allows users to authenticate via client-credentials grant by *either*:
1. Sending their client id and secret in the request body (the CF CLI does this)
1. Sending their client id and secret in the `Authorization` header.
It seems that the CF foundation you're targeting has somehow modified that behavior.
 
The text of that error does not appear anywhere in the UAA source code, which makes me inclined to believe that UAA is not responsible for returning this error and there may be some sort of additional (possibly proprietary) layer on top of the basic open-source UAA.

I'd advise you to contact the support/operations team for the targeted foundation to determine how they restricted the behavior of the `/oauth/token` endpoint, as the behavior you're seeing contradicts the UAA documentation. 


Since we don't have a way to repro this and the UAA docs refer to the current `cf auth --client-credentials` workflow as supported, I am closing this issue. Please feel free to reopen if you find additional details/steps to repro without needing to target Bluemix specifically.
