### ISSUE TITLE
Extend command "cf login" with  "--origin"

### ISSUE THREAD

**Issue by torsten-sap** [cloudfoundry/cli#1599]
**Please provide details on the following items. Failure to do so may result in deletion of your feature request.** 
The UAA allows the login with multiple origins (e.g. uaa, ldap, someSamlProvider, someOidcProvider). The command "cf auth" already provides the parameter "--origin" with which the user can specify it for login. However, this parameter is missing for command "cf login". 

**What's the user value of this feature request?**
The only way to login with an origin (that is not the UAA default) is currently:
- cf api ...
- cf auth --origin uaa user password
- cf target ...
This means that three commands instead of one command are necessary. Further, the user needs to enter the password unprotected to the console. 

**Who is the functionality for?**
Everybody who uses multiple origins for login to the UAA. 

**How often will this functionality be used by the user?**
Every time a user does a login.

**Who else is affected by the change?**
No breaking change.

**Is your feature request related to a problem? Please describe.**
Yes, the user in annoyed to type his password unprotected to the console. Further, it is not acceptable for users from my point of view with regards to security.

**Describe the solution you'd like**
Extend command "cf login" with  "--origin"

**Describe alternatives you've considered**
Command "cf auth" with "--origin" that has severe shortcomings as mentioned above.

**Comment by abbyachau** [comment]
See related: https://github.com/cloudfoundry/cli/issues/1272
