### ISSUE TITLE
Extend command "cf set-org-role"/"cf unset-org-role" with "--origin"

### ISSUE THREAD

**Issue by torsten-sap** [cloudfoundry/cli#1602]
**Please provide details on the following items. Failure to do so may result in deletion of your feature request.** 
The UAA allows the login with multiple origins (e.g. uaa, ldap, someSamlProvider, someOidcProvider). If multiple origins are used and the username is identical in at least two origins, the commands "cf set-org-role"/"cf unset-org-role" does not work.

**What's the user value of this feature request?**
If the commands "cf set-org-role"/"cf unset-org-role" are extended with "--origin" it can work with multiple origins even if the username is identical in at least two origins. Currently, the commands fail with an error message similar to the following:
"Server error, status code: 400, error code: 20006, message: The user exists in multiple origins. Specify an origin for the requested user from: 'ldap', 'uaa'"
Note that the specification of the origin as proposed by the error message is not possible.

**Who is the functionality for?**
Everybody who uses multiple origins for login to the UAA. Because there is no possibility to ensure that usernames of different origins are different.

**How often will this functionality be used by the user?**
Every time when a org role needs to be assigned or removed.

**Who else is affected by the change?**
No breaking change.

**Is your feature request related to a problem? Please describe.**
Yes, the admin in annoyed that he cannot assign/remove org roles with the CLI when multiple origins are used and the username exists twice. Note that this org role assignment/removal may happen manually (via command "cf cli"), programatically (via script) and also through some custom UI. The resolution of such situations are a pain in the neck.

**Describe the solution you'd like**
Extend command "cf set-org-role"/"cf unset-org-role" with "--origin".

**Describe alternatives you've considered**
CURL as mentioned here:
https://docs.cloudfoundry.org/cf-cli/getting-started.html#multi-origin
But this is not acceptable from the admin perspective.

**Comment by abbyachau** [comment]
Hi @torsten-sap this feature was released on today on [v7.0.0-beta.27](https://github.com/cloudfoundry/cli/releases/tag/v7.0.0-beta). Please let us know if you have any feedback, thanks. Closing this issue as completed.
