### ISSUE TITLE
Extend command "cf delete-user" with "--origin"

### ISSUE THREAD

**Issue by torsten-sap** [cloudfoundry/cli#1603]
**Please provide details on the following items. Failure to do so may result in deletion of your feature request.** 
The UAA allows the login with multiple origins (e.g. uaa, ldap, someSamlProvider, someOidcProvider). Because of that the CLI provides already the command "cf create-user" with option "--origin". However, the command "cf delete-user" does not support the option "--origin".

**What's the user value of this feature request?**
The admin can currently create UAA users for multiple origins (by using command "cf create-user" with option "--origin"). However, the admin cannot delete the user for a specific origin.

**Who is the functionality for?**
Everybody who uses multiple origins for login to the UAA.

**How often will this functionality be used by the user?**
Every time when a user needs to be deleted.

**Who else is affected by the change?**
No breaking change.

**Is your feature request related to a problem? Please describe.**
Yes, the admin is annoyed as he cannot delete users via the CLI (that were created using the CLI).

**Describe the solution you'd like**
Extend command "cf delete-user" with "--origin".

**Describe alternatives you've considered**
Usage of the UAA API:
https://docs.cloudfoundry.org/api/uaa/version/4.30.0/index.html#delete-4

**Comment by abbyachau** [comment]
Hi @torsten-sap @tack-sap we've completed this work on cf7 CLI and plan to release this enhancement in `7.0.0-beta.26` - see this [release marker](https://www.pivotaltracker.com/story/show/169043597) for more information, or watch our release page for the release. Please let us know if you have any questions/feedback.
