### ISSUE TITLE
Invalid character in the host name

### ISSUE THREAD

**Issue by TEAMBTG** [cloudfoundry/cli#1604]
Having an error while executing the command

`cf create-service postgresql v9.6-dev itemsdb`

```
C:\Users\Administrator\Downloads\smbmkt-master>cf login

API endpoint> cf create-service postgresql v9.6-dev itemsdb
FAILED
Error building request: parse https://cf create-service postgresql v9.6-dev item
sdb/v2/info: invalid character " " in host name
```

Is there any command that I've missed?

**Comment by tjvman** [comment]
@TEAMBTG You're inputting a `create-service` command at the prompt for an API endpoint, which is not a valid input. You should provide the API endpoint of the CF you wish to target at this prompt (or with the `-a` flag) and log in before attempting to create a service.
