### ISSUE TITLE
`cf copy-source` space searches are case-sensitive

### ISSUE THREAD

**Issue by cwlbraa** [cloudfoundry/cli#1605]
**Describe the bug and the command you saw an issue with**
When specifying org AND space, if a lowercase `-s` parameter is used to try to copy-source in a space that is normally represented in all caps, the command will fail to find the space as follows:

```
Could not find space dev in organization system
```

**Expected behavior**
It should find the allcaps-persisted space.

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
```
cf create-space DEV
cf target -o system -s dev
cf push source-app
cf push target-app
cf copy-source source-app target-app -v -o system -s dev
```
The final command will return:
```
Could not find space dev in organization system
```
The bug looks like it's here:
https://github.com/cloudfoundry/cli/blob/f0b289bf9eb5e56fd8dccd2012f2dfc8b6c2ae06/cf/commands/application/copy_source.go#L149-L156

**Comment by tjvman** [comment]
Was able to reproduce by following the provided steps. Marking as bug.

**Comment by hemchander23** [comment]
Hi,

Thought I'd contribute to this issue. 

I started with analyzing the copy_source.go file as @cwlbraa mentioned. The quickest solution would be to use `strings.EqualFold(s.Name,targetSpace)`. However, `buildCopyString `would output the given space name (which may or may not be the *actual* space name)

https://github.com/hemchander23/cli/blob/da98b6335d2c1e87f1e82d939cec99a8bb19233c/cf/commands/application/copy_source.go#L191

Although this step would obtain the end result, I thought I would make it much more better.

I made use of `cmd.orgRepo.FindByName` and `cmd.spaceRepo.FindByNameInOrg` to obtain the actual org and space names which will be passed in the buildCopyString and also in subsequent operations. 

Let me know if this is good ? 

https://github.com/hemchander23/cli/blob/da98b6335d2c1e87f1e82d939cec99a8bb19233c/cf/commands/application/copy_source.go#L108-L124

In my humble opinion, I feel 
https://github.com/hemchander23/cli/blob/da98b6335d2c1e87f1e82d939cec99a8bb19233c/cf/commands/application/copy_source.go#L164-L189
could be redundant ?

Will be making necessary changes accordingly along with tests if you can kindly confirm if the approach is right.

```
mr0x17@LAPTOP-TJT1NIMO:/usr/local/go/src/code.cloudfoundry.org/cli/out$ ./cf copy-source taskmanagernjs 75F7ckm2s13VwwGKer-taskmanagernjs -s deV -o PReLIVE
Copying source from app taskmanagernjs to target app 75F7ckm2s13VwwGKer-taskmanagernjs in org prelive / space dev as dev@he.ms...
```

**Comment by bwasmith** [comment]
Hello @cwlbraa,

This issue was fixed with these commits:
- [copy-source: Space name is case-insensitive](https://github.com/cloudfoundry/cli/commit/ca235907ea93f6dc9be98b38e9e4902c8d9f6acd)
- [copy-source: Output actual space name](https://github.com/cloudfoundry/cli/commit/d82ac9d45756440f5aa7d7a3591a13574ea30a08)

They will be on the next release.

Best,
Brendan
