### ISSUE TITLE
Request: as an admin `set-label info` for a global info resource; which is returned within /v2/info

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cli#1607]
I'm very excited for the `cf7 set-label <resource>` feature - for me it will allow developers to start documenting metadata about where is the application source code, which CI pipeline deploys etc, etc

Whilst I can see that `set-label` is a developer/user focused feature, perhaps it can now be turned to answer the question of how an operator can return additional metadata and URLs of associated services in the `/v2/info` endpoint.

That is, I'd like admins to be able to run `cf7 set-label info ourthing_endpoint=https://ourthing.system.com` and these values would be included in the `/v2/info` JSON.

**Comment by abbyachau** [comment]
Hi @drnic thanks. We don't have any current plans to support metadata on `info`. I'm cc'ing @Gerg here who might be thinking about this use case on V3. 

(cc @tcdowney @ssisil)

**Comment by Gerg** [comment]
@drnic There is [this manifest property](https://bosh.io/jobs/cloud_controller_ng?source=github.com/cloudfoundry/capi-release&version=1.78.0#p%3dcc.info) that I think does what you are looking for. This is not currently exposed anywhere on v3, but likely will be in the future.

**Comment by drnic** [comment]
@Gerg ooh excellent; I'll explore info.custom and see if it helps platform operators document additional endpoints etc to users/cli plugins.
