### ISSUE TITLE
Unexpected parsing of empty string

### ISSUE THREAD

**Issue by WalterS** [cloudfoundry/cli#1615]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Provide details on what you were trying to do (and why).

Depending on landscape configuration, we set "--skip-ssl-validation" or not like this in a Bash script:
```
export SSL_VALIDATION=''
[[ "SOME_VARIABLE" == "true" ]] && SSL_VALIDATION="--skip-ssl-validation"
# ...
cf api "SSL_VALIDATION" https://example.net
```
**What happened**
cf didn't report an error (= return code 0), but didn't set the API endpoint.

Other `cf` commands fail unexpected

**Expected behavior**
1. Don't parse empty strings as arguments
2. Exit with return code > 0 if command fails

**To Reproduce**
1. Run `cf api "$NONEXISTENT" https://example.net; echo "RC: $?"` (use an existing endpoint)
3. See error:
```
api endpoint:   https://example.net
api version:    2.133.0
Not logged in. Use 'cf login' to log in.
RC: 0
```

**Provide more context**
Ubuntu 18.04 with Bash version 4.4.19(1)
cf version 6.43
CC API 2.133.0

**Comment by abbyachau** [comment]
Hi @WalterS thanks for creating this bug report. We will review and get back to you as soon as we can, thanks!

**Comment by acrmp** [comment]
Hi @WalterS,

Sorry for the delay in getting back to you. We don't have any special support for ignoring empty arguments. It seems that this might be helpful for your case but potentially confusing in other cases when combined with positional arguments.

Your example does show that `cf api` ignores positional arguments after the optional URL. This is consistent with [an exploration](https://www.pivotaltracker.com/story/show/161904294) the team did some time ago to understand how extra positional arguments were treated.

I would recommend avoiding the `--skip-ssl-validation` flag and using certificates signed by a trusted certificate authority.

If you really do want to pass `--skip-ssl-validation` you could use a more verbose version:

```bash
if [[ "$SKIP_SSL_VALIDATION" == "true" ]]; then
  cf api --skip-ssl-validation https://api.example.com
else
  cf api https://api.example.com
fi
```

I'm going to close this issue and say that removing empty arguments is not something we will do at the moment. Please feel free to re-open.

Thanks,

Andrew.
