### ISSUE TITLE
Extend output of command "cf space-users" with origin of the user

### ISSUE THREAD

**Issue by torsten-sap** [cloudfoundry/cli#1622]
**Please provide details on the following items. Failure to do so may result in deletion of your feature request.** 
The UAA allows the existence of the very same username in multiple origins (e.g. uaa, ldap, someSamlProvider, someOidcProvider). The command "cf space-users" list the usernames of the users that have some org roles assigned (SPACE MANAGER, SPACE DEVELOPER or SPACE AUDITOR). If an username exists in multiple origins (e.g. uaa and ldap) it is not clear which user actually has the corresponding role assigned. It could be either the user with origin ldap or the one with origin uaa. The request is to extend the output of the command by the origin of the user, e.g. "myuser (uaa)".

**What's the user value of this feature request?**
The value is that the output of both, username and origin, identifies the user uniquely. This is currently not the case as only the username is provided.

**Who is the functionality for?**
Everybody who uses the command "cf space-users" and more than one origin for users. 

**How often will this functionality be used by the user?**
Every time a user executes "cf space-users".

**Who else is affected by the change?**
No breaking change.

**Is your feature request related to a problem? Please describe.**
Yes, the problem that a user cannot identified uniquely by the output of command "cf space-users".

**Describe the solution you'd like**
The output of the command "cf space-users" may look as follows (as an example):
```
Getting users in org myorg / space myspace as myuser

SPACE MANAGER
  somemanageruser (uaa)

SPACE DEVELOPER
  myuser (uaa)

SPACE AUDITOR
  someauditoruser (ldap)
```
Note that the username "myuser" in the first line can stay as it is as the user knowns with which origin he logged in.

**Describe alternatives you've considered**
There are no alternatives that I am aware of. If a user is listed by the command "cf space-users" you may try to assign him the same role again. If this does not work, he probably has the role already. But even such approaches do only work if the username is only listed once.

**Comment by abbyachau** [comment]
Proposed workflow for adding this feature: https://docs.google.com/document/d/1wFXhxkh0a5UttNnPcx37o7ByAczGciCVJqVZ2D2lJGg/edit

**Comment by bwasmith** [comment]
It looks like this was done as a part of `space-users` for the v7 CLI:
https://www.pivotaltracker.com/story/show/164450995
