### ISSUE TITLE
Update cf marketplace help text to include the correction Usage example for --no-plans

### ISSUE THREAD

**Issue by abbyachau** [cloudfoundry/cli#1623]
**Please fill out the issue checklist below and provide ALL the requested information.**

Missing example option in the Usage section of the cf marketplace help 
```
○ → ./cf m --help
NAME:
   marketplace - List available offerings in the marketplace

USAGE:
   cf marketplace [-s SERVICE]

ALIAS:
   m

OPTIONS:
   -s              Show plan details for a particular service offering
   --no-plans      Hide plan information for service offerings
```
- [ ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ ] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Provide details on what you were trying to do (and why).

**What happened**
A clear and concise description of what happen.

**Expected behavior**

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `cf ...`
2. Bind a service `cf bind-service`
3. See error

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm)
- version of the CLI you are running
- version of the CC API Release you are on

Note: As of January 2019, we no longer support API versions older than CF Release v284/CF Deployment v1.7.0 (CAPI Release: 1.46.0 (APIs 2.100.0 and 3.35.0).

**Comment by williammartin** [comment]
I've moved the tracker story to the SAPI backlog. Thanks for the issue!

**Comment by abbyachau** [comment]
Thanks @williammartin!
