### ISSUE TITLE
Invalid JSON response when trying to push to server

### ISSUE THREAD

**Issue by andyalbert** [cloudfoundry/cli#1659]
- [ Done] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ Done] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ Not sure] I am reporting a bug that others will be able to reproduce.

After logging into my organization account, I tried to push a code with manifest file, but I keep receiving an 'Invalid JSON content from server: invalid character '<' looking for beginning of value' error, I enabled tracing and found that the server send me a webpage in one of the responses that caused that issue.

**What happened**
Error with the following message: 'Invalid JSON content from server: invalid character '<' looking for beginning of value'

**Expected behavior**
The push should be successful.
**To Reproduce**
Couldn't reproduce on other devices.

**Provide more context**
- platform: Windows
- version of the CLI: Latest

**Comment by abbyachau** [comment]
Hi @andyalbert can you give us more information so we can help with this issue, i.e. the trace output. Thanks!

**Comment by andyalbert** [comment]
Sorry for the late reply, I couldn't post that data as it's contacting my organization server, I managed to solve it using another config.json file from another teammate whose installation work properly.
