### ISSUE TITLE
Parallel deploy app to cf platform with pipeline,happened cf login problem

### ISSUE THREAD

**Issue by bad2cat** [cloudfoundry/cli#1688]
when i parallel deploy my app to cf,it's occured following problem occasionally:
  
   Warning: Error read/writing config: unexpected end of JSON input for /root/.cf/config.json

   i've tried something method as follow:
      1)change CF_HOME to another folder
      2)chmod 755  ~/.cf/config.json
      3)and login in every parallel stage
   but still not work.
  The cf version and cli version is latest.
  i hope someone can give a solution, the problem already troubled me for a long time

**Comment by abbyachau** [comment]
Hi @bad2cat thanks. Could you provide details on the operating system you are using. Also, please review, if you haven't already, closed issues which might be a related issue. For example: https://github.com/cloudfoundry/cli/issues/1199

**Comment by bad2cat** [comment]
Hi @abbyachau thanks for reply.I've already review the related issue.
And i've tried methods which mentioned in related issue,but still not resolved this problem.
I use k8s cluster,the CLI is run in pods which pulled cli image from private repo every time.

**Comment by abbyachau** [comment]
Hey @bad2cat this is going to be difficult for us to help you debug unfortunately; the quickest way to get help is to perhaps go on Slack #cloudfoundry and see if anyone can help you with your specific question. It is a good place for the Community to ask questions and to see if anybody else has a similar issue. I'm closing this issue, thank you.
