### ISSUE TITLE
`cf uups <svc>` without params deletes values

### ISSUE THREAD

**Issue by spgreenberg** [cloudfoundry/cli#1694]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [X] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
If you run `cf uups <some-service>` without any flags (like -p), existing key/values are overwritten. This is in contrast to the message displayed by the CLI "No flags specified. No changes were made."

**What happened**
The existing key/values are removed from the UPSI.

**Expected behavior**
The existing key/values should not be changed.

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:

1. Be sure you have an app (any app) available to bind a service instance to.

2. Create a UPSI with key/values: `cf cups upsi -p '{"some-key":"some-value"}'`
3. Bind the UPSI to an app: `cf bs app upsi`
4. Observe the VCAP_SERVICES envar to ensure key/values in the credentials block are correct. `cf env app`

```
...
{
 "VCAP_SERVICES": {
  "user-provided": [
   {
    "binding_name": null,
    "credentials": {
     "some-key": "some-value"
    },
    "instance_name": "upsi",
    "label": "user-provided",
    "name": "upsi",
    "syslog_drain_url": "",
    "tags": [],
    "volume_mounts": []
   }
  ]
 }
}
...
```

5. Run update UPSI without parameters and observe the "No changes" message: `cf uups upsi`

```
Updating user provided service upsi in org blah / space blah as blah...
OK
TIP: Use 'cf restage' for any bound apps to ensure your env variable changes take effect
No flags specified. No changes were made.
```

6. Observe the key/values in the credentials block are now missing: `cf env app`

```
...
{
 "VCAP_SERVICES": {
  "user-provided": [
   {
    "binding_name": null,
    "credentials": {},
    "instance_name": "upsi",
    "label": "user-provided",
    "name": "upsi",
    "syslog_drain_url": "",
    "tags": [],
    "volume_mounts": []
   }
  ]
 }
}
...
```

**Provide more context**

MacOS
cf version 6.45.0+5f9ff16f9.2019-06-03
Using Pivotal Web Services

CC: @mxplusb

Note: As of January 2019, we no longer support API versions older than CF Release v284/CF Deployment v1.7.0 (CAPI Release: 1.46.0 (APIs 2.100.0 and 3.35.0).

**Comment by abbyachau** [comment]
Hi @williammartin please would you folks be able to help with this one?

**Comment by williammartin** [comment]
Yep, this is near the top of our backlog but we are going to refactor the command first.

**Comment by blgm** [comment]
@spgreenberg, thank you for raising this issue. You are quite correct that this is unexpected and unhelpful behaviour. We have just pushed a change to update the `cf update-user-provided-service` command so that it only makes the updates that you specify. Where no updated are specified, no changed will be made. Unfortunately it just missed the last release of the `cf` CLI, but should be included in the next release.
