### ISSUE TITLE
Cf Curl for ORG list only 100 Apps as per PageNUM

### ISSUE THREAD

**Issue by Muruganfly03** [cloudfoundry/cli#1695]
Hi Team

We have more that 130+ apps in the specific ORG(Have only one space). I am trying to collect the apps details. When i try the below commands i an able to get 100 apps(Based on RESULTPAGE). But if try more than 100 i am getting the output 0. How we can get all application mapped to specific ORG and Space.

-sh-4.2$ cf curl /v2/spaces/69b7f1c3-b801-48d5-9bf7-5fc7491b32d2345/apps?results-per-page=100 | grep guid | grep -v "space_guid"| grep -v "stack_guid" | grep -v "detected_buildpack_guid" |wc -l
100
-sh-4.2$ cf curl /v2/spaces/69b7f1c3-b801-48d5-9bf7-5fc7491b32d2345/apps?results-per-page=110 | grep guid | grep -v "space_guid"| grep -v "stack_guid" | grep -v "detected_buildpack_guid" |wc -l
0
-sh-4.2$ cf apps | wc -l
136

**Comment by waterlink** [comment]
@Muruganfly03 

That makes sense that there is a limit on how big these pages can get. It’s a standard way to handle pagination. 100 seems to be the maximum.

Have you tried to get multiple pages using the `page=1` and `page=2` query parameters? (see docs: https://apidocs.cloudfoundry.org/9.3.0/spaces/list_all_apps_for_the_space.html)

**Comment by Muruganfly03** [comment]
Hope it helps me! I will need to use my logic to list all Apps now. Thanks Oleksii :)

**Comment by abbyachau** [comment]
Closing this issue - thanks much for the contribution @waterlink - appreciate the help.

@Muruganfly03 please feel free to reopen if you have any further feedback/questions.
