### ISSUE TITLE
cf cli should report errors to the stderr instead of stdout

### ISSUE THREAD

**Issue by r0mk1** [cloudfoundry/cli#1700]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Some cli commands report an error to the stdout.  This leads to problems when their output is piped to other applications: grep, awk, etc.

**What happened**
The error message goes to a pipeline instead of being printed to a terminal.

**Expected behavior**
The error message should be printed to the stderr which by default prints to the terminal like regular tools:
```
ls /xyz | grep abc
ls: cannot access '/xyz': No such file or directory
```

**To Reproduce**
Steps to reproduce the behaviour; include the exact CLI commands and verbose output:
1. ```cf logout```
2. ``` cf a``` shows the error: "FAILED  Not logged in. Use 'cf login' to log in."
3. ```cf a | grep xyz``` outputs nothing but should print the error to the terminal.
4. Same to the ```cf r```.
5. Some commands do this correctly, e.g. ```cf s``` and ```cf app```.

**Provide more context**
- ```Linux arch 5.0.2-arch1-1-ARCH #1 SMP PREEMPT Thu Mar 14 18:47:49 UTC 2019 x86_64 GNU/Linux```
- ```cf version 6.45.0+5f9ff16f9.2019-06-03```
- version of the CC API doesn't matter

**Comment by acrmp** [comment]
Hi @r0mk1,

Thanks for opening this issue. You are right - the CLI is currently inconsistent in its use of stderr/stdout.

The team has been re-implementing commands for some time. Commands that print errors to stderr are normally the re-implemented commands, where-as the older commands continue to print errors to stdout.

Are you using grep awk etc interactively or are you trying to script against the CLI? We'd like to get to a position where we can offer a stable interface for scripting that would still allow us to change our output over time without breaking existing scripts.

Thanks,

Andrew.

**Comment by r0mk1** [comment]
Hi Andrew,

Thanks for the detailed answer.

>Are you using grep awk etc interactively or are you trying to script against the CLI?

Mostly interactively when need to find something in our environments.  Most of my commands are looking like this:
```
cf a | grep my-app-prefix
```
And was confused multiple times when got an empty result and considered the app not deployed mistakenly blaming our ops team though it was my login token expired :(

>We'd like to get to a position where we can offer a stable interface for scripting that would still allow us to change our output over time without breaking existing scripts.

It can be really hard to change the output format without breaking any of the existing scripts.  On the other hand proper scripts would check the exit code instead of relying solely on the output avoiding  problems I have in interactive sessions.

Regards,
Roman

**Comment by bwasmith** [comment]
Hello @r0mk1,

Thank you for the feedback about how you are scripting against the CLI. 

> It can be really hard to change the output format without breaking any of the existing scripts. 

The team is considering the possibility of a `--json` option which would allow us to give a more stable way to script against the CLI. The lack of a good scripting solution is in the minds of the CLI team and on the CLI roadmap, albeit somewhat distant. 

We do not expect a v6 CLI to be fully consistent with its stderr and stdout, as not all commands will be rewritten in v6. I would expect to see better consistency with the upcoming v7 CLI.

Sorry to hear that this is causing difficulty for your workflows. We do appreciate the feedback on how the CLI is being used and where it is insufficient. 

Best,
Brendan

**Comment by a-b** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket.
