### ISSUE TITLE
"cf login " interactive password prompt fails on cygwin

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#171]
password should be interactively prompted for when -p is omitted, regardless of whether -u was specified.

At least, it should be more user-friendly to remind users that if they prefer interactive login (to avoid having password recorded in their shell history) then they should omit both password *and* login, otherwise the password won't be prompted and auth will fail:

```
$ cf login -a https://api.run.pivotal.io -u user@domain.com -o myorg
API endpoint: https://api.run.pivotal.io
Authenticating...
Credentials were rejected, please try again.
Authenticating...
Credentials were rejected, please try again.
Authenticating...
Credentials were rejected, please try again.
FAILED
Unable to authenticate.

API endpoint: https://api.run.pivotal.io (API version: 2.4.0)
Not logged in. Use 'cf.exe login' to log in.

$ cf --version
C:\Program Files (x86)\CloudFoundry\cf.exe version 6.1.2-6a013ca
```

**Comment by hagemt** [comment]
Another +1 here. As for the story, after signing up, all I get is: "
You are not allowed to view the requested page."

**Comment by hao5ang** [comment]
+1

**Comment by maximilien** [comment]
-1 for cygwin or windows...

I kid, I kid, of course. We <3 our Windows users. Cheers.

**Comment by gberche-orange** [comment]
For windows users, a bash shell with productive features (searching in the history, clipboard cut/paste, completion on file path, alias to set CF_HOME to switch among CF instances...), makes a real difference in term of productivity when using the CF CLI.

I currently work around this issue using ``cf auth login pwd`` instead of ``cf login``.

**Comment by dhudici** [comment]
+1

**Comment by michaellihs** [comment]
+1 for implementing Cygwin support or at least providing a workaround with the current "bug"

**Comment by quanghungb** [comment]
+1 for Cygwin ;)

**Comment by piyush76** [comment]
it is the issue with cygwin. can't login

**Comment by roelensw** [comment]
another +1 for cygwin ( Git Bash actually )

**Comment by bigred-xx** [comment]
+1

**Comment by jeremyrobertson** [comment]
+1

**Comment by dkoper** [comment]
Thanks everbody for speaking up!

I have created an exploratory story to find out what's involved:
https://www.pivotaltracker.com/story/show/121841829

We currently do platform specific stuff to make the interactivity work, and the team's initial concern was that golang may not support what we need to implement this. This will be investigated as part of this story.

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
FYI, having spent a day or so investigating, the team has found no way to make this work on Windows. 

It seems the required APIs are not available to us in Golang.
We'll try one more experiment (calling the Unix APIs - not sure how that will go in cygwin) just to show how desperately we'd want this to work.
If that fails, we may explore a way to at least fail with a better message instead of the loop we see now.

In the meantime, if you have any other suggestions, or can provide us with Golang sample code to make it work, we'd love to take a look!

**Comment by dkoper** [comment]
PS: the issue seems to be the same as https://github.com/golang/go/issues/13088.

**Comment by ajayroy2006** [comment]
I was facing the same issue, fixed it by setting proxies , by running following command on windows
SET HTTP_PROXY=http://proxy.yourorganisation.com:port
SET HTTPS_PROXY=https://proxy.yourorganisation.com:port

**Comment by dkoper** [comment]
I have recorded this as a [known issue](https://github.com/cloudfoundry/cli#known-issues). Closing as a `won't fix` while we wait for golang to support the APIs/behaviour we need.

**Comment by michaellihs** [comment]
@dkoper thx for your updates!

**Comment by h0nIg** [comment]
it seems that https://github.com/golang/go/issues/13104 was solved, will there be an update?

**Comment by h0nIg** [comment]
@dkoper what do you mean with "or option -f to suppress the prompts." on https://github.com/cloudfoundry/cli#known-issues

**Comment by dkoper** [comment]
@h0nIg We're still waiting for Golang to add support for this (see the golang issue I linked to, to which you also added a comment).

The `option -f to suppress the prompts` referred to prompts in delete commands. But I just verified they work fine, so maybe that was a mistake. I have updated the known issue entry.
PS: Comments on closed issues are hard to track with our tooling - I just found your comments by co-incidence. Better raise a new issue, re-open or ask on Slack or the CF Dev mailing list.

Cheers,
Dies Koper
CF CLI PM

**Comment by jmprice** [comment]
I haven't tested this in Cygwin specifically, but the same symptoms exists when using the cli from within a git bash shell on Windows.  Adding the following alias to your .bashrc file seems to work:

alias cf='winpty cf'

or just run this from your shell:   echo alias cf="'winpty cf'" >> ~/.bashrc

I hope this helps.

**Comment by blastdan** [comment]
I ran into an issue while using Babun. It doesn't seem to install winpty by default so the ` alias cf="'winpty cf'" >> ~/.bashrc` doesn't work.

I installed https://github.com/tiangolo/babun-docker that tries to fix the same problem for docker and babun. Babun also uses zsh by default so running

`echo alias cf="'winpty cf'" >> ~/.zshrc`

is more appropriate

**Comment by housseinimaiga** [comment]
+1

**Comment by saipriyabalu** [comment]
I was also facing the same issue. But I tried using in the command prompt, it works well.

**Comment by cziaul** [comment]
Also facing the same issue with git. Then as per above suggestion, I tried using cmd but getting below:

Password>
Authenticating...
Credentials were rejected, please try again.


API endpoint:   https://api.local.pcfdev.io (API version: 2.75.0)
Not logged in. Use 'cf login' to log in.
FAILED
Unable to authenticate.

As you can see api.local.pcfdev.io. I have local VM, which password I should use? any default password?

**Comment by cziaul** [comment]
Just found out local default username and password

$ cf login -a https://api.local.pcfdev.io --skip-ssl-validation
Email: user
Password: pass

**Comment by aarunrohit** [comment]
Hi All,

Please try bx login, it works. 

regards,
Arun

**Comment by aarunrohit** [comment]
Hi All, 

Please follow these instructions. 

1.
Use the below command to verify your credentials. 
cf login -a https://api.example.com -u username@example.com -p Password
2. 
use login -a $url -u xxx@abc.com -p xxxxx instead of cf login -a $url command if you are using this in a script.  

Thanks,
Arun

**Comment by jeemis23** [comment]
@Arun
use ** cf login -a $url -u xxx@abc.com -p xxxxx** instead of cf login -a $url command, works for me

**Comment by dkoper** [comment]
FWIW, `cf login` on my Cygwin bash seems to work fine now.

While installing the latest Git on Windows, I noticed in its release notes:
> Some console programs, most notably non-MSYS2 Python, PHP, Node and OpenSSL, interact correctly with MinTTY only when called through winpty (e.g. the Python console needs to be started as winpty python instead of just python).

So @jmprice's suggestion seems to be their recommended work around.

**Comment by bakoontz** [comment]
Running under the  cygwin TERM allows for interactive prompts to work.  C:\cygwin64\Cygwin.bat will do this.  And you still get bash.

**Comment by loganmzz** [comment]
For Windows GitBash users, it works when using bash.exe (located under `bin/` subdirectory of Git installation directory). Which is useful if you're using integrated terminals from an IDE (e.g. VS Code)

**Comment by paulvi** [comment]
Yes, indeed. It works if when launching Git Bash as "C:\Program Files\Git\bin\bash.exe"
![image](https://user-images.githubusercontent.com/1614482/57516455-53f5ca00-7347-11e9-820c-11eb58ae1503.png)


@loganmzz if it works under some flavor of Git Bash, than it is not issue of go referenced here as https://github.com/golang/go/issues/13088, but issue of configuring Git Bash or some Git Bash default settings...

**Comment by ksndrsllvn** [comment]
This was a little tricky to find, so hopefully anyone having this issue that wants to just be able to 

> I haven't tested this in Cygwin specifically, but the same symptoms exists when using the cli from within a git bash shell on Windows. Adding the following alias to your .bashrc file seems to work:
> 
> alias cf='winpty cf'
> 
> or just run this from your shell: echo alias cf="'winpty cf'" >> ~/.bashrc
> 
> I hope this helps.

Hopefully anyone having this issue that still wants to use git bash finds the comment above. It worked for me.

(This is what I posted in my group's chat:
2) git bash will not work unless you go through some hoops (you can put your password in plain text on the same line with the -p flag (which is generally a *BAD IDEA*), use git cmd, run git bash from Git/bin, you can sign in under another service and go back to using git bash, _*OR you can actually fix the problem by setting an alias in your Git/etc/bash.bashrc with "alias cf='winpty cf'" according to a comment in the bottom of this cf issue page:*_ )
