### ISSUE TITLE
The use of ${random-word} creates a new route with every 'cf push'

### ISSUE THREAD

**Issue by ramnivas** [cloudfoundry/cli#173]
If I have a manifest.yml with the following entry:

```
host: cloud-services-test-${random-word}
```

Every time I push the application (`cf push`), it creates a new route, instead of reusing the one that is already bound to the application.

Observed this regression (about a week or two back, `cf` exhibited the right behavior with the same manifest.yml) with `cf` version `6.1.2-6a013ca` as well as today's master build `6.1.2-91a805a`.

**Comment by dsyer** [comment]
Please re-open this one. It's a regression and it's going to drive people nuts.
