### ISSUE TITLE
Release v6.46.0 for windows 64-bit contains incorrect version of CLI

### ISSUE THREAD

**Issue by aparolin** [cloudfoundry/cli#1730]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [X] I reviewed open and closed github issues that may be related to my problem.
- [X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [X] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
I have downloaded the release 6.46 of the CLI for Windows 64-bit and the CLI contained in both the binaries zip and delivered by the installer has the version 7.0.0-beta, which seems to have experimental features in the `push` command.

```
cf push my-app
This command is in EXPERIMENTAL stage and may change without notice

Updating app my-app...
Pushing app my-app to org *** / space dev as ************...
Getting app info...
Mapping routes...
API endpoint not found at 'https://******************/v3/routes?domain_guids=**********&hosts=my-app&paths='
FAILED

cf -v
7.0.0-beta.24+15564551a.2019-07-16
```

**What happened**
The version of CLI contained in the release 6.46 for Windows 64-bit is not correct.

**Expected behavior**
The version of CLI delivered by release 6.46 for Windows 64-bit should be 6.46 and the push should not be experimental.
I have checked the release 6.46 for Linux and the version of the CLI is correct. 

**To Reproduce**
Download the release 6.46 for windows 64-bit ([binaries](https://packages.cloudfoundry.org/stable?release=windows64-exe&version=6.46.0&source=github-rel) or [installer](https://packages.cloudfoundry.org/stable?release=windows64&version=6.46.0&source=github-rel))
Check the version of the CLI using `cf -v`.

**Provide more context**
- platform: Windows 64-bit
- version of the CLI you are running: Downloaded 6.46, but the packages deliver 7.0.0-beta

**Comment by bwasmith** [comment]
Hello @aparolin ,

Thank you very much for opening this issue. 

We confirmed the incorrect behavior on our end. We believe it is a result of the v7 CLI team beginning their release process, and accidentally interfering with the v6 releases. 

We will take the necessary steps to fix this now. 

Thank you,
Brendan and @acrmp

**Comment by bwasmith** [comment]
@aparolin This is fixed. The problems seemed to only be with the Windows related releases. We have tested the 64 bit Windows installer and binary. 

If you continue to see problems, please feel free to reopen this issue.
