### ISSUE TITLE
Token Override

### ISSUE THREAD

**Issue by johannaratliff** [cloudfoundry/cli#1746]
**What's the user value of this feature request?**
As a user of the CLI, I would like the same power I have to interact with CAPI through `curl <CAPI domain>/v3/<some endpoint>` but with the benefit of the CLI (and its' plugins) formatting.

**Who is the functionality for?**
Anyone who interacts with CAPI with more than just their oauth token.

**How often will this functionality be used by the user?**
As a developer of an app that acts on behalf of a UAA client instead of on behalf of myself, frequently.

**Who else is affected by the change?**
This wouldn't be breaking. Just an extension.

**Is your feature request related to a problem? Please describe.**
setup: I have a UAA client that has farther reaching permissions than my acct does.  
Right now, I cannot use those credentials and the CLI simultaneously. I have to use `uaac` to get a token from that client, and then pass it through a `-H "Authorization: $CLIENT_TOKEN"` as I curl the API. I want the benefit that comes from the CLI and its' plugins formatting. The reason we write CLIs are because sometimes to json parsing is just inherently awful and we can give you a better experience. I just want that, as whoever I am using the CLI as.

**Describe the solution you'd like**
`cf log-meta --token-override $CLIENT_TOKEN_I_FETCHED_FROM_UAA`

alternatively,
if `cf login` had an integration with UAAc so that I could login as my UAA client and then use things.

To contact for clarification: @johanna on pivotal slack

**Comment by abbyachau** [comment]
Hi @johannaratliff thanks for creating this, and for reaching out. Please help me understand your feature request. It looks like you want to log in as a client; I'm wondering why `cf auth` doesn't support your use case?
```
± |master ?:43 ✗| → ./cf auth -h
NAME:
   auth - Authenticate non-interactively

USAGE:
   cf auth USERNAME PASSWORD
   cf auth USERNAME PASSWORD --origin ORIGIN
   cf auth CLIENT_ID CLIENT_SECRET --client-credentials
```

Or, are you asking for scripting support? Thanks!

**Comment by johannaratliff** [comment]
Yo, it absolutely does. We honestly just didn't know that `cf auth` was useful for anything more than individual users' non-interactive login. I think right now we just have to open up the authorities a bit on the client itself to see things. Happy to have a solution - thanks!

**Comment by johanna** [comment]
Just a heads up, you accidentally added me to this thread.

/Johanna Eriksson
