### ISSUE TITLE
Unable to initialize javax.sql.Datasource via application.properties

### ISSUE THREAD

**Issue by ranadeep-sh** [cloudfoundry/cli#1747]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [ ] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ ] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**

In the attached file [complete.zip](https://github.com/cloudfoundry/cf-deployment/files/3474877/complete.zip), you will find AppController.java where the autowired field for Datasource is defined. Compilation via Maven goes well.

I have MySQL database running locally.
![Capture](https://user-images.githubusercontent.com/19390028/62589086-1943f500-b896-11e9-8ed0-8202240a34bc.JPG)

![Capture](https://user-images.githubusercontent.com/19390028/62589353-febe4b80-b896-11e9-938c-b7b9613be8bd.JPG)

**What happened**
However, when I push the Jar via CF CLI by using above command, the deployment fails saying -

>    2019-08-06T20:49:49.52-0400 [APP/PROC/WEB/0] OUT ***************************
   2019-08-06T20:49:49.52-0400 [APP/PROC/WEB/0] OUT APPLICATION FAILED TO START
   2019-08-06T20:49:49.52-0400 [APP/PROC/WEB/0] OUT ***************************
   2019-08-06T20:49:49.52-0400 [APP/PROC/WEB/0] OUT Description:
   2019-08-06T20:49:49.52-0400 [APP/PROC/WEB/0] OUT Parameter 1 of constructor in org.cloudfoundry.http.AppController re
quired a bean of type 'javax.sql.DataSource' that could not be found.
   2019-08-06T20:49:49.52-0400 [APP/PROC/WEB/0] OUT The following candidates were found but could not be injected:
   2019-08-06T20:49:49.52-0400 [APP/PROC/WEB/0] OUT     - Bean method 'dataSource' in 'JndiDataSourceAutoConfiguration'
not loaded because @ConditionalOnProperty (spring.datasource.jndi-name) did not find property 'jndi-name'
   2019-08-06T20:49:49.52-0400 [APP/PROC/WEB/0] OUT     - Bean method 'dataSource' in 'XADataSourceAutoConfiguration' no
t loaded because @ConditionalOnBean (types: org.springframework.boot.jdbc.XADataSourceWrapper; SearchStrategy: all) did
not find any beans of type org.springframework.boot.jdbc.XADataSourceWrapper
   2019-08-06T20:49:49.52-0400 [APP/PROC/WEB/0] OUT Action:
   2019-08-06T20:49:49.52-0400 [APP/PROC/WEB/0] OUT Consider revisiting the entries above or defining a bean of type 'ja
vax.sql.DataSource' in your configuration.
   2019-08-06T20:49:49.57-0400 [APP/PROC/WEB/0] OUT Exit status 1

I have also attached complete logs here
[cf_spring_boot_log.txt](https://github.com/cloudfoundry/cf-deployment/files/3474886/cf_spring_boot_log.txt).

**Expected behavior**
A successful deployment of the JAR with status indicated as STARTED, rather than CRASHED.

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Build a JAR named `pcf-people-mgmt-1.0-SNAPSHOT.jar` from attached code [complete.zip](https://github.com/cloudfoundry/cf-deployment/files/3474877/complete.zip) by running `mvn -U clean install`
2. Run `cf dev start -f pcfdev-v1.2.0-windows.tgz`. 
3. After start, run `cf login -a https://api.dev.cfdev.sh --skip-ssl-validation -u admin -p admin`
3. Run `cf push pcf-people-mgmt -p C:\Users\ranadeep-sharma\IdeaProjects\gs-spring-boot\complete\target\pcf-people-mgmt-1.0-SNAPSHOT.jar`
4. See error in CLI console.

**Provide more context**
- platform and shell details : Windows Pro 10 with 16 GB RAM and Intel i7 processor + Powershell ISE.
- version of the CLI you are running : 6.46.0+29d6257f1.2019-07-09
- version of the CC API Release you are on : 2.133.0

**Comment by abbyachau** [comment]
Hi @ranadeep-sh thanks - this doesn't look like a CF CLI issue - but here's some information that might help that I gathered from a Spring SME:
```
It looks like they expected the app to connect with their local MySQL although they're running the app on PCF Dev.

They would need to create and bind to a MySQL SI

And also have the spring cloud connectors in the build of their app
```

They've advised this site which might help you further debug:

https://gitter.im/spring-cloud/spring-cloud

I'm closing this issue since it's not CF CLI related, please visit the url above should you require further support.  Thanks and good luck.

**Comment by ranadeep-sh** [comment]
Thanks @abbyachau.
This is very helpful.
