### ISSUE TITLE
Consider a cf_include feature or a way to override the default cf_ignore feature

### ISSUE THREAD

**Issue by jmsmtn** [cloudfoundry/cli#1763]
**What's the user value of this feature request?**

Some developers need files, like the revision directories (.git, etc), which are by default excluded by the cf push command ([source](https://github.com/cloudfoundry/cli/blob/master/cf/appfiles/cf_ignore.go#L78)). An example is a developer who wants to use an application monitoring tool (like Sentry) which would correlate an issue to a particular .git release.  

**Who is the functionality for?**

Any developer who wishes to correlate application monitoring with revision releases. 

**How often will this functionality be used by the user?**

Unknown. Interested developers might use it on every application push or deployment. 

**Who else is affected by the change?**

No one. Only users who explicitly want to include .git directories, etc. 

**Is your feature request related to a problem? Please describe.**

I just want to include the .git directory with the app when I push the app, so I can track issues to a specific git commit. 

**Describe the solution you'd like**

something like:

- provide a .cf_include file to explicitly include files or directories which are normally ignored  [Source](https://github.com/cloudfoundry/cli/blob/master/cf/appfiles/cf_ignore.go#L78)
- or
- provide via a command line argument "--include-directories" to explicitly include directories

**Describe alternatives you've considered**

I've consider other ways of adding files to the app post deployment, with live sync plugins or via the API. 

**Additional context**

https://about.gitlab.com/2019/01/25/sentry-integration-blog-post/ CTRL-F "Find and fix bugs faster with release and commit tracking"

I've never contributed to an OSS project or programmed in Go, but this seems really approachable and solves a personal itch.

**Comment by ericpromislow** [comment]
Hello @jmsmtn , Here’s a solution you can implement right away with the beta of version 7 of `cf`: https://github.com/cloudfoundry/cli/releases/tag/v7.0.0-beta.24

In CF CLI 7 we have a feature called labels, which allows you to add snippets of metadata to an app, you could use this to store git information about the current version of the app pushed to cloud foundry.

For example, to store the commit of the code with the app, this would work:
```
cf push MYAPPNAME ... && \
cf7 set-label app MYAPPNAME commit=$(git rev-parse HEAD)
```

This will only update to label with the newest commit sha if the push is successful, preserving your current git sha as an app-label named commit.

And then to retrieve this info:
```
cf7 labels app MYAPPNAME | awk '$1 == "commit" { print $2 }'
```
