### ISSUE TITLE
Allow cf7 & cf binaries on the same system

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/cli#1774]
**Please provide details on the following items. Failure to do so may result in deletion of your feature request.** 

**What's the user value of this feature request?**

Currently with the MacOS installer, if you install cf7, it will uninstall cf, and vise versa. This makes side by side testing hard.

**Who is the functionality for?**

Anyone looking to use the cf7 beta and test while still having cf for a fallback.

**How often will this functionality be used by the user?**

Idk. When every you need to compare output or fall back to the cf v6 cli.

**Who else is affected by the change?**

It shouldn't impact anyone else.

**Is your feature request related to a problem? Please describe.**

Yes. The MacOS installer for cf7 will currently uninstall cf v6 cli, and vise versa.

**Describe the solution you'd like**

Allow for both versions to be installed at the same time using the MacOS package.

**Describe alternatives you've considered**

If I install one version using the MacOS package and one version using a zip installation I can work around this.

**Additional context**

N/A.

**Comment by abbyachau** [comment]
Hi @dmikusa-pivotal thanks we are reviewing now and will get back to you soon.

**Comment by abbyachau** [comment]
Thanks @dmikusa-pivotal we've implemented a fix and will be going through the acceptance and release process soon. Thanks for reporting this bug.

**Comment by abbyachau** [comment]
Hi @dmikusa-pivotal We wanted to give you heads up on this. We found a [similar issue](https://www.pivotaltracker.com/story/show/168305921) with the Windows installer. As precaution, we will be removing the ability to download v7 beta via the installers until this bug is fixed. Hopefully we'll release the fix soon.

**Comment by dmikusa-pivotal** [comment]
Thanks!

**Comment by abbyachau** [comment]
Hi @dmikusa-pivotal thanks, we've [released](https://github.com/cloudfoundry/cli/releases/tag/v7.0.0-beta.25) the fix. Thanks again for reporting this issue and let us know if you have any feedback.

**Comment by dmikusa-pivotal** [comment]
Works great now, thanks!
