### ISSUE TITLE
Support for route_mappings in CLI

### ISSUE THREAD

**Issue by enchobelezirev** [cloudfoundry/cli#1775]
REST API supports the creation of the route_mappins. More specifically, I am talking about this section in the documentation https://apidocs.cloudfoundry.org/11.2.0#route-mappings
I want to know whether there is a command on the command-line tool which provides the functionality to create route mappings. If there is no such command, are there any plans for adding such in the future? Even, if it is in the V3 support, could you please share with me what would be the usage of the command?
Also, could you tell me is there any support in the Manifest for these route_mappings?

**What's the user value of this feature request?**
Create route mappings(route destinations in V3) without the need to execute custom HTTP calls.

**Who is the functionality for?**
Users who want to create route mappings(destinations).

**How often will this functionality be used by the user?**
When you need to specify route which to corresponds to a given application port.

**Who else is affected by the change?**
I have received feature request by one of our clients.

**Is your feature request related to a problem? Please describe.**
My client wants easy way to create such route mappings(destinations) without making custom HTTP calls to the REST API.

**Describe the solution you'd like**
I would like to have a command on the command-line which to support the creation of these routes mappings. I would be very happy if you could give me information whether there is such support in the manifest.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
No additional context.

**Comment by enchobelezirev** [comment]
Hello,

Could you give me some update here? We are using the client a lot and I would like to have some answers.

Thanks,
Encho

P.S. If something needs to be added to the Description, please let me know :)

**Comment by abbyachau** [comment]
Hi there @enchobelezirev sorry for the delay.

The `map-route` commands allows you to map a route to an application. The `routes` property will create a route for your application. Please view the help text (cf h -a or cf map-route -h) for usage information. Let us know if you after something else, thanks.

**Comment by enchobelezirev** [comment]
Hello @abbyachau,

Thanks for the answer!
In the `map-route` command I do not see where I can specify HTTP port of the application - the only port which could be specified is a TCP port.
If you take a look at this route_mappings post request(https://apidocs.cloudfoundry.org/11.2.0/routes_mapping/mapping_an_app_and_a_route.html), please note that there is an app_port request parameter which is the port on which the application would receive the request.

**Comment by abbyachau** [comment]
Hi @enchobelezirev thanks we don't support custom app routes at the moment on the CLI, but you could use the API for that feature. 

We had scoped custom app ports with the Networking team on v6 but decided to postpone support (cc @adobley @shalako).

Pls let us know if you have any additional questions, thanks.

**Comment by abbyachau** [comment]
Hi @enchobelezirev I'm closing this issue as resolved, please do not hesitate to reopen if you have further questions or feedback, thanks.
