### ISSUE TITLE
v3-app command missing

### ISSUE THREAD

**Issue by vipinvkmenon** [cloudfoundry/cli#1776]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.
- [x] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
Based on the documentation provided [here](https://docs.cloudfoundry.org/devguide/multiple-processes.html#view-processes), I tried to get the app details using the command
`cf v3-app myapp`
I received the error,

> 'v3-app' is not a registered command. See 'cf help -a'

However, the command
`cf v3-apps` works perfectly

**What happened**
I was trying to push a multi-process app  based on the [documentation](https://docs.cloudfoundry.org/devguide/multiple-processes.html). At the end when I tried to get the details using the command `cf v3-app myapp` it failed stating it is not a registered command. However, `cf app myapp` works.

**Expected behavior**
 

**To Reproduce**
Steps to reproduce the behaviour; include the exact CLI commands and verbose output:
1. Run `cf v3-push my-app`
2. Wait for the application to start
3. Run `cf v3-app my-app`
> 'v3-app' is not a registered command. See 'cf help -a'

**Provide more context**
- Platform: Mac Os 10.14.6, Shell: iTerm2 (Build: 3.3.2) 
- CLI Version :  cf version 6.46.1
- CC API : "api_version": "2.138.0"

**Reason**
This is because 'v3-app' command not added in the [command_list_v6.go](https://github.com/cloudfoundry/cli/blob/496abad33812c14fe457800dd0795bebc979cf22/command/common/command_list_v6.go#L21). Instead of the said 'v3-app' only 'app' is used. This needs to be changed.

It is a minor correction and I have [tested](https://github.com/vipinvkmenon/cli/tree/v3-app-fix) this. I could make a PR for the same if you allow.

Note: In order to complete the v7 beta cf CLI in a timely matter, we develop and test against the latest CAPI release candidate. When v7 cf CLI is generally available, we will start supporting official CC API releases again.

**Comment by abbyachau** [comment]
Hi @vipinvkmenon thanks for reaching out. It looks like there's an issue with the documentation, which we'll fix, thanks. Could you try running `cf app app_name` instead? Or [download](https://github.com/cloudfoundry/cli/releases/tag/v7.0.0-beta.24) the v7 beta cf CLI and run `cf7 app app_name`. 


We don't plan on adding `v3-app` to the v6 cf CLI as we plan to deprecate the v6 version of the cf CLI and move on to the v7 version which will completely be backed by the v3 CC API (the component that enables the multi-process feature and other advanced workflows for app devs.) Let us know if you have any questions, thanks.

**Comment by vipinvkmenon** [comment]
sure thanks
