### ISSUE TITLE
Support relative paths for `cf7 push -f -p`

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cli#1791]
Initially discussion and workaround at https://cloudfoundry.slack.com/archives/C032824SM/p1568373815028000

**Describe the bug and the command you saw an issue with**

I tried to `cf7 push` an application who's code and manifest were in a subfolder. I got errors. The workaround was to provide absolute paths; but relative paths are expected to work (IMO) so am raising this bug.

**What happened**

```
cf7 create-app myapp
cf7 apply-manifest -f sub/folder/manifest-staging.yml
cf7 push myapp -p sub/folder
```

I would get an error:

```
must have at least one application
FAILED
```

**Expected behavior**

It was expected that the application in relative folder `sub/folder` would be deployed based on the manifest at relative path `sub/folder/manifest-staging.yml`

**To Reproduce**

Steps to reproduce the behavior; include the exact CLI commands and verbose output:

```
git clone https://github.com/starkandwayne/etcdproxy-buildpack.git
cd etcdproxy-buildpack
cf7 create-app app-using-etcd
cf7 apply-manifest -f fixtures/rubyapp/manifest.cfdev.yml
```
Now try any of the following and they all fail:

```
cf7 push app-using-etcd --path fixtures/rubyapp
cf7 push app-using-etcd --path fixtures/rubyapp -f fixtures/rubyapp/manifest.cfdev.yml
cf7 push app-using-etcd --path fixtures/rubyapp -f manifest.cfdev.yml
cf7 push app-using-etcd --path fixtures/rubyapp -f $PWD/fixtures/rubyapp/manifest.cfdev.yml
```

The permutation that works is absolute paths:

```
cf7 push app-using-etcd --path $PWD/fixtures/rubyapp -f $PWD/fixtures/rubyapp/manifest.cfdev.yml
```

**Provide more context**

```
$ cf7 -v
cf7 version 7.0.0-beta.25+3a77715f9.2019-09-07
$ uname -a
Darwin starkair.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
```

**Comment by abbyachau** [comment]
Thanks @drnic, we'll review this and get back to you very soon.

**Comment by abbyachau** [comment]
Thanks, here is the tracker story for this bug fix: https://www.pivotaltracker.com/story/show/168545851. Thanks again for reporting this issue.

**Comment by abbyachau** [comment]
This bug has been fixed and we plan to release it in `v7.0.0-beta.26`. Thanks again for the bug report, @drnic.

**Comment by drnic** [comment]
Thanks team.
-- 
Dr Nic Williams
Stark & Wayne LLC
http://starkandwayne.com
+61 437 276 076
twitter @drnic

**Comment by Ramanamark** [comment]
Hi, What's the solution/workaround for this issue?
