### ISSUE TITLE
Unrefactored Legacy Commands fail if CF_PLUGIN_HOME is set and CF_HOME is set to different, non-existent directory

### ISSUE THREAD

**Issue by bodnarbm** [cloudfoundry/cli#1798]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.
- [ ] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
Provide details on what you were trying to do (and why).

Bug appears when running unrefactored commands that execute the legacy main function if `CF_HOME` is set to a not-yet-existing directory and `CF_PLUGIN_HOME` is set to a directory that is not a descendant of `CF_HOME`

Encountered the error with `cf login` (in last release v6.46.1, but not in master since it was refactored since last release)

```bash
CF_HOME=./path/does/not/exist/yet CF_PLUGIN_HOME=$HOME cf login -a my-cf.example.com
```

Also occurs with other commands that are still in master, such as `cf config`

```bash
CF_HOME=./path/does/not/exist/yet CF_PLUGIN_HOME=$HOME cf config --trace=true
```

**What happened**
A clear and concise description of what happen.

Received this error message
```
FAILED
Config error: Error locating CF_HOME folder '.test'
```

**Expected behavior**

Expected the command to execute per normal and create the CF_HOME directory if needed. 

The expected behavior is what occurs if the above commands are executed when CF_PLUGIN_HOME is not set or is a descendant of CF_HOME. It works in those conditions because the CLI creates the CF_PLUGIN_HOME if it does not exists, but does not create CF_HOME if it does not already exist when running legacy commands. The refactored commands (like `login` in master) do create CF_HOME if it does not exist.

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `CF_HOME=./path/does/not/exist/yet CF_PLUGIN_HOME=$HOME cf config --trace=true` where `./path/does/not/exist/yet` does not exist yet.

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm)
Mac OS X 10.14.6 with iTerm (Bash)
- version of the CLI you are running
v6.46.1 for `login` and v6.46.1 and master for `config`
- version of the CC API Release you are on
N/A

Note: As of January 2019, we no longer support API versions older than CF Release v284/CF Deployment v1.7.0 (CAPI Release: 1.46.0 (APIs 2.100.0 and 3.35.0).

Note: In order to complete the v7 beta cf CLI in a timely matter, we develop and test against the latest CAPI release candidate. When v7 cf CLI is generally available, we will start supporting official CC API releases again.

**Comment by bodnarbm** [comment]
I am happy to submit a PR to address this if the expected behavior really is that `CF_HOME` should be created if it does not exist (similar to [CreatePluginHome function](https://github.com/cloudfoundry/cli/blob/v6.46.1/util/configv3/plugins_config.go#L93-L95) that is used in [main.go](https://github.com/cloudfoundry/cli/blob/v6.46.1/main.go#L184))

**Comment by abbyachau** [comment]
Thanks @bodnarbm for reaching out. We'll take a look and get back to you soon.

**Comment by acrmp** [comment]
Hi @bodnarbm,

Thanks for reporting this issue. I can confirm this is the behaviour on current `master` (for both v6 and v7):

```
$ rm -rf /tmp/path && CF_HOME=/tmp/path/does/not/exist/yet CF_PLUGIN_HOME=$HOME cf config --trace=true
FAILED
Config error: Error locating CF_HOME folder '/tmp/path/does/not/exist/yet'
```

It seems like in the old code it was a deliberate choice to NOT create `CF_HOME` when it doesn't already exist, see [#64928306](https://www.pivotaltracker.com/story/show/64928306).

They were thinking of situations such as the command below where the CF_HOME is intended to be set to `$HOME` but is set instead to an actual tilde:

```
$ CF_HOME='~' CF_PLUGIN_HOME=$HOME cf api https://api.example.com
# creates a directory called '~'
```

The re-implemented commands use the new config writing code which always creates the parent directories, introduced in [#126256625](https://www.pivotaltracker.com/story/show/126256625).

@abbyachau What do you think is the preferred behaviour here?

**Comment by bodnarbm** [comment]
Yeah, I can definitely understand a design choice to purposely not create the directory. 

Though, if `CF_PLUGIN_HOME` is not set, then the commands will create the directory specified in `CF_HOME` as part of the process of ensuring the plugin home exists.

For example

```shell
$ rm -rf /tmp/path && CF_HOME=/tmp/path/does/not/exist/yet cf config --trace=true
```

executes okay, and ends up creating `/tmp/path/does/not/exist/yet` So that is what threw me off as far as which behavior should be expected.

Aside: Funny that you mention the `~-means-a-directory-named-tilde-and-not-the-home-folder` thing as that was something my team had just recently encountered. 😄

**Comment by a-b** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket.
