### ISSUE TITLE
Using multiple buildpacks fails if you've previously pushed and deleted a buildpack you used to push your app with

### ISSUE THREAD

**Issue by abbyachau** [cloudfoundry/cli#1801]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [ ] I reviewed open and closed github issues that may be related to my problem.
- [ ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ ] I am reporting a bug that others will be able to reproduce.
- [ ] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
Pushing an app with multiple buildpacks. 

**What happened**
If you pushed an app with `php-test-delete` and you delete that buildpack and try to push with again with multiple buildpacks `cf p app -b new_buildpack -b new_buildpack`, push fails. It seems we make a `v2` call again to that old buildpack, even though it no longer exists.  
```
RESPONSE: [2019-09-25T15:06:54Z]
HTTP/1.1 400 Bad Request
Content-Length: 148
Content-Type: application/json;charset=utf-8
Date: Wed, 25 Sep 2019 15:06:54 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: efeddea2-91ac-4dda-74e8-51eb60ec27b4::7895d38b-1e18-4416-9b95-6011e611dd9b
{
  "code": 100001,
  "description": "The app is invalid: Specified unknown buildpack name: \"php-test-delete\"",
  "error_code": "CF-AppInvalid"
}


The app is invalid: Specified unknown buildpack name: "php-test-delete"
FAILED
```

**Expected behavior**
Push succeeds.

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. existing app dora was pushed with  old_buildpack
1. old_buildpack was deleted
2. dora was pushed again with new buildpacks , cf p dora -b new_buildpack -b new_buildpack
3. push fails because we reached out to the deleted old_buildpack

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm) `amd64 linux`
- version of the CLI you are running . `6.46`
- version of the CC API Release you are on ` 2.125.0`

Note: As of January 2019, we no longer support API versions older than CF Release v284/CF Deployment v1.7.0 (CAPI Release: 1.46.0 (APIs 2.100.0 and 3.35.0).

Note: In order to complete the v7 beta cf CLI in a timely matter, we develop and test against the latest CAPI release candidate. When v7 cf CLI is generally available, we will start supporting official CC API releases again.

**Comment by ericpromislow** [comment]
This looks like a CC error.  Here's how we repro'ed it:
```
$ cf push catnip -b INTEGRATION-BUILDPACK-1cfa803e-aceb-4b6d-4535-827ce547347f
$ cf delete-buildpack  INTEGRATION-BUILDPACK-1cfa803e-aceb-4b6d-4535-827ce547347f -f
$ cf push catnip -v
...
GET /v3/apps?names=catnip&space_guids=1d571e07-0a15-4dd5-9560-abc2281bde6a                                                                                                                                                          
                                                                                                                                                                                                                                              
RESPONSE: [2019-10-02T16:23:14-07:00]                                                                                                                                                                                                         
HTTP/1.1 422 Unprocessable Entity                                                                                                                                                                                                             
{                                                                                                                                                                                                                                             
  "errors": [                                                                                                                                                                                                                                 
    {                                                                                                                                                                                                                                         
      "code": 10008,                                                                                                                                                                                                                          
      "detail": "Buildpack \"INTEGRATION-BUILDPACK-1cfa803e-aceb-4b6d-4535-827ce547347f\" must be an existing admin buildpack or a valid git URI, Buildpack \"INTEGRATION-BUILDPACK-1cfa803e-aceb-4b6d-4535-827ce547347f\" must be an existing admin buildpack or a valid git URI",                                                                                                                                                                                                         
      "title": "CF-UnprocessableEntity"                                                                                                                                                                                                       
    }                                                                                                                                                                                                                                         
  ]                                                                                                                                                                                                                                           
}
```

The part that still needs analysis is that the above error message is emitted during validation, and validations don't fire on GET requests.

**Comment by ericpromislow** [comment]
Here's what happens during the `cf push`:
```
PUT /v2/apps/9655af03-aadd-441b-9714-1736af0d158c HTTP/1.1
{
  "buildpack": "INTEGRATION-BUILDPACK-d52289df-023d-41ab-74d0-d7d56b87e0c8",
...
}
```

**Comment by staylor14** [comment]
This was a straightforward fix for the v6 codebase.

The workaround is to create a bogus buildpack with the same name as the deleted buildpack before running the second push.  The buildpack doesn't need to actually work - the name just has to exist.  

The bogus buildpack name will then be replaced by the buildpacks specified on the command line, and you're free to delete the bogus buildpack after the push succeeds.

Regards,
Steve && @ericpromislow

**Comment by abbyachau** [comment]
This fix will be included in the next cf CLI release.
