### ISSUE TITLE
cli/plugin.CliConnection GetSpaces() siliently fails on SSL certificate errors

### ISSUE THREAD

**Issue by kieron-dev** [cloudfoundry/cli#1803]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.
- [ ] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
While writing a cf cli plugin, we were testing its behaviour with respect to specifying SSL certificates in the standard CF locations and using linux environment vars.

We noticed that the GetSpaces() method on the plugin.CliConnection struct fails silently on encountering an SSL certificate error.

**What happened**
We had set the CF API providing a SSL_CERT_FILE on the command line. We invoked the plugin without SSL_CERT_FILE set, in order to test behaviour when a required certificate was missing, and saw our plugin incorrectly report that the targeted org had no spaces.

**Expected behavior**
We expected to see an error about an invalid SSL certificate.

**To Reproduce**
A minimal plugin and repro script are contained in the following gist: https://gist.github.com/kieron-pivotal/65f75a8d9dc110bab5a2666e03ece8c8

*In a linux environment (in order to use the SSL_CERT_FILE env var)*:
1. Put both main.go and repro.sh in a directory.
1. `cd` into that directory
1. `chmod +x ./repro.sh`
1. Have a CF environment API URL available, and its ca-cert available locally.
1. `./repro.sh <path-to-cert> <api-url>`

You should see:
1. Plugin is built and installed successfully
1. Provided CF API is successfully targeted
1. Username and password are requested for given CF env.
1. Skip org selection
1. See dummy-org / dummy-space org and space created and targeted.
1. See `cf spaces` returns dummy-space
1. See `cf dummy` outputs the dummy-space as a GetSpaces_Model
1. When SSL_CERT_FILE is unset
    1. `cf spaces` errors as expected complaining about an Invalid SSL Cert
    1. `cf dummy` does not error, and outputs an empty slice of GetSpaces_Model

**Provide more context**
- Ubuntu Xenial
- cf version 6.46.1+4934877ec.2019-08-23
- CAPI 1.86.0

cc: @georgethebeatle

**Comment by abbyachau** [comment]
Hi @kieron-pivotal thanks for reporting this issue. We'll take a look and get back to you soon.

**Comment by staylor14** [comment]
Hi @kieron-pivotal,

First, let me thank you for a fantastic bug report.  You made it drop dead easy for us to reproduce the behavior, which was really kind.

The bad news is that this appears to be a design flaw in the current plugin architecture.  Fixing it would require an overhaul of the design, which is precluded by the good news: we're currently rewriting plugins.

Your bug report provides us with invaluable feedback at the early stages of the rewrite: we weren't aware of this shortcoming (which appears to silently swallow every error short of a panic) in the current design, and will look to include a solution in the re-write.

So, I'm afraid we won't be able to provide you with a resolution until we cut plugins over to use the v7 commands.

Please feel free to re-open this issue if you have further questions or concerns, and thanks again for the fantastic reproducing test case!

Steve && @a-b

**Comment by bwasmith** [comment]
Steve and I were talking this morning and we decided to leave this issue open until we confirm that it is resolved in the v7 plugin rewrite.
