### ISSUE TITLE
Customizing organizations limit to view from the default value 50

### ISSUE THREAD

**Issue by kancherlanagaraju** [cloudfoundry/cli#1816]
**Please provide details on the following items. Failure to do so may result in deletion of your feature request.** 

If organizations are more than 50, the message "There are too many options to display, please type in the name." is shown.

**What's the user value of this feature request?**
A clear and concise description of what the user value is.

Larger enterprises might have many orgs. For Operators and Administrators it would be easy while supporting. An option of scrolling 50 orgs with space key as we do with Linux More option it would be nice to have.

**Who is the functionality for?**
Who will use this feature? 
Especially, PCF Operators , Administrators and Devops Support teams.

**How often will this functionality be used by the user?**
How often will they use this feature?
Every day

**Who else is affected by the change?**
Does this feature cause a breaking change? Are other users affected by this change?
No

**Is your feature request related to a problem? Please describe.**
None

**Describe the solution you'd like**

Able to list all the organization One page at a time (with default value 50 per page).

**Describe alternatives you've considered**

Tried with CC API (v2/organizations)
this is listing all the meta data for all the orgs.  At the time of login , we may open other terminal to check actual org name. Again it is tedious process.

I can say as of now there are no alternative solutions for this default behavior.

**Additional context**

**Comment by abbyachau** [comment]
Hi @kancherlanagaraju thanks, just to clarify, is this an enhancement to the `login` command such that if there are more than 50 orgs, we provide the ability to scroll the next 50 results? Out of curiosity, why is typing the org name not sufficient? Thanks.

**Comment by mgadiya** [comment]
Hi @kancherlanagaraju, we believe that typing org name is sufficient to address your question and hence we are closing this issue. If you think otherwise, please re-open this issue.
