### ISSUE TITLE
Allow path attribute in a manifest to be a remote file

### ISSUE THREAD

**Issue by bendodd** [cloudfoundry/cli#182]
Allow the path attribute in a manifest to be a remote file, for example from an artefact server or similar.

**Comment by camelpunch** [comment]
Closing for now. Please follow [the Tracker story](https://www.pivotaltracker.com/n/projects/892938/stories/72401448) for updates on progress.

**Comment by eduardohl** [comment]
We have the same use case in our company and that would be really helpful. For now we're going to have to remediate by doing this with scripting or in code until the feature is developed.

**Comment by Agraham21** [comment]
There is an use case where a user needs to push artifacts from a remote site, such as cf push try -p https://abc.net/sample-1.0.jar so we would like to reopen this feature request.

**Comment by abbyachau** [comment]
Thanks @Agraham21 reopening this issue.

**Comment by abbyachau** [comment]
Hi @bendodd thanks for creating this issue. There is a feature narrative for Build Service which will support this use case. Please comment or provide feedback [here](https://docs.google.com/document/d/17ObyLOeY9kEgaYbzjJanBLoyeposEOVIL7cuMBpxP-Q/edit#heading=h.jg3g4j9rwn53). Build service support is likely to happen on the V7 CLI.

**Comment by arnavjain82** [comment]
Any updates on this please....

**Comment by abbyachau** [comment]
Looping in CC API team. On v3 API, the manifest is handled by the CAPI team (cc @ssisil @selzoc).

**Comment by selzoc** [comment]
Hi @arnavjain82 I think that any support for remote file paths will come via the build service/[kpack](https://github.com/pivotal/kpack) integration, which are just starting to explore now!

Thanks,
Chris

**Comment by arnavjain82** [comment]
Hi @selzoc Can it be done for cf cli also please> Need this functionality to work with cf push.

**Comment by XenoPhex** [comment]
@arnavjain82 The manifest going forward is controlled by the CC API team *not* the CF CLI team.

@heyjcollins Thoughts on who should follow up on this?

**Comment by selzoc** [comment]
Happy to transfer to the https://github.com/cloudfoundry/cloud_controller_ng/ repository, but given that this issue is 6 years old, maybe it would be worth opening a new issue there with more current details about the use case.

**Comment by JenGoldstrich** [comment]
Closing, feel free to re-open in the repo listed above
