### ISSUE TITLE
v6.47.0 (latest) `cf login` with parameter (username, password) broken

### ISSUE THREAD

**Issue by meip** [cloudfoundry/cli#1820]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.
- [ ] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
`cf login -a "url" -u "username" -p "password"`

**What happened**
Login rejected with `401 Unauthorized`

**Expected behavior**
Successful Login

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Get "latest" CLI v6.47.0
2. Run `cf login -a "url" -u "username" -p "password"`

**Provide more context**
- Platform: Linux
- CLI v6.47.0
- CLI Trace:
```
Authenticating...
REQUEST: [2019-10-17T13:45:30Z]
POST /oauth/token HTTP/1.1
Host: uaa.lyra-836.appcloud.swisscom.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/x-www-form-urlencoded
User-Agent: cf/6.47.0+fc6aad7f8.2019-10-15 (go1.12.10; amd64 linux)
[PRIVATE DATA HIDDEN]

RESPONSE: [2019-10-17T13:45:30Z]
HTTP/1.1 401 Unauthorized
```

**Comment by TimonLukas** [comment]
Can confirm - I've had the same problem when interacting with IBM Cloud. Logging in using v6.46.1 is no problem, v6.47.0 does not work.

**Comment by robachmann** [comment]
Can confirm. Works with `6.46.1` but not with `6.47.0+fc6aad7f8.2019-10-15`.
It works with `cf login --sso` though.

**Comment by abbyachau** [comment]
Hi all and @meip , thank you. We will review asap.

**Comment by robachmann** [comment]
is dodo stored in `uaa` or `ldap`?

**Comment by abbyachau** [comment]
@robachmann it's in uaa.

**Comment by acrmp** [comment]
The CLI team is able to reproduce this issue. Sorry for the regression.

Contrasting the requests with CLI v6.46.1 and v6.47.0 against Bluemix we see that the URL used to POST the oauth token to is different.

v6.46.1:

```
POST /cloudfoundry/login/us-south/oauth/token HTTP/1.1
Host: iam.cloud.ibm.com
```

v6.47.0:

```
POST /oauth/token HTTP/1.1
Host: uaa.us-south.cf.cloud.ibm.com
```

The older login implementation uses the `AuthorizationEndpoint` link advertised under `/v2/info` ( `https://iam.cloud.ibm.com/cloudfoundry/login/us-south`) but in 6.47.0 we ignore this, and assume that the UAA endpoint returned from `/` is equivalent.

```
$ curl -s 'https://api.ng.bluemix.net/' | jq -r '.links.uaa.href'
https://uaa.us-south.cf.cloud.ibm.com

$ curl -s 'https://api.ng.bluemix.net/v2/info' | jq -r '.authorization_endpoint'
https://iam.cloud.ibm.com/cloudfoundry/login/us-south
```

These endpoints were equivalent for our test environments (and run.pivotal.io), but they are not always.

We are working on a solution to this now.

Thanks,

Andrew && @staylor14

**Comment by acrmp** [comment]
@meip @TimonLukas @robachmann

Thanks for reporting this issue. We have pushed a fix to `master`. Once again our apologies for shipping this regression.

If you have the opportunity prior to our next release could you please test against your foundations with the current v6 edge binary to confirm if this resolves the issue for you:
https://github.com/cloudfoundry/cli#edge-binaries

Thanks,

Andrew.

**Comment by robachmann** [comment]
Thank you very much, Andrew. I can confirm that it works in our environment with version `6.47.0+d3f4788be.2019-10-18`

**Comment by meip** [comment]
@acrmp I can also confirm a successful test with the latest edge binary. Thank you for pushing this forward!

**Comment by abbyachau** [comment]
Hi all, thanks a quick update on this. 

We looking to releasing this fix as soon as possible, there are a few validation steps we still need to take, and the story needs to be accepted. 

Hopefully we can get this fix out as early as Monday. We are also looking into releasing today if we can but it a realistic estimate is next Monday/early next week. We'll keep you posted.

**Comment by abbyachau** [comment]
Hi all, a quick update: we are currently working on releasing a patch with this fix. We also need to update our Windows cert as part of this release. Hopefully we can do both (release this fix and support Windows with the new cert) at the same time; if the latter blocks this release for longer than expected, we'll consider releasing again without Windows support.  We'll keep you posted.

**Comment by abbyachau** [comment]
Hi everyone, we released a [patch release](https://github.com/cloudfoundry/cli/releases) for this issue today for OSX and Linux. However we haven't yet been to release for [Windows](https://github.com/cloudfoundry/cli/issues/1819). The team are working on Windows support now and we hope to release again soon with Windows support.

**Comment by meip** [comment]
Thanks for releasing the patch which resolves the login regression described in this issue.
