### ISSUE TITLE
Prefix routes with the protocol in the console output

### ISSUE THREAD

**Issue by IObert** [cloudfoundry/cli#1826]
**What's the user value of this feature request?**
I usually need to select these URLs with my cursor and "carry them" manually over to the browser of my choice, open a new tab, and paste the URL there.
Many terminals are able to parse links in from stdout today and allow developers to do a ctrl-click to open the URL easily. For this, the URLs need to be prefixed with the correct protocol (like http/https)
I know this is not an urgent problem, but probably sth that's very easy to implement.

The current output of `cf apps` looks like this:
```
name                    requested state   instances   memory   disk   urls
html5_app_repo_router   started           1/1         256M     256M   namespace-appname-domain.com
test-nodejs             started           1/1         256M     1G     test-nodejs-agile-hyena.cfapps.eu10.hana.ondemand.com
cloud-native-ui         stopped           0/1         512M     512M   namespace-appname-domain.com
user: nodejs $ 
```

And `cf push` prints messages like this:
```
...

name:              test-nodejs
requested state:   started
routes:            test-nodejs-appname-domain.com
last uploaded:     Wed 23 Oct 11:32:07 UTC 2019
stack:             cflinuxfs3
buildpacks:        nodejs

type:            web
instances:       1/1
memory usage:    256M
start command:   node web.js
     state     since                  cpu    memory      disk      details
#0   running   2019-10-23T11:32:19Z   0.0%   0 of 256M   0 of 1G   
```

**Who is the functionality for?**
Developers who use terminals that provide this functionality (such as VS Code or Eclipse Theia).

**How often will this functionality be used by the user?**
I would use it all the time. I guess others too as it makes life easier.

**Who else is affected by the change?**
Probably not.

**Is your feature request related to a problem? Please describe.**
It would make life (and CF development) easier.

**Describe the solution you'd like**
Prefix all URLs which are printed to stdout.

**Describe alternatives you've considered**
NA

**Comment by abbyachau** [comment]
Hey @IObert thanks for this suggestion. I'll mark this with the enhancement tag. When we get leeway in our roadmap, we can review this again. Thanks.

**Comment by a-b** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket.
