### ISSUE TITLE
Missing build instructions

### ISSUE THREAD

**Issue by rauar** [cloudfoundry/cli#1827]
The readme and the Wiki does not provide any instructions on how to prepare a local environment for building the cf client locally (e.g based on the head of the git repo).

I cloned the latest HEAD and tried to "make" in the root folder and noticed I need go-lang being installed. Did install it via homebrew as I'm using OSX. Now it fails that a dependency is missing (fatih/color).

It seems some steps are required to prepare for a successful build and that should be documented.

**Comment by abbyachau** [comment]
Hey @rauar thanks for creating this. We'll look into how we can help improve things in this area.

**Comment by abbyachau** [comment]
Hey @rauar I wanted to double check with you that you were able to review the [contributing guide](https://github.com/cloudfoundry/cli/blob/master/.github/CONTRIBUTING.md). If there are any particular areas here that we could improve on, let us know, thanks.

**Comment by rauar** [comment]
Hi @abbyachau,

thanks for the pointer. I think the contributing guide contains what I was looking for. However I have one recommendation. "Contributing" is not what I had in mind nor did I look for how to contribute. My intention was simply to build HEAD so that I can try out that "version" - this has nothing to do with contributing. So perhaps it would be a good idea to split the contributing guide into 2 parts - one document which aims at building HEAD (e.g. titled "Building CF from sources") and then a separate part about "Contributing" (which contains a reference at the beginning to "Building CF from sources" but then focuses on the rules on how to contribute and how to provide patches etc.).

**Comment by abbyachau** [comment]
Thanks @rauar, have you tried using our edge releases? https://github.com/cloudfoundry/cli/wiki
