### ISSUE TITLE
cf service key --guid should exit with non zero code when service key is missing

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#1833]
**Describe the bug and the command you saw an issue with**

cf service key --guid reports success when no such service key exists

This is similar to #1001 when the --guid param is provided.

**Provide details on what you were trying to do (and why).**

Writing smoke tests that asserts presence or absence of a service ket

**What happened**

given a service instance without a key
```
./cf service-keys osb-cmdb-smoketest-1572357767
Getting keys for service instance osb-cmdb-smoketest-1572357767 as admin...
No service key for service instance osb-cmdb-smoketest-1572357767
```

when asking for guid of a missing service key 

```
$ ./cf service-key osb-cmdb-smoketest-1572357767 missing-key --guid

$ echo $?
0
```

**Expected behavior**

The command should return a non exit 0, and a friendly error message on stderr
```
$ ./cf service-key osb-cmdb-smoketest-1572357767 missing-key --guid
FAILED
No service key missing-key found for service instance osb-cmdb-smoketest-1572357767
$ echo $?
1
```

This would be consistent with the behavior of `cf service --guid`:

```
$ ./cf service non-existant-service --guid
Service instance non-existant-service not found
FAILED
$ echo $?
1
```

**Provide more context**
- platform and shell details: Linux Alpine
- version of the CLI you are running: cf version 6.47.1+0921a21b7.2019-10-18

**Comment by abbyachau** [comment]
cc @addytripathi @waterlink @blgm

**Comment by FelisiaM** [comment]
Hi @gberche-orange 

Thanks for the feedback!

We have addressed this issue when implementing the new version of the CLI and will be included in the next major version of the CLI.

Thanks,
Felisia
