### ISSUE TITLE
consider using v3 endpoint with app queries that use name and space_guid

### ISSUE THREAD

**Issue by pusherofbrooms** [cloudfoundry/cli#1837]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [ x] I reviewed open and closed github issues that may be related to my problem.
- [ x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ x] I am reporting a bug that others will be able to reproduce.
- [ ] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
In both the v6 and v7 cli, when I perform actions like `cf restart` or `cf restage` which perform an app query like `/v2/apps?q=name%3Abinding-post&q=space_guid%3A9c331a1b-7311-4666-8cc3-f12f7b35ac80` to gather data, it takes up to 30 seconds to retrieve the response in our largest environment (more than 7k applications and more than 2k services).

A similarly crafted v3 call takes less than a second to return `/v3/apps?names=binding-post&space_guids=9c331a1b-7311-4666-8cc3-f12f7b35ac80` for example in my case.

**What happened**
It takes more than 30 seconds to perform a restart due to the slow api call mentioned above.

**Expected behavior**
A restart should take around 10 seconds.

**To Reproduce**
In a large environment, restart or restage any application.

**Provide more context**
This is related to https://github.com/cloudfoundry/cloud_controller_ng/issues/1314. I'm told by the CAPI folks that v2 calls don't get a lot of optimization. 

Please consider using the v3 endpoints in the information gathering used in things like `cf restart` `cf7 restart`, restage, etc.

`cf version 6.47.1+0921a21b7.2019-10-18`
`cf7 version 7.0.0-beta.26+649b9a675.2019-10-08`
`"api_version": "2.141.0"`

Note: As of January 2019, we no longer support API versions older than CF Release v284/CF Deployment v1.7.0 (CAPI Release: 1.46.0 (APIs 2.100.0 and 3.35.0).

Note: In order to complete the v7 beta cf CLI in a timely matter, we develop and test against the latest CAPI release candidate. When v7 cf CLI is generally available, we will start supporting official CC API releases again.

**Comment by abbyachau** [comment]
cc @reid47 re: `restart` for v7

**Comment by reid47** [comment]
Thanks for reaching out, @pusherofbrooms. In V7, we're steadily working on rewriting all commands to only use V3 endpoints (like `/v3/apps`). We have done this for `cf7 restart` (next beta release coming somewhat soon), and we have a story to do this for `cf7 restage`: 

https://www.pivotaltracker.com/story/show/169413098

You're right that V2 endpoints are unlikely to be optimized, but hopefully as we progress on V7 and switch everything over to V3 endpoints, these problems will be resolved.

**Comment by ericpromislow** [comment]
Hi @pusherofbrooms ,

As Reid said, the v7 (CLI) work includes using the v3 (API) endpoints, so we're closing this issue. Please feel free contact us if you have any further questions or suggestions.

Regards,
Eric and @staylor14 , CLI Community Pair
