### ISSUE TITLE
cf delete-service should provide --recursive option to delete keys,bindings,shares

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#1839]
**What's the user value of this feature request?**

As a CF user developing automated tests using CLI, in order to cleanup transient error states such as leaking service key/service bindings, I need an easy way to delete a service instance and all its dependent element (keys, bindings, shares)

**Who is the functionality for?**

* CF service authors
* CF admins 

**How often will this functionality be used by the user?**

When they need to cleanup a service instance that has leaking service keys, service bindings and potentially shares.

**Who else is affected by the change?**
> Does this feature cause a breaking change? Are other users affected by this change?

No

**Is your feature request related to a problem? Please describe.**

When trying to clean up a service instance using `cf delete-service myservice -f` I receive the `Cannot delete service instance. Service keys, bindings, and shares must first be deleted` error message

This requires complex shell scripting to iterate over all service keys/bindings/shares and delete them one by one, and then delete service instances (which are potentially asynchronous and need to be waited for, see related #1354)

**Describe the solution you'd like**

`cf delete-service myservice -f --recursive`

**Describe alternatives you've considered**

The alternative is to use `cf delete-space` repeatedly for async services:

```
/tmp/build/a8857d48 # cf delete-space coa-osb-cmdb-smoke-tests -f
Deleting space coa-osb-cmdb-smoke-tests in org service-sandbox as admin...
Job (49c6ea45-d762-433c-bacc-eb001ba49271) failed: Deletion of space coa-osb-cmdb-smoke-tests failed because one or more resources within could not be deleted.

        An operation for service instance osb-cmdb-smoketest-1572356046 is in progress.

        An operation for service instance osb-cmdb-smoketest-1572354434 is in progress.

        An operation for service instance osb-cmdb-smoketest-1572357429 is in progress.
FAILED

/tmp/build/a8857d48 # cf delete-space coa-osb-cmdb-smoke-tests -f
Deleting space coa-osb-cmdb-smoke-tests in org service-sandbox as admin...
Job (c21230ed-4517-49b8-821a-2cf887411186) failed: Deletion of space coa-osb-cmdb-smoke-tests failed because one or more resources within could not be deleted.

        An operation for service instance osb-cmdb-smoketest-1572357429 is in progress.
FAILED

[... more retries]

/tmp/build/a8857d48 # cf delete-space coa-osb-cmdb-smoke-tests -f
Deleting space coa-osb-cmdb-smoke-tests in org service-sandbox as admin...
OK

TIP: No space targeted, use 'cf target -s' to target a space.
```

**Additional context**

**Comment by abbyachau** [comment]
@addytripathi @waterlink @FelisiaM something to consider for v7 cf CLI.

**Comment by addytripathi** [comment]
Hello, I've added a placeholder to our tracker project (https://www.pivotaltracker.com/n/projects/2105761/stories/169531437). We're unlikely to pick this up until we start working on service-bindings endpoint.

**Comment by gberche-orange** [comment]
thanks @addytripathi

**Comment by jrgleason** [comment]
I know it says "complex shell scripting" but is there a quick workaround? I can't delete the space

**Comment by gberche-orange** [comment]
@jrgleason here is a shell that my automated acceptance tests use to recursively delete service instance and apps in a space (along with more: service broker). Hopefully, you'll get some inspiration

https://github.com/orange-cloudfoundry/osb-cmdb-ci/blob/9394d2c7c07199f481b30c1a4346d2cf59720762/scripts/clean-at-cf-environment.sh#L34

**Comment by FelisiaM** [comment]
Hi @gberche-orange 

We have decided to implement the v3 service instance delete endpoint as recursive by default in line with the behaviour implemented in spaces and org deletion. As a result, the CLI that will be backed by v3 API will do recursive deletion by default.
We are not considering changing the CLI for this feature. 

I'm closing this issue for the moment, but feel free to give us more feedback.

Thanks,
Felisia
