### ISSUE TITLE
cf marketplace -s should support Multi-Service Registration

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#1849]
**What's the user value of this feature request?**

As a user, in order to display a service offering that is declared from multiple brokers, I need the `cf marketplace -s SERVICE` to accept a -b BROKER flag to display the right service offering, and to refuse displaying a multiple registered service name without this flag.

**Who is the functionality for?**

CF developers 

**How often will this functionality be used by the user?**

As much as `cf marketplace -s` command usage for CF installations using the "Multi-Service Registration" feature released in [v6.43.0](https://github.com/cloudfoundry/cli/releases/tag/v6.43.0)

**Who else is affected by the change?**

This feature will not cause a breaking change

**Is your feature request related to a problem? Please describe.**

```
$ cf m
Getting services from marketplace in org service-sandbox / space osb-cmdb-smoke-tests as xx...
OK

service                plans                                                              description                                                                                              broker
p-mysql-cmdb           10mb, 20mb                                                         A useful service                                                                                         osb-cmdb-broker
noop-ondemand-cmdb     default                                                            A useful service                                                                                         osb-cmdb-broker
p-mysql-cmdb           10mb, 20mb                                                         A useful service                                                                                         osb-cmdb-broker-0
noop-ondemand-cmdb     default                                                            A useful service                                                                                         osb-cmdb-broker-0

TIP: Use 'cf marketplace -s SERVICE' to view descriptions of individual plans of a given service.

# no way to choose whether to display service plans details for osb-cmdb-broker-0/p-mysql-cmdb or osb-cmdb-broker/p-mysql-cmdb
# a default service broker is selected
$ cf m -s p-mysql-cmdb
Getting service plan information for service p-mysql-cmdb as xx...
OK

service plan   description       free or paid
10mb           A standard plan   free
20mb           A standard plan   free

# And the default selected this broker isn't displayed in the output

# expected UX would be consistent with cf create-service 
$ cf cs p-mysql-cmdb 10mb my_ambigious_service_request
Creating service instance my_ambigious_service_request in org service-sandbox / space osb-cmdb-smoke-tests as xx...
Service 'p-mysql-cmdb' is provided by multiple service brokers. Specify a broker by using the '-b' flag.
FAILED

```

**Describe the solution you'd like**

* given a service "p-mysql-cmdb" is registered by multiple brokers osb-cmdb-broker and osb-cmdb-broker-0
* when `cf m -s p-mysql-cmdb` command is run
* then the command fails with output:
```
Getting service plan information for service p-mysql-cmdb as xx...
Service 'p-mysql-cmdb' is provided by multiple service brokers. Specify a broker by using the '-b' flag.
FAILED
````
* and when `cf m -s p-mysql-cmdb -b osb-cmdb-broker` command is run
* then the command succeeds with message that confirms the broker is indeed selected:
````
Getting service plan information for service p-mysql-cmdb and broker osb-cmdb-broker as xx...
OK

service plan   description       free or paid 
10mb           A standard plan   free
20mb           A standard plan   free
````

* and when `cf m -s p-mysql-cmdb -b osb-cmdb-broker-0` command is run
* then the command succeeds and displays the plans associated with the requested broker
````
Getting service plan information for service p-mysql-cmdb and broker osb-cmdb-broker as xx...
OK

service plan   description       free or paid 
100mb           A NON standard plan   free
200mb           A NON standard plan   free
````

**Describe alternatives you've considered**

* alternative UX: cf m -s to display the broker name as a new column: however this is a breaking change for users parsing the output, and the same broker will always be displayed on all lines (duplicated output)

**Comment by blgm** [comment]
[This commit](https://github.com/cloudfoundry/cli/commit/e719d66acb7330c188d4a23354e871da12871ebd) introduces a new marketplace command that accepts a `-b` flag. Currently it will appear only in the latest V7 build.

I'm going to close this issue as the suggested change has been made, and there's no more work to do. But it can be reopened for feedback.

**Comment by gberche-orange** [comment]
great, thanks a lot @blgm !
