### ISSUE TITLE
Confusing Upgrades not supported by this broker text

### ISSUE THREAD

**Issue by subhankarc** [cloudfoundry/cli#1850]
Hi,
I get the CF CLI output "Upgrades are not supported by this broker"

I see it is printed [here](https://github.com/cloudfoundry/cli/blob/e5d465e055bee59ab778148f19b4e21710fa665a/command/v6/service_command.go#L238).
 

```
if !serviceInstanceSummary.UpgradeSupported() { 
cmd.UI.DisplayText("Upgrades are not supported by this broker.") return 
}
```

and UpgradeSupported is defined here as
 
```
func (s ServiceInstanceSummary) UpgradeSupported() bool { 
return s.ServicePlan.MaintenanceInfo.Version != "" 
}
```

Now according to [OSBAPI](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#service-plan-object), the plan definition may have maintenance_info,
 

> Maintenance information for a Service Instance which is provisioned using the Service Plan. If provided, a version string MUST be provided and platforms MAY use this when Provisioning or Updating a Service Instance.

Also, according to the spec,
 

> If a Service Broker provides maintenance information for a Service Plan in its Catalog, a Platform MAY provide the same maintenance information when updating a Service Instance. Any field except for maintenance_info.version will be ignored. This field can be used to perform maintenance on a Service Instance (for example, to upgrade the underlying operating system the Service Instance is running on). If a Service Broker's catalog has changed and new maintenance information version is available for the Service Plan that the Service Instance being updated is using, then the Service Broker MUST reject the request with a 422 Unprocessable Entity as described below.

Service Plan already has a plan_updateable attribute, which determines whether the plan update is possible or not. Having the text as "Upgrades not possible......" is slightly confusing for a missing maintenance_info, unless it is meant for normal upgrade, and not plan update. Could you please throw some light ?

Regards,
Subhankar

**Comment by Kiemes** [comment]
I was also confused by this since I knew that e.g. I could update the Postgres service instance from plan small to medium. There seems to be a difference between `update` and `upgrade` which might not be clear to everyone. https://cli.cloudfoundry.org/en-US/cf/update-service.html

**Comment by FelisiaM** [comment]
Hi @subhankarc & @Kiemes 

Thanks for raising this issue, and apologies for the late response.

You are right to observe that the `update` and `upgrade` operation for a service instance are not the same. 

For CF an `update` is the change of the plan (e.g from small to large) or change of parameters.
On the other hand, an `upgrade` is the process of updating that same SI to the latest version available on the broker of the same configuration: e.g SI was created using small plan and the broker later updated the configuration of the small plan. The SI can be updated to the latest version of the small plan by running `cf update service-instance --upgrade`
The cases when the broker does not support this behaviour are exposed as "Upgrades not possible......"

We have tried to explain this difference in the command usage for flag --upgrade.

> --upgrade, -u  Upgrade the service instance to the latest version of the service plan available.

I will close this issue for the moment but feel free to reopen it if you have any more questions. 

Thanks,
Felisia
