### ISSUE TITLE
Retrieval of object guids is slow

### ISSUE THREAD

**Issue by norman-abramovitz** [cloudfoundry/cli#1858]
**What's the user value of this feature request?**
The performance of the cf and cf7 commands seems slow when retrieving guid values using the --guid flag.   I am working on zsh command completion options and I discovered using cf curl is faster than just using the appropriate command to retrieve values.

Comparing the execution times of cf app name --guid to cf curl 'app?names=appname' seems inconsistent.  The execution times should approximately be the same, but the 'cf app' command is a great deal slower. 
cf curl '/v3/apps?names=cf-env'  0.07s user 0.04s system 12% cpu 0.864 total
cf app cf-env --guid  0.08s user 0.05s system 4% cpu 2.904 total

**Who is the functionality for?**
Any developer working with the API interface where guids are required.

**How often will this functionality be used by the user?**
I am improving the ZSH/BASH completion code to retrieve values and it seemed very slow.

**Who else is affected by the change?**
Any developer needing guids would benefit from any performance inprovement.

**Is your feature request related to a problem? Please describe.**

No
**Describe the solution you'd like**

If using the --guid flag then the output should be short circuited and avoid unused data.

**Describe alternatives you've considered**

None,  It is faster to writing shell code to processs curl output than to process the cf apps output.

**Comment by ericpromislow** [comment]
There's a lot of overhead around each cf command, involving checking the
server API, logged in, checking to see if the user has targetted an org
(and space),
if required. It is possible to carry out common operations using only curl
commands, except you'll have to handle refreshing the auth token when it
expires.
And doing resource matching and uploading in raw curl is not a fun
activity, and would most likely be done faster by the compiled CLI than in
bash.

**Comment by ericpromislow** [comment]
We added some code to profile the time spent doing network requests, and averaged it over 30 runs to get these values:
```
$ time cf app dodo --guid
866b2406-ba6b-4955-af26-353909d12217

real    0m0.419s
user    0m0.078s
sys     0m0.037s

$ for x in {1..30} ; do echo $i; cf app dodo --guid -v | grep -A 1 -E 'time for the request|REQUEST:' | grep -E 'time for the request|HTTP'; sleep 0.1; done | ruby /tmp/filter.rb
102.846 msec -- GET /
 62.184 msec -- GET /v3
124.742 msec -- GET /login
 72.508 msec -- GET /v3/apps?names=dodo&space_guids=SPACEGUID
```

The numbers in the first column are the average, over 30 runs, for each of the four network requests that are made. The above sum up to 335 msec, which is about 80% of the total processing time.  

Also, every time you run a cf command, the main config file gets updated, usually with an updated access token. We're going to instrument that next. Hopefully that will bring us to about 90% of the observed wallclock time and we don't have to resort to a profiler.

You're very welcome to pull down the branch we're doing this instrumentation in: `wip-170047708-manually-trace-network-calls`

**Comment by ericpromislow** [comment]
Here's some output from `strace -tt cf app dodo --guid 2>&1 | vim -`:

1. Time spent reading `config.json`:
```log

200 11:54:15.756246 newfstatat(AT_FDCWD, "/home/pivotal/.cf/config.json", {st_mode=S_IFREG|0600, st_size=3945, ...}, 0) = 0
 201 11:54:15.756282 openat(AT_FDCWD, "/home/pivotal/.cf/config.json", O_RDONLY|O_CLOEXEC) = 6
 202 11:54:15.756315 epoll_ctl(4, EPOLL_CTL_ADD, 6, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=1595190536, u64=139935924661512}}) = -1 EPERM (Operation not permitted)
 203 11:54:15.756347 epoll_ctl(4, EPOLL_CTL_DEL, 6, 0xc0000d9704) = -1 EPERM (Operation not permitted)
 204 11:54:15.756378 fstat(6, {st_mode=S_IFREG|0600, st_size=3945, ...}) = 0
 205 11:54:15.756412 read(6, "{\n  \"AccessToken\": \"bearer eyJhb"..., 4457) = 3945
 206 11:54:15.756454 read(6, "", 512)        = 0
 207 11:54:15.756485 close(6)                = 0
 208 11:54:15.756817 newfstatat(AT_FDCWD, "/home/pivotal/.cf/plugins/config.json", {st_mode=S_IFREG|0600, st_size=1298, ...}, 0) = 0
 209 11:54:15.756879 openat(AT_FDCWD, "/home/pivotal/.cf/plugins/config.json", O_RDONLY|O_CLOEXEC) = 6
 210 11:54:15.756917 epoll_ctl(4, EPOLL_CTL_ADD, 6, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=1595190536, u64=139935924661512}}) = -1 EPERM (Operation not permitted)
 211 11:54:15.756951 epoll_ctl(4, EPOLL_CTL_DEL, 6, 0xc00021555c) = -1 EPERM (Operation not permitted)
 212 11:54:15.756981 fstat(6, {st_mode=S_IFREG|0600, st_size=1298, ...}) = 0
 213 11:54:15.757014 read(6, "{\n  \"Plugins\": {\n    \"CF-CLI-Int"..., 1810) = 1298
 214 11:54:15.757051 read(6, "", 512)        = 0
 215 11:54:15.757081 close(6)                = 0
```
In other words, time spent reading configs: `15.757081 - 15.755967` = 1.1 msec
```

**Comment by jpalermo** [comment]
Hey @norman-abramovitz, we're not seeing any large sets of wasted time in the CLI that would speed this up. 

There was a small bit of unexpected time spent after the command was done executing. We're not sure what might be causing that, garbage collection doesn't seem like it would take too much time, maybe there are some TCP connections that are being gracefully closed at that point and that's taking a bit of extra time. It's not enough of a time sink that it's something we can devote resources to digging into it right now though.

We're going to close the issue for now, but if you've got any other ideas feel free to reopen it.

Thanks!
