### ISSUE TITLE
Manifest random-route takes precedence over --hostname command line option

### ISSUE THREAD

**Issue by fg78nc** [cloudfoundry/cli#1862]
I assume that command line options passed to CLI should take precedence (override) manifest attributes.

However
If we specify in manifest : `random-route : true`

and then in command line `--hostname` (or `-n`) 

Manifest option takes precedence and random route is provided.

cf version 6.47.2+d526c2cb3.2019-11-05

**Comment by ericpromislow** [comment]
Hi @fg78nc ,

Thanks for reporting this. It is indeed a bug, and we pushed a fix for the next v6 release.

Regards,
Eric and @staylor14   CF CLI community team
