### ISSUE TITLE
Copy/paste errors in set_label_command_test.go

### ISSUE THREAD

**Issue by blgm** [cloudfoundry/cli#1874]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [X] I reviewed open and closed github issues that may be related to my problem.
- [X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [X] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X] I am reporting a bug that others will be able to reproduce.
- [X] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
While looking at `set_label_command_test.go` we saw various instances of tests having been copied and not subsequently updated, so that they are testing the wrong thing.

For instance the Domain label test, actually test App labels in some testcases.

https://github.com/cloudfoundry/cli/blob/84a6d3b10b8b6877b42cc393e12f55fe16578c2d/command/v7/set_label_command_test.go#L424-L426
https://github.com/cloudfoundry/cli/blob/84a6d3b10b8b6877b42cc393e12f55fe16578c2d/command/v7/set_label_command_test.go#L451-L454

**Routes tests:**
https://github.com/cloudfoundry/cli/blob/84a6d3b10b8b6877b42cc393e12f55fe16578c2d/command/v7/set_label_command_test.go#L729
https://github.com/cloudfoundry/cli/blob/84a6d3b10b8b6877b42cc393e12f55fe16578c2d/command/v7/set_label_command_test.go#L1086-L1089

**Spaces test:**
https://github.com/cloudfoundry/cli/blob/84a6d3b10b8b6877b42cc393e12f55fe16578c2d/command/v7/set_label_command_test.go#L1089
https://github.com/cloudfoundry/cli/blob/84a6d3b10b8b6877b42cc393e12f55fe16578c2d/command/v7/set_label_command_test.go#L1109
https://github.com/cloudfoundry/cli/blob/84a6d3b10b8b6877b42cc393e12f55fe16578c2d/command/v7/set_label_command_test.go#L1157
https://github.com/cloudfoundry/cli/blob/84a6d3b10b8b6877b42cc393e12f55fe16578c2d/command/v7/set_label_command_test.go#L1260-L1263

**Stacks tests:**
https://github.com/cloudfoundry/cli/blob/84a6d3b10b8b6877b42cc393e12f55fe16578c2d/command/v7/set_label_command_test.go#L1263
https://github.com/cloudfoundry/cli/blob/84a6d3b10b8b6877b42cc393e12f55fe16578c2d/command/v7/set_label_command_test.go#L1283
https://github.com/cloudfoundry/cli/blob/84a6d3b10b8b6877b42cc393e12f55fe16578c2d/command/v7/set_label_command_test.go#L1330

**What happened**
It seems that many unit test are not actually testing what the author intended to test.

**Expected behavior**
Perhaps using a table test would reduce chances of this happening.

**To Reproduce**
Code inspection. Links above.

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm)
- version of the CLI you are running
- version of the CC API Release you are on

Note: As of January 2019, we no longer support API versions older than CF Release v284/CF Deployment v1.7.0 (CAPI Release: 1.46.0 (APIs 2.100.0 and 3.35.0).

Note: In order to complete the v7 beta cf CLI in a timely matter, we develop and test against the latest CAPI release candidate. When v7 cf CLI is generally available, we will start supporting official CC API releases again.

**Comment by JenGoldstrich** [comment]
Thanks for bringing this up @blgm we are looking to fix this soon!

**Comment by blgm** [comment]
As part of other work we have changed this file significantly and when we did so we fixed all these issues.
