### ISSUE TITLE
`cf push --var value="012345678.91234456678"` treats value as a number

### ISSUE THREAD

**Issue by squeedee** [cloudfoundry/cli#1893]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
I was trying to push with a long string that can be cast as a number, but I wanted the string.
[Full example with README here](https://github.com/cf-platform-eng/cf-cli-test/tree/v0.0.1)

**What happened**
The quoted variable was treated as a number and converted to scientific notation

**Expected behavior**
For the quoted string to be treated as a string and not cast

**To Reproduce**
please see the demo app: https://github.com/cf-platform-eng/cf-cli-test/tree/v0.0.1

**Provide more context**
Mac OSX 10.4.16
CF CLI 6.49.0 through Homebrew

**Comment by squeedee** [comment]
It's not a pretty workaround, but `cf push --var "value=\"01234567689.1234567890123\""` does create the correct output

**Comment by squeedee** [comment]
Moved the demo app to https://github.com/squeedee/cf-cli-test

**Comment by a-b** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket.
