### ISSUE TITLE
Hey, I was trying to list all the orgs but it says no orgs found when it was listed there

### ISSUE THREAD

**Issue by abrhambas01** [cloudfoundry/cli#1896]
Hey, I was trying to target an orgs with 

But I have this in my orgs.. while I have this 

ibm cloud foundry link](https://cloud.ibm.com/account/cloud-foundry
)
![image](https://user-images.githubusercontent.com/12043306/74705935-7a3e8380-5250-11ea-99b2-4c12d1309ae3.png)

```
$ cf orgs
Getting orgs as xxxxxx@hotmail.com...
No orgs found.
```

it doesn't match and there's no orgs found.

**Comment by JenGoldstrich** [comment]
Hey @abrhambas01!

We unfortunately do not know how IBM CF manages orgs but I would assume it would be relatively similar to normal, what version of the cf CLI are you using, are you sure you're targeting the right API with the right user name?

Thanks!
