### ISSUE TITLE
macos Catalina won't open the installer packages.

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/cli#1902]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [ x] I reviewed open and closed github issues that may be related to my problem.
- [n/a ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ n/a] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ x] I am reporting a bug that others will be able to reproduce.
- [ n/a] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
Provide details on what you were trying to do (and why).

* Download a macos installer package while running macos Catalina (10.15 or later).

* Run the installer

* I see “cf7-cli-installer_7.0.0-beta.30_osx.pkg” can’t be opened because Apple cannot check it for malicious software."

**What happened**

I can't install the software

**Expected behavior**

I expect to see the standard package installation wizard

**To Reproduce**

See above

**Provide more context**

https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by ericpromislow** [comment]
Actual story: https://www.pivotaltracker.com/story/show/171506482

**Comment by bwasmith** [comment]
There are workarounds referenced in the `terraform` repo: https://github.com/hashicorp/terraform/issues/23033

**Comment by heyjcollins** [comment]
We're prioritizing the GA of v7 CLI and will consider this issue once that's complete

**Comment by a-b** [comment]
Closing, as this should be fixed now.
