### ISSUE TITLE
Allow smoke tests to run during 'cf7 push APP-NAME --strategy rolling'

### ISSUE THREAD

**Issue by simonjohansson** [cloudfoundry/cli#1903]
**What's the user value of this feature request?**
Currently all of our deployments to CF is done with [halfpipe-cf-plugin](https://github.com/springernature/halfpipe-cf-plugin)

Essentially what happens under the hood is
```
$ cf halfpipe-push -manifestPath path/to/manifest-dev.yml -appPath path/to/app -testDomain dev.cf.com
# cf push my-app-CANDIDATE -f path/to/manifest-dev.yml -p path/to/app --no-route --no-start
# cf map-route my-app-CANDIDATE dev.cf.com -n my-app-dev-CANDIDATE
# cf start my-app-CANDIDATE
```

At this point we can run smoke tests agains `my-app-dev-CANDIDATE.dev.cf.com` before running the `promote` step.

```
$ cf halfpipe-promote -manifestPath path/to/manifest-dev.yml -testDomain dev.cf.com
# cf map-route my-app-CANDIDATE dev.cf.com -n my-app # from manifest
# cf map-route my-app-CANDIDATE dev.cf.com -n some-other-host --path nodejs # from manifest
...
# cf rename my-app my-app-OLD
# cf stop my-app-OLD
# cf rename my-app-CANDIDATE my-app
```

There is a couple of issues with this approach
* Every time we deploy we get a new app guid, which makes it hard to create graphs for apps 
* If the memory for the app is `1G` and we need `10` instances, at the point of deployment we require 20G of memory, 10 for the current app and 10 for the candidate app. 
* We need to maintain this, when the rolling strategy is 90% there.

**Who is the functionality for?**
Our developers that use CF.

**How often will this functionality be used by the user?**
Thousands of times a tay.

**Describe the solution you'd like**

It would be neat to be able to say
```
$ cf7 push APP-NAME --strategy rollingWithSmokeTests --testRoute blah.domain.com
$ TEST_ROUTE=blah.domain.com ./smokeTests && cf7 continue-deployment APP-NAME || cf7 cancel-deployment APP-NAME
```

Where `continue-deployment` would un-map the testRoute, bind the routes from the manifest and continue with the rolling strategy.

**Comment by a-b** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket.
