### ISSUE TITLE
CLI command to fetch revisions for an app.

### ISSUE THREAD

**Issue by simonjohansson** [cloudfoundry/cli#1907]
**What's the user value of this feature request?**
Given the new `--stratergy rolling` flag to `cf push` it would be neat to have a command, `cf revisions appName` , to fetch all revisions for an app, to easier find the `GUID` in case the user would like to rollback the app to a previous version.

**Who is the functionality for?**
Users of the platform

**How often will this functionality be used by the user?**
Every day, for sure.

**Who else is affected by the change?**
N/A

**Is your feature request related to a problem? Please describe.**
Its currently cumbersome and error prone to roll back to a previous version of an app as described [here](https://docs.cloudfoundry.org/devguide/revisions.html#push-app)

This would be a first step to make it easier.

**Describe the solution you'd like**
`cf revisions app` calls out to `/v3/apps/appGUID/revisions`

**Describe alternatives you've considered**
Bash magic.

**Comment by simonjohansson** [comment]
Ping pong.

**Comment by simonjohansson** [comment]
Ping again.

**Comment by heyjcollins** [comment]
Hey @simonjohansson -
We have a revisions feature that we'll be rolling out after the v7 CLI with the current features, including rolling deploys, GA's.
Thanks for your input/plus-one for the revisions feature.
I'll include that feature in release notes once it's been added to the CLI.
I'm going to go ahead and close this issue out - feel free to comment and reopen if you wish.

**Comment by simonjohansson** [comment]
@heyjcollins you have any rough ETA for these features in the CLI?
