### ISSUE TITLE
Please support "cf unmap-route ghost ghost-branch-staging.starkandwayne.com/blog"

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cli#1909]
I ran the following and it did not work as expected:

```
cf unmap-route ghost ghost-branch-staging.starkandwayne.com/blog
```

Eventually I figured out I needed to run the following unintuitive command:

```
cf unmap-route ghost starkandwayne.com -n ghost-branch-staging --path /blog
```

Could we please support full routes in `cf upmap-route`?

**Comment by a-b** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket.
