### ISSUE TITLE
"cf7 apps --labels xyz --all-spaces", "cf7 services --labels xyz  --all-spaces" to work across all spaces

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cli#1916]
**What's the user value of this feature request?**

Resource metadata labels allow us to describe and group resources across many spaces. Currently `cf7 apps --labels xyz` only works within the target space, but `cf curl /v3/apps\?label_selector=xyz` works across all spaces.

Alternately, support `cf7 apps --labels xyz --all-spaces`.

When I specify a label, I expect to see all objects across all spaces.

**Who is the functionality for?**

People who are working with microservices that are deployed across many spaces.

**How often will this functionality be used by the user?**

This would allow a transition from space-orientated deployment to label-orientated deployment. Those users would begin to use it all the time.

**Who else is affected by the change?**

No one would be affected if they didn't use the `--all-spaces` flag.

But personally, I think if `--labels` is used, then it should implicitly mean "all spaces". But others might disagree.

**Describe the solution you'd like**

The `cf7 apps`, `cf7 services` etc commands would all support searching across all accessible spaces and listing the results.

An additional column would be displayed to show which space the resource belongs to.

**Describe alternatives you've considered**

`cf curl /v3/apps` allows discovery across all spaces.

So the alternate is to write multi-space cf plugins to do this work.

**Comment by JenGoldstrich** [comment]
Hey @drnic I really like this idea! I will bring this up to the whole CLI team to discuss implementing this!

Thanks!
Jenna and @heyjcollins

**Comment by a-b** [comment]
Thank you for your submission. We passed this idea to our product. If you still run into this issue with the latest CLI v8,  please open a new ticket.
