### ISSUE TITLE
Redact environment variable values by default in `cf env`

### ISSUE THREAD

**Issue by xtreme-jesse-malone** [cloudfoundry/cli#1920]
**Please provide details on the following items. Failure to do so may result in deletion of your feature request.** 

I think it would be worthwhile to redact environment variable values whenever they are visible especially in the output of `cf env`. I think the default behavior should be to redact with a command line option like '--no-redact' required to display the values. 

**What's the user value of this feature request?**

A lot of apps keep sensitive credentials in environment variables (not to mention service binding credentials in VCAP_APPLICATION). Redacting by default would prevent accidental exposure in scenarios such as a screen sharing session.

**Who is the functionality for?**
Platform end users especially application developers.

**How often will this functionality be used by the user?**
As often as the `cf env` command which I'd imagine is used very frequently.

**Who else is affected by the change?**
It is possible that automation scripts that read output from the `cf env` command would be broken by this change and would need to be updated to use the `--no-redact` option.

**Is your feature request related to a problem? Please describe.**
Yes and no, it comes from the realization that I (and many others) screen share often and its easy to run `cf env` in passing, forgetting that it just dumped a bunch secrets for all to see.

**Describe the solution you'd like**

- The `cf env` command redacts environment variable values in its output.
- The `cf env` has a `--no-redact` option which will override the redaction of environment variable values.

(Nice to have: environment variable values are also redacted in CF_TRACE output.)

**Describe alternatives you've considered**
No reliable alternatives come to mind. The obvious thing is to "be careful" but that's guaranteed to fail.

**Comment by JenGoldstrich** [comment]
Hey @xtreme-jesse-malone!

Thanks for filing this feature request! I am curious how you would feel about a potential flag for redacting values being optional, rather than the default being redacted, alternatively a way to query for only a specific env value such as `cf env database_url`?

Thanks!
Jenna

**Comment by xtreme-jesse-malone** [comment]
I think the most benefit would come from changing the default behavior. A flag to redact values at least makes it easier to be careful. But it would be best for the easiest command to also be the safest, and to require extra effort in order to take an unsafe action (where "unsafe" means potentially displaying secrets). 

A query for specific environment variable values could also be useful provided there is a safe way to list the available variable names. 

Thanks,

Jesse

**Comment by a-b** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket.
