### ISSUE TITLE
`cf push --path <app-dir>` ignores app manifest

### ISSUE THREAD

**Issue by goonzoid** [cloudfoundry/cli#1921]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.
- [x] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
Tried to push an app without needing to have my application directory be the app source directory using the `--path` flag, because I was in some other environment specific directory, and changing directory would have caused me to be targeting a different CF deployment (because `direnv`).

**What happened**
The application was pushed, but the `manifest.yml` file in the application directory was not used. I discovered this using `CF_TRACE=true`. When pushing from the application directory without the `--path` flag, the trace output prints `Applying manifest file <manifest-path>...` right before the info about the `POST` to `/v3/spaces/<guid>/actions/apply_manifest`, but when pushing from a different dir using `--path`, it doesn't. Additionally, my app failed to stage (in the `--path` case) because the staging process was dependent on something in the manifest.

**Expected behavior**
I expect the manifest to be used in both cases, or for the output of `cf push --help` to make it clear that it won't be.

**To Reproduce**
1. Clone https://github.com/cloudfoundry-samples/logging-route-service to `~/workspace/logging-route-service`
1. From outside of the app directory, run `cf push --path ~/workspace/logging-route-service -b go_buildpack logging-route-service`
2. See staging fail because the env vars from the app manifest aren't present
3. From inside the app directory, run `cf push -b go_buildpack logging-route-service`
4. See staging succeed

**Provide more context**
- platform and shell details: zsh 5.7.1 (x86_64-apple-darwin18.2.0)
- version of the CLI you are running: 7.0.0-beta.30+6203bbe5d.2020-02-21
- version of the CC API Release you are on: capi-release 1.92.0

Note: As of January 2019, we no longer support API versions older than CF Release v284/CF Deployment v1.7.0 (CAPI Release: 1.46.0 (APIs 2.100.0 and 3.35.0).

Note: In order to complete the v7 beta cf CLI in a timely matter, we develop and test against the latest CAPI release candidate. When v7 cf CLI is generally available, we will start supporting official CC API releases again.

**Comment by JenGoldstrich** [comment]
Hey @goonzoid thank you for opening this issue.  

We discussed this in slack and have decided this is a documentation quirk rather than a bug to fix, closing this issue.

Feel free to open it again if you feel I've closed it in error

Thanks!
Jenna

https://cloudfoundry.slack.com/archives/CCRLX88DD/p1585933355218400
https://cloudfoundry.slack.com/archives/C032824SM/p1585691153006900
