### ISSUE TITLE
cf logs appname fails to output logs if client datetime is in the past

### ISSUE THREAD

**Issue by jboelter** [cloudfoundry/cli#1929]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [X] I reviewed open and closed github issues that may be related to my problem.
- [X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [X] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X] I am reporting a bug that others will be able to reproduce.
- [ ] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**

`cf logs appname` fails if the client system time is in the past (unclear what the boundary is).

`cf logs appname --recent` works.

**What happened**

Using WSL on Windows; the WSL environment datetime was out of sync (in the past). This results in requests to the logs API returning HTTP 200 OK, but produce no output.

Note the negative start_time value in the request below.

```
REQUEST: [2020-05-03T00:00:22-07:00]
GET /api/v1/read/redacted?descending=true&limit=1&start_time=-6795364578871345152 HTTP/1.1
Host: log-cache.redacted.com
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.51.0+2acd15650.2020-04-07 (go1.13.8; amd64 linux)

RESPONSE: [2020-05-03T00:00:22-07:00]
HTTP/1.1 200 OK
Content-Length: 822
Content-Type: application/json
Date: Tue, 05 May 2020 03:30:09 GMT
Grpc-Metadata-Content-Type: application/grpc
X-Vcap-Request-Id: redacted
```

**Expected behavior**

CLI should stream the logs or error out; client timestamp should not break this functionality.

**To Reproduce**

1. set a date time in the past (this is in WSL). `sudo date --set "2020-05-03"`
2. stream the logs `cf logs appname`
3. no logs are observed; see `CF_TRACE=1 cf logs appname -v` for http request/response output.

**Provide more context**
- `Linux redacted 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- `cf version 6.51.0+2acd15650.2020-04-07`
- `api version:    3.81.0`

Maybe related:
  - https://github.com/cloudfoundry/go-log-cache/commit/d69e61173e394772128ecf3be27419695f44676d
  - https://github.com/cloudfoundry/go-log-cache/issues/28

**Comment by robachmann** [comment]
Interestingly, I can reproduce it without setting a wrong time and am facing the same issue. Since cf logs consumes log events from log-cache, this seems to be messed up for my cli. 
```
$ CF_TRACE=1 cf logs my-app --recent 
-snip-
REQUEST: [2020-05-13T15:48:15+02:00]
GET /api/v1/read/85318d26-aae1-4131-b42d-f3f712341c2a?descending=true&limit=1&start_time=-6795364578871345152 HTTP/1.1
Host: log-cache.company.com
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.51.0+2acd15650.2020-04-07 (go1.13.8; amd64 darwin)
```

after some time (~3 minutes) I receive the desired logs but sometimes I simply get the following response:

```
Failed to retrieve logs from Log Cache: unexpected status code 404
```

```
$ cf -v
cf version 6.51.0+2acd15650.2020-04-07
```
verified on MacOS, Windows and Debian (WSL)

**Comment by JenGoldstrich** [comment]
Hey @jboelter thanks for reporting this, the cf CLI's implementation of log cache currently relies on client time, we are iterating on ways to avoid this issue and will link the appropriate tracker story when we create it.

Thanks!
Jenna

**Comment by VarunVemala** [comment]
I am facing this issue as well. Initially, it was because my Mac time was off. But once I corrected the time, I was still seeing the issue.
However, if I connect to a different org, it works fine.

**Comment by a-b** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket.
