### ISSUE TITLE
cf push -f Manifest.yml --var myVar=value

### ISSUE THREAD

**Issue by sthiru** [cloudfoundry/cli#1931]
To pass environment variable using cli option along with Manifest.yml

Content of Manifest.yml 
```
****
env:
  ASPNETCORE_ENVIRONMENT: PROD
  "VAULT:NAMESPACE": "GROUP/BU"
```

I want to pass the "VAULT:TOKEN" to the PCF environment variable using 

`cf push -f Manifest.yml --var "VAULT:TOKEN"=value`

**What happened**
In the pcf application the environment variables set in manifest are available.
The "VAULT:TOKEN" set using cli "--var" is not shown.

**Expected behavior**
environment variable passed using --var should be added to the pcf application 

**Provide more context**
- platform and shell details 
   Windows powershell 
- version of the CLI you are running
    cf.exe version 6.50.0+4f0c3a2ce.2020-03-03

**Comment by bbodenmiller** [comment]
It looks like `--var` is only used to set variables in manifest and not PCF environment variables.

**Comment by reid47** [comment]
Hi @sthiru, I believe you can achieve your goal today with something like the following:

In your manifest:
```yaml
---
applications:
- name: my-app
   env:
     ((env_var_key)): ((env_var_value))
```

When you push:
```
cf push --var env_var_key="VAULT:TOKEN" --var env_var_value="MY_VALUE"
```

As @bbodenmiller said, the `--var` flag lets you interpolate variables into your manifest file. If you leave placeholder variables in the `env` section of your manifest file, you can fill them in with `--var` and they will be passed as environment variables to your app.

**Comment by sthiru** [comment]
Hi @reid47 , I have tried your suggestion, and it doesn't work as expected, If the manifest file has the value set for the variable(key), it is only updated in the application instance.

My  .gitlab-ci.yml
```
Variables:
  V_TOKEN: "s.validtoken.value"
before_script:
  - cf login -a "api_url" -u $user -p $pass -o org -s space
scripts:
  - "cf push -p  ./artifactsfolder  -f  manifest.yml --var \"Vault:Token\"=$V_TOKEN"
after_script:
  - cf logout
```

My manifest.yml
```
---
app: app-name
command: dotnet application.dll
env:
  ASPNETCORE_Environment: Staging
  "Vault:Token" : ""
```

The PCF "User Provided Environment Variables" is what is in the manifest.yml not the value passed in the cf push command.

**Comment by reid47** [comment]
Hi @sthiru, I think your manifest.yml file should look like this:

```
---
app: app-name
command: dotnet application.dll
env:
  ASPNETCORE_Environment: Staging
  "Vault:Token" : ((vault_token_value))
```

And then when you push in your .gitlab-ci.yml, you can try something like:

```
"cf push -p  ./artifactsfolder  -f  manifest.yml --var vault_token_value=$V_TOKEN"
```

Note the use of `((vault_token_value))` in the manifest – this indicates a placeholder that must be filled in with `--var vault_token_value=something` when pushing.

**Comment by sthiru** [comment]
Thanks @reid47  for your help and explanation.
It works now.
