### ISSUE TITLE
Cant push an app with symlinks

### ISSUE THREAD

**Issue by david-klug-sap** [cloudfoundry/cli#1934]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [X] I reviewed open and closed github issues that may be related to my problem.
- [X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [X] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X] I am reporting a bug that others will be able to reproduce.
- [ ] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
I tried pushing a simple app to my space. (cf push)
The app contains a symlink to an folder in the root. 
Problem is only on Windows. Mac users can push the application without any problems.

**What happened**
While pushing an error occurs:
Error staging application: App staging failed in the buildpack compile phase

**Expected behavior**
Push the app to my space without errors and write the expected console.log with the string 'my-dependency'.

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. run npm install
2. run cf push
3. See error

**Provide more context**
- platform: Windows 10
- shell details: GitBash for Windows
- CF version: cf.exe version 6.51.0+2acd15650.2020-04-07
- node: 12

[simpleApp.zip](https://github.com/cloudfoundry/cli/files/4598140/simpleApp.zip)

**Comment by JenGoldstrich** [comment]
Hey @david-frey1410 !

Can you please provide the full stack trace of this error?

Thanks!
Jenna

**Comment by david-frey1410** [comment]
$ cf push
Pushing from manifest to org MY-ORG / space MY-SPACE as MY-USERNAME...
Getting app info...
Updating app with these attributes...
  name:                cf-my-node-app
  path:                C:\Users\MY-USERNAME\repositories\simpleApp
  buildpacks:
    https://github.com/cloudfoundry/nodejs-buildpack.git#v1.7.8
  health check type:   port
  instances:           1
  memory:              512M
  stack:               cflinuxfs3
  routes:
    cf-my-node-app-generous-buffalo-vw.MY-DOMAIN

Updating app cf-my-node-app...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 1.66 KiB / 1.66 KiB [======================================================================================================================================================================] 100.00% 1s

Waiting for API to complete processing files...

Staging app and tracing logs...
   Cell 9fecef4c-d146-4df0-9a59-f7281a3981a6 successfully created container for instance 775fbbda-dc7d-44c8-ad97-6de94633a307
   Downloading app package...
   Downloading build artifacts cache...
   Downloaded app package (1.7K)
   Downloaded build artifacts cache (23.8M)
   -----> Download go 1.12.4
   -----> Running go build supply
   /tmp/buildpackdownloads/9284b6a79b4f8b822d6a37da819efac6 ~
   ~
   -----> Nodejs Buildpack version 1.7.8
   -----> Installing binaries
          engines.node (package.json): ^12.14.0
          engines.npm (package.json): unspecified (use default)
   -----> Installing node 12.14.0
          Copy [/tmp/cache/final/dependencies/53d0d79ef6b12b53b89897960e91aa1bc159f3f4e3427b1f858320d894de9962/node-12.14.0-linux-x64-cflinuxfs3-09b879d7.tgz]
Error staging application: App staging failed in the buildpack compile phase
FAILED

**Comment by david-frey1410** [comment]
Any updates here ?

**Comment by JenGoldstrich** [comment]
Hey, @david-frey1410

We tested your simpleApp on Mac OS using iTerm and Windows using GitBash and PowerShell, and got the same result.

The app logs "my dependancy" if you scan through cf logs (you wouldn't see log output in cf push) and then closes, looking at the app this makes sense as all it does is console.log and exit, we are unable to replicate your issue with the app staging failed in the buildpack compile phase on Windows, what version of the cf API are you using as this might cause an issue.

Its possible the app closes mid staging and causes the build pack to complain but I am not sure is a Windows specific issue.

Thanks
@nickjameswebb and Jenna

**Comment by david-frey1410** [comment]
$ cf -v
cf.exe version 6.51.0+2acd15650.2020-04-07

**Comment by JenGoldstrich** [comment]
Hey @david-frey1410 thats your cf CLI version, which you already provided above we need your cf API version, you can find this by typing ```cf api```

example: 

``` 
cf api
API endpoint:   https://api.run.pivotal.io
API version:    3.86.0
```

Thanks! 
Jenna

**Comment by dfrey1994** [comment]
Any updates ?!

**Comment by david-frey1410** [comment]
Any updates ?

**Comment by a-b** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket with the necessary information mentioned in our issue template.
