### ISSUE TITLE
Improve missleading error message when unsharing service-instances

### ISSUE THREAD

**Issue by JuergenSu** [cloudfoundry/cli#1936]
**Please provide details on the following items. Failure to do so may result in deletion of your feature request.** 

**What's the user value of this feature request?**
The user gets a clear error message what will happen when a service is unshared. At the moment the warning / confirmation message looks like if you unshare one share, it will delete all shares

**Who is the functionality for?**
for every developer unsing the cf cli

**How often will this functionality be used by the user?**
sharing service instances is not that common, so this functionality will not be needed that often, but it should be easy to do 

**Who else is affected by the change?**
this feature does not affect anny other users

**Is your feature request related to a problem? Please describe.**
The problem is a confusing error message when unsharing service-instances, this leads to confusing among developers what will happen when unsharing a service. in most cases they created a testsetup to confirm if unshare does what it is expecte to do. A clear message would help  to clarify in that situation

**Describe the solution you'd like**
Change the confirmation message to a message that tells more exactly what will happen

**Describe alternatives you've considered**
its just a textual replacement. the alternative would be leaving it as is. 

**Additional context**

if doing an cf unshare-service the following message is issued:

``` 
cf unshare-service mongo -s testspace2
WARNING: Unsharing this service instance will remove any service bindings that exist in any spaces that this instance is shared into. This could cause applications to stop working.

Really unshare the service instance? [yN]: y
```
but this would mean, that if the service is shared in multiple spaces, the bindings in any space is removed, which is not what the user intended to do. 

what actually happend is what the user intended, just the one shared instance is removed and all the bindings for this instance. 

maybe changeing the Message to :

WARNING: Unsharing this service instance will remove any service bindings that exist in **the** spaces that this instance is shared into. This could cause applications to stop working.

or is there a specific reason for the word any i havent found?

Thanks

**Comment by kirederik** [comment]
Hey @JuergenSu!
Thanks for opening this issue. We have updated the message and it will now say:

> WARNING: Unsharing this service instance will remove any existing bindings originating from the service instance in the space "space-name". This could cause apps to stop working.

It will be available with the next release of the cli (both v6 and v7 versions).

I'll close this for now but feel free to reopen it

Thanks!

**Comment by heyjcollins** [comment]
@kirederik and @JuergenSu - Heads up that we're no longer updating the v6 line except to fix the most severe blocking defects and/or patch CVEs so we've reverted the change that was made to the v6 branch.
