### ISSUE TITLE
Cannot login to space containing comma sign

### ISSUE THREAD

**Issue by philippthun** [cloudfoundry/cli#1938]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [X] I reviewed open and closed github issues that may be related to my problem.
- [X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [X] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X] I am reporting a bug that others will be able to reproduce.
- [ ] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
I have a space named `a,b`. When running `cf login -u <user> -o <org> -s "a,b"`, I get `Space 'a,b' not found.` But executing `cf target -s "a,b"` succeeds.

**What happened**
See above.

**Expected behavior**
I expect that both commands (`cf login -s` and `cf target -s`) behave the same.

**To Reproduce**
See above.

**Provide more context**
* cf version 6.49.0+d0dfa93bb.2020-01-07
* V2 API 2.146.0
* V3 API 3.81.0

Adding `-v` to the CF CLI commands shows that for `cf login` a call to the V3 API is sent, whereas for `cf target` the V2 API is used.

```
GET /v3/spaces?names=a%2Cb&organization_guids=b12a0c77-32ce-4ed3-ba16-aa0a1fc03e3e HTTP/1.1
=> "resources": null

GET /v2/spaces?order-by=name&q=name%3Aa%2Cb&q=organization_guid%3Ab12a0c77-32ce-4ed3-ba16-aa0a1fc03e3e HTTP/1.1
=>   "resources": [{"entity": { ...
```

The [V3 API Docs](https://v3-apidocs.cloudfoundry.org/version/3.84.0/index.html#list-spaces) state that the `names` parameter contains a `Comma-delimited list of space names to filter by.` - so it seems that the comma sign is causing trouble here...

I'm not sure if this is a client (CF CLI) or server (CF API) issue; maybe space names need some special encoding before they are sent to the server. As this issue shows up when using the CF CLI, I decided to open a bug here.

**Comment by voelzmo** [comment]
*bump* 
Hey, it's been a month, can we get a temperature check on this? Is this something you could have a look at? Unfortunately we have customers using commas in their spaces, which used to work fine with v2, but doesn't using the v3 API.

/cc @Gerg @ssisil

**Comment by Gerg** [comment]
I'm guessing the CLI is not properly double-encoding the comma in the space name. I'll see if some engineers can look into it.

**Comment by Gerg** [comment]
This issue should be fixed in the next release of v7.
