### ISSUE TITLE
v7: `set-org-role` should not always default `--origin` to `uaa` 

### ISSUE THREAD

**Issue by mwdb** [cloudfoundry/cli#1940]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [X] I reviewed open and closed github issues that may be related to my problem.
- [X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [X] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X] I am reporting a bug that others will be able to reproduce.
- [X] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
We have configured UAA with a OIDC default identity provider. With this configuration, UAA will always authenticate against the default identity provider when no default identity provider is configured.
When I logged in with the default identity provider and call
cf7 set-org-role user@customer.com myOrg OrgManager
Assigning role OrgManager to user user@customer.com in org ...

No user exists with the username 'user@customer.com' and origin 'uaa'.

**What happened**
When no --origin is specified, the v7 cli uses origin uaa as default. v6 would query across all IdPs and assign if only one user exists or error in case the user exists in multiple IdPs.

**Expected behavior**
Either keep the v6 behaviour or use the default IdP configured in UAA.

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Configure an OIDC IdP in UAA and set it as default IdP.
2. cf7 set-org-role user@customer.com myOrg OrgManager
3. Get error No user exists with the username 'user@customer.com' and origin 'uaa'.

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm)
Mac 10.15.4
- version of the CLI you are running
latest v7
- version of the CC API Release you are on

Note: As of January 2019, we no longer support API versions older than CF Release v284/CF Deployment v1.7.0 (CAPI Release: 1.46.0 (APIs 2.100.0 and 3.35.0).

Note: In order to complete the v7 beta cf CLI in a timely matter, we develop and test against the latest CAPI release candidate. When v7 cf CLI is generally available, we will start supporting official CC API releases again.

**Comment by reid47** [comment]
Hi @mwdb, thanks for the report. We believe this is a bug. I've changed the title to capture more details of the issue, and we will prioritize fixing this shortly.

**Comment by mwdb** [comment]
Thanks, appreciate that. If you need support for testing, please reach out.

**Comment by Gerg** [comment]
This issue was addressed in https://github.com/cloudfoundry/cli/commit/64d642525a15a8c90969356325aac26a12a7d2f3 and https://github.com/cloudfoundry/cli/commit/394ba022520193ce18d262e6a8f22353d703f9b7.

Please let us know if you have any further issues.
