### ISSUE TITLE
Using push --strategy rolling option, once crash after didn't push again.

### ISSUE THREAD

**Issue by koosomang** [cloudfoundry/cli#1945]
# Issue
---------------------------------------------------------------------------------------

Hi, We have problem for push option --strategy rolling by using cf7 cli. Speaking of the phenomenon, First push app is start and using well. Second same app "cf7 push [APP] -f manifest.yml --strategy rolling" but that app has a problem so, the application didn't make it.
Third we solve that problem and again "cf7 push [APP] -f manifest.yml --strategy rolling" but it doesn't work.

We doesn't want it delete the app. Because product never stop for processing to using users. But In case using same app, crashed apps must be delete and again push. How to work don't stop app push using --strategy rolling option even if the app has a problem? 
Thanks you.

---------------------------------------------------------------------------------------

# The logs is second time push failed log
Waiting for API to complete processing files...
18:18:55
18:18:55
Staging app and tracing logs...
18:18:56
Get /api/v1/info: unsupported protocol scheme ""
18:18:56
Get /api/v1/info: unsupported protocol scheme ""
18:18:56
Get /api/v1/info: unsupported protocol scheme ""
18:18:56
Get /api/v1/info: unsupported protocol scheme ""
18:19:26
Get /api/v1/info: unsupported protocol scheme ""
18:19:26
18:19:26
Starting deployment for app [APP]...
18:24:26
Waiting for app to deploy...
18:24:26
Start app timeout
18:24:26
18:24:26
TIP: Application must be listening on the right port. Instead of hard coding the port, use the $PORT environment variable.
18:24:26
18:24:26
Use 'cf7 logs [APP] --recent' for more information
18:24:26
FAILED

# The logs is third time push failed log
Targeted space [APP]
18:32:09
18:32:09
18:32:09
18:32:09
API endpoint: https://api.system.pas-dev.cni.local (API version: 3.74.0)
18:32:09
User: admin
18:32:09
Org: mrh
18:32:09
Space: [APP]
18:32:09
18:32:09
Running command: cf7 push [APP] -f manifest.yml --strategy rolling
18:32:09
Pushing app [APP] to org mrh / space [APP] as admin...
18:32:12
Applying manifest file manifest.yml...
18:32:12
For application '[APP]': Cannot update this process while a deployment is in flight.
18:32:12
FAILED

**Comment by JenGoldstrich** [comment]
Hey @koosomang 

Please use the included template when you create a new issue next time, it helps us better assist you :)!

Like the other issue we need to know your cf7 version, API version, OS, and terminal, I think this is just a way that the cf7 CLI would fail to push when using an unsupported API version (have you seen this before @Gerg @reid47)

It might also be helpful to run these commands in verbose mode `cf push app --strategy rolling -v` and give us the output

Thanks!
Jenna and @a-b

**Comment by JenGoldstrich** [comment]
From your other issue and seeing your API version I am thinking this is the same issue with an incompatible cf-deployment version.

Closing this for the same reason as the other issue

"This is not surprising when running the v7 beta CLI against an unsupported API version, I would encourage you if able to use a newer cf-deployment or to stick to the v6 CLI for now :)

Closing this issue, feel free to re-open if you think I closed it in error

Thanks!
Jenna"
