### ISSUE TITLE
cf7 logs doesn't show up.

### ISSUE THREAD

**Issue by koosomang** [cloudfoundry/cli#1946]
# Issue
Request api version is not equal, but push command is works, the other command also works, just logs command its not works. How to solve it? I want to use cf7 logs command. In addition, in the cf 6 version, the logs command is available.

# For reference currently cf version & cf api version info.

cf 
- version : 6.43.0
- api version : 2.139.0

cf7 
- version : 7.0.0-beta.30
- api version : 3.74.0

# cf7 logs [app name] 
Get /api/v1/info: unsupported protocol scheme ""
Failed

**Comment by JenGoldstrich** [comment]
Hey @koosomang!

Thanks for opening this issue, we need a little bit more information to diagnose this and ensure that future v7 releases do not have this issue

What operating system are you using, what terminal are you using?

Would you be comfortable running `cf7 logs app -v` and copy paste the output of that command into a issue comment (this runs the command in verbose mode to output requests/responses) (Make sure there's nothing confidential ofc!)

Does this issue occur for you on v6, the v6 version you included is fairly old so I would be curious if this happens for you on v6.51.0 or if this only occurs on the v7 beta CLI?

You are using a fairly old API which would have weird outcomes on the v7 beta CLI, some commands will work, a fair amount will not on an older API version.  The v7 Beta CLI requires newer versions of the API to run with full support.

@a-b and Jenna

**Comment by koosomang** [comment]
cf7 logs app -v logs
-----------------------------------
REQUEST: [2020-06-04T12:41:27+09:00]
GET / HTTP/1.1
Host: api.system.pas.local
Accept: application/json
User-Agent: cf7/7.0.0-beta.30+6203bbe5d.2020-02-21 (go1.13.4; amd64 linux)

RESPONSE: [2020-06-04T12:41:27+09:00]
HTTP/1.1 200 OK
Content-Length: 1197
Content-Type: application/json;charset=utf-8
Date: Thu, 04 Jun 2020 03:42:11 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 4534316e-e1ae-415e-5755-96bcacdb11b6::fe170156-678b-45af-ad66-3f3ce9716a15
{
  "links": {
    "app_ssh": {
      "href": "ssh.system.pas.local:2222",
      "meta": {
        "host_key_fingerprint": "44:35:52:70:9c:87:eb:d5:81:cb:07:a0:30:53:21:f1",
        "oauth_client": "ssh-proxy"
      }
    },
    "bits_service": null,
    "cloud_controller_v2": {
      "href": "https://api.system.pas.local/v2",
      "meta": {
        "version": "2.139.0"
      }
    },
    "cloud_controller_v3": {
      "href": "https://api.system.pas.local/v3",
      "meta": {
        "version": "3.74.0"
      }
    },
    "credhub": null,
    "log_stream": {
      "href": "https://log-stream.system.pas.local"
    },
    "logging": {
      "href": "wss://doppler.system.pas.local:443"
    },
    "network_policy_v0": {
      "href": "https://api.system.pas.local/networking/v0/external"
    },
    "network_policy_v1": {
      "href": "https://api.system.pas.local/networking/v1/external"
    },
    "routing": {
      "href": "https://api.system.pas.local/routing"
    },
    "self": {
      "href": "https://api.system.pas.local"
    },
    "uaa": {
      "href": "https://uaa.system.pas.local"
    }
  }
}


REQUEST: [2020-06-04T12:41:27+09:00]
GET /v3 HTTP/1.1
Host: api.system.pas.local
Accept: application/json
User-Agent: cf7/7.0.0-beta.30+6203bbe5d.2020-02-21 (go1.13.4; amd64 linux)

RESPONSE: [2020-06-04T12:41:27+09:00]
HTTP/1.1 200 OK
Content-Length: 1896
Content-Type: application/json; charset=utf-8
Date: Thu, 04 Jun 2020 03:42:11 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Runtime: 0.002566
X-Vcap-Request-Id: 6836462d-6af3-4241-5848-7b1c10c43bd9::742fa89d-ec6c-4913-aa32-2b8d2b37e37a
X-Xss-Protection: 1; mode=block
{
  "links": {
    "apps": {
      "href": "https://api.system.pas.local/v3/apps"
    },
    "buildpacks": {
      "href": "https://api.system.pas.local/v3/buildpacks"
    },
    "builds": {
      "href": "https://api.system.pas.local/v3/builds"
    },
    "deployments": {
      "experimental": true,
      "href": "https://api.system.pas.local/v3/deployments"
    },
    "domains": {
      "href": "https://api.system.pas.local/v3/domains"
    },
    "droplets": {
      "href": "https://api.system.pas.local/v3/droplets"
    },
    "feature_flags": {
      "href": "https://api.system.pas.local/v3/feature_flags"
    },
    "isolation_segments": {
      "href": "https://api.system.pas.local/v3/isolation_segments"
    },
    "organizations": {
      "href": "https://api.system.pas.local/v3/organizations"
    },
    "packages": {
      "href": "https://api.system.pas.local/v3/packages"
    },
    "processes": {
      "href": "https://api.system.pas.local/v3/processes"
    },
    "resource_matches": {
      "experimental": true,
      "href": "https://api.system.pas.local/v3/resource_matches"
    },
    "routes": {
      "experimental": true,
      "href": "https://api.system.pas.local/v3/routes"
    },
    "self": {
      "href": "https://api.system.pas.local/v3"
    },
    "service_brokers": {
      "experimental": true,
      "href": "https://api.system.pas.local/v3/service_brokers"
    },
    "service_instances": {
      "href": "https://api.system.pas.local/v3/service_instances"
    },
    "spaces": {
      "href": "https://api.system.pas.local/v3/spaces"
    },
    "stacks": {
      "href": "https://api.system.pas.local/v3/stacks"
    },
    "tasks": {
      "href": "https://api.system.pas.local/v3/tasks"
    }
  }
}


REQUEST: [2020-06-04T12:41:27+09:00]
GET /login HTTP/1.1
Host: uaa.system.pas.local
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
User-Agent: cf7/7.0.0-beta.30+6203bbe5d.2020-02-21 (go1.13.4; amd64 linux)

RESPONSE: [2020-06-04T12:41:27+09:00]
HTTP/1.1 200 OK
Cache-Control: no-store
Content-Language: en-US
Content-Length: 415
Content-Type: application/json;charset=UTF-8
Date: Thu, 04 Jun 2020 03:42:11 GMT
Set-Cookie: X-Uaa-Csrf=rsMgEqb1MGG4EnMbU2xi4V; Max-Age=86400; Expires=Fri, 05-Jun-2020 03:42:11 GMT; Path=/; Secure; HttpOnly
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Vcap-Request-Id: a7f8364b-879c-4092-65cd-3a68764d92b1
X-Xss-Protection: 1; mode=block
{
  "app": {
    "version": "73.4.18"
  },
  "commit_id": "a2e680d",
  "entityID": "http://login.system.pas.local",
  "idpDefinitions": {},
  "links": {
    "login": "https://login.system.pas.local",
    "passwd": "/forgot_password",
    "register": "/create_account",
    "uaa": "https://uaa.system.pas.local"
  },
  "prompts": {
    "password": "[PRIVATE DATA HIDDEN]",
    "username": [
      "text",
      "Email"
    ]
  },
  "timestamp": "2020-02-25T23:56:54+0000",
  "zone_name": "uaa"
}


user01(으)로 portal2 org/mrh2 영역의 mrh2-project app에 대한 logs를 searching 중...

REQUEST: [2020-06-04T12:41:27+09:00]
GET /v3/apps?names=mrh2-project&space_guids=e3360480-b267-446d-ae38-4a50f68f552a HTTP/1.1
Host: api.system.pas.local
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf7/7.0.0-beta.30+6203bbe5d.2020-02-21 (go1.13.4; amd64 linux)

RESPONSE: [2020-06-04T12:41:27+09:00]
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Thu, 04 Jun 2020 03:42:11 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Runtime: 0.008771
X-Vcap-Request-Id: f089f83c-3732-4f75-7af7-1f937bbe336a::39d99628-a0ae-4582-bb22-663f39ca5b32
X-Xss-Protection: 1; mode=block
{
  "pagination": {
    "first": {
      "href": "https://api.system.pas.local/v3/apps?names=mrh2-project&page=1&per_page=50&space_guids=e3360480-b267-446d-ae38-4a50f68f552a"
    },
    "last": {
      "href": "https://api.system.pas.local/v3/apps?names=mrh2-project&page=1&per_page=50&space_guids=e3360480-b267-446d-ae38-4a50f68f552a"
    },
    "next": null,
    "previous": null,
    "total_pages": 1,
    "total_results": 1
  },
  "resources": [
    {
      "created_at": "2020-05-29T09:01:02Z",
      "guid": "6579464f-c802-494a-82a9-e5da6c93d119",
      "lifecycle": {
        "data": {
          "buildpacks": [
            "mrh3-apt-buildpack",
            "mrh2-python-buildpack",
            "nginx_buildpack"
          ],
          "stack": "cflinuxfs3"
        },
        "type": "buildpack"
      },
      "links": {
        "current_droplet": {
          "href": "https://api.system.pas.local/v3/apps/6579464f-c802-494a-82a9-e5da6c93d119/droplets/current"
        },
        "deployed_revisions": {
          "href": "https://api.system.pas.local/v3/apps/6579464f-c802-494a-82a9-e5da6c93d119/revisions/deployed"
        },
        "droplets": {
          "href": "https://api.system.pas.local/v3/apps/6579464f-c802-494a-82a9-e5da6c93d119/droplets"
        },
        "environment_variables": {
          "href": "https://api.system.pas.local/v3/apps/6579464f-c802-494a-82a9-e5da6c93d119/environment_variables"
        },
        "packages": {
          "href": "https://api.system.pas.local/v3/apps/6579464f-c802-494a-82a9-e5da6c93d119/packages"
        },
        "processes": {
          "href": "https://api.system.pas.local/v3/apps/6579464f-c802-494a-82a9-e5da6c93d119/processes"
        },
        "revisions": {
          "href": "https://api.system.pas.local/v3/apps/6579464f-c802-494a-82a9-e5da6c93d119/revisions"
        },
        "route_mappings": {
          "href": "https://api.system.pas.local/v3/apps/6579464f-c802-494a-82a9-e5da6c93d119/route_mappings"
        },
        "self": {
          "href": "https://api.system.pas.local/v3/apps/6579464f-c802-494a-82a9-e5da6c93d119"
        },
        "space": {
          "href": "https://api.system.pas.local/v3/spaces/e3360480-b267-446d-ae38-4a50f68f552a"
        },
        "start": {
          "href": "https://api.system.pas.local/v3/apps/6579464f-c802-494a-82a9-e5da6c93d119/actions/start",
          "method": "POST"
        },
        "stop": {
          "href": "https://api.system.pas.local/v3/apps/6579464f-c802-494a-82a9-e5da6c93d119/actions/stop",
          "method": "POST"
        },
        "tasks": {
          "href": "https://api.system.pas.local/v3/apps/6579464f-c802-494a-82a9-e5da6c93d119/tasks"
        }
      },
      "metadata": {
        "annotations": {},
        "labels": {}
      },
      "name": "mrh2-project",
      "relationships": {
        "space": {
          "data": {
            "guid": "e3360480-b267-446d-ae38-4a50f68f552a"
          }
        }
      },
      "state": "STARTED",
      "updated_at": "2020-06-03T03:43:03Z"
    }
  ]
}


HTTP REQUEST: [2020-06-04T12:41:27+09:00]
GET /api/v1/info HTTP/1.1
HOST: ://
QUERY: 
Authorization: [PRIVATE DATA HIDDEN]


HTTP ERROR: [2020-06-04T12:41:27+09:00]
Get /api/v1/info: unsupported protocol scheme ""

failed

-----------------------------------

cf logs app -v logs
-----------------------------------
REQUEST: [2020-06-04T12:42:25+09:00]
GET /v2/info HTTP/1.1
Host: api.system.pas.local
Accept: application/json
User-Agent: cf/6.51.0+2acd15650.2020-04-07 (go1.13.8; amd64 linux)

RESPONSE: [2020-06-04T12:42:25+09:00]
HTTP/1.1 200 OK
Content-Length: 748
Content-Type: application/json;charset=utf-8
Date: Thu, 04 Jun 2020 03:43:08 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: fbddf09c-a984-495c-759b-803b4d698a73::5fd52e33-b730-4d98-9406-c9e6b29fcda4
{
  "api_version": "2.139.0",
  "app_ssh_endpoint": "ssh.system.pas.local:2222",
  "app_ssh_host_key_fingerprint": "44:35:52:70:9c:87:eb:d5:81:cb:07:a0:30:53:21:f1",
  "app_ssh_oauth_client": "ssh-proxy",
  "authorization_endpoint": "https://login.system.pas.local",
  "build": "2.7.11-build.17",
  "description": "https://docs.pivotal.io/pivotalcf/2-7/pcf-release-notes/runtime-rn.html",
  "doppler_logging_endpoint": "wss://doppler.system.pas.local:443",
  "min_cli_version": "6.23.0",
  "min_recommended_cli_version": "6.23.0",
  "name": "Pivotal Application Service",
  "osbapi_version": "2.15",
  "routing_endpoint": "https://api.system.pas.local/routing",
  "support": "https://support.pivotal.io",
  "token_endpoint": "[PRIVATE DATA HIDDEN]",
  "version": 0
}


REQUEST: [2020-06-04T12:42:25+09:00]
GET /login HTTP/1.1
Host: login.system.pas.local
Accept: application/json
Connection: close
User-Agent: cf/6.51.0+2acd15650.2020-04-07 (go1.13.8; amd64 linux)

RESPONSE: [2020-06-04T12:42:25+09:00]
HTTP/1.1 200 OK
Cache-Control: no-store
Content-Language: en-US
Content-Length: 415
Content-Type: application/json;charset=UTF-8
Date: Thu, 04 Jun 2020 03:43:08 GMT
Set-Cookie: X-Uaa-Csrf=0euhP6i6hYYi6eQUFqASGJ; Max-Age=86400; Expires=Fri, 05-Jun-2020 03:43:08 GMT; Path=/; Secure; HttpOnly
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Vcap-Request-Id: b8722c73-400f-4b8c-57be-8966220e4ae5
X-Xss-Protection: 1; mode=block
{
  "app": {
    "version": "73.4.18"
  },
  "commit_id": "a2e680d",
  "entityID": "http://login.system.pas.local",
  "idpDefinitions": {},
  "links": {
    "login": "https://login.system.pas.local",
    "passwd": "/forgot_password",
    "register": "/create_account",
    "uaa": "https://uaa.system.pas.local"
  },
  "prompts": {
    "password": "[PRIVATE DATA HIDDEN]",
    "username": [
      "text",
      "Email"
    ]
  },
  "timestamp": "2020-02-25T23:56:54+0000",
  "zone_name": "uaa"
}


REQUEST: [2020-06-04T12:42:25+09:00]
GET / HTTP/1.1
Host: api.system.pas.local
Accept: application/json
User-Agent: cf/6.51.0+2acd15650.2020-04-07 (go1.13.8; amd64 linux)

RESPONSE: [2020-06-04T12:42:25+09:00]
HTTP/1.1 200 OK
Content-Length: 1197
Content-Type: application/json;charset=utf-8
Date: Thu, 04 Jun 2020 03:43:08 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: f6a74e84-801f-4775-6a94-5c0b3b80a69f::83a9e9a3-1d15-4706-a192-69343f0fac57
{
  "links": {
    "app_ssh": {
      "href": "ssh.system.pas.local:2222",
      "meta": {
        "host_key_fingerprint": "44:35:52:70:9c:87:eb:d5:81:cb:07:a0:30:53:21:f1",
        "oauth_client": "ssh-proxy"
      }
    },
    "bits_service": null,
    "cloud_controller_v2": {
      "href": "https://api.system.pas.local/v2",
      "meta": {
        "version": "2.139.0"
      }
    },
    "cloud_controller_v3": {
      "href": "https://api.system.pas.local/v3",
      "meta": {
        "version": "3.74.0"
      }
    },
    "credhub": null,
    "log_stream": {
      "href": "https://log-stream.system.pas.local"
    },
    "logging": {
      "href": "wss://doppler.system.pas.local:443"
    },
    "network_policy_v0": {
      "href": "https://api.system.pas.local/networking/v0/external"
    },
    "network_policy_v1": {
      "href": "https://api.system.pas.local/networking/v1/external"
    },
    "routing": {
      "href": "https://api.system.pas.local/routing"
    },
    "self": {
      "href": "https://api.system.pas.local"
    },
    "uaa": {
      "href": "https://uaa.system.pas.local"
    }
  }
}


REQUEST: [2020-06-04T12:42:25+09:00]
GET /v3 HTTP/1.1
Host: api.system.pas.local
Accept: application/json
User-Agent: cf/6.51.0+2acd15650.2020-04-07 (go1.13.8; amd64 linux)

RESPONSE: [2020-06-04T12:42:25+09:00]
HTTP/1.1 200 OK
Content-Length: 1896
Content-Type: application/json; charset=utf-8
Date: Thu, 04 Jun 2020 03:43:08 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Runtime: 0.002497
X-Vcap-Request-Id: 6fffd244-a5d1-4bc9-6c3d-29515c50e399::ea63bbdf-c933-400c-9ffa-d934a7aa3afb
X-Xss-Protection: 1; mode=block
{
  "links": {
    "apps": {
      "href": "https://api.system.pas.local/v3/apps"
    },
    "buildpacks": {
      "href": "https://api.system.pas.local/v3/buildpacks"
    },
    "builds": {
      "href": "https://api.system.pas.local/v3/builds"
    },
    "deployments": {
      "experimental": true,
      "href": "https://api.system.pas.local/v3/deployments"
    },
    "domains": {
      "href": "https://api.system.pas.local/v3/domains"
    },
    "droplets": {
      "href": "https://api.system.pas.local/v3/droplets"
    },
    "feature_flags": {
      "href": "https://api.system.pas.local/v3/feature_flags"
    },
    "isolation_segments": {
      "href": "https://api.system.pas.local/v3/isolation_segments"
    },
    "organizations": {
      "href": "https://api.system.pas.local/v3/organizations"
    },
    "packages": {
      "href": "https://api.system.pas.local/v3/packages"
    },
    "processes": {
      "href": "https://api.system.pas.local/v3/processes"
    },
    "resource_matches": {
      "experimental": true,
      "href": "https://api.system.pas.local/v3/resource_matches"
    },
    "routes": {
      "experimental": true,
      "href": "https://api.system.pas.local/v3/routes"
    },
    "self": {
      "href": "https://api.system.pas.local/v3"
    },
    "service_brokers": {
      "experimental": true,
      "href": "https://api.system.pas.local/v3/service_brokers"
    },
    "service_instances": {
      "href": "https://api.system.pas.local/v3/service_instances"
    },
    "spaces": {
      "href": "https://api.system.pas.local/v3/spaces"
    },
    "stacks": {
      "href": "https://api.system.pas.local/v3/stacks"
    },
    "tasks": {
      "href": "https://api.system.pas.local/v3/tasks"
    }
  }
}


REQUEST: [2020-06-04T12:42:25+09:00]
GET /login HTTP/1.1
Host: uaa.system.pas.local
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
User-Agent: cf/6.51.0+2acd15650.2020-04-07 (go1.13.8; amd64 linux)

RESPONSE: [2020-06-04T12:42:25+09:00]
HTTP/1.1 200 OK
Cache-Control: no-store
Content-Language: en-US
Content-Length: 415
Content-Type: application/json;charset=UTF-8
Date: Thu, 04 Jun 2020 03:43:08 GMT
Set-Cookie: X-Uaa-Csrf=6l8sZ35M6ouWdYsgbE3kPF; Max-Age=86400; Expires=Fri, 05-Jun-2020 03:43:08 GMT; Path=/; Secure; HttpOnly
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Vcap-Request-Id: 7e3bf92e-3c07-4b00-743c-61c913b4aa46
X-Xss-Protection: 1; mode=block
{
  "app": {
    "version": "73.4.18"
  },
  "commit_id": "a2e680d",
  "entityID": "http://login.system.pas.local",
  "idpDefinitions": {},
  "links": {
    "login": "https://login.system.pas.local",
    "passwd": "/forgot_password",
    "register": "/create_account",
    "uaa": "https://uaa.system.pas.local"
  },
  "prompts": {
    "password": "[PRIVATE DATA HIDDEN]",
    "username": [
      "text",
      "Email"
    ]
  },
  "timestamp": "2020-02-25T23:56:54+0000",
  "zone_name": "uaa"
}


REQUEST: [2020-06-04T12:42:25+09:00]
GET / HTTP/1.1
Host: api.system.pas.local
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.51.0+2acd15650.2020-04-07 (go1.13.8; amd64 linux)

RESPONSE: [2020-06-04T12:42:25+09:00]
HTTP/1.1 200 OK
Content-Length: 1197
Content-Type: application/json;charset=utf-8
Date: Thu, 04 Jun 2020 03:43:08 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 17c243c2-92ca-496e-66e3-8e0a9087a410::d085fef7-3749-41f9-98a3-9c62ef4ede72
{
  "links": {
    "app_ssh": {
      "href": "ssh.system.pas.local:2222",
      "meta": {
        "host_key_fingerprint": "44:35:52:70:9c:87:eb:d5:81:cb:07:a0:30:53:21:f1",
        "oauth_client": "ssh-proxy"
      }
    },
    "bits_service": null,
    "cloud_controller_v2": {
      "href": "https://api.system.pas.local/v2",
      "meta": {
        "version": "2.139.0"
      }
    },
    "cloud_controller_v3": {
      "href": "https://api.system.pas.local/v3",
      "meta": {
        "version": "3.74.0"
      }
    },
    "credhub": null,
    "log_stream": {
      "href": "https://log-stream.system.pas.local"
    },
    "logging": {
      "href": "wss://doppler.system.pas.local:443"
    },
    "network_policy_v0": {
      "href": "https://api.system.pas.local/networking/v0/external"
    },
    "network_policy_v1": {
      "href": "https://api.system.pas.local/networking/v1/external"
    },
    "routing": {
      "href": "https://api.system.pas.local/routing"
    },
    "self": {
      "href": "https://api.system.pas.local"
    },
    "uaa": {
      "href": "https://uaa.system.pas.local"
    }
  }
}


REQUEST: [2020-06-04T12:42:25+09:00]
GET /v3 HTTP/1.1
Host: api.system.pas.local
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.51.0+2acd15650.2020-04-07 (go1.13.8; amd64 linux)

RESPONSE: [2020-06-04T12:42:25+09:00]
HTTP/1.1 200 OK
Content-Length: 1896
Content-Type: application/json; charset=utf-8
Date: Thu, 04 Jun 2020 03:43:08 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Runtime: 0.002018
X-Vcap-Request-Id: 83d5acf1-bf12-4822-60d9-b812980ca10c::f084fe95-8af0-4f07-a6fe-e4050712dd8c
X-Xss-Protection: 1; mode=block
{
  "links": {
    "apps": {
      "href": "https://api.system.pas.local/v3/apps"
    },
    "buildpacks": {
      "href": "https://api.system.pas.local/v3/buildpacks"
    },
    "builds": {
      "href": "https://api.system.pas.local/v3/builds"
    },
    "deployments": {
      "experimental": true,
      "href": "https://api.system.pas.local/v3/deployments"
    },
    "domains": {
      "href": "https://api.system.pas.local/v3/domains"
    },
    "droplets": {
      "href": "https://api.system.pas.local/v3/droplets"
    },
    "feature_flags": {
      "href": "https://api.system.pas.local/v3/feature_flags"
    },
    "isolation_segments": {
      "href": "https://api.system.pas.local/v3/isolation_segments"
    },
    "organizations": {
      "href": "https://api.system.pas.local/v3/organizations"
    },
    "packages": {
      "href": "https://api.system.pas.local/v3/packages"
    },
    "processes": {
      "href": "https://api.system.pas.local/v3/processes"
    },
    "resource_matches": {
      "experimental": true,
      "href": "https://api.system.pas.local/v3/resource_matches"
    },
    "routes": {
      "experimental": true,
      "href": "https://api.system.pas.local/v3/routes"
    },
    "self": {
      "href": "https://api.system.pas.local/v3"
    },
    "service_brokers": {
      "experimental": true,
      "href": "https://api.system.pas.local/v3/service_brokers"
    },
    "service_instances": {
      "href": "https://api.system.pas.local/v3/service_instances"
    },
    "spaces": {
      "href": "https://api.system.pas.local/v3/spaces"
    },
    "stacks": {
      "href": "https://api.system.pas.local/v3/stacks"
    },
    "tasks": {
      "href": "https://api.system.pas.local/v3/tasks"
    }
  }
}


s3498.kang(으)로 portal2 조직/mrh2 영역의 mrh2-project 앱에 대한 로그를 검색 중...

REQUEST: [2020-06-04T12:42:25+09:00]
GET /v2/apps?q=name%3Amrh2-project&q=space_guid%3Ae3360480-b267-446d-ae38-4a50f68f552a HTTP/1.1
Host: api.system.pas.local
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.51.0+2acd15650.2020-04-07 (go1.13.8; amd64 linux)

RESPONSE: [2020-06-04T12:42:25+09:00]
HTTP/1.1 200 OK
Content-Length: 2717
Content-Type: application/json;charset=utf-8
Date: Thu, 04 Jun 2020 03:43:08 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 3754c3bc-6be0-42b4-7f16-cda31cc08e86::a22893e6-e6e0-4685-bb1f-5df06e77f533
{
  "next_url": null,
  "prev_url": null,
  "resources": [
    {
      "entity": {
        "buildpack": "mrh3-apt-buildpack",
        "command": null,
        "console": false,
        "debug": null,
        "detected_buildpack": "nginx",
        "detected_buildpack_guid": "1b049415-b57c-4908-948a-e4aa0741e0d4",
        "detected_start_command": "varify -buildpack-yml-path ./buildpack.yml ./nginx.conf $HOME/modules $DEP_DIR/nginx/modules && nginx -p $PWD -c ./nginx.conf",
        "diego": true,
        "disk_quota": 3072,
        "docker_credentials": {
          "password": "[PRIVATE DATA HIDDEN]",
          "username": null
        },
        "docker_image": null,
        "enable_ssh": true,
        "environment_json": {
          "DISABLE_COLLECTSTATIC": "1",
          "LANG": "ko_KR.UTF-8",
          "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:/home/vcap/deps/0/apt/usr/lib/oracle/12.1/client64/lib",
          "ORACLE_HOME": "/home/vcap/deps/0/apt/usr/lib/oracle/12.1/client64",
          "http_proxy": "http://168.219.61.252:8080",
          "https_proxy": "http://168.219.61.252:8080",
          "no_proxy": "minio.control.cni.local,rt.sec.samsung.net,sec.samsung.net,localhost"
        },
        "events_url": "/v2/apps/6579464f-c802-494a-82a9-e5da6c93d119/events",
        "health_check_http_endpoint": "/portal/mobile/index/",
        "health_check_timeout": null,
        "health_check_type": "http",
        "instances": 3,
        "memory": 8192,
        "name": "mrh2-project",
        "package_state": "STAGED",
        "package_updated_at": "2020-06-03T03:41:09Z",
        "ports": [
          8080
        ],
        "production": false,
        "route_mappings_url": "/v2/apps/6579464f-c802-494a-82a9-e5da6c93d119/route_mappings",
        "routes_url": "/v2/apps/6579464f-c802-494a-82a9-e5da6c93d119/routes",
        "service_bindings_url": "/v2/apps/6579464f-c802-494a-82a9-e5da6c93d119/service_bindings",
        "space_guid": "e3360480-b267-446d-ae38-4a50f68f552a",
        "space_url": "/v2/spaces/e3360480-b267-446d-ae38-4a50f68f552a",
        "stack_guid": "c316c29d-c352-4d40-96be-c0910eb0eff4",
        "stack_url": "/v2/stacks/c316c29d-c352-4d40-96be-c0910eb0eff4",
        "staging_failed_description": null,
        "staging_failed_reason": null,
        "staging_task_id": "a9843b31-a6c0-4aa9-9ea2-4fc75ae46249",
        "state": "STARTED",
        "version": "00f6add5-a85e-403b-9617-fc3dd472b62c"
      },
      "metadata": {
        "created_at": "2020-05-29T09:01:02Z",
        "guid": "6579464f-c802-494a-82a9-e5da6c93d119",
        "updated_at": "2020-06-03T04:01:32Z",
        "url": "/v2/apps/6579464f-c802-494a-82a9-e5da6c93d119"
      }
    }
  ],
  "total_pages": 1,
  "total_results": 1
}


REQUEST: [2020-06-04T12:42:25+09:00]
GET /api/v1/info HTTP/1.1
Host: log-cache.system.pas.local
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.51.0+2acd15650.2020-04-07 (go1.13.8; amd64 linux)


RESPONSE: [2020-06-04T12:42:25+09:00]
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Date: Thu, 04 Jun 2020 03:43:08 GMT
X-Vcap-Request-Id: 6ee8c59f-290f-4378-457a-5b6fa77c4408
Content-Length: 20


REQUEST: [2020-06-04T12:42:25+09:00]
GET /api/v1/read/6579464f-c802-494a-82a9-e5da6c93d119?descending=true&limit=1&start_time=-6795364578871345152 HTTP/1.1
Host: log-cache.system.pas.local
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.51.0+2acd15650.2020-04-07 (go1.13.8; amd64 linux)


RESPONSE: [2020-06-04T12:42:25+09:00]
HTTP/1.1 200 OK
Date: Thu, 04 Jun 2020 03:43:09 GMT
Grpc-Metadata-Content-Type: application/grpc
X-Vcap-Request-Id: 657fce60-8ec2-49a6-6a36-a09ab67331d9
Content-Length: 794
Content-Type: application/json


REQUEST: [2020-06-04T12:42:25+09:00]
GET /api/v1/read/6579464f-c802-494a-82a9-e5da6c93d119?descending=true&limit=1&start_time=-6795364578871345152 HTTP/1.1
Host: log-cache.system.pas.local
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.51.0+2acd15650.2020-04-07 (go1.13.8; amd64 linux)


RESPONSE: [2020-06-04T12:42:25+09:00]
HTTP/1.1 200 OK
Content-Length: 794
Content-Type: application/json
Date: Thu, 04 Jun 2020 03:43:09 GMT
Grpc-Metadata-Content-Type: application/grpc
X-Vcap-Request-Id: 6527fd81-46ba-4f4e-7e63-b6e35ebfde4e


REQUEST: [2020-06-04T12:42:25+09:00]
GET /api/v1/read/6579464f-c802-494a-82a9-e5da6c93d119?descending=true&limit=1&start_time=-6795364578871345152 HTTP/1.1
Host: log-cache.system.pas.local
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.51.0+2acd15650.2020-04-07 (go1.13.8; amd64 linux)


RESPONSE: [2020-06-04T12:42:26+09:00]
HTTP/1.1 200 OK
Content-Length: 794
Content-Type: application/json
Date: Thu, 04 Jun 2020 03:43:09 GMT
Grpc-Metadata-Content-Type: application/grpc
X-Vcap-Request-Id: a1b3e08e-e651-476c-7bf2-38bfdf2eabef


REQUEST: [2020-06-04T12:42:26+09:00]
GET /api/v1/read/6579464f-c802-494a-82a9-e5da6c93d119?descending=true&limit=1&start_time=-6795364578871345152 HTTP/1.1
Host: log-cache.system.pas.local
User-Agent: cf/6.51.0+2acd15650.2020-04-07 (go1.13.8; amd64 linux)
Authorization: [PRIVATE DATA HIDDEN]


RESPONSE: [2020-06-04T12:42:26+09:00]
HTTP/1.1 200 OK
Content-Length: 794
Content-Type: application/json
Date: Thu, 04 Jun 2020 03:43:09 GMT
Grpc-Metadata-Content-Type: application/grpc
X-Vcap-Request-Id: 37dcd878-56a4-4d45-7c1f-4b73762c2dd5


REQUEST: [2020-06-04T12:42:26+09:00]
GET /api/v1/read/6579464f-c802-494a-82a9-e5da6c93d119?descending=true&limit=1&start_time=-6795364578871345152 HTTP/1.1
Host: log-cache.system.pas.local
User-Agent: cf/6.51.0+2acd15650.2020-04-07 (go1.13.8; amd64 linux)
Authorization: [PRIVATE DATA HIDDEN]


RESPONSE: [2020-06-04T12:42:26+09:00]
HTTP/1.1 200 OK
Content-Length: 794
Content-Type: application/json
Date: Thu, 04 Jun 2020 03:43:09 GMT
Grpc-Metadata-Content-Type: application/grpc
X-Vcap-Request-Id: c76ac9b8-328b-41ec-5ef5-fba044a224b1

-----------------------------------

**Comment by JenGoldstrich** [comment]
This is not surprising when running the v7 beta CLI against an unsupported API version, I would encourage you if able to use a newer cf-deployment or to stick to the v6 CLI for now :)

Closing this issue, feel free to re-open if you think I closed it in error

Thanks!
Jenna
