### ISSUE TITLE
Unable to download cf-cli on RaspberryPi

### ISSUE THREAD

**Issue by guptar85** [cloudfoundry/cli#1956]
Hello,

I was trying to install cf-cli on Raspberry Pi 3 B+ (which is running Raspberry OS (32 bit)) and unfortunately it is giving error as `E: Unable to locate package cf-cli`

![image](https://user-images.githubusercontent.com/63718017/85204236-bc77ee80-b330-11ea-887c-cfac199977c8.png)

Since this OS is derived from Debian so I followed the Linux installation instructions and everything was good till Step 2 but while executing Step 3 it throws this error. 

Below are the steps to reproduce:

1. `wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list`

![image](https://user-images.githubusercontent.com/63718017/85204301-3b6d2700-b331-11ea-8c2e-370794f4f3d2.png)

2. `sudo apt-get update`

![image](https://user-images.githubusercontent.com/63718017/85204349-8e46de80-b331-11ea-8fff-a3032f76508a.png)

3. `sudo apt-get install cf-cli`

![image](https://user-images.githubusercontent.com/63718017/85204360-9bfc6400-b331-11ea-991c-0e2fd207e05a.png)

I looked into the issue list and found 2 ([this ](https://github.com/cloudfoundry/cli/issues/1241)related to Docker and [this ](https://github.com/cloudfoundry/cli/issues/1477)related to arch64 Linux) but unfortunately, couldn't get the solution for this hence creating a new one.

Thanks!

**Comment by nickjameswebb** [comment]
Hi @guptar85,

We don't official support Raspbian (the Raspberry Pi OS). We also do not currently have an easy way to test this or fix this issue. You might have more success directly downloading and unzipping the [binary](https://github.com/cloudfoundry/cli#installers-and-compressed-binaries). We are going to close this issue for now, but feel free to reopen it if you have any questions.

Thanks,

Nick and @JenGoldstrich
