### ISSUE TITLE
Error while specifying comma separated values in the command line arguments for starting an application jar 

### ISSUE THREAD

**Issue by sivajrm** [cloudfoundry/cli#1963]
Hi,

- [ YES] I reviewed open and closed Github issues that may be related to my problem.
- [ YES] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ YES] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ YES] I am reporting a bug that others will be able to reproduce.
- [ NO] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
I am trying to run a jar with command-line arguments having comma-separated values. After setting the arguments, when the app starts, I received an error. 

**What happened**
I started my app as below, 
**java -jar {path-to-jar} -root-dir=./mock-files --verbose --no-request-journal
                 --local-response-templating --extensions=value-1,value-2,value-3**
After starting, I received an error as below, 
[ConfigurationUtils]             WARN  User config value for {value-1} is not valid, existing property not present
[ConfigurationUtils]             WARN  User config value for {value-2} is not valid, existing property not present
....
[ConfigurationUtils]             WARN  User config value for {value-n} is not valid, existing property not present

**Expected behavior**
All these values have to be passed on to the application so that the app is executed to run with these params. 

**To Reproduce**
Create a sample jar that takes an argument with values separated by comma. 
Start that app in the cloudfoundry environment with the arguments having comma. And then the error will popup. 

**Provide more context**
MacOS
cf version 6.51.0+2acd15650.2020-04-07

**Comment by nickjameswebb** [comment]
Hi @sivajrm, the CF CLI doesn't interact directly with apps or app start commands. This appears to be a [Java Buildpack Issue](https://github.com/cloudfoundry/java-buildpack/).  I would recommend opening an issue there. I am going to close this issue, but feel free to reopen it if you have additional questions.

Thanks,

Nick and @JenGoldstrich
