### ISSUE TITLE
cf push fails when app name contains invalid hostname characters

### ISSUE THREAD

**Issue by patrickcrocker** [cloudfoundry/cli#1966]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.
- [x] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
I'm trying to `cf push` an application that contains spaces in the name (ex: `My App 123xyz`).  I have defined explicit valid routes for the application in the `manifest.yml`

**What happened**
The `push` fails with the following error:
```
For application 'My App 123xyz': Failed to create default route from app name: Host must be either "*" or contain only alphanumeric characters, "_", or "-"
```

**Expected behavior**
I expect that since I have provided valid routes for the application in the manifest that the push should succeed.  There is no need for the cli to attempt to create a default route based on the application name because of the explicit routes defined.

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Using this manifest:
```
$ cat manifest.yml
---
applications:
- name: My App 123xyz
  routes:
  - route: my-app-123xyz.cfapps.nulldriver.com
```
2. Run `cf push`:
```
$ cf push
Pushing app My App 123xyz to org My Org 123xyz / space My Space 123xyz as admin...
Applying manifest file /Users/patrickcrocker/git/logging-route-service/manifest.yml...
For application 'My App 123xyz': Failed to create default route from app name: Host must be either "*" or contain only alphanumeric characters, "_", or "-"
FAILED
```

**Provide more context**
- Tested on MAC OS X 10.15.5 with iTerm2 v3.3.11
- cf version 7.0.1+fb3f929c2.2020-06-24
- cf API version 3.80.0

**Comment by Gerg** [comment]
This should be fixed in the next capi-release: https://github.com/cloudfoundry/cloud_controller_ng/commit/c5865d92b83cfecae584d852a379783602eb9ac0

There was also a related CLI bug that was exposed by your reproduction steps, which should be fixed in the next v7 release: https://github.com/cloudfoundry/cli/commit/9678715c7d3f804072a79d94184710d6ebbaf791

**Comment by abdonrd** [comment]
Any news here? Thanks!

**Comment by piyush8098** [comment]
I also notice that even though I provide route configuration explicitly, cf tries to create a default route.

For application xyz-abc-sss: Failed to create default route from app name: Host must be either "*" or contain only alphanumeric characters, "_", or "-".

As per the manifest schema (http://v3-apidocs.cloudfoundry.org/version/3.86.0/index.html#the-manifest-schema) it should have ignored default route creation had we provided the routes.

Moreover we don't even mention default-route attribute anywhere within our manifest file.

**Comment by reid47** [comment]
The fix that Greg mentioned above has now been released, both on the CAPI side and the CLI side. Thanks for your help!

@piyush8098, this sounds like it may be a separate issue. If you're still experiencing this, could you please open a new issue with reproduction steps? Thank you!

**Comment by anudee423** [comment]
is there a fix for this hostname bug
