### ISSUE TITLE
Debug Logs exist in cf7 restart command

### ISSUE THREAD

**Issue by MasslessParticle** [cloudfoundry/cli#1969]
We noticed this during testing:

https://github.com/cloudfoundry/cli/blob/499f47fbe88df6cec3a5c7626d8713baad91b5d0/command/v7/restart_command.go#L30-L34

**Comment by reid47** [comment]
Whoops, yeah, that shouldn't be there. Thanks! We'll fix this early next week.

**Comment by reid47** [comment]
I moved the Tracker story into our (the V3 Acceleration Team's) backlog.

**Comment by Gerg** [comment]
This was addressed in https://github.com/cloudfoundry/cli/commit/758080afd768ceff677cf79f8893760e15e59c43 and should be in the next v7 release

**Comment by reid47** [comment]
I believe this went out in 7.0.2, so going to close this now.
