### ISSUE TITLE
cf curl to return non-zero exit status for 4XX and 5XX http status

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#1970]
**Describe the bug and the command you saw an issue with**

As a CF CLI user
* in order to automate CF API calls using `cf curl` such as workaround for #1859 
* I need an easy way to detect a `cf curl` command failed

**What happened**

`cf curl` always return zero (successfull) exit status

**Expected behavior**

`cf curl` to return non zero exit status for HTTP error status (likely 4XX and 5XX)

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:

```
$ cf curl nosuchEndpoint
{
   "description": "Unknown request",
   "error_code": "CF-NotFound",
   "code": 10000
}
$ echo $?
0
```

**Provide more context**
- platform and shell details ( e.g. Linux ubuntu 18.04)
- version of the CLI you are running: `cf version 6.51.0+2acd15650.2020-04-07`
- version of the CC API Release you are on

**Workaround**

in the script, save stdout, and grep presence of `error_code`

**Comment by JenGoldstrich** [comment]
Hey @gberche-orange !

I confirmed this occurs on the newest cf CLI release (v7.0.1) 

```
$ cf curl blah
{
   "description": "Unknown request",
   "error_code": "CF-NotFound",
   "code": 10000
}
$echo $?
0
$ cf -v
cf version 7.0.1+fb3f929c2.2020-06-24
```

I do not believe we will fix this on v6 but maybe this is a change to consider in future v7 releases @heyjcollins

**Comment by reid47** [comment]
@gberche-orange @JenGoldstrich I believe this is what the `--fail` flag is for. I think that's consistent with how the real `curl` tool behaves (exits 0 on HTTP error status codes, unless `--fail` is provided).

**Comment by reid47** [comment]
Related issue: https://github.com/cloudfoundry/cli/issues/953

**Comment by gberche-orange** [comment]
thanks @reid47! 

Sorry I missed this flag and associated issues.
