### ISSUE TITLE
Please rename v7 cli back to cf7.

### ISSUE THREAD

**Issue by ukabu** [cloudfoundry/cli#1974]
cf7 should never have been renamed cf. they have incompatible interfaces, they should have two different command names.

**Comment by heyjcollins** [comment]
Hey @ukabu - We're not going to change the v7 CLI back to cf7. It's a major release of the same product with the same goals and covered use cases plus enhancements. When released, cf6 broke the contract with the previous major release of the CLI cf5, and there are many other applications that release new versions including breaking changes to the interface and maintain a consistent naming convention. 

That said, I'd be interested in hearing more specifically what problem you've experienced because we changed cf7 to cf. 

Thanks,

Josh

**Comment by heyjcollins** [comment]
I'm going to go ahead and close this issue out @ukabu, but I remain interested in learning more about his specific problems if you're willing to share them. 
Thanks!

Josh

**Comment by ukabu** [comment]
We have a large userbase that uses PCF. We also follow closely the platform releases, but have several environment that cannot be all updated at the same time.

We also have pipelines that have some tasks that uses the cf cli.

So we need two version of the cli to co-exist nicely. v7 does not work yet on our version (beta was ok). For pipeline we could have two version of our images, but then again, it would be nice to have the two cli version in the same image.

Our linux environment and images are debian based, today. we cannot have the cli v6 & v7 debian package coexist. It they were using alternatives, we could chose which one the cf command links too, but that is not the case.

And then there is the memory muscle thing. A different command name, even if it's just a 7 at the end, helps the brain adjust to the new subcommands more easily.

Having the same command for two completely different command line interface is akin, imo, to having a brand new API at the same endpoint as the previous one. We (you) don't do this for APIs, why would that be different for cli?

Doing it for historical reasons is not a very compelling argument ;-)

**Comment by jmenger** [comment]
Hi,
@heyjcollins you say : We're not going to change the v7 CLI back to cf7
but how come I still see cf7.exe in both installers and binaries ???

**Comment by gberche-orange** [comment]
Feedback provided in https://github.com/cloudfoundry/cli/issues/2001 is that the current switching mechanism does not easily allow users to work with an heterogeneous set of CF instances: some CF instance supporting the v3 API requirements, and some not, hence becoming unuseable with cf v7

**Comment by gberche-orange** [comment]
I see the binaries for linux still include cf7 and a cf symlink.
Here is the workaround script I have to ease switching without requiring access to apt-get and redowloading the package

```bash

#switch cli version by simlinking /usr/bin/cf to /usr/bin/cf6 or /usr/bin/cf7
#$1 6 or 7
function switch-cli() {
  local cli_version=$1
  if [[ -L /usr/bin/cf ]];
  then
    sudo ln -nsf /usr/bin/cf${cli_version} /usr/bin/cf
    echo "which cf:"
    which cf | xargs ls -al
  else
    echo "cf is not a simlink, check your install"
    ls -al /usr/bin/cf
  fi
  cf -v
}


alias switch-cf6='switch-cli 6'
alias switch-cf7='switch-cli 7'
```

UX:
```
$ switch-cf6
which cf:
lrwxrwxrwx 1 root root 12 sept. 11 18:51 /usr/bin/cf -> /usr/bin/cf6
cf version 6.51.0+2acd15650.2020-04-07

$ switch-cf7
which cf:
lrwxrwxrwx 1 root root 12 sept. 11 18:51 /usr/bin/cf -> /usr/bin/cf7
cf version 7.1.0+4c3168f9a.2020-09-09
```

Hope this can help others.
