### ISSUE TITLE
binary still named cf7 instead of cf

### ISSUE THREAD

**Issue by jmenger** [cloudfoundry/cli#1979]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.
- [ ] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
Provide details on what you were trying to do (and why).

The Binary for window-64-bit (https://packages.cloudfoundry.org/stable?release=windows64-exe&version=7.0.1&source=github-rel) still contains cf7.exe instead of cf.exe as described in the docs...

Quoting from https://github.com/cloudfoundry/cli#downloading-the-latest-v7-cf-cli it says :  
Important Note: The v7 CF CLI is now GA and the binary has been renamed from cf7 to cf.

But it still is called cf7.exe

**What happened**
A clear and concise description of what happen.

In our release-pipeline we use this extension https://marketplace.visualstudio.com/items?itemName=ms-vsts.cloud-foundry-build-extension&ssr=false#qna to install and use cf. It can download the binary mentioned above, but it's looking for cf.exe, but the binary contains cf7.exe, dispite what's mentioned in the documentation.

**Expected behavior**
the windows-64-bit-binary contains cf.exe as mentioned in the documentation.

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. download windows-64-bit binary https://packages.cloudfoundry.org/stable?release=windows64-exe&version=7.0.1&source=github-rel
2. unzip it
3. check contents contain cf7.exe, no cf.exe

**Provide more context**
- platform : windows 64 bit
- version of the CLI you are running : tried both v7.0.0 & v7.0.1

**Comment by heyjcollins** [comment]
We're working on a solution for this -- here's the story in our system: https://www.pivotaltracker.com/story/show/173856644. -- the story is publicly accessible so I'm going to close this out with this comment.

**Comment by bmcorum** [comment]
@heyjcollins and @jmenger I noticed this similar problem and during a recent fresh install of the CF CLI onto a completely new machine I stumbled upon a rather interesting find. When installing using the CF7 installer 7.0.1 onto a machine that previously had version 6 of the CF CLI it installed the binary cf7.exe and left the existing cf.exe (version 6) binary. However upon using the CF7 installer on brand new windows machine with no previous CF CLI version I noticed it installed both the cf7.exe binary and a symlinked cf.exe binary pointing to the cf7.exe binary. Running both cf -v and cf7 -v results in the same version output of cf version 7.0.1+fb3f929c2.2020-06-24. So to test further I went back to my local machine and deleted the old cf.exe (version 6 binary) and ran the CF7 installer once more and ah ah! There it was a new cf.exe symlink to preexisting cf7.exe binary. Though this may still be an issue with the windows installer, @jmenger this may provide you some valuable information. If you uninstall any previous version of the CF CLI you may have and then reinstall CF7 you should then be able to use both cf and cf7 commands which will both run version 7.0.1.

**Comment by jmenger** [comment]
@bmcorum Yep, I noticed that as well, but that only works when you use the installer. In our release-pipe we use an extension which requires cf.exe and the binary, not the installer. Apparently you can't put a symlink in a zip.
