### ISSUE TITLE
Cf push should fail with an explicit error message on manifest type error

### ISSUE THREAD

**Issue by o-orand** [cloudfoundry/cli#1983]
- [X] I reviewed open and closed github issues that may be related to my problem.
- [X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [X] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
I pushed a cf app (Hello World) to Pivotal Web Services, using a manifest that contains " around integer value (like `timeout: "25"`, or `instances: "2"`)

**What happened**
An `yaml: unmarshal errors:` occurred as result, without additional info

**Expected behavior**
cf cli should display an appropriate error message including with unmarshal key 

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Create a Hello World sample app or reuse an existing one, using a manifest
2. add " around integer value inside manifest, or add one like timeout: "32"
3. cf push -f <your_manifest>

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm)
- version of the CLI you are running: 7.0.1+fb3f929c2.2020-06-24
- version of the CC API Release you are on:    "api_version": "2.151.0"

**Comment by JenGoldstrich** [comment]
Hello @o-orand!

Thank you for submitting this issue, we absolutely agree that `yaml: unmarshall errors:` was not the best error message

The .yml library we are using unfortunately does not provide helpful errors about which keys specifically are wrong, we have changed the error message in https://github.com/cloudfoundry/cli/commit/58a0eb060da6fb7c2a54e5cd58ebd528825a67f4 this commit to be something like..

```
cf push pora
Unable to push app because manifest /home/aberezovsky/workspace/cf-acceptance-tests/assets/pora/manifest.yml is not valid yaml.
FAILED
```

If that sounds good to you we will close this issue when we next release v7 and this error message improvement goes out.  

Thanks!
Jenna and @nickjameswebb

**Comment by o-orand** [comment]
Hello @JenGoldstrich,
For me, wrapping `yaml: unmarshall errors:` into another error give a better user experience :smile: , thanks !

Unfortunately, in this case, I'm not sure it's going to be helpfull, as it is a 'type error'. Maybe it's possible to include hints in error message, like  
`.... manifest.yml is not valid yaml. Please ensure yaml syntax and yaml types are corrects. See http://v3-apidocs.cloudfoundry.org/version/<CC_API_VERSION>/index.html#the-manifest-schema` or any better wording :wink: 

BR
Olivier

**Comment by JenGoldstrich** [comment]
Hey @o-orand 

This is very valuable feedback, we've decided to not add that hint text for now, but we are logging this feedback and will consider again in the future.  We'd be worried about exposing a link to CAPI docs in case that link ever moves. 

The change in the error message we previously listed will go live in the next v7 release and when it does, we will close this issue, please feel free to open another one to talk more about linking to CAPI docs or improving this error further!

Thank you!
Jenna and @heyjcollins

**Comment by JenGoldstrich** [comment]
This change has been released [here](https://github.com/cloudfoundry/cli/releases/tag/v7.1.0) in v7.1.0

Thank you for your feedback @o-orand !!
