### ISSUE TITLE
CF7 marketplace fails with CF deployment version v12.42.0

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#2001]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.
- [x] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**

* As a CF developer running against a CF deployment version  [v12.42.0](https://github.com/cloudfoundry/cf-deployment/commit/5399285bfca99c9d30c68368cee12e38a2dc2632)
* When running `cf marketplace`
* I expect the marketplace to be displayed using V2 or V3 api is the minimum prereqs documented in https://github.com/cloudfoundry/cli#the-initial-ga-of-the-v7-cf-cli-is-opt-in is met:

> The v7 CLI's minimum supported version of the CC APIs are v2.128.0 and v3.63.0 (published in CAPI release v1.74.0).

**What happened**

```
$ cf m
Getting all service offerings from marketplace in org osb-cmdb-backend-services-org-client-5 / space noop-ondemand as gberche...
The query parameter is invalid: Unknown query parameter(s): 'fields'. Valid parameters are: 'page', 'per_page', 'order_by', 'available', 'broker_catalog_ids', 'names', 'organization_guids', 'service_broker_guids', 'service_broker_names', 'service_instance_guids', 'service_offering_guids', 'service_offering_names', 'space_guids', 'include', 'label_selector', Invalid included resource: 'service_offering'. Valid included resources are: 'space.organization'
FAILED

$ CF_TRACE=true cf m
Getting all service offerings from marketplace in org osb-cmdb-backend-services-org-client-5 / space noop-ondemand as xxx ...
REQUEST: [2020-07-27T16:58:28+02:00]
GET /v3/service_plans?fields%5Bservice_offering.service_broker%5D=name%2Cguid&include=service_offering&space_guids=f81987fd-ad60-4e06-81b7-fa33b97a1f11 HTTP/1.1
Host: api.redacted-domain
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/7.0.1+fb3f929c2.2020-06-24 (go1.13.8; amd64 linux)

RESPONSE: [2020-07-27T16:58:28+02:00]
HTTP/1.1 400 Bad Request
Content-Length: 569
Content-Type: application/json; charset=utf-8
Date: Mon, 27 Jul 2020 14:58:28 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Runtime: 0.004311
X-Vcap-Request-Id: ef70decc-e852-4670-6815-4e0715e4ed6a::4c7c7f3a-1ca4-47cf-97ae-ec84f9dc4fbe
X-Xss-Protection: 1; mode=block
{
  "errors": [
    {
      "code": 10005,
      "detail": "The query parameter is invalid: Unknown query parameter(s): 'fields'. Valid parameters are: 'page', 'per_page', 'order_by', 'available', 'broker_catalog_ids', 'names', 'organization_guids', 'service_broker_guids', 'service_broker_names', 'service_instance_guids', 'service_offering_guids', 'service_offering_names', 'space_guids', 'include', 'label_selector', Invalid included resource: 'service_offering'. Valid included resources are: 'space.organization'",
      "title": "CF-BadQueryParameter"
    }
  ]
}

$ cf curl v2/info | grep api_version
   "api_version": "2.147.0",


```

**Expected behavior**

Ideally, CF7 uses the V2 API matching the documented min v2 version ( v2.128.0) if it detects that v3 version is not matching min prereq

As a fallback, a clean error message such as `this cli version does not support the backend CF server, please switch back to cf v6 version`

**To Reproduce**

See detailed steps above

**Provide more context**
- platform and shell details : ubuntu 18.04 bash
- version of the CLI you are running: `cf version : cf version 7.0.1+fb3f929c2.2020-06-24`
- version of the CC API Release you are on: CF deployment version  [v12.42.0](https://github.com/cloudfoundry/cf-deployment/commit/5399285bfca99c9d30c68368cee12e38a2dc2632) capi-version: "1.92.0"

**Comment by FelisiaM** [comment]
Hi @gberche-orange 

Thanks for raising the issue.

I believe there is some miss information about the minimum required v3 API for the v7 CLI. There is an issue opened (#2008) about that. Apologies for the confusion. 

The correct minimum version of capi that the v7 CLI supports is [3.85.0](http://v3-apidocs.cloudfoundry.org/version/3.85.0/#get-a-service-plan). This is part of `capi-release` [v1.95.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.95.0) and part of `cf-deployment` [v13.5.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v13.5.0)
Moving to that version would fix your issue. 

There is no fallback mechanism in any of the v7 commands since they are intended to be used only with v3 API. Only commands that need resources that have not been exposed in v3 API will be communicating to v2 API. 

Thanks,
Felisia

**Comment by gberche-orange** [comment]
thanks @FelisiaM /CC @heyjcollins

How does the CLI/SAPI teams envison supporting users that work with both recent CF deployments (e.g. PWS) and old CF deployments ?

The currently recommended [version switching procedure](https://github.com/cloudfoundry/cli#version-switching) is not possible in a number of scenarios similar to feedback provided by @ukabu at https://github.com/cloudfoundry/cli/issues/1974#issuecomment-657729669 

Also, the lack of a user friendly message such as `this cli version does not support the backend CF server, and requires a CF server with API version 3.85.0, please switch back to cf v6 version to proceed` will imply higher support costs for CF admins and unsatisfied CF users :-(

**Comment by FelisiaM** [comment]
Thanks for the response @gberche-orange 

I understand that there are some use cases that have been made more complicated. I think it would be good to gather all opinions about the issues with the `cf7` command being renamed to `cf` in issue #1974. That way us and the CLI team can gather all the necessary feedback.

Regarding the CLI version support, I believe there is a warning issued when the user is authenticated that explains that certain commands will not work correctly: `Warning: Your targeted API's version (3.82.0) is less than the minimum supported API version (3.85.0). Some commands may not function correctly.`

**Comment by gberche-orange** [comment]
thanks @FelisiaM, I've commented #1974 

> Regarding the CLI version support, I believe there is a warning issued when the user is authenticated that explains that certain commands will not work correctly: Warning: Your targeted API's version (3.82.0) is less than the minimum supported API version (3.85.0). Some commands may not function correctly.

As a user upgrading to v7, I was not displayed this message since I was already logged in. I would expect many existing users to experience the same.

Should the warning message instruct users to use cf cli V6 instead ?
