### ISSUE TITLE
Release notes need to be updated with known issues.

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/cli#2002]
**What's the user value of this feature request?**
When an issue is found in a particular version customers could be able to look at the release notes to know if there are known issues so they could pick which release they should use.

**Who is the functionality for?**
End users of the CLI

**How often will this functionality be used by the user?**
Quite often to know if there are known issues with certain releases.

**Who else is affected by the change?**
NO

**Is your feature request related to a problem? Please describe.**
For 7.0.0 and 7.0.1 there was an issue in the CLI where our customers were prevented from picking up the version due to a known issue.  We would like to have seen the issue addressed in the release notes so we could more easily point customers to explanations.

**Describe the solution you'd like**
Update release notes after the fact to indicate known issues.  As cf-deployment does.

**Describe alternatives you've considered**
We need somewhere to keep known issues against releases.  If this can be easily searched in issues then that would be sufficient but the issues are closed and not able to be found easily.

**Additional context**
None

**Comment by jpalmerpivotal** [comment]
Updated
