### ISSUE TITLE
Clarify supported API version for v7

### ISSUE THREAD

**Issue by bbodenmiller** [cloudfoundry/cli#2008]
As noted at https://github.com/cloudfoundry/cli/commit/f9f34785be90af3a4b1aca9d82733e18e4a0887a#r40956344 various parts of `README.md` and https://github.com/cloudfoundry/cli/releases disagree about minimum version of API supported. 

https://github.com/cloudfoundry/cli/blame/master/README.md#L47

> The v7 CLI's _minimum supported version_ of the CC API is `v3.85.0` (published in [CAPI release v1.95.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.95.0)).</br>

https://github.com/cloudfoundry/cli/blame/master/README.md#L54

> The v7 CLI's _minimum supported version_ of the CC APIs are `v2.128.0` and `v3.63.0` (published in [CAPI release v1.74.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.74.0)).</br> 

https://github.com/cloudfoundry/cli/blame/master/README.md#L208

> The v7 CLI's minimum supported version of the CC API is `v3.85.0` (published in [CAPI release v1.95.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.95.0)).

https://github.com/cloudfoundry/cli/releases/tag/v7.0.0

> Minimum API Version: 3.85.0 (cf deployment v13.5.0)

https://docs.cloudfoundry.org/cf-cli/v7.html

> The cf CLI v7 requires cf-deployment v13.5.0 or later.
> 
> This version of cf-deployment contains CAPI release v1.95.0, which provides the CAPI v3 API version 3.85.0.

cf CLI / https://github.com/cloudfoundry/cli/blob/master/command/v7/shared/version_checker.go#L9

> Warning: Your targeted API's version (x) is less than the minimum supported API version (3.85.0). Some commands may not function correctly.

**Comment by heyjcollins** [comment]
Thanks for pointing this leftover from v7-beta days. Cleaned it up here: https://github.com/cloudfoundry/cli/commit/7a2fce8c9443148b2ab151a9f855b27b2a3f96db
