### ISSUE TITLE
Breaking change to v7 create-org is not documented

### ISSUE THREAD

**Issue by lisamburns** [cloudfoundry/cli#2012]
- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.
- [x] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
Trying to switch scripts from v6 to v7. Creating an org fails with client credentials, where the client has only cloud controller admin. It looks like in v6, create-org succeeded with just the cloud_controller.admin scope, whereas in v7, create-org needs the client to have both cloud_controller.admin and clients.read scope (or clients.admin, or zones.uaa.admin). The error happens when attempting to assign the OrgManager role.

**What happened**
It failed. The change in behavior was not documented here: https://docs.cloudfoundry.org/cf-cli/v7.html#table

**Expected behavior**
I expected it to succeed. Or I expected this change to be documented in the table above.

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `cf auth <client> <client-secret> --client-credentials` with a client that has only cloud_controller.admin and no other scopes.
2. Run `cf create-org foo`
3. Permission denied

**Provide more context**
Linux, running the versions of CLI and CAPI specified here:
https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L2656-L2658
https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L2544-L2546
Slack conversation here:
https://cloudfoundry.slack.com/archives/C032824SM/p1595542391482500

**Comment by heyjcollins** [comment]
Thanks @lisamburns - we're looking into this issue with CAPI folks and good catch!

**Comment by heyjcollins** [comment]
Hey @lisamburns - We updated the [**Differences Table**](https://docs.cloudfoundry.org/cf-cli/v7.html#table) in our documentation to reflect the permissions required to run `create-org` in v7 vs. v6.
I'm going to go ahead and close this issue with this comment, but please feel free to reopen if you'd like engage in further discussion and thank you very much for bringing this up!
