### ISSUE TITLE
cf revisions prints OK

### ISSUE THREAD

**Issue by vitreuz** [cloudfoundry/cli#2034]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.
- [x] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
`cf revisions` is a list command. As a list command, it is not supposed to print `OK` as per the style guide [list command section](https://github.com/cloudfoundry/cli/wiki/CF-CLI-Style-Guide#list-commands)

**What happened**
`cf revisions` prints `OK`

**Expected behavior**
`cf revisions` should not print `OK` for any code fork.

**To Reproduce**
1. Run `cf revisions <appname>` with any app (valid and invalid apps)

**Comment by heyjcollins** [comment]
Thanks for reporting this @vitreuz - we'll take care of this and release a fix in v7.1.0

**Comment by reid47** [comment]
We recently released [v7.2.0](https://github.com/cloudfoundry/cli/releases/tag/v7.2.0), which should contain a fix for this issue. Thanks for your help!
