### ISSUE TITLE
Can not login with v6.52.0 using $CF_HOME/.cf/config.json from earlier version

### ISSUE THREAD

**Issue by HannesHasselbring** [cloudfoundry/cli#2035]
- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ ] I am reporting a bug that others will be able to reproduce.
- [ ] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
Used version MacOS: cf version 6.52.0+b086fe522.2020-08-26 
Used Version Linux: cf version 6.52.0+b086fe522.2020-08-26

Given an existing config in `$CF_HOME/.cf/config.json` or `$HOME/.cf/config.json` created by `cf version 6.51.0+2acd15650.2020-04-07`
```bash
CF_TRACE=1 ./cf a
FAILED
No API endpoint set. Use 'cf login' or 'cf api' to target an endpoint.
```
With a `config.json` created by `cf version 6.52.0+b086fe522.2020-08-26` the example above works

**What happened**
A clear and concise description of what happen.

**Expected behavior**
getting a list of all Apps
```bash
cf a
Getting apps in org <ORG> / space production as <USER>...
OK
...
```

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `cf login` with `cf version 6.51.0+2acd15650.2020-04-07` 
2. List all apps with `cf version 6.52.0+b086fe522.2020-08-26` eg. `cf a`
3. See error

**Provide more context**
- Platform:
   - MacOS
   - Alpine linux x86_64 as docker container
- cf versions: see above

**Comment by JenGoldstrich** [comment]
Hello @HannesHasselbring!

This is something we have in the release notes for v6.52.0 https://github.com/cloudfoundry/cli/releases/tag/v6.52.0

```
NOTE: We bumped the config as part of the implementation. CLI users that had targeted and logged into their foundations prior to updating to this CLI version may be required to to re-login & target in order to initialize the updated config.
```

We bumped the config.json version which requires folks to re-target so we can introduce a change to the config file.

I am closing this issue, please feel free to re-open if you have any more questions or feel free to reach out to us in #cli in the OSS CloudFoundry slack!

Thanks
Jenna
