### ISSUE TITLE
cf target to accept --org-guid or --space-guid 

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#2048]
**What's the user value of this feature request?**

As a cf user 
* in order to inspect a resource from its guid (e.g. an app or a service instance)
* I need to target the associated space to be able to use usual CF CLI commands (such as `cf service` or `cf app`) by specifying the space guid such as `cf t --space-guid GUID`

**Who is the functionality for?**

For CF admins and CF developers automating using CF CLI and CF API through `cf curl` outputs which provides space_guid attached to most resources (app, service instance, route etc...)

**How often will this functionality be used by the user?**

Each time switching among space is required to inspect a resource from its guid (e.g. from audit events which only include guids)

**Who else is affected by the change?**
> Does this feature cause a breaking change? Are other users affected by this change?

No breaking change

**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Currently, additional unnessary calls need to be made to inspect an object from its guid or space_url. 

```bash
      cf curl ${space_url} | jq -r '.entity | [ .name, .organization_guid, .organization_url ] | @tsv' |
        while IFS=$'\t' read -r space_name organization_guid organization_url; do
          org_name=$(cf curl ${organization_url} | jq -r '.entity.name')
          #            echo "---------------------------------------------------------------------"
          #            echo "associated space:"
          #            echo "$ cf t -o $org_name -s $space_name"
          cf t -o $org_name -s $space_name >/dev/null
```

See https://github.com/orange-cloudfoundry/cf-cli-cmdb-scripts/blob/ec3aa283989e638bcc326b3532e04dd4c6f4f063/cf-cli-cmdb-functions.bash#L271-L326 for full example

**Describe the solution you'd like**

 `cf t --space-guid GUID`
 `cf t --org-guid GUID`

**Describe alternatives you've considered**

* CF curl scripting (which waste API calls)
* directly tweak $CF_HOME/.cf/config.json would be fragile and intrusive
```json
 "OrganizationFields": {
    "GUID": "018ee7d1-c4d4-4975-84e9-f92610ef5306",
    "Name": "osb-cmdb-backend-services-org-client-0"
  },
[...]
  "SpaceFields": {
    "GUID": "",
    "Name": "",
    "AllowSSH": false
  },
```

**Additional context**

**Comment by heyjcollins** [comment]
Thanks for the feature request @gberche-orange.
Would it not be more direct to capture details for a resource without retargeting?

You're probably already aware of this, but if you have the guid for the resource, you can `cf curl /v3/RESOURCE/GUID` to view details associated with out being in the same org/space (assuming you have the right access credentials to access information for that resource).

**For example:**
I have an app in org `o` / space `s`
My CLI is currently targeting org `system`
```
cf curl /v3/apps/$appguid
{
   "guid": "9c0d1de8-858d-4825-9f54-f789a3ce499f",
   "created_at": "2020-09-15T23:19:07Z",
   "updated_at": "2020-09-22T19:17:36Z",
   "name": "dora1",
   "state": "STARTED",
   "lifecycle": {
      "type": "buildpack",
      "data": {
         "buildpacks": [],
         "stack": "cflinuxfs3"
      }
   },
   "relationships": {
      "space": {
         "data": {
            "guid": "8fca272e-2381-4955-ab1b-e81910fef937"
         }
      }
   },
   "metadata": {
      "labels": {},
      "annotations": {}
   },
   "links": {
      "self": {
         "href": "https://api.env.cli.fun/v3/apps/9c0d1de8-858d-4825-9f54-f789a3ce499f"
      },
      "environment_variables": {
         "href": "https://api.env.cli.fun/v3/apps/9c0d1de8-858d-4825-9f54-f789a3ce499f/environment_variables"
      },
      "space": {
         "href": "https://api.env.cli.fun/v3/spaces/8fca272e-2381-4955-ab1b-e81910fef937"
      },
      "processes": {
         "href": "https://api.env.cli.fun/v3/apps/9c0d1de8-858d-4825-9f54-f789a3ce499f/processes"
      },
      "packages": {
         "href": "https://api.env.cli.fun/v3/apps/9c0d1de8-858d-4825-9f54-f789a3ce499f/packages"
      },
      "current_droplet": {
         "href": "https://api.env.cli.fun/v3/apps/9c0d1de8-858d-4825-9f54-f789a3ce499f/droplets/current"
      },
      "droplets": {
         "href": "https://api.env.cli.fun/v3/apps/9c0d1de8-858d-4825-9f54-f789a3ce499f/droplets"
      },
      "tasks": {
         "href": "https://api.env.cli.fun/v3/apps/9c0d1de8-858d-4825-9f54-f789a3ce499f/tasks"
      },
      "start": {
         "href": "https://api.env.cli.fun/v3/apps/9c0d1de8-858d-4825-9f54-f789a3ce499f/actions/start",
         "method": "POST"
      },
      "stop": {
         "href": "https://api.env.cli.fun/v3/apps/9c0d1de8-858d-4825-9f54-f789a3ce499f/actions/stop",
         "method": "POST"
      },
      "revisions": {
         "href": "https://api.env.cli.fun/v3/apps/9c0d1de8-858d-4825-9f54-f789a3ce499f/revisions"
      },
      "deployed_revisions": {
         "href": "https://api.env.cli.fun/v3/apps/9c0d1de8-858d-4825-9f54-f789a3ce499f/revisions/deployed"
      },
      "features": {
         "href": "https://api.env.cli.fun/v3/apps/9c0d1de8-858d-4825-9f54-f789a3ce499f/features"
      }
   }
}
```

**Comment by gberche-orange** [comment]
thanks @heyjcollins for considering this feature
> Would it not be more direct to capture details for a resource without retargeting?

Unfortunately I do need to leverage the CF CLI native UX (e.g. `cf service`) which goes well beyond formatting the output of a single `/v3/RESOURCE/GUID` (see the last 4 relevant endpoint calls below)

```
CF_TRACE=true cf service my-service-instance | grep 'GET '
GET /v2/info HTTP/1.1
GET / HTTP/1.1
GET /login HTTP/1.1
GET /v2/spaces/15704fa0-7dc5-482e-8d03-0ffc034f8483/service_instances?q=name%3Asec-group-broker-filter-cf-smoketest-1599561485&return_user_provided_service_instances=true HTTP/1.1
GET /v2/config/feature_flags HTTP/1.1
GET /v2/service_instances/3fdcc497-6b26-442c-b4fe-2046de1d64d5/shared_to HTTP/1.1
GET /v2/service_plans/d92e72c3-b3c8-4d9d-920a-52c4e1b932e4 HTTP/1.1
GET /v2/services/457d323c-e3ad-4f41-9ca8-c22dd5cd6ffe HTTP/1.1
GET /v2/service_instances/3fdcc497-6b26-442c-b4fe-2046de1d64d5/service_bindings HTTP/1.1

$ cf -v
cf version 7.1.0+4c3168f9a.2020-09-09
```

**Comment by a-b** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket with the necessary information mentioned in our issue template.
