### ISSUE TITLE
Binary is still cf7

### ISSUE THREAD

**Issue by mayrstefan** [cloudfoundry/cli#2051]
**Describe the bug and the command you saw an issue with**
The README says "If you've been pulling down the v7 CF CLI beta previously, you will notice the name of the v7 binary has changed from cf7 to cf"

**What happened**
Current RPM and Windows Installer both a binary still named cf7
Old 6.x and 7.x CLI are now installed

**Expected behavior**
I expected to get only a cf binary, not a cf7 binary
Also now two packages are installed instead of the old one being updated

**Exact Steps To Reproduce**
Install cf CLI with Red Hat RPM or Windows Installer
1. try `cf` - still the old CLI (6.5x)
2. try `cf7` - new CLI

**Provide more context**
- Windows and SUSE Linux Enterprise Server (using the RPM
- Version 7.1.0

**Comment by nickjameswebb** [comment]
@mayrstefan thanks for pointing this out. The README was incorrect, we eventually decided to keep the binary at `cf7` and create a symlink from `cf -> cf7` for flexibility with the existing cf CLI v6. The only exception is the Windows binary zip, where we ship a copy of the binary at both `cf7` and `cf`. The README and Version Switching Guide have been updated!

cc @a-b
