### ISSUE TITLE
CF7 "scale" doesn't work on stopped apps (regression?)

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/cli#2053]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
We have a stopped CF app with 2 instances. With CF CLI v6 (6.52.0) we can call `cf scale <app> -i 1` and downscaling works. With CF CLI v7 (7.1.0) the "scale" command hangs in "Instances starting...". Seems that the "scale" command assumes that the app is running, see https://github.com/cloudfoundry/cli/blob/78c0f37d0cf6e02fe24b78f1de155f2fe0fbaa77/command/v7/scale_command.go#L58

**Expected behavior**
We expected the "scale" command to behave as in CF CLI v6 (Or to mention the incompatibility on https://docs.cloudfoundry.org/cf-cli/v7.html).

**Exact Steps To Reproduce**
1. cf7 push \<testapp>
2. cf7 scale \<testapp> -i 2
3. cf7 stop \<testapp>
4. cf7 scale \<testapp> -i 1

**Provide more context**
Ubuntu 18.04.4 LTS
cf7 version 7.1.0+4c3168f9a.2020-09-09
capi-release 1.98.0

**Comment by heyjcollins** [comment]
Thanks for reporting this regression @jochenehret.
I've pulled it into our backlog and we'll publish a fix in the next v7 release.

**Comment by jochenehret** [comment]
Great, thanks!

**Comment by reid47** [comment]
We recently released [v7.2.0](https://github.com/cloudfoundry/cli/releases/tag/v7.2.0), which should contain a fix for this issue. Thanks for your help!
