### ISSUE TITLE
CF7 fails to map a route after push if the org/space is changed during the app staging REGRESSION

### ISSUE THREAD

**Issue by mike1808** [cloudfoundry/cli#2068]
**Describe the bug and the command you saw an issue with**
I have a script which pushes multiple apps in multiple orgs and spaces. To minimize the wait time I run `cf push` commands in background. I try to push 10 apps to every space so when the 10th app in the space is pushed I change my current context and target the next space.

**What happened**
When the staging for the 10th app is finished it starts mapping route to it and it fails with:

`For application 'bin-10': Routes cannot be mapped to destinations in different spaces`.

**Expected behavior**
`cf` CLI should have a mechanism to save its context (space/org) when it's executed so the change in org/space doesn't affect already executed command. 

This scenario was possible with CF6 but not with CF7.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. `cf target -s space1`
2. `cf push app-1 & sleep 5; cf target -s space2`

**Provide more context**
- `cf version 7.1.0+4c3168f9a.2020-09-09`
- [cf-for-k8s current develop branch](https://github.com/cloudfoundry/cf-for-k8s/tree/549717840dff5a1af5d6bbda450e825bfcd60078)
- `Linux ant 5.4.0-1024-gcp #24-Ubuntu SMP Sat Sep 5 02:07:13 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by heyjcollins** [comment]
@mike1808 - thanks for reporting this issue to us.
We're having trouble reproducing it.

Could you please run your script and for the 10th app in the loop, run the commands with a `-v` and include the verbose output here for us to review?

**Comment by heyjcollins** [comment]
@mike1808 - we'll take a look at this once you've had a chance to provide us with the additional information requested in the previous comment.

**Comment by mike1808** [comment]
@heyjcollins sorry for the delay. This is not critical, I'll provide repro script sooner this week.

**Comment by a-b** [comment]
You can assign a unique `CF_HOME` for each process to ensure consistent settings for each app.
I'm resolving this issue now. Please don't hesitate to reopen it if you have any more questions or comments.
