### ISSUE TITLE
cf api address-to-api-server logs you out instead of using existing login

### ISSUE THREAD

**Issue by stokescomp** [cloudfoundry/cli#2075]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Login using cf login and provide your username and password and choose the org and space.
Now use cf spaces to check if you are logged in. It lists the spaces I can see.
Next use the command
`cf api api.pvu.cf.churchofjesuschrist.org`

**What happened**
It sets the api but logs out at the same time. 
```
Setting API endpoint to api.pvu.cf.churchofjesuschrist.org...
OK
API endpoint:   https://api.pvu.cf.churchofjesuschrist.org
API version:    3.87.0
Not logged in. Use 'cf login' or 'cf login --sso' to log in.
```

**Expected behavior**
I expect the cli to set the api server and stay logged in. In V6 it didn't log you out when running the cf api server-path command.
I tried it in WSL in windows and in command line cdm.exe and in bash command line and it does the same thing.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run cf api server-url
```
Setting API endpoint to api.abc.cf.domain.org...
OK

API endpoint:   https://api.abc.cf.domain.org
API version:    3.87.0

Not logged in. Use 'cf login' or 'cf login --sso' to log in.
```

**Provide more context**
Windows 10 with cmd.exe and also tried WSL and tried bash command line.
CF CLI Version: 7.1.0+4c3168f9a.2020-09-09
CF API version: 3.87

**Comment by heyjcollins** [comment]
Hey @stokescomp - we made a change to both v6 and v7 to remove/revoke existing tokens whenever a user switches api endpoints or logs out - this was intentional for security.

If you get the latest v6 - 6.53.0, you should have the same experience.

I'm going to close this out with this comment, but feel free to reopen if you want to discuss this issue further.

Thanks for reaching out!

Josh
