### ISSUE TITLE
No org targeted, use 'cf.exe target -o ORG' to target an org. FAILED

### ISSUE THREAD

**Issue by amiwrcd** [cloudfoundry/cli#2080]
Hello! I am using "Cloud Foundry apps" to deploy my applications to the IBM Cloud. Haven't used this service before.
I am using Windows for converging. I did everything step by step as described on the site.
Logged into my IBM Cloud account and selected the API endpoint.
`ibmcloud login`
Targeting Cloud Foundry organization and space:
`ibmcloud target --cf`

But in the third step. When needed from the get-start-python directory
submit my app to IBM Cloud
i am getting error when running command:
`ibmcloud cf push`

error:

```
$ ibmcloud cf push
FAILED
No CF API endpoint set.
Use 'C: \ Users \ ami \ .bluemix \ .cf \ cfcli \ ibmcloud.exe target --cf-api ENDPOINT [-o ORG] [-s SPACE]' to target Cloud Foundry, or 'C: \ Users \ ami \ .bluemix \ .cf \ cfcli \ ibmcloud.exe target --cf 'to target it interactively.
```

And also I ran the command:

```
$ cf.exe create-org ORG

Creating org ORG as mygmail5@gmail.com...
OK

Org ORG already exists.
```

ORG - exists

```


$ ibmcloud cf push
Invoking 'cf push'...

No org targeted, use 'cf.exe target -o ORG' to target an org.
FAILED
```

How do I create an ORG? Help me to understand!

**Comment by amiwrcd** [comment]
> We have created an issue in Pivotal Tracker to manage this:
> 
> https://www.pivotaltracker.com/story/show/175285016
> 
> The labels on this github issue will be updated when the story is started.

When I use the command: ibmcloud target --cf I see empty ones: "Org" "Space" Next I want to create an ORG ibmcloud cf create-org ORG Writes success! again I use the command: ibmcloud target --cf again I see empty ones: "Org" "Space" I took a screenshot of my steps: https://ibb.co/ZNnf9G3

**Comment by heyjcollins** [comment]
Hey @amiwrcd ,
Firstly - it looks like you're using the IBM-Bluemix version of the cli - which wraps the cf CLI - so I'm not super familiar with the user experience but I looked at the screenshot of the steps (thanks for sharing that).

Questions:
Are you actually targeting and org and space before you push?
what happens if you run:
```
cf target -o SOME_ORG -s SOME_SPACE_IN_THAT_ORG
cf push YOUR_APP
```

also - what version of the CLI are you using right now (run `cf -v`)?

**Comment by heyjcollins** [comment]
Hi @amiwrcd -
Since there's been no response for a few weeks, I'm going to close this issue.
Please feel free to reopen with comments and answers to the questions I posed previously if you still need help.

**Comment by abhinavkrdubey** [comment]
Hi, I have been facing same issue, i have done everything as done in above issue. The CLI version is "6.53.0+8e2b70a4a.2020-10-01"
