### ISSUE TITLE
Timeout error while cf push

### ISSUE THREAD

**Issue by an391111** [cloudfoundry/cli#2085]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [ ] I reviewed open and closed github issues that may be related to my problem.
- [ ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ √] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Provide details on what you were trying to do (and why).
- Getting Timeout issue while cf push, failing on uploading code file. This issue is coming intermittently/randomly at any time.Below is the error code.
$ Response 502
$ code 0, Title : , Detail: 502 Bad gateway : Registered endpoint failed to handle request.**

**What happened**
A clear and concise description of what happen.
- Need to push code mutiple time to get success result.

**Expected behavior**
- It should not give timeout error, as this is critical bug.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `cf push <app-name> --strategy rolling`
Failing while pushing through azure devops(Windows) , VMware accepted that this issue is related to cli.

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm)
* Azure devops (Windows)
- version of the CLI you are running
* cf v7.1.0+4c3168f9a
- version of the CC API Release you are on
* CAPI - 1.95.2 

**Notes regarding V6 and V7 CLI support:** 
- V6:
  - Minimum supported version of CF Deployment: v7.0.0 (CAPI Release: 1.74.0 (APIs 2.128.0 and 3.63.0))
  - Maximum supported version of CF Deployment: v13.4.0 (CAPI Release: 1.94.0 (APIs 2.149.0 and 3.84.0))
- V7:
  - Minimum supported version of CF Deployment: v13.5.0 (CAPI Release: 1.95.0 (APIs 2.150.0 and 3.85.0))

**Comment by David-Pivotal** [comment]
For your reference, a Jira had been opened to the CAPI team. The link is https://pivotal-io.atlassian.net/browse/CC-36. The backgournd and the logs can be found in the Jira too. It is suspected that this issue being in the CLI itself.

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
