### ISSUE TITLE
cf delete: not able to delete service instance while update in progress

### ISSUE THREAD

**Issue by snehalborse** [cloudfoundry/cli#2091]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [ ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
1) Create cf service instance and delete it while create in progress
`cf create-service my-service -c create.json`

2) Update cf service instance and delete it while update in progress
`cf update-service my-service -c update.json`

**What happened**
for scenario 1 I was able to delete the service while it was still creating

for scenario 2 I get error if I try any operation while update in progress
`Server error, status code: 409, error code: 60016, message: An operation for service instance my-service is in progress.`

**Expected behavior**
Consistent behavior for both scenarios i.e. either get error for both or allow both.

**Exact Steps To Reproduce**
1. Create a service instance
2. While create in progress try to delete it
3. Create a service instance
4. Once created try to update it
5. Try to delete service instance while update in progress

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm)
Linux version 4.4.121-92.141, bash

- version of the CLI you are running
cf version 6.51.0+2acd15650.2020-04-07

- version of the CC API Release you are on 
2.151.0

**Comment by blgm** [comment]
Hi @snehalborse, deleting a service instance while an update is in progress is not supported by Cloud Foundry using either the V2 or the V3 API. So this doesn't look like an error with the CLI. However, it could be argued that it's a missing feature in Cloud Foundry.

Deleting a service instance while a **create** is in progress is allowed (although it is not supported by all service brokers), so there is an argument that deleting a service instance while an update is in progress should be allowed too. I'm not aware of that feature being requested until now.

My suggestion would be that you first check that the broker in use would be capable of performing a delete operation while an update is in progress, as there's not much point in requesting a new feature in Cloud Foundry if the broker would ultimately reject the request.

**Comment by blgm** [comment]
As this isn't a CLI issue (although potentially it is a feature request for the Cloud Controller), I'm going to close this off due to inactivity. If there is a desire to progress it, a feature request should be raised for the Cloud Controller.
