### ISSUE TITLE
`cf apps` should return app names in space even if CAPI's `/stats` endpoint fails

### ISSUE THREAD

**Issue by njbennett** [cloudfoundry/cli#2093]
**Describe the bug and the command you saw an issue with**
Load of various kinds can cause several components required to serve CAPI's `/v3/processes/<appUUID>/stats` endpoint to fail. When this happens, `/stats` returns a 503, and the `cf apps` command returns no information, including information that it has that might be useful for debugging or fixing the problem affecting the `/stats` endpoint. It should instead return the information that it does have, and report state of the processes as unknown.

 "Stats unavailable: Stats server temporarily unavailable."

**What happened**
I pushed ~2000 apps to a single space, then ran the `cf apps` command. The command returned
```
→ cf apps
Getting apps in org scale-tests-2 / space scale-tests-2 as admin...

Stats unavailable: Stats server temporarily unavailable.
FAILED
```

**Expected behavior**
I expected to see something like
```
Getting apps in org scale-tests-2 / space scale-tests-2 as admin...

name     requested state   processes   routes
bin-24   started           web:??/2     bin-24.apps.scale-testing.k8s.capi.land
bin-25   started           web:??/2     bin-25.apps.scale-testing.k8s.capi.land
bin-26   started           web:??/2     bin-26.apps.scale-testing.k8s.capi.land
bin-27   started           web:??/2     bin-27.apps.scale-testing.k8s.capi.land
bin-28   started           web:??/2     bin-28.apps.scale-testing.k8s.capi.land
bin-29   started           web:??/2     bin-29.apps.scale-testing.k8s.capi.land
catnip   stopped           web:??/10
meow     stopped           web:??/10    meow.apps.scale-testing.k8s.capi.land
```
as the fields marked with "??" are the only parts of this display that the CLI does not, at this point, know -- that information is discoverable if you run with `CF_TRACE=true.`

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
_Ways to up the system for failure_
0. Run `cf push catnip -i <some ridiculous number>` (probably with `-m 50i`
0. Push a version of CAPI that always returns a 503 to the /stats endpoint
0. Modify the /stats call with a proxy

__Once you have a failing CAPI_
0. `cf apps`

**Provide more context**
- platform and shell details: Mac OS X 10.15.7 iTerm
- version of the CLI you are running: cf version 7.1.0+4c3168f9a.2020-09-09
- version of the CC API Release you are on: cf-for-k8s tags/v1.0.0.RC1~21

**Comment by heyjcollins** [comment]
Hi @njbennett,
Thanks for reporting this issue. It seems like a reasonable enhancement to provide the information we **do** have in this situation and we'll consider it for prioritization.

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
