### ISSUE TITLE
run `cf config` right after upgrade from < 6.52.0 will purge plugin repos in config

### ISSUE THREAD

**Issue by archerzz** [cloudfoundry/cli#2096]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**

CF CLI >= `6.52.0` has bumped the config data version to `v4`, thus will purge the some config data the first time you run commands after upgrading from CLI version < `6.52.0`. However, if the first command I run is to update config, e.g. `cf config --color false`, then it will purge all config data including the plugin repo settings.

**What happened**

If I run `cf config --color false` right after upgrading from CF CLI version < `6.52.0`, then plugin repos settings are purged as well.

**Expected behavior**

Plugin repo settings should be kept after upgrading, unless users explicitly set them.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Install a CF CLI version < `6.52.0` which is still on `v3` config data
2. Run `cf list-plugin-repos` and there should be one default plugin repo.
3. Upgrade to CF CLI version >= `6.52.0` which is on `v4` config data
4. Run `cf config --color false`
5. Run `cf list-plugin-repos`, and all plugin repos are gone.

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm): irrelevant
- version of the CLI you are running:
  - old: 6.48.0
  - new: 6.52.0
- version of the CC API Release you are on: irrelevant

**Notes regarding V6 and V7 CLI support:** 
- V6:
  - Minimum supported version of CF Deployment: v7.0.0 (CAPI Release: 1.74.0 (APIs 2.128.0 and 3.63.0))
  - Maximum supported version of CF Deployment: v13.4.0 (CAPI Release: 1.94.0 (APIs 2.149.0 and 3.84.0))
- V7:
  - Minimum supported version of CF Deployment: v13.5.0 (CAPI Release: 1.95.0 (APIs 2.150.0 and 3.85.0))

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
