### ISSUE TITLE
AADSTS900144: The request body must contain the following parameter: 'scope'

### ISSUE THREAD

**Issue by macevil** [cloudfoundry/cli#2099]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
I have configured my UAA with an Azure AD OIDC Identity Provider and want to authenticate against it. The browser login works, but the cf cli login/auth does not.

**What happened**
When trying to login the error message appears: AADSTS900144: The request body must contain the following parameter: 'scope'

**Expected behavior**
Successful login with cf cli.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Configuring Azure Active Directory as an OIDC Identity Provider https://docs.pivotal.io/p-identity/1-13/azure-oidc/config-azure.html#config-sso
2. Configuring UAA Identity Provider
```
{
    "type": "oidc1.0",
    "config": {
        "emailDomain": ["*"],
        "attributeMappings": {
            "user_name": "email"
        },
        "addShadowUserOnLogin": true,
        "storeCustomAttributes": true,
        "linkText": "Login with AZURE AD",
        "showLinkText": true,
        "clientAuthInBody": true,
        "skipSslValidation": false,
        "relyingPartyId": "***",
        "relyingPartySecret": "***",
        "scopes": ["openid"],
        "discoveryUrl": "https://login.microsoftonline.com/TENANTID/v2.0/.well-known/openid-configuration",
        "passwordGrantEnabled": true,
        "responseType": "code"
    },
    "originKey": "azure",
    "name": "azure",
    "active": true
}
```
3. `cf auth steve.***@outlook.com password --origin azure -v`

```
REQUEST: [2020-10-27T06:30:28+01:00]
POST /oauth/token?login_hint=%7B%22origin%22%3A%22azure%22%7D HTTP/1.1
Host: login.SYSTEM-DOMAIN
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/x-www-form-urlencoded
User-Agent: cf/7.1.0+4c3168f9a.2020-09-09 (go1.13.8; amd64 darwin)
[PRIVATE DATA HIDDEN]

RESPONSE: [2020-10-27T06:30:29+01:00]
HTTP/1.1 401 Unauthorized
Cache-Control: no-store
Content-Type: application/json
Date: Tue, 27 Oct 2020 05:30:28 GMT
Pragma: no-cache
Server: istio-envoy
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Www-Authenticate: Basic realm="UAA/client", error="unauthorized", error_description="{"error":"invalid_request","error_description":"AADSTS900144: The request body must contain the following parameter: 'scope'.\r\nTrace ID: acc08b39-56c9-48f2-b7cf-8b5d397cb000\r\nCorrelation ID: 07e345e1-086a-4deb-a790-5b9c5a5e17b7\r\nTimestamp: 2020-10-27 05:30:29Z","error_codes":[900144],"timestamp":"2020-10-27 05:30:29Z","trace_id":"acc08b39-56c9-48f2-b7cf-8b5d397cb000","correlation_id":"07e345e1-086a-4deb-a790-5b9c5a5e17b7","error_uri":"https://login.microsoftonline.com/error?code=900144"}"
X-Content-Type-Options: nosniff
X-Envoy-Upstream-Service-Time: 128
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
{
  "error": "unauthorized",
  "error_description": "{\"error\":\"invalid_request\",\"error_description\":\"AADSTS900144: The request body must contain the following parameter: 'scope'.\\r\\nTrace ID: acc08b39-56c9-48f2-b7cf-8b5d397cb000\\r\\nCorrelation ID: 07e345e1-086a-4deb-a790-5b9c5a5e17b7\\r\\nTimestamp: 2020-10-27 05:30:29Z\",\"error_codes\":[900144],\"timestamp\":\"2020-10-27 05:30:29Z\",\"trace_id\":\"acc08b39-56c9-48f2-b7cf-8b5d397cb000\",\"correlation_id\":\"07e345e1-086a-4deb-a790-5b9c5a5e17b7\",\"error_uri\":\"https://login.microsoftonline.com/error?code=900144\"}"
}
```

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm) -> macOS 10.15.7
- version of the CLI you are running -> v7.1.0
- version of the CC API Release you are on -> 3.90.0

**Notes regarding V6 and V7 CLI support:** 
- V6:
  - Minimum supported version of CF Deployment: v7.0.0 (CAPI Release: 1.74.0 (APIs 2.128.0 and 3.63.0))
  - Maximum supported version of CF Deployment: v13.4.0 (CAPI Release: 1.94.0 (APIs 2.149.0 and 3.84.0))
- V7:
  - Minimum supported version of CF Deployment: v13.5.0 (CAPI Release: 1.95.0 (APIs 2.150.0 and 3.85.0))

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
