### ISSUE TITLE
cannot operate on resource that contain a dash (-) as the first character of the name

### ISSUE THREAD

**Issue by marklindell** [cloudfoundry/cli#2100]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [ x ] I reviewed open and closed github issues that may be related to my problem.
- [ x ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ x ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ x ] I am reporting a bug that others will be able to reproduce.

I create a space with the name "-test" using the API. I was unable to work with the space via the CLI as it always returns the error:

For example:
```
cf space "-test" --guid
```

**What happened**
```
Incorrect Usage: unknown flag `t'
```

**Expected behavior**
I would expect to be able to use the CLI to manipulate resources with dashes as the first name char of the name. 

**Exact Steps To Reproduce**
I create a space with the name "-test" using the API. I was unable to work with the space via the CLI as it always returns the error:
For example:
```
cf space "-test" --guid
```
**Provide more context**
- Powershell 7 + cmd.exe Windows
- cf.exe version 6.52.0+b086fe522.2020-08-26
- "api_version": "2.152.0"

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
