### ISSUE TITLE
cf auth is rejecting passwords starting with dash with message "Incorrect Usage: unknown flag"

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#2102]
**Describe the bug and the command you saw an issue with**

* As a cf cli user
* in order to login into the CF CLI using login/passwords
* I need the CLI to accept user-defined passwords including the ones starting with - (dash)

**What happened**

The password is incorrectly interpreted as a flag and rejected

`Incorrect Usage: unknown flag `M'`

**Expected behavior**

flags should be checked against 3rd argument, but not 1st or 2nd argument (username or password)

```
cf auth --help
NAME:
   auth - Authenticate non-interactively

USAGE:
   cf auth USERNAME PASSWORD
   cf auth USERNAME PASSWORD --origin ORIGIN
   cf auth CLIENT_ID CLIENT_SECRET --client-credentials
```

**Exact Steps To Reproduce**
> Steps to reproduce the behavior; include the exact CLI commands and verbose output:

1. Run `cf auth username "-MyRandomLyGeneratedPassWord"`
2. See error

Note: escaping the dash bypasses the flag parsing, but fails login 

```
$ cf auth username "\-MyRandomLyGeneratedPassWord"
Authenticating...
Credentials were rejected, please try again.
FAILED
```

**Provide more context**
- platform and shell details ( bash "Ubuntu 18.04.5 LTS" )
- version of the CLI you are running: `cf version 7.1.0+4c3168f9a.2020-09-09` and `cf version 6.52.0+b086fe522.2020-08-26`
- version of the CC API Release you are on

**Comment by signalwerk** [comment]
@gberche-orange did you ever find a workaround? I have the same problem.

**Comment by gberche-orange** [comment]
@signalwerk Sorry, the only workaround I'm aware of is changing the account password to not start with a dash

**Comment by signalwerk** [comment]
@gberche-orange ok. thank you for your fast answer ☺️. Right now, I'm unable to do that, but let's hope that in the future we will get a solution for this.

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
