### ISSUE TITLE
cf deploy stage fails for html5 Application for SAP Cloud Platform on Cloud Foundry

### ISSUE THREAD

**Issue by anuwilson137** [cloudfoundry/cli#2104]
These are the logs:
Starting application "mta_ManageDemand_ui_deployer"...
Application "mta_ManageDemand_ui_deployer" started
Error executing application "mta_ManageDemand_ui_deployer": Deployment of html5 application content failed [Deployment Id: deploy-76e5e15c-1d09-11eb-9dbc-eeee0a80df70] Error: The resources folder resources does not exist or is empty.
Stopping application "mta_ManageDemand_ui_deployer"...
A step of the process has failed. Retrying it may solve the issue.
Process failed.

Any Advice how to solve this?

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
