### ISSUE TITLE
Stop calling the stats endpoint for a process with zero instances

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/cli#2106]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x ] I reviewed open and closed github issues that may be related to my problem.
- [ x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x ] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Provide details on what you were trying to do (and why).

```
z spring-petclinic
cf push petclinic
cf apps -v
```

**What happened**
```
...
REQUEST: [2020-11-05T12:29:16-08:00]
GET /v3/processes/2fe0d913-4d18-4078-8d10-bcdc85a5a4d7/stats HTTP/1.1
...
RESPONSE: [2020-11-05T12:29:21-08:00]
HTTP/1.1 200 OK
…
{
  "resources": null
}
…
Getting apps in org org / space space as admin...

name         requested state   processes                               routes
petclinic   started           web:1/1, executable-jar:0/0, task:0/0   petclinic.apps.disreputable-turtle.k8s-dev.relint.rocks
```

Took 12 seconds.  10 of those seconds were spent calling .../stats on the two zero-instance processes.

**Expected behavior**

I expect a near-instance response. OK, 1 or 2 seconds, not 12.

**Exact Steps To Reproduce**

See above

**Provide more context**
- OS: macos 10.15.3
- CLI: cf version 7.0.2+17b4eeafd.2020-07-24
- version of the CLI you are running
- API versions:  2.157.0 and 3.92.0

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
