### ISSUE TITLE
Unset-org-role of an OrgManager does not validate whether a user is the org's last OrgManager

### ISSUE THREAD

**Issue by reneighbor** [cloudfoundry/cli#2112]
## Issue

From Jochen Ehret (community):
Some of our users have unassigned the "OrgManager" role from themselves and no "OrgManager" was left in a particular organization. Only with the help of an admin user we could reassing the role (which is not always trivial, as you have to carefully check if a user is permitted to have access to a certain organization). Shouldn't there be some kind of safety net that prevents accidental removal of the last OrgManager? Or was that left out because it's assumed that OrgManager have to be careful with commands like "unset-org-role"?

Confirmed that we do not validate whether a user is the last OrgManager before removing that role. (In v3 we do validate whether an OrgUser has Space[ROLE] responsibilities before proceeding with the delete).

CF7: https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/controllers/v3/roles_controller.rb#L63

CF6: https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/controllers/runtime/organizations_controller.rb#L203

## Steps to Reproduce

[ordered list the process to finding and recreating the issue, example below]

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you are currently experiencing from this process, and thereby explain the bug]

[include relevant logs]

## Possible Fix

Consider adding a validation step to DELETE v3/roles/[GUID] as well as DELETE v2/orgs/[GUID]/managers to ensure that you are not deleting the last OrgManager or an org.

## Inform Customers:
https://cloudfoundry.slack.com/archives/C07C04W4Q/p1587989234156500

**Comment by sethboyles** [comment]
Transferring this issue from the CCNG repository as this sort of specific validation/confirmation isn't really possible within the context of individual API requests, aside from blocking the removal of the last OrgManager completely, which isn't something we're likely to enforce.

**Comment by a-b** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket.
