### ISSUE TITLE
Control concurrent instance starts in cf push --strategy rolling

### ISSUE THREAD

**Issue by mayrstefan** [cloudfoundry/cli#2113]
**What's the user value of this feature request?**
Speed up deployment of apps with many instances and/or slow startup times

**Who is the functionality for?**
Improvement of cf push rolling update strategy

**How often will this functionality be used by the user?**
Less often for small fast starting apps with small instance counts, more often for slow starting apps with high instance counts

**Who else is affected by the change?**
Nobody should be affected. The default can stay with one concurrent revision deployment

**Is your feature request related to a problem? Please describe.**
Before cf CLI v7 we used a blue-green deployment which starts all app instances concurrently and swapped routes afterwards. Changing them to cf push --strategy rolling increased deployment time from 2 minutes to 8 minutes which causes the CI/CD system to fail (timeout after 6 minutes). Developers want to stay with the old deployment method instead of migrating to the new one.

**Describe the solution you'd like**
Add a parameter, e.g. --max-inflight, to control how man app instances of the new revision are concurrently started. Default can be 1to keep the current behaviour

**Describe alternatives you've considered**
Use a plugin or a helper script for blue-green deployment

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
