### ISSUE TITLE
Make some commands aware of different running revisions

### ISSUE THREAD

**Issue by mayrstefan** [cloudfoundry/cli#2114]
**What's the user value of this feature request?**
Since we got `cf push --strategy rolling` it is possible to have a state with different app revisions running. We managed to get in this state when we restarted an app that was deploying a new revision. A developer/operator should be able to interact with these revisions.

**Who is the functionality for?**
cf CLI users who would like to resolve a state with two running revisions

**How often will this functionality be used by the user?**
In rare cases when something goes wrong with rolling updates

**Who else is affected by the change?**
we hope nobody needs to

**Is your feature request related to a problem? Please describe.**
See value. Since we adopt  rolling updates we sometimes get into some "undefined" states. We would like top stop/restart/ssh into the app instances but we can not differentiate between the different revisions: there are two instances with index 0: revision 1 and revision 2. Using cf CLI we can not access anything from revision 2. The only way to fix this is to delete the old app and do a fresh cf push. 

**Describe the solution you'd like**
Add a parameter, e.g. `--revision number` to stop/restart-app-instance/ssh. Also display the revision number in `cf app`. We currently use Pivotal Apps Manager to see what revisions are running

**Describe alternatives you've considered**
The only fix we found is to delete and redeploy the app to get into a clean state

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
