### ISSUE TITLE
Link in readme for Version Switching does not go anywhere

### ISSUE THREAD

**Issue by idavidmcdonald** [cloudfoundry/cli#2120]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [ ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
In the readme, the link for `Version Switching` points to https://github.com/cloudfoundry/cli#version-switching. However, there is no anchor that matches this. I'm not quite sure where it should point to (otherwise I would put in a PR).

**Comment by reid47** [comment]
Thanks @idavidmcdonald! Looks like this was fixed in this PR:
https://github.com/cloudfoundry/cli/commit/3c7fba497f614bf6f6b97a9caf3686da52947952

Going to close this now.
