### ISSUE TITLE
Make it easier to remove a user from an org

### ISSUE THREAD

**Issue by robachmann** [cloudfoundry/cli#2121]
We detected some inconsistencies and unexpected behavior in user's role management, namely the `organization_user` role:
- If a user received organization_manager (or auditor) rights, he or she also gets the `organization_user` role assigned. 
- When removed from the organization via `cf unset-org-role`, the `organization_user` role remains assigned to the user.
- The only way to remove this role - and thus have the user completely removed from the organization - is by issueing a `cf curl -X DELETE /v3/roles/:roleid` but a user usually will need to figure out the role's id with another call first. 

There has already been a story to request an easier way to accomplish this (https://github.com/cloudfoundry/cli/issues/781) but the general opinion back then was better to ask CAPI to have it implemented there. 

The simplest solution would be to add `OrganizationUser` to the available roles of `cf unset-org-role` and let developers remove themselves from orgs in a convenient way which is why I submit this issue (and because @reid47 [told me to](https://cloudfoundry.slack.com/archives/C032824SM/p1607979022183400)). 

However, I think there might be some caveats and could introduce undesired side-effects: What happens, if a user tries to unset the role even if he or she still has either an org-role or a space-role in any of the org's spaces assigned? Clearly the CLI should throw an error and decline such a request. Also, should `cf org-users` then contain users without the 'OrgManager', 'BillingManager' and 'OrgAuditor' role but with 'OrganizationUser'?

Since `organization_user` does not serve any practical purpose to the enduser, my preferred implementation would actually be to have CAPI remove the role upon removing the last org-role from a user, because CAPI assigned the role in the first place. If it's really _just_ a marker role, the removal of the role itself could also be worth discussing? Bear in mind that a foundation with ~4000 users in ~3000 spaces results in several tens of thousands `organization_user` role elements - additionally to all the specific `space_manager`, `organization_manager`, ... roles.

That sheer amount of users and roles is also the reason we'd like to clean up unused and unnecessary roles. I've come across (technical, local) users with more than 1000 roles assigned which then needlessly slow down every single of their API calls.

**Comment by gururajsh** [comment]
Thank you for your submission. As mentioned earlier, this is more of a CAPI change than CLI. Please create a CAPI GH Issue.
