### ISSUE TITLE
"Get /login: unsupported protocol scheme "" " when trying to target API endpoint "https://api.dev.cfdev.sh"

### ISSUE THREAD

**Issue by sourzseven** [cloudfoundry/cli#2124]
- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

Provide details on what you were trying to do (and why).
Trying to use PCF Dev for a while now (tried every single version that is available with different pcf dev plugins - on W7, W8, W10, Linux). I made it work  on Windows 10 by using **pcfdev-v1.2.0**-windows.tgz(https://network.pivotal.io/products/pcfdev#/releases/339789) and **CF CLI v.7.20** (https://github.com/cloudfoundry/cli/releases/tag/v7.2.0). 

**Expected behavior**
Trying to target API endpoint: "https://api.dev.cfdev.sh" and receiving the following message:
**Get /login: unsupported protocol scheme ""
FAILED**

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1.  cf login -a https://api.dev.cfdev.sh --skip-ssl-validation
(https://docs.pivotal.io/pcf-dev/usage.html)
**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm)
- version of the CLI you are running
- version of the CC API Release you are on
- 
![image](https://user-images.githubusercontent.com/32751979/103895583-4df65480-50f9-11eb-9985-f9faffd65284.png)

**Comment by reid47** [comment]
Hi @sourzseven , as suggested by that warning, I believe you're using a newer CLI version with an older API version. I believe you should use a v6 CLI with the API version you're targeting.

**Comment by rluan** [comment]
I have almost the same issue with cf7 login, this is my process to solve it, hope it helps.

------

cf7 login -a https://api.sys.np.paas.covapp.io
API endpoint: https://api.sys.np.paas.covapp.io

Get "login-cf.sys.np.paas.covapp.io/login": unsupported protocol scheme ""
FAILED

------
https://github.com/cloudfoundry/capi-release/blob/develop/jobs/cloud_controller_ng/spec

under api job:

  login.protocol:
    description: "http or https"
    default: "https"
  login.url:
    description: "URL of the login server"
  login.enabled:
    default: true
    description: "whether use login as the authorization endpoint or not"

the login.url must be set to:
https://YOUR-LOGIN-URI

why I was wrong as I set it with out "https://"

**Comment by dinissilvauk** [comment]
https:// is what was missing in me, thanks a lot!

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
