### ISSUE TITLE
[Clarification] In the cf cli command for health check, there is no way to configure health-check-timeouts.  Does invocation-timeout and health-check-timeout the same?

### ISSUE THREAD

**Issue by PrajwalGonsalves07** [cloudfoundry/cli#2127]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [ ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ ] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Provide details on what you were trying to do (and why).
There is no way I can change the health-check-timeout for my microservice via cli. There is a parameter called invocation-timeout, but I dont know if they both are the same.

**Comment by reid47** [comment]
Hi @PrajwalGonsalves07, yes, the `--invocation-timeout` flag on `cf set-health-check` corresponds with the `invocation_timeout` field on the CF API health check object: https://v3-apidocs.cloudfoundry.org/version/3.94.0/index.html#the-health-check-object
