### ISSUE TITLE
cf login: cannot delete characters when using git bash

### ISSUE THREAD

**Issue by fkriegl** [cloudfoundry/cli#2128]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce. -- Well, at least my colleagues could reproduce in their terminal 

**Describe the bug and the command you saw an issue with**
Provide details on what you were trying to do (and why).
When I try to do a cf login in git-bash and enter my email, it sometimes happens, that I have a typo in it. I would like to correct this, so I press the "delete" key on my keyboard. But this doesn't work. See screenshot:
![image](https://user-images.githubusercontent.com/46963438/105054719-99eab700-5a72-11eb-89f8-7843199d4fd3.png)

**What happened**
Some [D characters appeared in the terminal, but text was not deleted.

**Expected behavior**
I'm able to correct any typos in my email or password, like it works in CMD.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `cf login` in a git bash terminal
2. Enter an email address and try to delete some characters
3. See the error

**Provide more context**
- platform and shell details: Windows 10 Git Bash (latest version)
- version of the CLI you are running: latest V7
- version of the CC API Release you are on: dunno

**Notes regarding V6 and V7 CLI support:** 
- V6:
  - Minimum supported version of CF Deployment: v7.0.0 (CAPI Release: 1.74.0 (APIs 2.128.0 and 3.63.0))
  - Maximum supported version of CF Deployment: v13.4.0 (CAPI Release: 1.94.0 (APIs 2.149.0 and 3.84.0))
- V7:
  - Minimum supported version of CF Deployment: v13.5.0 (CAPI Release: 1.95.0 (APIs 2.150.0 and 3.85.0))

CF CLI is the only cli tool I'm having this issue with. Other cli tools work fine in git bash.

Thanks for your reply.

**Comment by reid47** [comment]
Hi @fkriegl , thanks for the report. Unfortunately, I believe this is related to a known issue with Git Bash on Windows: https://github.com/cloudfoundry/cli#known-issues

**Comment by fkriegl** [comment]
@reid47 thanks for the quick response. It's not directly listed there, but sounds related (git bash issues). However, does _known issue_ mean, it is on the list of things you consider fixing at some point in time or rather that it won't be fixed at all?

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
