### ISSUE TITLE
cf enable-ssh requires a restart of the app

### ISSUE THREAD

**Issue by stefan0001** [cloudfoundry/cli#2133]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
SSH access does not work after enabling it, because it requires a restart.
As stated by the documentation `enable-ssh` requires a restart of the app to work.
However I would consider this as a bug, as it is an unexpected behaviour.
https://docs.cloudfoundry.org/devguide/deploy-apps/ssh-apps.html#enable-disable-ssh

**What happened**
SSH access does not work after enabling it, because it requires a restart.

**Expected behavior**
SSH access works directly, without a restart of the app.

**Exact Steps To Reproduce**
1. App is deployed with globally set `default_app_ssh_access` to false.
2. Enable ssh with `cf enable-ssh app`
3. `cf ssh app` is not working, a restart of the app is required.

Note: After ssh was enabled + app restarted it works, even the ssh will be disbaled & enabled again

**Provide more context**
`cf version 7.2.0+be4a5ce2b.2020-12-10`

**Comment by beyhan** [comment]
A hint provided by the `cf enable-ssh <app-name>` command will also help a lot here like with `cf bs...` provides. Is this something the CF CLI team will accept? I can provide the pull request.

**Comment by wanddynosios** [comment]
@beyhan I had a similar idea and added https://github.com/cloudfoundry/cli/pull/2314 which adds displays TIP when enabling cf ssh

**Comment by beyhan** [comment]
I think this can be closed now because https://github.com/cloudfoundry/cli/pull/2314 got merged.

**Comment by gururajsh** [comment]
Closing this issue since it's resolved
