### ISSUE TITLE
CF Login returns authentication failure

### ISSUE THREAD

**Issue by AbdullahChougle** [cloudfoundry/cli#2134]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [X ] I reviewed open and closed github issues that may be related to my problem.
- [ X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X ] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
 % cf login -a https://api.cf.company.cf.URL.com

**What happened**
After entering the user and password, I get an error 
{"error":"invalid_grant","error_description":"User authentication failed: INVALID_AUTHORIZATION_HEADER_LENGTH"}

I am the admin of the org and spaces. 

**Expected behavior**
Login to be successful

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `cf login -a https://api.cf.company.cf.URL.com`
2. enter username and password
3. See error mentioned above

**Provide more context**
- Mac Big Sur
- cf version 7.2.0+be4a5ce2b.2020-12-10

**Comment by parthgupta0912** [comment]
@AbdullahChougle Did you find a solution to this issue?

**Comment by AbdullahChougle** [comment]
@parthgupta0912 

I used the option --sso. I then am getting a link on the terminal to generate the token which is used to login to cf

cf login **--sso** -a https://api.cf.company.cf.URL.com

**Comment by krishdubey** [comment]
my cf login is not working
