### ISSUE TITLE
Release binaries for arm64

### ISSUE THREAD

**Issue by odidev** [cloudfoundry/cli#2144]
**Please provide details on the following items. Failure to do so may result in deletion of your feature request.** 

**Who is the functionality for?**
The functionality will be used by arm64 users.

**Who else is affected by the change?**
No, this feature does not cause a breaking change.

**Is your feature request related to a problem? Please describe.**
I was trying to build **nulldriver/cf-cli-resource** image on arm64 platform but it was failing as cli v6 and v7 binaries are not available for arm64.

Do you have any plans to release v6 and v7 binaries for arm64?

**Describe the solution you'd like**
I have build the v6/v7 binaries by following steps-

- Installed the golang 1.13 version.

- Cloned the package and then switched to branch v6/v7.

- Ran command `make build`.

Both v6 and v7 binaries were created.

It will be very helpful if the v6 and v7 binaries are released for arm64.

**Comment by radoslav-tomov** [comment]
Any chance to get it soon ?

**Comment by antjori** [comment]
Any news regarding when the cli6 and cli7 for ARM64 versions will be available? Thank you in advance.

**Comment by gururajsh** [comment]
Thank you for your submission. This issue has been addressed, so closing it.
