### ISSUE TITLE
Cannot access service instance in Cloud Foundry

### ISSUE THREAD

**Issue by sundarvc** [cloudfoundry/cli#2146]
Hi, 
I have a Spring Boot service running in k8s cluster that I am exposing using Service Broker in Cloud Foundry.
Everything runs find and I am able to create a service instance in CF and a service-key . When I list the service-key I get back and uri with IP address , username and password as expected. However, when I try to hit the endpoint from my macOS laptop, I get the following error from curl.

curl: (7) Failed to connect to <cf_ip_address> port 443: Operation timed out

Seems like this issue might be related to https://github.com/cloudfoundry-incubator/cfdev/issues/73 . 

Any ideas ?

Thanks,
Sundar

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
