### ISSUE TITLE
update-user-provided-service with user prompts truncates the value to 4096 bytes

### ISSUE THREAD

**Issue by adborden** [cloudfoundry/cli#2147]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
I'm trying to update an RSA 4096 key (base64 encoded, ~4200 bytes) within our user-provided service. When using `cf uups -p PRIVATE_KEY`, I am prompted for PRIVATE_KEY, I can paste the value (from copy/paste buffer) and the CLI reports the service is updated successfully. However, when I inspect the service with `cf env <app>`, the value is truncated to 4096 bytes.

I'm not sure if this is related to my env/shell but at least I can confirm that my copy/paste buffer has the correct contents. This issue doesn't affect other methods of uups, `-p <file>` and `-p '{"json":"value"}'` work as expected.

**What happened**
CLI returns OK, service is updated with a truncated value (up to 4096 bytes).

**Expected behavior**
The CLI should give an error if it cannot process the input, `-p <file>` and `-p '{"json":"value"}'` do not have this issue.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Create the user-provided service `cf cups test -p '{"FOO": "asdf}'`
2. Bind a service `cf bind-service <app> test`
3. Update the service `cf uups test -p PRIVATE_KEY`, paste a value > 4096 bytes
4. Inspect the service `cf env <app>`

**Provide more context**
- Mac OS X 10.15, iTerm, bash
- cf version 7.2.0+be4a5ce2b.2020-12-10
- API 3.94.0

**Notes regarding V6 and V7 CLI support:** 
- V6:
  - Minimum supported version of CF Deployment: v7.0.0 (CAPI Release: 1.74.0 (APIs 2.128.0 and 3.63.0))
  - Maximum supported version of CF Deployment: v13.4.0 (CAPI Release: 1.94.0 (APIs 2.149.0 and 3.84.0))
- V7:
  - Minimum supported version of CF Deployment: v13.5.0 (CAPI Release: 1.95.0 (APIs 2.150.0 and 3.85.0))

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
