### ISSUE TITLE
cf7 cli does not list route-services with cf routes command

### ISSUE THREAD

**Issue by mwdb** [cloudfoundry/cli#2149]
**Please fill out the issue checklist below and provide ALL the requested information.**

I understand from https://docs.pivotal.io/application-service/2-8/cf-cli/v7.html that with cf7 the cf routes command no longer 
lists the route services which are bound to a service.

When using router services, what is the recommendation to list the route services and their mappings? Using v6 I could get the information using cf routes. What is the recommendation for v7?

- [x ] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
cf routes in v7 no longer lists the used route services.
v6 did return that information
**What happened**
Called cf routes and did not find information on the used route services

**Expected behavior**
List the route service in cf routes

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
Call cf routes for a route that has a route service bound.

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm)
- version of the CLI you are running
- version of the CC API Release you are on

**Notes regarding V6 and V7 CLI support:** 
- V6:
  - Minimum supported version of CF Deployment: v7.0.0 (CAPI Release: 1.74.0 (APIs 2.128.0 and 3.63.0))
  - Maximum supported version of CF Deployment: v13.4.0 (CAPI Release: 1.94.0 (APIs 2.149.0 and 3.84.0))
- V7:
  - Minimum supported version of CF Deployment: v13.5.0 (CAPI Release: 1.95.0 (APIs 2.150.0 and 3.85.0))

**Comment by blgm** [comment]
This is mentioned in the "Table of Differences" in the CLI v7 upgrade guide: https://docs.cloudfoundry.org/cf-cli/v7.html

The column is planned to be added back in V8 and the code for this is already in the `master` branch. The complexity with porting the change to V7 is that it uses an API endpoint that is not available in all CF versions that v7 supports.

There is some more context in this story: https://www.pivotaltracker.com/story/show/166713294

I think the main ways forward would be to:
- release V8
- attempt to fix for V7

This would be a decision for the CLI team based on how advanced the plans are for V8

**Comment by mwdb** [comment]
Can you recommend a workaround until v8 is available?

**Comment by blgm** [comment]
The v6 CLI should still work. I've seen people with CF CLI v6 installed as `cf6` so they can switch easily between versions. I realise it's far from ideal, but it would work without having to wait for a fix.

**Comment by gururajsh** [comment]
If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
