### ISSUE TITLE
cf push in v7 is case sensitive on app names

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/cli#2152]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [X] I reviewed open and closed github issues that may be related to my problem.
- [X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [X] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Push an app with a mixed case name:
`cf push CamelCaseTest -b staticfile_buildpack`

Immediately try to update the same app with a different case:
`cf push camelcasetest -b staticfile_buildpack`

**What happened**
Results in an error from the CLI:

`App is invalid. Ensure it exists and you have access to it.`
`FAILED`

Error from the API:

`{`
`  "errors": [`
`    {`
`      "code": 10008,`
`      "detail": "App is invalid. Ensure it exists and you have access to it.",`
`      "title": "CF-UnprocessableEntity"`
`    }`
`  ]`
`}`

**Expected behavior**
CF commands should execute regardless of case, and it does work correctly for commands like cf delete.

**Provide more context**
- Same error occurs on both Linux and Windows
- CLI 7.2.0+be4a5ce2b.2020-12-10
- CC API 3.91.0

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
