### ISSUE TITLE
cf set-health-check output misleading

### ISSUE THREAD

**Issue by PaulKlumpp** [cloudfoundry/cli#2158]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [ x] I reviewed open and closed github issues that may be related to my problem. (did not find any matching)
- [ x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x ] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**

We never expected an app restart once we did "cf set-health-check" as the output was strongly misleading.

```
cf set-health-check $appname http --endpoint $endpoint --invocation-timeout 3600
Updating health check type for app lala-PROD-blue process web in org ABC / space abc-prod as abc_service...
OK
TIP: An app restart is required for the change to take effect.
```

But right after the command, the app restarted.

**Expected behavior**
As the text is not matching to behavior:
- Either the app should not restart after set-health-check
- Or, the app should restart but the text output should tell exactly something like: "NOTICE: The app will be restarted now for the change to take effect."

**Exact Steps To Reproduce**
See above.

**Provide more context**
```
cf -v
cf version 7.2.0+be4a5ce2b.2020-12-10
```

- Mac OS X 11.2.3
- homebrew installed cloudfoundry 7.2.0+be4a5ce2b.2020-12-10
- version of the CC API Release you are on: API version:    3.85.0

**Notes regarding V6 and V7 CLI support:** 
- V6:
  - Minimum supported version of CF Deployment: v7.0.0 (CAPI Release: 1.74.0 (APIs 2.128.0 and 3.63.0))
  - Maximum supported version of CF Deployment: v13.4.0 (CAPI Release: 1.94.0 (APIs 2.149.0 and 3.84.0))
- V7:
  - Minimum supported version of CF Deployment: v13.5.0 (CAPI Release: 1.95.0 (APIs 2.150.0 and 3.85.0))

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
