### ISSUE TITLE
Issue with cf login in Mac OS

### ISSUE THREAD

**Issue by ivyxiao123** [cloudfoundry/cli#2173]
Hello,

Getting issue with 7.2.0+be4a5ce2b.2020-12-10, the command cf login is not working

Command
Execute cf login 

What occurred

> cf login -a https://test.com -u xxxx -p xxxx -o xxxx -s xxxx --skip-ssl-validation                                                                                                                                                                                            
> API endpoint: https://test.com Invalid JSON content from server: invalid character '<' looking for beginning of value
> FAILED
>>> 

What you expected to occur
Able to login

CLI Version
Command is broken on: 7.2.0+be4a5ce2b.2020-12-10

Platform & Shell Details
Platform: Mac OS mojave 10.14.6 , iTerm Version 2.9.5 (421.2)

Any other relevant information
Found [this](https://github.com/cloudfoundry/cli/issues/1342) similar issue, and someone mentioned removing `config.json` would fix the issue, but I'm still having same issue.

**Comment by JenGoldstrich** [comment]
Hey @ivyxiao123 thanks for submitting this issue,

Can we get a bit more information about the foundation you're using?

What version of the CF API are you using so we can see if we can replicate this (output of `cf api` command will tell you this)

Thanks!
Jenna

**Comment by JenGoldstrich** [comment]
Hey @ivyxiao123 just bumping this are you still experiencing this issue?

**Comment by ivyxiao123** [comment]
> Hey @ivyxiao123 just bumping this are you still experiencing this issue?

Hi thanks for checking up again and I'm no longer having the issue, not exactly sure what happened, but I'm all good now. Thanks again!
