### ISSUE TITLE
Create official docker images for v6/v7/edge v8

### ISSUE THREAD

**Issue by JenGoldstrich** [cloudfoundry/cli#2174]
Based on https://github.com/cloudfoundry/cli/issues/1578 and several other requests from users there is clearly demand to create an official CLI docker image.

We want to create separate images on the v6/v7/master branches for v6/v7/v8 respectively, these images should use Alpine as it is a standard for small footprint images, and should pull in the latest released version of the cf CLI (or the edge version for v8).

We also will want a pipeline which runs with v6/v7/v8 that can test the dockerfile for each commit, and just run cf -v to make sure the cf CLI is built correctly into the image.

**Comment by JenGoldstrich** [comment]
https://hub.docker.com/r/cfcli/cf-cli/tags?page=1&ordering=last_updated we now publish v6 and v7 latest, leaving this issue open until we release v8.

Kudos to @jdgonzaleza and @dominicrobertsc !

**Comment by vchrisb** [comment]
This is great! May I suggest adding additional tags to the latest image?
e.g.
7 / 7.2.0 to the latest cli 7 image, in this case 7.2.0
This makes it easier to use the lates cli version of a specific major version.
`docker pull cfcli/cf-cli:7`

**Comment by JenGoldstrich** [comment]
Hey @vchrisb, docker doesn't seem to play too nicely with the concept of multiple tags on a single dockerhub push unless we're doing this wrong, its definitely something we could manually add in the future, to maintain also a tagged v7//v8 latest release tag to make it easier to find.

**Comment by vchrisb** [comment]
not sure were the ci configuration is, but if it is a script, you can simply tag the build image and push it with the additional tag.
something along the lines
```
VERSION="7.2.0"
docker build -t cfcli/cf-cli:${VERSION} .
docker push cfcli/cf-cli:${VERSION}
docker tag cfcli/cf-cli:${VERSION} cfcli/cf-cli:v7
docker push cfcli/cf-cli:7
docker tag cfcli/cf-cli:${VERSION} cfcli/cf-cli:latest
docker push cfcli/cf-cli:latest
```

**Comment by jdgonzaleza** [comment]
Hey @vchrisb, thanks for the feedback! currently I just came up for a solution for the suggestion you made. I just want to be clear about something: We would like to tag the latest v7 version as `7`, `7.x.x` and `latest` ?
If that's the case, I think we can make this possible in our ci implementation 😄

**Comment by jdgonzaleza** [comment]
Just uploaded the new tags. Now we have the following docker images:
* 7
* 7.2.0
* 6
* 6.53.0
* latest
The `latest` tag will have the latest version of the latest major release. 
`6` and `7` will have the latest release for v6 and v7 respectively.

**Comment by jdgonzaleza** [comment]
Hello everyone! We just migrated the images into the [cloudfoundry official repository](https://hub.docker.com/r/cloudfoundry/cli/tags?page=1&ordering=last_updated). 
From now on, all the official docker images for the cli could be pulled from `cloudfoundry/cli:${version}`
