### ISSUE TITLE
Unable to install CF CLI on MacOS using PKG type

### ISSUE THREAD

**Issue by GeneralNitin** [cloudfoundry/cli#2184]
While trying to open the file, it gives an error stating:

```
“cf7-cli-installer_7.2.0_osx.pkg” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.
```

**Comment by JenGoldstrich** [comment]
Hello @GeneralNitin 

I believe this might be an existing issue but I am not 100% sure, but here is the work around.

1. Try to open the package again, and click cancel.
2. Open Security & Privacy inside of System Preferences
3. Click the Open Anyway button next to the "cf7-cli-installer-----" text towards the bottom.
4. Click Open when the warning appears again, this time it will have a button to do that.

Let me follow up with you on if this is an existing issue or not, I would like to add it to the Known Issues column of the readme if that is the case

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
