### ISSUE TITLE
Warning: error tailing logs Get /api/v1/info: unsupported protocol scheme ""

### ISSUE THREAD

**Issue by Rahulvks** [cloudfoundry/cli#2198]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [ ] I reviewed open and closed github issues that may be related to my problem.
- [ ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ *] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
ibmcloud cf push 
getting below error while deploying  the node'js code in the cloud foundary 

```
Starting app dedcrqaclient in org D / space DED_Con_Rig_UAT as dsgs@ds.ae...
Warning: error tailing logs
Get /api/v1/info: unsupported protocol scheme ""
Warning: error tailing logs
Get /api/v1/info: unsupported protocol scheme ""
Warning: error tailing logs
Get /api/v1/info: unsupported protocol scheme ""
Warning: error tailing logs
Get /api/v1/info: unsupported protocol scheme ""
Warning: error tailing logs
Get /api/v1/info: unsupported protocol scheme ""

FAILED
Error restarting application: BuildpackCompileFailed
```

**What happened**
above error is from the deployment 

**Expected behavior**
Successful deployment and restart the service

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `cf ...`
2. Bind a service `cf bind-service`
3. See error

**Provide more context**
- platform and shell details mac -11.4

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
