### ISSUE TITLE
Deploy target when not logged in should return clearer message

### ISSUE THREAD

**Issue by ianquigley-sap** [cloudfoundry/cli#2203]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Trying to deploy to Cloud Foundry using the CF cli tools

**What happened**
I wasn't logged into CF, and got the following error message:

```
FAILED
Could not get access token: not a compact JWS
npm ERR! code ELIFECYCLE
```

**Expected behavior**
I would have expected the message to be a little clearer and advise me that I need to login to CF in order to deploy.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Ensure you are logged out of CF
2. Attempt to deploy a valid CF archive.
3. You are not logged in, the following error is returned:

```
FAILED
Could not get access token: not a compact JWS
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mta-project@0.0.1 deploy: `cf deploy mta_archives/archive.mtar --retries 1`
npm ERR! Exit status 1
npm ERR! 
```

**Provide more context**
- MacOS 11.5.2
- CF CLI version 7.2.0+be4a5ce2b.2020-12-10

**Notes regarding V6 and V7 CLI support:** 
- V6:
  - Minimum supported version of CF Deployment: v7.0.0 (CAPI Release: 1.74.0 (APIs 2.128.0 and 3.63.0))
  - Maximum supported version of CF Deployment: v13.4.0 (CAPI Release: 1.94.0 (APIs 2.149.0 and 3.84.0))
- V7:
  - Minimum supported version of CF Deployment: v13.5.0 (CAPI Release: 1.95.0 (APIs 2.150.0 and 3.85.0))

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
