### ISSUE TITLE
[cf7 cli issue with host name format ] cf7 push fail if app name contains .  [dot] ..but old cli version it is working properly

### ISSUE THREAD

**Issue by parasuram-tanguturu** [cloudfoundry/cli#2204]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
unable to push app if appname contains .[dot].
'CF_TRACE=1': Host format is invalid.

**What happened**
cf7 push is failing 'For application 'v1.testapiname': No domains exist for route v1.testapiname-appreciative-hyrax-dt.<domain>'
but cf push which uses :cf version 6.40.1+85d04488a.2018-10-31 is working fine .
**Expected behavior**
cf7 push should work as cf push

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
(install cf cli 6th version as well 7th version)
1. Run 'cf7 push' which will use cli 7 version
2. see error
3. run 'cf push' which uses cli 6th version .it works

For application 'CF_TRACE=1': Host format is invalid.
FAILED

used cli versions:\
windows
**cli 6th: cf version 6.40.1+85d04488a.2018-10-31
cli 7th : cf7 version 7.2.0+be4a5ce2b.2020-12-10**

**Comment by gururajsh** [comment]
Thank you @parasuram-tanguturu for bringing this to our attention. The issue has been added to our backlog for further investigation.

**Comment by gururajsh** [comment]
Thank you for your submission. 
Starting v8 dot is no longer a valid character for app names.
If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
