### ISSUE TITLE
CF CLI RPM Installation package not available for SUSE Linux

### ISSUE THREAD

**Issue by ManjunathSAP** [cloudfoundry/cli#2209]
Hello Members,
We are trying to install the CF CLI Package on our SUSE Linux Servers(SLES 15.1) and see that there are no direct RPM Packages available for SUSE Linux for CF CLI Installation.
We cannot make use of the compressed binaries option (https://github.com/cloudfoundry/cli/blob/master/doc/installation-instructions/installation-instructions-v7.md#installers-and-compressed-binaries) as this is not a standard and not permitted from a security standpoint.
Also since there are no other OS Flavors used, we cannot deploy other Linux flavors as well

Hence requesting you to provide the direct RPM Packages for CF CLI Installation similar to how it is made available for Debian/Ubuntu or fedora based Operating systems.

Could you kindly check this request and respond please ?

Thanks,
-Manju

**Comment by gururajsh** [comment]
Thank you for your submission. Since we have linux distribution for CLI available, closing this issue.
