### ISSUE TITLE
Add Docker template to generate-release-notes script

### ISSUE THREAD

**Issue by a-b** [cloudfoundry/cli#2214]
Starting CLI v8.0.0 we added Docker distribution.

```cucumber
Feature: Docker section in release notes
As cf cli user
I want to see a docker section with prepopulated docker command  in the release notes
So I can easily access docker image with new cf
```

# Resources
- Release notes script: https://github.com/cloudfoundry/cli/blob/19278c3aed08aa3ce867c02467be7e453c5c1c56/bin/generate-release-notes#L22
- [Example](https://github.com/cloudfoundry/cli/releases/tag/v8.0.0) of the release with a Docker section

**Comment by gururajsh** [comment]
Closing since its complete
