### ISSUE TITLE
CF CLI not available for ARM64

### ISSUE THREAD

**Issue by i353296** [cloudfoundry/cli#2215]
Hello,

I have a MAC book PRO with the M1 Chip
It has the ARM64 architecture.

I want to install cf cli of any version for my work, but it is not available for this architecture.

Can you suggest an alternative or mitigation for this issue.
<img width="565" alt="Screenshot 2021-09-29 at 1 29 01 PM" src="https://user-images.githubusercontent.com/42734167/135227314-747b9e67-05fc-4e0e-8bde-01501f3b8a20.png">

**Comment by a-b** [comment]
Closing as duplicate of https://github.com/cloudfoundry/cli/issues/2131

**Comment by stuaxo** [comment]
@a-b that other ticket is closed, as far as I can see you only build arm64 builds for MacOS, but don't provide them for Linux ?
