### ISSUE TITLE
'cf7 apps' builds too long GET v3/processes requests

### ISSUE THREAD

**Issue by cloudmarius** [cloudfoundry/cli#2216]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Given a space with 200+ applications
When I execute `cf7 apps`
Then cf7 will execute a `GET v3/processes?app_guids=looooooong_list_of_apps_guids_goes_here` request
And this request can fail with `HTTP/1.1 414 Request-URI Too Long` when it reaches nginx

**Expected behavior**
The cli should query in smaller batches to avoid such failures

**Exact Steps To Reproduce**
1. create space with 200 apps
2. Run `CF_TRACE=true cf7 apps`
3. See error

**Provide more context**
- cf7 version 7.3.0+645c3ce6a.2021-08-16
- CAPI 3.102.0

**Comment by marius-munteanu-sc** [comment]
Hi, any feedback on this one?

**Comment by gururajsh** [comment]
Thank you @cloudmarius for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket with the necessary information mentioned in our issue template
