### ISSUE TITLE
Help for 'cf push' is misleading: app name is not required

### ISSUE THREAD

**Issue by mhaas** [cloudfoundry/cli#2217]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] ~I attempted to run the command with `CF_TRACE=1` to help debug the issue.~
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**

The output of `cf push --help` indicates that APP_NAME is a required argument:

```
$ cf --version
cf version 8.0.0+e8d41cf8e.2021-09-16
$ cf push --help
NAME:
   push - Push a new app or sync changes to an existing app

USAGE:
   cf push APP_NAME [-b BUILDPACK_NAME]
   [-c COMMAND] [-f MANIFEST_PATH | --no-manifest] [--no-start] [--no-wait] [-i NUM_INSTANCES]
   [-k DISK] [-m MEMORY] [-p PATH] [-s STACK] [-t HEALTH_TIMEOUT] [--task TASK]
   [-u (process | port | http)] [--no-route | --random-route]
   [--var KEY=VALUE] [--vars-file VARS_FILE_PATH]...
 
   cf push APP_NAME --docker-image [REGISTRY_HOST:PORT/]IMAGE[:TAG] [--docker-username USERNAME]
   [-c COMMAND] [-f MANIFEST_PATH | --no-manifest] [--no-start] [--no-wait] [-i NUM_INSTANCES]
   [-k DISK] [-m MEMORY] [-p PATH] [-s STACK] [-t HEALTH_TIMEOUT] [--task TASK]
   [-u (process | port | http)] [--no-route | --random-route ]
   [--var KEY=VALUE] [--vars-file VARS_FILE_PATH]...
```
This is confusing: I coded my automation around the fact that I have to give the APP_NAME instead of it being taken from the manifest.

I then tried to leave out the `APP_NAME` while pushing my manifest and it worked perfectly.

I would propose to update the help to indicate that `APP_NAME` is not mandatory.

**Provide more context**
```
cf version 8.0.0+e8d41cf8e.2021-09-16
```
```
$ cf target
API endpoint:   https://api.cf.sap.hana.ondemand.com
API version:    3.103.0
```

**Comment by gururajsh** [comment]
Thank you @mhaas for your submission. `APP_NAME` is mandatory when using default settings for `cf push` as mentioned [here](https://docs.cloudfoundry.org/devguide/deploy-apps/deploy-app.html). Only while using manifest file, which is an optional flag, the app name is taken from manifest if one is not provided.
