### ISSUE TITLE
How to pass parameters to push and run Docker images

### ISSUE THREAD

**Issue by viju2008** [cloudfoundry/cli#2223]
Hi,

I went through the  documentation. However i could not find how to pass  to pass parameters to run Dockee image like -p or
-e.

Is it possible to use them  along with CF PUSH ?

**Comment by gururajsh** [comment]
Hello,

Docker images can be pushed using the cf push command. Please refer [this](https://cli.cloudfoundry.org/en-US/v6/push.html) for details.

**Comment by viju2008** [comment]
> Hello,
> 
> Docker images can be pushed using the cf push command. Please refer [this](https://cli.cloudfoundry.org/en-US/v6/push.html) for details.

However i am unable to get clarity on how to pass arguments

**Comment by acuppoor** [comment]
Hello @viju2008

Have you been able to figure out how to pass parameters with cf push?

I want to create a redis container with some params :
Docker - d redis - p 6379:6379 - - requirepass mysecurepwd

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket with the necessary information mentioned in our issue template
