### ISSUE TITLE
CF CLI accessing database service metadata

### ISSUE THREAD

**Issue by nesanmano** [cloudfoundry/cli#2224]
**Please provide details on the following items. Failure to do so may result in deletion of your feature request.** 
I have CF (PaaS) set up and running. I have an API deployed along with the dependent services such as a9s database and log drain.

I am trying to develop a shell script to access the PaaS and retrieve information regarding the database service. I would like to know if back up has been made and so on.

Using Cmder, I am able to create an SSH tunnel but from there I not even able to access my database using psql.

I am trying to access my DB service status.

I have successfully executed the below commands

cf login

cf ssh

// I am not getting to access my DB via CMDER (I will try installing psql on my local station and see if it helps)

**Comment by gururajsh** [comment]
Thank you @nesanmano for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket with the necessary information mentioned in our issue template
