### ISSUE TITLE
download-droplet not working in v8 with S3 object store

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/cli#2225]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [X] I reviewed open and closed github issues that may be related to my problem.
- [X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [X] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Due to the same root cause from https://github.com/cloudfoundry/cli/issues/1165, the download-droplet command is not working in the v8 version of the CLI.

**What happened**
Using the download-droplet command using CLI v8 throws an error due to the Content-Type header included in the request.

**Expected behavior**
The download-droplet command should work to download the droplet from the object store.

**Exact Steps To Reproduce**
1. Run `cf8 -v download-droplet appname`
2. Receive error from S3: `The request signature we calculated does not match the signature you provided`
3. Run `cf7 -v download-droplet appname`
4. Droplet is downloaded successfully

**Provide more context**
- Windows 10
- CLI v8.0.0

Relevant trace output:

v7.3.0:

`REQUEST: [2021-10-28T14:56:11-07:00]`
`GET /v3/droplets/7514513a-e8b7-459c-a0f6-ad63b178f269/download HTTP/1.1`
`Host: api.domain.com`
`Accept: application/json`
`Authorization: [PRIVATE DATA HIDDEN]`
`User-Agent: cf7.exe/7.3.0+645c3ce6a.2021-08-16 (go1.16.6; amd64 windows)`

v8.0.0:

`REQUEST: [2021-10-28T14:58:20-07:00]`
`GET /v3/droplets/7514513a-e8b7-459c-a0f6-ad63b178f269/download HTTP/1.1`
`Host: api.domain.com`
`Accept: application/json`
`Authorization: [PRIVATE DATA HIDDEN]`
`Content-Type: application/json`
`User-Agent: cf8.exe/8.0.0+e8d41cf8e.2021-09-16 (go1.16.6; amd64 windows)`

The added `Content-Type` header is causing the issue in v8.

**Comment by kirkfox** [comment]
Is this on the roadmap?

**Comment by Samze** [comment]
@gururajsh should https://github.com/cloudfoundry/cli/pull/2976 have resolved this?

**Comment by gururajsh** [comment]
Yes, it should be resolved now
