### ISSUE TITLE
CF8 windows installer creates symbolic link for cf7.exe

### ISSUE THREAD

**Issue by ndlu1234** [cloudfoundry/cli#2227]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x]  I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
After installed cf8 I wanted to run a command to see the installed version using cf -v. 

**What happened**
I see the error:
The system cannot find the file C:\Program Files\Cloud Foundry\cf.exe.

If I go to Cloud Foundry folder and run 'dir cf.exe', I can see that the symbolic link cf.exe is pointing to non-existing cf7.exe instead of cf8.exe:
C:\Program Files\Cloud Foundry>dir cf.exe
 Volume in drive C has no label.
 Volume Serial Number is 761B-BA9C

 Directory of C:\Program Files\Cloud Foundry

07/11/2021  09:45 pm    <SYMLINK>      cf.exe [C:\Program Files\Cloud Foundry\cf7.exe]
               1 File(s)              0 bytes

**Expected behavior**
1. When I run `cf -v`, I expect the installed version of cf to be displayed, eg. cf8 version 8.0.0+e8d41cf8e.2021-09-16
2. When I run `dir cf.exe` from Cloud Foundry folder, I should see the symbolic link cf.exe is pointing to cf8.exe.

**Exact Steps To Reproduce**
1. Run `cf -v`
2. See error
3. Go to Cloud Foundry folder
4. Run `dir cf.exe` 
5. See Symbolic link target

**Provide more context**
- Windows 10 command prompt
- CF CLI 8

**Comment by RyuRavi** [comment]
The shortcut created as CF.exe is still pointing to CF7.exe  I had to rename the CF8.exe to CF7.exe for CF command to work

**Comment by jonathan-barner** [comment]
Happened to me today as well, exact same issue.

**Comment by JD-CSTx** [comment]
Problem still exists with Installer from cf8-cli-installer_8.1.0_winx64.zip.

**Comment by pivotalgeorge** [comment]
Hi there!

Looking at this after the change of our release process to GitHub Actions, this issue should be resolvede. here are the relevant portions of the InnoSetup config:
- [this line](https://github.com/cloudfoundry/cli/blob/b604dbcd60e926d41d9be76bb587155eb2c3a4a2/.github/win/windows-installer-v7-x64.iss#L26) from the [v7 x64 innosetup config](https://github.com/cloudfoundry/cli/blob/v7/.github/win/windows-installer-v7-x64.iss)
- [this line](https://github.com/cloudfoundry/cli/blob/2855a1b812cd60f8e7e0f8eab9dbb3d277d83903/.github/win/windows-installer-v8-x64.iss#L26) from the [v8 x64 innosetup config](https://github.com/cloudfoundry/cli/blob/v8/.github/win/windows-installer-v8-x64.iss)

We also just manually tested on a Windows VM and the installation appears to result in a `cf` link in Program Files pointing at `cf8.exe`

Could someone confirm that `v8.3.0` works for them? If so, we'll go ahead and mark this resolved.

**Comment by jonathan-barner** [comment]
Confirmed on `cf8-cli-installer_8.4.0_winx64.zip` - that's the version that's currently linked.

**Comment by ccjaimes** [comment]
Given that this has been patched in `v8.3.0` we will proceed to close this issue. Feel free to reopen in any case needed.

**Comment by laura-la** [comment]
I just had a similar issue with cf8-cli-installer_8.5.0_winx64.zip, where cf8 worked fine but cf was not recognized as a command.

In my case, no cf.exe link was created in the Cloud Foundry folder at all. My workaround was to create the link myself in the Cloud Foundry folder:

`cf8-cli-installer_8.5.0_winx64.zip`
