### ISSUE TITLE
Nginx with Docker not starting on cloud foundry

### ISSUE THREAD

**Issue by tvelingkar** [cloudfoundry/cli#2239]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
I am trying to deploy docker image with Nginx on cloudfoundry.
The port exposed in Dockerfile is 8080 using expose directive and same is used in nginx.conf

**What happened**
App is not starting and throwing below error

`Instance never healthy after 3m1.002s: Failed to make HTTP request to '/health' on port 80: connection refused`

**Expected behavior**
App should start normally and should be available on URL

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Build docker image with Nginx exposed on port 8080
2. Deploy image to cf using docker
3. See error

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm) - Docker
- version of the CLI you are running - cf7-cli
- version of the CC API Release you are on

**Notes regarding V6 and V7 CLI support:** 
- V6:
  - Minimum supported version of CF Deployment: v7.0.0 (CAPI Release: 1.74.0 (APIs 2.128.0 and 3.63.0))
  - Maximum supported version of CF Deployment: v13.4.0 (CAPI Release: 1.94.0 (APIs 2.149.0 and 3.84.0))
- V7:
  - Minimum supported version of CF Deployment: v13.5.0 (CAPI Release: 1.95.0 (APIs 2.150.0 and 3.85.0))

**Comment by gururajsh** [comment]
Thank you @tvelingkar for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket with the necessary information mentioned(including the exact commands to be run) in our issue template.
