### ISSUE TITLE
fatal error: runtime: bsdthread_register error

### ISSUE THREAD

**Issue by m4rc3iro** [cloudfoundry/cli#2240]
**cf --version**
cf version 7.4.0+e55633fed.2021-11-15

**CLI Version**
7.4.0, although this issue happens as well in latest v8

**Error**
Error happens when running `cf enable-debug` or `cf set-logging-level` commands:
```
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x142e183, 0x21)
	/xmake/j/prod-build10310/w/final-assembly/final-assembly-xs-cf-cli-plugin-OD-linuxx86_64_indirectshipment/gen/go-workspace/go-install-dir/go/src/runtime/panic.go:596 +0x95 fp=0x7ff7bfeff740 sp=0x7ff7bfeff720
runtime.goenvs()
	/xmake/j/prod-build10310/w/final-assembly/final-assembly-xs-cf-cli-plugin-OD-linuxx86_64_indirectshipment/gen/go-workspace/go-install-dir/go/src/runtime/os_darwin.go:108 +0xa0 fp=0x7ff7bfeff770 sp=0x7ff7bfeff740
runtime.schedinit()
	/xmake/j/prod-build10310/w/final-assembly/final-assembly-xs-cf-cli-plugin-OD-linuxx86_64_indirectshipment/gen/go-workspace/go-install-dir/go/src/runtime/proc.go:486 +0xa1 fp=0x7ff7bfeff7b0 sp=0x7ff7bfeff770
runtime.rt0_go(0x7ff7bfeff7e8, 0x6, 0x7ff7bfeff7e8, 0x0, 0x1000000, 0x6, 0x7ff7bfeff9c8, 0x7ff7bfeff9f8, 0x7ff7bfeff9fe, 0x7ff7bfeffa10, ...)
	/xmake/j/prod-build10310/w/final-assembly/final-assembly-xs-cf-cli-plugin-OD-linuxx86_64_indirectshipment/gen/go-workspace/go-install-dir/go/src/runtime/asm_amd64.s:158 +0x183 fp=0x7ff7bfeff7b8 sp=0x7ff7bfeff7b0
```

**Platform Details**
e.g. Mac OS X 12.0.1

**Shell**
iTerm

**Comment by selvaganapathyt** [comment]
I am facing the same issue when I run cf service-logs command. I am running on MAC OS Monterey 12.6

**Comment by selvaganapathyt** [comment]
unistalling and re-installing plugin( in my case, its the service-logs plugin)   did the trick for me.

**Comment by gururajsh** [comment]
Thank you @selvaganapathyt for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket with the necessary information mentioned in our issue template.Thank you for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket with the necessary information mentioned in our issue template.
