### ISSUE TITLE
cf7 cannot install any plugins

### ISSUE THREAD

**Issue by norman-abramovitz** [cloudfoundry/cli#2241]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [ x] I reviewed open and closed github issues that may be related to my problem.
- [ x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x ] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Trying to install plugins on a docker image Linux image.  The CF command is able to run and list apps.

**What happened**
Docker image built with 
FROM ubuntu:latest

The CF7 command downloaded the plugin and then crashed trying to start the plugin.

	Command
		cf7 install-plugin -r CF-Community top

		CLI Version
		7.4.0+e55633fed.2021-11-15

		Error
		assignment to entry in nil map

		Stack Trace
			goroutine 1 [running]:
	code.cloudfoundry.org/cli/util/panichandler.HandlePanic()
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/panichandler/handler.go:19 +0x85
	panic(0xfb6f00, 0x125f7a0)
		/usr/local/go/src/runtime/panic.go:965 +0x1b9
	code.cloudfoundry.org/cli/util/configv3.(*Config).AddPlugin(0xc00022e300, 0xc0004b2850, 0x3, 0xc0004304b0, 0x15, 0x0, 0x9, 0x5, 0x0, 0x0, ...)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/configv3/plugins_config.go:91 +0x56
	code.cloudfoundry.org/cli/actor/pluginaction.Actor.InstallPluginFromPath(0x7f1a33b8e9c0, 0xc00022e300, 0x1280b08, 0xc00004a0c0, 0xc00080e2d0, 0x29, 0xc0004b2850, 0x3, 0xc0004304b0, 0x15, ...)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/actor/pluginaction/install.go:181 +0x1b5
	code.cloudfoundry.org/cli/command/common.InstallPluginCommand.installPlugin(0x7ffecfc7b927, 0x3, 0x0, 0x7ffecfc7b91a, 0xc, 0x0, 0x0, 0x0, 0x0, 0x129b438, ...)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/command/common/install_plugin_command.go:172 +0x19c
	code.cloudfoundry.org/cli/command/common.InstallPluginCommand.Execute(0x7ffecfc7b927, 0x3, 0x0, 0x7ffecfc7b91a, 0xc, 0x0, 0x0, 0x0, 0x0, 0x129b438, ...)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/command/common/install_plugin_command.go:164 +0xb98
	code.cloudfoundry.org/cli/util/command_parser.(*CommandParser).executionWrapper(0xc00054e010, 0x7f1a33b8e978, 0x191ee50, 0xc0001ee000, 0x0, 0x4, 0x0, 0x0)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/command_parser/command_parser.go:93 +0x24e
	github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000216000, 0xc0000c8010, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
		/tmp/build/80754af9/gopath/pkg/mod/github.com/jessevdk/go-flags@v1.4.1-0.20181221193153-c0795c8afcf4/parser.go:331 +0x85d
	code.cloudfoundry.org/cli/util/command_parser.(*CommandParser).parse(0xc00054e010, 0xc0000c8010, 0x4, 0x4, 0xfbbe80, 0x191c3c0, 0x7f1a3422afff, 0x7f1a33ecbb30, 0x7f1a33ecbb30)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/command_parser/command_parser.go:221 +0xe5
	code.cloudfoundry.org/cli/util/command_parser.(*CommandParser).ParseCommandFromArgs(...)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/command_parser/command_parser.go:57
	main.main()
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/main.go:40 +0x19e

	goroutine 604 [IO wait]:
	internal/poll.runtime_pollWait(0x7f1a33ed3c00, 0x72, 0xffffffffffffffff)
		/usr/local/go/src/runtime/netpoll.go:222 +0x55
	internal/poll.(*pollDesc).wait(0xc000806298, 0x72, 0xfb00, 0xfb64, 0xffffffffffffffff)
		/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
	internal/poll.(*pollDesc).waitRead(...)
		/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
	internal/poll.(*FD).Read(0xc000806280, 0xc0006a2000, 0xfb64, 0xfb64, 0x0, 0x0, 0x0)
		/usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
	net.(*netFD).Read(0xc000806280, 0xc0006a2000, 0xfb64, 0xfb64, 0x1295, 0xc000656000, 0x5)
		/usr/local/go/src/net/fd_posix.go:55 +0x4f
	net.(*conn).Read(0xc000474478, 0xc0006a2000, 0xfb64, 0xfb64, 0x0, 0x0, 0x0)
		/usr/local/go/src/net/net.go:183 +0x91
	crypto/tls.(*atLeastReader).Read(0xc00035c630, 0xc0006a2000, 0xfb64, 0xfb64, 0xc0002419f8, 0xc000088800, 0x0)
		/usr/local/go/src/crypto/tls/conn.go:776 +0x63
	bytes.(*Buffer).ReadFrom(0xc0000aecf8, 0x1273520, 0xc00035c630, 0x40b6a5, 0xfd1020, 0x10e8b00)
		/usr/local/go/src/bytes/buffer.go:204 +0xbe
	crypto/tls.(*Conn).readFromUntil(0xc0000aea80, 0x12742c0, 0xc000474478, 0x5, 0xc000474478, 0x10000001e)
		/usr/local/go/src/crypto/tls/conn.go:798 +0xf3
	crypto/tls.(*Conn).readRecordOrCCS(0xc0000aea80, 0x0, 0x0, 0x438ffc)
		/usr/local/go/src/crypto/tls/conn.go:605 +0x115
	crypto/tls.(*Conn).readRecord(...)
		/usr/local/go/src/crypto/tls/conn.go:573
	crypto/tls.(*Conn).Read(0xc0000aea80, 0xc00061f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
		/usr/local/go/src/crypto/tls/conn.go:1276 +0x165
	net/http.(*persistConn).Read(0xc00016b440, 0xc00061f000, 0x1000, 0x1000, 0xc0008100c0, 0xc000241d40, 0x405755)
		/usr/local/go/src/net/http/transport.go:1922 +0x77
	bufio.(*Reader).fill(0xc000249a40)
		/usr/local/go/src/bufio/bufio.go:101 +0x108
	bufio.(*Reader).Peek(0xc000249a40, 0x1, 0x0, 0x1, 0x4, 0x1, 0x3)
		/usr/local/go/src/bufio/bufio.go:139 +0x4f
	net/http.(*persistConn).readLoop(0xc00016b440)
		/usr/local/go/src/net/http/transport.go:2083 +0x1a8
	created by net/http.(*Transport).dialConn
		/usr/local/go/src/net/http/transport.go:1743 +0xc77

	goroutine 675 [syscall]:
	os/signal.signal_recv(0x0)
		/usr/local/go/src/runtime/sigqueue.go:168 +0xa5
	os/signal.loop()
		/usr/local/go/src/os/signal/signal_unix.go:23 +0x25
	created by os/signal.Notify.func1.1
		/usr/local/go/src/os/signal/signal.go:151 +0x45

	goroutine 676 [chan receive]:
	code.cloudfoundry.org/cli/util/configv3.catchSignal(0xc0003b1440, 0xc00080c180, 0x1e)
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/configv3/write_config.go:64 +0x34
	created by code.cloudfoundry.org/cli/util/configv3.(*Config).WriteConfig
		/tmp/build/80754af9/gopath/src/code.cloudfoundry.org/cli/util/configv3/write_config.go:41 +0x2de

	goroutine 605 [select]:
	net/http.(*persistConn).writeLoop(0xc00016b440)
		/usr/local/go/src/net/http/transport.go:2382 +0xf7
	created by net/http.(*Transport).dialConn
		/usr/local/go/src/net/http/transport.go:1744 +0xc9c

	goroutine 629 [IO wait]:
	internal/poll.runtime_pollWait(0x7f1a33ed3ce8, 0x72, 0xffffffffffffffff)
		/usr/local/go/src/runtime/netpoll.go:222 +0x55
	internal/poll.(*pollDesc).wait(0xc00040c298, 0x72, 0x5e00, 0x5e23, 0xffffffffffffffff)
		/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
	internal/poll.(*pollDesc).waitRead(...)
		/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
	internal/poll.(*FD).Read(0xc00040c280, 0xc0007b8000, 0x5e23, 0x5e23, 0x0, 0x0, 0x0)
		/usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
	net.(*netFD).Read(0xc00040c280, 0xc0007b8000, 0x5e23, 0x5e23, 0x20300000000000, 0x7f1a3422afff, 0x400)
		/usr/local/go/src/net/fd_posix.go:55 +0x4f
	net.(*conn).Read(0xc000474470, 0xc0007b8000, 0x5e23, 0x5e23, 0x0, 0x0, 0x0)
		/usr/local/go/src/net/net.go:183 +0x91
	crypto/tls.(*atLeastReader).Read(0xc00048e090, 0xc0007b8000, 0x5e23, 0x5e23, 0xc0002429f8, 0x1914f20, 0x0)
		/usr/local/go/src/crypto/tls/conn.go:776 +0x63
	bytes.(*Buffer).ReadFrom(0xc00018baf8, 0x1273520, 0xc00048e090, 0x40b6a5, 0xfd1020, 0x10e8b00)
		/usr/local/go/src/bytes/buffer.go:204 +0xbe
	crypto/tls.(*Conn).readFromUntil(0xc00018b880, 0x12742c0, 0xc000474470, 0x5, 0xc000474470, 0x203000)
		/usr/local/go/src/crypto/tls/conn.go:798 +0xf3
	crypto/tls.(*Conn).readRecordOrCCS(0xc00018b880, 0x0, 0x0, 0x438ffc)
		/usr/local/go/src/crypto/tls/conn.go:605 +0x115
	crypto/tls.(*Conn).readRecord(...)
		/usr/local/go/src/crypto/tls/conn.go:573
	crypto/tls.(*Conn).Read(0xc00018b880, 0xc00012a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
		/usr/local/go/src/crypto/tls/conn.go:1276 +0x165
	net/http.(*persistConn).Read(0xc0003f46c0, 0xc00012a000, 0x1000, 0x1000, 0xc000286f00, 0xc000242d40, 0x405755)
		/usr/local/go/src/net/http/transport.go:1922 +0x77
	bufio.(*Reader).fill(0xc000791e60)
		/usr/local/go/src/bufio/bufio.go:101 +0x108
	bufio.(*Reader).Peek(0xc000791e60, 0x1, 0x0, 0x1, 0x4, 0x1, 0x3)
		/usr/local/go/src/bufio/bufio.go:139 +0x4f
	net/http.(*persistConn).readLoop(0xc0003f46c0)
		/usr/local/go/src/net/http/transport.go:2083 +0x1a8
	created by net/http.(*Transport).dialConn
		/usr/local/go/src/net/http/transport.go:1743 +0xc77

	goroutine 623 [IO wait]:
	internal/poll.runtime_pollWait(0x7f1a33ed3dd0, 0x72, 0xffffffffffffffff)
		/usr/local/go/src/runtime/netpoll.go:222 +0x55
	internal/poll.(*pollDesc).wait(0xc000806498, 0x72, 0xd00, 0xdfb, 0xffffffffffffffff)
		/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
	internal/poll.(*pollDesc).waitRead(...)
		/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
	internal/poll.(*FD).Read(0xc000806480, 0xc000824000, 0xdfb, 0xdfb, 0x0, 0x0, 0x0)
		/usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
	net.(*netFD).Read(0xc000806480, 0xc000824000, 0xdfb, 0xdfb, 0x0, 0x64, 0xc000411878)
		/usr/local/go/src/net/fd_posix.go:55 +0x4f
	net.(*conn).Read(0xc000474468, 0xc000824000, 0xdfb, 0xdfb, 0x0, 0x0, 0x0)
		/usr/local/go/src/net/net.go:183 +0x91
	crypto/tls.(*atLeastReader).Read(0xc000233200, 0xc000824000, 0xdfb, 0xdfb, 0xc0004119f8, 0x1914f20, 0x0)
		/usr/local/go/src/crypto/tls/conn.go:776 +0x63
	bytes.(*Buffer).ReadFrom(0xc00018a978, 0x1273520, 0xc000233200, 0x40b6a5, 0xfd1020, 0x10e8b00)
		/usr/local/go/src/bytes/buffer.go:204 +0xbe
	crypto/tls.(*Conn).readFromUntil(0xc00018a700, 0x12742c0, 0xc000474468, 0x5, 0xc000474468, 0x203000)
		/usr/local/go/src/crypto/tls/conn.go:798 +0xf3
	crypto/tls.(*Conn).readRecordOrCCS(0xc00018a700, 0x0, 0x0, 0x438ffc)
		/usr/local/go/src/crypto/tls/conn.go:605 +0x115
	crypto/tls.(*Conn).readRecord(...)
		/usr/local/go/src/crypto/tls/conn.go:573
	crypto/tls.(*Conn).Read(0xc00018a700, 0xc000825000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
		/usr/local/go/src/crypto/tls/conn.go:1276 +0x165
	net/http.(*persistConn).Read(0xc00016b200, 0xc000825000, 0x1000, 0x1000, 0xc0002dfaa0, 0xc000411d40, 0x405755)
		/usr/local/go/src/net/http/transport.go:1922 +0x77
	bufio.(*Reader).fill(0xc00081af60)
		/usr/local/go/src/bufio/bufio.go:101 +0x108
	bufio.(*Reader).Peek(0xc00081af60, 0x1, 0x0, 0x1, 0x4, 0x1, 0x3)
		/usr/local/go/src/bufio/bufio.go:139 +0x4f
	net/http.(*persistConn).readLoop(0xc00016b200)
		/usr/local/go/src/net/http/transport.go:2083 +0x1a8
	created by net/http.(*Transport).dialConn
		/usr/local/go/src/net/http/transport.go:1743 +0xc77

	goroutine 624 [select]:
	net/http.(*persistConn).writeLoop(0xc00016b200)
		/usr/local/go/src/net/http/transport.go:2382 +0xf7
	created by net/http.(*Transport).dialConn
		/usr/local/go/src/net/http/transport.go:1744 +0xc9c

	goroutine 630 [select]:
	net/http.(*persistConn).writeLoop(0xc0003f46c0)
		/usr/local/go/src/net/http/transport.go:2382 +0xf7
	created by net/http.(*Transport).dialConn
		/usr/local/go/src/net/http/transport.go:1744 +0xc9c

		Your Platform Details
		e.g. Mac OS X 10.11, Windows 8.1 64-bit, Ubuntu 14.04.3 64-bit

		Shell
		e.g. Terminal, iTerm, Powershell, Cygwin, gnome-terminal, terminator

**Expected behavior**
The plugin would install

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Build a docker image
2. 

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm)
- version of the CLI you are running
- version of the CC API Release you are on

**Notes regarding V6 and V7 CLI support:** 
- V6:
  - Minimum supported version of CF Deployment: v7.0.0 (CAPI Release: 1.74.0 (APIs 2.128.0 and 3.63.0))
  - Maximum supported version of CF Deployment: v13.4.0 (CAPI Release: 1.94.0 (APIs 2.149.0 and 3.84.0))
- V7:
  - Minimum supported version of CF Deployment: v13.5.0 (CAPI Release: 1.95.0 (APIs 2.150.0 and 3.85.0))

**Comment by norman-abramovitz** [comment]
This error is caused by a corrupted config.json file in the plugins directory.  There seems to be no attempt to avoid multiple writers.

**Comment by norman-abramovitz** [comment]
The config.json needs to be removed or restored from a backup.   You need to install the again.

**Comment by gururajsh** [comment]
Thank you @norman-abramovitz for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket with the necessary information mentioned in our issue template.
