### ISSUE TITLE
CLI v8 windows installer cf.exe symlink still points to cf7.exe

### ISSUE THREAD

**Issue by bgreman** [cloudfoundry/cli#2242]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [X] I reviewed open and closed github issues that may be related to my problem.
- [X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [X] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
After installing the v8 CLI from the Windows Installer on Windows 10, `cf <command>` does not work.

**What happened**
In windows command prompt, the following is displayed
```
C:\Program Files\Cloud Foundry>cf login
The system cannot find the file C:\Program Files\Cloud Foundry\cf.exe.
```

In Powershell it manifests as:
```
C:\Program Files\Cloud Foundry> cf login
ResourceUnavailable: Program 'cf.exe' failed to run: No application is associated with the specified file for this operation.At line:1 char:1
+ cf login
+ ~~~~~~~~.
```

**Expected behavior**
Normal command-line functionality is provided.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Uninstall any existing CF CLI installation.
2. Download and install the x64 Windows installer for the v8 CLI with default options selected.
3. Attempt to run a cf command from the Windows command prompt or Powershell.

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm)
- version of the CLI 8.1.0

A short investigation led to finding that the `cf.exe` symlink created in the default installation directory (`C:\Program Files\Cloud Foundry`) is pointing at the non-existent `cf7.exe` instead of `cf8.exe`.

This can be worked around by deleting the existing `cf.exe` symlink and creating a valid one with:
```
cd C:\Program Files\Cloud Foundry
mklink cf.exe cf8.exe
```

**Comment by a-b** [comment]
Thanks for reporting this seems like a duplicate to https://github.com/cloudfoundry/cli/issues/2227 . I'll go ahead and close this. Feel free to reopen this issue.

**Comment by bgreman** [comment]
Sorry about that.  I did search but only for 'symlink' and not 'symbolic link.'  My bad.
