### ISSUE TITLE
cf create-service error return code handling changed since version 8.x for existing instances

### ISSUE THREAD

**Issue by OliverDrechsler** [cloudfoundry/cli#2251]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**

When I execute the command 
`cf create-service myService myServicePlan myServiceInstanceName` 
for creating a service instance and when it already exists the command returned a success / OK with return code 0

I detected that since Version 8.1 (and i assume since 8.0 create-service api change to v3) 
that the return code in case of failures changed to `failed` with return code 1. 
In all previous Version till 7.3 it was every time a return code 0 means OK/success returned. 

**What happened**
Till version 7.3 the command `cf create-service myService myServicePlan myServiceInstanceName -v`
*returned in verbose output:*
```
.
.
.

REQUEST: [2022-02-10T17:06:18+01:00]
POST /v2/service_instances?accepts_incomplete=true HTTP/1.1
Host: a_CF_API_FQDN
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: cf/7.3.0+645c3ce6a.2021-08-16 (go1.16.6; amd64 linux)
{
"name": "myServiceInstanceName",
"service_plan_guid": "3708633b-3499-403f-bba1-b454a6397894",
"space_guid": "e5213d47-f9b3-468b-8a4c-c7faccdd2e44"
}

RESPONSE: [2022-02-10T17:06:18+01:00]
HTTP/1.1 400 Bad Request
Content-Length: 134
Content-Type: application/json;charset=utf-8
Date: Thu, 10 Feb 2022 16:06:19 GMT
Server: nginx
X-B3-Spanid: 12345e123a1d123c
X-B3-Traceid: 12345e123a1d123c
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: ea502859-f91d-4b89-8abb-dbbbc0243b42::a8d3b815-1d03-464c-8410-4e16c4939be2
{
"code": 60002,
"description": "The service instance name is taken: myServiceInstanceName",
"error_code": "CF-ServiceInstanceNameTaken"
}


OK

Service myServiceInstanceName already exists
```
It returned a OK with bash return code 0.

*Same command above with cf cli version 8.1 returned in verbose output:*
```
.
.
.

REQUEST: [2022-02-10T16:05:38Z]
POST /v3/service_instances HTTP/1.1
Host: a_CF_API_FQDN
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: cf/8.1.0+034d929d7.2022-01-03 (go1.16.6; amd64 linux)
{
"name": "myServiceInstanceName",
"relationships": {
"service_plan": {
"data": {
"guid": "3708633b-3499-403f-bba1-b454a6397894"
}
},
"space": {
"data": {
"guid": "e5213d47-f9b3-468b-8a4c-c7faccdd2e44"
}
}
},
"type": "managed"
}

RESPONSE: [2022-02-10T16:05:38Z]
HTTP/1.1 422 Unprocessable Entity
Content-Type: application/json; charset=utf-8
Date: Thu, 10 Feb 2022 16:05:38 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx
X-B3-Spanid: 12345e123a1d123c
X-B3-Traceid: 12345e123a1d123c
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Runtime: 0.082659
X-Vcap-Request-Id: ea502859-f91d-4b89-8abb-dbbbc0243b42::a8d3b815-1d03-464c-8410-4e16c4939be2
X-Xss-Protection: 1; mode=block
{
"errors": [
{
"code": 10008,
"detail": "The service instance name is taken: myServiceInstanceName.",
"title": "CF-UnprocessableEntity"
}
]
}


The service instance name is taken: myServiceInstanceName.
FAILED
```
Now this returned a FAILED with bash return code 1.

 
**Expected behavior**
- Either the old return code behaviour "0" 
or
- a clear breaking change code description for error return code handling at minimum in the release notes

because this was nowhere mentioned.  

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:  

With cf cli version before 8.x
1. create a NEW service instance `cf cf create-service myService myServicePlan myServiceInstanceName`  
2. rerun the command `cf cf create-service myService myServicePlan myServiceInstanceName -v` again with same Name  
3. See success
With cf cli Version 8.1 and above
4. create a NEW service instance `cf cf create-service myService myServicePlan myServiceInstanceName`  
5. rerun the command `cf cf create-service myService myServicePlan myServiceInstanceName -v` again with same Name  
6. See failed message

**Notes regarding V6 and V7 CLI support:** 
- V6:
  - Minimum supported version of CF Deployment: v7.0.0 (CAPI Release: 1.74.0 (APIs 2.128.0 and 3.63.0))
  - Maximum supported version of CF Deployment: v13.4.0 (CAPI Release: 1.94.0 (APIs 2.149.0 and 3.84.0))
- V7:
  - Minimum supported version of CF Deployment: v13.5.0 (CAPI Release: 1.95.0 (APIs 2.150.0 and 3.85.0))

**Comment by gururajsh** [comment]
Thank you @OliverDrechsler for your submission. This is a change that happened by switching to CAPI v3 as mentioned in [release notes](https://github.com/cloudfoundry/cli/releases/tag/v8.0.0) of 8.0.0 which is a new major version(containing breaking changes). This more of a CAPI behavior change than CLI.
