### ISSUE TITLE
Update the tip for security group commands

### ISSUE THREAD

**Issue by mariash** [cloudfoundry/cli#2255]
**Please provide details on the following items. Failure to do so may result in deletion of your feature request.** 

**What's the user value of this feature request?**

Users will see the new tip after they run security-groups commands like (bind-security-group, unbind-security-group and update-security-group) that their changes will be applied automatically if they have dynamic asgs enabled.

**Who is the functionality for?**

Customers who use security group commands

**How often will this functionality be used by the user?**

Whenever user is running security group command

**Is your feature request related to a problem? Please describe.**

Users should know they don't need to restart their application when they have dynamic ASG's enabled.

Please see these 2 pull requests:

* for v9 - https://github.com/cloudfoundry/cli/pull/2254
* for v8 - https://github.com/cloudfoundry/cli/pull/2256
* for v7 - https://github.com/cloudfoundry/cli/pull/2253

**Comment by hjcalderon10** [comment]
Hi @mariash!

We have reviewed the PRs and merged them respectively. This change will be released on the next V7 and V8 patch release.

I will close the issue now, feel free to reopen it if needed.
