### ISSUE TITLE
Support $XDG_CONFIG_HOME environment variable

### ISSUE THREAD

**Issue by piejanssens** [cloudfoundry/cli#2258]
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

If $XDG_CONFIG_HOME is set, put the cf config in `$XDG_CONFIG_HOME/cf`.
Usually `$XDG_CONFIG_HOME` is set to `~/.config`.

**Comment by ljluestc** [comment]
1. Set the `$XDG_CONFIG_HOME` Environment Variable: In your shell profile (e.g., `.bashrc`, `.zshrc`), set the `$XDG_CONFIG_HOME` environment variable to specify the desired configuration directory. You mentioned that `$XDG_CONFIG_HOME` is usually set to `~/.config`, so you can add the following line to your shell profile:

   ```bash
   export XDG_CONFIG_HOME="$HOME/.config"
   ```

   Save the file and then reload your shell or run `source ~/.bashrc` (or equivalent for your shell).

2. Create the CF Config Directory: After setting the `$XDG_CONFIG_HOME` environment variable, the CF CLI will look for its configuration in `$XDG_CONFIG_HOME/cf`. If the directory doesn't exist, create it:

   ```bash
   mkdir -p "$XDG_CONFIG_HOME/cf"
   ```

3. Move Existing CF Config (Optional): If you have an existing CF configuration in the default location (usually `~/.cf`), you can move it to the new location using the following command:

   ```bash
   mv ~/.cf/* "$XDG_CONFIG_HOME/cf/"
   ```

With these steps, the CF CLI should use the configured `$XDG_CONFIG_HOME/cf` directory for its configuration.

Please note that while the CF CLI does not natively support the XDG Base Directory Specification, you can achieve the desired behavior by setting the appropriate environment variables and organizing the configuration files accordingly.
