### ISSUE TITLE
cf8 create-service improperly fails when service brought by multiple brokers but only one plan is visible 

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#2269]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**

```
$ cf create-service o-intranet-proxy-access default o-intranet-proxy-access-service
Creating service instance o-intranet-proxy-access-service in org internal / space osb-reverse-proxy-1 as auser...
Service offering 'o-intranet-proxy-access' is provided by multiple service brokers. Specify a broker name by using the '-b' flag.
FAILED

# However a single service plan has the visibility in the current space
$ cf service-access -e o-intranet-proxy-access
Getting service access for service offering o-intranet-proxy-access as auser...

broker: intranet-sec-broker
   offering                  plan      access   orgs
   o-intranet-proxy-access   default   none     

broker: o-intranet-proxy-access
   offering                  plan      access    orgs
   o-intranet-proxy-access   default   limited   system_domain,orange,internal
```

when specifying the -b option, cf8 still fails to create the service instance

```
$ cf create-service o-intranet-proxy-access default o-intranet-proxy-access-service -b o-intranet-proxy-access
Creating service instance o-intranet-proxy-access-service in org internal / space osb-reverse-proxy-1 as auser
The plan 'default' could not be found for service offering 'o-intranet-proxy-access' and broker 'o-intranet-proxy-access-service'.
FAILED
```

With `CF_TRACE=true` option, cl8 shows the api request is `/v3/service_plans?names=default&page=1&per_page=50&service_broker_names=o-intranet-proxy-access-service&service_offering_names=o-intranet-proxy-access`

**What happened**
service creation failed

**Expected behavior**

just like with with cf v7, the creation request should be accepted since a single service plan has the visibility in the current space

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `cf ...`
2. Bind a service `cf bind-service`
3. See error

* Deploy two brokers offering the same service 
* Only enable visibility for a single broker
* Try to create a service instance -> fails unless -b flag is specified

**Provide more context**
- platform and shell details ( e.g. Mac OS X 10.11 iTerm)
- version of the CLI you are running: cf version 8.3.0+e6f8a85.2022-03-11
- version of the CC API Release you are on

**Notes regarding V6 and V7 CLI support:** 
- V6:
  - Minimum supported version of CF Deployment: v7.0.0 (CAPI Release: 1.74.0 (APIs 2.128.0 and 3.63.0))
  - Maximum supported version of CF Deployment: v13.4.0 (CAPI Release: 1.94.0 (APIs 2.149.0 and 3.84.0))
- V7:
  - Minimum supported version of CF Deployment: v13.5.0 (CAPI Release: 1.95.0 (APIs 2.150.0 and 3.85.0))

**Comment by gururajsh** [comment]
Thank you @gberche-orange for your submission. Looks like this issue has been addressed [here](https://github.com/cloudfoundry/cli/issues/2792). If you are still seeing this issue with the latest version of CLI (and CAPI > 1.173.0) please open a new GH Issue.
