### ISSUE TITLE
Error sync of  repository https://packages.cloudfoundry.org/fedora/

### ISSUE THREAD

**Issue by lsstreet** [cloudfoundry/cli#2273]
Hello.

We are using a RedHat Satellite server and during the synchronization of the repositories " https://packages.cloudfoundry.org/fedora/" is giving next error:

`A file located at the url https://packages.cloudfoundry.org/fedora/releases/v8.0.103/cf8-cli-installer_i686.rpm failed validation due to checksum.`

Tried also to install the package "cf8-cli-installer_i686.rpm" directly using but the package cannot be open

```
[root@localhost ~]# yum localinstall  https://packages.cloudfoundry.org/fedora/releases/v8.0.103/cf8-cli-installer_i686.rpm f
Loaded plugins: auto-update-debuginfo, fastestmirror, product-id, search-disabled-repos, subscription-manager, verify, versionlock

cf8-cli-installer_i686.rpm                                                                                                                                                          | 2.4 kB  00:00:00     
Cannot open: https://packages.cloudfoundry.org/fedora/releases/v8.0.103/cf8-cli-installer_i686.rpm. Skipping.
Skipping: f, filename does not end in .rpm.
Nothing to do
```
![satelite (002)](https://user-images.githubusercontent.com/97909821/164507309-ed62cf67-a19d-4f69-96d5-f9e55bf122e8.png)

Can you please check from your side if the package cf8-cli-installer_i686.rpm : https://packages.cloudfoundry.org/fedora/releases/v8.0.103/cf8-cli-installer_i686.rpm
was not altered by mistake? 
Thank you

**Comment by gururajsh** [comment]
Hi,
The issue was with the filename. It is resolved now.  Please try downloading using the filename 'cf8-cli-installer_8.0.103_i686.rpm'. 
If the issue still persists, please let us know.

**Comment by lsstreet** [comment]
Hi @gururajsh 
Actually we are using Redhat Satellite to synchronize the cloudfoundre repository. I just checked and the error is still persists

"A file located at the url https://packages.cloudfoundry.org/fedora/releases/v8.0.103/cf8-cli-installer_i686.rpm failed validation due to checksum."

Can you check this issuer once again.
Thanks

**Comment by gururajsh** [comment]
Hi @lsstreet,

The link posted above is still pointing to old filename. I just tried with [https://packages.cloudfoundry.org/fedora/releases/v8.0.103/cf8-cli-installer_8.0.103_i686.rpm](https://packages.cloudfoundry.org/fedora/releases/v8.0.103/cf8-cli-installer_8.0.103_i686.rpm) and I'm able to download. Can you try with this link?

**Comment by lsstreet** [comment]
Hi @gururajsh, 
Thank you for your reply
Yes, your link is working, but our satellite server, when it try to synchronize  is checking all packages from your repositories and is failing for the file cf8-cli-installer_i686.rpm which was modified and the checksum also changed.  
If it is an old version of package in my opinion is better to remove this file and regenerate rpm metadata.

**Comment by gururajsh** [comment]
All 8.0.103 version files are removed now. Looks like this version was added as part of some testing, hence the issue.

**Comment by lsstreet** [comment]
hmm,  still have the error.
A file located at the url https://packages.cloudfoundry.org/fedora/releases/v8.0.103/cf8-cli-installer_i686.rpm failed validation due to checksum.

**Comment by gururajsh** [comment]
v8.0.103 folder itself is deleted. So, the link should give some path not found related error. May be its cached?

**Comment by lsstreet** [comment]
![cloudfoundry](https://user-images.githubusercontent.com/97909821/199378241-b1a967ff-f575-48fd-8466-f303477bc0b2.png)

**Comment by lsstreet** [comment]
@gururajsh 
I just checked and it seems that the version v8.0.103 is still available, please see the screenshot in above message.

**Comment by a-b** [comment]
Hi @lsstreet, where did you get `8.0.103` from? This is not an officially released version [here](https://github.com/cloudfoundry/cli/releases) or [here](https://github.com/cloudfoundry/cli/tags)

cc @gururajsh

**Comment by gururajsh** [comment]
Closing this issue. @lsstreet if you still face issues with downloading latest CLI version, please open a new issue.
