### ISSUE TITLE
CF-CLI v7.5.0 missing on AWS S3

### ISSUE THREAD

**Issue by JamesClonk** [cloudfoundry/cli#2281]
**Description**
According to https://github.com/cloudfoundry/cli/blob/master/doc/installation-instructions/installation-instructions-v7.md#installers-and-compressed-binaries the way to download the CF-CLI tarball is to use https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github.
but since this morning this URL is not working anymore.

It seems there was an attempt at releasing a new version of the v7 CLI, v7.5.0, but somehow this was improperly done and that CLI version is missing on S3.

When opening https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github all we get is the following error message:
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>releases/v7.5.0/cf7-cli_7.5.0_linux_x86-64.tgz</Key>
<RequestId>N19X09H8GARBX5N8</RequestId>
<HostId>
44cJe71/JIiu0XrKqmctymdhOjCOegiIDL46J+R5wA9i6VBGe7/3PCCBGhZBK/iHVPE2ThLuuZg=
</HostId>
</Error>
```

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Go to https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github
2. See above mentioned error message about missing v7.5.0 CF-CLI

**Comment by JamesClonk** [comment]
It seems now that whatever the issues was with the not-quite-yet released v7.5.0 has been reverted, https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github is pointing back to the existing v7.4.0.
:+1: 

I'll close this here then..

**Comment by a-b** [comment]
Your observation is accurate. Sorry for this experience - we had some issues with our shiny new release pipeline. v7.5.0 should be released soon.

**Comment by jibblesskibbles87** [comment]
Hey team did we also check this for the fedora release? we seem to be having the same issue.
