### ISSUE TITLE
Support Snap package manager

### ISSUE THREAD

**Issue by a-b** [cloudfoundry/cli#2282]
We're considering snap as the new CF CLI distribution channel. Please write your thoughts.

**What's the user value of this feature request?**
Linux distributions like Ubuntu leaning on snap recently. 

**Who is the functionality for?**
Linux users who prefer https://snapcraft.io/

**How often will this functionality be used by the user?**
During the installation on the relevant system.

**Who else is affected by the change?**
Not applicable

**Is your feature request related to a problem? Please describe.**
As an Ubuntu user, I want to install cf cli via snap.

**Describe the solution you'd like**
Publish CF CLI releases on https://snapcraft.io/

**Comment by gururajsh** [comment]
@a-b Is this still relevant?

**Comment by a-b** [comment]
It seems that modern Ubuntu adopted the Snap package format. However, it still supports Debian repositories and is unlikely to phase them out. @joaopapereira, do you have any thoughts on this?

**Comment by joaopapereira** [comment]
We should not add new delivery mechanisms just for the sake of it. My 2 cents here is that if no users are asking for this we should not do it.

**Comment by gururajsh** [comment]
We can look into this when there is user requirement.
