### ISSUE TITLE
Promote revisions, revision, and rollback commands from experimental to permanent

### ISSUE THREAD

**Issue by a-b** [cloudfoundry/cli#2289]
Revisions, revision, and rollback commands were introduced as experimental. The proposal is to promote `revisions`, `revision`, and `rollback` commands to the permanent set.

**Context**
https://github.com/cloudfoundry/docs-cf-cli/issues/78

**Comment by a-b** [comment]
I am adding @Gerg for visibility.

**Comment by gururajsh** [comment]
With v8.8.0 `revisions` and `rollback` command are no longer experimental. We are currently looking into making `revision` command non-experimental. It should be out soon.
