### ISSUE TITLE
Avoid use of deprecated `apt-key` in Linux installation documentation

### ISSUE THREAD

**Issue by vpavic** [cloudfoundry/cli#2304]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [ ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
[Linux installation documentation](https://docs.cloudfoundry.org/cf-cli/install-go-cli.html#pkg-linux) suggests setup of Cloud Foundry Foundation public key using `apt-key` tool that was deprecated. See relevant [manpages](https://manpages.ubuntu.com/manpages/jammy/en/man8/apt-key.8.html).

[Repository search for `apt-key`](https://github.com/cloudfoundry/cli/search?q=apt-key) shows 3 references in the project files and 3 in Wiki pages.

**What happened**
Usage of deprecated `apt-key` causes warnings both during installation and further `apt` usage.

**Expected behavior**
Installation documentation should not guide users to use deprecated tools.

**Exact Steps To Reproduce**
Follow Linux installation instructions and observe warnings due to `apt-key` usage.

**Provide more context**
This problem was already mentioned in an issue that was closed by the reporter:
- https://github.com/cloudfoundry/cli/issues/2218

Related Ask Ubuntu question:
- https://askubuntu.com/questions/1328806/how-to-solve-apt-key-deprecated

**Comment by gururajsh** [comment]
Hi, thank you for your submission. The wiki has been updated to not use `apt-key`
