### ISSUE TITLE
Getting error when I try to delete a cf app starting with hyphen

### ISSUE THREAD

**Issue by ibasu12** [cloudfoundry/cli#2308]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [X ] I reviewed open and closed github issues that may be related to my problem.
- [ X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ X] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ X] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Tried deleting a cf app name starting with hyphen using command  :  cf d -f '-my-app'

**What happened**
cf d -f '-my-app'
Incorrect Usage: unknown flag `m'

NAME:
   delete - Delete an app

USAGE:
   cf.exe delete APP_NAME [-r] [-f]

ALIAS:
   d

OPTIONS:
   -f      Force deletion without confirmation
   -r      Also delete any mapped routes

SEE ALSO:
   apps, scale, stop

**Expected behavior**
Expecting a successful deletion.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `cf d -f <app name starting with hyphen>`
3. See error

**Provide more context**
- Windows 10
- version of the CLI you are running : 7.2.0+be4a5ce2b.2020-12-10

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
