### ISSUE TITLE
pkg.go.dev documentation out of date

### ISSUE THREAD

**Issue by KevinJCross** [cloudfoundry/cli#2318]
Hi guys,
Im looking at re-using the cc client code within the cli in the app-autoscaler acceptance tests. 
this is problematic because the documentation on  [pkg.go.dev](https://pkg.go.dev/github.com/cloudfoundry/cli)  is out of date the last release was [7.1.0+incompatible](https://pkg.go.dev/github.com/cloudfoundry/cli?tab=versions)

The new releases 8.x have never been uploaded.

It would be great to have them there as reference instead of looking directly into the code like it was before.

**Comment by a-b** [comment]
I welcome this proposal. Would you like to make a PR?

**Comment by gururajsh** [comment]
Hi. Thank you for your submission. At this time it is not feasible for us to support this.
