### ISSUE TITLE
Feature Request: Support the restart of a single instance in restart command

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cli#232]
I didn't see a story in the tracker for this.  It would be great if we could restart a single instance with the CLI.

https://s3-us-west-1.amazonaws.com/cc-travis-api-doc/api_docs/31195055/apps/terminate_the_running_app_instance_at_the_given_index.html

Mike

**Comment by rvennam** [comment]
Did this feature ever make it in? It doesn't seem to be in cf 6.11.2

**Comment by youngm** [comment]
Yes.  cf restart-app-instance

**Comment by rvennam** [comment]
Great. Thanks!

**Comment by pradeepkusingh** [comment]
i am trying to restart only one instance out of 4 at a time , but above commands doesn't work for me.

cf restart-app-instacne
cf: 'restart-app-instacne' is not a registered command. See 'cf help'
