### ISSUE TITLE
Re-open #1952

### ISSUE THREAD

**Issue by philippthun** [cloudfoundry/cli#2344]
It was our assumption that `cf buildpacks` should now list a `state` column, but it's not. Tested with `cf version 8.5.0+73aa161.2022-09-12`.

I guess [this is the line](https://github.com/cloudfoundry/cli/blob/2201c608a95c65da071fc264cb3f4477d58cb6b6/command/v7/buildpacks_command.go#L51) where the table columns are defined and `state` is missing although CAPI returns that information.

**Comment by a-b** [comment]
Hi @philippthun, is there any PR you'd like us to review?

**Comment by philippthun** [comment]
@a-b - I've opened a small PR to address this issue: #2636
