### ISSUE TITLE
Error on creating a database with mapping to other spaces

### ISSUE THREAD

**Issue by 4CaDlqr2aU** [cloudfoundry/cli#2369]
- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
I am trying to create a database that includes a mapping to another space by specifying the "databaseMappings" property.

**What happened**
Creation failed with error  "provision could not be completed: Service broker error: Service broker hana-cloud failed with: invalid Parameter (databaseMappings): array must contain a single entry [ref 2KiptiuNe5Q9tvxYnJkpfHziifb]"

**Expected behavior**
Expected the database to be created successfully, including an additional mapping to the other space.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. create service instance: `cf8 create-service hana-cloud hana test_create_mapping -c "<json>"`
```
{
  "data": {
    "systempassword": "<pass>",
    "edition": "cloud",
    "memory": 30,
    "databaseMappings": [{
        "organization_guid": "<organization_guid>",
        "space_guid": "<space_guid>"
      },
      {
        "organization_guid": "<organization_guid>",
        "space_guid": "<space_guid> of the other space"
      }
    ]
  }
}
```
2. See error: provision could not be completed: Service broker error: Service broker hana-cloud failed with: invalid Parameter (databaseMappings): array must contain a single entry [ref 2KiptiuNe5Q9tvxYnJkpfHziifb]"
FAILED

**Provide more context**
- platform and shell details: Windows, version 10.0.22621
- version of the CLI you are running: 8.5.0+73aa16182.2022-09-12

**Notes regarding V6 and V7 CLI support:** 
- V6:
  - Minimum supported version of CF Deployment: v7.0.0 (CAPI Release: 1.74.0 (APIs 2.128.0 and 3.63.0))
  - Maximum supported version of CF Deployment: v13.4.0 (CAPI Release: 1.94.0 (APIs 2.149.0 and 3.84.0))
- V7:
  - Minimum supported version of CF Deployment: v13.5.0 (CAPI Release: 1.95.0 (APIs 2.150.0 and 3.85.0))

**Comment by gururajsh** [comment]
If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
