### ISSUE TITLE
Error while installing cli on debian

### ISSUE THREAD

**Issue by I065450** [cloudfoundry/cli#2376]
**Describe the bug and the command you saw an issue with**:

the following code to install cf cli stopped working since last version,
I have check and the documentation for installation didn't changed.

**curl -s https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add - && \
  echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list && \
  apt-get update && \
  apt-get install -y cf8-cli**

**What happened**:

our code started to fail since last version of CLI, here is the error we get:

**Get:1 https://packages.cloudfoundry.org/debian stable/main amd64 cf8-cli amd64 8.6.0 [7082 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 7082 kB in 4s (1920 kB/s)
dpkg-deb: error: archive '/var/cache/apt/archives/cf8-cli_8.6.0_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /var/cache/apt/archives/cf8-cli_8.6.0_amd64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/cf8-cli_8.6.0_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c curl -s https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add - &&   echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list &&   apt-get update &&   apt-get install -y cf8-cli' returned a non-zero code: 100
Build step 'Execute shell' marked build as failure**

**Expected behavior**:

CLI installed

**Exact Steps To Reproduce**:

run installation code as above on debian

**Provide more context**:

the code is part of our docker file

**Comment by mymasse** [comment]
Same issue when installing on debian bullseye.

**Comment by vmspotgit** [comment]
Same problem here.


Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

-----
Get:1 https://packages.cloudfoundry.org/debian stable/main amd64 cf8-cli amd64 8.6.0 [7082 kB]
Fetched 7082 kB in 14s (503 kB/s)
dpkg-deb: error: archive '/var/cache/apt/archives/cf8-cli_8.6.0_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /var/cache/apt/archives/cf8-cli_8.6.0_amd64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/cf8-cli_8.6.0_amd64.deb

**Comment by a-b** [comment]
Hi, thanks for bringing this to our attention.

@xandroc and I were able to reproduce this issue on a Debian container. As a workaround for now, you should be able to install the previous version by running `apt install -y cf8-cli=8.5.0`. 

Our post-release QA is performed on the Ubuntu container and works as expected. We will look into this issue.

**Comment by a-b** [comment]
@xandroc and I suspect some dependencies changed in [this job](https://github.com/cloudfoundry/cli/blob/e9720d88608d8e5f716914401ca71315671f76ba/.github/workflows/build-sign-upload.yml#L306-L394).
[This is](https://github.com/cloudfoundry/cli/blob/e9720d88608d8e5f716914401ca71315671f76ba/.github/workflows/build-sign-upload.yml#L342) where we are compressing Debian packages.
Our working theory is that GitHub Actions ubuntu-latest [here](https://github.com/cloudfoundry/cli/blob/e9720d88608d8e5f716914401ca71315671f76ba/.github/workflows/build-sign-upload.yml#L159) got updated deb that uses a new type of compression between 8.5.0 and 8.6.0 cf cli releases.

**Comment by I065450** [comment]
> hat GitHub Actions ubuntu-la

Thanks, this is what we have done for now,
We are waiting for a solution.

**Comment by a-b** [comment]
Should be solved with [v8.6.1](https://github.com/cloudfoundry/cli/releases/tag/v8.6.1)

Feel free to reopen if you have any questions.
