### ISSUE TITLE
Bind SAP HANA DB in Business Application Studio

### ISSUE THREAD

**Issue by SergioEngineering** [cloudfoundry/cli#2381]
In SAP Business Application Studio (BAS) is necessary bind a micro service in SAP Hana DB, but since January 2023 there is an error:

Error running command hanaExplorerView.bindLocal.hdiContainer: Failed to chdir to /local/source/openvscode-server: No such file or directory

		Something unexpected happened. This is a bug in cf.

		Please re-run the command that caused this exception with the environment
		variable CF_TRACE set to true.

		Also, please update to the latest cli and try the command again:
		https://code.cloudfoundry.org/cli/releases

		Please create an issue at: https://code.cloudfoundry.org/cli/issues

		Include the below information when creating the issue:

		Command
		cf curl /v3/service_offerings?space_guids=ed20b411-198c-40e5-91b1-0fc8c5051eea&per_page=297

		CLI Version
		8.5.0+73aa161.2022-09-12

		Error
		template: Display Text:1: function "app_router_url" not defined

		Stack Trace
			goroutine 1 [running]:
	code.cloudfoundry.org/cli/util/panichandler.HandlePanic()
		/home/runner/work/cli/cli/util/panichandler/handler.go:19 +0x57
	panic({0x102e080, 0xc00084a090})
		/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x207
	text/template.Must(...)
		/opt/hostedtoolcache/go/1.18.5/x64/src/text/template/helper.go:25
	code.cloudfoundry.org/cli/util/ui.generateTranslationFunc.func1({0xc000800000, 0x202ab}, {0xc00084a010, 0x1, 0xc000800000?})
		/home/runner/work/cli/cli/util/ui/i18n.go:119 +0x2e8
	code.cloudfoundry.org/cli/util/ui.(*UI).TranslateText(...)
		/home/runner/work/cli/cli/util/ui/ui.go:409
	code.cloudfoundry.org/cli/util/ui.(*UI).DisplayText(0xc0001dfa20, {0xc000800000, 0x202ab}, {0x0?, 0x18?, 0x7ffcb41b1b8d?})
		/home/runner/work/cli/cli/util/ui/ui.go:248 +0x14c
	code.cloudfoundry.org/cli/command/v7.CurlCommand.Execute({{{0x13c70a0, 0xc0001dfa20}, {0x13c8300, 0xc000438e00}, {0x13bde10, 0xc0000b40e0}, {0x13caef8, 0xc000495650}, 0xc000018000, 0xc0003fa720}, ...}, ...)
		/home/runner/work/cli/cli/command/v7/curl_command.go:58 +0x2af
	code.cloudfoundry.org/cli/util/command_parser.(*CommandParser).executionWrapper(0xc0005160d0, {0x7f85049a26c0, 0x1b454d8}, {0xc0000b40c0, 0x0, 0x2})
		/home/runner/work/cli/cli/util/command_parser/command_parser.go:93 +0x297
	github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc0000e5c70, {0xc00019a160, 0x2, 0x2})
		/home/runner/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.1-0.20181221193153-c0795c8afcf4/parser.go:331 +0x8d4
	code.cloudfoundry.org/cli/util/command_parser.(*CommandParser).parse(0xc0005160d0, {0xc00019a160?, 0x2, 0x2}, {0x1058f60, 0x1b43ae0})
		/home/runner/work/cli/cli/util/command_parser/command_parser.go:224 +0xea
	code.cloudfoundry.org/cli/util/command_parser.(*CommandParser).ParseCommandFromArgs(...)
		/home/runner/work/cli/cli/util/command_parser/command_parser.go:57
	main.main()
		/home/runner/work/cli/cli/main.go:41 +0x2d4
	
	goroutine 18 [chan receive]:
	k8s.io/klog/v2.(*loggingT).flushDaemon(0x0?)
		/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1169 +0x6a
	created by k8s.io/klog/v2.init.0
		/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:420 +0xf6
	
	goroutine 604 [syscall]:
	os/signal.signal_recv()
		/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/sigqueue.go:151 +0x2f
	os/signal.loop()
		/opt/hostedtoolcache/go/1.18.5/x64/src/os/signal/signal_unix.go:23 +0x19
	created by os/signal.Notify.func1.1
		/opt/hostedtoolcache/go/1.18.5/x64/src/os/signal/signal.go:151 +0x2a
	
	goroutine 605 [chan receive]:
	code.cloudfoundry.org/cli/util/configv3.catchSignal(0xc00050cfd0?, {0xc00003e3f0, 0x24})
		/home/runner/work/cli/cli/util/configv3/write_config.go:64 +0x25
	created by code.cloudfoundry.org/cli/util/configv3.(*Config).WriteConfig
		/home/runner/work/cli/cli/util/configv3/write_config.go:41 +0x28b
	
	goroutine 586 [IO wait]:
	internal/poll.runtime_pollWait(0x7f8504add058, 0x72)
		/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/netpoll.go:302 +0x89
	internal/poll.(*pollDesc).wait(0xc0003a7f80?, 0xc00099e000?, 0x0)
		/opt/hostedtoolcache/go/1.18.5/x64/src/internal/poll/fd_poll_runtime.go:83 +0x32
	internal/poll.(*pollDesc).waitRead(...)
		/opt/hostedtoolcache/go/1.18.5/x64/src/internal/poll/fd_poll_runtime.go:88
	internal/poll.(*FD).Read(0xc0003a7f80, {0xc00099e000, 0xb82e, 0xb82e})
		/opt/hostedtoolcache/go/1.18.5/x64/src/internal/poll/fd_unix.go:167 +0x25a
	net.(*netFD).Read(0xc0003a7f80, {0xc00099e000?, 0xc00013be80?, 0xc00083a00d?})
		/opt/hostedtoolcache/go/1.18.5/x64/src/net/fd_posix.go:55 +0x29
	net.(*conn).Read(0xc0001aebb8, {0xc00099e000?, 0x0?, 0x0?})
		/opt/hostedtoolcache/go/1.18.5/x64/src/net/net.go:183 +0x45
	crypto/tls.(*atLeastReader).Read(0xc0008380c0, {0xc00099e000?, 0x0?, 0x0?})
		/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:785 +0x3d
	bytes.(*Buffer).ReadFrom(0xc0004393f8, {0x13ad340, 0xc0008380c0})
		/opt/hostedtoolcache/go/1.18.5/x64/src/bytes/buffer.go:204 +0x98
	crypto/tls.(*Conn).readFromUntil(0xc000439180, {0x13af560?, 0xc0001aebb8}, 0x414346?)
		/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:807 +0xe5
	crypto/tls.(*Conn).readRecordOrCCS(0xc000439180, 0x0)
		/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:614 +0x116
	crypto/tls.(*Conn).readRecord(...)
		/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:582
	crypto/tls.(*Conn).Read(0xc000439180, {0xc000315000, 0x1000, 0x1?})
		/opt/hostedtoolcache/go/1.18.5/x64/src/crypto/tls/conn.go:1285 +0x16f
	net/http.(*persistConn).Read(0xc0003ee6c0, {0xc000315000?, 0xc0004ca060?, 0xc000834d30?})
		/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:1929 +0x4e
	bufio.(*Reader).fill(0xc0008883c0)
		/opt/hostedtoolcache/go/1.18.5/x64/src/bufio/bufio.go:106 +0x103
	bufio.(*Reader).Peek(0xc0008883c0, 0x1)
		/opt/hostedtoolcache/go/1.18.5/x64/src/bufio/bufio.go:144 +0x5d
	net/http.(*persistConn).readLoop(0xc0003ee6c0)
		/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:2093 +0x1ac
	created by net/http.(*Transport).dialConn
		/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:1750 +0x173e
	
	goroutine 587 [select]:
	net/http.(*persistConn).writeLoop(0xc0003ee6c0)
		/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:2392 +0xf5
	created by net/http.(*Transport).dialConn
		/opt/hostedtoolcache/go/1.18.5/x64/src/net/http/transport.go:1751 +0x1791

applying the note the problem remains

**Comment by a-b** [comment]
This looks similar to https://github.com/cloudfoundry/cli/issues/2116. I'm going to close this ticket. Please feel free to reopen if this is a different issue.

**Comment by SergioEngineering** [comment]
hi,
purtroppo l'issue #2116 non risolve il problema, perchè si parla di CLI v. 7.0 ma qui abbiamo le CLI 8.5, quindi l'issue è differente.

**Comment by SergioEngineering** [comment]
hello, unfortunately issue #2116 does not solve the problem, because it talks about updating CLI 7.0, but here we have CLI 8.5
