### ISSUE TITLE
CF CLI on Windows 10 64bit still open "CF_TRACE" directory

### ISSUE THREAD

**Issue by mpucenicz** [cloudfoundry/cli#2386]
Hello everybody,

When I try lo execute "login" or "api" command as following 

`PS C:\Users\myUser> cf login`
`API endpoint: https://api.cf.us10.hana.ondemand.com`
`open C:\cf\trace: is a directory `

the commnad promp still there, it's like if the promp never finde the CF_TRACE directory....
 
I was changed the enviroment variables for trace, but the problem still.

could you help me please?

thank you so much!

Matias

**Comment by gururajsh** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8, please open a new ticket with the necessary information mentioned in our issue template.
