### ISSUE TITLE
provide golang 1.20 compiled binaries to fix DNS resolver issue

### ISSUE THREAD

**Issue by metskem** [cloudfoundry/cli#2391]
**What's the user value of this feature request?**
Currently the downloadable/installable binaries seem to be compiled with golang <1.20, which make them unusable if your MacOS  (arm arch) has only system resolvers configured.

[Starting in Go 1.201, DNS lookups when running on macOS will be done via the system instead of via Go’s built-in resolver.](https://danp.net/posts/macos-dns-change-in-go-1-20/)

Having a golang 1.20 compiled cf cli makes it usable in such configurations.

**Who is the functionality for?**
Anyone running MacOS (arm arch) where only system resolvers are configured.

**How often will this functionality be used by the user?**
On any invocation of cf that requires DNS lookups (almost all subcommands).

**Who else is affected by the change?**
No other users affected, it is not a breaking change.

**Is your feature request related to a problem? Please describe.**
We ran into this problem when we recently had to switch (company policy) from OpenVPN to F5 VPN. The F5 VPN client only configures the MacOS system resolvers. Once we switched to that VPN, most of our cf commands return error messages like : 

**_Getting apps in org system / space system as foo.bar@example.com...

Post "https://login.sys.example.com/oauth/token": dial tcp: lookup login.sys.example.com on [fe80::7e39:53ff:feed:67ef%en0]:53: no such host
FAILED_**

After building cf cli locally with golang 1.20 it works again.

**Describe the solution you'd like**
All the releases (or at least cf v8) should be compiled with golang 1.20 or higher (many other projects in the cf landscape have already switched to 1.20)

**Describe alternatives you've considered**
Well, building the binaries ourselves.

**Additional context**
N/A

**Comment by a-b** [comment]
We are planning to release the next cli with golang 1.20 very soon.
