### ISSUE TITLE
support for "targets" subcommand

### ISSUE THREAD

**Issue by pmuellr** [cloudfoundry/cli#24]
As I use a number of different CF environments during the course of my work, the `cf targets` command is very useful, so I can display all the current targets that I'm set up for.  

This subcommand doesn't seem to be available for `gcf`.

**Comment by jhiemer** [comment]
+1 highly needed here.

**Comment by simonleung8** [comment]
This probably doesn't address the issue entirely, but the plugin 'cf recorder' allows me to switch between different CF environments with a single command. It is simple to use
```
cf record env1
cf api ....
cf login ...
cf target ....
```
now just replay the command with `cf replay env1`, hope this can alleviate the pain a little :)

**https://github.com/simonleung8/cli-plugin-recorder

**Comment by maximilien** [comment]
Nicely done @simonleung8. Love the idea of this plugin. 

You should FYI this to mailing list (if you have not done so already.) Cheers :beers:

**Comment by camelpunch** [comment]
The Targets plugin provides this functionality: https://github.com/guidowb/cf-targets-plugin
