### ISSUE TITLE
error running command

### ISSUE THREAD

**Issue by VolkerSaggau** [cloudfoundry/cli#2413]
Error running command hanaExplorerView.bindLocal.hdiContainer: Failed to chdir to /local/source/openvscode-server: No such file or directory Something unexpected happened. This is a bug in cf. Please re-run the command that caused this exception with the environment variable CF_TRACE set to true. Also, please update to the latest cli and try the command again: https://code.cloudfoundry.org/cli/releases Please create an issue at: https://code.cloudfoundry.org/cli/issues Include the below information when creating the issue: Command cf curl /v3/service_offerings?space_guids=830c4854-133b-4f35-ba1c-bae1867ee947&per_page=297 CLI Version 8.5.0+73aa161.2022-09-12 Error template: Display Text:1: function "app_router_url" not defined Stack Trace goroutine 1 [running]: code.cloudfoundry.org/cli/util/panichandler.HandlePanic() /home/runner/work/cli/cli/util/panichandler/handler.go:19 +0x57 panic({0x102e080, 0xc0003b80f0}) /opt/hostedtoolcache/go/1.18...

**What happened**
in SAP BusinessApplicationStudio the HANA Tooling offers an assignment of a BINDING. This fails with this error message

**Expected behavior**
no error message

**Comment by a-b** [comment]
I can't find any reference or `app_router_url` in the cli or capi code. This seems SAP-specific.
I'm resolving this issue as fixed for now. Please don't hesitate to reopen it if you have any more questions or comments.
