### ISSUE TITLE
Incorrect values written to Registry for Inno Installers

### ISSUE THREAD

**Issue by mdanish-kh** [cloudfoundry/cli#2426]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**

While adding the package in Windows Package Manager (WinGet) https://github.com/microsoft/winget-pkgs/pull/107769, I found that the DisplayVersion written to Registry is incorrect in case of Inno installers. The DisplayVersion written is the raw string `VERSION` instead of the actual version string. DisplayName also contains the raw string instead of the actual version (but this isn't as important as version being incorrect). Since WinGet relies on metadata from Registry to be the source of accurate information about a given package, WinGet users will fail to know accurate information about the package and may even fail to receive an upgrade if matching logic determines the string `VERSION` > any given version e.g. 8.6.1

**What happened**

DisplayVersion and DisplayName keys written to Registry (and visible in Apps&Features / `appwiz.cpl`) contain the string `VERSION` instead of the actual version
![image](https://github.com/cloudfoundry/cli/assets/88161975/05f105ee-bd40-47d6-848a-53b6c65f19f7)

**Expected behavior**

DisplayVersion and DisplayName Registry values should contain the actual version string e.g. 8.6.1 for https://github.com/cloudfoundry/cli/releases/tag/v8.6.1

**Exact Steps To Reproduce**

1. Install x64 / x86 **installer** from https://github.com/cloudfoundry/cli/releases/tag/v8.6.1
2. Notice the version in `appwiz.cpl` / Apps&Features / DisplayVersion string in Registry

**Provide more context**

Happens with both x64 and x86 installers of `8.6.1`

**Comment by a-b** [comment]
Thanks for your input. Please consider making PR, as all release scripts are OSS and located [here](https://github.com/cloudfoundry/cli/blob/a003850873ca5428d5926f35669298f051a69fea/.github/win/windows-installer-v8-x64.iss#L6)

**Comment by a-b** [comment]
Thank you for your submission. If you still run into this issue with the latest CLI v8,  please open a new ticket with the necessary information mentioned in our issue template.
