### ISSUE TITLE
credhub-cli: The x86_64 architecture is required for this software. Error: credhub-cli: An unsatisfied requirement failed this build

### ISSUE THREAD

**Issue by sanganalla** [cloudfoundry/cli#2474]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [ ] I reviewed open and closed github issues that may be related to my problem.
- [ ] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ ] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
**brew install credhub-cli** is giving the below error on the MAC OS Ventura 13.4.1 Apple M2 chipset 8 GB RAM

**What happened**
Giving the below error after executing the above command.
credhub-cli: The x86_64 architecture is required for this software.
Error: credhub-cli: An unsatisfied requirement failed this build.

**Expected behavior**
It should install the credhub cli successfully.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. bin/bash -c "$(curl -fsSL [https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"] (https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

2. echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bash_profile
3. brew install credhub-cli

**Provide more context**
- platform and shell details ( e.g. Mac OS Ventura  13.4.1)
- version of the CLI you are running
  CredHub Cli version : latest
- version of the CC API Release you are on

**Comment by moleske** [comment]
This cli is for cloud foundry.  The credhub-cli can be found [here](https://github.com/cloudfoundry/credhub-cli).  Please open an issue against that repo
