### ISSUE TITLE
Feature Request: Support downloading raw files

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cli#248]
We'd like to download raw binary and text files from the cli.  I know you can `>` the output but it adds the `Getting files for app\nOK` message to the output which is annoying and doesn't work with binary files.

I'm thinking an arg like -f would work.

`cf files app app/someBinary.zip -f localBinary.zip`

As a side note.  We have  a fork of the CLI.  It would be handy if there was a way to invoke `net.doRequest` (https://github.com/cloudfoundry/cli/blob/master/cf/net/gateway.go#L402) without `net.dumpResponse` dumping the response body as well.  https://github.com/cloudfoundry/cli/blob/master/cf/net/http_client.go#L59

I imagine changing that api will be necessary to fix this issue so it would be great if it was fixed in such a way that others could take advantage of the ability to execute requests that don't dump the response body aswell.

Thanks,
Mike

**Comment by youngm** [comment]
with SCP coming in Diego I think I'll close this.

**Comment by afeld** [comment]
https://github.com/ibmjstart/cf-downloadmay help for those not on Diego yet.

**Comment by gberche-orange** [comment]
For those landing on this old issue, the CF ssh enables use of the scp command, whose specific syntax is detailed in https://docs.cloudfoundry.org/devguide/deploy-apps/ssh-apps.html#other-ssh-access
