### ISSUE TITLE
Docker image for 8.7.1 missing

### ISSUE THREAD

**Issue by pc-jedi** [cloudfoundry/cli#2497]
**Describe the bug and the command you saw an issue with**
According to the release notes of [`8.7.1`](https://github.com/cloudfoundry/cli/releases/tag/v8.7.1) one can pull the docker image with the following command:
```
docker pull cloudfoundry/cli:8.7.1
```

But it looks like that the image was never uploaded to docker hub. 
Because the latest version that is available there is 8.6.1 and since ~5 month no new version has been uploaded there.
See https://hub.docker.com/r/cloudfoundry/cli/tags

Besides that I'm curious what the `Dockerfile` looks like. I could not find it in the repository.

**Comment by moleske** [comment]
We had issues with our docker publishing so we missed 8.7.1.  Closing this as later cli versions have been published as a docker image

To answer the other question, here is where the dockerfile is for v8 https://github.com/cloudfoundry/cli/blob/v8/docker/Dockerfile .  It is a similar path for v7
