### ISSUE TITLE
high cpu usage behaviour 

### ISSUE THREAD

**Issue by PoojaGidaveer** [cloudfoundry/cli#2499]
Hi,

I am running performance tests on one of the CF applications. cf app has 4GB memory allocated. i have triggered a very slowramp tests and i see the cpu usage is increasing gradually and reached upto 300% and then app usage drops to 0 and the test execution fails with 500 Internal Server errors.

I don't see any restarts in the cf events of the applications.
as 4Gb is allocated i understand that the app has guaranteed cpu of 1c. 

can you please help me understand this cpu behaviour of cf app from 300% to 0% and then again 300% to 0% of cpu.
Does the deigo restarts the container as it is consuming more cpu than guaranteed?

Thanks and Regards,
Pooja

**Comment by moleske** [comment]
This does not describe a cf cli issue, though please correct me or reopen if I am misunderstanding.  I would suggest opening an issue on [diego-release](https://github.com/cloudfoundry/diego-release) if you have proven that your app is not the cause of the cpu usage spikes.
