### ISSUE TITLE
Feature Request: Provide a way for non admins to display security groups associated with their spaces

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cli#254]
It would be really useful if I as a non admin user had a way to see the security groups and their rules for a given space I am a member of.

I created a CC issue (https://github.com/cloudfoundry/cloud_controller_ng/issues/288) but @fraenkel correctly pointed out that security groups are returned as a part of a space already they're just not being used by the CLI.  The current CLI commands appear to be using admin only endpoints instead of getting the data from the space.

**Comment by simonleung8** [comment]
The newest CLI has this feature.
see the merged [Pull Request](https://github.com/cloudfoundry/cli/pull/344)
