### ISSUE TITLE
GPG key expired / regression on Linux repository (EXPKEYSIG)

### ISSUE THREAD

**Issue by kristian** [cloudfoundry/cli#2571]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Looks like your GPG key again expired, like in issue https://github.com/cloudfoundry/cli/issues/2046:

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://cf-cli-debian-repo.s3.amazonaws.com stable InRelease: The following signatures were invalid: EXPKEYSIG 172B5989FCD21EF8 CF CLI Team <cf-cli-eng@pivotal.io>
W: Failed to fetch https://packages.cloudfoundry.org/debian/dists/stable/InRelease  The following signatures were invalid: EXPKEYSIG 172B5989FCD21EF8 CF CLI Team <cf-cli-eng@pivotal.io>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**What happened**
A clear and concise description of what happen.

Cannot install CF CLI on Linux.

**Expected behavior**

Can install CF CLI on Linux.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:

```
wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
sudo apt-get update
```

**Provide more context**
Debian

**Comment by sv320151774** [comment]
We too facing the below metioned issue while installing cf7-cli

W: GPG error: https://cf-cli-debian-repo.s3.amazonaws.com stable InRelease: The following signatures were invalid: EXPKEYSIG 172B5989FCD21EF8 CF CLI Team <cf-cli-eng@pivotal.io>
E: The repository 'https://cf-cli-debian-repo.s3.amazonaws.com stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by Markus-Schroeder-de** [comment]
grr, it seems, if this happens every year in September.

**Comment by Markus-Schroeder-de** [comment]
dirty & bad Quick-fix: "apt-get install cf8-cli --allow-unauthenticated -y"

**Comment by sv320151774** [comment]
Download from URL and installed; this works for now

https://cli.run.pivotal.io/stable?release=debian64&source=github
dpkg -i cf7-cli-installer_7.7.2_x86-64.deb && apt-get install -f

**Comment by PierreFritsch** [comment]
Similar issues in the past:

- Sep 22, 2022 https://github.com/cloudfoundry/cli/issues/2046#issuecomment-1254709607

    > The fix from https://github.com/cloudfoundry/cli/issues/2046#issuecomment-930545620 worked so I'm not reopening the issue.

- Sep 27, 2021 https://github.com/cloudfoundry/cli/issues/2046#issuecomment-927910315

    > we proactively rotated our key a couple of weeks ago.
    > 
    > please try to update previously cached key in your system
    > ```sh
    > wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
    > ```

- Sep 13, 2020 https://github.com/cloudfoundry/cli/issues/2046

    > We've [prioritized this](https://www.pivotaltracker.com/story/show/174788941) as top of backlog, and will resolve it asap.
- Sep 13, 2018 https://github.com/cloudfoundry/cli/issues/1459 

    > We have a [story](https://www.pivotaltracker.com/story/show/160470508) to update the key

**Comment by michelmueller** [comment]
To workaround that issue, I replaced the existing `apt-get update` command with the following:

`apt -o Acquire::AllowInsecureRepositories=true -o Acquire::AllowDowngradeToInsecureRepositories=true update`

( thanks to https://github.com/cloudfoundry/cli/issues/2046#issuecomment-692238208 )

**Comment by kristian** [comment]
This is a issue that happened couple of times in the past already (this is why I put "regression" in the title initially).

Also in regards to the comments of @michelmueller and @Markus-Schroeder-de, everything you do on the apt-get side to allow insecure repositories is compromising your system security, as it will allow man-in-the-middle attacks to inject arbitrary code! A somewhat safe-ish bet on how to use the package anyways is what @sv320151774 suggested. I would definitely not consider setting `AllowDowngradeToInsecureRepositories` or `allow-unauthenticated` as it was pointed out by @michelmueller these options are not only "dirty & bad" but in the end **insecure**.

**Comment by michelmueller** [comment]
@kristian  absolutely agree. I will point that out and updating my comment.

**Comment by urquha** [comment]
My team has just encountered this problem. Is it a problem that we need to do something to solve or will the key get updated and it will just work for us?

**Comment by Tallicia** [comment]
We are experiencing this issue as well, and noted it in the thread from last year: https://github.com/cloudfoundry/cli/issues/2046#issuecomment-1713826060

**Comment by jbrown-xentity** [comment]
These errors are really problematic for any teams that have implemented ci/cd, as that usually involves the CLI tool... Very painful, please fix ASAP!!!

**Comment by kristian** [comment]
I tried raising awareness to the CLI team of Pivotal by sending an email to the DL they provided in the key.

**Comment by a-b** [comment]
CLI team is working on this.

**Comment by a-b** [comment]
Thanks for bringing it up. Debian should be fixed by now. Please test and let us know. 

The RedHat release will be fixed tomorrow by cutting a new release.

cc @ccjaimes , @moleske

**Comment by kristian** [comment]
Working! Thanks so much @a-b & team!

**Comment by ccjaimes** [comment]
:tada: CF CLI [v8.7.3](https://github.com/cloudfoundry/cli/releases/tag/v8.7.3) and [v7.7.3](https://github.com/cloudfoundry/cli/releases/tag/v7.7.3) have been released! This should include RedHat fix. Feel free to reopen in any case needed.

**Comment by mogul** [comment]
Is there any sort of regression test in place which might prevent this from recurring in the future?

**Comment by tiga05** [comment]
Happy september.
Its september, 2024 and it happens again

So @mogul I guess the answer is NO.
