### ISSUE TITLE
Cannot install CF CLI error: gpg: no valid OpenPGP data found

### ISSUE THREAD

**Issue by dkdralea** [cloudfoundry/cli#2598]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [ ] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
Provide details on what you were trying to do (and why).
Install CF CLI during deployment workflow.

**What happened**
A clear and concise description of what happen.
Installation of CF CLI fails with error: gpg: no valid OpenPGP data found.

**Expected behavior**
CF CLI installation works.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
  wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list &&
  sudo apt-get -y update &&
  sudo apt-get -y install cf8-cli

**Provide more context**
- ubuntu-20.04
- cf8-cli

**Comment by dkdralea** [comment]
Following the workaround from here works, but I feel it's hacky: https://answers.sap.com/questions/13210328/installing-cf-cli-on-ubuntu-20041.html
I can install CF CLI v8 I add **--no-check-certificate** as below:
wget **--no-check-certificate** -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -

Can you please have a look at the issue anyway?

**Comment by andreasvoigt** [comment]
Maybe connected to https://github.com/cloudfoundry/cli/issues/2603 ?
