### ISSUE TITLE
Cli fails to list repo plugins

### ISSUE THREAD

**Issue by theghost5800** [cloudfoundry/cli#2616]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
I am trying to execute `cf repo-plugins -r CF-Community` but fails with

`Getting plugins from repository 'CF-Community' ...
Logged errors:
Invalid json data from 'CF-Community' - invalid character '<' looking for beginning of value`

list of configured plugins repo urls:
```
cf list-plugin-repos
OK

Repo Name      URL
CF-Community   https://plugins.cloudfoundry.org
```

https://plugins.cloudfoundry.org is accessible through web browser

With set env CF_TRACE=1 doesn't show any additional details 

**Expected behavior**
It supposed to return list of available plugins for installation.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. cf list-plugin-repos
2. cf repo-plugins -r CF-Community

**Provide more context**
- platform and shell details - MacOS Ventura 13.6, iTerm2
- version of the CLI you are running - cf version 8.7.3+efd1d03.2023-09-12
- version of the CC API Release you are on - 3.147.0

**Comment by mjyeaney** [comment]
Still having these issues on cf version 8.7.7+583a09a.2023-12-26, using WSL / Ubuntu 22.04.3. 

Any updates as to what is causing this? We're effectively blocked.

**Comment by moleske** [comment]
whoops forgot to link the prs here
https://github.com/cloudfoundry/cli/pull/2722
https://github.com/cloudfoundry/cli/pull/2731
https://github.com/cloudfoundry/cli/pull/2732

**Comment by mjyeaney** [comment]
Appreciate the links - any idea when these would be released?

**Comment by mjyeaney** [comment]
Bumping again...any updates on a release for this fix?

**Comment by mjyeaney** [comment]
@theghost5800 Confirmed - appreciate the insights. Our build script stopped at a list check and we assumed all other repo operations were disrupted as well. Thank you!
