### ISSUE TITLE
Feature request: allow the org admin to list all routes in the org

### ISSUE THREAD

**Issue by haojun** [cloudfoundry/cli#265]
Currently, cf routes only lists routes in the current space, it's not convenient for the org admin to manage the routes, e.g:
1. to find how many orphaned routes exists in the org and which ones can be released
2. to find if a route is mapped to an app of another space, so if a new app wants to use an existing route, the admin can decide weather to map the route to the new app

I think the feature is usable, and if it is accepted, i will make some PRs to handle this.

Thanks
Haojun

**Comment by dieucao** [comment]
@haojun cf-release v198 now supports filtering /v2/routes by organization_guid
