### ISSUE TITLE
when use this command "cf bind-service rails-sample test-pubsub-01", get the message below.

### ISSUE THREAD

**Issue by chenwj** [cloudfoundry/cli#266]
using this version of the CLI: 6.6.0-704d304

	and that this error occurred:

		runtime error: invalid memory address or nil pointer dereference

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x4)
		/home/ubuntu/go/src/github.com/cloudfoundry/cli/main/main.go:133 +0xa9
	main.handlePanics()
		/home/ubuntu/go/src/github.com/cloudfoundry/cli/main/main.go:117 +0xfb
	runtime.panic(0x8c38c0, 0x108f3a8)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/commands/service.(*BindService).Run(0xc210207780, 0xc2100668f0)
		/home/ubuntu/go/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/service/bind_service.go:85 +0x8e7
	github.com/cloudfoundry/cli/cf/command_runner.ConcreteRunner.RunCmdByName(0x7f9bbfd21468, 0xc210208d80, 0x7f9bbfd21498, 0xc210042100, 0x97d390, ...)
		/home/ubuntu/go/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/command_runner/runner.go:48 +0x3d0
	github.com/cloudfoundry/cli/cf/command_runner.(*ConcreteRunner).RunCmdByName(0xc2103203e0, 0x97d390, 0xc, 0xc2100668f0, 0x4, ...)
		/home/ubuntu/go/src/github.com/cloudfoundry/cli/tmp/cli_gop

**Comment by goehmen** [comment]
resolved via PR https://github.com/cloudfoundry/cli/pull/317
