### ISSUE TITLE
Typo in the V8 CLI Installation Guide wiki

### ISSUE THREAD

**Issue by RoyceWang** [cloudfoundry/cli#2714]
Just a simple typo at the [wiki](https://github.com/cloudfoundry/cli/wiki/V8-CLI-Installation-Guide#installers-and-compressed-binaries):
In section "Installers and compressed binaries", the sample script is incorrectly typed as "**mv cf8 /user/local/bin**", which the "**user**" should be "**usr**".

**Comment by gururajsh** [comment]
Thank you @RoyceWang for bringing this to our attention. The typo has been fixed.
