### ISSUE TITLE
service key as true JSON

### ISSUE THREAD

**Issue by ThePlenkov** [cloudfoundry/cli#2739]
**The problem**

Cloud Foundry CLI delivers `service-key` command capable to print credentials. Unfortunately printing credentials to the terminal is not always secure. Additionally the response of this CLI is not parseable because of the text `Getting key ... for service instance ... as ...` 

Yes, the solution is very simple now - just removing few lines with a script like this `cf service-key $SK $SK-key | sed -n '2,$p'` but still - since we talk about CLI it would be nice to make it a standard feature with some parameter like --parseable ( like in npm commands )

**Desired solution**
 Instead of the script like this 
`cf service-key $SK $SK-key | sed -n '2,$p' | jq .credentials` 
I'd like to run something like 
`cf service-key $SK $SK-key --parseable | jq .credentials`

**Comment by foxracle** [comment]
it is not common for a modern cli to output only something text for human-readable, but not easy-parse for automation.
Is there anyone know the reasons?

**Comment by a-b** [comment]
We are considering to add machine-readable output such as `--json` or output for non-TTY receivers. As a temporary workaround, you can try `cf curl`. 

I'm resolving this issue for now, but please don't hesitate to reopen it if you have any more questions or comments.
