### ISSUE TITLE
Using `cf create-service` with v8 CLI does not consider current targeted space

### ISSUE THREAD

**Issue by hursey013** [cloudfoundry/cli#2792]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**

Running the following command using v8 CLI:
```
cf create-service cloud-service-account space-deployer my-service-account
```

Results in the following failure:
```
Creating service instance my-service-account in org my-org / space dev as user@domain.com...

Service offering 'cloud-service-account' is provided by multiple service brokers. Specify a broker name by using the '-b' flag.

FAILED
```

When specifying `-b` flag, the command still fails:

```
cf create-service cloud-service-account space-deployer my-service-account -b uaa-credentials-broker

Creating service instance my-service-account in org my-org / space dev as user@domain.com...

Service offering 'cloud-service-account' is provided by multiple service brokers. Specify a broker name by using the '-b' flag.

FAILED
```

**What happened**
It appears that when the v8 CLI makes the call using v3 API it's not considering the current targeted space like the v7 client does with the v2 API queries. This causes the `create-service` command to fail.

When inspecting the underlying API calls, CF CLI v7 makes these requests:
- /v2/spaces/<your space guid>/services?q=label%3Acloud-service-account
- /v2/service_plans?q=service_guid:<service-offering-guid>

So notably it's using the V2 of the cloud controller API, not V3

When using CF CLI v8 to make this request to the CC API V3:
- /v3/service_plans?names=space-deployer&page=1&per_page=50&service_offering_names=cloud-service-account

Which as a non-admin user is returning 3 results for the space-deployer plan, but CF CLI v7 is making this request to CC API V2:

- /v2/service_plans?q=service_guid:<service-offering-guid>

Which only shows one instance of the space-deployer plan

**Expected behavior**
When using either the v7 or v8 CLI, running `create-service` should consider the currently targeted space.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:

- 1 broker with 2 plans - both plans are org scoped and not in all orgs
- User is in 2 or more orgs and v8cli using v3 queries returns dup results x the number of orgs the user is a member of where the plan is scoped
- Adding a space_guids of the current targeted space results in a single result

1. Run `cf create-service cloud-service-account space-deployer my-service-account`
2. See error

**Provide more context**
- Mac OS X Terminal Version 2.13
- cf version 8.7.7+583a09a.2023-12-26
- version of the CC API Release you are on

Possibly related: https://github.com/cloudfoundry/cli/issues/2269

**Comment by johha** [comment]
This issue is fixed with https://github.com/cloudfoundry/cloud_controller_ng/pull/3648 which is part of [CAPI 1.173.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.173.0).
