### ISSUE TITLE
On first login to a new CF, it asks for a space but none exist

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cli#28]
On a fresh Cloud Foundry deployment, there are no usable organizations or spaces yet.

So the new "ops user" experience looks like:

```
$ gcf login -u admin -p eaa139af52343
API endpoint: http://api.107.20.148.206.xip.io
Warning: Insecure http API endpoint detected: secure https API endpoints are recommended

Authenticating...
OK

Select a space:

Space> test
FAILED
Error finding space test
Space test not found
```

**Comment by eduardohl** [comment]
I'm facing this issue, jsut did a fresh installation and now I can't login to it because there are no Orgs or Spaces. I don't know how to proceed, my output is exactly the same as above. What's the solution taken in this case?
