### ISSUE TITLE
cf push does not follow convention that usage is printed

### ISSUE THREAD

**Issue by jchesterpivotal** [cloudfoundry/cli#282]
Most `cf` commands will print usage if you use them without arguments:

Eg:

```
$ cf delete
FAILED
Incorrect Usage.

NAME:
   delete - Delete an app

ALIAS:
   d

USAGE:
   cf delete APP [-f -r]

OPTIONS:
   -f	Force deletion without confirmation
   -r	Also delete any mapped routes
```

But `cf push` breaks this convention:

```
$ cf push
FAILED
Error: App name is a required field
```

But `cf help push` reveals the full usage.

**Comment by camelpunch** [comment]
It's my understanding that this behaviour isn't about to change soon, as `cf push` is so handy for reading everything from the manifest.yml. @goehmen amirite?

**Comment by jchesterpivotal** [comment]
If I have a manifest, I'd still want usage and maybe a hint on what to repair. ("Your manifest.yml defines these apps: foo, bar, baz")

If I don't have a manifest, I'd want usage, like every other command.

**Comment by camelpunch** [comment]
Makes sense to me. You sort of get usage, but in an unconventional format:

```
foobarbaz$ cf push
FAILED
Error: Manifest file is not found in the current directory, please provide either an app name or manifest
```

Since the previous Tracker story had gone to Tracker story heaven, here's a new one: https://www.pivotaltracker.com/story/show/103419480
