### ISSUE TITLE
cf delete-route is confusing

### ISSUE THREAD

**Issue by jchesterpivotal** [cloudfoundry/cli#283]
Here is a dramatic recreation of one interaction with `cf delete-route`. We found it to be a little difficult to understand upon a first encounter.

We wanted to delete the route to the `bcs` app. So:

```
$ cf routes
Getting routes as admin ...

host   domain               apps
bcs    10.244.0.34.xip.io   bcs
```

So far so good.

First attempt to delete a route:

```
$ cf delete-route bcs
FAILED
Domain bcs not found
```

OK, it talks about "domain" and I see that `10.244.0.34.xip.io` is listed under "domain". So:

```
$ cf delete-route 10.244.0.34.xip.io

Really delete the route 10.244.0.34.xip.io?> yes
Deleting route 10.244.0.34.xip.io...
Unable to delete, route '10.244.0.34.xip.io' does not exist.
Endpoint deprecated
```

Doesn't exist? Let me check ...

```
$ cf routes
Getting routes as admin ...

host   domain               apps
bcs    10.244.0.34.xip.io   bcs
```

Well that didn't work. I guess I'll need to find and read the FM:

```
$ cf help delete-route
NAME:
   delete-route - Delete a route

USAGE:
   cf delete-route DOMAIN [-n HOSTNAME] [-f]

OPTIONS:
   -f   Force deletion without confirmation
   -n   Hostname
```

Weird, the brackets on hostname suggest it's optional. Let's try it anyway:

```
$ cf delete-route 10.244.0.34.xip.io -h bcs
NAME:
   delete-route - Delete a route

USAGE:
   cf delete-route DOMAIN [-n HOSTNAME] [-f]

OPTIONS:
   -f   Force deletion without confirmation
   -n   Hostname
```

Hm, I'm fully specifying the hostname with an `-h` and ... oh. It's not aitch. It's en.

I got confused because '-h' and '-n' are very very similar visually. I was expecting single-letter arguments to be mnemonic with the full word ("hostname", not "nostname"). I guess it's for "name"? But the output of `cf route` clearly calls it "host", the help refers to it as "hostname".

I guess it sees `-h` as "help", which is why I didn't get the "FAILED Incorrect Usage" message.

So:

```
$ cf delete-route 10.244.0.34.xip.io -n bcs

Really delete the route bcs.10.244.0.34.xip.io?> yes
Deleting route bcs.10.244.0.34.xip.io...
OK
Endpoint deprecated
```

I guess "endpoint deprecated" means it's gone. Let me double-check:

```
$ cf routes
Getting routes as admin ...

host   domain   apps
No routes found
```

\o/

---

We think some hint text might have helped. Eg:

```
$ cf delete-route bcs
FAILED
Domain bcs not found
Did you mean:
    cf delete-route 10.244.0.34.xip.io -n bcs
```

**Comment by tedhoganacn** [comment]
I just encountered this same issue. Googled and I am here. FYI

**Comment by SugandhaAgrawal** [comment]
Use of cf delete-route --help explains:
NAME:
   delete-route - Delete a route

USAGE:
   cf delete-route DOMAIN [--hostname HOSTNAME] [--path PATH] [-f]

EXAMPLES:
   cf delete-route example.com                              # example.com
   cf delete-route example.com --hostname myhost            # myhost.example.com
   cf delete-route example.com --hostname myhost --path foo # myhost.example.com/foo

OPTIONS:
   -f                  Force deletion without confirmation
   --hostname, -n      Hostname used to identify the route
   --path              Path used to identify the route

So then you have to explicitly mention your domain name and hostname and then it worked for me.

**Comment by Malu44** [comment]
Has the same issue - but Google is your friend. And here I'm!

**Comment by dkoper** [comment]
@Malu44 @tedhoganacn 

I missed your updates to this issue. @jchesterpivotal described his initial experience encompassing several issues. I understood the major ones were addressed. Can you be specific on "the same issue" you are having, ideally open a new issue detailing it so we get a new story in our tracker to prioritize?

Cheers,
Dies Koper
CF CLI PM

**Comment by tedhogan** [comment]
@dkoper the --help still lists the Hostname argument as optional and with -n which can be confusing to the inexperienced. 

This is what I see when I type cf delete-route --help from VERSION 6.16.1+924508c-2016-02-26:
cf delete-route DOMAIN [--hostname HOSTNAME] [--path PATH] [-f]

As a user, I have a route to my app. I want to delete the route to my app. My first thought is "cf delete-route <routeName>" should work. It doesn't, so I look up the help and it tells me that I need a DOMAIN argument, but that the HOSTNAME (what in my mind I call my app) is optional. So, I Google, end up here and see:

cf delete-route 10.244.0.34.xip.io -n bcs

In the comments and bingo, I get it. 

At first glance, I expected the most important argument of that command to be the HOSTNAME and I expected the DOMAIN to be implied and optional. To me, this would be more natural. So, I find the current way that the command is setup to be the opposite from what I would expect.

Hope this helps.
