### ISSUE TITLE
cf files APP [-i INSTANCE] [PATH] is confusing & not according to the cf docs

### ISSUE THREAD

**Issue by SrinivasChilveri** [cloudfoundry/cli#294]
according to CF docs.....cf v6 commands behave consistently and logically:
•Required arguments never have flags.
•Optional arguments always have flags.
•When there is more than one required argument, their order matters.
•Optional arguments can be provided in any order.

but htipl@cf5:~/cf-downloads/cf-env$ cf help files
 NAME:
 files - Print out a list of files in a directory or the contents of a specific file
 ALIAS:
 f
 USAGE:
 cf files APP [-i INSTANCE] [PATH]
 OPTIONS:
-i Instance 

htipl@cf5:~/cf-downloads/cf-env$ cf apps
 Getting apps in org SriniOrg / space SriniSpace as admin...
 OK
 name requested state instances memory disk urls
 CfApp started 1/1 256M 1G cfapp.10.244.0.34.xip.io

so if we observe 1)htipl@cf5:~/cf-downloads/cf-env$ cf files CfApp
 Getting files for app CfApp in org SriniOrg / space SriniSpace as admin...
 OK
 .bash_logout 220B
 .bashrc 3.0K
 .profile 675B
 app/ -
 logs/ -
 run.pid 3B
 staging_info.yml 217B
 tmp/ -

 2)htipl@cf5:~/cf-downloads/cf-env$ cf files CfApp logs
 Getting files for app CfApp in org SriniOrg / space SriniSpace as admin...
 OK
 staging_task.log 1.0K

 3)htipl@cf5:~/cf-downloads/cf-env$ cf files CfApp -i 0 logs
 FAILED
 App logs not found

 4)htipl@cf5:~/cf-downloads/cf-env$ cf files CfApp logs -i 0
 Getting files for app CfApp in org SriniOrg / space SriniSpace as admin...
 OK
 staging_task.log 1.0K

So here are my issues
 1)[PATH] is a kind of optional param when we don't give it takes as root "/"...here its againest cf document Optional arguments always have flags 
 2) when we provide [PATH] its behaviour is as required parameter because we should provide it before -i option if not it will fail as shown above
 3)it is against the cf-docs "Optional arguments always have flags" ,"When there is more than one required argument, their order matters".

I feel we have to make the [PATH] either mandatory as 'cf files APP PATH [-i instance]' or optional as 'cf files APP [-p PATH] [-i instance]'
I feel better to make it mandatory so that user can give what ever he wants.
cf experts whats your opinion?
I can change the modifications and do the PR based on your suggestion.

**Comment by goehmen** [comment]
Fixed help to reflect the required order of args/flags:

± sl+dr |master ✓| → cf help files
NAME:
   files - Print out a list of files in a directory or the contents of a specific file

ALIAS:
   f

USAGE:
   cf files APP_NAME [PATH] [-i INSTANCE]

OPTIONS:
   -i 	Instance
