### ISSUE TITLE
update-space-quota does not fail if quota cannot be changed

### ISSUE THREAD

**Issue by I554344** [cloudfoundry/cli#3037]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
I'm using `cf update-space-quota` to increase space quota in an org which has memory limit set by administrators of the CF runtime.

**What happened**
`cf update-space-quota` does not fail when CF runtime has a hard limit enforced by administrators. 

**Expected behavior**
`cf update-space-quota` should fail if quota was not changed.

**Exact Steps To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Log in to a CF space where runtime quota has hard limit of 210GB
2. `cf update-space-quota` and set the new quota to 220GB
3. See that the command finishes without any errors and without changing the quota.

**Provide more context**
- Mac OS X 14.5 (23F79)
- cf version 8.6.1+b5a352a.2023-02-27

**Comment by gururajsh** [comment]
Hello @I554344 ,

It is allowed to set space quota value higher than org quota but while pushing app an, the lower of the two will be checked. For ex, If org quota memory limit is 1G and space quota memory limit is 2G and I try to push an app with 2G memory, it fails stating `organization's memory limit exceeded` .
