### ISSUE TITLE
Clarify description for `cf restart-app-instance` command

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cli#3059]
**What's the user value of this feature request?**
The current description for the `restart-app-instance` command is confusing. Unlike the regular `cf restart` command, this command does not update the app environment (environment variables, service bindings, app renaming, etc.) for the instance.

Current help text:
```
cf restart-app-instance -h
NAME:
   restart-app-instance - Terminate, then instantiate an app instance

USAGE:
   cf restart-app-instance APP_NAME INDEX [--process PROCESS]

OPTIONS:
   --process      Process to restart (Default: web)
```

**Who is the functionality for?**
App developers / app operators.

**How often will this functionality be used by the user?**
Whenever they wish to learn more about `cf restart-app-instance`.

**Who else is affected by the change?**
No one, it merely clarifies existing behavior.

**Is your feature request related to a problem? Please describe.**
Users run `cf restart-app-instance` and expect it to behave like `cf restart`. When it doesn't they are surprised and confused.

**Describe the solution you'd like**
Update the description to the command to something like:

```
Stop, then start application instance without updating application environment
```

(thanks @Benjamintf1 for talking through suggestions with me)

Example new help text:
```
cf restart-app-instance -h
NAME:
   restart-app-instance - Stop, then start application instance without updating application environment

USAGE:
   cf restart-app-instance APP_NAME INDEX [--process PROCESS]

OPTIONS:
   --process      Process to restart (Default: web)
```

**Additional context**
Under the hood Cloud Controller calls the [RetireActualLRP](https://pkg.go.dev/github.com/cloudfoundry/bbs#Client) endpoint on BBS.

```
// Shuts down the ActualLRP matching the given ActualLRPKey, but does not modify the desired state
	RetireActualLRP(logger lager.Logger, traceID [string](https://pkg.go.dev/builtin#string), key *[models](https://pkg.go.dev/code.cloudfoundry.org/bbs/models).[ActualLRPKey](https://pkg.go.dev/code.cloudfoundry.org/bbs/models#ActualLRPKey)) [error](https://pkg.go.dev/builtin#error)
```

**Comment by gururajsh** [comment]
Hi @tcdowney ,

I have added this issue to our tracker and will let you know when it's complete.

**Comment by gururajsh** [comment]
PRs are in. This change should be available with next release.
