### ISSUE TITLE
update V8-CLI-Installation-Guide for Ubuntu (wiki)

### ISSUE THREAD

**Issue by vchrisb** [cloudfoundry/cli#3210]
PRs to the wiki can't be created.

**What's the user value of this feature request?**
Update installation guide for Ubuntu

**Who is the functionality for?**
Ubuntu/Debian Users

**How often will this functionality be used by the user?**
when install cli

**Who else is affected by the change?**
no

**Is your feature request related to a problem? Please describe.**
`apt-key` tooling is deprecated, which is used in https://github.com/cloudfoundry/cli/wiki/V8-CLI-Installation-Guide for Ubuntu/Debian.

**Describe the solution you'd like**
`apt-key` is deprecated since quite a while. The following steps are supported with Ubuntu 18+:

```
# ...first add the Cloud Foundry Foundation public key and package repository to your system
wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo gpg --dearmor -o /usr/share/keyrings/cli.cloudfoundry.org.gpg
echo "deb [signed-by=/usr/share/keyrings/cli.cloudfoundry.org.gpg] https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
# ...then, update your local package index, then finally install the cf CLI
sudo apt-get update
sudo apt-get install cf8-cli
```

**Comment by gururajsh** [comment]
Hello.. Thank you for bringing this to our attention. Have updated the wiki instructions.
