### ISSUE TITLE
cf files command error

### ISSUE THREAD

**Issue by jamee** [cloudfoundry/cli#326]
When I type
$ cf help files
It says:
USAGE:
   cf files APP [-i INSTANCE] [PATH]

But
$  cf files hlj -i 0 "/app"
FAILED
App /app not found
FAILED
App /app not found

If I change to:
$ cf files "/app" -i 0 "hlj"
OK

.java-buildpack/                             -
.java-buildpack.log                      80.9K
META-INF/                                    -
WEB-INF/                                     -
index.jsp                                  52B

My cli version:
VERSION:
6.8.0-b15c536

cf version 6.8.0-b15c536-2014-12-10T19:26:38+00:00

**Comment by SrinivasChilveri** [comment]
Hi @jamee @goehmen 
Currently In cf files command  if cf-user wants to give [PATH]  then we should give before optional parameter then only it works(cf files hlj -i 0 "/app"   should be  cf files hlj  "/app  -i  0").This command is not according to cf-cli docs. Please do refer the https://www.pivotaltracker.com/story/show/82534256

**Comment by goehmen** [comment]
help fixed
