### ISSUE TITLE
Improve cf push usage instructions

### ISSUE THREAD

**Issue by sanjeevchopra** [cloudfoundry/cli#327]
cf version :   6.8.0-b15c536-2014-12-10T23:34:29+00:00

'cf push APP.....'  in the 3rd line below - wouldn't it be better to rename to 'cf push APPNAME ...' ?
"
USAGE:
   Push a single app (with or without a manifest):
   cf push APP [-b BUILDPACK_NAME] [-c COMMAND] [-d DOMAIN] [-f MANIFEST_PATH]
   [-i NUM_INSTANCES] [-k DISK] [-m MEMORY] [-n HOST] [-p PATH] [-s STACK] [-t TIMEOUT]
   [--no-hostname] [--no-manifest] [--no-route] [--no-start]
"

**Comment by goehmen** [comment]
Done

USAGE:
   Push a single app (with or without a manifest):
   cf push APP_NAME [-b BUILDPACK_NAME] [-c COMMAND] [-d DOMAIN] [-f MANIFEST_PATH]
