### ISSUE TITLE
How to login on 2 different cloud foundary api at the same time from same machine without conflict ?

### ISSUE THREAD

**Issue by marshell08** [cloudfoundry/cli#330]
If i try to login to cloud foundry using the cli command that is hosted on 2 different location (https://api.stage1.ng.bluemix.net & https://api.stage1.eu-gb.bluemix.net ) but from  2 different session on the same machine they seem to conflict each other. For instance it would pick one of them mostly the one that ran first therefore if i try to push an app on https://api.stage1.eu-gb.bluemix.net it would rather push it on https://api.stage1.ng.bluemix.net

How can i make them run independently at the same time ? I don't want them to conflict. Is there a way to make them run on different thread ? Please suggest 

Session 1:
cf login -a https://api.stage1.ng.bluemix.net -u xyz@gmail.com -p xyz -o XYZ_ORG  -s test
cf push -f manifest.yml

Session2:
cf login -a https://api.stage1.eu-gb.bluemix.net -u xyz@gmail.com -p xyz -o XYZ_ORG  -s test
cf push -f manifest.yml

Tried on Linux CentOS 6.0.5 as root user

**Comment by goehmen** [comment]
There are a couple options here:

1. CF_HOME environment variable: When you want to use the cf client as part
of an automated workflow running multiple jobs in parallel, manipulating
different spaces, you can leverage the CF_HOME environment variable. This
allows you to have multiple instances of the cli running in parallel as
different users. Each instance can then be used to target a desired
org/space that will be specific to that CF_HOME.

2. cfenv: You can use cfenv [0] which is based on (and cloned from) rbenv -
see this thread from cfenv author Ben Hale on the CF Google Group [1]

[0] https://github.com/nebhale/cfenv

[1]
https://mail.google.com/mail/u/0/?pli=1#search/multiple+cf_homes/1465d4ca71b4a3c1

**Comment by goehmen** [comment]
@marshell08 I'm going to close this issue b/c I think the above info answers your questions, but please reopen if the need arises.

**Comment by josephharding** [comment]
@goehmen thanks for this, very nice little feature!

**Comment by lampardchelsea** [comment]
Just want to re-post the solution since its only able to observe on cache page:
Cloud Foundry: Working with Applications in Multiple Spaces
http://webcache.googleusercontent.com/search?q=cache:Obcp5GpZJYkJ:www.ecsteam.com/cloud-foundry-working-with-applications-in-multiple-spaces+&cd=1&hl=en&ct=clnk&gl=us
the critical point is setup CF_HOME for each child thread which will create corresponding config.json file for each thread's cf commands to run with, hence no conflict or race condition will generate
