### ISSUE TITLE
[plugins] Allow for plugins to be pre-installed/shared across users

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cli#332]
We're trying to bundle `cf` and various admin plugins (plus the `uaac`) into a traveling-cf-admin installer (installing `uaac` is annoying for non-ruby devs; see https://github.com/cloudfoundry-community/traveling-bosh for the traveling-bosh example)

In the initial `cf plugins` implementation, it is assumed that a single user will download a plugin and run `cf install-plugin` within their `$HOME` environment.

We'd like to be able to bundle plugins with the `cf` command when we install that for a shared machine that may have many unix user accounts.

**Comment by drnic** [comment]
See description in #331 also

**Comment by goehmen** [comment]
leveraging $PLUGIN_HOME should enable many unix user accts on a single machine to share plugins.  Docs :  
```
Changing the Plugin Directory
By default, the cf CLI stores plugins in $HOME/.cf/plugins on your workstation. To change the root directory of this path from
 $HOME, set the CF_PLUGIN_HOME environment variable. The cf CLI appends .cf/plugins to the CF_PLUGIN_HOME path that 
you specify and stores plugins in that location.

For example, if you set CF_PLUGIN_HOME to /my-folder, cf CLI stores plugins in /my-folder/.cf/plugins.
```

**Comment by drnic** [comment]
@goehmen would this allow shared/pre-installed plugins + user-installed plugins? Or just one or the other?

**Comment by camelpunch** [comment]
@goehmen do you have an answer for @drnic, or shall we just close this?

**Comment by krishicks** [comment]
@drnic: CF_PLUGIN_HOME will be used as the single source for plugins; there is no splitting of shared and user plugins.

I'm going to close this for now; please let me know if you want to discuss it further.

**Comment by dkoper** [comment]
We'll take a note of the suggestion and wait to see if this becomes a common request.
