### ISSUE TITLE
Help output for new `cf create-app-manifest` doesn't name manifest file correctly

### ISSUE THREAD

**Issue by qanx** [cloudfoundry/cli#335]
The help output for `cf create-app-manifest` indicates that the generated yml file will be named `<app-name>-manifest.yml`, but after testing the command the default file name is `manifest_generated.yml`.

**Comment by simonleung8** [comment]
This issue has been fixed in the [newest version](https://github.com/cloudfoundry/cli/releases) of CLI, manifest will be correctly named to <app-name>-manifest.yml

Thanks
