### ISSUE TITLE
Pushing multiple times an app with a random route maps new routes at each push

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#337]
The random-word support in the manifest is great, however, when I push multiple times the same app with this manifest, I end up with extra random routes (one for each push).

```
$ cat manifest.yml
---
applications:
- name: spring-travel
  host: spring-travel-${random-word}
[...]
```

It might feel more natural for the cli to not try to create new random routes if the app already exists and one of the existing route maps the route specs, including random word.

**Comment by simonleung8** [comment]
The random-word function is designed to return a random word from a predefined list every time it is called. It is probably best not to use this function if you desire to create a single app route and push to it multiple times. 
I am closing this issue, feel free to reopen if needed
