### ISSUE TITLE
issue with home directory 

### ISSUE THREAD

**Issue by Kamaraju333** [cloudfoundry/cli#340]
Aww shucks.

   Something completely unexpected happe
   Please file this bug : https://github
   Tell us that you ran this command:

           cf

   using this version of the CLI:

           6.9.0-620f841

   and that this error occurred:

           open Z:\.cf\plugins\config.js

   and this stack trace:

           goroutine 1 [running]:
   main.generateBacktrace(0xc0840021c0,
           C:/GoAgent/pipelines/Win64-Un
   main.handlePanics(0x1915d8, 0xc084049
           C:/GoAgent/pipelines/Win64-Un
   runtime.panic(0x90be40, 0xc084096690)
           C:/Users/ADMINI~1/AppData/Loc
   main.func·002(0x19fa08, 0xc084096690)
           C:/GoAgent/pipelines/Win64-Un
   github.com/cloudfoundry/cli/cf/config
           C:/GoAgent/pipelines/Win64-Un
   sync.(*Once).Do(0xc08421b4e0, 0xc0842
           C:/Users/ADMINI~1/AppData/Loc
   github.com/cloudfoundry/cli/cf/config
           C:/GoAgent/pipelines/Win64-

**Comment by jberkhahn** [comment]
Hi there,

It looks like the CLI crashed while trying to read your plugin configuration file (Z:\.cf\plugins\config.js).

Could you please post the contents of that file so we could try and figure out what went wrong? Additionally, it looks like you only posted a partial stack trace. If there's any more that you could post it would a great help.

**Comment by jberkhahn** [comment]
Hey there,

We haven't heard back from you so we're going to assume everything is resolved on your end. Please feel free to reopen if you continue to experience any issues.
