### ISSUE TITLE
unmap route - app still accessible

### ISSUE THREAD

**Issue by sklevenz** [cloudfoundry/cli#342]
unmap-route doesn't work as expected if scale i > 1

Test Case:

cf scale myapp -i 1
cf unmap-route myapp mydomain.com -n myhost
curl http://myhost.mydomain.com => 404 (expeceted)

=> the route is gone 

cf scale myapp -i 5
cf unmap-route myapp mydomain.com -n myhost
curl http://myhost.mydomain.com => 200 (not expected)
// wait a while
curl http://myhost.mydomain.com => 200 (not expected)

=> the route doesn't go away 

discussion: https://groups.google.com/a/cloudfoundry.org/forum/#!mydiscussions/vcap-dev/mPF4uwvr_7w

---
cf release: 195
cf version 6.8.0-b15c536-2014-12-10T23:34:29+00:00

**Comment by simonleung8** [comment]
hi, are you see this in bosh-lite only or also other environment?

**Comment by goehmen** [comment]
CLI team was able to repro in bosh-lite not in any other env.  Closing - please reopen if you can provide details.
