### ISSUE TITLE
plugins.cloudfoundry.org has cert error with https

### ISSUE THREAD

**Issue by jbayer** [cloudfoundry/cli#350]
https fails, but http is ok

```
$ cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org

FAILED
There is an error performing request on 'https://plugins.cloudfoundry.org/list': %!(EXTRA string=Get https://plugins.cloudfoundry.org/list: x509: certificate is valid for *.cfapps.io, cfapps.io, not plugins.cloudfoundry.org)
$ cf add-plugin-repo CF-Community http://plugins.cloudfoundry.org

OK
http://plugins.cloudfoundry.org/list added as 'CF-Community'
```

**Comment by jbayer** [comment]
acceptable work-around is to use plugins.cfapps.io

```
dig plugins.cloudfoundry.org

; <<>> DiG 9.8.3-P1 <<>> plugins.cloudfoundry.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21926
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;plugins.cloudfoundry.org.	IN	A

;; ANSWER SECTION:
plugins.cloudfoundry.org. 299	IN	CNAME	plugins.cfapps.io.
plugins.cfapps.io.	59	IN	A	54.85.213.36
plugins.cfapps.io.	59	IN	A	54.85.197.113

;; Query time: 132 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Feb 12 17:28:55 2015
;; MSG SIZE  rcvd: 105
$ cf add-plugin-repo CF-Community https://plugins.cfapps.io

OK
https://plugins.cfapps.io/list added as 'CF-Community'
```

**Comment by goehmen** [comment]
Glad there is a work around but let's get this fixed ASAP.  Simon is on PTO
but Jonathan is available.

I bumped this to top of BL. Let's point it in standup at 9:15 and get it
fixed.

Thanks all for taking care w/o me.

G

On Thursday, February 12, 2015, James Bayer <notifications@github.com>
wrote:

> acceptable work-around is to use plugins.cfapps.io
>
> dig plugins.cloudfoundry.org
>
> ; <<>> DiG 9.8.3-P1 <<>> plugins.cloudfoundry.org
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21926
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0
>
> ;; QUESTION SECTION:
> ;plugins.cloudfoundry.org.  IN  A
>
> ;; ANSWER SECTION:plugins.cloudfoundry.org. 299   IN  CNAME   plugins.cfapps.io.plugins.cfapps.io.  59  IN  A   54.85.213.36plugins.cfapps.io.  59  IN  A   54.85.197.113
>
> ;; Query time: 132 msec
> ;; SERVER: 8.8.8.8#53(8.8.8.8)
> ;; WHEN: Thu Feb 12 17:28:55 2015
> ;; MSG SIZE  rcvd: 105
> $ cf add-plugin-repo CF-Community https://plugins.cfapps.io
>
> OKhttps://plugins.cfapps.io/list added as 'CF-Community'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/cli/issues/350#issuecomment-74190418>.
>


-- 
Greg Oehmen
Cloud Foundry Product Manager
415.205.6596

**Comment by goehmen** [comment]
Will do.

**Comment by thansmann** [comment]
I double-checked and we don't have a 'cloudfoundry.org' ssl cert (we've got .com). Is it worth getting one?

**Comment by jberkhahn** [comment]
This has been fixed, closing the issue.
