### ISSUE TITLE
CF CLI execution , DOS window opens but closes immediatly

### ISSUE THREAD

**Issue by vasuram** [cloudfoundry/cli#352]
I installed CF V6.10 on Windows 7 64-bit machine. Install finishes fine. When try to execute CF command from the DOS prompt ( after navigating to c:..\cloud foundry\), a new window opens, I see few lines flashing , but the new window closed immediately. 
Vasu Ram
vasu_ram@yahoo.com

**Comment by simonleung8** [comment]
Does it happen in other directory other than c:...\cloud foundry? CF itself doesn't open new terminals, maybe something else is going on here.

**Comment by vasuram** [comment]
It was a problem from my side. 
I thought, I closed this by updating my original post.
Sorry.
RegardsVasu Ram 

     On Thursday, March 12, 2015 4:33 PM, Simon Leung <notifications@github.com> wrote:
   

 Does it happen in other directory other than c:...\cloud foundry? CF itself doesn't open new terminals, maybe something else is going on here.—

**Comment by singhanuradha** [comment]
Even I am facing the same issue. the cf CLI is getting opened and is getting closed immediately. I have simple installed the cf-cli-installer-6.22.2
