### ISSUE TITLE
cf -v returns "Aww shucks." when CF_HOME is set and HOMEDRIVE's drive does not exist

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/cli#355]
On my Windows 7 machine, HOMEDRIVE defaults to a remote drive mapped as I: at the office.
So at home it maps to a drive that does not exist.
Following the documentation, I set CF_HOME before running cf.

1. Why does HOMEDRIVE overrule the documented CF_HOME?
2. Can cf -v at least display its own version number before it bombs out loading the plugins' version numbers? (or maybe it should just ignore the error - clearly I have no plugins installed)
```
c:\>set CF_HOME=c:\.cf

c:\>cf -v


        Aww shucks.

        Something completely unexpected happened. This is a bug in cf.
        Please file this bug : https://github.com/cloudfoundry/cli/issues
        Tell us that you ran this command:

                cf -v

        using this version of the CLI:

                6.10.0-b78bf10

        and that this error occurred:

                open i:\.cf\plugins\config.json: The system cannot find the path specified.

        and this stack trace:

                goroutine 1 [running]:
        main.generateBacktrace(0xc084003640, 0x2)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:174 +0xac
        main.handlePanics(0x1816b0, 0xc084047cc0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:158 +0x126
        runtime.panic(0x91c880, 0xc0840a9360)
                C:/Users/ADMINI~1/AppData/Local/Temp/2/makerelease155988687/go/src/pkg/runtime/panic.c:248 +0x11b
        main.func·002(0x181810, 0xc0840a9360)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:90 +0x4c
        github.com/cloudfoundry/cli/cf/configuration/plugin_config.func·003()
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/configuration/plugin_config/plugin_config.go:7
1 +0x86
        sync.(*Once).Do(0xc08421df90, 0xc084234760)
                C:/Users/ADMINI~1/AppData/Local/Temp/2/makerelease155988687/go/src/pkg/sync/once.go:40 +0x9d
        github.com/cloudfoundry/cli/cf/configuration/plugin_config.(*PluginConfig).init(0xc084218e00)
                C:/GoAgent/pipelines/Win64-
```

**Comment by simonleung8** [comment]
@dkoper You are right to set the CF_HOME, however, CF_PLUGIN_HOME has to be set to a valid location as well. Maybe this is not clearly documented as this is a new feature, can you point us to the documentation you were following and we will make sure it is updated.

Thanks

**Comment by goehmen** [comment]
Wouldn't it make sense to set cf_plugin_home=$cf_home by default to
eliminate this program?

On Wednesday, March 18, 2015, Simon Leung <notifications@github.com> wrote:

> @dkoper <https://github.com/dkoper> You are right to set the CF_HOME,
> however, CF_PLUGIN_HOME has to be set to a valid location as well. Maybe
> this is not clearly documented as this is a new feature, can you point us
> to the documentation you were following and we will make sure it is updated.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/cli/issues/355#issuecomment-83190429>.
>


-- 
Greg Oehmen
Cloud Foundry Product Manager
415.205.6596

**Comment by simonleung8** [comment]
@goehmen That will create another problem, users who set CF_HOME will lose access to all plugins installed in the $HOME directory, we will have to give more thoughts into this.

Maybe we only set default to CF_HOME if $user_home is not a valid directory.

**Comment by jberkhahn** [comment]
This will be addressed with bug: https://www.pivotaltracker.com/story/show/90652456
We'll let you know when we've figured this out.

**Comment by camelpunch** [comment]
The bug that @jberkhahn mentioned got fixed. Please re-open if this is still a problem.
