### ISSUE TITLE
Allow multiple domains to be specified in a manifest

### ISSUE THREAD

**Issue by vito** [cloudfoundry/cli#358]
I have the following route configuration that I'd like to be able to push via a manifest for a single app:

* foo.ci
* foo-ci.org
* foo-ci.net
* foo-ci.com
* www.foo.ci
* www.foo-ci.org
* www.foo-ci.net
* www.foo-ci.com

As far as I can tell this is not doable with today's manifests, which only support a single domain (but with many hosts).

**Comment by hhercules** [comment]
So see what with version https://github.com/cloudfoundry/cli/releases/tag/v6.11.0 multiple domains allowed, but even with latest the generation of manifest only captures one domain. 

So I can define app like this:


---
applications:
- name: myapp
  memory: 2048M
  instances: 1
  timeout: 180
  host: myapp
  domains:
  - mydomain.com
  - mydomain2.com
  path: build/libs/my.war

But generation gives you this:
cf create-app-manifest myapp

---
applications:
- name: condosafe
  memory: 2048M
  instances: 1
  timeout: 180
  host: condosafe-sa
  domain: corelogic.com
  services:

**Comment by camelpunch** [comment]
Closing, as generation would be another Issue. Feel free to create one if it's still of concern.
