### ISSUE TITLE
cf files APP_NAME fails with message: no such host

### ISSUE THREAD

**Issue by johnpfield** [cloudfoundry/cli#362]
The cf files command fails with an error that seems to indicate that the API endpoint / hostname specified in the HTTP GET request is not properly formed / dereferenced.

Context:  I successfully created a service instance, pushed an app, bind a service to app, and so on. I can also successfully do a cf logs command.  So, in general, things appear to be working.  However, the "cf files" command fails.

I am using  

VERSION:
6.10.0-b78bf10

cf version 6.10.0-b78bf10-2015-02-11T22:25:45+00:00 

My CLI client is running on OS-X 10.9.5

And I am pointing at a CF elastic runtime v1.3.4.0

Error message:  

John-Field-MacBook-Pro:ptm jfield$ cf files ptm 
Getting files for app ptm in org psemc / space development as jfield@pivotal.io...
FAILED
Error performing request: 
Get https://f4c8d58905a841fd97236ce510287c0e.pcf.laas.lab.emc.com/instance_paths/2dcc8166c5e3487ab65e8bbcd978b118?hmac=...truncated...43c0aecc74d2c0d87cd948&path=&timestamp=1424791080: dial tcp: lookup f4c8d58905a841fd97236ce510287c0e.pcf.laas.lab.emc.com: no such host

NOTE: that if I create my own request using curl command line to go to the API endpoint, then it works.  Here I changed the target of the GET request to be the API endpoint, but I leave the HTTP Host: header to be the indicated instance name:

John-Field-MacBook-Pro:ptm jfield$ curl -k --get https://api.pcf.laas.lab.emc.com/instance_paths/2dcc8166c5e3487ab65e8bbcd978b118 
--header "Host: f4c8d58905a841fd97236ce510287c0e.pcf.laas.lab.emc.com" 
--header "Accept: application/json"  
--header "User-Agent: go-cli 6.10.0-b78bf10 / darwin" 
--data "hmac=<truncated>&path=&timestamp=1424790459"

.bash_logout                              220B
.bashrc                                       3.0K
.profile                                       675B
app/                                            -
logs/                                            -
run.pid                                        3B
staging_info.yml                        761B
tmp/                                             -
John-Field-MacBook-Pro:ptm jfield$

**Comment by simonleung8** [comment]
The `/instance_path` endpoint is a redirect from hitting `/v2/apps/:app_guid/instances/:instance_index/files` endpoint, which come from CC. I have tried to use curl to hit the Host from the redirected request and everything works fine, the host is valid.
```
curl -k --get https://b3af3e89574c488697539d3acbe12960.run.pivotal.io//instance_paths/8bc2992d27854fc1bb2eb7ec03d3f202 --header "User-Agent: go-cli 6.10.0-b78bf10 / darwin" --header "Accept: application/json" --data "hmac=&path=&timestamp=1424823088"
.bash_logout                              220B
.bashrc                                   3.0K
.profile                                  675B
app/                                         -
logs/                                        -
run.pid                                     3B
staging_info.yml                          193B
tmp/                                         -
```

Is this problem persistent for you? And do you get this issue from all the apps?

**Comment by johnpfield** [comment]
Thanks for checking on this.  Yes it is persistent, and yes it is for all
apps.

Following your reply I did some more research and testing and I think I
have located the root cause.  This is *NOT* a problem with the cf cli.

The issue exists only on my VPN connections. The VPN client app applies
security policies and re-configures my local machine to limit hostname
lookups to a pair of VPN-specific DNS servers. Those DNS servers returned
"no such host" when asked about that host in my PCF subdomain. Basically,
it's a feature :-)  There are a number of potential solutions/workarounds,
but the this is not a cf cli problem.

Sorry for the distraction.  Perhaps this thread will help a future VPN user.

Thanks,
John


On Tue, Feb 24, 2015 at 7:29 PM, Simon Leung <notifications@github.com>
wrote:

> The /instance_path endpoint is a redirect from hitting
> /v2/apps/:app_guid/instances/:instance_index/files endpoint, which come
> from CC. I have tried to use curl to hit the Host from the redirected
> request and everything works fine, the host is valid.
>
> curl -k --get https://b3af3e89574c488697539d3acbe12960.run.pivotal.io//instance_paths/8bc2992d27854fc1bb2eb7ec03d3f202 --header "User-Agent: go-cli 6.10.0-b78bf10 / darwin" --header "Accept: application/json" --data "hmac=&path=&timestamp=1424823088"
> .bash_logout                              220B
> .bashrc                                   3.0K
> .profile                                  675B
> app/                                         -
> logs/                                        -
> run.pid                                     3B
> staging_info.yml                          193B
> tmp/                                         -
>
> Is this problem persistent for you? And do you get this issue from all the
> apps?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/cli/issues/362#issuecomment-75881483>.
>



-- 

John P. Field | Security Architect | Pivotal Services @ EMC

Direct: (908) 962-3394 | jfield@ <jfield@gopivotal.com>pivotal.io

**Comment by simonleung8** [comment]
Glad you found the root cause of the issue, I am sure this will help others with similar issue in the future.

thanks
