### ISSUE TITLE
cf depends on network drive, fails when disconnected H:\.cf\plugins\config.json: The network path was not found.

### ISSUE THREAD

**Issue by MJonker** [cloudfoundry/cli#367]
I have tried to use CF_HOME as an environment variable, but no luck.

How to tell CF to start fresh ?

C:\Windows\system32>cf

        Aww shucks.

        Something completely unexpected happened. This is a bug in cf.
        Please file this bug : https://github.com/cloudfoundry/cli/issues
        Tell us that you ran this command:

                cf

        using this version of the CLI:

                6.10.0-b78bf10

        and that this error occurred:

                open H:\.cf\plugins\config.json: The network path was not found.

        and this stack trace:

                goroutine 1 [running]:
        main.generateBacktrace(0xc084006180, 0x1)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/main/main.go:174 +0xac
        main.handlePanics(0x1c15d8, 0xc08404abe0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/main/main.go:158 +0x126
        runtime.panic(0x91c880, 0xc0840a6300)
                C:/Users/ADMINI~1/AppData/Local/Temp/2/makerelease155988687/go/s
rc/pkg/runtime/panic.c:248 +0x11b
        main.func·002(0x1c1738, 0xc0840a6300)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/main/main.go:90 +0x4c
        github.com/cloudfoundry/cli/cf/configuration/plugin_config.func·003()
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/cf/configuration/plugin_config/plugin_config.go:71 +0x86
        sync.(*Once).Do(0xc0841fc930, 0xc084233760)
                C:/Users/ADMINI~1/AppData/Local/Temp/2/makerelease155988687/go/s
rc/pkg/sync/once.go:40 +0x9d
        github.com/cloudfoundry/cli/cf/configuration/plugin_config.(*PluginConfi
g).init(0xc0841dcfc0)
                C:/GoAgent/pipelines/Win64-

C:\Windows\system32>

**Comment by simonleung8** [comment]
Hi, to change the default location for plugins config and binaries, use `CF_PLUGIN_HOME` environment variable.
