### ISSUE TITLE
CLI Test Suite is not handling .coverprofile file.

### ISSUE THREAD

**Issue by savitaashture** [cloudfoundry/cli#371]
When we run the ./bin/test in CLI with -cover option it will generate a file <packagename.coverprofile> in the respective packages.
after that if we run agian ./bin/test without -cover option the testsuite is failing and it is giving error as follow:
```
Failure [0.048 seconds]
factory [It] provides the metadata for its commands
/home/cf7/go/src/github.com/cloudfoundry/cli/cf/command_factory/factory_test.go

this file has no corresponding command: commands.coverprofile
Expected
: 0
to equal
: 1
```

I have fixed and ran its working fine.
Fix:
	we should ignore the generated .coverprofile

So we are planning to do PR.
Please give your openion.

**Comment by jberkhahn** [comment]
Hey there. Yep, this is an easy fix. We actually just implemented it ourselves, since it's been a while since you original posted.

Thanks,
