### ISSUE TITLE
cf login -h formatting is missing a newline char within the EXAMPLE section

### ISSUE THREAD

**Issue by joshisa** [cloudfoundry/cli#372]
Notice the missing newline after the fourth example.
{**current**}  cf login -h output
[....]
EXAMPLE:
   cf login (omit username and password to login interactively -- cf will prompt for both)
   cf login -u name@example.com -p pa55woRD (specify username and password as arguments)
   cf login -u name@example.com -p "my password" (use quotes for passwords with a space)
   cf login -u name@example.com -p "\"password\"" (escape quotes if used in password)   **cf login --sso (cf will provide a url to obtain a one-time password to login)**
[....]

{**desired**} cf login -h output
[....]
EXAMPLE:
   cf login (omit username and password to login interactively -- cf will prompt for both)
   cf login -u name@example.com -p pa55woRD (specify username and password as arguments)
   cf login -u name@example.com -p "my password" (use quotes for passwords with a space)
   cf login -u name@example.com -p "\"password\"" (escape quotes if used in password)
   **cf login --sso (cf will provide a url to obtain a one-time password to login)**
[....]

![image](https://cloud.githubusercontent.com/assets/1133849/6493685/550d24d2-c28a-11e4-9608-8d41d6aab238.png)

**Comment by simonleung8** [comment]
Thanks, we will be fixed for next release.
