### ISSUE TITLE
Unable to use 'null' as an admin buildpack name

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/cli#374]
We created a buildpack from github.com/cloudfoundry-incubator/null-buildpack and we named it `null`. When we used the cli to push an app:
```
cf push test -b null
```
the cli's payload used `"buildpack": null` instead of `"buildpack":"null"` in the payload which caused detect to be executed against all buildpacks.

**Comment by simonleung8** [comment]
@sykesm Is there a specific reason to name your buildpack `null`?

We are not sure if we could change the CLI behavior, looking at the code, it specifically look for 'null' and set it to empty string.

https://github.com/cloudfoundry/cli/blob/master/cf/commands/application/push.go#L490

**Comment by sykesm** [comment]
I called it `null` because it was the "null buildpack."  

As for the code, `"null" != null`.  I can't begin to understand why anyone would treat the string as a nil reference.

Ultimately it's your call to figure out what to do but it seems broken.

**Comment by simonleung8** [comment]
I do agree the "null"/"default" usage is not natural, but taking it out will be a breaking change, so we won't be changing the push behavior at this point.

I will close this, feel free to reopen if you want to discuss further.
