### ISSUE TITLE
cf cli hard to uninstall because name not set in Windows Programs and Features

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/cli#376]
On a new Windows 7 machine I installed CF CLI from https://cli.run.pivotal.io/stable?release=windows64&version=6.10.0&source=github-rel.
On Windows, we use "Control Panel\All Control Panel Items\Programs and Features" to list and uninstall applications.
CF CLI is listed as:
```
Name: 6.10.0
Publisher:
Size:
Version: 6.10.0
```
Please correct the name, publisher and size fields.

**Comment by goehmen** [comment]
added installer label so when we start on installer themed work, this will be included.  Closing issue since this is represented in CLI tracker now

**Comment by dkoper** [comment]
This seems to have been resolved since.
