### ISSUE TITLE
include cli name and version in installer, binary releases

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/cli#377]
I regularly download CF CLI releases from e.g. https://cli.run.pivotal.io/stable?release=windows64&version=6.10.0&source=github-rel.
The filename defaults to "installer-windows-amd64.zip".
A month or so later I see this file in my Downloads folder and wonder... installer for what? what version?

The downloadable binary is currently named: cf-windows-amd64.zip

Please consider renaming them (for all OSs):
```
installer-windows-amd64.zip -> cf_cli-6.10.0-windows-amd64-installer.zip
cf-windows-amd64.zip        -> cf_cli-6.10.0-windows-amd64.zip
```

**Comment by jberkhahn** [comment]
Hello there,

We're currently unable to do this as we need the filenames set up a certain way to keep track of our downloads using Google Analytics. Unfortunately this prevents us from changing our naming scheme for the foreseeable future.
