### ISSUE TITLE
with cf cups, CLI is not creating services when JSON is being provided in the command

### ISSUE THREAD

**Issue by thefalconfeat** [cloudfoundry/cli#378]
```
C:\>cf -v                                                    
cf version 6.10.0-b78bf10-2015-02-11T22:26:25+00:00          
                                                             
C:\>cf cups my_service -p '{"key":"value","key2":"value2"}'  
                                                             
'{key:value>
```                                             

CLI is not parsing the input as Json, instead its parsing the whole string by ',' and requesting us to enter value against each of those parsed strings.

**Comment by goehmen** [comment]
Escape the inner double quotes

For windows dos: cf cups my_service -p "{\"key\":\"value\", \"key2\":\"value2\"}"

For window powershell:  cf cups my_service -p '{\"key\":\"value\", \"key2\":\"value2\"}'

**Comment by goehmen** [comment]
I added a story to the CLI backlog to include windows examples in the cf cups/uups help
