### ISSUE TITLE
FakeCliConnection does not match real concurrency behaviour

### ISSUE THREAD

**Issue by argon** [cloudfoundry/cli#380]
We are working on a plugin which should run several CF commands concurrently. We are unable to write tests for this as `FakeCliConnection.CliCommand` is wrapped in a Mutex.

It **is** possible to run commands concurrently when using a real CliConnection, but the test fakes do not match this behaviour.

**Comment by simonleung8** [comment]
Hi, currently running CliConnection is not officially supported, see `Known issues` section at the bottom of the [plugins guide](https://github.com/cloudfoundry/cli/tree/master/plugin_examples#known-issues).

We should be addressing this issue in the near future though.
