### ISSUE TITLE
Why do I have to specify app name when it is in the manifest.yml

### ISSUE THREAD

**Issue by docwhat** [cloudfoundry/cli#382]
Why do I have to specify the app name (e.g. `cf push MyApp` or `cf logs MyApp`) when only one app is in the `manifest.yml`?

If there are multiple, then default to the first.

**Comment by simonleung8** [comment]
Hi, currently if you are at the directory where the manifest.yml is at, and an app name if specified in the manifest, `cf push` doesn't require an app name.

As for `cf logs`, this command does not utilize the manifest in any way, so an app name is required.

We are going to close this issue, feel free to reopen if you want to further discuss.
