### ISSUE TITLE
Do we have testcases to test command metadata print?

### ISSUE THREAD

**Issue by xingzhou** [cloudfoundry/cli#388]
This comes to our mind when we are doing the create-service-key command, we don't find a place to add our test cases to test metadata print of a command.

If there are no test cases to test metadata, I suggest we modify the test helper's code and add test cases.

cc: @simonleung8

**Comment by goehmen** [comment]
@xingzhou Can you explain your use case a bit more.  CLI team is not quite understanding your question.  Thanks

**Comment by xingzhou** [comment]
@goehmen , when I was doing the "create-service-key" command, I want to write some unit test cases to test the help information of this command, for this command, at present, we have the help info like:
```
dongdong:Projects dongdong$ ./cf csk
FAILED
Incorrect Usage.

NAME:
   create-service-key - Create key for a service instance

ALIAS:
   csk

USAGE:
   cf create-service-key SERVICE_INSTANCE SERVICE_KEY

EXAMPLE:
   cf create-service-key mydb mykey
```
So i want to add some test cases to test whether the help info is printed out correctly, seems now, the testhelpers only support print out the result of the command(like whether the execuation failed or not), but the help information does not print out.

**Comment by simonleung8** [comment]
@xingzhou The meta information is printed by a third party package `codegangsta`, we have little control of it's printing format, so simply testing whether the metadata is printed should be suffice. We have plans to redo the help printing in the near future, we should have more test coverage in this area then.
If you want to assert the help content is indeed being printed, it could be done by running the command with `-h` and assert the help text is in the output.
Closing issue, feel free to reopen if you want to further discuss.
