### ISSUE TITLE
Plugin CLI Output - Capture but don't print

### ISSUE THREAD

**Issue by benlaplanche** [cloudfoundry/cli#390]
I have a scenario where I would like to capture the output of a core CLI command, so i can use it in my plugin, but for it not to be printed on the screen.

For example, i want to call `cf create-org development`. If the org development already exists then i get this output
```
➜  ~  cf create-org development
Creating org development as admin...
OK
Org development already exists
```

In my plugin, i want to search for the string `Org development already exists` and alter my behavior if it does. 

I'm currently using

`x, err := cliConnection.CliCommandWithoutTerminalOutput("create-org", "development")`

So `x` is always empty and will never return the value i'm looking for.

What i'd like is for `x` to return the value i'm looking for, so i can handle it in my plugin but it not to appear on the terminal output.

See https://github.com/benlaplanche/cf-testuser-plugin/blob/master/test_user_cmd.go#L158 for an example of what i'm trying to do.

**Comment by drnic** [comment]
Sorry to ask you to repeat yourself - in what way is the CCWTO() helper not doing what you need? x contains the output that would have out printed to the screen.

**Comment by benlaplanche** [comment]
You are totally correct! Sorry, i should double-check before opening an issue.

**Comment by drnic** [comment]
xoxo it's all good!
