### ISSUE TITLE
I ran the cf command using this version of the CLI: 6.10.0-b78bf10 as a regular user

### ISSUE THREAD

**Issue by countdmona** [cloudfoundry/cli#394]
And this error occurred: 
                open /home/kaayotee/.cf/plugins/config.json: permission denied

        and this stack trace:

                goroutine 1 [running]:
        main.generateBacktrace(0xc21000a000, 0x1)
                /var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:174 +0xa9
        main.handlePanics(0x7fd4f22c75d8, 0xc2100704e0)
                /var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:158 +0x123
        runtime.panic(0x90f2a0, 0xc21022f900)
                /var/vcap/packages/golang-1.2/src/pkg/runtime/panic.c:248 +0x106
        main.funcÂ·002(0x7fd4f22d6fe8, 0xc21022f900)
                /var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:90 +0x49
        github.com/cloudfoundry/cli/cf/configuration/plugin_config.funcÂ·003()
                /var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/configuration/plugin_config/plugin_config.go:71 +0x83
        sync.(*Once).Do(0xc21018dcd0, 0xc210264760)
                /var/vcap/packages/golang-1.2/src/pkg/sync/once.go:40 +0x9a
        github.com/cloudfoundry/cli/cf/configuration/plugin_config.(*

**Comment by goehmen** [comment]
You don't have privs on the directory where the /.cf/plugins/config.json file lives.  You might have changed the cf_env directory but not the cf_plugin_home location.
