### ISSUE TITLE
cf create-app-manifest not saving buildpack information

### ISSUE THREAD

**Issue by hhercules** [cloudfoundry/cli#395]
When using a particular manifest to deploy I have been specifying buildpack to use, but return yaml does not have it. 

Manifest used to create app:
```applications:
- name: app
  memory: 1G
  instances: 2
  host: app
  domain: mydomainexample.com
  buildpack: java_buildpack_offline-2_5
  services:
```

Manifest I get back from cf create-app-manifest:
```applications:
- name: app
  memory: 1024M
  instances: 2
  host: app
  domain: mydomainexample.com
  services:
```

**Comment by goehmen** [comment]
You're right.  Good catch.  We'll include buildpack info. Story is in the backlog
