### ISSUE TITLE
Wrongly creating the route based on the manifest's filename

### ISSUE THREAD

**Issue by francoisyanick** [cloudfoundry/cli#403]
Recently, the CF CLI is giving me a hard time to push my app as its creating a route based on the manifest's filename:

{code}
$ cf push -f manifest-stage.yml 
Creating manifest-stage.yml... OK

Creating route manifest-stage.yml.mysite.com... FAILED
CFoundry::RouteInvalid: 210001: The route is invalid: host format
{code}

I have tried to reinstall the CF CLI (Mac) but it did not resolve the issue.

**Comment by goehmen** [comment]
@francoisyanick What version of the CLI are you using?  What version of cf-runtime?

can you scrub and post the manifest?

**Comment by goehmen** [comment]
@francoisyanick If you are able to share the requested info, please reopen this issue so we can revisit it.

**Comment by francoisyanick** [comment]
I have reinstalled the CLI and it is working fine. My guess is that something else in my system was interacting at that moment but the CF CLI itself was working fine - at least it is working fine now that I have reinstall it.

Thank you.
