### ISSUE TITLE
Feature request: allow hooking/overriding commands

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/cli#404]
(originally posted on https://groups.google.com/a/cloudfoundry.org/d/msg/vcap-dev/jF1h16IFEh4/h8uEUsqCTAkJ)

We have one feature request from our users that can't be addressed using the current CLI plugin infrastructure: we would like to have an announcement feature to convey important maintenance information to users. 

Basically, whenever a user runs a command with the CLI we would like to be able to display a custom message pulled from a central location. 

Unfortunately the current plugin infrastructure does not allow to hook in either in the initialization phase or when any other command is executed, so it's basically impossible to implement as-is without modifying the CLI itself. We already have a plugin that exposes a custom "announce" command, but this requires the user to explicitly ask for the announce. 

So we would like either:
1) to be able to run some code (and print some output) during initialization
2) to be able to run all cf commands and run some code (and print some output) before the execution of the command itself
3) for this "announce" feature to be implemented upstream :)

**Comment by goehmen** [comment]
The ability to Override commands is not a feature we are looking at.  We set up a few tenets for plugins when we incepted and "Core commands are immutable" was one.

Pre/post hooks is something that comes up once in a while.  I appreciate your input here and will keep it as evidence of the demand for this  feature.  If we can get more support for it, then we can take an engineering look at what it would take to deliver it.

**Comment by CAFxX** [comment]
How about option 3, i.e. Implementing the announce feature?

**Comment by CAFxX** [comment]
@goehmen How about option 3, i.e. Implementing the announce feature?

**Comment by harrisj** [comment]
We have an interest in pre/post hooks as well, @goehmen
