### ISSUE TITLE
cf apps failed ，help me

### ISSUE THREAD

**Issue by tsxyz** [cloudfoundry/cli#409]
root@lishuai-desktop:~/cf_nise_installer/test_app# cf apps
Getting apps in org DevBox / space test as admin...
FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.

My own environment, using a nise bosh installation

**Comment by tsxyz** [comment]
supplement

root@lishuai-desktop:~/cf_nise_installer/test_app#  CF_TRACE=true cf apps

VERSION:
6.10.0-b78bf10

Getting apps in org DevBox / space test as admin...

REQUEST: [2015-04-13T16:00:15+08:00]
GET /v2/spaces/b94b1c28-3983-494b-9ba5-d4626774acc3/summary HTTP/1.1
Host: api.lishuai.local
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.10.0-b78bf10 / linux



RESPONSE: [2015-04-13T16:00:15+08:00]
HTTP/1.1 401 Unauthorized
Content-Length: 97
Content-Type: application/json;charset=utf-8
Date: Mon, 13 Apr 2015 08:00:15 GMT
Server: nginx
X-Cf-Requestid: 219376cc-b9b9-4afa-6521-85d41772abd7
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 8e08a332-6060-4311-43e6-4ccaebb5334c::3f0a10a0-4df5-4bb3-b07f-738d511b2da2

{
  "code": 1000,
  "description": "Invalid Auth Token",
  "error_code": "CF-InvalidAuthToken"
}


REQUEST: [2015-04-13T16:00:15+08:00]
POST /oauth/token HTTP/1.1
Host: uaa.lishuai.local
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/x-www-form-urlencoded
User-Agent: go-cli 6.10.0-b78bf10 / linux

grant_type=refresh_token&refresh_token=eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiIyMWY2MjA5Zi1iMzc4LTQwOGItOGJmZC04NDA0YjFlYWQ3ODgiLCJzdWIiOiJmYThmZmRkOC04YjM1LTQ4NjItYmI4Ny02NzY5YTBhMmY2ZmIiLCJzY29wZSI6WyJzY2ltLnJlYWQiLCJjbG91ZF9jb250cm9sbGVyLmFkbWluIiwic2NpbS53cml0ZSIsImNsb3VkX2NvbnRyb2xsZXIud3JpdGUiLCJwYXNzd29yZC53cml0ZSIsIm9wZW5pZCIsImNsb3VkX2NvbnRyb2xsZXIucmVhZCIsImRvcHBsZXIuZmlyZWhvc2UiXSwiaWF0IjoxNDI4OTA0Mzc5LCJleHAiOjE0MzE0OTYzNzksImNpZCI6ImNmIiwiaXNzIjoiaHR0cHM6Ly91YWEubGlzaHVhaS5sb2NhbC9vYXV0aC90b2tlbiIsImdyYW50X3R5cGUiOiJwYXNzd29yZCIsInVzZXJfbmFtZSI6ImFkbWluIiwidXNlcl9pZCI6ImZhOGZmZGQ4LThiMzUtNDg2Mi1iYjg3LTY3NjlhMGEyZjZmYiIsImF1ZCI6WyJjZiIsInNjaW0iLCJjbG91ZF9jb250cm9sbGVyIiwicGFzc3dvcmQiLCJvcGVuaWQiLCJkb3BwbGVyIl19.nFZ0TyBngF_US-zV0bZAR44awScoKmIIRiNztQOojYR47K1KPdkFULWHsm9Iuih38F4KzokkNS4r30K5_4NC51wChSbsIX20TMpxspU0ha09ZKTghkc-4cfn-s9TogcTlkKwkT4xl0yb4k5N3V6Pzw-aiWraKnDy0Wa4--yO5tY&scope=

RESPONSE: [2015-04-13T16:00:15+08:00]
HTTP/1.1 200 OK
Content-Length: 2033
Cache-Control: no-store
Content-Type: application/json;charset=UTF-8
Date: Mon, 13 Apr 2015 08:00:15 GMT
Pragma: no-cache
Server: Apache-Coyote/1.1
X-Cf-Requestid: d44a285e-2386-4bfe-5af8-df67510d3603

{"access_token":"[PRIVATE DATA HIDDEN]","token_type":"bearer","refresh_token":"[PRIVATE DATA HIDDEN]","expires_in":599,"scope":"scim.read cloud_controller.admin password.write scim.write openid cloud_controller.write cloud_controller.read doppler.firehose","jti":"a4150fca-7555-4e49-97af-a6db01f59f9f"}

REQUEST: [2015-04-13T16:00:15+08:00]
GET /v2/spaces/b94b1c28-3983-494b-9ba5-d4626774acc3/summary HTTP/1.1
Host: api.lishuai.local
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.10.0-b78bf10 / linux



RESPONSE: [2015-04-13T16:00:20+08:00]
HTTP/1.1 500 Internal Server Error
Content-Length: 99
Content-Type: application/json;charset=utf-8
Date: Mon, 13 Apr 2015 08:00:20 GMT
Server: nginx
X-Cf-Requestid: 8f17b961-71d4-4b76-4112-d9840a019be0
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: f8eec705-1598-48e7-73d1-60bbf6edef74::c6655b6f-6d8a-4920-8c75-752007e65238

{
  "error_code": "UnknownError",
  "description": "An unknown error occurred.",
  "code": 10001
}

FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.
FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.

**Comment by goehmen** [comment]
That trace shows that something with your Cloud Controller is not right.  Can you validate the install of CF?  You can login & target, what about other commands?  Is the problem specific to `cf apps`?

**Comment by goehmen** [comment]
Please reopen if the problem persists.
