### ISSUE TITLE
In manifest, 'no-hostname' clobbers 'host' or 'hosts'

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cli#418]
If I want to create an application that has both a route with no hostname and a route with a hostname, I would expect 'no-hostname' and 'host' to be additive. I would expect this manifest:

```yml
no-hostname: true
host: app
domain: example.com
```

to create these routes

```
space        host      domain                          apps
acceptance             example.com           my-app
acceptance   app   example.com           my-app
```

Instead, I only get the no-host route. If I want to create both routes, I need my manifest to look like this:

```yml
domain: example.com
hosts:
  - app
  - ''
```

**Comment by goehmen** [comment]
@wendorf It looks like you have found a way to get this done using the 
```
hosts:
  -  app
  - ''
```

**Comment by wendorf** [comment]
Yeah, exactly. If feels strange that `no-hostname` and `host` are not additive. I when I discovered that the `- ''` line worked, it felt like a secret trick instead of the supported path to getting both routes added. At the very least, I'd like the documentation to tell me how I can accomplish having both routes with hostnames and without hostnames, but I'd prefer a different syntax that felt more natural and expected.

**Comment by goehmen** [comment]
@wendorf Well, when you specify no-hostname, you shouldn't then expect to get an app with a hostname.  The unnatural thing is to expect that to work, I think.  no-hostname is taken literally.

**Comment by imod** [comment]
I would have loved some change here too, specially this gets strange/impossible if I have two domains and wanna have the `no-hostname` rule only used one of them.

e.g. I'm not able to do something like this:

```
my_host.cfapps.io
example.com
```
using the pattern described above I would end up with this:
```
example.com
my_host.example.com
cfapps.io
my_host.cfapps.io
```
which leaves me with two additional (unwanted) access points

**Comment by drnic** [comment]
@dkoper could this issue be re assessed please? `no-hostname` and `hosts` aren't implicitly mutually exclusive. The desire for a "root" app to have both `dingotiles.com` and `www.dingotiles.com` isn't uncommon.

**Comment by dkoper** [comment]
My proposal for tcp routes support for app manifest should cover this case. I sent it to cf dev 1-2 months ago. I put it on hold when routing team wanted to reconsider the workflow for multiple app ports support after feedback on this proposal. Can you take a look at it and see what you think of it?

**Comment by drnic** [comment]
For reference:

* https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/message/N4ZDS7FVHBQFSGP724ZAXUOMISNVURIR/
* https://docs.google.com/document/d/17c1FwsuK_YCjQhH_7CebQkjrot4sfIsbAMQ0Cwcvv0M/edit

@dkoper so my example above would be mapped to your proposal as:

```yaml
---
applications:
- name: myapp
  routes:
  - domain: dingotiles.com
    no-hostname: true
  - domain: dingotiles.com
    host: www
```
