### ISSUE TITLE
cf command cannot be downloaded

### ISSUE THREAD

**Issue by alongoles** [cloudfoundry/cli#420]
I cannot download any cf files. This is critical.

![image](https://cloud.githubusercontent.com/assets/7274129/7231949/658e5d00-e781-11e4-8206-041a6bdbd275.png)

**Comment by simonleung8** [comment]
It is working now, probably just a temp issue.

reopen if problem persist for you.

**Comment by alongoles** [comment]
Problem occurs again. How do I reopen the issue?
Seems to be a recurring problem, see issue #392.
