### ISSUE TITLE
in manifest_test, Domains and Hosts evaluation sometimes fails

### ISSUE THREAD

**Issue by zhang-hua** [cloudfoundry/cli#422]
I running into this issue when executing the bin/test, I get some errors like:
```
• Failure [0.040 seconds]
Manifests [It] removes duplicated values in 'hosts' and 'domains'
/Users/cf/Code/Go/src/github.com/cloudfoundry/cli/cf/manifest/manifest_test.go:302

  Expected
      <[]string | len:3, cap:4>: ["host-2", "my-hostname", "host-1"]
  to equal
      <[]string | len:3, cap:3>: ["my-hostname", "host-1", "host-2"]

  /Users/cf/Code/Go/src/github.com/cloudfoundry/cli/cf/manifest/manifest_test.go:301
```
It looks like the line of [L301](https://github.com/cloudfoundry/cli/blob/master/cf/manifest/manifest_test.go#L301) expect Hosts to equal a slice of strings, but fails sometime due to the uncertain sequence of the strings after removing duplicate host. This is not found to be reproducible on Travis. Perhaps we just need to check like this:
```
Expect(*apps[0].Hosts).To(ConsistOf([]string{"my-hostname", "host-1", "host-2"}))
```

I found this issue also apply at [L269](https://github.com/cloudfoundry/cli/blob/master/cf/manifest/manifest_test.go#L269) and [L270](https://github.com/cloudfoundry/cli/blob/master/cf/manifest/manifest_test.go#L270).

**Comment by simonleung8** [comment]
This is due to the version of Go the test is running on. The map order in Go v1.3+ is not maintained. We have a fix in the concourse branch, it will be merged into master soon.
