### ISSUE TITLE
RFE: cf api to return non-zero exit status when no api is being set

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#428]
It could make it easier for scripting to return non zero status when no api is set, to avoid having to parse the english output to know if an api is currently set or not.

currently, it seems the 0 exit status is always returned

```
$ cf api --unset
Unsetting api endpoint...
OK

No api endpoint set.

$ cf api
No api endpoint set. Use 'cf.exe api' to set an endpoint

$ echo $?
0

$ cf api https://api.[...] 
Setting api endpoint to https://api.[...]
OK

API endpoint:   https://api.[..] (API version: 2.25.0)
Not logged in. Use 'cf.exe login' to log in.

$ cf api
API endpoint: https://api.[...] (API version: 2.25.0)

$ echo $?
0

$ cf --version
C:\Program Files (x86)\CloudFoundry\cf.exe version 6.11.1-4ef66f6-2015-04-20T14:13:38+00:00
```

**Comment by goehmen** [comment]
@gberche-orange Actually each of these commands is executing successfully and returning the correct return code.  

`cf api` queries state and returns successfully in this case.

**Comment by gberche-orange** [comment]
thanks @goehmen for your response, this makes senses, sorry for submitting this noisy issue.

I'll stick with parsing the returned state:

```
$ cf api --unset
Unsetting api endpoint...
OK

No api endpoint set.

$ cf api | grep http > /dev/null
$ echo $?
1

$ cf api https://api.[...]
Setting api endpoint to [...]
OK

$ cf api | grep http > /dev/null
$ echo $?
0
```

**Comment by goehmen** [comment]
@gberche-orange Don't be sorry..always challenge the status quo.  that's what drives innovation.
