### ISSUE TITLE
cf push permission denied error

### ISSUE THREAD

**Issue by bluethundr** [cloudfoundry/cli#429]
Hello,

 When I try to push this one application, I get a strange permission denied error:

Using route appplatform.pcf.inbcu.com
Uploading appplatform...
FAILED
Error uploading application.
open /var/folders/ls/rr5vl0417p59x087k32d6ntc0000gn/T/apps196296657/sites/default/default.settings.php: permission denied

As far as I know there are no symlinks in the code directory pointing to any other locations. 

This is all I see if I do a cf logs appname --recent:

[TimothyDunphy@JEC206429674LM:~/Desktop/pcf/code/optl] #cf logs appplatform --recent
Connected, dumping recent logs for app appplatform in org NBCUni / space OpenPlatform as timothy.dunphy@nbcuni.com...

2015-04-27T16:22:27.56-0400 [API]     OUT Updated app with guid bb3c8a84-9e14-49dd-b17b-2e67577d58b4 ({"name"=>"appplatform", "memory"=>128, "buildpack"=>"https://github.com/dmikusa-pivotal/cf-php-build-pack", "environment_json"=>"PRIVATE DATA HIDDEN"})

I enabled CF_TRACE=true and dumped the output to a file. Could someone please take a look at that and let me know what they think is wrong?

I'm on cf version 6.7.0-c38c991-2014-11-12T01:45:23+00:00

I'm on mac os X:

[TimothyDunphy@JEC206429674LM:~/Desktop/pcf/code/optl] #uname -a
Darwin JEC206429674LM.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

**Comment by bluethundr** [comment]
I didn't see a way to upload an attachment to github. So I created this dropbox share as a work around.

https://www.dropbox.com/s/9so9hf07qe0y6ac/cf_push.txt?dl=0

Thanks,
Tim

**Comment by goehmen** [comment]
@bluethund The app you are pushing appears to have a symlink or something strange that is causing this permissions problem. The directory in question appears to be a temp dir which you don't want to have as part of your app push.

**Comment by bluethundr** [comment]
Hello,

For comparison I pushed the very simple 'fib' app just to demonstrate that PCF works. Here's the output of that, with CF_TRACE=true enabled:

https://www.dropbox.com/s/d363ysui7e6vbgk/cf_push_fib.txt?dl=0


Also, I went to the directory I was trying to push the code from:

/Users/TimothyDunphy/Desktop/pcf/code/optl

And did a find command, but didn't find any symlinks at all!

Is there any way you think you could still help me get to the bottom of this?

Thanks,
Tim

**Comment by simonleung8** [comment]
Are you still having problem with this app? We are not seeing anything unusual from the trace other than the permission denied error.
Just curious, the error comes from `default.settings.php`, what happens if you push the app without this file?
