### ISSUE TITLE
CLI version 6.11.1 doesn't the Name and Publisher on windows 7 (64)

### ISSUE THREAD

**Issue by StefH** [cloudfoundry/cli#436]
I cannot see the Name and Publisher and that this is actually the Cloud Foundry CLI ?

![2015-04-30_17h56_09](https://cloud.githubusercontent.com/assets/249938/7416821/4ffd49fe-ef62-11e4-9b36-34778d4742b9.png)

**Comment by jberkhahn** [comment]
Hey there,

This should be fixed in the upcoming release. Thanks for bringing this to our attention.
