### ISSUE TITLE
"runtime error: index out of range" when pushing app

### ISSUE THREAD

**Issue by fugumaki** [cloudfoundry/cli#437]
I'm trying out Stackato's Micro Cloud distribution with the Stackato bottle-py3 sample application, and I've received the error below.  Sorry if this isn't the right place to post it; the app told me to post it here.  :)

-----

Starting app bottle-py3 in org Development / space Sandbox as smitrobb...

        Aww shucks.

        Something completely unexpected happened. This is a bug in cf.
        Please file this bug : https://github.com/cloudfoundry/cli/issues
        Tell us that you ran this command:

                cf push bottle-py3

        using this version of the CLI:

                6.11.1-4ef66f6

        and that this error occurred:

                runtime error: index out of range

        and this stack trace:

                goroutine 1 [running]:
        main.generateBacktrace(0xc08401ddb0, 0x3)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xac
        main.handlePanics(0x2417b0, 0xc084049c80)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x126
        runtime.panic(0x96c9a0, 0x126a957)
                C:/Users/ADMINI~1/AppData/Local/Temp/2/makerelease155988687/go/src/pkg/runtime/panic.c:248 +0x11b
        github.com/cloudfoundry/cli/cf/api/app_instances.CloudControllerAppInstancesRepository.updateInstancesWithStats(0x24acc0, 0xc0840428a0, 0x24af20, 0xc0840edd80, 0xb4d738, ...)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/api/app_instances/app_instances.go:101 +0x465
        github.com/cloudfoundry/cli/cf/api/app_instances.CloudControllerAppInstancesRepository.GetInstances(0x24acc0, 0xc0840428a0, 0x24af20, 0xc0840edd80, 0xb4d738, ...)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/api/app_instances/app_instances.go:75 +0x3f5
        github.com/cloudf

**Comment by maximilien** [comment]
Can you post the output from:

```
cf curl <api-url>/v2/apps/<app-guid>/stats
```

Where `<api-url>` and `<app-guid>` are replaced with your API URI and the application you are dealing with, e.g., `bottle-py3` you listed above.

**Comment by goehmen** [comment]
Also - what version of cf-release are you running with stackato?  You
probably will need to follow-up with active state directly as this is a
commercial piece of software.

Greg Oehmen
Cloud Foundry Product Manager
415.205.6596

**Comment by fugumaki** [comment]
maimilien:  Hopefully this give you what you wanted:

U:\workspace\bottle-py3>cf curl /v2/apps/9289427f-6463-4231-a2a3-2e8908cf28ab/stats
{
   "0": {
      "state": "DOWN",
      "since": 1430854602
   }
}

goehmen:  I'm using Stackato V3.4.2 which it says is based on Cloud Foundry V2.

Anyway, I'll put this question to the Stackato Community forum.

Thanks!
