### ISSUE TITLE
set-space-role fails on public CF instances where users lack scim.userids scope

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cli#444]
Currently, on PWS, the `set-space-role` command fails, probably because my public account there lacks scim.userids role (which seems the normal case, especially on public instances to preserve users privacy)

```
$ cf set-space-role another.email@org.com my-org development SpaceAuditor: 
[...]
{"error":"access_denied","error_description":"Invalid token does not contain resource id (scim)"}

$ CF_TRACE=true cf set-space-role another.email@org.com my-org development SpaceAuditor
GET /Users?attributes=id,userName&filter=userName+Eq+%22another.email@org.com%22 HTTP/1.1

```
I'm wondering whether the previous adaptions made to `cf org-users -a` to use /v2/organizations/{guid}/users instead of UAA endpoint could also be made to `set-space-role`, to work around this, and provide username to userguid, necessary to the next API endpoint call.

Then, I'd expect the remaining API endpoint call to succeed:

```
$ CF_TRACE=true cf curl -X 'PUT' /v2/spaces/96ecb509-9063-41b7-ac36-147e5f145549/auditors/67598a00-731b-4b4f-a3f3-25f33474cd44
[...]
Host: api.run.pivotal.io
[...]
RESPONSE: [2015-05-07T12:11:36+02:00]
HTTP/1.1 201 Created
```

Related docs:
https://github.com/cloudfoundry-community/cf-docs-contrib/wiki/v196
https://www.pivotaltracker.com/n/projects/966314/stories/63345104

**Comment by goehmen** [comment]
https://www.pivotaltracker.com/story/show/88838792

**Comment by camelpunch** [comment]
The story @goehmen mentioned is done.

**Comment by gberche-orange** [comment]
Thanks @camelpunch for the update. 

I understand that the fix was finally brought by [story #98135898 As a CF user, I have scope to access UAA's /ids/Users by default](https://www.pivotaltracker.com/n/projects/966314/stories/98135898) and that the CLI CC API call was not modified. Rather ``GET /Users?attributes=id,userName&filter=userName+Eq+%22another.email@org.com%22`` is now accepted by CC API by default when invoked from a cf users bearer token.

**Comment by camelpunch** [comment]
@goehmen any ideas?

**Comment by andrew-edgar** [comment]
Also looking for when this story will land.  Looks like the CAPI story is not yet scheduled.  Can we get an update as to the status?

**Comment by dkoper** [comment]
The CLI team has 4-5 stories in the following epic https://www.pivotaltracker.com/epic/show/1991856 regarding this issue, which we hope to get to next month.

**Comment by krishicks** [comment]
Closing this in favor of the epic @dkoper linked above.
