### ISSUE TITLE
Improve restage tip

### ISSUE THREAD

**Issue by snicoll** [cloudfoundry/cli#446]
When one binds a service to an app, the CLI displays a tip indicating the app has to be restaged, something like:

```
➜  target  cf bind-service jsug jsug-db
Binding service jsug-db to app jsug in org FrameworksAndRuntimes / space development as snicoll@pivotal.io...
OK
TIP: Use 'cf restage' to ensure your env variable changes take effect
```

It would be nice if the tip would provide the name of the app as plain `cf restage` won't work (i.e. `Use 'cf restage jsug' ....).

Thanks!

**Comment by jberkhahn** [comment]
We wrote a fix for this that updates the tip. This should be in v6.11.3.
