### ISSUE TITLE
cf push 6.7.0-c38c991 bug from Bluemix

### ISSUE THREAD

**Issue by OscarAlmgren** [cloudfoundry/cli#450]
Tell us that you ran this command:

                cf push

        using this version of the CLI:

                6.7.0-c38c991

        and that this error occurred:

                runtime error: invalid memory address or nil pointer dereference

        and this stack trace:

                goroutine 1 [running]:
        main.generateBacktrace(0xc21000a000, 0x2)
                /Users/pivotal/go-agent/pipelines/Mac-OSX-Testing/src/github.com/cloudfoundry/cli/main/main.go:147 +0xa9
        main.handlePanics(0xf9a5d8, 0xc210066500)
                /Users/pivotal/go-agent/pipelines/Mac-OSX-Testing/src/github.com/cloudfoundry/cli/main/main.go:131 +0x123
        runtime.panic(0x51b5c0, 0xd78d59)
                /usr/local/go/src/pkg/runtime/panic.c:248 +0x106
        io/ioutil.func·001()
                /usr/local/go/src/pkg/io/ioutil/ioutil.go:29 +0xf0
        runtime.panic(0x51b5c0, 0xd78d59)
                /usr/local/go/src/pkg/runtime/panic.c:248 +0x106
        bytes.(*Buffer).ReadFrom(0xc210bb6d20, 0x0, 0x0, 0x0, 0x0, ...)
                /usr/local/go/src/pkg/bytes/buffer.go:169 +0x1f1
        io/ioutil.readAll(0x0, 0x0, 0x200, 0x0, 0x0, ...)
                /usr/local/go/src/pkg/io/ioutil/ioutil.go:32 +0x156
        io/ioutil.ReadAll(0x0, 0x0, 0x0, 0x0, 0x0, ...)
                /usr/local/go/src/pkg/io/ioutil/ioutil.go:41 +0x3f
        github.com/cloudfoundry/cli/cf/net.Gateway.doRequestAndHandlerError(0xfa3a58, 0xc210085bd0, 0x6dab28, 0x1, 0x12a05f200, ...)
                /Users/pivotal/go-a

That's all I got from terminal.

**Comment by goehmen** [comment]
Oscar:

Can you tell me what version of runtime you are hitting?  (cf curl /v2/info)

and rerun the cf push with trace on (CF_TRACE=true cf push) and share the
output?


Greg Oehmen
Cloud Foundry Product Manager
415.205.6596

**Comment by OscarAlmgren** [comment]
Sure thing! Please note, I actually got 'cf push' working by doing another push like 20 min later. Not sure if this is a reoccurring bug or just a temp glitch. The whole trace log is cut off (2000+ lines) in this input form (and on pastebin) because of limits. Should I send it by email? 

```{
   "name": "Bluemix",
   "build": "205005",
   "support": "http://ibm.com",
   "version": 2,
   "description": "IBM Bluemix",
   "authorization_endpoint": "https://login.ng.bluemix.net/UAALoginServerWAR",
   "token_endpoint": "https://uaa.ng.bluemix.net",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.23.0",
   "logging_endpoint": "wss://loggregator.ng.bluemix.net:443"
}```

**Comment by goehmen** [comment]
Oscar:

2.23.0 is a pretty new version of runtime.  I recommend upgrading your CLI
to latest stable.  Your CLI was released last November.

Greg Oehmen
Cloud Foundry Product Manager
415.205.6596

**Comment by goehmen** [comment]
@OscarAlmgren - we can't repro this.  I'm going to close this issue since your subsequent push worked just fine.  If this keeps happening, please re-open and we'll take a deeper look.
