### ISSUE TITLE
cf output 

### ISSUE THREAD

**Issue by ncsucharlie** [cloudfoundry/cli#451]
Version: 6.11.0-bba7fcf-2015-04-13T17:49:06+00:00

I am using the cli in a cygwin terming on Windows 7.  Whenever I issue any cf command in the cygwin terminal the output from CLI is formatted in an unreadable state... Looks like it's adding a bunch of spaces after each line in place of a return.  A picture is worth a 1000 words so see my attached screen capture.  Not sure if this info would be useful but my TERM variable is set to 'xterm' in the cygwin terminal.
![cf_output_formatting_prob](https://cloud.githubusercontent.com/assets/12009095/7687770/8a1bb51c-fd6d-11e4-82e6-3bb3b28d9164.png)

**Comment by goehmen** [comment]
CLI team to try to repro.

**Comment by ncsucharlie** [comment]
found out what is going on... if I cf login through a windows command prompt and then go to use the cf commands in a cygwin terminal is when I'm getting the bad formatting... if I do the cf login from the cygwin terminal then formatting is good.

**Comment by goehmen** [comment]
@ncsucharlie Definitely good to know.  Thanks!

**Comment by jberkhahn** [comment]
@goehmen This is due to the config file (that controls how the translation files are formatted for the system you're on) only gets written when you run certain commands - things like target, login, api, etc.

**Comment by jberkhahn** [comment]
Going to close this, please feel free to reopen if you need any additional help.
