### ISSUE TITLE
Local overrides for organization/space?

### ISSUE THREAD

**Issue by harrisj** [cloudfoundry/cli#454]
As we have been using CloudFoundry in many projects, we've been interested in some way to automatically switch to the right organization/space when we `cd` into a project directory. This is definitely doable by having [autoenv](https://github.com/kennethreitz/autoenv) called `cf target`, but we've wanted to improve on this in two ways:

* If for some reason, we need to retarget the project to a different org/space, it would be great if it automatically updated to the new target/org for future cd's into the project
* More importantly, if we have two projects in separate terminal windows, switching the target for one affects the deployment for the other because the org/space setting is global. Of course, that is an issue running manual `cf target` without using autoenv as well.

I am curious if there are any plans for supporting local overrides that can be installed someplace like `.cf.json` in the root of a project. Something a bit like rvm's .rvmrc, but not setting the global state in the same way that does it. I have started to look into how to implement it, but I don't want to submit a pull request if there is either no interest in this functionality or plans are already in the works. Thank you.

**Comment by goehmen** [comment]
@harrisj Check out https://github.com/nebhale/cfenv

```
Specify your app's Cloud Foundry environment once, in a single file. Changing directrories changes your Cloud Foundry environment.
```

**Comment by jberkhahn** [comment]
Gonna close this, if you need any more help, please feel free to reopen it.
