### ISSUE TITLE
cf runtime error

### ISSUE THREAD

**Issue by phillipgilmore** [cloudfoundry/cli#459]
ran this command: 
cf push SkyKisses

version of CLI: 
6.11.2-2a26d55

runtime error: invalid memory address or nil pointer dereference

with extended stack trace information (not shown)

**Comment by goehmen** [comment]
@phillipgilmore What cf-release are you hitting?  Can you push again with CF_TRACE=true and provide the output?  Thanks

**Comment by phillipgilmore** [comment]
[image: Inline image 1]

On Tue, May 26, 2015 at 4:27 PM, greg oehmen <notifications@github.com>
wrote:

> @phillipgilmore <https://github.com/phillipgilmore> What cf-release are
> you hitting? Can you push again with CF_TRACE=true and provide the output?
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/cli/issues/459#issuecomment-105669705>.
>



-- 
Phillip L. Gilmore, PhD
Industrial-Organizational Psychology
Dallas, TX

**Comment by jberkhahn** [comment]
Hey there, it looks like your image didn't upload, could you try again please?

**Comment by goehmen** [comment]
@phillipgilmore Hey there, it looks like your image didn't upload, could you try again please?

**Comment by jberkhahn** [comment]
Closing this. If you continue to experience this, please feel free to reopen.
