### ISSUE TITLE
index out of range panic when getting stats for Diego app while Diego stats endpoint is down

### ISSUE THREAD

**Issue by leochu** [cloudfoundry/cli#460]
Command run:

`cf app dora`

CLI version:

`6.11.2-72291d7`

Error:

`runtime error: index out of range`

Stack trace:

```
goroutine 1 [running]:
main.generateBacktrace(0xc21000a000, 0x3)
/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xa9
main.handlePanics(0x10c45d8, 0xc2100695a0)
/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x123
runtime.panic(0x5704c0, 0xe7c8f7)
/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc2100bd9c0, 0xc2100b19c0, 0x24, 0x0, 0x0, ...)
/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x275
github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc210341000, 0xc2100b19c0, 0x24, 0xc21018b590, 0x4, ...)
/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:112 +0x683
github.com/cloudfound
```

If the `/v1/actual_lrps/:guid/stats` endpoint is broken on the TPS component of Diego, then the `GetInstances` call [here](https://github.com/cloudfoundry/cli/blob/d364b91144c3332057bc8c78199bfd09fde145d3/cf/commands/application/app.go#L108-L118) returns an empty slice, and probably an error which isn't being handled.  The empty slice gets passed to `GetContainerMetrics` [here](https://github.com/cloudfoundry/cli/blob/d364b91144c3332057bc8c78199bfd09fde145d3/cf/api/logs_noaa.go#L56-L68) where `metrics` may not be empty even though `instances` is, so it will blow up on line 68.

**Comment by jberkhahn** [comment]
Hey there,

Thanks for bringing this to our attention. Really nice bug report, I wish all our issues were this clean :)

 We're writing a fix for this that should be out the next time we cut a release.
