### ISSUE TITLE
bin/test fails for go-bindata

### ISSUE THREAD

**Issue by nakaji-s** [cloudfoundry/cli#461]
bin/test fails because of errors below.
```
=== RUN TestFindFilesWithSymlinks
--- FAIL: TestFindFilesWithSymlinks (0.00 seconds)
	convert_test.go:55: Symlink source and target produced different function lists.  Expected symlinktargetFile1 to be file1
	convert_test.go:55: Symlink source and target produced different function lists.  Expected symlinktargetFile2 to be file2
	convert_test.go:55: Symlink source and target produced different function lists.  Expected symlinktargetFile3 to be file3
	convert_test.go:55: Symlink source and target produced different function lists.  Expected symlinktargetFile4 to be file4
```

bin/test tests not only cli's unit test but also go-bindata's unit test.
And go-bindata's unit test doesn't pass now.

So, I think..
* go-bindata should be version specified.(using godep)
* bin/test shouldn't test go-bindata.

**Comment by jberkhahn** [comment]
Pretty sure this isn't the case - our internal pipelines have been fine, and we personally haven't noticed this issue. All our tests are written and run using ginkgo, which go-bindata does not even use. I don't really see how bin/test could be causing the go-bindata tests to run.

If you continue to experience this issue, please feel free to post some more information about how to reproduce this issue, but  for now I'm going to close this.

**Comment by nakaji-s** [comment]
This issue was my misunderstanding. My $GOPATH was wrong and go-bindata was installed wrong place.
I'm sorry to cause you trouble. 

thanks.
