### ISSUE TITLE
manifest.yml ignored when using create-buildpack

### ISSUE THREAD

**Issue by simonjjones** [cloudfoundry/cli#462]
When I create a new buildpack using `cf create-buildpack NAME PATH POSITION` a file named manifest.yml is incorrectly ignored from the upload to the runners.

For example, when using the recently released asp.net buildpack https://github.com/cloudfoundry-community/asp.net5-buildpack the manifest.yml is required by the buildpack, however the resulting buildpack directory on the CF runners does not include it:

```
$ ls -1
bin
cf.Gemfile
cf.Gemfile.lock
compile-extensions
CONTRIBUTING.md
Gemfile
Gemfile.lock
lib
LICENSE
README.md
resources
spec
VERSION
```

Pushing an app using this buildpack will result in an error in that buildpack's code, which eventually resolves to `file not found: manifest.yml`

It would appear that the upload code for buildpacks & apps is shared, and while it is appropriate to ignore manifest.yml for applications, I don't believe it is for buildpacks.

**Comment by jberkhahn** [comment]
Hey there,

I don't believe buildpack manifests are used by the cli - I think they're used by the buildpack packager: https://github.com/cloudfoundry-incubator/buildpack-packager, which is mentioned in the docs for the asp buildpack you linked - checkout step 3 under "Building".

Once you've packaged the buildpack into a tar using that, you upload the tar using the cli and everything should work.

**Comment by simonjjones** [comment]
Hey Jonathan,

I agree there are a number of workarounds to get this working, however, I wonder if the behaviour of having the `create-buildpack` & `update-buildpack` code reusing the `push` zipping code & ignoring files which shouldn't be ignored for buildpacks is correct?

Cheers, Simon
