### ISSUE TITLE
cf cli not proxy aware?

### ISSUE THREAD

**Issue by mhlandry** [cloudfoundry/cli#464]
I cannot set my api endpoint when I am behind my corporate proxy. I am following the Cloud Foundry deployment steps in the readme, but whenever I run the command `cf api --skip-ssl-validation https://api.10.244.0.34.xip.io`, I get this error:

     $ cf api --skip-ssl-validation https://api.10.244.0.34.xip.io
     Setting api endpoint to https://api.10.244.0.34.xip.io...
     FAILED
     Error performing request: Get https://api.10.244.0.34.xip.io/v2/info: read tcp <my ip>: connection reset by peer`

My vagrant VM is running, and bosh cck shows no errors and both my http_proxy and https_proxy vars are set. I have tried setting my no_proxy as well, as instructed from the readme:

     $ printenv
     ...
     no_proxy=192.168.50.4,*.xip.io

However, if do a curl of that URL, I get a good response:

```
{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","min_cli_version":null,"min_recommended_cli_version":null,"api_version":"2.27.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}%
```

So it would appear the cli isn't picking up my proxy settings.

**Comment by jberkhahn** [comment]
Hey there,

As far as we're aware, the golang http package is supposed to handle the proxy as long as HTTP_PROXY and/or HTTPS_PROXY are set. Do you have any more information about the proxy you are using? Also, if you could run the command with CF_TRACE=true and post the output, as well as show your exact env variables, that would be helpful.

Thanks,

**Comment by mhlandry** [comment]
Thanks for the reply.  If I turn on CF_TRACE, I wind up getting:
```
Error performing request: Get https://api.10.244.0.34.xip.io/v2/info: read tcp x.x.x.x:80: connection reset by peer
```
where x.x.x.x:80 is an IP address on my company's internal network.

But if I curl the URL, I get a good response:
```
{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud Foundry sponsored by Pivotal","authorization_endpoint":"http://login.10.244.0.34.xip.io","token_endpoint":"https://uaa.10.244.0.34.xip.io","min_cli_version":null,"min_recommended_cli_version":null,"api_version":"2.27.0","logging_endpoint":"wss://loggregator.10.244.0.34.xip.io:443"}%
```

**Comment by jberkhahn** [comment]
Hi there

Re: environment variables

Can you provide what PROXY related environment variables are set, for example:

$ env | grep PROXY

Cheers

**Comment by mhlandry** [comment]
I have the following set:

HTTP_PROXY=...
HTTPS_PROXY=...
FTP_PROXY=...
RSYNC_PROXY=...

I'd prefer to not give out the actual URL as it is company specific.

**Comment by goehmen** [comment]
@mhlandry - So you've gotten to the same point in both github issues (this & https://github.com/cloudfoundry/cf-release/issues/679).  If you can't share info from your CF_TRACE, our hands are tied.  Did you look at the output as @sparameswaran recommended?

**Comment by mhlandry** [comment]
@goehmen 
I thought I shared the relevant output from CF_TRACE in my first reply in this thread.  Having said that, please do not keep this issue open any longer on my account.  Unfortunately, I have tried so many different debug tips in the last two months that I am having a different issue now and I cannot reproduce the original issue.  At this point I think it's a DNS issue with xip.io.

**Comment by xizhendu** [comment]
The root case is more like on the dns server you get when you are in your corp network.
Looks the cf command is always resolving the fqdn by /etc/resolv.conf, regardless local network or not, even we map ip/hostname in /etc/hosts, it never works.
So if the current dns server on your system can't resolve the *.local.pcfdev.io to 192.168.11.11 correctly, we will have to face this issue.
