### ISSUE TITLE
create-app-manifest does not store buildpack parameter

### ISSUE THREAD

**Issue by krishicks** [cloudfoundry/cli#466]
If I push an app using a manifest that specifies a `buildpack` parameter and then use `create-app-manifest`, the generated manifest will not include a `buildpack` parameter.

The buildpack I'm using is the go-buildpack from https://github.com/cloudfoundry/go-buildpack.git.

**Comment by flavorjones** [comment]
This is related to an email I just sent @goehmen about exposing buildpacks as metadata in `cf app` output as well. +1, I'd like to see this, too.

**Comment by jberkhahn** [comment]
Hey, we fixed it so that cf create-app-manifest will include buildpack. Will be fixed in next release.
Cheers

**Comment by krishicks** [comment]
Thanks!
