### ISSUE TITLE
cf cli cliConnection not working on 6.9 

### ISSUE THREAD

**Issue by jessexu20** [cloudfoundry/cli#468]
I have checked the cliConnection on 6.11 and works fine for me... but it doesn't seem to work on cf version 6.9 and there is no error info about that, just exit quietly....

**Comment by jberkhahn** [comment]
Not really sure about your problem here. Are you referring to the plugin cli_connection.go? What seems to be the issue? We've added functionality to plugins since 6.9, so if your plugin takes advantage of those it won't work on an older version of the cli.

Need some more info about your problem.

**Comment by jessexu20** [comment]
I was using the methods like AccessToken() in cliConnection and found out there are no such methods in version earlier than 6.11.1...But it seems that go didn't give any error information when running on a older version of cf, which it should report exceptions like ** methods not found **. So is there any suggestions to that? Thx.

**Comment by jberkhahn** [comment]
Unfortunately, we can't control error message from golang itself. We do have functionality that allows a plugin author to specify a minimum required version of cf, to try and alleviate errors like this. 

We've updated the changelog for plugins to try and keep better of when individual methods were added.

**Comment by jessexu20** [comment]
Thanks for that..
