### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by palonsoro** [cloudfoundry/cli#476]
I have found some mistakes at Spanish translation file `cf/i18n/resources/es_ES.all.json `cf/i18n/resources/es_ES.all.json`:

- String with id 'app crashed' translates to 'La app rompio' but it be 'La app se ha caído' (literally, it would be 'La app se ha roto', but that would sound a bit strange in Spanish, I think).
- String with id 'crashing' translates to 'rompio' while it should be 'caída'.
- String 'owned' is translated to 'adueneada', which is no correct word in Spanish. The good translation may be "propia" (which means 'owned').

**Comment by jberkhahn** [comment]
Hey,
Thanks for taking an interest in the CLI translations. Do you think you could type up a PR to the spanish translation file in cf/i18n/resources/es_ES.all.json?

**Comment by palonsoro** [comment]
Ok. As soon as I have enough time,  I will do it.

**Comment by jberkhahn** [comment]
Thanks a lot. Look forward to merging it.
