### ISSUE TITLE
Security group spaces not displayed if bound to more than 50 spaces

### ISSUE THREAD

**Issue by vlerenc** [cloudfoundry/cli#486]
### Summary
Security group spaces not displayed if bound to more than 50 spaces.

### Details
When a security group is bound to more than 50 spaces, the spaces are not displayed. This gives the impression that it's a deployment-wide security group when in fact it's a space-bound security group. This caused some issues in our landscape as it is easy to miss (in combination with another issue: iptable rules are created per security group and space even if the same/not distinct, resulting in very slow runner performance when starting an application).

### Analysis
It seems https://github.com/cloudfoundry/cloud_controller_ng/blob/2b1d38cba944086fa545d621a37ce4089b8e239e/lib/cloud_controller/rest_controller/preloaded_object_serializer.rb defines ```MAX_INLINE_DEFAULT = 50```, which is then evaluated in https://github.com/cloudfoundry/cloud_controller_ng/blob/2b1d38cba944086fa545d621a37ce4089b8e239e/lib/cloud_controller/rest_controller/preloaded_object_serializer.rb which for to_many relations ```if associated_model_instances.count > opts[:max_number_of_associated_objects_to_inline]``` returns with no spaces at all. https://github.com/cloudfoundry/cli/blob/4a108fd21d6633b250f6d9f46e870967cae96ac0/cf/commands/securitygroup/security_groups.go is then showing the security group with no org and no space.

### Steps to reproduce
Bind non-staging/running security group to more than 50 spaces.

**Comment by goehmen** [comment]
@vlerenc - This is a known bug and will be fixed with this https://www.pivotaltracker.com/story/show/96033766

The fix should be out in the nexgt CLI release - 6.12.0 which should come out by end of next week at the latest.
