### ISSUE TITLE
get_currentspace and get_CurrentOrg not work 

### ISSUE THREAD

**Issue by jessexu20** [cloudfoundry/cli#488]
Here is the code, it works 5days ago. But it seems that the methods inside the plugin has been changed..I always get the following error info..

        reading body gob: type mismatch: no fields matched compiling decoder for SpaceSummary

Here is the code

        cf_api, err:=cliConnection.ApiEndpoint();check(err);
	token, err:= cliConnection.AccessToken();check(err);
	fmt.Println(cf_api,token)
	tok:=token[7:]
        //above works
	space, err:=cliConnection.GetCurrentSpace();
	fmt.Println(space)
	space_id:=space.Guid
	org, err := cliConnection.GetCurrentOrg();check(err);

can you please anything that I need to modify? thanks

**Comment by jberkhahn** [comment]
Hey there,

We're currently in the process of tweaking the plugin api data models. You might have to recompile your plugins if you're using an edge release of the cli, or when 6.12.0 comes out.

**Comment by jessexu20** [comment]
Okay.. may I ask when the 6.12 will come out?

**Comment by simonleung8** [comment]
A fast way to fix this is to re-compile and re-install your plugin against the new CLI

**Comment by goehmen** [comment]
@jessexu20 6.12.0 will be released likely this eek.  you can see the release marker in the backlog here https://www.pivotaltracker.com/n/projects/892938
