### ISSUE TITLE
Ability to push all apps in a manifest.yml in parallel

### ISSUE THREAD

**Issue by tsaleh** [cloudfoundry/cli#492]
This would be useful for microservice architectures.

**Comment by camelpunch** [comment]
Saved you a click: "literally in parallel"

**Comment by krishicks** [comment]
@dkoper: What do you think about this?

**Comment by dkoper** [comment]
Let me confirm the issue currently - pushing multiple apps is too slow? And if we would upload the bits in parallel, it will be fast?
@tsaleh Would you happen to have a breakdown of the push process showing how much time is spent on uploading vs other steps?
Would there be any circumstances under which you'd want to push apps sequentially?

**Comment by tsaleh** [comment]
Saying "in parallel" may have been a mistake on my part.  The point of this isn't about speed, but about the ability to push all of the apps defined in a manifest easily and quickly.  Doing it in parallel would be a nice optimisation, but what I'm really looking for is `cf push --all`.

**Comment by dkoper** [comment]
@tsaleh Apologies in the delay. How does `cf push -f app-manifest-with-multiple-apps` not already provide this?

**Comment by tsaleh** [comment]
It does.  I think it didn't when I opened the issue?

...now, how about doing it in parallel?  :D:D:D  Should that be a separate GH issue?

**Comment by dkoper** [comment]
You'd probably submit an issue with the same title? We may as well re-use this one :)

So far we have no API calls that we make in parallel. I have listed my initial concerns with it here:
https://github.com/cloudfoundry/cli/pull/805#issuecomment-218371703

That said, with the upcoming Bits Service, uploading of artifacts will no longer put a load on the Cloud Controller, and may even allow uploading directly to a blobstore. We could experiment if significant performance improvements are made by parallelizing uploads.

**Comment by butzopower** [comment]
This is a feature I would also like.  For us, it is not the artifact uploading serially that is slow, but that we have to wait for each app to start before the next one stops and restarts.

For instance, we are deploying 7 Spring apps in a sandbox environment that we run our smoke tests against.  Across uploading, stopping, and starting each application, our total deploy time takes 10+ minutes.  If each app were starting in parallel, then the deploy time will only be as long as the longest application deployment.

We can currently hack around this in our CI environment by having different jobs for deploying with individual manifests, but it really feels more like a workaround when we want to deploy all of the applications as a bundle (at least for smoke testing).

**Comment by dkoper** [comment]
@butzopower @tsaleh
A UX concern with this is how to display the current output and CF logs when we're retrieving staging logs and polling multiple apps at the same time.
Also, we wouldn't want to change the current sequential behaviour as (micro-service based) applications may depend on it: defining the backend services at the top of the app manifest and the front-end app last to ensure everything's running by the time the external facing app is up.

Have you considered using `--no-start` in your app manifest and rely on your shell to start them simultaneously? Something like:
`cf push -f app-manifest.yml --no-start && cf start one-app & && cf start another-app & && cf start yet-another-app & && cf start the-final-app && wait`?
*with an additional check to only start your smoke tests if all apps started successfully*

This has the advantage that you could send the trace for each app start to a different file by just prepending `CF_TRACE=one-app` etc. before the start commands.

**Comment by DarrylD** [comment]
Any progress on this? Would be nice to push 10 of our apps in parallel.

**Comment by dkoper** [comment]
@DarrylD I see many complexities (mentioned in my previous comment) that need to be resolved and I wonder how these could be resolved in a way that keep this feature as useful and usable as people expect.

I'd rather see someone in the community develop a CLI plugin for this feature, and make it useful for their use case. If it turns out widely-adopted and well-liked, we can use that as a model to consider providing it in the core CLI.

**Comment by gitricko** [comment]
Is there any of this new how to build this ? I think this is a useful feature
