### ISSUE TITLE
cf curl doesn't work on windows

### ISSUE THREAD

**Issue by benmoss** [cloudfoundry/cli#495]
When I try to run `CF_TRACE=true cf curl "/v2/apps/f630424e-1bf0-4675-ba84-1b844089d3c7" -X PUT -d '{"enable_ssh": false}'` on Windows using the bash shell provided in https://msysgit.github.io/ I get

```
$ CF_TRACE=true cf curl "/v2/apps/f630424e-1bf0-4675-ba84-1b844089d3c7" -X PUT -d '{"enable_ssh": false}'

VERSION:
6.11.3-cebadc9


REQUEST: [2015-06-24T10:19:27-04:00]
PUT /C:/Program%20Files%20%28x86%29/Git/v2/apps/f630424e-1bf0-4675-ba84-1b844089d3c7 HTTP/1.1
Host: api.10.244.0.34.xip.io
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.11.3-cebadc9 / windows

{"enable_ssh": false}

RESPONSE: [2015-06-24T10:19:27-04:00]
HTTP/1.1 404 Not Found
Content-Length: 86
Content-Type: application/json;charset=utf-8
Date: Wed, 24 Jun 2015 14:19:27 GMT
Server: nginx
X-Cascade: pass
X-Cf-Requestid: ffd8bbc9-85dd-4d45-4d55-db779df598cb
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 20c16995-f4d5-4e4d-40b4-dda78575a855::e6f17de8-99d1-4dff-860f-a491678afa9e

{
  "code": 10000,
  "description": "Unknown request",
  "error_code": "CF-NotFound"
}
{
   "code": 10000,
   "description": "Unknown request",
   "error_code": "CF-NotFound"
}
```

Somehow the path is getting a prepended with the path to Git.

When run via Command Prompt, I get a different issue:

```
C:\>cf curl "/v2/apps/f630424e-1bf0-4675-ba84-1b844089d3c7" -X PUT -d '{"enable_ssh": false}

VERSION:
6.11.3-cebadc9

FAILED
Incorrect Usage.

Unknown flag "-X"

NAME:
   curl - Executes a raw request, content-type set to application/json by default

USAGE:
   cf curl PATH [-iv] [-X METHOD] [-H HEADER] [-d DATA] [--output FILE]

OPTIONS:
   -i           Include response headers in the output
   -v           Enable CF_TRACE output for all requests and responses
   -X 'GET'     HTTP method (GET,POST,PUT,DELETE,etc)
   -H           Custom headers to include in the request, flag can be specified multiple times
   -d           HTTP data to include in the request body
   --output     Write curl body to FILE instead of stdout
```

**Comment by stefanschneider** [comment]
If I remember correctly it should work without the initial /
e.g. cf curl v2/info

**Comment by goehmen** [comment]
@benmoss is this still an issue or did @stefanschneider 's suggestion resolve it?

**Comment by benmoss** [comment]
@goehmen seems like it's still an issue. leaving off the leading slash works, but it seems like more of a temporary workaround than a real fix

**Comment by camelpunch** [comment]
@goehmen this seems related to our current effort to figure out which Windows shells we support.

**Comment by dkoper** [comment]
This works for me in ```cf version 6.13.0``` on Windows 7 command prompt, so maybe it's been fixed since. Can you try? (note that I took out the single quotes to avoid an "Incorrect Usage" error.

```
D:\>cf curl "/v2/apps/96513a0f-1684-4f82-9c75-9de4385e789c" -X PUT -d "{\"enable_ssh\": false}"
{
   "metadata": {
      "guid": "96513a0f-1684-4f82-9c75-9de4385e789c",
      "url": "/v2/apps/96513a0f-1684-4f82-9c75-9de4385e789c",
      "created_at": "2015-10-21T22:43:25Z",
      "updated_at": "2015-10-22T03:44:40Z"
...
```

**Comment by benmoss** [comment]
Ah, the single quotes to double quotes issue was it! Not sure I totally get why, but only using double quotes seems to fix the issue on Windows.

**Comment by ichandan16** [comment]
I am getting below error in Windows 7 in git bash:

```
$ cf curl /v2/info
{
   "description": "Unknown request",
   "error_code": "CF-NotFound",
   "code": 10000
}
```

The single quotes  or double quotes around the command does not work either.

However this : `cf curl v2/info`  works.

I am using `cf.exe version 6.33.1+c77e55743.2017-12-15`

**Comment by dkoper** [comment]
@ichandan16 Do you mind submitting a new issue? With our tooling it's easy to miss comments on already closed issues, and I can't move them into the backlog for the team to investigate.

**Comment by ichandan16** [comment]
Thank you @dkoper .
