### ISSUE TITLE
Feature Request: list related commands for `cf help <command>`

### ISSUE THREAD

**Issue by MarkyMarkMcDonald** [cloudfoundry/cli#497]
The commands I keep in the back of my mind are `cf help` and `cf help <command>`.
I find myself wishing `cf help <command>` would give a list of related commands would appear so that I don't always have to scan through `cf help` for the name of the command I want to look up.

E.g. `cf help services` gives 

```
NAME:
   services - List all service instances in the target space

ALIAS:
   s

USAGE:
   cf services
```

and I'd like it to also include

```
RELATED COMMANDS:
   marketplace, service, create-service, update-service, delete-service, rename-service, bind-service, unbind-service
```

So that I know my next help command should be `cf help bind-service`.

Is this something that is in the works? If I created a pull request, is this something that would be merged in?

**Comment by goehmen** [comment]
Yes - this is part of the overall strategy for refactoring cf help to be more helpful.

https://www.pivotaltracker.com/story/show/82977390

It's coming soon.
