### ISSUE TITLE
How to execute cf push using curl command?

### ISSUE THREAD

**Issue by naveensf** [cloudfoundry/cli#498]
I'm executing cf push command i.e., working fine but i want that cf push command using curl 

command:
cf push HelloWorld -b https://github.com/naveensf/bluemix.git -n helloworld -m 256M -c 'node app.js'

i want this command using curl how to do this 

And i want cf oauth-token
 command using curl for dynamic oauth-token

**Comment by goehmen** [comment]
@naveensf see this story https://www.pivotaltracker.com/story/show/78235856 for all the things a `cf push` does.  You'd need to account for all in a curl'd push.

It looks like the main issue is you are using an external auth server and you are trying to push with some auth token that is not native to UAA/CF.  Is that right?

**Comment by naveensf** [comment]
I want to push code using node.js to bluemix app deploying for that i am using curl operation pls help me

**Comment by jabrena** [comment]
@naveensf Hi, I am trying to do the same thing with Node.
Take a look my project here:
https://github.com/jabrena/cf-nodejs-client

I am using "cf_nise_installer" as the platform.

**Comment by camelpunch** [comment]
See the conversation at https://www.pivotaltracker.com/n/projects/892938/stories/78235856. Please comment / reopen if you feel strongly otherwise.

**Comment by naveensf** [comment]
@jabrena  Hi i am trying https://github.com/jabrena/cf-nodejs-client while running example code it giving error. can u help me on this

Error:
/home/opteamize/Desktop/testing/node_modules/cf-nodejs-client/lib/utils/HttpUtils.js:33
    return new Promise(function (resolve, reject) {
               ^
ReferenceError: Promise is not defined
    at HttpUtils.request (/home/opteamize/Desktop/testing/node_modules/cf-nodejs-client/lib/utils/HttpUtils.js:33:16)
    at CloudFoundry.getInfo (/home/opteamize/Desktop/testing/node_modules/cf-nodejs-client/lib/model/CloudFoundry.js:36:22)
    at Object.<anonymous> (/home/opteamize/Desktop/testing/test.js:12:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
