### ISSUE TITLE
cf login doesn't honor .netrc

### ISSUE THREAD

**Issue by Stwissel** [cloudfoundry/cli#499]
When building scripted automation credentials are critical. Hardcoding them into scripts isn't a good idea. GIT, FTP, curl and others use the file .netrc to lookup credentials if present. Could the cf cli be extended to do that too? (Or is there another mechanism?). I would suggest to extend the syntax like this:
      cf login --netrc

Thx for the good work!

**Comment by tjarratt** [comment]
This is a really cool idea, thanks for sharing this bit of unix wisdom with the community @Stwissel ! I had never seen this before, but I feel a lot more knowledgable now that I know about `.netrc`.

**Comment by tjarratt** [comment]
Any idea how this might work on Windows? (is there something comparable?)

**Comment by Stwissel** [comment]
Yes - works on Windows too. In windows you need an environment variable HOME pointing to your home directory (afaik that var is part of a default install now) and the file must be _netrc (not .netrc).

Proper access is required: only current user must be able to read. 




Would be REALLY helpful in cf



—
Pegged on Glas Stephan H. Wissel

+65 9667 3269

@notessensei

**Comment by simonleung8** [comment]
@Stwissel Thanks for suggesting the feature.

Please follow our tracker story for future updates.
https://www.pivotaltracker.com/story/show/97864114
