### ISSUE TITLE
Can't create/update buildpack

### ISSUE THREAD

**Issue by MrEnzyme** [cloudfoundry/cli#500]
I'm having an issue where I can't upload any buildpack to cloudfoundry; it says "The buildpack upload is invalid: a filename must be specified" and the cf_trace confirms it's sending a null value for filename. The thing is, I have specified a file name every time and get this error. I've used a few different CLI versions and uploaded different buildpacks as both zip files/directories, and nothing works.
CLI is version 6.11.2, CF api version 2.23.0

Here's the trace output: https://gist.github.com/MrEnzyme/7ebd45c9c34151a52050

**Comment by camelpunch** [comment]
@MrEnzyme still a problem?

**Comment by MrEnzyme** [comment]
This turned out to be an issue with nginx disabled; turns out buildpacks can't be uploaded to the CC unless nginx is used
