### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Kriil** [cloudfoundry/cli#501]
Tell us that you ran this command:

		/usr/bin/cf-orig/cf push OpenFDA-Tracker-API

	using this version of the CLI:

		6.7.0-IDS

	and that this error occurred:

		runtime error: invalid memory address or nil pointer dereference

	and this stack trace:

		goroutine 16 [running]:
	main.generateBacktrace(0x0, 0x0)
		/root/gocode/src/github.com/cloudfoundry/cli/main/main.go:147 +0xcf
	main.handlePanics(0x7f2c2653dad0, 0xc208043900)
		/root/gocode/src/github.com/cloudfoundry/cli/main/main.go:131 +0x15e
	runtime.panic(0x9f9d00, 0x19249b3)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x18d
	github.com/cloudfoundry/cli/cf/net.Gateway.performRequestForResponseBytes(0x7f2c26542ab0, 0xc20804f830, 0x167d190, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7f2c26542890, 0xc20807ae40, ...)
		/root/gocode/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:248 +0x2e4
	github.com/cloudfoundry/cli/cf/net.Gateway.PerformPollingRequestForJSONResponse(0x7f2c26542ab0, 0xc20804f830, 0x167d190, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7f2c26542890, 0xc20807ae40, ...)
		/root/gocode/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:287 +0x2a9
	github.com/cloudfoundry/cli/cf/net.Gateway.createUpdateOrDeleteResource(0x7f2c2

**Comment by goehmen** [comment]
@Kriil Can you update your CLI and see if the issue is resolved.  6.7.0 is fairly old now & we've addressed a few bugs. 

If the issue still exists after update, then rerun the failing command with CF_TRACE=true and cleanse and send the output.  Also send the output from `cf curl /v2/info` so we can see what version of the runtime you are hitting.

**Comment by goehmen** [comment]
@Kriil I trust that upgrading your CLI resolved the issue.  IF not, please reopen this issue.
