### ISSUE TITLE
runtime error: index out of range

### ISSUE THREAD

**Issue by renannprado** [cloudfoundry/cli#502]
Aww shucks.

 Something completely unexpected happened. This is a bug in cf.
 Please file this bug : https://github.com/cloudfoundry/cli/issues
 Tell us that you ran this command:

         cf api http://localhost:9999

 using this version of the CLI:

         6.11.3-cebadc9

 and that this error occurred:

         runtime error: index out of range

 and this stack trace:

         goroutine 1 [running]:
 main.generateBacktrace(0xc08401ee40, 0x3)
         C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xac
 main.handlePanics(0x3415d8, 0xc084047d20)
         C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x126
 runtime.panic(0x97cb80, 0x129ac97)
         C:/Users/ADMINI~1/AppData/Local/Temp/2/makerelease155988687/go/src/pkg/runtime/panic.c:248 +0x11b
 github.com/cloudfoundry/cli/cf/api.defaultLoggregatorEndpoint(0xc0840035e0, 0x15, 0x0, 0x1)
         C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/api/endpoints.go:98 +0x2a6
 github.com/cloudfoundry/cli/cf/api.RemoteEndpointRepository.attemptUpdate(0x341998, 0xc0840419f0, 0x34b6d0, 0xc08406fab0, 0xb63f80, ...)
         C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/api/endpoints.go:83 +0x2e5
 github.com/cloudfoundry/cli/cf/api.RemoteEndpointRepository.UpdateEndpoint(0x341998, 0xc0840419f0, 0x34b6d0, 0xc08406fab0, 0xb63f80, ...)
         C:/GoAgent/pipelines/Win

**Comment by goehmen** [comment]
@renannprado Is there another CF environment that you can point to to retry the `cf api` command?  Trying to determine whether this is something wrong with your local install/env since you are hitting localhost.

**Comment by goehmen** [comment]
@renannprado Were you able to resolve this by hitting another API endpoint?  If not, please reopen the issue.
