### ISSUE TITLE
Failed deploying sample `Spring Music` application

### ISSUE THREAD

**Issue by kennetham** [cloudfoundry/cli#504]
Why am I getting this failed error? How do I fix this?

```log
Warning: error tailing logs
Error dialing loggregator server: dial tcp 10.232.xxx.xx:4443: connection refused.
Please ask your Cloud Foundry Operator to check the platform configuration (loggregator endpoint is wss://loggregator.xxx.xxx.intra.xxx.co.jp:4443).
Starting app spring-music in org yrl / space testgradle-01 as admin...
FAILED
Server error, status code: 400, error code: 170001, message: Staging error: no available stagers
```

**Comment by goehmen** [comment]
@kennetham The "no available stagers" error  can happen when you do not have enough resources to allocate an app instance on a DEA.  Probably you need to increase the size or number of DEAs to accommodate this app push.

**Comment by kennetham** [comment]
@goehmen yup you are right! I have expanded the resources. Thank you for clarifying!
