### ISSUE TITLE
Please help me what went wrong here..

### ISSUE THREAD

**Issue by paranigit** [cloudfoundry/cli#510]
Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		/usr/bin/cf-orig/cf push InsuranceDigest

	using this version of the CLI:

		6.7.0-IDS

	and that this error occurred:

		runtime error: invalid memory address or nil pointer dereference

	and this stack trace:

		goroutine 16 [running]:
	main.generateBacktrace(0x0, 0x0)
		/root/gocode/src/github.com/cloudfoundry/cli/main/main.go:147 +0xcf
	main.handlePanics(0x7f42d379e990, 0xc208043900)
		/root/gocode/src/github.com/cloudfoundry/cli/main/main.go:131 +0x15e
	runtime.panic(0x9f9d00, 0x19249b3)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x18d
	github.com/cloudfoundry/cli/cf/net.Gateway.performRequestForResponseBytes(0x7f42d37a39e8, 0xc20804f830, 0x167d190, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7f42d37a37c8, 0xc20807ae40, ...)
		/root/gocode/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:248 +0x2e4
	github.com/cloudfoundry/cli/cf/net.Gateway.PerformPollingRequestForJSONResponse(0x7f42d37a39e8, 0xc20804f830, 0x167d190, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x7f42d37a37c8, 0xc20807ae40, ...)
		/root/gocode/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:287 +0x2a9
	github.com/cloudfoundry/cli/cf/net.Gateway.createUpdateOrDeleteResource(0x7f42d

Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by goehmen** [comment]
@paranigit - please try updating your version of the CLI and verify whether the error reproduces.  6.7.0 is a pretty old.  Newest versions are here:  https://github.com/cloudfoundry/cli/releases

**Comment by goehmen** [comment]
@paranigit It appears that the CLI upgrade resolved the issue.  If not, please reopen the issue and we will take another look.
