### ISSUE TITLE
Something completely unexpected happened. This is a bug in cf.

### ISSUE THREAD

**Issue by wjk940** [cloudfoundry/cli#511]
Tell us that you ran this command:

		cf st green

	using this version of the CLI:

		6.12.1-56792aa

	and that this error occurred:

		runtime error: index out of range

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x3)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:175 +0xa9
	main.handlePanics(0x116fb78, 0xc2101847d0)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:159 +0x123
	runtime.panic(0x5a5b80, 0xf0d8b7)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc210273c00, 0xc21054d870, 0x24, 0xc2105419c0, 0x2, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x275
	github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc21006d230, 0xc21054d870, 0x24, 0xc210513a08, 0x5, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:179 +0x6e0
	github.com/c

**Comment by goehmen** [comment]
@wjk940 - it looks like a component of logging is not running properly in your env.  Could be doppler but not sure.  it would be the component that is responsible for providing the3metric that the CLI expects to consume when the start command runs.

**Comment by goehmen** [comment]
@wjk940 We are addressing this issue the best we can from the CLI side by returning a more descriptive error message when the problem is encountered so that users can better diagnose and resolve the issue.

https://www.pivotaltracker.com/story/show/98672332 is the bug we are fixing.
