### ISSUE TITLE
curl should provide a link to the API docs

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cli#512]
I've found that the API docs (for example, http://apidocs.cloudfoundry.org/) are pretty difficult for many app developers to discover. It would be useful if the help for `cf curl` linked to the docs (either the standard http://apidocs.cloudfoundry.org/ or a custom docs URL based on the target cloud foundry, if possible) so that users who started diving into the API had a point of reference.

**Comment by goehmen** [comment]
done.  It is in 6.12.2


add tip to curl command for api doc url [#98862944]
