### ISSUE TITLE
Error running cf push

### ISSUE THREAD

**Issue by ryanjones71** [cloudfoundry/cli#513]
Tell us that you ran this command:
 
 		cf push -f manifest-dev.yml -p event.notify.register.jar
 
 	using this version of the CLI:
 
 		6.11.2.lds-205a2a7
 
 	and that this error occurred:
 
 		NewMap called with unexpected argument
 
 	and this stack trace:
 
 		goroutine 1 [running]:
 	main.generateBacktrace(0xc21000a000, 0x6)
 		/opt/anthill3/agent/var/jobs/projects/CLI/Project_Build/src/github.com/cloudfoundry/cli/main/main.go:177 +0xa9
 	main.handlePanics(0x7f34613735d8, 0xc21006b560)
 		/opt/anthill3/agent/var/jobs/projects/CLI/Project_Build/src/github.com/cloudfoundry/cli/main/main.go:161 +0x123
 	runtime.panic(0x8a9300, 0xc210193740)
 		/opt/go/src/pkg/runtime/panic.c:248 +0x106
 	github.com/cloudfoundry/cli/generic.NewMap(0xc210193720, 0x1, 0x1, 0x88f340, 0xc210165600)
 		/opt/anthill3/agent/var/jobs/projects/CLI/Project_Build/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/generic/map.go:56 +0x79b
 	github.com/cloudfoundry/cli/generic.mergeReducer(0x8a9300, 0xc210196db0, 0x8a4b00, 0xc210164ea0, 0x7f3461383138, ...)
 		/opt/anthill3/agent/var/jobs/projects/CLI/Project_Build/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/generic/merge_reduce.go:28 +0x1f7
 	github.com/cloudfoundry/cli/generic.Reduce(0x7f34611ed6b0, 0x2,

**Comment by simonleung8** [comment]
Hey there,

Could you please post the manifest you used? Looks like there might be an error in how we parse it.

Thanks,

**Comment by ryanjones71** [comment]
I figured the problem out.  I was trying to put some of the properties for
application in the mainfest-dev.yml and others in the base-manifest.yml and
the dev.yml was missing the -name: line under applications.  I found that
it wouldn't even work with that, because it thought they were 2 separate
applications.

This bug can be closed.
