### ISSUE TITLE
Downloading the bits for a package recognizing text only

### ISSUE THREAD

**Issue by jeffpak93** [cloudfoundry/cli#516]
Currently, downloading the bits for a package using cf curl /v2/apps/:guid/download doesn't return the same bits as a regular curl. We think this has something to do with the bits being returned in text mode, rather than in binary.

For example, `cf curl /v2/apps/:guid/download | sha1sum` is different than `curl https://api.example.com/v2/apps/:guid/download | sha1sum`.

**Comment by simonleung8** [comment]
@jeffpak93 
We couldn't reproduce the issue using OSX.

Curl wasn't able to download the app bits when we used the `curl` command you have posted, we had to manually extract the redirected URL from curl and issue a second curl for the download to work. Both `cf curl` and `curl` produced the same shasum.

**Comment by dkoper** [comment]
Closing as not reproducible. Feel free to re-open if you can help us reproduce it with the latest cf CLI release.

* CLI team
