### ISSUE TITLE
Selective "cf push" with manifest 

### ISSUE THREAD

**Issue by bsideup** [cloudfoundry/cli#517]
Hi!

We have manifest.yml with few apps. But sometimes we want to push only one app. 

I know that we can split manifest.yml into few small manifests, but it's not so handful to run "cf push" on each in case if we want to push all.

Would be cool if in case of manifest push there will be switch `--only=foo,bar` to deploy only "foo" and "bar" apps from this manifest.

Thanks!

**Comment by goehmen** [comment]
@bsideup That is a cool idea but goes against the core set of rules we currently have for app manifests.  Right now, you'd have to settle for having multiple manifests that specify a given app of subsets of the whole set of apps.
