### ISSUE TITLE
CLI reports version requirement for CF API even though it's more recent.

### ISSUE THREAD

**Issue by danhigham** [cloudfoundry/cli#518]
Calling `cf target` against API version 2.25.0 with CLI version "6.11.3-cebadc9" returns the following error;

"Cloud Foundry API version 2.25.0 requires CLI version 6.7.0.  You are currently on version 6.11.3-cebadc9. To upgrade your CLI, please visit: https://github.com/cloudfoundry/cli#downloads"

**Comment by goehmen** [comment]
known bug - https://www.pivotaltracker.com/story/show/98664206
fixed in 6.12.2
