### ISSUE TITLE
401 Suppresses Any Error Message

### ISSUE THREAD

**Issue by cholick** [cloudfoundry/cli#521]
In authentication.go, every error with a 401 is translated into a generic message and any errors coming back from the UAA server are suppressed:
```
...
	case errors.HttpError:
		if response.StatusCode() == 401 {
			apiErr = errors.New(T("Credentials were rejected, please try again."))
		}
	}
...
```

Our implementation of the login server returns 401 for different reasons (account locked, invalid password/username combo, & others).

Would you accept a pull request that surfaced these errors similar to the way that every non-401 error is surfaced?

**Comment by goehmen** [comment]
@cholick Yes, I'd be interested in that PR
