### ISSUE TITLE
Error read/writing plugin config

### ISSUE THREAD

**Issue by littlepd** [cloudfoundry/cli#522]
Whenever I try to execute any cf command, I get the following error message:

FAILED
Error read/writing plugin config: mkdir N:\\.cf: Access is denied.,

My N: drive is mapped to my organizations shared Home folder. I have my own personal folder under Home to which I can write. But only the network admin has rights to the Home root.

Why is cf using N:\?

How can I change it?

**Comment by littlepd** [comment]
As a workaround, I temporarily remapped my N: drive to a local folder. But my N: drive is mapped to the network share during boot up, and I'd like to not have to remap it every time I want to use the cf cli. Where can I set the default location that cf uses away from N: to somewhere else?

**Comment by goehmen** [comment]
@littlepd Look at $CF_PLUGIN_HOME.  When you get that error, $CF_PLUGIN_HOME is probably not set.  If you set that variable to a directory where you have write permissions, you should be OK.

If this isn't the case, repoen the issue and let us know.

**Comment by littlepd** [comment]
Is that some sort of environment variable or something? Is it created
during installation?



*Michael Daly*

Senior Consultant/Developer

[image: KS2 site-logo]

KS2 Technologies, Inc.

1020 Mustang Drive | Grapevine, Texas 76051
(o)  817.310.1813 | (m) 214.477.9078 | (f) 817.310.1801

mdaly@ks2inc.com | http://www.ks2inc.com





*From:* greg oehmen [mailto:notifications@github.com]
*Sent:* Monday, July 27, 2015 5:56 PM
*To:* cloudfoundry/cli
*Cc:* littlepd
*Subject:* Re: [cli] Error read/writing plugin config (#522)



@littlepd <https://github.com/littlepd> Look at $CF_PLUGIN_HOME. When you
get that error, $CF_PLUGIN_HOME is probably not set. If you set that
variable to a directory where you have write permissions, you should be OK.

If this isn't the case, repoen the issue and let us know.

—
Reply to this email directly or view it on GitHub
<https://github.com/cloudfoundry/cli/issues/522#issuecomment-125373548>.

**Comment by mattzwol** [comment]
I just encountered this issue after a fresh install of the CF CLI on Windows 7. I was able to fix it by editing the environment variables in control panel (Control Panel - System and Security - System - Advanced System Settings). Then go to "Environment Variables". Add a "New" variable under the user variables. The variable name should be CF_HOME. Make the value a directory that you can write to. e.g. the one I used (which I had created) was C:\CF. Once you press OK, you may need to close any CMD console you have and re-open it for CF to work.

**Comment by bhaskarv82** [comment]
I happens in cli 6.23.0 but works fine with 6.19.0 (https://github.com/cloudfoundry/cli/releases/tag/v6.19.0)

**Comment by bhaskarv82** [comment]
How do I report it to pivotal?

**Comment by bhaskarv82** [comment]
It works fine with 6.19.0 but doesn't work with 6.23.0
https://github.com/cloudfoundry/cli/releases/tag/v6.19.0
