### ISSUE TITLE
Problem creating an App using CF REST API

### ISSUE THREAD

**Issue by jabrena** [cloudfoundry/cli#525]
Hi, I am testing the REST API and I am trying to create an App in a Cloud Foundry instance.

Using the documentation:
http://apidocs.cloudfoundry.org/213/apps/creating_an_app.html

The method only need for header:

``` javascript

    var headers = {
        'Authorization': token_type + " " + access_token,
        'Content-Type': 'application/x-www-form-urlencoded',
        'Cookie' : ''
    };

```

and for body:

``` javascript

    var form = {
        "name": "my_super_app",
        "space_guid": "e558b66a-1b9c-4c66-a779-5cf46e3b060c"
    };  

```

Why I receive the following message?

``` json
{
  "code": 1001,
  "description": "Request invalid due to parse error: lexical error: invalid char in json text.\\\n                                       space_guid=7ef3c4e0-350d-11e5-b\\\n                     (right here) ------^\\\n",
  "error_code": "CF-MessageParseError"
}

```

Many thanks in advance.

Juan Antonio

**Comment by goehmen** [comment]
@jabrena Are you trying to do the equivalent of `cf push` via the api?  Push does much more that create an app.

**Comment by jabrena** [comment]
Yes, I can publish a local application using CLI (cf push), but now, If i try to call REST API, I have this problem.

I was reading this old article:
http://www.activestate.com/blog/2015/01/get-some-rest-delving-cloud-foundry-rest-api

and I discovered that cf push, executes:

```
1. get space uuid
2. add app
3. set route
4. upload app
5. start app
```

I get the uuid from current spaces, but when I execute the REST call using Postman, I receive the previous problem:

``` javascript
{
  "code": 1001,
  "description": "Request invalid due to parse error: lexical error: invalid char in json text.\\\n                                       space_guid=7ef3c4e0-350d-11e5-b\\\n                     (right here) ------^\\\n",
  "error_code": "CF-MessageParseError"
}
```

Did I forget anything in my test with Postman?

http://apidocs.cloudfoundry.org/213/apps/creating_an_app.html

``` javascript
name	The name of the app.	my_super_app
space_guid	The guid of the associated space.	78857449-5d4d-4087-af3c-3590c3058bba
```

Do I need any additional input?

Juan Antonio

**Comment by goehmen** [comment]
During the CLI teams's plugin work, I had them decompose push to better understand how plugins would interact with push or components of it.  Check out https://www.pivotaltracker.com/story/show/78235856

What exactly is your goal?  Simply to further knowledge of the API?  script/automate app pushes?  Other?  I ask because `cf push` is complex and is not something we recommend recreating via API

**Comment by jabrena** [comment]
I am trying to automate the process using Node.js with a UI.

Nice URL:
https://www.pivotaltracker.com/n/projects/892938/stories/78235856

My question is about this point (3. creates or updates app with app params). I use login token without any problem. If you execute the REST call with a bad token, system return a auth error.

In this URL, I think that writer forgot explaining that it is necessary to get space uuid using a REST call.

Do you have more detail about about the call to create app?

What is the source of cf push?
Maybe checking the code, it is possible to solve the problem, I mean.

**Comment by jabrena** [comment]
Hi, I coded latest atomic tests and I receive the following message:

404 Not Found: Requested route ('dev') does not exist.

dev is an space defined when I execute v2/apps (POST)

```

//Add a new App
cloudFoundry.getInfo().then(function (result) {
	token_endpoint = result.token_endpoint;	
    return cloudFoundry.login(token_endpoint,config.username,config.password);
}).then(function (result) {    
    return cloudFoundrySpaces.getSpaces(result.token_type,result.access_token); 
}).then(function (result) {
	space_guid = result.resources[0].metadata.guid;	
    return cloudFoundry.login(token_endpoint,config.username,config.password);
}).then(function (result) { 	
    return cloudFoundryApps.addApp(result.token_type,result.access_token,appName, space_guid);
}).then(function (result) {
    console.log(result);   
}).catch(function (reason) {
    console.error("Error: " + reason);
});

```

Is it necessary to create a route?

**Comment by jabrena** [comment]
I Fixed the problem, I had a problem with the way than I send data to REST Api:

Before:

``` Javascript

    var form = {
        "name": "my_super_app",
        "space_guid": "e558b66a-1b9c-4c66-a779-5cf46e3b060c"
    }; 

```

Now:

```  Javascript

    var body = JSON.stringify({
        "name": name,
        "space_guid": space_guid
    })   

```

**Comment by jabrena** [comment]
@goehmen Many thanks for the support. :)

**Comment by abiksr** [comment]
@jabrena Hello, I am trying to achieve the exact same functionality that you did. I wanted to automate the deployment. I am stuck in the final stage where I upload the bis. I am able to upload the bit successfully and start the app but I wanted to include manifest.yml file with configurations. When I zip the app and manifest.yml file, it does not seems to honor the yml file. Did you get it working ?
