### ISSUE TITLE
Crashing bug when creating app manifest for ASP.NET app at BlueMix 

### ISSUE THREAD

**Issue by JanSichula** [cloudfoundry/cli#526]
Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		cf create-app-manifest aspnet-1-jany-helloworld

	using this version of the CLI:

		6.12.2-24abed3

	and that this error occurred:

		runtime error: invalid memory address or nil pointer dereference

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0x0, 0x0)
		C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xce
	main.handlePanics(0x199ba8, 0xc0821c86f0)
		C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x1ab
	github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).createManifest(0xc0822089c0, 0xc0822a5200, 0x24, 0xc082201740, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
		C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:91 +0x8c
	github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).Execute(0xc0822089c0, 0x19a908, 0xc082177a80)
		C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:87 +0x4d9
	main.main()
		C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:81 +0xcdd
	
	goroutine 360 [IO wait]:
	net.(*pollDesc).Wait(0xc0821a8d70, 0x72, 0x0, 0x0)
		c:/go/src/net/fd_poll_runtime.go:84 +0x4e
	net.(*ioSrv).

**Comment by goehmen** [comment]
@JanSichula I'm trying to verify with IBM what version of runtime Bluemix is running on to make sure that   the `create-app-manifest` feature is available.  You might want to open a ticket with IBM/Bluemix team on this too.

**Comment by goehmen** [comment]
I have not heard back from IBMers.  Have you?

**Comment by jmcvea** [comment]
I get a similar 'Aww shucks.  Something completely unexpected...' message when running `cf create-app-manifest myRubyApp`.

This occurs running cf version 6.12.2-24abed3.  If I drop back to 6.12.1-56792aa, then the command works as expected.

The current version of CF for Bluemix is 210.8.

Another odd thing with the 6.12.2-24abed3 version and the create-app-manifest command is that the response to the console includes information about the 'logs' command as shown below.  The correct usage information is displayed with the previous 6.12.1-56792aa version:
```
$ cf create-app-manifest
FAILED
Incorrect Usage. Requires app name as argument

NAME:
   logs - Tail or show recent logs for an app

USAGE:
   CF_NAME logs APP_NAME

OPTIONS:
   --recent      Dump recent logs instead of tailing
```

**Comment by JanSichula** [comment]
Hello Greg,

thank you for your effort but I have decided not to contact IBM at this time since they explicitly warn that this is experimental build-pack without support. I looks like the ASP.NET at Bluemix needs more time as it is really only at an early and experimental stage.

**Comment by afeld** [comment]
I don't think this is an IBM-specific problem...I'm having the same issue on the community version.

/cc #536 #549

**Comment by simonleung8** [comment]
Thanks for filing the bug, we have a story in the tracker and will be fixed in the next release.

https://www.pivotaltracker.com/story/show/101367528
