### ISSUE TITLE
bin/generate-language-resources dependency not called out

### ISSUE THREAD

**Issue by krishicks** [cloudfoundry/cli#529]
I was trying to run unit tests on the utils package recently and ran into an issue:

```bash
$ cd $GOPATH/src/github.com/cloudfoundry/cli/utils
$ ginkgo .
Failed to compile utils:

../cf/i18n/init.go:13:2: cannot find package "github.com/cloudfoundry/cli/cf/resources" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/cloudfoundry/cli/cf/resources (from $GOROOT)
	/Users/krishicks/.go/src/github.com/cloudfoundry/cli/cf/resources (from $GOPATH)

Ginkgo ran 1 suite in 1.110890964s
Test Suite Failed
```

The same error will occur when trying to run `go build ./main`, of course.

It wasn't clear to me that I needed to run `bin/generate-language-resources`, which is a step that is done within `bin/test` and `bin/build`.

Nowhere does it say in the README that building the project requires running `bin/generate-language-resources` first. I only figured it out by running a grep for the package name.

**Comment by dsabeti** [comment]
+1

More importantly, the github.com/cloudfoundry/cli/plugin package is not go gettable because of this. We are in the process of developing a plugin and came across this problem.

**Comment by maximilien** [comment]
Off topic: @dsabeti are you back? Nice!

**Comment by camelpunch** [comment]
@dsabeti (warning: go noob). I can't reproduce the go-getting problem. Can you explain further? Perhaps it's gone away since your comment.
