### ISSUE TITLE
Allow route to be mapped after app has been started.

### ISSUE THREAD

**Issue by mdelillo** [cloudfoundry/cli#533]
We have a use case where we would like to specify the domain and hostname for our app in the manifest.yml, but when we push we don't want the route mapped until the end. Our current workaround is to add `no-route: true` to our manifest and then map the route by hand after the push. It would be really nice if there were an option we could specify when pushing (or even better, in our manifest since it describes multiple apps) that would defer route mapping until the end of the push.

**Comment by camelpunch** [comment]
Thanks for the feature request. Since it's now in Tracker, you can track its progress there.

**Comment by dkoper** [comment]
Hi @mdelillo 

I'm trying to understand your use case. What do you mean by "the end"? What's the impact of the difference in timing of mapping the route?

Cheers,
Dies Koper
CF CLI PM

**Comment by mdelillo** [comment]
I think what I meant was that binding the route to the app should happen after the app is started. This way if a user tries to visit the route, they don't get sent to an app that is still starting. But I was unable to actually reproduce the original problem and I'm no longer on the project that needed this.
