### ISSUE TITLE
CLI blows up when getting app status when the app is down.

### ISSUE THREAD

**Issue by slackersoft** [cloudfoundry/cli#538]
This only seems to happen after I have stopped the app, when it's running it works just fine.

Tell us that you ran this command:

    cf app past-time

using this version of the CLI:

    6.12.2-24abed3

and that this error occurred:

    runtime error: index out of range

and this stack trace:

````
  goroutine 1 [running]:
main.generateBacktrace(0xc21000a000, 0x3)
  /Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xa9
main.handlePanics(0x116b9a0, 0xc2101865c0)
  /Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x123
runtime.panic(0x5a3660, 0xf08d17)
  /usr/local/go/src/pkg/runtime/panic.c:248 +0x106
github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc21026b900, 0xc2100cff90, 0x24, 0x0, 0x0, ...)
  /Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x275
github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc21006fa80, 0xc2100cff90, 0x24, 0xc2100a4940, 0x9, ...)
  /Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:179 +0x6e0
github.com/cloudfound
````

**Comment by goehmen** [comment]
Yes.  This is indicative of an incorrect logging environment setup.  The CLi is not getting the correct response from `/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68`.  The CLI team is wroking on a bug right now to improve the error message to assist with troubleshooting this error.  The improvement will be in the next release 6.12.3.
