### ISSUE TITLE
some commands displaying CF_NAME the help usage

### ISSUE THREAD

**Issue by dieucao** [cloudfoundry/cli#539]
Some commands are displaying CF_NAME in usage in the help
```
$ cf org
FAILED
Incorrect Usage. Requires an argument

NAME:
   org - Show org info

USAGE:
   CF_NAME org ORG

OPTIONS:
   --guid      Retrieve and display the given org's guid.  All other output for the org is suppressed.
```

Also the
cf org-users
cf space-users
cf space
cf create-service

**Comment by simonleung8** [comment]
Hi, we have addressed this bug in this story
https://www.pivotaltracker.com/story/show/100453848

Closing. Thanks.
