### ISSUE TITLE
Migrate dependencies away from code.google.com

### ISSUE THREAD

**Issue by dprotaso** [cloudfoundry/cli#541]
godep restore warns:

warning: code.google.com is shutting down; import path code.google.com/p/go.crypto/ssh/terminal will stop working
warning: code.google.com is shutting down; import path code.google.com/p/go.net/websocket will stop working
warning: code.google.com is shutting down; import path code.google.com/p/gogoprotobuf/proto will stop working

**Comment by camelpunch** [comment]
Fixed with https://github.com/cloudfoundry/cli/commit/7113930c199c8cd0210eefa8716c9445b9cc58e8
