### ISSUE TITLE
cf files adds a newline to downloaded files.

### ISSUE THREAD

**Issue by jhellan** [cloudfoundry/cli#545]
When used to download a file, `cf files` adds a newline to it.
The reason is that `cf files` uses `cf curl` to download, and `cf curl` adds the newline.
For many use cases for `cf curl`, this makes sense, so I'm filing the bug against `cf files`.

Manually removing a newline from a single file is no big deal. But when there are many
(e.g  the `cf download` plugin), it gets old fast.

**Comment by camelpunch** [comment]
@jhellan thanks for the report. What are these use cases of `cf curl` where it makes sense to change the downloaded file?
