### ISSUE TITLE
Downloads are broken

### ISSUE THREAD

**Issue by jszroberto** [cloudfoundry/cli#550]
Hi guys, when you try to download a binary or installer an internal server error is shown.

**Comment by camelpunch** [comment]
Thanks @jszroberto! I've been downloading these today and the issue seems to be resolved.

**Comment by dkoper** [comment]
We found an issue with our downloads when you use a browser configured with a preferred language without country (e.g. 'en', as opposed to 'en-US', 'fr-FR', etc.). Tracking this here https://www.pivotaltracker.com/story/show/105519946. Until resolved, the work around is to include a country code.

**Comment by dkoper** [comment]
The issue I referred to above has now been fixed. Please open another issue if you encounter download problems again. Thanks!
