### ISSUE TITLE
As a golang developer, I want the cf/api package to be an independent library, so that I can leverage the CLI CC API abstraction without dependency on the CLI process

### ISSUE THREAD

**Issue by guidowb** [cloudfoundry/cli#552]
It seems that what we have there is a complete golang client similar to the java and javascript clients. If it were extracted, but still used by the CLI, it would be guaranteed to be maintained and supported (unlike someone else building a golang client that's not consumed by the CLI)

**Comment by guidowb** [comment]
Also seems like this would potentially eliminate a body of code to maintain in the plugin rpc layer, so might be even more powerful written as "As a CLI developer, ..."
![cliplugins](https://cloud.githubusercontent.com/assets/5896094/9309010/c81302ca-44cc-11e5-81ee-e41ee19bfaf4.png)

**Comment by camelpunch** [comment]
Cool diagram. This is now managed in Tracker!
