### ISSUE TITLE
As a plugin developer, I want the plugin submission process to accept source code, so that I don’t have to version and maintain cross-platform binaries in Github

### ISSUE THREAD

**Issue by guidowb** [cloudfoundry/cli#554]
I'd love to be able to just submit a github commit SHA, and have the plugin repo do the cross-platform builds, computing of checksums, and storing/serving of the various binaries.

**Comment by drnic** [comment]
A shared concourse installation for each plugin could be handy here

**Comment by camelpunch** [comment]
We're still going through our Concourse transition. After that, this might have a chance. You can follow progress in the Tracker story.
