### ISSUE TITLE
SSO link is incorrect for v1.5+ of PCF

### ISSUE THREAD

**Issue by xchapter7x** [cloudfoundry/cli#556]
When issuing a `cf login --sso` against a install of PCF 1.5+ the given url is for the uaa.
This no longer works, as it requires the login url instead.

ex.
`One Time Code (Get one at https://uaa.run.pez.pivotal.io/passcode)`
should be
`One Time Code (Get one at https://login.run.pez.pivotal.io/passcode)`

the prompt is coming from login, but the data seems to be set down in endpoints.go... 
https://github.com/cloudfoundry/cli/blob/master/cf/api/endpoints.go#L80
https://github.com/cloudfoundry/cli/blob/master/cf/commands/login.go#L128

**Comment by fhanik** [comment]
It will be available in the next release
https://www.pivotaltracker.com/n/projects/997278/stories/96567690

**Comment by camelpunch** [comment]
Story's done.
