### ISSUE TITLE
should a higher version give a warning?

### ISSUE THREAD

**Issue by mikfreedman** [cloudfoundry/cli#567]
If we are using a higher version than the API requires, should this message be shown? If so, then maybe the messaging should indicate that the version is in fact **higher**

```bash
Cloud Foundry API version 2.25.0 requires CLI version 6.7.0.  You are currently on version 6.11.1-4ef66f6. To upgrade your CLI, please visit: https://github.com/cloudfoundry/cli#downloads
```bash

**Comment by simonleung8** [comment]
It is a bug in the older version of CLI, the problem has been resolved in the latest CLI.
