### ISSUE TITLE
cf create-app-manifest <appname>  -  runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by insanitysauce** [cloudfoundry/cli#568]
Aww shucks.
 
        Something completely unexpected happened. This is a bug in cf.
        Please file this bug : https://github.com/cloudfoundry/cli/issues
        Tell us that you ran this command:
 
                cf create-app-manifest bigapp
 
        using this version of the CLI:
 
                6.12.2.lds-f35526e
 
        and that this error occurred:
 
                runtime error: invalid memory address or nil pointer dereference
 
        and this stack trace:
 
                goroutine 1 [running]:
        main.generateBacktrace(0xc08401cde0, 0x3)
                /opt/anthill3/agent/var/jobs/projects/CLI/Project_Build/src/github.com/cloudfoundry/cli/main/main.go:177 +0xac
        main.handlePanics(0x37b2d0, 0xc0840885e0)
                /opt/anthill3/agent/var/jobs/projects/CLI/Project_Build/src/github.com/cloudfoundry/cli/main/main.go:161 +0x126
        runtime.panic(0x9e85c0, 0x13bb10f)
                /opt/go-1.2.2/src/pkg/runtime/panic.c:248 +0x11b
        github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).createManifest(0xc08424e660, 0xc0841d02a0, 0x24, 0xc08406c598, 0x6, ...)
                /opt/anthill3/agent/var/jobs/projects/CLI/Project_Build/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:91 +0x5a
        github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).Execute(0xc08424e660, 0x37c030, 0xc08424bc00)
                /opt/anthill3/agent/var/jobs/projects/CLI/Project_Build/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.
com/cloudfoundry/cli/cf/commands/create_app_manifest.go:87 +0x434
        main.

**Comment by insanitysauce** [comment]
I should mention that I've only been able to repro this on Windows 10.

**Comment by simonleung8** [comment]
Thanks for filing the bug, we have a story in the tracker and will be fixed in the next release.

https://www.pivotaltracker.com/story/show/101367528
