### ISSUE TITLE
cf --version is not recognized as valid command

### ISSUE THREAD

**Issue by hhercules** [cloudfoundry/cli#569]
Seems like passing --version is not working. 

[sys]$ cf --version
'--version' is not a registered command. See 'cf help'
[sys]$ cf -v
cf version 6.12.3-c0c9a03-2015-08-31T20:29:20+00:00

/etc/redhat-release
Red Hat Enterprise Linux Server release 6.5 (Santiago)

**Comment by simonleung8** [comment]
Thanks for bringing this up. This will be fixed in the next release.
