### ISSUE TITLE
cf --version doesn't work anymore after upgrade.

### ISSUE THREAD

**Issue by thomasdarimont** [cloudfoundry/cli#574]
--version is broken after upgrading the cf CLI from cf version 6.12.2 to cf version 6.12.3-xxxx.
This happend on ubuntu 15.04.

```code
$ cf -v
cf version 6.12.3-c0c9a03-2015-08-31T20:29:20+00:00
```

```code
$ cf --version
'--version' is not a registered command. See 'cf help'
```

```code
$ cf help
...
GLOBAL OPTIONS:
   --version, -v                      Print the version
```

**Comment by goehmen** [comment]
This was addressed in #102641456.  That fix is in the latest edge binary and will be in the next stable release which appears to be 6.13.4 and looks to be ready to be released in the next week or so.
