### ISSUE TITLE
Marketplace errors on newest cli

### ISSUE THREAD

**Issue by cholick** [cloudfoundry/cli#575]
CLI 6.12.3 fails to generate services or list services against our Cloud Foundry install. The error is:
```
Error parsing JSON: invalid syntax
```

Chasing down recent changes, it looks like this is the issue:

According to the service broker API (https://docs.cloudfoundry.org/services/api.html), metadata is not a required field.

Metadata from the service broker is translated into `extra` at the API layer:
https://github.com/cloudfoundry/cloud_controller_ng/blob/179beaf37d134624e99e67ab957c55ff8a4d779c/lib/services/service_brokers/service_manager.rb#L38
(which defaults to nil)

Pull request #523 by @zachgersh assumes the extra field is de-serializable as json. Empty string will fail to deserialize.

**Comment by camelpunch** [comment]
@cholick can you please confirm that this occurs in 6.12.3?

**Comment by cholick** [comment]
Yes, this would still happen.

API can return an empty string for `extra`. The implementation doesn't support that. Pulled out to demonstrate:

http://play.golang.org/p/xsJh2V1_bB
```
package main

import "fmt"
import "strconv"
import "encoding/json"

type ServiceOfferingExtra struct {
	DocumentationURL string `json:"documentationUrl"`
}

type serviceOfferingExtra ServiceOfferingExtra

func main() {
	extra := serviceOfferingExtra{}

	unquoted, err := strconv.Unquote(string(""))
	if err != nil {
		fmt.Printf("%s", err)
	}

	err = json.Unmarshal([]byte(unquoted), &extra)
	if err != nil {
		fmt.Printf("%s", err)
	}

}
```

**Comment by zachgersh** [comment]
Hey @cholick / @camelpunch - 

This should have been fixed with https://github.com/cloudfoundry/cli/commit/014fc0e88ac1da3ad1df936b7e59a5234d32c5ee

It's in v6.13.0

**Comment by cholick** [comment]
Sorry, my mistake. I think I followed a link to the old source rather than HEAD. Ignore previous comment.

**Comment by camelpunch** [comment]
I of course meant 6.13. Thanks for the update!
