### ISSUE TITLE
Error for "cf create-app-manifest"

### ISSUE THREAD

**Issue by trisberg** [cloudfoundry/cli#576]
$ cf create-app-manifest scd-admin
Creating an app manifest from current settings of app scd-admin ...

	Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		cf create-app-manifest scd-admin

	using this version of the CLI:

		6.12.3-c0c9a03

	and that this error occurred:

		runtime error: invalid memory address or nil pointer dereference

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0x0, 0x0)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:117 +0xc7
	main.handlePanics(0xe1b2f0, 0xc2080ec500)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:101 +0x1a4
	github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).createManifest(0xc208214d80, 0xc20881fda0, 0x24, 0xc208838c16, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:91 +0x85
	github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).Execute(0xc208214d80, 0xe1cb80, 0xc20821cd80)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:87 +0x4d2
	main.main()
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/

**Comment by goehmen** [comment]
Fixed in latest edge binary.  Fix will be in 6.12.4
