### ISSUE TITLE
Index of out range on `cf scale`

### ISSUE THREAD

**Issue by benmoss** [cloudfoundry/cli#578]
○ → cf scale nora -m 2g -i 1

This will cause the app to restart. Are you sure you want to scale nora?> y

Scaling app nora in org org / space space as admin...
OK
Stopping app nora in org org / space space as admin...
OK

Starting app nora in org org / space space as admin...

0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
1 of 1 instances running

App started

OK

App nora was started using this command `tmp/lifecycle/WebAppServer.exe .`

Showing health and status for app nora in org org / space space as admin...

	Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		cf scale nora -m 2g -i 1

	using this version of the CLI:

		6.12.3-c0c9a03

	and that this error occurred:

		runtime error: index out of range

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0x0, 0x0)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:117 +0xc7
	main.handlePanics(0xe1b3a0, 0xc2080f8900)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:101 +0x1a4
	github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc208214f60, 0xc20810f410, 0x24, 0xc208439da0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x2ea
	github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc20800b810, 0xc20810f410, 0x24, 0xc2080ef7f8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:169 +0x8e5
	github.com/cloudfoundry/cli/cf/commands/application.

**Comment by camelpunch** [comment]
Related to https://github.com/cloudfoundry/cli/issues/543?

**Comment by camelpunch** [comment]
We're removing the logs_noaa code on the next release. Should be fixed with that.
