### ISSUE TITLE
Instructions for creating/initializing development environment in README.md are incomplete

### ISSUE THREAD

**Issue by mcowger** [cloudfoundry/cli#583]
Some steps for Go newbies around navigating the directory structure are missing.

**Comment by camelpunch** [comment]
See PR for discussion

**Comment by camelpunch** [comment]
This is now in our Backlog. Please see the Tracker story for updates.

**Comment by krishicks** [comment]
I re-opened this because the Tracker story for it remains. However, I note that the PR was closed (not merged), so I will delete the Tracker story and re-close this.
