### ISSUE TITLE
cf --version return error on 6.12.3

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry/cli#585]
We are seeing the following output when trying to use `--version` on 6.12.3 on Mac OSX.

```
$ cf --version
'--version' is not a registered command. See 'cf help'

$ cf -v
cf version 6.12.3-c0c9a03-2015-08-31T20:29:00+00:00
```

**Comment by camelpunch** [comment]
Fixed on master: https://github.com/cloudfoundry/cli/commit/f050f990d5ba0a8a40c8565888f30228e36e0ea1

**Comment by jtarchie** [comment]
@camelpunch: see [comment](https://github.com/cloudfoundry/cli/commit/f050f990d5ba0a8a40c8565888f30228e36e0ea1#commitcomment-13270561)

**Comment by simonleung8** [comment]
@jtarchie https://github.com/cloudfoundry/cli/commit/f050f990d5ba0a8a40c8565888f30228e36e0ea1 hasn't made into v6.12.3

*test for `--version` also fixed.
