### ISSUE TITLE
Failed to update app

### ISSUE THREAD

**Issue by csymeonides** [cloudfoundry/cli#591]
Tell us that you ran this command:
 
 		cf push buildcicsoi -p /home/jenkins/workspace/WEB UI Build/CICSInsightWeb/buildOutput/deployment -m 512MB
 
 	using this version of the CLI:
 
 		6.6.2-0c953cf
 
 	and that this error occurred:
 
 		runtime error: invalid memory address or nil pointer dereference
 
 	and this stack trace:
 
 		goroutine 1 [running]:
 	main.generateBacktrace(0xc21000a000, 0x7)
 		/var/vcap/data/gocd-agent/pipelines/Linux-64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:140 +0xa9
 	main.handlePanics()
 		/var/vcap/data/gocd-agent/pipelines/Linux-64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:124 +0xfb
 	runtime.panic(0x90e3e0, 0x11523c8)
 		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
 	github.com/cloudfoundry/cli/cf/net.Gateway.performRequestForResponseBytes(0x7fd4e11aa9f8, 0xc210080850, 0xac9518, 0x1, 0x12a05f200, ...)
 		/var/vcap/data/gocd-agent/pipelines/Linux-64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:229 +0x23c
 	github.com/cloudfoundry/cli/cf/net.Gateway.PerformPollingRequestForJSONResponse(0x7fd4e11aa9f8, 0xc210080850, 0xac9518, 0x1, 0x12a05f200, ...)
 		/var/vcap/data/gocd-agent/pipelines/Linux-64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:268 +0x241
 	github.com/cloudfoun

**Comment by camelpunch** [comment]
Hi @csymeonides. That's quite an old version of the CLI. Would you mind trying again with an updated binary? Looks like you're in Jenkins so appreciate this might be a little involved...
