### ISSUE TITLE
cf login calls for password even though it is provided with -p

### ISSUE THREAD

**Issue by kmejka** [cloudfoundry/cli#592]
```cf login``` command prompts for password and space even though they were provided with appropriate parameters. See command below. I have blocked the parameters for obvious reasons. Even though I have provided all the parameters (username, password, organization and space) I am asked to provide two of them again. Tested in MacOSX 10.10 with bash and fish shells. I'll be grateful for any help :)

```bash
$ cf login -a {{URL}} -u {{USERNAME}} –p {{PASSWORD}} -o {{ORG}} –s {{SPACE}}
API endpoint: {{URL}}

Password>
Authenticating...
OK

Targeted org {{ORG}}

Select a space (or press enter to skip):
1. ----------
2. ----------
3. ----------
4. ----------
5. ----------
6. ----------
7. ----------
8. ----------
9. ----------
10. ----------
11. ----------

Space> 9
Targeted space {{SPACE}}



API endpoint:   {{URL}}
User:           {{USERNAME}}
Org:            {{ORG}}
Space:          {{SPACE}}
```

**Comment by camelpunch** [comment]
Hi @kmejka! Could you please provide the output of `cf --version`?

**Comment by kmejka** [comment]
Weird, ```cf --version``` doesn't work (though its listed in help), but ```cf -v``` does. Anyway, here the output:

```shell
GLOBAL OPTIONS:
   --version, -v                      Print the version
   --help, -h                         Show help

$ cf -v
cf version 6.12.3-c0c9a03-2015-08-31T20:29:00+00:00
$ cf --version
'--version' is not a registered command. See 'cf help'
````

**Comment by camelpunch** [comment]
Yeah, --version will be fixed in the next release. Could you please try again with an edge binary from: https://github.com/cloudfoundry/cli#downloads?

**Comment by kmejka** [comment]
I did the same thing and the result was the same:

```shell
~/Downdloads $ ./cf -v
./cf version 6.12.3-ecdf2fe-2015-09-17T17:42:46+00:00

~/Downdloads $ ./cf login -a {{URL}} -u {{USER}} –p {{PASS}} -o {{ORG}} –s {{SPACE}}
API endpoint: {{URL}}

Password>
Authenticating...
OK

Targeted org {{ORG}}

Select a space (or press enter to skip):
1. ---------
2. ---------
3. ---------
4. ---------
5. ---------
6. ---------
7. ---------
8. ---------
9. ---------
10. ---------
11. ---------

Space> 9
Targeted space {{SPACE}}



API endpoint:   {{URL}}
User:           {{USER}}
Org:            {{ORG}}
Space:          {{SPACE}}
```

**Comment by camelpunch** [comment]
A couple more questions:

* What sort of Cloud Foundry installation is this? e.g. Pivotal Web Services, BOSH lite, corporate install.
* Can you successfully do `cf api $api_url && cf auth $username $password && cf target -o $org -s $space`?

**Comment by kmejka** [comment]
Regarding your questions:
- It is a corporate install. AFAIK I'm the only person with this problem, my colleagues succeed with this kind of call.
- The chain of command you provided works ok. Result below (I've uncovered the API Version printout, maybe this helps).

```shell
$ cf api {{API}} ; cf auth {{USER}} {{PASS}} ; cf target -o {{ORG}} -s {{SPACE}}
Setting api endpoint to {{API}}...
OK


API endpoint:   {{API}} (API version: 2.33.0)
Not logged in. Use 'cf login' to log in.
API endpoint: {{API}}
Authenticating...
OK
Use 'cf target' to view or set your target org and space

API endpoint:   {{API}} (API version: 2.33.0)
User:           {{USER}}
Org:            {{ORG}}
Space:          {{SPACE}}

```

**Comment by Zouuup** [comment]
might be stupid suggestion, but can you please try another shell or another user on your system?

**Comment by kmejka** [comment]
@Zouuup I've tried this on two different shells - in bash and in fish. I can't try it on a different user because my system is quite locked - I don't have admin rights to create a new user, this is not my personal machine.

**Comment by Zouuup** [comment]
hmm... i believe something is wrong locally, but i'm not sure what.
can you verify that you have ~/.cf/config.json? can you remove ~/.cf and retry?

**Comment by kmejka** [comment]
@Zouuup yeah, I have the ```.cf/config.json``` file. I'll delete the folder and try again.

**Comment by kmejka** [comment]
Nope, no luck after deleting the file. Nothing changes.

**Comment by Zouuup** [comment]
@kmejka Out of ideas, sorry :(

**Comment by kmejka** [comment]
@Zouuup thats a bummer. Well I'll just continue to use the combination of ```cf api && cf auth && cf target``` for now posted by @camelpunch .
I'll wait for an answer anyway though :)
Could  you tell me how I could perhaps debug/test it at home myself? Some startup giude? I'd like to help in my spare time anyway :).

**Comment by Zouuup** [comment]
@kmejka hmm, it might be good idea to try to login to another CF deployment and see if same thing happen,  if you can, try to login to your corporation installation from another box (home maybe) as well. maybe that could help to narrow down the problem.

**Comment by kmejka** [comment]
@Zouuup I've tried a different cf deployment on my machine and I got the same results. I have however tried the command with all parameters passed on a different physical machine. And everything went fine. So the problem seems to be isolated to my machine.

**Comment by Zouuup** [comment]
that's pretty odd, do you have something extra tight going on? selinux, apparmor, etc?

**Comment by kmejka** [comment]
don't know what these are, so I guess not :). I've got a mac, I've got some mcafee installed, but no specific firewalls or something. The other computer I tried to use has got the same configuration (or at least should) and is in the same network. I don't know what to look for to be honest.
