### ISSUE TITLE
The --version flag doesn't appear to work while -v does

### ISSUE THREAD

**Issue by dipolesource** [cloudfoundry/cli#593]
Macbook Air 1.7 GHz Intel Core i7 running 10.10.4

![screen shot 2015-09-18 at 12 00 39 pm](https://cloud.githubusercontent.com/assets/54610/9964247/3ef54972-5dfd-11e5-929a-a77b67138c46.png)

**Comment by Zouuup** [comment]
Hello,
just got fixed at 422c5e455762e2adee9ffc0df2d1d3f1db2a1811

**Comment by simonleung8** [comment]
Hi, like what Zouuup said, this has been fixed in our latest release.

Thanks.
