### ISSUE TITLE
Help commands should only show help for the shell you are running in

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cli#598]
`cf help create-service` (and others?) shows formatting for Linux/Mac, Windows Command Line, and Windows PowerShell. The binary should be able to tell at the very least that we are running on either Linux/Mac or Windows, and only show the relevant formatting.

If possible to distinguish between cmd.exe and PowerShell, or Linux and OS X, that would be great, too.

The relevant help portion looks like:

```
EXAMPLE:
   Linux/Mac:
      cf create-service db-service silver -c '{"ram_gb":4}'

   Windows Command Line:
      cf create-service db-service silver -c "{\"ram_gb\":4}"

   Windows PowerShell:
      cf create-service db-service silver -c '{\"ram_gb\":4}'
```

**Comment by camelpunch** [comment]
Yo Dan. This sounds great. Unfortunately, it now lives in Tracker. Please follow it there for updates.
