### ISSUE TITLE
#599

### ISSUE THREAD

**Issue by crobles2** [cloudfoundry/cli#599]
:: removed per request by @crobles2 ::

**Comment by camelpunch** [comment]
@crobles2 looks like I'd have to be on your PagerDuty to see that error.

**Comment by crobles2** [comment]
This was the only part I left out of the error.. at the top. But I put the output in the ticket. 
2015-09-24 19:10:10 INFO  # 0 : e2e started

Creating service v3_ts_21864:
* query timeseriesdatabase guid: 5ed01e14-49e1-4135-9889-ef79b2e380eb
* query small guid: fca1a495-51ea-42ce-ad0a-1220bfe53704
* start to create service

**Comment by crobles2** [comment]
Hello, I ask that you delete the pivotal story at https://www.pivotaltracker.com/n/projects/892938/stories/104134520. Due to legal reasons, the content needs to be editted down. The story was generated by the cf gitbot above on sept 24. Please comment when you have done so or email me at roblescameron@gmail.com

**Comment by crobles2** [comment]
As well, I would need this ticket blocked. I will recreate a new ticket with the appropriate information.

**Comment by nicw** [comment]
@crobles2 sorry this happened for you - unfortunately GH doesn't allow deletion of issues. I've removed your description, but as this is a public repo all of this is available via the eventsstream.

**Comment by crobles2** [comment]
I was reading if you deleted an account that it's issues would be deleted as well. But I do not own the issue so this did not work. 
Thank you for attempting. We got as much information removed as possible so thank you. One last thing would be to change the title to "." or something that would be unlikely to pop up in any search.
