### ISSUE TITLE
[enhancement - cli output] Add json output in addition to the existing text format

### ISSUE THREAD

**Issue by cyrille-leclerc** [cloudfoundry/cli#604]
As a Cloud Foundry user who uses the CF CLI in scripts, I would like to get the cli output in a json format to easily parse the result of the executed commands.

**Comment by camelpunch** [comment]
Presuming that CF_TRACE env var doesn't help here. Please follow the Tracker story for updates.

**Comment by jabley** [comment]
(I can't comment on the Pivotal Tracker story, so doing it here instead)

`cf curl` and https://apidocs.cloudfoundry.org/ has helped me with this in the past.

**Comment by menicosia** [comment]
Now that the BOSH CLI has a [--json](http://bosh.io/docs/cli-global-flags.html#output) flag, it'd be nice if the `cf` CLI had one as well, for consistency.

I understand that one can `cf curl` as a workaround, but I'd prefer to know one syntax (CLI) rather than two (CLI and API) for the same purposes.

Not sure why this enhancement request is closed. I also notice that there's additional work in [#128209191](https://www.pivotaltracker.com/n/projects/892938/stories/128209191), which hasn't made a whole lot of progress in the last year. :)

**Comment by camelpunch** [comment]
Agree that this would be a great feature. You could argue that `cf curl` is a leaky abstraction. Looks like the Tracker story has had some activity recently, though.

**Comment by dkoper** [comment]
@menicosia Before I became PM, the CLI team used to close GitHub stories early, after acknowledging them, to keep the GitHub issue tracker clean and focused on what will be addressed in the near future.
I prefer to keep issues open unless they're delivered or I reject them. (Hence now the large number of open, seemingly inactive issues).

About this particular feature request, as @camelpunch pointed out it has received some intermittent activity in that I've done some comparison studies with other CLIs. Also, our designers interviewed some developers about it, but initial interest seemed low.

For now we're flat out with exposing back-end features and integrating the new v3 commands into core. I'd like us to pick this up again when we come up for air again.

**Comment by DanielJonesEB** [comment]
+1 for JSON output. We could use `cf curl`, but then we need to worry about pagination, which is too much complexity for use cases like Bash scripts piping to `jq`.

**Comment by rjain-pivotal** [comment]
Not sure why this issue is closed? Do we have this feature `--json`

**Comment by technocharpie** [comment]
Anything new on this?

**Comment by markpollack** [comment]
This would be very much appreciated to have, actually adding equivalent to `kubectl`'s `-o -jsonPath={.blahblah}` would be ideal.

**Comment by msouth** [comment]
With a small amount of effort you could make it less bad. For example, the ```cf service``` output is mostly space delimited, but you have spaces in the headers and in the list of bound apps, which makes it a royal pain to parse.  I'm guessing someone could fix things like that in an afternoon.

**Comment by msouth** [comment]
With a small amount of effort you could make it less bad. For example, the ```cf services``` output is mostly space delimited, but you have spaces in the headers and in the list of bound apps, which makes it a royal pain to parse. I'm guessing someone could fix things like that in an afternoon, by eliminating in-field spaces.

**Comment by bruxelles86** [comment]
+1 for this. Would be really, really useful when scripting.

**Comment by Masterxilo** [comment]
I second this request. Many Cloud CLIs have this nowadays.

However, I would refrain from adding some query parameters on top like `-o -jsonPath={.bla}`, that's what `jq` and similar are for, and it would violate Unix Philosophy to add this orthogonal feature.

**Comment by kingdase** [comment]
It's really dumb to have to rebuild cf services with cf curl to get parsable output. It's not one simple cf curl command, because for the bound apps a second cf curl has to be issued and then the whole stuff has to be looped together with jq.
