### ISSUE TITLE
Feature Request for Mac OS X: Use the keychain to store my password

### ISSUE THREAD

**Issue by PierreFritsch** [cloudfoundry/cli#605]
Hi folks

It would be very comfortable if the CF CLI could use the Mac OS X Keychain (the secure way of storing passwords on that OS) to retrieve the username and password when `cf login` is called from the command-line.

Benefit for me as as CLI user:
The OS would ask me for permission ("The CF CLI wants to use the password for api.cf.my-company.com") and I wouldn't have to remember passwords, to store them in unsecure places on my computer or to transfer them using the unsecure copy-and-paste mechanism.

Hint for the implementation: Check the `security` command-line tool.

Thanks and best regards
Pierre

**Comment by squeedee** [comment]
Thankyou for this suggestion!

We will take it under advisement.

* We would prefer to come up with something cross platform for credential caching.
* You could try and create a plugin for this! We'd add it to our online repo if it works. Feel free to reach out to us if you need help.
