### ISSUE TITLE
Bosh create cf release offline

### ISSUE THREAD

**Issue by sdheepa** [cloudfoundry/cli#606]
I am attempting to create a bosh cf release in a set up that does not have outside connectivity. On a machine that has connectivity I did a git clone of cf-release and then did a bosh sync blobs. I then zipped up this after ignoring the .git folders and put it in my set up. 
Running "bosh create release --force" fails with the following error.. Any pointers on what I am missing or doing wrong? Is this the right way to create a bosh release offline if the VM does not have connectivity to outside?

root@inceptionvm:/opt/cisco/vms-installer/bosh/releases/cf/cf-release-new# bosh create release --force
Syncing blobs...
Building DEV release

Release artifact cache: /root/.bosh/cache
Building license

Building license...
  Using final version '861d82c0d9745784acfcd026ccf44e942579824a'
  Downloading from blobstore (id=d2cb714c-d668-45bc-8cf8-899c215d5b8d)...
Blobstore error: Failed to fetch object, underlying error: <SocketError: getaddrinfo: Temporary failure in name resolution (https://s3.amazonaws.com:443)> /usr/local/rvm/gems/ruby-1.9.3-p551/gems/httpclient-2.4.0/lib/httpclient/session.rb:805:in `initialize'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/httpclient-2.4.0/lib/httpclient/session.rb:805:in `new'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/httpclient-2.4.0/lib/httpclient/session.rb:805:in `create_socket'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/httpclient-2.4.0/lib/httpclient/session.rb:752:in `block in connect'
/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/httpclient-2.4.0/lib/httpclient/session.rb:751:in `connect'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/httpclient-2.4.0/lib/httpclient/session.rb:609:in `query'
/usr/loc

**Comment by sdheepa** [comment]
Could someone who has done this before/familiar with this please help/provide suggestions? Thanks!

**Comment by camelpunch** [comment]
@sdheepa you should direct this query to https://github.com/cloudfoundry/cf-release
