### ISSUE TITLE
Cf app crashed

### ISSUE THREAD

**Issue by sai43** [cloudfoundry/cli#613]
please find the attachment to get more info
![screen shot 2015-10-05 at 3 45 57 pm](https://cloud.githubusercontent.com/assets/4579664/10278124/63f6ed38-6b78-11e5-9b27-0cfe994d2773.png)

**Comment by squeedee** [comment]
Hey Sai!.

Could you reproduce using `CF_TRACE=true` ?

**Comment by nicw** [comment]
@sai43 hi Sai,
do you have any update on this issue?
If not, we'll close this in the next few days.

Thanks! 
- CLI Team

**Comment by dkoper** [comment]
Closing this issue as we have not enough information to help. Feel free to re-open or create a new issue if you have more details.

Thanks.
* CLI Team

**Comment by sai43** [comment]
Hi Team,

It's working now, without any problem.

On Thu, Oct 29, 2015 at 1:45 AM, Dies Koper <notifications@github.com>
wrote:

> Closing this issue as we have not enough information to help. Feel free to
> re-open or create a new issue if you have more details.
>
> Thanks.
>
>    - CLI Team
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/cli/issues/613#issuecomment-151977061>.
>



-- 
*Sai Ch* <http://about.me/saich.43>
 Ruby on Rails Developer
 Email: chsai.btech@gmail.com
 Ph: +91 9618706514
 Website: about.me/saich.43
