### ISSUE TITLE
CF crashes 

### ISSUE THREAD

**Issue by tajinders** [cloudfoundry/cli#616]
Hi All, 

I am deploying my app on IBM bluemix cloud. CF got crashed, please find below the error. 

C:\Users\IBM_ADMIN>cf push tajsmapp -p C:\Users\IBM_ADMIN\workspace\devops\solut
ion-manager-deployment\dev-deployment\target\dev-deployment-1.0-SNAPSHOT-liberty
.zip
Updating app tajsmapp in org Solutions on Cloud - DEV / space tajsingh as tajind
er.singh@ca.ibm.com...
OK

Uploading tajsmapp...
Uploading app files from: C:\Users\IBM_ADMIN\workspace\devops\solution-manager-d
eployment\dev-deployment\target\dev-deployment-1.0-SNAPSHOT-liberty.zip
Uploading 2.5K, 6 files
Done uploading
OK

Stopping app tajsmapp in org Solutions on Cloud - DEV / space tajsingh as tajind
er.singh@ca.ibm.com...
OK

Starting app tajsmapp in org Solutions on Cloud - DEV / space tajsingh as tajind
er.singh@ca.ibm.com...
-----> Downloaded app package (35M)
-----> Downloaded app buildpack cache (1.2M)
    -----> Liberty Buildpack Version: v2.0-20150914-1535
-----> Retrieving IBM 1.8.0_20150711 JRE (ibm-java-jre-8.0-1.10-pxa6480sr1fp10-2
0150711_01-cloud.tgz) ... (0.0s)
         Expanding JRE to .java ... (1.1s)
-----> Retrieving App Management 1.7.0_20150729-1104 (app-mgmt_v1.7-20150729-110
4.zip) ... (0.0s)
         Expanding App Management to .app-management (1.2s)
-----> Downloading Auto Reconfiguration 1.10.0_RELEASE from https://download.run
.pivotal.io/auto-reconfiguration/auto-reconfiguration-1.10.0_RELEASE.jar (0.0s)
       Modifying /WEB-INF/web.xml for Auto Reconfiguration
-----> Retrieving com.ibm.ws.liberty-2015.8.0.0-201509141535.tar.gz ... (0.0s)
-----> Retrieving com.ibm.ws.liberty.ext-2015.8.0.0-201509141535.tar.gz ... (0.0
s)
         Installing archive ... (0.9s)
-----> Retrieving and installing client jar(s) from com.ibm.ws.icap.clientJars.c
loudant.zip (0.2s)
-----> Retrieving and installing client jar(s) from com.ibm.ws.icap.clientJars.d
b2.zip (0.0s)
-----> Retrieving and installing client jar(s) from wmq.jmsra.rar (0.0s)
-----> Auto-configuration is updating config for service instance 'Cloudant NoSQ
L DB-13' of type 'cloudantNoSQLDB'
    W, [2015-10-06T17:30:14.119168 #67]  WARN -- /var/vcap/data/dea_next/admin_b
uildpacks/8c5f8f52-5d89-4571-a21d-cd658f01705d_8473787eb534aa93b8de6f0fa70ab7703
4d078f7/lib/liberty_buildpack/services/utils.rb:225:in `get_api_visibility': Una
ble to determine classloader visibility as there are 2 apps
W, [2015-10-06T17:30:14.131267 #67]  WARN -- /var/vcap/data/dea_next/admin_build
packs/8c5f8f52-5d89-4571-a21d-cd658f01705d_8473787eb534aa93b8de6f0fa70ab77034d07
8f7/lib/liberty_buildpack/services/utils.rb:249:in `add_library_to_app_classload
er': Unable to add a shared library for service Cloudant NoSQL DB-13. There are
2 applications
-----> Auto-configuration is updating config for service instance 'dashDB-b2' of
 type 'AnalyticsWarehouse'
W, [2015-10-06T17:30:14.137960 #67]  WARN -- /var/vcap/data/dea_next/admin_build
packs/8c5f8f52-5d89-4571-a21d-cd658f01705d_8473787eb534aa93b8de6f0fa70ab77034d07
8f7/lib/liberty_buildpack/container/services_manager.rb:142:in `rescue in block
in update_configuration': Failed to update the configuration for a service. Deta
ils are  There is no configured JDBC driver for dashDB-b2
-----> Auto-configuration is updating config for service instance 'MQLight-mc' o
f type 'mqlight'
-----> Auto-configuration is updating config for service instance 'Single Sign O
n-72' of type 'SingleSignOn'
-----> Liberty buildpack is done creating the droplet
-----> Uploading droplet (240M)

1 of 1 instances running

App started

OK

        Aww shucks.

        Something completely unexpected happened. This is a bug in cf.
        Please file this bug : https://github.com/cloudfoundry/cli/issues
        Tell us that you ran this command:

                cf push tajsmapp -p C:\Users\IBM_ADMIN\workspace\devops\solution
-manager-deployment\dev-deployment\target\dev-deployment-1.0-SNAPSHOT-liberty.zi
p

        using this version of the CLI:

                6.10.0-b78bf10

        and that this error occurred:

                runtime error: invalid memory address or nil pointer dereference

        and this stack trace:

                goroutine 1 [running]:
        main.generateBacktrace(0xc084007190, 0x5)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/main/main.go:174 +0xac
        main.handlePanics(0x3515d8, 0xc08404ac20)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/main/main.go:158 +0x126
        runtime.panic(0x94fd20, 0x1211baf)
                C:/Users/ADMINI~1/AppData/Local/Temp/2/makerelease155988687/go/s
rc/pkg/runtime/panic.c:248 +0x11b
        github.com/cloudfoundry/cli/cf/net.Gateway.performRequestForResponseByte
s(0x35ac80, 0xc084060120, 0xb23500, 0x1, 0x12a05f200, ...)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/cf/net/gateway.go:249 +0x248
        github.com/cloudfoundry/cli/cf/net.Gateway.PerformRequestForJSONResponse
(0x35ac80, 0xc084060120, 0xb23500, 0x1, 0x12a05f200, ...)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/cf/net/gateway.go:267 +0x98
        github.com/cloudfoundry/cli/cf/net.Gateway.GetResource(0x35ac80, 0xc0840
60120, 0xb23500, 0x1, 0x12a05f200, ...)
                C:/GoAgent/pipelines/

Please let me know if you have any questions. 

Thanks .
Taj

**Comment by simonleung8** [comment]
hi Taj,

Could you reproduce using CF_TRACE=true? It will help us debug the problem. 

Thanks

**Comment by camelpunch** [comment]
6.10.0-b78bf10 is also pretty old. Worth trying to upgrade.
