### ISSUE TITLE
PWS, CF CLI generates bad route ..

### ISSUE THREAD

**Issue by farrell0** [cloudfoundry/cli#620]
Hola ..

On PWS today (2015/10-09), a 
   cf push fff_v1           #  Underscore
will generate a route for that app equal to,
   fff-v1.cfapps.io         #  Hyphen

   --

A cf push fff_v1 -n fff_v1   works fine, so does cf create-route

**Comment by camelpunch** [comment]
Please see Tracker story for updates on this.

**Comment by dkoper** [comment]
Hi @farrell0,

This is by specification. Generally, underscores are not recommended in domain names, so cf CLI doesn't use the app name as-is. However, underscores are not illegal characters in domain names, so if you know what you're doing, you can use `-n` or `create-route` instead.

Regards,
Dies Koper
CF CLI PM
