### ISSUE TITLE
saving the output of cf files

### ISSUE THREAD

**Issue by evanfarrar** [cloudfoundry/cli#626]
One of the users of our instance approached me with a minor annoyance. He has used cloudfoundry to compile one of his dependencies, and then fetched that dependency so that he could save it for future deploys of his app.

It tripped him up when he tried to use the files command to do this:
``cf files buildenvironment ./oracledriver.jar > oracledriver.jar``

Perhaps similar to cf curl, we could support --output like so:
``cf files buildenvironment ./oracledriver.jar --output=oracledriver.jar``

Or we could do something else, such as outputting only file contents to stdout or detecting that we are not outputting to a terminal. Either way, with binary files this changing of the file can be tricky to debug and tedious to fix.

**Comment by camelpunch** [comment]
Hey Evan. Closing in favour of the Tracker story.
