### ISSUE TITLE
`cf curl` support reading HTTP request body data from a file

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/cli#629]
At the moment, it seems like `cf curl` only supports `-d` which is a command line argument for setting the HTTP request body.  In cases where the request body is large it's not practical to set as a command line argument or you might get "arg list too long" error depending on the OS.  

It would be nice if `cf curl` supported something similar to `curl` where you can do `-d @file-name` and have it read the request body from the file instead of from the argument.

**Comment by dkoper** [comment]
Hi Dan,

Yes that does sound helpful. Our backlog is long, but if you'd like to submit a PR we'll review it straight away!

Best,
Dies Koper
* CLI team

**Comment by dkoper** [comment]
Closing this feature request. You can continue following the status of this story at the tracker link above.

**Comment by dkoper** [comment]
Hi @dmikusa-pivotal,

In implementing this we noticed something which made me question your issue.
`curl`'s `-d` with '@' is used to pass in FORM data using the content-type application/x-www-form-urlencoded.
https://curl.haxx.se/docs/manpage.html#-d

Does this indeed match your use case, or are you after something like curl's `--data-binary` or `-F`?

Cheers,
Dies Koper
CF CLI PM

**Comment by dmikusa-pivotal** [comment]
It's been a while here so I don't recall the exact command I was trying to run.  I think the gist is that if you need to set HTTP body data the only option for `cf curl` at the moment is to do that on the command line with an argument.

In some cases, the command line args works fine but in other's it's not practical because of the size of what you'd need to specify.  One solution would be to allow `cf curl` to pull that information from a file (or STDIN and you could pipe it into the command).  I'm open to other solutions, I just mentioned this particular one because it's the option that `curl` uses.  The usage with `curl` was really just an example to try and illustrate what I meant though.  

As far as making `cf curl -d` behave exactly like `curl -d`, that's probably not necessary.  For example, with `cf curl` it would probably make more sense if the default content type was JSON, since that's what we use when talking to cloud controller & UAA.  I don't know about the encodings (i.e. curl's `-d` vs `--data-binary`).  My take would be to do whatever "just works" and makes interacting with the CF API as easy as possible.

As far as curl `-F`, I don't think that's what we want here as my understanding is that's for doing file uploads.  I don't want to upload the file itself, just have `cf curl` read the contents and use that in place of what I'd normally type in on the command line.

Thanks and really glad we're looking into this feature more!

**Comment by dkoper** [comment]
This has been implemented in cf CLI v6.16.0.
https://github.com/cloudfoundry/cli#downloads

Regards,
Dies Koper
CF CLI PM
