### ISSUE TITLE
name of os-x installer

### ISSUE THREAD

**Issue by dirkjot** [cloudfoundry/cli#630]
Hi, small issue here:  If I download the CLI installer for osx, I get a package that is called `installer-osx-amd64.pkg`.  It would be more standard to name this something like `cloudfoundry-cli-installer-osx-amd64-6.12.4.pkg'. I guess the same holds for the other installers, but I didn't try.  

Thx for making this great piece of software.

**Comment by dkoper** [comment]
@dirkjot Thanks for raising this issue!
We have renamed our installers to include the release version. The one you mentioned is now called `cf-cli-installer_6.13.0_osx.pkg`.
