### ISSUE TITLE
Using Trusted Self-Signed Root CA Certificate

### ISSUE THREAD

**Issue by jigsheth57** [cloudfoundry/cli#636]
I'm trying to get the CF CLI to work with self-signed root ca in Ubuntu. I've added the self-signed root ca to /etc/ssl/certs/ca-certificates.crt according to ("https://golang.org/src/crypto/x509/root_linux.go"). It works successfully with curl command, but still get complain with CF CLI?? What cert store is being used by "https://github.com/cloudfoundry/cli/blob/master/cf/net/ssl.go"??

$ ./cf api https://api.west-1.fe.gopivotal.com
Setting api endpoint to https://api.west-1.fe.gopivotal.com...
FAILED
Invalid SSL Cert for api.west-1.fe.gopivotal.com
TIP: Use 'cf api --skip-ssl-validation' to continue with an insecure API endpoint

$ CF_TRACE=true ./cf api https://api.west-1.fe.gopivotal.com
Setting api endpoint to https://api.west-1.fe.gopivotal.com...

REQUEST: [2015-10-16T16:35:38Z]
GET /v2/info HTTP/1.1
Host: api.west-1.fe.gopivotal.com
Accept: application/json
Content-Type: application/json
User-Agent: go-cli 6.12.4-b4b6af1 / linux

FAILED
Invalid SSL Cert for api.west-1.fe.gopivotal.com
TIP: Use 'cf api --skip-ssl-validation' to continue with an insecure API endpoint
FAILED
Invalid SSL Cert for api.west-1.fe.gopivotal.com
TIP: Use 'cf api --skip-ssl-validation' to continue with an insecure API endpoint

$ curl https://api.west-1.fe.gopivotal.com/v2/info
{"name":"vcap","build":"2222","support":"https://support.pivotal.io","version":2,"description":"Cloud Foundry sponsored by Pivotal","authorization_endpoint":"https://login.west-1.fe.gopivotal.com","token_endpoint":"https://uaa.west-1.fe.gopivotal.com","min_cli_version":"6.7.0","min_recommended_cli_version":"6.11.2","api_version":"2.25.0","logging_endpoint":"wss://loggregator.west-1.fe.gopivotal.com:443"}

**Comment by goehmen** [comment]
I see the desire for this feature a lot in talking to CF Operators.

**Comment by ryanpei** [comment]
+1 to what @goehmen says above, this would be very very attractive for us

**Comment by dkoper** [comment]
@jigsheth57 Can you confirm you have actually registered the CA root that signed the server certificate of api.west-1.fe.gopivotal.com (i.e. the cert with issuer's common name /C=US/O=Pivotal), not just the server certificate itself?
I believe the location you found to put the CA is correct. If you can provide me with that cert I can investigate deeper.

Cheers,
Dies Koper
CF CLI PM

**Comment by jigsheth57** [comment]
Attach is the self-signed cert generated by the ops manager console, which is used for the ER. 



Best Regards,
Jignesh Sheth | Sr. Platform Architect | Pivotal
Phone: (847)970-0298 | jigsheth@pivotal.io <mailto:jigsheth@pivotal.io>





Platform as a Service | Agile Development | Big Data
www.Pivotal.io <http://www.pivotal.io/> | http://pivotal.io/cloud-native <http://pivotal.io/cloud-native>

**Comment by ryanpei** [comment]
Hi Jignesh,

I could not find the attachment you sent. Also, can you please include Dies
Koper (diesk@fast.au.fujitsu.com) in your reply?

On Wed, Jan 13, 2016 at 6:39 AM, Jignesh Sheth <notifications@github.com>
wrote:

> Attach is the self-signed cert generated by the ops manager console, which
> is used for the ER.
>
>
>
> Best Regards,
> Jignesh Sheth | Sr. Platform Architect | Pivotal
> Phone: (847)970-0298 | jigsheth@pivotal.io <mailto:jigsheth@pivotal.io>
>
>
>
>
>
> Platform as a Service | Agile Development | Big Data
> www.Pivotal.io <http://www.pivotal.io/> | http://pivotal.io/cloud-native <
> http://pivotal.io/cloud-native>
> > On Jan 12, 2016, at 11:43 PM, Dies Koper <notifications@github.com>
> wrote:
> >
> > @jigsheth57 <https://github.com/jigsheth57> Can you confirm you have
> actually registered the CA root that signed the server certificate of
> api.west-1.fe.gopivotal.com (i.e. the cert with issuer's common name
> /C=US/O=Pivotal), not just the server certificate itself?
> > I believe the location you found to put the CA is correct. If you can
> provide me with that cert I can investigate deeper.
> >
> > Cheers,
> > Dies Koper
> > CF CLI PM
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/cloudfoundry/cli/issues/636#issuecomment-171176660>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/cli/issues/636#issuecomment-171310712>.
>



-- 
Thanks,
Ryan

**Comment by jigsheth57** [comment]
Hi Ryan,

Let’s see if this works. LMK, if you see the attach certificate.

Best Regards,
Jignesh Sheth | Sr. Platform Architect | Pivotal
Phone: (847)970-0298 | jigsheth@pivotal.io <mailto:jigsheth@pivotal.io>





Platform as a Service | Agile Development | Big Data
www.Pivotal.io <http://www.pivotal.io/> | http://pivotal.io/cloud-native <http://pivotal.io/cloud-native>

**Comment by dkoper** [comment]
Hi @jigsheth57,

I received an email with the certificate used by api.west-1.fe.gopivotal.com. It is not self-signed.
Is this the one, and the only one, you added to /etc/ssl/certs/ca-certificates.crt?

**Comment by dkoper** [comment]
You sent me a pem file with an intermediate cert and a self-signed CA cert. They don't seem to be the ones used to sign the server cert of api.west-1.fe.gopivotal.com, hence cf CLI is failing.

**Comment by jigsheth57** [comment]
Those certs are not meant for CF api.west-1.fe.gopivotal.com

It's meant for my private CF install that I usually do not keep running. 

api.system.pcf-apps.com

Jig

**Comment by jbayer** [comment]
@dkoper @krishicks if someone (like the CLI engineering team) is on the pivotal internal network, this installation can be used with a self-signed certificate https://pcf.horse.wild.cf-app.com/

**Comment by krishicks** [comment]
Thanks, @jbayer!

**Comment by jigsheth57** [comment]
Hi Guys,

I tried it but failed. Please take a look at the log.txt. I imported the attach self-signed certificate, but was not able to initiate trusted secure connection. 


Best Regards,
Jignesh Sheth | Sr. Platform Architect | Pivotal
Phone: (847)970-0298 | jigsheth@pivotal.io <mailto:jigsheth@pivotal.io>





Platform as a Service | Agile Development | Big Data
www.Pivotal.io <http://www.pivotal.io/> | http://pivotal.io/cloud-native <http://pivotal.io/cloud-native>
> On Feb 8, 2016, at 9:55 PM, Kris Hicks <notifications@github.com> wrote:
> 
> Thanks, @jbayer <https://github.com/jbayer>!
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/cloudfoundry/cli/issues/636#issuecomment-181697317>.
> 


pivotal@pivotal-virtual-machine:~$ chmod 400 Tempest.pem 
pivotal@pivotal-virtual-machine:~$ sudo mv Tempest.pem /usr/local/share/ca-certificates/Tempest.crt
[sudo] password for pivotal: 
pivotal@pivotal-virtual-machine:~$ sudo update-ca-certificates
Updating certificates in /etc/ssl/certs...
WARNING: Skipping duplicate certificate ValiCert_Class_2_VA.pem
WARNING: Skipping duplicate certificate ValiCert_Class_2_VA.pem
WARNING: Skipping duplicate certificate UbuntuOne-Go_Daddy_Class_2_CA.pem
WARNING: Skipping duplicate certificate UbuntuOne-Go_Daddy_Class_2_CA.pem
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.

pivotal@pivotal-virtual-machine:~$ curl -i https://pcf.horse.wild.cf-app.com/login
curl: (51) SSL: certificate subject name (Tempest) does not match target host name 'pcf.horse.wild.cf-app.com'
pivotal@pivotal-virtual-machine:~$ curl -v https://pcf.horse.wild.cf-app.com/login
*   Trying 10.85.34.16...
* Connected to pcf.horse.wild.cf-app.com (10.85.34.16) port 443 (#0)
* found 188 certificates in /etc/ssl/certs/ca-certificates.crt
* found 762 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* SSL: certificate subject name (Tempest) does not match target host name 'pcf.horse.wild.cf-app.com'
* Closing connection 0
curl: (51) SSL: certificate subject name (Tempest) does not match target host name 'pcf.horse.wild.cf-app.com'

pivotal@pivotal-virtual-machine:~/Downloads$ ./cf login -a https://api.horse.wild.cf-app.com
API endpoint: https://api.horse.wild.cf-app.com
FAILED
Invalid SSL Cert for api.horse.wild.cf-app.com
TIP: Use 'cf login --skip-ssl-validation' to continue with an insecure API endpoint

pivotal@pivotal-virtual-machine:~$ curl -k https://api.horse.wild.cf-app.com/info
{"name":"vcap","build":"2222","support":"https://support.pivotal.io","version":2,"description":"Cloud Foundry sponsored by Pivotal","authorization_endpoint":"https://login.horse.wild.cf-app.com","token_endpoint":"https://uaa.horse.wild.cf-app.com","allow_debug":true}pivotal@pivotal-virtual-machine:~$ 
pivotal@pivotal-virtual-machine:~$ 
pivotal@pivotal-virtual-machine:~$ curl https://api.horse.wild.cf-app.com/infocurl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by dkoper** [comment]
Hi @jigsheth57,

James' certificate wasn't self-signed, it has the same problem as the one you sent me in that it was signed by another certificate, which I don't have, and is for an API endpoint I can't access.

In your curl statement I see:

```
* found 188 certificates in /etc/ssl/certs/ca-certificates.crt 
* found 762 certificates in /etc/ssl/certs
```

Curl is looking in multiple places for CA certificates.
While golang looks only in /etc/ssl/certs/ca-certificates.crt.

So I wonder if, when you tried this originally, the certificate that signed the server certificate of *.west-1.fe.gopivotal.com was stored in /etc/ssl/certs, hence curl was working but `cf login` was not.

If you could locate that CA certificate (and if not self-signed or signed by another certificate, all those certs too) in /etc/ssl/certs and copy it over into /etc/ssl/certs/ca-certificates.crt and try again, we could test that theory.

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Hi @jigsheth57, @ryanpei, @jbayer,

I was able to verify it works fine using bosh-lite on ubuntu:
* installed bosh-lite according to its instructions (I used `./bin/provision_cf`)
* used `openssl s_client -showcerts -connect api.10.244.0.34.xip.io:443 </dev/null 2>/dev/null`  to retrieve its certificate
* Opened the system truststore file and added the content of the pem encoded certificate from the output above to the top of the file (`sudo vi /etc/ssl/certs/ca-certificates.crt`)
* Logged in without using the `--skip-ssl-validation` option:
```
cf login -a https://api.bosh-lite.com  -u admin -p admin
API endpoint: https://api.bosh-lite.com
Authenticating...
OK



API endpoint:   https://api.bosh-lite.com (API version: 2.48.0)
User:           admin
No org or space targeted, use 'cf target -o ORG -s SPACE'
```

Regards,
Dies Koper
CF CLI PM
