### ISSUE TITLE
Cloud Foundry CLI version 6.11.2 or later is required for the IBM Containers plug-in. Upgrade your Cloud Foundry CLI installation to continue

### ISSUE THREAD

**Issue by 1993hzh** [cloudfoundry/cli#639]
> cf -v
cf version 6.13.0-e68ce0f-2015-10-15T22:53:58+00:00

> cf install-plugin https://static-ice.ng.bluemix.net/ibm-containers-linux_x64
> Plugin IBM-Containers v0.8.723 successfully installed.

> cf ic login

>Expect: login successfully
Actual: Cloud Foundry CLI version 6.11.2 or later is required for the IBM Containers plug-in. Upgrade your Cloud Foundry CLI installation to continue.

How could this happened? I have installed the latest cf...
BTW, my os is Ubuntu 14.04

**Comment by krishicks** [comment]
Hi @1993hzh,

This seems to be something internal to the plugin itself, given:

```bash
$ strings ibm-containers-linux_x64 | grep "CLI version"
Cloud Foundry CLI version 6.11.2 or later is required for the IBM Containers plug-in. Upgrade your Cloud Foundry CLI installation to continue.
```

**Comment by dkoper** [comment]
Please raise the issue with the IBM Container plug-in authors. Closing this one.
