### ISSUE TITLE
Aww Shucks cf logs error

### ISSUE THREAD

**Issue by owencarp** [cloudfoundry/cli#640]
Tell us that you ran this command:

                cf login -u ocarpen4@ford.com -p xxxx -o FORD_DDS -s DEV

        using this version of the CLI:

                6.13.0-e68ce0f

        and that this error occurred:

                runtime error: invalid memory address or nil pointer dereference

        and this stack trace:

                goroutine 1 [running]:
        main.generateBacktrace(0x0, 0x0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:127 +0xbb
        main.handlePanics(0x1d0038, 0xc08255f0a0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:111 +0x183
        github.com/cloudfoundry/cli/cf/net.getBaseDomain(0xc0825542d0, 0x2a, 0x0, 0x0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/net/http_client.go:99 +0x141
        github.com/cloudfoundry/cli/cf/net.PrepareRedirect(0xc082286000, 0xc082296008, 0x1, 0x1, 0x0, 0x0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/net/http_client.go:36 +0x227
        net/http.(*Client).doFollowingRedirects(0xc082567c50, 0xc082530540, 0xe4aee8, 0xc0822902d0, 0x0, 0x0)
                c:/go/src/net/http/client.go:368 +0xb0b
        net/http.(*Client).Do(0xc082567c50, 0xc082530540, 0xc082567c50, 0x0, 0x0)
                c:/go/src/net/http/client.go:175 +0xa3
        github.com/cloudfoundry/cli/cf/net.Gateway.doRequest(0x1d0470, 0xc082290bd0, 0xe4a498, 0x1, 0x12

I got this error when trying to monitor logs on my IBM Bluemix application running on Tomcat.  My co-worker does not get this error from this mac book.  I have my proxy settings correctly enabled.  Unsure why I am getting this error.

**Comment by dkoper** [comment]
Hi,

Could you reproduce using CF_TRACE=true? It will help us debug the problem.

Cheers.
* CLI Team

**Comment by dkoper** [comment]
Closing this issue. Feel free to reopen when you have more details.

* CLI team
