### ISSUE TITLE
Aww shucks

### ISSUE THREAD

**Issue by JMStudiosJoe** [cloudfoundry/cli#641]
cf push

	using this version of the CLI:

		6.12.4-b4b6af1

	and that this error occurred:

		runtime error: invalid memory address or nil pointer dereference

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0x0, 0x0)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:117 +0xc7
	main.handlePanics(0x181b1a8, 0xc2081144b0)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:101 +0x1a4
	github.com/cloudfoundry/cli/cf/net.Gateway.performRequestForResponseBytes(0x181b5e0, 0xc2082667e0, 0x9051e0, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x181b380, 0xc208286ae0, ...)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:253 +0x2f0
	github.com/cloudfoundry/cli/cf/net.Gateway.PerformPollingRequestForJSONResponse(0x181b5e0, 0xc2082667e0, 0x9051e0, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x181b380, 0xc208286ae0, ...)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:292 +0x309
	github.com/cloudfoundry/cli/

**Comment by dkoper** [comment]
Can you provide more details? Is it reproducible? On the latest cf CLI release? Does push always fail no matter what the application is you push, the flags you specify and/or the manifest file entries you set?

**Comment by dkoper** [comment]
Closing this issue. Feel free to reopen when you have more details.

* CLI team
