### ISSUE TITLE
dpkg installed 6.12.#  as 6.13.0

### ISSUE THREAD

**Issue by helenxu1221** [cloudfoundry/cli#643]
I downloaded different version of 6.12.# and use dpkg to install it. it was installed as version 6.13.0

here is the command I used
wget -O /tmp/cf_cli.deb https://cli.run.pivotal.io/stable?release=debian64&version=6.12.1&source=github-rel
dpkg -i /tmp/cf_cli.deb
Selecting previously unselected package cf-cli.\n(Reading database ... 35894 files and directories currently installed.)\nPreparing to unpack /tmp/cf_cli.deb ...\nUnpacking cf-cli (6.13.0) ...\nSetting up cf-cli (6.13.0) ...
dpkg -l | grep cf
ii  cf-cli                              6.13.0                               amd64        Cloud Foundry command line client

**Comment by krishicks** [comment]
Hi @helenxu1221,

This is because you aren't quoting the string, which means the version query param is being dropped. By default, with no version specified, you get latest, which is presently 6.13.0.

```
$ wget -O /tmp/cf_cli.deb "https://cli.run.pivotal.io/stable?release=debian64&version=6.12.1&source=github-rel"
$ cd /tmp
$ ar xv cf_cli.deb
$ tar xvf control.tar.gz
$ cat control
Package: cf-cli
Maintainer: Ted Young <tyoung@pivotallabs.com>
Source: cf-cli
Homepage: https://github.com/cloudfoundry/cli
Section: misc
Priority: optional
Description: Cloud Foundry command line client
Installed-Size: 10480
Version: 6.12.1
Architecture: amd64
```
