### ISSUE TITLE
In cf plugin,  flag package API does not produce error when invalid command flags are specified

### ISSUE THREAD

**Issue by sbielasi** [cloudfoundry/cli#644]
It appears that if I specify a command line flag that is not explicitly handled in the code via a FlagSet instruction, no error or usage message is produced. The same code but in a non-plugin go executable does produce such a message. I confirmed this by using the EchoDemo plugin downloaded from https://github.com/cloudfoundry/cli/blob/master/plugin_examples/echo.go. This plugin demo handles a single '-uppercase' command line flag intended to signal that all remaining text on command line be uppercased. This works fine if I specify the '-uppercase' flag on the cf plugin command line but fails to produce a usage message if some other flag is specified.

Here is the code segment that sets up flag processing.

    echoFlagSet := flag.NewFlagSet("echo", flag.ExitOnError)
    uppercase := echoFlagSet.Bool("uppercase", false, "displayes all provided text in uppercase")

Here is what happens when I run this plugin with various scenarios. Note that when I specify a command line flag other than '-uppercase', the plugin does not produce an error or usage message.

    # Plugin no command line flag
    $ cf echo no uppercase flag argument so dont uppercase this
    no uppercase flag argument so dont uppercase this

    # Plugin command line -uppercase flag specified
    $ cf echo -uppercase uppercase flag argument so uppercase this
    UPPERCASE FLAG ARGUMENT SO UPPERCASE THIS

    # Plugin unsupported command line flag specified
    $ cf echo -unsupportedflag never return from Parse but does not display usage message
    # (exits but no error or usage message is produced)

If I take the code contained in the plugin Run function and place it directly in a main function in a *echo.go* file and edit the call to the Parse function from

    err := myFlagSet.Parse(args[1:])

to

    err := echoFlagSet.Parse(os.Args[1:])

build it and run it, I do get an error message if an unsupported command line flag is specified.

    # No command line flag
    $ ./echo no uppercase flag argument so dont uppercase this
    no uppercase flag argument so dont uppercase this

    # Command line -uppercase flag specified
    $ ./echo -uppercase uppercase flag argument so uppercase this
    UPPERCASE FLAG ARGUMENT SO UPPERCASE THIS

    # Unsupported command line flag specified
    flag provided but not defined: -unsupportedflag
    Usage of echo:
      -uppercase
         displayes all provided text in uppercase

Am I doing something wrong in the plugin that results in no error or usage message being produced?

**Comment by simonleung8** [comment]
Hi @sbielasi 
The echo plugin is using the standard Go flag library, defined [here](https://github.com/cloudfoundry/cli/blob/master/plugin_examples/echo.go#L9), which doesn't check for invalid/undefined flags.

Currently CLI does not handle flag parsing for plugins, it simply provides the arguments from the end user.

CLI is using this [flag package](https://github.com/simonleung8/flags) for flag parsing, which checks for invalid flags. You can use this package in the plugin to get the same parsing result as CLI.

I am closing this issue, feel free to re-open if you have more questions.
