### ISSUE TITLE
Is it possible to add api to refresh tok?

### ISSUE THREAD

**Issue by jessexu20** [cloudfoundry/cli#647]
Since the cf tok expires every 12 hours, is it possible for the cf plugins to call an api which will get the tok refreshed? Thanks

**Comment by simonleung8** [comment]
hi @jessexu20 
Thanks for raising the issue and we are aware of it. The plugin api will now refresh the token before sending it back. See b16aad6
This feature is currently available in our edge release, and will be available in our next stable release.
