### ISSUE TITLE
Out of memory errors when deploying for Diego enabled applications.

### ISSUE THREAD

**Issue by emileswarts** [cloudfoundry/cli#649]
Hi 

I am busy moving our apps from DEA to Diego but running into trouble.

When I enable Diego on the app and push to it, it times out.  When I remove Diego from the app and push to it, it's fine.

I have bumped the memory of the application from 256M to 2G but it does not seem to make a difference.

Is there anything specific that I can troubleshoot to try get this fixed?

Thanks

**Comment by ematpl** [comment]
Hi, @emileswarts,

It's hard to tell from your description exactly what's going wrong. Could you please post output from `cf logs` for your app when trying to start it on the Diego backend, and also from the DEAs for comparison? Those logs may indicate what the specific problem is. Also, is it correct that you're only restarting the app on the different backend, and not restaging it?

If you haven't done so already, you may also want to consult the Diego team's notes on migrating to Diego, located at https://github.com/cloudfoundry-incubator/diego-design-notes/blob/master/migrating-to-diego.md. It's possible that you're encountering a problem that's documented there.

Thanks,
Eric, CF Runtime Diego PM

**Comment by dkoper** [comment]
Closing this issue as we have not enough information to help further. Feel free to file another issue in the Diego repo (https://github.com/cloudfoundry-incubator/diego/issues) if you need more help.

* CLI team
