### ISSUE TITLE
cf cli cannot login in git bash on Windows

### ISSUE THREAD

**Issue by sbenario** [cloudfoundry/cli#651]
Because git bash provides a bunch of tooling that regular windows CMD doesn't have, I often find myself doing work in that window.

However, I found today that I could not log in to cf from this window. I did this with git bash shipping mintty 2.0.3 (current download from the git website). CF CLI version:  6.13.0-e68ce0f-2015-10-15T15:53:50+00:00

Repro steps:
```
$ cf target

API endpoint:   https://api.xxyy.com (API version: 2.39.0)
User:           admin
Org:            ORG
Space:          SPACE

Administrator@WIN-DEVBOX MINGW64 ~
$ cf login
API endpoint: https://api.xxyy.com

Email> admin
Authenticating...
Credentials were rejected, please try again.
Authenticating...
Credentials were rejected, please try again.
Authenticating...
Credentials were rejected, please try again.
FAILED
Unable to authenticate.


API endpoint:   https://api.xxyy.com (API version: 2.39.0)
Not logged in. Use 'cf.exe login' to log in.
```

Note that after typing "admin" for the username, it automatically failed authentication 3 times with no user input. We suspect it may have to do with the way that this particular terminal respond to the attempt to mask user input for the password field.

**Comment by nicw** [comment]
Hi @sbenario we've got this in the queue, you can see progress in the link above

**Comment by dkoper** [comment]
Duplicate of #171.

**Comment by navr** [comment]
koper, how abt u kill yourself. whoever produce such a bug should kill himself on the spot

**Comment by feedonat** [comment]
Installing the new Git fix my issue !!
