### ISSUE TITLE
Issue while running 'cf' command

### ISSUE THREAD

**Issue by senthilmkumar** [cloudfoundry/cli#653]
Hi I have latest version of CF CLI 6.13.0-e68ce0f
while running 'cf' command I am getting following error

	Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		cf

	using this version of the CLI:

		6.13.0-e68ce0f

	and that this error occurred:

		runtime error: makeslice: len out of range

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0x0, 0x0)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:127 +0xb4
	main.handlePanics(0x19a2778, 0xc8204e2d40)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:111 +0x17c
	strings.Repeat(0x86c2d8, 0x1, 0xfffffffffffffffe, 0x0, 0x0)
		/usr/local/go/src/strings/strings.go:464 +0x5f
	github.com/cloudfoundry/cli/cf/help.newAppPresenter.func2(0x0, 0x0, 0x0)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/help/help.go:86 +0x28a
	github.com/cloudfoundry/cli/cf/help.newAppPresenter(0x7fff5fbffc88, 0x2, 0xc820118780, 0x32, 0xc8204e4480, 0x28, 0xecdc338b6, 0x32f64b13, 0xd09f80, 0x0, ...)
		/Users/cffadmin/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/help/help.go:392 +0x372b
	github.com/cloudfoundry/cli/cf/help.showApp

**Comment by dkoper** [comment]
Can you provide more details, like did it happen once or every time you run the command? If you recently upgraded from an older cf version, did the same command work? Does it fail with this error for every app, app manifest configuration and subcommand or only some?
Thanks!
* CLI Team

**Comment by senthilmkumar** [comment]
- This issue is happening every time I run 'cf'
- Yes, I did upgrade my cf version today from 6.12.4 to 6.13.0
- I had same problem while using previous version also
- Good part is I have few other cf commands working fine ex : cf orgs, cf login, etc...

**Comment by dkoper** [comment]
Do you have any plugins installed, and if you remove them one by one, can you figure out which one may be impacting this, and let us know which plugin it is and how we can get it to test with?

**Comment by simonleung8** [comment]
@senthilmkumar @dkoper Confirmed the bug. To reproduce, modify basic_plugin.go in plugin_examples/ to have a long command name. This is the command name I have used to cause the failure `really-long-command-name-loooooooooooooooooooooooooooooooooooooooooog`.
```
go build basic_plugin.go
cf install-plugin basic_plugin
cf
```

**Comment by senthilmkumar** [comment]
@dkoper recently I have installed BluemixAdminCLI plugin, I uninstalled the plugin and it worked.
cf uninstall-plugin BluemixAdminCLI

Now I don't see the any error when I issue 'cf' command.

But I need to use BluemixAdminCLI plugin for my admin activities. Is there a workaround?

Thanks for your help

**Comment by dkoper** [comment]
According to https://www.ng.bluemix.net/docs/overview/mngdedicated.html, Bluemix Admin CLI plugin requires cf 6.11.2 or later. Assuming the plugin developer(s) tested their plugin with v6.11.2 before release and found no issues, you could also try this version. Or possibly you could try an older version of the plugin: maybe they introduced a new command recently with a long command name that uncovered this issue. Otherwise you can wait until it is fixed in the cli.

**Comment by dkoper** [comment]
Hi @senthilmkumar,

We have fixed this issue in today's 6.14.0 CLI release. Please check it out:
https://github.com/cloudfoundry/cli#downloads

Regards,
Dies Koper
CF CLI PM

**Comment by senthilmkumar** [comment]
@dkoper Thanks it works fine.
