### ISSUE TITLE
In login faced this bug "index out of range"

### ISSUE THREAD

**Issue by pankajgupta06** [cloudfoundry/cli#655]
Aww shucks.

        Something completely unexpected happened. This is a bug in cf.
        Please file this bug : https://github.com/cloudfoundry/cli/issues
        Tell us that you ran this command:

                cf login i322350

        using this version of the CLI:

                6.13.0-e68ce0f

        and that this error occurred:

                runtime error: index out of range

        and this stack trace:

                goroutine 1 [running]:
        main.generateBacktrace(0x0, 0x0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/main/main.go:127 +0xbb
        main.handlePanics(0x32cb598, 0xc082584210)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/main/main.go:111 +0x183
        github.com/cloudfoundry/cli/cf/net.getBaseDomain(0xc08251f480, 0x33, 0x0
, 0x0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/cf/net/http_client.go:100 +0x13f
        github.com/cloudfoundry/cli/cf/net.PrepareRedirect(0xc082088000, 0xc0820
f6000, 0x1, 0x1, 0x0, 0x0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/cf/net/http_client.go:36 +0x1be
        net/http.(*Client).doFollowingRedirects(0xc082582b40, 0xc082110000, 0xe4
aee8, 0xc08240e090, 0x0, 0x0)
                c:/go/src/net/http/client.go:368 +0xb0b
        net/http.(*Client).Do(0xc082582b40, 0xc082110000, 0xc082582b40, 0x0, 0x0
)
                c:/go/src/net/http/client.go:175 +0xa3
        github.com/cloudfoundry/cli/cf/net.Gateway.doRequest(0x32cb9d0, 0xc08212
1a70, 0xe4a498, 0x1, 0

**Comment by pankajgupta06** [comment]
Got the error, its my fault.
Sorry

**Comment by dkoper** [comment]
Can you share with us what it was? I'm wondering if there's anything we can improve on the CLI side to make it easier to find the error, rather than showing the panic message.

Cheers.
* CLI Team

**Comment by pankajgupta06** [comment]
i entered the proxy instead of cf api end point

But even after entering api i am getting this bug 
=============================================


C:\Users\I322350\Downloads>cf login i322350

API endpoint> cf api https://api.cf.neo.ondemand.com


        Aww shucks.

        Something completely unexpected happened. This is a bug in cf.
        Please file this bug : https://github.com/cloudfoundry/cli/issues
        Tell us that you ran this command:

                cf login i322350

        using this version of the CLI:

                6.13.0-e68ce0f

        and that this error occurred:

                runtime error: index out of range

        and this stack trace:

                goroutine 1 [running]:
        main.generateBacktrace(0x0, 0x0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/main/main.go:127 +0xbb
        main.handlePanics(0x3346a48, 0xc0825984f0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/main/main.go:111 +0x183
        github.com/cloudfoundry/cli/cf/net.getBaseDomain(0xc08245a840, 0x33, 0x0
, 0x0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/cf/net/http_client.go:100 +0x13f
        github.com/cloudfoundry/cli/cf/net.PrepareRedirect(0xc0824a9960, 0xc0823
2eca8, 0x1, 0x1, 0x0, 0x0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundr
y/cli/cf/net/http_client.go:36 +0x1be
        net/http.(*Client).doFollowingRedirects(0xc0825883f0, 0xc08252e380, 0xe4
aee8, 0xc08241e090, 0x0, 0x0)
                c:/go/src/net/http/client.go:368 +0xb0b
        net/http.(*Client).Do(0xc0825883f0, 0xc08252e380, 0xc0825883f0, 0x0, 0x0
)
                c:/go/src/net/http/client.go:175 +0xa3
        github.com/cloudfoundry/cli/cf/net.Gateway.doRequest(0x3346e80, 0xc08255
07e0, 0xe4a498, 0x1, 0
==================================================================

**Comment by dkoper** [comment]
Closing, we now show a better error message. Thanks again!
