### ISSUE TITLE
`GetAppModel` and `ApplicationFromSummary` are using `time.Time` pointer members

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry/cli#656]
While trying to build a CLI plugin, I ran into an issue with the data being returned from cliConnection in my `Run`.

If I do a call `cliConnection.GetApp("my_app")`, the return result always had a `nil` value on the `PackageUpdatedAt` member on the `GetAppModel` struct.

After tracing it down, it appears to be associated with [GetApp](https://github.com/cloudfoundry/cli/blob/8450d0f4264a1b6194ea89aa162fea1f6980d5ee/plugin/models/get_app.go#L20) and [ApplicationFromSummary](https://github.com/cloudfoundry/cli/blob/8450d0f4264a1b6194ea89aa162fea1f6980d5ee/cf/api/app_summary.go#L40). JSON unmarshalling cannot capture a string time into time pointer.

When we changed the member to be a non-pointer `time.Time` everything worked for us.

**Comment by jtarchie** [comment]
We thought we'd be able to file a pull request, but we are unable to fix the tests to pass correctly.

**Comment by simonleung8** [comment]
@jtarchie @dkoper  We confirmed the bug. The plugin model is being populated by a partially filled app model, hence `PackageUpdatedAt` is nil.

**Comment by dkoper** [comment]
Hi @jtarchie. Thanks for trying with the PR! We're a bit low-staffed next week with the CF Summit and release preparation, but you can try reaching out to @krishicks to pair with you on your fix if you want it fast-tracked.

**Comment by krishicks** [comment]
This isn't something that @jtarchie and I need to pair on; this is something that @simonleung8 and I should pair on. It'll require a fair amount of changing how that model is populated.

**Comment by dkoper** [comment]
This issue has been fixed and confirmed by @jtarchie. Thanks guys!
