### ISSUE TITLE
i/o timeout error

### ISSUE THREAD

**Issue by NickTsitlakidis** [cloudfoundry/cli#660]
Hello,

I've just installed the cli on Elementary OS (based on Ubuntu) and I'm trying to do a basic deployment.

I'm getting errors with basic commands like login or setting the api endpoint. It doesn't ask for password and the output is the following:

```Error performing request: Get http://api.useast.appfog.ctl.io/v2/info: dial tcp: i/o timeout```

Any thoughts on what I might be missing?

**Comment by dkoper** [comment]
Hi Nick,

Although not related to your issue, we'd highly recommend you use HTTPS instead of HTTP for communication with the API endpoint. I.e. `cf login -a https://api.useast.appfog.ctl.io`.

The cli is failing to connect to the API endpoint. If you copy the url to your browser, do you get an error too? Are you behind a firewall and require to use an HTTP proxy to access the Internet, if so can you check your `https_proxy` environment variable?

**Comment by NickTsitlakidis** [comment]
Hello, 

I'm not using a proxy to connect. If a try from a windows machine through the same network, everything works as expected.

Calling the url from the browser shows this : 

``{
  "code": 10000,
  "description": "Unknown request",
  "error_code": "CF-NotFound"
}``

Regarding the https you're right. I was just trying out the http link just in case this was causing trouble. Normally I'm trying to connect with https.

**Comment by dkoper** [comment]
Okay. we're making progress. From the same shell where you run the cli, can you confirm you can curl and wget the API endpoint?

**Comment by NickTsitlakidis** [comment]
curl returns the same error as the browser. wget returns a 404.

**Comment by dkoper** [comment]
I'm running out of ideas. Can you rerun the command with CF_TRACE=true and share the full output?

**Comment by NickTsitlakidis** [comment]
Output is the same with or without the CF_TRACE parameter.

Could it be a bad installation of cli?

**Comment by dkoper** [comment]
Output should at least have:

```
d:\>set CF_TRACE=true

d:\>cf api api.blah.com
Setting api endpoint to api.blah.com...

REQUEST: [2015-11-04T07:26:04+09:00]
GET /v2/info HTTP/1.1
Host: api.blah.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.13.0-950d9fc / windows
```

If you could install the latest cf cli release (currently 6.13.0) and try again, that would be great.

**Comment by NickTsitlakidis** [comment]
Tried reinstalling the tool using the latest download provided here in github. Same output. :/

**Comment by simonleung8** [comment]
Hi,

Do you only have problem with that deployment? What happens if you try to target other deployments. Just for example.

`cf api https://api.ng.bluemix.net`
or
`cf api https://api.run.pivotal.io`

**Comment by NickTsitlakidis** [comment]
Thanks for the tip.

It looks like the problem occurred with a specific wifi network and only with my linux installation. Weird combo apparently.

I'm closing the issue.

**Comment by kimkimkere** [comment]
Should we open this problem again? Because I have same problem, too.
I run the CLI from Ubuntu with connection from my phone's tethering

**Comment by dkoper** [comment]
@kimkimkere
See cf help for the CF_DIAL_TIMEOUT environment variable. If increasing that doesn't help, better open a new issue.

**Comment by kimkimkere** [comment]
@dkoper
Wow, that's great. It solves instantly. Thank you very much!

**Comment by balakrishna513** [comment]
Installing "curl" package on ubuntu worked for me. thanks
