### ISSUE TITLE
cf app: index out of range

### ISSUE THREAD

**Issue by afortener** [cloudfoundry/cli#664]
Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		cf app env

	using this version of the CLI:

		6.11.3-cebadc9

	and that this error occurred:

		runtime error: index out of range

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x3)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xa9
	main.handlePanics(0x12555d8, 0xc2100675a0)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x123
	runtime.panic(0x570540, 0xe7c917)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc210037000, 0xc2100b0cf0, 0x24, 0xc2100bcd20, 0x1, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x275
	github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc210342120, 0xc2100b0cf0, 0x24, 0xc21018c6e0, 0x3, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:112 +0x683
	github.com/c

**Comment by dkoper** [comment]
Hi,

Can you please retry on the latest cf cli release?
We fixed a bug in the area this error occurred.

Cheers,
* CLI team

**Comment by ryandotclair** [comment]
I'm running into same issue. It appears when you scale it up, and then scale it down, then do a cf app. 

using this version of the CLI:

		6.12.1-56792aa

	and that this error occurred:

		runtime error: index out of range

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x3)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:175 +0xa9
	main.handlePanics(0x11704e0, 0xc210189b60)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:159 +0x123
	runtime.panic(0x5a5b80, 0xf0d8b7)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc2102697e0, 0xc2100bd450, 0x24, 0xc21018dcc0, 0x1, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x275
	github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc21006ea80, 0xc2100bd450, 0x24, 0xc2100ac420, 0xc, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:179 +0x6e0
	github.com/c

**Comment by dkoper** [comment]
Hi Ryan,
Can you confirm whether it's reproducible with the latest cli release?
https://github.com/cloudfoundry/cli#downloads

**Comment by ryandotclair** [comment]
That works! The latest version on Caskroom/cask/cloudfoundry-cli has the bug. I just had to tap your pivotal/tap for the version with the fix in it. Thanks

**Comment by dkoper** [comment]
Thanks for checking. I wasn't aware of the Caskroom site and their linked version is fairly old. You can always get our latest versions from the github page above.

Regards,
Dies Koper - CF CLI PM
