### ISSUE TITLE
Uploading failed due to : Access is denied

### ISSUE THREAD

**Issue by pankajgupta06** [cloudfoundry/cli#665]
I am trying to upload a simple servlet program, to get familiar with cloud foundry.
while using push command, it throws this error every time.
I tried to upload one sample app but still for me the error remains the same.

Can you tell me what can i do in such scenarios?

Uploading C:\Users\I322350\Desktop\HelloWorld.java...
FAILED
Error uploading application.
open C:\WINDOWS\system32\LogFiles\WMI\RtBackup: Access is denied.

**Comment by dkoper** [comment]
Hi,
Are you using the latest cf cli release (v6.13.0)? Can you enable cf trace (`set CF_TRACE=true`), rerun the command and share the full log? What Windows edition are you using?

Cheers,
* CLI team

**Comment by pankajgupta06** [comment]
yes i am using the same version with windows 10 Enterprise Edition.
The Log is as follows

Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/x-www-form-urlencoded
User-Agent: go-cli 6.13.0-e68ce0f / windows

grant_type=refresh_token&refresh_token=eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJhZjMxM2FhOS03OWY5LTQ5YmYtOGYyMS01Zjc1ZjU2NDhiZTAiLCJzdWIiOiI4OTE2NjY4NC1lMDEyLTQwMjMtYWZiNi0wNTgwNDkwMjEyODIiLCJzY29wZSI6WyJwYXNzd29yZC53cml0ZSIsImNsb3VkX2NvbnRyb2xsZXIud3JpdGUiLCJvcGVuaWQiLCJjbG91ZF9jb250cm9sbGVyLnJlYWQiXSwiaWF0IjoxNDQ2NjExMDUyLCJleHAiOjE0NDkyMDMwNTIsImNpZCI6ImNmIiwiaXNzIjoiaHR0cHM6Ly91YWEuY2YubmVvLm9uZGVtYW5kLmNvbS9vYXV0aC90b2tlbiIsInppZCI6InVhYSIsImdyYW50X3R5cGUiOiJwYXNzd29yZCIsInVzZXJfbmFtZSI6ImkzMjIzNTAiLCJ1c2VyX2lkIjoiODkxNjY2ODQtZTAxMi00MDIzLWFmYjYtMDU4MDQ5MDIxMjgyIiwiYXVkIjpbImNmIiwicGFzc3dvcmQiLCJjbG91ZF9jb250cm9sbGVyIiwib3BlbmlkIl19.AtEP9zg7PfIW3rOf0N7VlZ7ui5VwX0i4pd4XzqjwTeAwyX6S8cGg8khCp1nmg-XUCVoAUKR1jpC5yO6nfE32-JGL5sPtlbXXxoOg_jt57LmuJ1Vu3updUX3ohMxkPocfb-WoHAiin-BMXQ5fU3qz1iienfgIFYkMwXx3Me6-Q5c&scope=

RESPONSE: [2015-11-04T10:51:21+05:30]
HTTP/1.1 200 OK
Content-Length: 1799
Access-Control-Allow-Origin: *
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Cache-Control: no-store
Content-Type: application/json;charset=UTF-8
Date: Wed, 04 Nov 2015 05:21:22 GMT
Expires: 0
Pragma: no-cache
Pragma: no-cache
Server: Apache-Coyote/1.1
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Cf-Requestid: deb2b14d-2d26-46b5-6d09-99124b04ef3b
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block

{"access_token":"[PRIVATE DATA HIDDEN]","token_type":"bearer","refresh_token":"[PRIVATE DATA HIDDEN]","expires_in":599,"scope":"password.write openid cloud_controller.write cloud_controller.read","jti":"614d7741-ecf2-46f1-86ea-6430485df74e"}

REQUEST: [2015-11-04T10:51:21+05:30]
GET /v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/apps?q=name%3AC%3A%5CUsers%5CI322350%5CDesktop%5CHelloWorld.java&inline-relations-depth=1 HTTP/1.1
Host: api.cf.neo.ondemand.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.13.0-e68ce0f / windows



RESPONSE: [2015-11-04T10:51:22+05:30]
HTTP/1.1 200 OK
Content-Length: 4537
Content-Type: application/json;charset=utf-8
Date: Wed, 04 Nov 2015 05:21:22 GMT
Server: nginx
X-Cf-Requestid: 17cefe06-b843-4c0b-5a32-b3e70780daa1
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 75480276-036f-462f-41d7-6011bec12f2f::41dc49cf-e121-4f5a-aad8-c26820fb0c66

{
  "total_results": 1,
  "total_pages": 1,
  "prev_url": null,
  "next_url": null,
  "resources": [
    {
      "metadata": {
        "guid": "bd749fe7-0953-4102-b95a-7163d47e7cce",
        "url": "/v2/apps/bd749fe7-0953-4102-b95a-7163d47e7cce",
        "created_at": "2015-11-04T04:26:16Z",
        "updated_at": "2015-11-04T04:36:08Z"
      },
      "entity": {
        "name": "C:\\Users\\I322350\\Desktop\\HelloWorld.java",
        "production": false,
        "space_guid": "6189cb90-8743-4272-b5e5-c76136a19e22",
        "stack_guid": "48e8b243-3a55-439c-bd67-b72442278356",
        "buildpack": null,
        "detected_buildpack": null,
        "environment_json": {

        },
        "memory": 1024,
        "instances": 1,
        "disk_quota": 1024,
        "state": "STOPPED",
        "version": "31da0be0-20c5-409b-aca5-e0a0337693f2",
        "command": null,
        "console": false,
        "debug": null,
        "staging_task_id": null,
        "package_state": "PENDING",
        "health_check_type": "port",
        "health_check_timeout": null,
        "staging_failed_reason": null,
        "diego": false,
        "docker_image": null,
        "package_updated_at": null,
        "detected_start_command": "",
        "enable_ssh": true,
        "docker_credentials_json": {
          "redacted_message": "[PRIVATE DATA HIDDEN]"
        },
        "space_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22",
        "space": {
          "metadata": {
            "guid": "6189cb90-8743-4272-b5e5-c76136a19e22",
            "url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22",
            "created_at": "2015-10-29T05:04:05Z",
            "updated_at": null
          },
          "entity": {
            "name": "i322350",
            "organization_guid": "04f3ba24-5166-42fc-8ffc-1a5cdc1da5e7",
            "space_quota_definition_guid": null,
            "allow_ssh": true,
            "organization_url": "/v2/organizations/04f3ba24-5166-42fc-8ffc-1a5cdc1da5e7",
            "developers_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/developers",
            "managers_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/managers",
            "auditors_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/auditors",
            "apps_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/apps",
            "routes_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/routes",
            "domains_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/domains",
            "service_instances_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/service_instances",
            "app_events_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/app_events",
            "events_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/events",
            "security_groups_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/security_groups"
          }
        },
        "stack_url": "/v2/stacks/48e8b243-3a55-439c-bd67-b72442278356",
        "stack": {
          "metadata": {
            "guid": "48e8b243-3a55-439c-bd67-b72442278356",
            "url": "/v2/stacks/48e8b243-3a55-439c-bd67-b72442278356",
            "created_at": "2015-06-26T08:57:19Z",
            "updated_at": null
          },
          "entity": {
            "name": "cflinuxfs2",
            "description": "Cloud Foundry Linux-based filesystem"
          }
        },
        "events_url": "/v2/apps/bd749fe7-0953-4102-b95a-7163d47e7cce/events",
        "service_bindings_url": "/v2/apps/bd749fe7-0953-4102-b95a-7163d47e7cce/service_bindings",
        "service_bindings": [

        ],
        "routes_url": "/v2/apps/bd749fe7-0953-4102-b95a-7163d47e7cce/routes",
        "routes": [
          {
            "metadata": {
              "guid": "48fa8ebc-4b95-4fef-88c7-61f0d7e43906",
              "url": "/v2/routes/48fa8ebc-4b95-4fef-88c7-61f0d7e43906",
              "created_at": "2015-11-04T04:26:19Z",
              "updated_at": null
            },
            "entity": {
              "host": "cusersi322350desktophelloworldjava",
              "path": "",
              "domain_guid": "59761e92-b166-4421-8e9a-bd7c142080b2",
              "space_guid": "6189cb90-8743-4272-b5e5-c76136a19e22",
              "domain_url": "/v2/domains/59761e92-b166-4421-8e9a-bd7c142080b2",
              "space_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22",
              "apps_url": "/v2/routes/48fa8ebc-4b95-4fef-88c7-61f0d7e43906/apps"
            }
          }
        ]
      }
    }
  ]
}
Updating app C:\Users\I322350\Desktop\HelloWorld.java in org trial / space i322350 as i322350...

REQUEST: [2015-11-04T10:51:22+05:30]
PUT /v2/apps/bd749fe7-0953-4102-b95a-7163d47e7cce?async=true&inline-relations-depth=1 HTTP/1.1
Host: api.cf.neo.ondemand.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.13.0-e68ce0f / windows

{"name":"C:\\Users\\I322350\\Desktop\\HelloWorld.java"}

RESPONSE: [2015-11-04T10:51:23+05:30]
HTTP/1.1 201 Created
Content-Length: 4022
Content-Type: application/json;charset=utf-8
Date: Wed, 04 Nov 2015 05:21:23 GMT
Server: nginx
X-Cf-Requestid: 4efbc5bf-882f-40b8-62e6-2182de7619e9
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: d87d2f32-bb7e-4082-4e30-36c68400e4fc::5c7359a9-8d67-4ecf-a18d-45295653e64d

{
  "metadata": {
    "guid": "bd749fe7-0953-4102-b95a-7163d47e7cce",
    "url": "/v2/apps/bd749fe7-0953-4102-b95a-7163d47e7cce",
    "created_at": "2015-11-04T04:26:16Z",
    "updated_at": "2015-11-04T05:21:23Z"
  },
  "entity": {
    "name": "C:\\Users\\I322350\\Desktop\\HelloWorld.java",
    "production": false,
    "space_guid": "6189cb90-8743-4272-b5e5-c76136a19e22",
    "stack_guid": "48e8b243-3a55-439c-bd67-b72442278356",
    "buildpack": null,
    "detected_buildpack": null,
    "environment_json": {

    },
    "memory": 1024,
    "instances": 1,
    "disk_quota": 1024,
    "state": "STOPPED",
    "version": "31da0be0-20c5-409b-aca5-e0a0337693f2",
    "command": null,
    "console": false,
    "debug": null,
    "staging_task_id": null,
    "package_state": "PENDING",
    "health_check_type": "port",
    "health_check_timeout": null,
    "staging_failed_reason": null,
    "diego": false,
    "docker_image": null,
    "package_updated_at": null,
    "detected_start_command": "",
    "enable_ssh": true,
    "docker_credentials_json": {
      "redacted_message": "[PRIVATE DATA HIDDEN]"
    },
    "space_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22",
    "space": {
      "metadata": {
        "guid": "6189cb90-8743-4272-b5e5-c76136a19e22",
        "url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22",
        "created_at": "2015-10-29T05:04:05Z",
        "updated_at": null
      },
      "entity": {
        "name": "i322350",
        "organization_guid": "04f3ba24-5166-42fc-8ffc-1a5cdc1da5e7",
        "space_quota_definition_guid": null,
        "allow_ssh": true,
        "organization_url": "/v2/organizations/04f3ba24-5166-42fc-8ffc-1a5cdc1da5e7",
        "developers_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/developers",
        "managers_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/managers",
        "auditors_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/auditors",
        "apps_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/apps",
        "routes_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/routes",
        "domains_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/domains",
        "service_instances_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/service_instances",
        "app_events_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/app_events",
        "events_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/events",
        "security_groups_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22/security_groups"
      }
    },
    "stack_url": "/v2/stacks/48e8b243-3a55-439c-bd67-b72442278356",
    "stack": {
      "metadata": {
        "guid": "48e8b243-3a55-439c-bd67-b72442278356",
        "url": "/v2/stacks/48e8b243-3a55-439c-bd67-b72442278356",
        "created_at": "2015-06-26T08:57:19Z",
        "updated_at": null
      },
      "entity": {
        "name": "cflinuxfs2",
        "description": "Cloud Foundry Linux-based filesystem"
      }
    },
    "events_url": "/v2/apps/bd749fe7-0953-4102-b95a-7163d47e7cce/events",
    "service_bindings_url": "/v2/apps/bd749fe7-0953-4102-b95a-7163d47e7cce/service_bindings",
    "service_bindings": [

    ],
    "routes_url": "/v2/apps/bd749fe7-0953-4102-b95a-7163d47e7cce/routes",
    "routes": [
      {
        "metadata": {
          "guid": "48fa8ebc-4b95-4fef-88c7-61f0d7e43906",
          "url": "/v2/routes/48fa8ebc-4b95-4fef-88c7-61f0d7e43906",
          "created_at": "2015-11-04T04:26:19Z",
          "updated_at": null
        },
        "entity": {
          "host": "cusersi322350desktophelloworldjava",
          "path": "",
          "domain_guid": "59761e92-b166-4421-8e9a-bd7c142080b2",
          "space_guid": "6189cb90-8743-4272-b5e5-c76136a19e22",
          "domain_url": "/v2/domains/59761e92-b166-4421-8e9a-bd7c142080b2",
          "space_url": "/v2/spaces/6189cb90-8743-4272-b5e5-c76136a19e22",
          "apps_url": "/v2/routes/48fa8ebc-4b95-4fef-88c7-61f0d7e43906/apps"
        }
      }
    ]
  }
}
OK

Uploading C:\Users\I322350\Desktop\HelloWorld.java...
FAILED
Error uploading application.
open C:\WINDOWS\system32\LogFiles\WMI\RtBackup: Access is denied.
FAILED
Error uploading application.
open C:\WINDOWS\system32\LogFiles\WMI\RtBackup: Access is denied.

C:\WINDOWS\system32>

**Comment by pankajgupta06** [comment]
what should i do?
Any suggestions please.

**Comment by jhiemer** [comment]
@pankajgupta06 I am not sure if it is possible to push a single java file. I would expect this is not possible. Did you try it with a *.jar or *.war?

**Comment by pankajgupta06** [comment]
I tried with one of the sample app from the git only. but still it was showing the same error.

**Comment by dkoper** [comment]
What is the exact command (with arguments) you are running and from what directory? Are you using a manifest file?

I'm curious why it's first trying to push the Java file from your desktop and then ends up traversing through your windows folders and in the end have your prompt there.

But jhiemer is right that you need to compile and package locally and push the jar or war instead.

**Comment by jhiemer** [comment]
I think the error is even coming from that, as it tries to iterate over a few directories, where the CLI is not able to retrieve information from. 
So steps to proceed:

- Package your application in a war file
- Create a manifest.yml
- Run again

**Comment by pankajgupta06** [comment]
Command:

cf push "C:\Users\I322350\Desktop\Hello World.java"

okay let me try with jar or war too.

**Comment by dkoper** [comment]
Ah, that clears things up. Type `cf push -h` to see the usage syntax.
The first argument after `cf push` is the application name.
So you are currently pushing all files in your current directory (C:\WINDOWS\system32) as an app with name "C:\Users\I322350\Desktop\HelloWorld.java".

Instead, after compiling your code and building your war or jar, use `cf push APPNAME -p "C:\Users\I322350\Desktop\HelloWorld.jar"`. You can check the java buildpack github page for additional requirements for jar or war files to be recognized as such (you may need to create a WEB-INF or META-INF folder with the appropriate manifest file).

**Comment by pankajgupta06** [comment]
ok, thank you sir :)
