### ISSUE TITLE
How to uninstall Cloud Foundry CLI on Mac OSX?

### ISSUE THREAD

**Issue by sunocean** [cloudfoundry/cli#669]
have installed Cloudfoundry version 6.13 using `.pkg` installer .

It looks like using brew would be better solution to keep up with new releases. I would like to uninstall current version of CF CLI so i could let brew manage my CF cli upgrades.

Do we have uninstall instructions documented somewhere?

Thanks!

**Comment by krishicks** [comment]
Hi @sunocean,

The OS X installer creates a binary, `/usr/local/bin/cf` and a directory, `/usr/local/share/doc/cf-cli`.

Deleting those would fully uninstall it.

**Comment by sunocean** [comment]
Hi @krishicks  , thank you very much. it works.
