### ISSUE TITLE
Plugin API leaking file descriptors

### ISSUE THREAD

**Issue by davidehringer** [cloudfoundry/cli#678]
I have some plugins that basically iterate through all Org, Spaces, and Apps to do some work.  I had originally implemented this using `cf curl` via `CliCommandWithoutTerminalOutput`.  
```
cliConnection.CliCommandWithoutTerminalOutput("curl", ...)
```
There were not problems here.  I changed the implementation to use the new plugin APIs such as `GetOrgs()`, `GetOrg(name)`, `GetApps()`, and so on.  In doing this I started getting `accept tcp 127.0.0.1:49251: too many open files` errors after a moderate number of calls to those plugin APIs.

It looks like in `cli_connection.go` those new API methods aren't closing the Client.  Whereas in the methods backing `CliCommandWithoutTerminalOutput` the client connection is closed (`defer cliServerConn.Close()`).

**Comment by krishicks** [comment]
Hi @davidehringer,

Seems legit. Thanks!

KH

**Comment by dkoper** [comment]
Hi @davidehringer,

We have fixed the bug. If you could verify the issue is resolved for you and report back here, we can include it in our upcoming CLI release. Visit https://github.com/cloudfoundry/cli#downloads and download an Edge binary (links are in the final paragraph).

Cheers,
Dies Koper
CF CLI PM

**Comment by davidehringer** [comment]
Hi @dkoper,

Based on my testing, that looks to have resolved the problem.  Rather than download the edge binary, I had to recompile my plugin against the latest source.

Thanks!

**Comment by dkoper** [comment]
Thanks for the quick verification!
