### ISSUE TITLE
cf help doesn't provide the correct usage string. 

### ISSUE THREAD

**Issue by jmaryland** [cloudfoundry/cli#680]
$ cf files -i 1 psg app
Getting files for app psg in org PaaS_PrototypePhase2 / space development as rs35752...
OK

.java-buildpack/                             -
.java-buildpack.log                      82.2K
ESAPI.properties                         23.9K
JFP_Authentication.config                  74B
JfpPolicy.json                            1.9K
JfpPolicy.xml                            11.0K
META-INF/                                    -
bootstrap.yml                             184B
com/                                         -
cpsap-sit3550-StatisticsArchiveFile.gfs       9.3M
eventclass.properties                     6.5K
lib/                                         -
org/                                         -

$ cf help files        
NAME:
   files - Print out a list of files in a directory or the contents of a specific file

ALIAS:
   f

USAGE:
   cf files APP [-i INSTANCE] [PATH]

OPTIONS:
   -i   Instance
$ cf files psg -i 1 app
FAILED
App app not found

**Comment by dkoper** [comment]
Hi Jay,

Is it possible you are using a very old version of the CLI? I believe this is a bug that was fixed almost a year ago (#326). The current cf cli version is 6.13.0, which returns:
```
USAGE:
   cf files APP_NAME [PATH] [-i INSTANCE]
```

Cheers,
Dies Koper
CF CLI PM
