### ISSUE TITLE
create-app-manifest unexpected error

### ISSUE THREAD

**Issue by karol-brejna-i** [cloudfoundry/cli#683]
Aww shucks.

        Something completely unexpected happened. This is a bug in cf.
        Please file this bug : https://github.com/cloudfoundry/cli/issues
        Tell us that you ran this command:

                cf create-app-manifest xxx

        using this version of the CLI:

                6.12.3-c0c9a03

        and that this error occurred:

                runtime error: invalid memory address or nil pointer dereference

        and this stack trace:

                goroutine 1 [running]:
        main.generateBacktrace(0xc21000a000, 0x3)
                /var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:117 +0xa9
        main.handlePanics(0x7f121af06450, 0xc2101967e0)
                /var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:101 +0x123
        runtime.panic(0x980a00, 0x129f148)
                /usr/local/go/src/pkg/runtime/panic.c:248 +0x106
        github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).createManifest(0xc2102a20c0, 0xc21029f360, 0x24, 0xc2100a52c0, 0x15, ...)
                /var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:91 +0x57
        github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).Execute(0xc2102a20c0, 0x7f121af09c18, 0xc21028fc00)
                /var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:87 +0x

**Comment by dkoper** [comment]
Hi @karol-brejna-i,

Could you rerun this on the latest cf cli release and enable CF_TRACE and send that to us?
This command makes an API call to retrieve app details and my concern is that somehow the name or app memory fields may not be populated properly in the response.

Cheers,
Dies Koper
CF CL PM
