### ISSUE TITLE
cf create-app-manifest fails

### ISSUE THREAD

**Issue by jchesterpivotal** [cloudfoundry/cli#688]
Per the helpful message (which is awesome, by the way, you guys rock):

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		cf create-app-manifest spike

	using this version of the CLI:

		6.12.2-24abed3

	and that this error occurred:

		runtime error: invalid memory address or nil pointer dereference

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x3)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xa9
	main.handlePanics(0x116bad8, 0xc2101864e0)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x123
	runtime.panic(0x5a3660, 0xf09679)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).createManifest(0xc21026b7e0, 0xc210089a50, 0x24, 0xc210326cd0, 0x5, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:91 +0x57
	github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).Execute(0xc21026b7e0, 0x116c838, 0xc210265b40)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:87 +0x431
	main.main()
		/Us

We installed the [autopilot](https://github.com/concourse/autopilot), but after uninstalling it, `create-app-manifest` shows the same fault.

Of interest is that the help for `create-app-manifest` seems to be for `logs`:

```
$ cf create-app-manifest
FAILED
Incorrect Usage. Requires app name as argument

NAME:
   logs - Tail or show recent logs for an app

USAGE:
   CF_NAME logs APP_NAME

OPTIONS:
   --recent      Dump recent logs instead of tailing
```

We're not sure if that's related; if it's not feel free to tell us and we'll open another issue.

**Comment by krishicks** [comment]
Hi @jchesterpivotal,

Your CLI is quite out of date.

Can you try updating to the [latest release](https://github.com/cloudfoundry/cli/releases/latest) and try it again?

**Comment by jchesterpivotal** [comment]
Confirm that latest works for us, thanks.

As an aside I recall putting in an issue suggesting that the CLI should advertise when it is out of date, but I can't find it.

**Comment by dkoper** [comment]
Hi @jchesterpivotal,

That was #292 - we have not forgotten. #657 is a similar feature suggestion, even going as far as doing the update for you. Hope to get to them soon!

Regards,
Dies Koper
CF CLI PM
