### ISSUE TITLE
CLI installer for Mac OS X isn't signed with a developer cert

### ISSUE THREAD

**Issue by zaksoup** [cloudfoundry/cli#689]
In order for GateKeeper to allow the CF CLI installer it must be created with an apple developer cert. Currently trying to use the install results in an error that must be dismissed by disabling Gatekeeper for this binary which is a frustrating user experience.

**Comment by krishicks** [comment]
We have two stories for this:

https://www.pivotaltracker.com/story/show/66469062
https://www.pivotaltracker.com/story/show/66476084
