### ISSUE TITLE
cf app scale-demo command fails after scaling down application from 4 to 1 instances

### ISSUE THREAD

**Issue by phopper-pivotal** [cloudfoundry/cli#691]
cf app scale-demo

	using this version of the CLI:

		6.12.2-24abed3

	and that this error occurred:

		runtime error: index out of range

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x3)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xa9
	main.handlePanics(0x116ba98, 0xc210186600)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x123
	runtime.panic(0x5a3660, 0xf08d17)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc21026b9c0, 0xc210304390, 0x24, 0xc21036a840, 0x1, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x275
	github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc21006eaf0, 0xc210304390, 0x24, 0xc21017edf0, 0xa, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:179 +0x6e0
	github.com/c

**Comment by dkoper** [comment]
Please upgrade to the latest CLI release. The offending code has been removed.
https://github.com/cloudfoundry/cli#downloads

Regards,
Dies Koper
CF CLI PM

**Comment by phopper-pivotal** [comment]
Thank you. Local binary updated to

cf version 6.14.0+2654a47-2015-11-18
