### ISSUE TITLE
`cf push` should allow me to set a health-check

### ISSUE THREAD

**Issue by onsi** [cloudfoundry/cli#694]
On Diego, workers that do not listen on a port need to be run with `cf set-health-check APP none`

It would be vastly more convenient if the health check could be set on push:

```
cf push APP --health-check=none --no-routes
```

**Comment by ematpl** [comment]
As of v6.13.0, the CLI has the `--health-check-type` flag, or `-u` for short:

```
$ cf help push
<snip />
OPTIONS:
   -i                           Number of instances
   --docker-image, -o           docker-image to be used (e.g. user/docker-image-name)
   --health-check-type, -u      Application health check type (e.g. port or none)
```

**Comment by onsi** [comment]
oh hai.  that was easy! :grinning:
