### ISSUE TITLE
app manifest should support referencing a docker image with docker registry

### ISSUE THREAD

**Issue by jbayer** [cloudfoundry/cli#696]
i didn't see support for it here and assume that it means there is no support for specifying a docker image reference in a cf app manifest.yml
https://github.com/cloudfoundry/cli/blob/aa1c389162d53caec986a96ef370d8bd7a4ac142/cf/manifest/manifest.go#L167-L223

**Comment by dkoper** [comment]
Hi @jbayer,

Correct. We are focusing on exposing back-end features such as the routing related ones and manifest support is falling behind. It hasn't fallen off my radar though!

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
@SocalNick The docker upload API is still marked `experimental`. What are the plans with it?
http://apidocs.cloudfoundry.org/238/apps/creating_a_docker_app_%28experimental%29.html

**Comment by jbayer** [comment]
i'm not aware of reasons it should still marked experimental. are there any?

/cc @dieucao

**Comment by SocalNick** [comment]
Maybe because `docker_credentials_json` and `ports` are still experimental? We can remove the experimental tag from the top-level if you like. Story: https://www.pivotaltracker.com/story/show/126058395

FWIW, we intend to remove `docker_credentials_json` as part of this story until we officially tackle private docker repos: https://www.pivotaltracker.com/story/show/92603918

**Comment by rohitgkk** [comment]
Hi 
there is a manifest.yml option docker_image: which can be used to push cloud foundry image but I was unable to do so.

My question is can we push docker image via manifest? ( docker_image: )

**Comment by jbayer** [comment]
@dkoper @dieucao @zrob now that there is proper private docker repository support in CF, not having a docker image manifest option is one of the last things needed to make the docker image experience 1st class. is support for this planned?

**Comment by dkoper** [comment]
@jbayer Definitely!

**Comment by wmnnd** [comment]
@dkoper Great to hear that Docker support is now planned for manifests. Is there an ETA when we can expect this feature?

**Comment by motevets** [comment]
:+1:

**Comment by dkoper** [comment]
@wmnnd, @motevets Are you planning to use only public Docker images, or also from private Docker repositories?

The story for Docker image support in manifests is currently scheduled for delivery in 1-2 months.
Private Docker repo support in manifest files may take longer: we need to explore a solution where we preferably not force people to include secrets in their app manifest.

The ETA for the former is based on the current refactor of `push` (and subsequent refactor of `create-app-manifest`): current `push` has a lot of code and not written well to be easily extended. We're cleaning it up (and adding lots of tests) to make it easier to enhance, but that takes time.

If demand is high enough, we can at least investigate how much effort and risk is involved in implementing it in the current `push` ahead of the refactor completion...

**Comment by wmnnd** [comment]
@dkoper I am using only private registries. For now, I am using `cf curl /v2/apps` with a JSON file that looks something like a manifest already and then a shell script to attach the necessary services and routes:
```json
{
  "name": "myapp",
  "memory": 128,
  "space_guid": "…",
  "docker_image": "my.registry/image",
  "docker_credentials": {
    "username": "foo",
    "password": "bar"
  },
  "environment_json": {
    "FOO": "bar"
  },
  "diego": true
}

```
If I may make a suggestion about avoiding putting the credentials for private registries in the manifest: You already have `CF_DOCKER_PASSWORD`, so if you added `CF_DOCKER_USER`, I think all would be good :smile:

**Comment by motevets** [comment]
My use case at the time was for a public image, but I would find private
images useful in the future.

I like solution @wmnnd proposed using environment variables. I'm also not
scared of putting credentials in my manifest because I already put
sensitive environment variables in my manifest, but don't check it in with
the source code.

**Comment by dkoper** [comment]
This feature is now supported in cf CLI 6.31.0 onwards.
For now the username can be set in the app manifest and the password passed in with an environment variable. We are exploring other ways to provide both in the future.
