### ISSUE TITLE
go build fails for plugin building / dependency cannot be found

### ISSUE THREAD

**Issue by emirozer** [cloudfoundry/cli#697]
Hi,

I cannot build the plugin i am working on because of a dependency that cannot be fetched:

github.com/cloudfoundry/cli/cf/resources

../../go/src/github.com/cloudfoundry/cli/cf/i18n/i18n.go:10:2: cannot find package "github.com/cloudfoundry/cli/cf/resources" in any of:

**Comment by emirozer** [comment]
https://github.com/cloudfoundry/cli/search?utf8=%E2%9C%93&q=AssetNames

You can see no such package or func signature exist.
@simonleung8 @krishicks 

Thanks!

**Comment by krishicks** [comment]
Hi @emirozer,

That dependency isn't fetched; it's generated. You'll need to run `bin/generate-language-resources` in `github.com/cloudfoundry/cli`.

**Comment by emirozer** [comment]
Ah okay, probably docs aren't up to date on this, will open a pr. Thanks!

**Comment by krishicks** [comment]
I've updated the plugin README: https://github.com/cloudfoundry/cli/commit/3d0c935657e138c6090c77d667479fab6e0fdd6b
