### ISSUE TITLE
falla la conexión con Bluemix en WIN10 

### ISSUE THREAD

**Issue by DiegOliveros** [cloudfoundry/cli#698]
Command
                cf api https://api.ng.bluemix.net

                CLI Version
                6.14.0+2654a47

                Error
                runtime error: invalid memory address or nil pointer dereference

                Stack Trace
                        goroutine 1 [running]:
        main.generateBacktrace(0x0, 0x0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:129 +0xbb
        main.handlePanics(0x3826ac8, 0xc0825879d0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:113 +0x183
        github.com/cloudfoundry/cli/cf/net.Gateway.performRequestForResponseBytes(0x3826ec0, 0xc0825626c0, 0xe632c0, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x3826ce8, 0xc0825ab920, ...)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/net/gateway.go:250 +0x48b
        github.com/cloudfoundry/cli/cf/net.Gateway.PerformRequestForJSONResponse(0x3826ec0, 0xc0825626c0, 0xe632c0, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x3826ce8, 0xc0825ab920, ...)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/net/gateway.go:268 +0x9e
        github.com/cloudfoundry/cli/cf/net.Gateway.GetResource(0x3826ec0, 0xc0825626c0, 0xe632c0, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x3826ce8, 0xc0825ab920, ...)
                C:/GoAgent/pipelines/Win64-Unit-Tests/sr

                Your Platform Details
                e.g. Mac OS X 10.11, Windows 8.1 64-bit, Ubuntu 14.04.3 64-bit

                Shell
                e.g. Terminal, iTerm, Powershell, Cygwin, gnome-terminal, terminator

C:\Users\DIEGO OLIVEROS\Documents\1.POLI\IBM\primerapp>cf api https://api.ng.bluemix.net
Configurando endpoint api a https://api.ng.bluemix.net...

        Something unexpected happened. This is a bug in cf.

        Please re-run the command that caused this exception with the environment
        variable CF_TRACE set to true.

        Also, please update to the latest cli and try the command again:
        https://github.com/cloudfoundry/cli/releases

        Please create an issue at: https://github.com/cloudfoundry/cli/issues

        Include the below information when creating the issue:

                Command
                cf api https://api.ng.bluemix.net

                CLI Version
                6.14.0+2654a47

                Error
                runtime error: invalid memory address or nil pointer dereference

                Stack Trace
                        goroutine 1 [running]:
        main.generateBacktrace(0x0, 0x0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:129 +0xbb
        main.handlePanics(0x17fb730, 0xc082541ba0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:113 +0x183
        github.com/cloudfoundry/cli/cf/net.Gateway.performRequestForResponseBytes(0x17fbad8, 0xc0821af950, 0xe632c0, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x17fb900, 0xc0825570e0, ...)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/net/gateway.go:250 +0x48b
        github.com/cloudfoundry/cli/cf/net.Gateway.PerformRequestForJSONResponse(0x17fbad8, 0xc0821af950, 0xe632c0, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x17fb900, 0xc0825570e0, ...)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/net/gateway.go:268 +0x9e
        github.com/cloudfoundry/cli/cf/net.Gateway.GetResource(0x17fbad8, 0xc0821af950, 0xe632c0, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x17fb900, 0xc0825570e0, ...)
                C:/GoAgent/pipelines/Win64-Unit-Tests/sr

                Your Platform Details
                e.g. Mac OS X 10.11, Windows 8.1 64-bit, Ubuntu 14.04.3 64-bit

                Shell
                e.g. Terminal, iTerm, Powershell, Cygwin, gnome-terminal, terminator

**Comment by krishicks** [comment]
Hi @DiegOliveros,

Please re-run the command with CF_TRACE=true and paste the log here.

Also, which shell were you using? Powershell? Something else?

**Comment by dkoper** [comment]
Closing this issue as we don't have enough information to investigate. Feel free to reopen or open a new issue when you have more information to share.

Cheers,
Dies Koper
CF CLI PM
