### ISSUE TITLE
How to build the CF CLI with i18n resource file changes? 

### ISSUE THREAD

**Issue by liujul** [cloudfoundry/cli#700]
I updated i18n resources on my locale machine. How do I build the CF CLI to pick up the translation update? 

I issues ./bin/build, but the translation updates do not appear in the executable.

**Comment by krishicks** [comment]
Hi @liujul,

Can you be more explicit about the steps you performed? Did you update an existing file, or add a new file? Are you building against the latest cli source? How are you determining the translations are not in the binary? A list of steps to use to reproduce the issue would be helpful.

`bin/build` should be sufficient as it runs `bin/generate-language-resources` for you, which creates go-bindata out of the files in `cf/i18n/resources`, which is what is used for translations.

**Comment by liujul** [comment]
I figured it out finally. bin/build is sufficient to build it wiht i18n files.

**Comment by krishicks** [comment]
Excellent.
