### ISSUE TITLE
love the install via homebrew, but shouldn't it be a cloudfoundry tap, rather than a pivotal?

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/cli#703]
Seems like the tap should be for CFF products, not for Pivotal products.

**Comment by sykesm** [comment]
Agreed.

/cc @chipchilders

**Comment by dkoper** [comment]
Thanks Shannon for bringing this up.
The "Experimental" install of the cf cli through Homebrew has been around for almost 2 years, so I agree it's about time to evaluate it, and consider a new, official home.
I'll discuss with the team what our options are, also what the download statistics are like.

@flavorjones @chipchilders The [Pivotal tap](https://github.com/pivotal/homebrew-tap) includes bosh-init, which doesn't fall under the cli team. If we were to introduce a CFF products tap, would a team like the CI/Tools team be better positioned to own it? We'd then just register our new releases with it as we currently do.

**Comment by flavorjones** [comment]
tagging @vkelkar-pivotal, PM of Toolsmiths

**Comment by krishicks** [comment]
This is now available under cloudfoundry/tap:

```
brew tap cloudfoundry/tap
brew install cf-cli
```
