### ISSUE TITLE
distribute signed OSX package installer

### ISSUE THREAD

**Issue by jbayer** [cloudfoundry/cli#708]
i got some feedback below from a new CLI user that the OSX package is not signed. is that something we could consider to improve the UX of the cf cli?

_Installing CF CLI: On Mac, .pkg installer file is not signed (install blocked by OSX)
Recommendation: Request certs from Apple and sign PKG files_

**Comment by dkoper** [comment]
Hi James,

This is something we have started, see https://www.pivotaltracker.com/story/show/66469062.
We also have a story for Windows.

Regards,
Dies Koper
CF CLI PM
