### ISSUE TITLE
cf restage recommended on binding a service

### ISSUE THREAD

**Issue by duncwinn** [cloudfoundry/cli#709]
When following these typical steps:

 $ cf push redis-example-app --no-start
 $ cf create-service p-redis development redis
 $ cf bind-service redis-example-app redis

The bind service tells you to restage. But the app has not been staged yet because it's not been started. 

Both the --no-start and the --bind-service options need more documentation / help prompts and if the desired behaviour is correct then the --bind-service needs to return a different response if the app is not started.

**Comment by krishicks** [comment]
It would be helpful if you had suggestions for what kind of messaging you’d like to see. If you don’t, that’s fine too.

I’m also not sure about implementation for this because I don’t know how we can know that the app you pushed wasn’t started in a later command.

Whatever message it would show should be generic and helpful enough to cover both scenarios.

**Comment by dkoper** [comment]
We have improved the description of the `restage` command.
If we improved the --no-start` option of `push as follows, it would reflect better what is happening:
```
--no-start                   Do not stage and start an app after pushing
```

I'm not familiar with the --bind-service option, I don't think we have that. Is there an issue with the response from `bind-service` and what would you suggest it to be?

**Comment by gjunming** [comment]
@dkoper  

but is restage really necessary.  having a restart is helpful?

so, restage is a so huge action, where restart is more light.

could we just restart after bind/unbind service?

**Comment by dkoper** [comment]
@gjunming If you have a Java app with a bound postgres service, the Java buildpack will add the postgres jdbc driver during staging. When you then unbind that service and bind a mysql service, and restart your app, connection details and credentials for the new services will be passed to your app, but it'll still have the postgres library and no mysql library. In this case, restarting is required.
So it depends on whether the buildpack does anything special during the staging process depending on the bound service. We'd rather play it safe and suggest people to restage, but when people understand what happens during staging they are free to ignore the tip and just do a restart.
