### ISSUE TITLE
X-Cf-Warnings header is not displayed to user

### ISSUE THREAD

**Issue by crhino** [cloudfoundry/cli#711]
While working on a feature to add warnings for clients of the Cloud Controller, we noticed that the CLI is not showing these warnings to the CLI user currently.

Trying follow the CLI history here, we first have these two stories [#76833522](https://www.pivotaltracker.com/story/show/76833522) and [#77395800](https://www.pivotaltracker.com/story/show/77395800). Our reading of these stories is that the first story removes the warning output from the CLI, but the second story adds it back after finding out that the warnings were used not just for deprecation messages but also actual warnings.

A while afterwards, there is [this commit](https://github.com/cloudfoundry/cli/commit/f7be577#diff-16aa7e9dc7803fad8cb24d4ec7429cecL213) that removes the `warningsCollector.PrintWarnings()` call from the main.go. We are not totally sure, but we believe that this was an unintended change and caused the warnings to no longer be printed.

Ideally we would like to see the CLI print this warnings to users again, but wondering what your thoughts are as well.

@crhino && @yuzhangcmu

**Comment by dkoper** [comment]
Tracker discussion on Pivotal Tracker story.
