### ISSUE TITLE
create-user-provided-service should accept a file path that contains parameters

### ISSUE THREAD

**Issue by mcelep** [cloudfoundry/cli#714]
Hi,

create-user-provided-service command should ideally accept a file path that contains parameters just like the create-service command.
Example :  cf create-user-provided-service my-db-mine -p ~/workspace/db_credentials.json

BR,
Murat

**Comment by dkoper** [comment]
Hi Murat,

We recently received the same enhancement request in #650. May I ask your specific use case?

Cheers,
Dies Koper
CF CLI PM

**Comment by krishicks** [comment]
I think we can close this in favor of #650.
