### ISSUE TITLE
cf push fails if paths are too long (more than about 260 chars) on windows

### ISSUE THREAD

**Issue by d024441** [cloudfoundry/cli#716]
Pushing an app on windows with 'deep nested' paths (path length > 260) fails with 
```
FAILED
Error uploading application.
GetFileAttributesEx ...
```
This issue was already reported in #564 but is not fixed in client version 6.14.0: 
```
>cf --version
cf version 6.14.0+2654a47-2015-11-18
```
For reference please see:
- Go issue: https://github.com/golang/go/issues/3358
- Windows API (MAX_PATH):
 - https://msdn.microsoft.com/de-de/library/windows/desktop/aa364944%28v=vs.85%29.aspx
 - https://msdn.microsoft.com/de-de/library/windows/desktop/aa365247%28v=vs.85%29.aspx#maxpath

**Comment by krishicks** [comment]
Hi @d024441,

This has been fixed in the latest edge release. See the last comment in the issue you mentioned: https://github.com/cloudfoundry/cli/issues/564#issuecomment-163785073

**Comment by krishicks** [comment]
What I said above isn't strictly correct; this is fixed specifically for the case where you use `.cfignore` to ignore directories that are too long, as in the node_modules case in the linked issue #564. https://github.com/cloudfoundry/cli/issues/728 will be used to track fixing this for non-cfignored directories.
