### ISSUE TITLE
Wrong column width when display non-latin characters in table.

### ISSUE THREAD

**Issue by weago** [cloudfoundry/cli#723]
CF CLI will display table with wrong column width when the table header has non-latin characters. For example, if I set locale to zh_Hans (zh-cn), and retrieve the CF applications through "cf apps" command, the table will looks like:

名称          状态
APP1     Running
...

The width of "状态”(State) column header was wrong. It seems that the width calculation of non-latin character has some issues..

![wrong-width](https://cloud.githubusercontent.com/assets/6398951/12000678/dd435190-ab15-11e5-9795-769b62e6c8fc.png)

**Comment by dkoper** [comment]
Hi @weago 

Thanks for your report. We have fixed this in cf CLI release v6.15.0 published two days ago.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM
