### ISSUE TITLE
cf files not working

### ISSUE THREAD

**Issue by dsyer** [cloudfoundry/cli#724]
This happens for all apps in all spaces:

```
$ cf files voter-module
Getting files for app voter-module in org FrameworksAndRuntimes / space dsyer as dsyer@gopivotal.com...
FAILED
Server error, status code: 400, error code: 190001, message: File error: Request failed for app: voter-module, instance: 0 and path:  as the instance is not found.
```

**Comment by dkoper** [comment]
Hi Dave,

'cf files' is only supported for apps deployed to DEAs, not DIEGO. Can you confirm what your apps are running on?
We have a story upcoming to improve the command's help and error messages.

Regards,
Dies Koper 
CF CLI PM

**Comment by krishicks** [comment]
Related cf-dev thread: https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/MRIMP4XQLV5Q2PAIXIKBRFURS2ZAKTSR/#QK4I56RPV5AMXXTLP4OGRVDKOJYORVUQ

**Comment by dkoper** [comment]
We have improved the error message and help text of `cf files` in cf CLI release v6.15.0 published two days ago.
https://github.com/cloudfoundry/cli#downloads

**Comment by mgunter-pivotal** [comment]
Will diego cells ever support CF FIles or only CF ssh going forward?

**Comment by krishicks** [comment]
That's a question for the Diego PM, @emalm.

**Comment by ematpl** [comment]
@mgunter-pivotal: It's theoretically possible, but not currently prioritized.

Thanks,
Eric, CF Runtime Diego PM

**Comment by ursyppc** [comment]
Any update on this? Is this being worked upon? What's the alternative to get the files in Diego?
