### ISSUE TITLE
Homebrew: install cf-cli not found

### ISSUE THREAD

**Issue by gawin** [cloudfoundry/cli#726]
When following the README.md Homebrew is unable to install cf-cli:

```
$ brew tap cloudfoundry/tap
==> Tapping cloudfoundry/tap
Cloning into '/usr/local/Library/Taps/cloudfoundry/homebrew-tap'...
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
Checking connectivity... done.
Tapped 1 formula (27 files, 17.8K)
```
```
$ brew install cf-cli
==> Installing cf-cli from cloudfoundry/tap
Error: No available formula with the name "cloudfoundry-cli"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
This formula was found in a tap:
Caskroom/cask/cloudfoundry-cli
To install it, run:
  brew install Caskroom/cask/cloudfoundry-cli
```

```
$ brew --version
Homebrew 0.9.5 (git revision ef28; last commit 2016-01-07)
```

**Comment by krishicks** [comment]
This seems to be a bug in `conflicts_with`. It seems you need to have `pivotal/tap` tapped for it to work, otherwise it fails because it couldn't find `cloudfoundry-cli`.

I'll revert @sykesm's commit for now.

**Comment by krishicks** [comment]
Updated: https://github.com/cloudfoundry/homebrew-tap/commit/1248f038aba788a58f2c51b6c8c16d68103e804d

**Comment by krishicks** [comment]
Issue created in homebrew: https://github.com/Homebrew/homebrew/issues/47909

**Comment by krishicks** [comment]
I closed the issue in homebrew as using the fully-qualified "pivotal/tap/cloudfoundry-cli" name in the `conflicts_with` line works.

**Comment by krishicks** [comment]
@gawin Let me know if you continue to see the problem with the updated tap.
