### ISSUE TITLE
Cf commands fails intermittently dial tcp: i/o timeout

### ISSUE THREAD

**Issue by nitinpadalia** [cloudfoundry/cli#731]
Hi,
My CF CLI commands fail intermittently giving TCP timeout error.

I've gone through below issue, it says a retry is introduced in v6.6.2
https://github.com/cloudfoundry/cli/issues/272

I am using version 6.14.1+dc6adf6-2015-12-22 for cli, how can I verify that retry is being called?

As in CF debug logs I see request is being logged only one time, however tcp: i/o timeout is logged twice two time.

**Comment by dkoper** [comment]
Hi @nitinpadalia 

The CLI does not expose any logs that would help you to determine if, and how many retries have occurred. CF trace would look no different.
The tcp i/o timeout message comes from your system. I don't know how the message was logged twice (e.g. right after each other, or with CF TRACE message templating around it?).

Two options to try is to either put a proxy between your CLI and API endpoint that logs the requests going through, or compile a special version of the CLI with extra debugging statements to log retries.
Feel free to reach out if you need any help with that.

Regards,
Dies Koper
CF CLI PM
