### ISSUE TITLE
app status listing error for 1 stopped app

### ISSUE THREAD

**Issue by squid314** [cloudfoundry/cli#745]
I ran `cf app my-app-name` when there was 1 instance of my app in a stopped state. The following error came up. I had just run `cf app my-other-app` which had 2 running instances and it worked fine, showing the status of both instances.

        Aww shucks.

        Something completely unexpected happened. This is a bug in cf.
        Please file this bug : https://github.com/cloudfoundry/cli/issues
        Tell us that you ran this command:

                cf app my-app-name

        using this version of the CLI:

                6.12.1-56792aa

        and that this error occurred:

                runtime error: index out of range

        and this stack trace:

                goroutine 1 [running]:
        main.generateBacktrace(0xc21000a000, 0x3)
                /Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:175 +0xa9
        main.handlePanics(0x116fb40, 0xc210189640)
                /Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:159 +0x123
        runtime.panic(0x5a5b80, 0xf0d8b7)
                /usr/local/go/src/pkg/runtime/panic.c:248 +0x106
        github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc21026a420, 0xc2100cd090, 0x24, 0x0, 0x0, ...)
                /Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x275
        github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc21006ea80, 0xc2100cd090, 0x24, 0xc2102c8f20, 0x16, ...)
                /Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:179 +0x6e0
        github.com/cloudfoun

**Comment by krishicks** [comment]
@squid314 Can you try updating your CLI to the [latest version](https://github.com/cloudfoundry/cli/releases/latest) and try the above again? 6.12.1-56792aa is a bit old at this point.

**Comment by dkoper** [comment]
A bug in a similar location was addressed in v6.12.3.
Closing, feel free to reopen or create a new issue if you encounter the issue in the latest cf CLI release.

**Comment by squid314** [comment]
Sorry about not getting back to you on this. I had been using the homebrew version of the cf cli and it was old. It is now updated and I will verify that this is not a problem any longer. Thanks.
