### ISSUE TITLE
manifest mapper doesn't map router-path property

### ISSUE THREAD

**Issue by floriangosse** [cloudfoundry/cli#748]
Currently you can't set the route-path in the manifest.yml. I created a PR which implemented this missing feature (#747).

**Comment by dkoper** [comment]
Hi @floriangosse,

We have a story on supporting this new feature in app manifest files and the reason I haven't prioritised it yet is because we're still reviewing the UX of it. Can you explain your PR's UX, how it compares to the one suggested in our story?
https://www.pivotaltracker.com/story/show/104193622

Cheers,
Dies Koper
CF CLI PM

**Comment by floriangosse** [comment]
Hi @dkoper,

I like like the way, to move all the route specific properties into a list and make is possible to define multiple of it.
For me it isn't needed define multiple routes for my applications, but for someone this will be the thing that is needed.

My solution was simple. I simply added the `route-path` value of the `yamlMap` to the `appParams`. This was the logical and missing step for me after the last release which makes it possible to define a route path with the command line options.

**Comment by dkoper** [comment]
Note that we have a proposal (two actually) on supporting routes with paths in App Manifests to the CF Dev mailing list:
https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/message/N4ZDS7FVHBQFSGP724ZAXUOMISNVURIR/

Please take a look and join the discussion!

**Comment by sradnidge** [comment]
Hi Dies,

What's the status of this? The docs suggest it has been implemented, if it has then there looks to be a bug that I can't map a path onto another host name via the manifest (can do via CLI).

So for example:

```
---
  name: app-v1
  routes:
  - route: app.domain.com/v1
```

Doesn't work?

**Comment by dkoper** [comment]
@sradnidge I failed to update & close this issue. It was implemented in cf CLI 6.21.0, two weeks ago.
https://github.com/cloudfoundry/cli#downloads

Please confirm what cf CLI version you're using, and if 6.21.0 or later, please submit a new issue with all the details (cf CLI version, cf trace).

Cheers,
Dies Koper
CF CLI PM

**Comment by sradnidge** [comment]
Awesome - cheers! I was trying with 6.20, will give 6.21 a try and report back :)

**Comment by sradnidge** [comment]
Can confirm - all working as expected. FWIW I'm glad you went with that format for the 'UI', its nice.
