### ISSUE TITLE
Using bad paramter on create private domain request

### ISSUE THREAD

**Issue by cgfrost** [cloudfoundry/cli#750]
The field `wildcard` doesn't exist on the the endpoint to create a private domain. The CLI shouldn't use it.

`cf create-domain ORG DOMAIN`
`POST /v2/private_domains`

Related: https://github.com/cloudfoundry/cloud_controller_ng/issues/526

**Comment by dkoper** [comment]
@zrob & @fkotsian

Has this field never existed on this endpoint, or is there a CC version before which we should keep specifying it?

**Comment by cgfrost** [comment]
The documentation goes as far back as version 192 (API version 2.17.0) which still doesn't have the field. I checked all the in between versions as well.

**Comment by dkoper** [comment]
@dieucao confirmed on slack that "we don't support that field. It's ignored by cc.".
I'll close this as a won't-fix - our team is small and our backlog is long enough already.
