### ISSUE TITLE
`cf delete app -r` deletes shared routes

### ISSUE THREAD

**Issue by glyn** [cloudfoundry/cli#751]
The `-r` option deletes routes even if other applications are using them.
### Steps to reproduce

First issue:

```
cf push myapp ...
cf push myapp2 ...
cf map-route myapp cfapps.io --hostname myhost
cf map-route myapp2 cfapps.io --hostname myhost
```

At this point `cf routes` shows:

```
space              host                                   domain      path        apps
development   myapp                               cfapps.io                  myapp
development   myapp2                             cfapps.io                  myapp2
development   myhost                              cfapps.io                  myapp,myapp2
```

Now issue `cf delete`:

```
cf delete myapp2 -f -r
```

`cf routes` then shows:

```
space              host                                 domain      path        apps
development   myapp                             cfapps.io                  myapp
```

The route `myhost.cfapps.io` has been removed from `myapp`, which violates the principle of least surprise.

**Comment by krishicks** [comment]
Hi @glyn,

I think this is something @shalako and @dkoper should look at. CLI just hits the endpoint; if a shared route should not be deleted we should be getting an error from the API.

**Comment by shalako** [comment]
@dieucao I believe the convention in CC is that recursively deleting an app deletes the relationship with other resources, but not those other resources. The service binding is deleted, but not the service instance. Similarly, I would expect the mapping to the route to be deleted, but not the route (even if the app being deleted is the only one mapped to the route). To delete both the app and the route (or the service instance), you'd have to recursively delete the parent object (the space).

**Comment by glyn** [comment]
@krishicks thanks for directing this bug to the correct parties. I raised it against the CLI because it was presumably a CLI design decision to support `-r`.

**Comment by krishicks** [comment]
@glyn No worries; you did the right thing.

**Comment by glyn** [comment]
This behaviour also resulted in a bug in Spring Cloud Services. A "worker" application (part of the SCS service broker implementation) is upgraded by renaming the application, pushing the upgraded worker application, and then deleting the renamed application using `cf delete ... -f -r`. Unfortunately this destroys the route to the upgraded application.

A workaround is to omit the `-r`, but this example shows the ease with which this issue can cause problems.

**Comment by XenoPhex** [comment]
Hi @glyn thanks for raising this issue. Since the issue you've described is CC-related, and not CLI-related, we are closing this issue. Feel free to reach out to the CAPI team if you believe the recursive behavior should change.

**Comment by zrob** [comment]
i'm not following how this is a CC issue.  the cli explicitly calls DELETE on the route resource.

**Comment by shalako** [comment]
@zrob The use case was deleting the app with recursive option. I would expect any relationships with other resources to be deleted (e.g. `/v2/apps/:guid/routes/:guid`), but would you expect the route to be deleted also? That seems surprising, considering that other apps may be using the route.

**Comment by zrob** [comment]
i believe the behavior you're describing is what already happens at the api level

for example, if you send DELETE /v2/apps/:guid?recursive=true, then the route WILL EXIST afterwards.

it is actually the cli that is explicitly finding routes for the app and calling DELETE /v2/routes/:guid

**Comment by shalako** [comment]
Makes sense.

**Comment by giner** [comment]
@nebhale does closing mean there is a fix for the issue?

**Comment by nebhale** [comment]
Sorry!  Wrong window!

**Comment by abbyachau** [comment]
Hi @glyn and all, thanks for commenting on this issue. On v7 beta cf CLI, we've changed the behavior when using `cf delete app -r`, the command no longer deletes routes if the route is bound to another app. Please see [here](https://www.pivotaltracker.com/story/show/160467192) for more information, and do not hesitate to get in touch if you have any questions. Thanks.

**Comment by giner** [comment]
Hi @abbyachau,

```
Really delete the app dora?> y
App 'dora' was not deleted because route 'dodo.arsicault.cli.fun' is mapped to more than one app. 
FAILED
```

Why should it fail if the route is mapped to a different app? What it warned "the route is not deleted as it is also mapped to: ..." but didn't stop from deleting an app?

**Comment by abbyachau** [comment]
@giner thanks for the feedback. In the case that the route was not deleted and the app was, it might be confusing to a user if the command exited with `0` and an `ok`. Failing the command and providing a TIP to tell users to `Run 'cf delete app' to delete the app and 'cf delete-route' to delete the route` might take an extra step but it adds more guard rails to this command. Please let me know if you have any additional thoughts. Thanks.

**Comment by giner** [comment]
I don't see why it should fail. Also this breaks a common blue-green scenario:
1. domain.com is mapped to app1
2. User pushes app2 with domain.com
3. User stops app1
4. User deletes app1

One may say "don't use `-r` when deleting an app" but `-r` helps to keep the environment clean by deleting routes which only belong to the app we are deleting.

**Comment by giner** [comment]
cf delete-route should be unnecessary:
1. Rename the original app (`cf rename app app-venerable`)
2. Push a new app using the same manifest (`cf push`)
3. Clean up if #2 is successful (`cf delete app-venerable -r`)

I'm wondering about the reasoning behind trying to delete routes shared by other apps, when would anybody want this?

**Comment by giner** [comment]
@abbyachau, I'm not sure what you mean by deleting mappings as they only exist if the app exists. Having `-r` deleting only non-shared routes would just be a convenient way to keep the space clean through time.

**Comment by adobley** [comment]
From my understanding of this, `cf delete abby -r` should delete the app & the mapped routes. I would expect that the result would be to remove the route, as long as it isn't shared or being used by another app.

**Comment by heyjcollins** [comment]
With the GA of the v7 CLI, we're no longer actively developing against the v6 line.  With an interest the overall hygiene of the CLI project we're closing this  issue.
If this issue is still occurring in v7 please feel free to comment and re-open. Thank you!

**Comment by glyn** [comment]
I tried to reproduce this with cf7 version 7.0.1+fb3f929c2.2020-06-24 and was pleased by the new behaviour:
```
cf7 delete myapp2 -f -r
Deleting app myapp2 in org glyn / space glyn as admin...
App 'myapp2' was not deleted because route 'myhost.apps.plum.springapps.io' is mapped to more than one app.
FAILED

TIP: Run 'cf delete myapp2' to delete the app and 'cf delete-route' to delete the route.
```
So problem solved!
