### ISSUE TITLE
New command: what-was-that-trace

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cli#753]
Sometimes when I get into a strange situation when using the CLI, I really wish I _had_ seen the trace for my previous command, but it's too late (e.g. if the setup was complicated, or it was a one-off error) to reproduce.

I would like to be able to do something like this:

```
cf set-something-strange # This does something weird, and I wish I had set CF_TRACE=true
cf what-was-that-trace # Give me the trace from the "set-something-strange" command
```

Thanks!

**Comment by dkoper** [comment]
Hi @wendorf,

Currently we can do:
```
$ cf config --trace /tmp/my-cf-trace.txt
$ cf set-something-strange
<strange thing happening>
$ tail /tmp/my-cf-trace.txt
```

What's missing from the trace is an easy way of determining which API request(s) were made for what command. If we could introduce a marker into the trace log, we could tail the trace of only that command.

Would that address your situation?

Of course this depends on you configuring the trace to be output to a file, with its associated maintenance (deleting it periodically before your filesystem fills up).

Also, do you really want to use a cf command to look at the trace? I tend to end up copying it to a file and open it in a big text editor window with regex search capabilities.

**Comment by dkoper** [comment]
PS: Great idea!

**Comment by wendorf** [comment]
Hi @dkoper ,

Thanks for your response! If the configured trace file had markers that were easy to spot, that would go a decent way toward fixing my situation. Unfortunately, a situation I commonly find myself it is being called to other peoples' computers whereupon I'm shown a failed command. At that point, it's too late to see what happened at the trace level, so to have the logs already available as an "ace up my sleeve" would be really nice.

**Comment by dkoper** [comment]
I know as a PM I should be concerned with the What, not with the How, but without saving the trace to disk for every command without the user's knowledge/consent, I'm not sure how to satisfy the use case fully. Do you have any suggestions?

**Comment by wendorf** [comment]
I agree that you'd have to have something persist (a single file in the
temp directory that is replaced after every command, perhaps?). Are there
concerns in using the temp directory to save recent trace information? I
know the CLI already stores a small amount of configuration on the file
system, such as current org/space targets.

**Comment by dkoper** [comment]
The trace may contain sensitive information. Run for example `cf uups alarm-service -p "{\"username\":\"admin\",\"master-password\":\"pa55woRD\"}"` with trace on: master password in clear-text in a file in /tmp readable by all.
Run that as the last command on the day... maybe the next day your work station is lent out for an interview...
It is very difficult to mask all fields that could contain sensitive information. It's very easy to miss something, especially over time as new APIs and fields are added.

The CLI stores a file locally that contains a token with an expiry date and a few other fields, but no arbitrary user provided data, which makes it easier to control.

**Comment by dkoper** [comment]
Still I find it a great idea and have had several occasions since you submitted it that I wish we had that!

**Comment by wendorf** [comment]
~/.cf/ already has enough information to gain credentials. Could the logs
live there? They could be deleted on `cf logout`.

**Comment by dkoper** [comment]
~/.cf/config.json only have tokens that expire, after which they are useless. Logs could have credentials that don't expire. And, does anyone ever use `cf logout`?
I wonder if we could encrypt the log in a way that after the token expired, the file can no longer be decrypted?

**Comment by dkoper** [comment]
Closing as I'm out of ideas. Feel free to reopen, anyone, who wants to help brainstorm!
