### ISSUE TITLE
cf ssh containers do not have app's environment

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cli#754]
Not sure if this bug is in CLI or Diego.

I ran `cf ssh` against a Ruby application and found that inside the container I did not have the correct ruby selected, nor were any of the buildpack tools available (`bundle`).

The workaround - or rather the piece that `cf ssh` is not doing yet - is to manually run the `~/app/.profile.d/*.sh` script (but with `$HOME` set to the app folder).

```bash
cd app
HOME=$(pwd) source ~/app/.profile.d/*.sh  
```

Documented https://blog.starkandwayne.com/2016/02/07/run-one-off-tasks-and-database-migrations/

I think this is a bug - I think a user expects that they can get straight to work inside a container, rather than manually sourcing profile scripts.

**Comment by ematpl** [comment]
@drnic, have you seen my replies to your thread on cf-dev? https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/ROEK63S34PSJPM2WXPSP5G7XKF7S3Z7A/

Thanks,
Eric

**Comment by drnic** [comment]
Crap, no, never saw that reply. Thanks for replying and re-replying!

**Comment by drnic** [comment]
Aside: I've updated blog post with your alternate suggestion; and emailed Linux foundation to find out why I didn't get either of your cf-dev replies.

**Comment by dkoper** [comment]
Diego team is on it. Feel free to re-open if it turns out the CLI team needs to take action.

**Comment by ematpl** [comment]
Thanks for including my suggestion in your post, @drnic, and for contacting the Foundation about continued mail delivery issues with the CF mailing lists!

Best,
Eric
