### ISSUE TITLE
check-route fails to recognize route

### ISSUE THREAD

**Issue by stevewallecs** [cloudfoundry/cli#757]
Hello,
When using the check-route command it appears it is not detecting an existing route. (API version: 2.43.0)

$ ./cf -v
./cf version 6.15.0+fa1bfe2-2016-01-13
$ ./cf r
Getting routes as temp-admin ...

space                                                           host                                  domain                             path   apps   
sips-validator-converter-functional-testing   sips-validator-converter   ft.apps.cfdev1.ux.dg.local          sips-validator-converter-1-0-341   

$ ./cf check-route sips-validator-converter ft.apps.cfdev1.ux.dg.local
Checking for route...
OK
Route sips-validator-converter.ft.apps.cfdev1.ux.dg.local does exist

**Comment by krishicks** [comment]
Hi @stevewallecs,

When you say it fails to detect the route, what do you mean? The above log, unless I'm reading it incorrectly, shows the route does exist.

**Comment by stevewallecs** [comment]
Sorry! I was looking at it wrong.
