### ISSUE TITLE
can not push my GO app with version 6.14.1 and 6.15.0

### ISSUE THREAD

**Issue by boyang9527** [cloudfoundry/cli#759]
I can always push my Go app using cf v6.14.0 and previous versions. From 6.14.1, I failed with "No app files found" message.  Is there anything changed?

**Comment by dkoper** [comment]
You can refer to the change logs to see what changed: https://github.com/cloudfoundry/cli/releases
If you can provide more details (see https://github.com/cloudfoundry/cli#filing-bugs), we could investigate.

**Comment by boyang9527** [comment]
I got the reason.  I put " */.*"  in .cfignore to ignore the hidden files,  looks like it matches  xxx/..  and ignored all the files.  While why it succeeds for previous versions?

**Comment by dkoper** [comment]
Hi @boyang9527,

.cfignore is modeled after .gitignore, for which "/.*" ignores hidden files.
Not sure what to expect for "/.": ignore the current directory?
The change in behaviour may have occurred as a side-effect of the fixes for #687 or #564.

Regards,
Dies Koper
CF CLI PM

**Comment by boyang9527** [comment]
sorry, my typo. 
I put  "**/.*"  in .gitignore  to ignore the hidden files in all directories, and I failed with "No app files found". 
After I remove this line, I can push successfully with  6.14.1 and 6.15.0

**Comment by dkoper** [comment]
I think to ignore the hidden files in all directories you should use "**/.*" in .cfignore. If that stopped working, we should investigate.

**Comment by dkoper** [comment]
Closing. Feel free to reopen or submit a new option if "*/." does not work.
