### ISSUE TITLE
Route Service

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry/cli#760]
Hi,

I know is still on going but I think we should not be able to bind a route service like we bind normal service (bind-service).

**Comment by dkoper** [comment]
Care to elaborate?

**Comment by shinji62** [comment]
yes, 
`cf cups fowarding -r https://myforwarding.service.route` is normal.
`cf bind-route-service local.micropcf.io fowarding --hostname dump-request `  make sense.
`cf bind-service myapp fowarding` do not make sense but maybe I am missing something.

**Comment by dkoper** [comment]
Your issue title is Route Service. In the upcoming cf CLI release you will be able to use `cf bind-route-service local.micropcf.io fowarding --hostname dump-request`, which you agree makes sense.
You can't use `cf bind-service` to map routing services, they are to map application services (DBs, etc.).

Isn't that what you expected?

**Comment by shinji62** [comment]
Hi, 
Strange I could bind using bind-service even if there no real effect.
What about getting an error if we try to do so ?


Thanks
Envoyé de mon iPhone

**Comment by dkoper** [comment]
Just to confirm, you mean you created a route service (using `cf create-user-provided-service` with `-r` option) and want it to fail when bound to an app using `cf bind-service`?

**Comment by shinji62** [comment]
Sorry I am not clear, the fact is I was expected to get an error when I use bind-service or a warning it just bind as normal service. 


Envoyé de mon iPhone

**Comment by shalako** [comment]
@dkoper @dieucao There are use cases for being able to bind a service instance to BOTH a route and an app. However, @shinji62 raises a good point in that we could allow brokers to declare that the service does not support credentials, enabling CC to reject requests from commands `bind-service` or `create-service-key`.

**Comment by dkoper** [comment]
Closing, as it sounds like the CLI should keep doing what it's doing. Feel free to continue the discussion on the CC issue tracker or CF Dev mailing list about CC rejecting (CLI) requests.
