### ISSUE TITLE
cf create-route fails due to invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by neckert** [cloudfoundry/cli#766]
Tell us that you ran this command:

	cf create-route dev stage1.eu-gb.bluemix.net -n serviceprovider-jenkins2

using this version of the CLI:

	6.9.0-620f841

and that this error occurred:

	runtime error: invalid memory address or nil pointer dereference

and this stack trace:

	goroutine 1 [running]:
main.generateBacktrace(0xc21000a000, 0x6)
	/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:174 +0xa9
main.handlePanics(0x7fc2a48425d8, 0xc21006a4e0)
	/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:158 +0x123
runtime.panic(0x930f00, 0x11bff08)
	/var/vcap/packages/golang-1.2/src/pkg/runtime/panic.c:248 +0x106
github.com/cloudfoundry/cli/cf/net.Gateway.performRequestForResponseBytes(0x7fc2a484bb28, 0xc210097990, 0xaf8390, 0x1, 0x12a05f200, ...)
	/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.go:249 +0x245
github.com/cloudfoundry/cli/cf/net.Gateway.PerformRequestForJSONResponse(0x7fc2a484bb28, 0xc210097990, 0xaf8390, 0x1, 0x12a05f200, ...)
	/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/net/gateway.

**Comment by dkoper** [comment]
Hi @neckert ,

Your cf CLI version is over a year old. This bug has likely been fixed. Can you try on our latest release?
https://github.com/cloudfoundry/cli/releases

Cheers,
Dies Koper
CF CLI PM

**Comment by neckert** [comment]
This is the first time the problem happened and it didn't happen again since that. Thus, using the latest version of the CF CLI, it will be hard to tell whether the problem is really solved. Anyhow, if the information provided is not sufficient to look into the problem, I'm fine to close it.

**Comment by dkoper** [comment]
Thanks. Feel free to re-open if you run into the exact error trace with the new cf CLI version.

Regards,
Dies Koper
CF CLI PM

**Comment by lpinto-git** [comment]
I am seeing this error `runtime error: invalid memory address or nil pointer dereference` when I'm trying to login to bluemix using `strace ./cf ic login`:

trace:

`futex(0xc82002d508, FUTEX_WAKE, 1)      = 1
stat("/home/lpinto/.cf", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/home/lpinto/.cf/config.json", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0600, st_size=2719, ...}) = 0
read(3, "{\n  \"ConfigVersion\": 3,\n  \"Targe"..., 3231) = 2719
read(3, "", 512)                        = 0
close(3)                                = 0
stat("/home/lpinto/.cf/config.json", {st_mode=S_IFREG|0600, st_size=2719, ...}) = 0
stat("/home/lpinto/.cf", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/home/lpinto/.cf/config.json", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0600, st_size=2719, ...}) = 0
read(3, "{\n  \"ConfigVersion\": 3,\n  \"Targe"..., 3231) = 2719
read(3, "", 512)                        = 0
close(3)                                = 0
stat("/home/lpinto/.cf/config.json", {st_mode=S_IFREG|0600, st_size=2719, ...}) = 0
stat("/home/lpinto/.cf", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/home/lpinto/.cf/config.json", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0600, st_size=2719, ...}) = 0
read(3, "{\n  \"ConfigVersion\": 3,\n  \"Targe"..., 3231) = 2719
read(3, "", 512)                        = 0
close(3)                                = 0
mmap(0xc820500000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc820500000
mmap(0xc81ffd0000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc81ffd0000
futex(0xc82002d508, FUTEX_WAKE, 1)      = 1
mmap(NULL, 1439992, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7feba71b4000
mmap(0xc820600000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc820600000
mmap(0xc81ffc8000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc81ffc8000
mmap(0xc820700000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc820700000
mmap(0xc81ffc0000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc81ffc0000
mmap(0xc820800000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc820800000
mmap(0xc81ffb8000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc81ffb8000
mmap(0xc000002000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc000002000
mmap(0xc820900000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc820900000
mmap(0xc81ffb0000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc81ffb0000
stat("/home/lpinto/.cf/plugins", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/home/lpinto/.cf/plugins/config.json", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0600, st_size=3242, ...}) = 0
read(3, "{\n  \"Plugins\": {\n    \"IBM-Contai"..., 3754) = 3242
read(3, "", 512)                        = 0
close(3)                                = 0
socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 3
setsockopt(3, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
setsockopt(3, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
bind(3, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
listen(3, 128)                          = 0
epoll_create1(EPOLL_CLOEXEC)            = 4
epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=2805130424, u64=140650099172536}}) = 0
getsockname(3, {sa_family=AF_INET, sin_port=htons(60053), sin_addr=inet_addr("127.0.0.1")}, [16]) = 0
openat(AT_FDCWD, "/dev/null", O_WRONLY|O_CLOEXEC) = 5
pipe2([6, 7], O_CLOEXEC)                = 0
getpid()                                = 8624
clone(child_stack=0, flags=SIGCHLD)     = 8628
close(7)                                = 0
read(6, "", 8)                          = 0
close(6)                                = 0
close(5)                                = 0
wait4(8628, Deleting the old configuration file...
Retrieving client certificates for IBM Containers...
runtime error: invalid memory address or nil pointer dereference
[{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, {ru_utime={0, 16000}, ru_stime={0, 4000}, ...}) = 8628
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=8628, si_status=1, si_utime=0, si_stime=0} ---
rt_sigreturn()                          = 8628
futex(0x1335450, FUTEX_WAKE, 1)         = 1
exit_group(1)                           = ?
`
