### ISSUE TITLE
cf push fails with "The query parameter is invalid: path"

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry/cli#768]
Hi,
as my other comment on an existing ticket was ignored, I open up a new one. The content is the same as in: https://github.com/cloudfoundry/cli/issues/744

If you need more information, please let me know.

**Comment by jhiemer** [comment]
Going back to an earlier version, for example through:

```
brew unlink cf-cli
brew switch cloudfoundry-cli 6.12.4
```

helps me to deploy again.

**Comment by dkoper** [comment]
Thanks @jhiemer, I missed your comment on the other issue - thanks for opening a new one.
The team will take a look.

**Comment by jhiemer** [comment]
@dkoper thank you very much. :-)

**Comment by dkoper** [comment]
This has been implemented in cf CLI v6.16.0.
https://github.com/cloudfoundry/cli#downloads

Regards,
Dies Koper
CF CLI PM
