### ISSUE TITLE
Consumed memory info is not comming proper

### ISSUE THREAD

**Issue by sanjay19834U** [cloudfoundry/cli#769]
Hi Team,

When i am running  cf app <app name > command on cf cli its giving following information about app   

   state    |            since            |                       cpu      |     memory          |       disk    |        detail
  running  | 2016-02-17 09:01:34 AM  |          100.0%   |   858.1M of 1G   |     0 of 1G|

in this above result ,its showing memory consumed is 858.1 m out of 1G.
But when i calculating consumed memory by JAVA Runtime class method . its showing total free heap memory is 625MB. 
Our memory allocation ratios are default on cloud foundry.
75% for heap memory
10% for metasapce
10% for native resources
5% for  stack memory

I am not able to understand ,why approx 600 MB memory gap is coming .

what exactly means of 858.1M of 1G ?

**Comment by dkoper** [comment]
Hi @sanjay19834U,

The cf CLI just returns the stats the Cloud Controller returns to us: 858.1M out of the maximum of 1GB configured for your container.
@dieucao (CAPI team) or @ematpl (Diego team) should be in a better position to explain how the value of 858.1M is obtained.
How that relates to the JVM is a question @nebhale (Java Buildpack team) may have a better understanding of.

**Comment by nebhale** [comment]
@sanjay19834U The difference you're seeing here is related to the fact that once the JVM requests memory from the operating system, it (effectively) never gives it back.  So, what you're seeing is that at some point the JVM requested up to 858.1M of memory for objects and then GC'd itself back down to some smaller memory usage.  While internally the JVM is no longer using that memory, it never gives it back to the operating system, preferring instead to keep a hold of it for the next time the memory balloons before a GC.  From the perspective of the container, the JVM process still occupies that larger memory space, while internally, the JVM reports that your application can grow into that space.

**Comment by dkoper** [comment]
Closing. Feel free to ask more questions on the CF Dev mailing list or the respective components' issue trackers!
