### ISSUE TITLE
cf create-app-manifest should capture disk quota

### ISSUE THREAD

**Issue by glyn** [cloudfoundry/cli#771]
If an application is pushed specifying a disk quota value via the `-k` switch, `cf create-app-manifest` does not record this value in the generated manifest. So the manifest cannot be used to redeploy the application with the same settings unless the disk quota is remembered and specified as a separate parameter.

The manifest does support [disk_quota](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#disk-quota) however.

**Comment by krishicks** [comment]
Good catch. Somehow gitbot didn't add a comment here, so I'll link the story: https://www.pivotaltracker.com/story/show/114089069

**Comment by dkoper** [comment]
This has been implemented in cf CLI v6.16.0.
https://github.com/cloudfoundry/cli#downloads

Regards,
Dies Koper
CF CLI PM

**Comment by glyn** [comment]
Thanks!
