### ISSUE TITLE
cf create-app-manifest should capture stack

### ISSUE THREAD

**Issue by glyn** [cloudfoundry/cli#772]
If an application is pushed specifying a stack via the `-s` switch, `cf create-app-manifest` does not record this value in the generated manifest. So the manifest cannot be used to redeploy the application with the same settings unless the stack is remembered and specified as a separate parameter.

The manifest does support [stack](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#stack) however.

**Comment by dkoper** [comment]
Thanks! I understand use of stacks is becoming more wide-spread with Windows having its own and other custom ones.

**Comment by dkoper** [comment]
This has been implemented in cf CLI v6.16.0.
https://github.com/cloudfoundry/cli#downloads

Regards,
Dies Koper
CF CLI PM

**Comment by glyn** [comment]
Thanks!
