### ISSUE TITLE
CLI version 6.16 ssh-code command returns oauth-token instead of ssh code

### ISSUE THREAD

**Issue by selzoc** [cloudfoundry/cli#780]
Expected behavior:
```
> cf ssh-code
vVVMWl
```

Observed behavior:
```
> cf ssh-code
bearer [REDACTED]
```

This behavior appears to be related to this refactoring: https://github.com/cloudfoundry/cli/commit/eaae429bdbec277d4aa0edbadb03b8301d1c91af

It looks like ssh-code command returns the direct result of the `authRepo.RefreshAuthToken()` call instead of doing further processing to exchange that for a one-time ssh code.

I have verified that this works as expected with version 6.15.

### Command

cf ssh-code

### CLI Version

6.16.0+ee4d916-2016-02-24

### Error

Returns oauth-token instead of ssh code

### CC API Version

v228

### CF Trace

For bugs related to HTTP requests, please run the command with env var `CF_TRACE=true`

### Platform Details

Mac OS X 10.11.3

### Shell

Terminal (bash)

**Comment by krishicks** [comment]
Yikes.

Thanks for the catch! We'll be releasing a patch release soon.

**Comment by dkoper** [comment]
This has been fixed in cf CLI v6.16.1.
https://github.com/cloudfoundry/cli#downloads

Thanks again!
Dies Koper
CF CLI PM
