### ISSUE TITLE
Create command org-remove-user

### ISSUE THREAD

**Issue by goehringc** [cloudfoundry/cli#781]
If a user has had no prior role assignments for a org or a space, that user has no visibility that the org exists nor any other attributes about the org through the `cf` cli.  Once a user has been assigned a role for an org or one of it's spaces, and is later removed from all associated roles with `cf unset-org-role` or `cf unset-space-role` respectively, the user still has membership in the org and can list attributes like org members.

Given that there is no way to generically associate a user with an org exposed through the cli, ideally removing all roles related to an org would also implicitly remove the user's membership in the org.  At a minimum recommend adding a cli command such that a user with the admin role or associated OrgManager role would be able to remove a user from an org.

**Comment by krishicks** [comment]
Hi @goehringc,

I think we need @dieucao, the CAPI PM, to weigh in on this.

**Comment by dkoper** [comment]
Currently, the cf CLI (and I believe the documentation) assumes a user always has a role within an org or space they are a member of, while the CC API allows members without roles.
I need to check with @SocalNick what a user without a role can do less than one with an Auditor role: If nothing, I'd favor the solution of implicitly removing the user's membership if no roles are left.

**Comment by dcarley** [comment]
We found that this was unexpected.

For reference, the steps to remove a user from an org are:

1. List the spaces belonging to the org with `cf spaces`
1. List the users and roles for each space with `cf space-users`
1. Remove the user for each combination of space and role with `cf unset-space-role`
1. Find the org GUID with `cf org --guid`
1. Use the API to remove the user from the org:

  ```
cf curl -X DELETE '/v2/organizations/<ORG_GUID>/users' -d '{"username": "<USERNAME>"}'
```

**Comment by SocalNick** [comment]
I've created a charter to determine if we can eliminate the Org / User relationship: https://www.pivotaltracker.com/story/show/127479261

**Comment by mogul** [comment]
Thanks for pursuing this... It's very confusing that the org-level `User` role is not at all documented in the CF docs or CLI.  Moreover, a SpaceManager can't set a space-level role for anyone not already associated with the Org, while an admin can! The implicit behavior is frustrating. 

If it needs to stay, I'd rather see it be explicitly documented, eg "Users must at minimum have the `User` role set at the Org-level before they can be granted Space-level roles. People with the `User` role can list Org members." Then include it in the CF docs and *don't* make admins add it implicitly when granting space-level roles.

**Comment by brittag** [comment]
I'm on the same team as @mogul, and I've seen our platform users confused about this as well. Here's an example fictionalized user story that may help explain why it's useful to document this behavior (even if it's not ideal behavior):

> As an Org Manager for a system in a regulated environment, I need to ensure my system complies with security requirements including strict access control.

> I use the [Cloud Foundry docs page about roles and permissions](https://docs.cloudfoundry.org/concepts/roles.html) and ["Users and Roles" commands](https://docs.cloudfoundry.org/cf-cli/getting-started.html#user-roles) to guide me in assigning and removing roles correctly, including `cf set-org-role`, `cf unset-org-role`, `cf set-space-role`, and `cf unset-space-role`.

> During my periodic audit of access to my org, I use the `cf org-users` and `cf space-users` commands to review roles and ensure no former team members have any access.

> I notice the `cf org-users ORG -a` flag in the [CF CLI docs](http://cli.cloudfoundry.org/en-US/cf/org-users.html), and I see several former team members in the list. I know I removed their space and org roles before, but I check `cf org-users` and `cf space-users` again to make sure I didn't make a mistake, and I don't see them there.

> So I can't figure out why these people are still listed, what they have access to, or how to remove them. I ask for help from the platform operators, since this may indicate a security problem for my org.

The alternate user story with more documentation would be:

> As an Org Manager for a system in a regulated environment, I need to ensure my system complies with security requirements including strict access control.

> I use the [Cloud Foundry docs page about roles and permissions](https://docs.cloudfoundry.org/concepts/roles.html) and ["Users and Roles" commands](https://docs.cloudfoundry.org/cf-cli/getting-started.html#user-roles) to guide me in assigning and removing roles correctly, including `cf set-org-role`, `cf unset-org-role`, `cf set-space-role`, and `cf unset-space-role`. When I need to completely remove a person who has left the team, I use an API command to remove their user status as well (the first time it took me a little extra time to use the API instead of the CF CLI, but that's ok, I know how to use an API).

> During my periodic audit of access to my org, I use the `cf org-users`, `cf org-users ORG -a`, and `cf space-users` commands to review roles and ensure no former team members have any access.

**Comment by XenoPhex** [comment]
Hi @goehringc thanks for creating this issue. This sounds more like a CAPI-related issue, and not a CLI issue - closing this issue but please follow the CAPI story mentioned above for progress. Alternatively, try the [cf-mgmt tool](pivotalservices/cf-mgmt).
