### ISSUE TITLE
A bug in cf

### ISSUE THREAD

**Issue by nicolelovecoding** [cloudfoundry/cli#782]
Command
		cf push --no-route devops-etl

		CLI Version
		6.16.1+924508c

		Error
		interface conversion: interface is bool, not string

		Stack Trace
			goroutine 1 [running]:
	main.generateBacktrace(0x0, 0x0)
		/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/main/main.go:141 +0xb4
	main.handlePanics(0x88211c58b8, 0x821435be0)
		/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/main/main.go:125 +0x17c
	panic(0x810aa0, 0x8210dc040)
		/usr/local/go/src/runtime/panic.go:426 +0x4e9
	github.com/cloudfoundry/cli/cf/manifest.envVarOrEmptyMap.func1(0x6c4000, 0x820fb85db, 0x6c5700, 0x8212e0c80)
		/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/manifest/manifest.go:417 +0x5a
	github.com/cloudfoundry/cli/generic.Each(0x8820fa6038, 0x820f7c050, 0x8212586c0)
		/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/generic/map.go:136 +0x115
	github.com/cloudfoundry/cli/cf/manifest.envVarOrEmptyMap(0x8820fa6038, 0x820f7c030, 0x821258a98, 0x8c8ac0)
		/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/manifest/manifest.go:418 +0x969
	github.com/cloudfoundry/cli/cf/manifest.envVarOrEmptyMap(0x8820fa6038, 0x820f7c030, 0x821258a98, 0x8)
		/tmp/

		Your Platform Details
		e.g. Mac OS X 10.11, Windows 8.1 64-bit, Ubuntu 14.04.3 64-bit

		Shell
		e.g. Terminal, iTerm, Powershell, Cygwin, gnome-terminal, terminator

**Comment by dkoper** [comment]
Hi @nicolelovecoding 

Something seemed to have happened while parsing your manifest file. Can you attach your manifest file so we can investigate?

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Closing. Feel free to reopen when you can provide us more information.
