### ISSUE TITLE
cpu utilizaion and free disk memory means

### ISSUE THREAD

**Issue by sanjay19834U** [cloudfoundry/cli#784]
Hi Team,
When i am running "cf app <APPNAME>" command on cf cli . Its giving following information about app.

state | since | cpu | memory | disk | detail
running | 2016-02-17 09:01:34 AM | 100.0% | 858.1M of 1G | 0 of 1G|

in this above result ,its showing cpu 100% and Disk 0 of 1G.
I have two questions 
1.What exactly 100% cpu means ?  "As per my understanding, i think its cpu used of DAE(container) which is dedicated to my APP  "

2. why 0 of1G  is coming even after deploy my app?

**Comment by fraenkel** [comment]
1. Yes, to get a better understanding see https://docs.cloudfoundry.org/concepts/architecture/warden.html#cpu
2. If disk quotas are disabled, there is no disk usage reported.

**Comment by dkoper** [comment]
Closing. Feel free to open another issue on the relevant tracker (DEA, Diego or here) or on the CF Dev mailing list for follow-up questions.
