### ISSUE TITLE
Unable to connect to CF deployment using cf api

### ISSUE THREAD

**Issue by rahulkj** [cloudfoundry/cli#786]
### Command

cf api --skip-ssl-validation api.<TLD>

### CLI Version

cf version 6.16.1+924508c-2016-02-26

### Error

Error performing request: Get http://api.<TLD>/v2/info: dial tcp: lookup api.sys.homelab.io on <GATEWAY>:53: no such host
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

### CC API Version
v2

### Platform Details

Mac OS X 10.11

### Shell

Terminal

This same command works with `cf version 6.14.1+dc6adf6-2015-12-22`
My *nameserver* is defined in the `/etc/resolver/homelab.io`, and using the older CLI, the domain used to resolve fine, but with the new release I get the error mentioned above.

**Comment by dkoper** [comment]
Hi @rahulkj 

Can you confirm whether you get the same issue with cf CLI release 6.15.0?
Your issue seems related to #763. Can you try the work-around mentioned in that issue and report back if that makes a difference?

Cheers,
Dies Koper
CF CLI PM

**Comment by rahulkj** [comment]
Hi @dkoper 

Oh yes, the issue we're facing is the same. But without setting `GODEBUG=netdns=cgo` for v6.15.0 it works fine. So v6.16.x doesn't work with this flag.

**Comment by rahulkj** [comment]
Closing as this is duplicate and commenting on #763
