### ISSUE TITLE
New command: Get-JAR

### ISSUE THREAD

**Issue by ytupman** [cloudfoundry/cli#790]
I'm working on a few spaces at the same time, and the current jars at are on a specific space sometimes get mixed up.

At the moment there is a comfortable way to get the current manifests

I would like to be able to do something like this:

`cf get-jar appname -s spacename
`

Thanks!!

**Comment by dkoper** [comment]
Hi @ytupman 

Can you provide more detail? I have absolutely no idea what you're asking for. jars of what?
Is this specific to Java applications? (and you know the cf CLI is generic to cater for many programming languages?)

Thanks,
Dies Koper
CF CLI PM

**Comment by ytupman** [comment]
Hi @dkoper 

Sure, i meant to extract the java applications that are upload to the CF.
Hope you understood me now. :)

**Comment by dkoper** [comment]
You can use the `cf files` command to download individual files from your application. Or `cf ssh` if your app is on Diego.
There is also a CC API to download application bits (http://apidocs.cloudfoundry.org/231/apps/downloads_the_bits_for_an_app.html) - you can use `cf app APPNAME --guid` to retrieve your app's guid and pass it to `cf curl` to start the download.
Does that help?
