### ISSUE TITLE
Mac users getting "Invalid SSL Cert" error in version 6.16

### ISSUE THREAD

**Issue by jmprice** [cloudfoundry/cli#791]
We have had a couple of users report that they get an "Invalid SSL Cert" error when using v6.16 of the CLI.  Version 6.15 works without error.

Our certificates are issued by our own internal PKI and the cert chains are installed on the client machines.

### Command
± % cf login -a https://api.our.platform.com/ -u some.guy@person.com                                                            !10036
API endpoint: https://api.our.platform.com/
FAILED
Invalid SSL Cert for api.our.platform.com
TIP: Use 'cf login --skip-ssl-validation' to continue with an insecure API endpoint

### CLI Version
6.16.1+924508c

### CC API Version
2.43.0

### Platform Details
e.g. Mac OS X

### Shell
iTerm (zsh)

-- Jon Price
Intel Corporation

**Comment by jmprice** [comment]
I suppose this could be the issue:  https://github.com/golang/go/issues/14514

**Comment by cbguder** [comment]
@jmprice We have built a new binary that we think might fix this issue. Please give it a try and let us know if it fixes the issue you're seeing.

Installer:https://s3.amazonaws.com/go-cli/releases/v6.16.1-2016-03-17/cf-cli-installer_6.16.1_osx.pkg

Binary: https://s3.amazonaws.com/go-cli/releases/v6.16.1-2016-03-17/cf-cli_6.16.1_osx.tgz

**Comment by jmprice** [comment]
@cbguder 
I apologize for the delay, but I finally got one of our developers to test this out and it seems to have fixed the issue.  Thank you very much! :)

**Comment by dkoper** [comment]
Hi @jmprice 

Thanks for the confirmation. We have ported the fix into our edge binaries. Any chance you could try out our edge binary as well and confirm the issue is addressed?
https://cli.run.pivotal.io/edge?arch=macosx64&source=github

Cheers,
Dies Koper
CF CLI PM

**Comment by jmprice** [comment]
@dkoper 

One of our developers with a Mac just tried it out and reports that it works great.  :)
