### ISSUE TITLE
Ampersand char within cf service-key return value unexpectedly displaying as \u0026 

### ISSUE THREAD

**Issue by joshisa** [cloudfoundry/cli#794]
### Command

`cf service-key <objectstorageinstance> <service-keys-credential-name>`
### CLI Version

6.16.1+924508c-2016-02-26
### Error

Command returns JSON value similar to:

```
Getting key <service-keys-credential-name> for service instance <objectstorageinstance> as joshisa@us.ibm.com...

{
 "auth_url": "https://identity.open.softlayer.com",
 "domainId": "some_hex_value",
 "domainName": "853255",
 "password": "Xj\u00262ir1TKoW-]Jf\u0026",
 "project": "object_storage_more_hex_chars",
 "projectId": "hex_value_palooza",
 "region": "dallas",
 "userId": "one_more_hex_value",
 "username": "Admin_hex_value_for_the_road"
}
```

**The password field incorrectly displays the unicode representation of the Ampersand char as \u0026**
If this returned value is used literally, the python openstack swift client authentication fails.  The correct password string should be represented as "Xj&2ir1TKoW-]Jf&"
### Platform Details

Mac OS X 10.11.3
### Shell

iTerm

**Comment by dkoper** [comment]
Hi @joshisa 

What do you think is incorrect? This command's output is in JSON. \u0026 is the unicode for the ampersand, and legal in json.
Many people use `jq` to parse json. `cf service-key <objectstorageinstance> <service-keys-credential-name> | jq '.password'` returns the password with unicode converted as ampersand, suitable for the openstack swift client?

Regards,
Dies Koper
CF CLI PM

**Comment by joshisa** [comment]
Hi @dkoper 
No argument on the validity of the json itself.  The concern is from the consumer point of view.   There seems to be no intelligent way for an end user to distinguish between a password string that contains a unicode escaped value versus a password string that should be treated as a literal unescaped string that just happens to contain a generated set of chars that fits the pattern of \u0026.  How would a consumer decide?  Always assume unicode escaped regardless of field being processed?  In my case, it was very time-consuming and frustrating to discern this difference.

Given there are semantics with any of these json fields, I feel that returning valid JSON is not enough.  For example, the url field value could resolve as "**https://www.google.com/search?q\u003Dunicode**"  which would validate as an error (https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.google.com%2Fsearch%3Fq%5Cu003Dunicode) even though its literal equivalent is perfectly valid ==  "**https://www.google.com/search?q=unicode**".  In this case, it might be obvious to the consumer that an invalid unicode escape sequence exists in an invalid area of the url and needs to be converted.  For the semantics of a password field value, even this insight is not so straightforward since all chars found within a potential escape sequence are equally valid as being a coincidental part of an unescaped password string.

Given that it's impossible for the CLI to know the semantics of all possible JSON fields surfaced, my suggestion is that the strings returned by the CLI always have their unicode code point escapes converted back to their unescaped representation.  If this has unwanted side-effects, then a less ideal option would be to target password fields and ensure that their values are always returned in their unescaped form.

**Comment by dkoper** [comment]
Hi @joshisa 

I believe the CLI is just returning what Cloud Controller is giving, which is in JSON format.
If so, how would the CLI decide? Always assume unicode escaped for the password field? Sounds like this could be a limitation of the CC API - or maybe passwords should be avoided that are ambiguous when rendered in JSON? @SocalNick?

**Comment by SocalNick** [comment]
Hi @joshisa,

Could you check what the API returns by doing `cf curl /v2/service_keys/:guid` and report back the results? If the Cloud Controller is incorrectly escaping, we can open an issue in our end. 

Nick

**Comment by joshisa** [comment]
Hi @SocalNick

$ cf curl /v2/service_keys/<some_guid>
{
   "metadata": {
      "guid": "<some_guid>",
      "url": "/v2/service_keys/<some_guid>",
      "created_at": "2016-03-09T16:59:08Z",
      "updated_at": null
   },
   "entity": {
      "name": "Credentials-1",
      "service_instance_guid": "some_service_instance_guid",
      "credentials": {
         "auth_url": "https://identity.open.softlayer.com",
         "project": "object_storage_7d1f4fd4_5016_4d9c_ac7d_2eafcf985a6c",
         "projectId": "some_project_id",
         "region": "dallas",
         "userId": "some_user_id",
         "username": "Admin_nice_long_string",
         "password": "Xj&2ir1TKoW-]Jf&",
         "domainId": "xxx",
         "domainName": "853255"
      },
      "service_instance_url": "/v2/service_instances/some_guid"
   }
} 

The cf curl response seems to return the unescaped form of the password - which is good.  My preference is to have the response that is displayed in the CLI stdout mirror this -- since it is the actual password.

**Comment by SocalNick** [comment]
@dkoper seems like the CLI might be doing some escaping?

**Comment by challiwill** [comment]
This is the [default JSON decoding behavior for Golang](https://golang.org/pkg/encoding/json/#Marshal)

> String values encode as JSON strings coerced to valid UTF-8, replacing invalid bytes with the Unicode replacement rune. The angle brackets "<" and ">" are escaped to "\u003c" and "\u003e" to keep some browsers from misinterpreting JSON output as HTML. Ampersand "&" is also escaped to "\u0026" for the same reason.

Are we acknowledging this and asking that we then re-encode this?

**Comment by whereswaldon** [comment]
Any word on fixing this since go 1.7 has been out for a while now?

**Comment by dkoper** [comment]
@whereswaldon Is there something in golang 1.7 that would help us resolve this?

**Comment by whereswaldon** [comment]
@dkoper The link that @challiwill posted to [this issue](https://github.com/cf-tm-bot/cli/issues/68) made me think that golang 1.7 was the blocking issue. My mistake if that's not the case.

**Comment by challiwill** [comment]
@whereswaldon I believe you mean the link that @XenoPhex posted.

**Comment by whereswaldon** [comment]
@challiwill Yes, sorry.

In any event, [this corresponding pivotal tracker ticket](https://www.pivotaltracker.com/n/projects/892938/stories/115471849) indicates that Go 1.7 was the blocking issue for this. Am I misreading that somehow?

**Comment by heyjcollins** [comment]
With the GA of the v7 CLI, we're no longer actively developing against the v6 line.  With an interest the overall hygiene of the CLI project we're closing this  issue.
If this issue is still occurring in v7 please feel free to comment and re-open. Thank you!
