### ISSUE TITLE
How to deploy and use cf services?

### ISSUE THREAD

**Issue by vimal115** [cloudfoundry/cli#796]
Hi,

I have cf deployed on vagrant machine using bosh-lite for that I have followed instruction from https://github.com/cloudfoundry/cli/issues/741 .Now I want to deploy services and bind service to my application.For service deployment I have followed instrution from  https://github.com/cloudfoundry-community/cf-services-contrib-release/tree/master/ . But I am not able to create service.

Command :- cf marketplace
Getting services from marketplace in org RelevanceLab / space RLCatalyst as admin...
OK

No service offerings found

Can someone please help me out with the problem .

### CLI Version
cf version 6.16.1+924508c-2016-02-26

Thanks,
Vimal Mishra

**Comment by dkoper** [comment]
Hi @vimal115,

I think you'd have more luck posting your question on the CF Dev mailing list or on the GitHub tracker of the cf-services-contrib project. We are not aware of any issues with the `cf marketplace`. Also, you haven't mentioned the CF release version you have deployed, but the latest CF release no longer supports the v1 service broker functionality cf-services-contrib depends on.

Regards,
Dies Koper
CF CLI PM

**Comment by vimal115** [comment]
Hi Dies,

Sorry for the inconvenience.Please find the below mentioned cf release and
stemcell info.

cf -v  : cf version 6.16.1+924508c-2016-02-26

Stemcell info
-------------
Name:    bosh-warden-boshlite-ubuntu-trusty-go_agent
Version: 3147

I have followed the following steps for cloud foundry deployment on local
machine :


1. Installed virtual box and vagrant.
2. wget -O spiff.zip
https://github.com/cloudfoundry-incubator/spiff/releases/download/v1.0.7/
<https://github.com/cloudfoundry-incubator/spiff/releases/download/v1.0.7/spiff_linux_amd64.zip>
3. unzip spiff.zip
4. export PATH=`pwd`:$PATH
5. git clone https://github.com/cloudfoundry/bosh-lite
6. git clone https://github.com/cloudfoundry/cf-release
7. export CF_RELEASE_DIR=`pwd`/cf-release
8. cd bosh-lite
9. bin/provision_cf
10. bin/add-routes

After these steps I am able to use cf login and create org and space.

Then I ran the command cf marketplace ,following message was displayed :

*Getting services from marketplace in org RelevanceLab / space RLCatalyst
as admin... OK No service offerings found*


So I have tried to deploy the services and followed instruction mentioned
on following link  .

https://github.com/cloudfoundry-community/cf-services-contrib-release

1. bosh upload release
https://cf-contrib.s3.amazonaws.com/boshrelease-cf-services-contrib-6.tgz

2. git clone
https://github.com/cloudfoundry-community/cf-services-contrib-release.git
3. cd cf-services-contrib-release
4. git checkout v6
5. templates/make_manifest warden
6. bosh -n deploy


Then ran the command cf marketplace.It displays the same message.
Can you please confirm that process followed is correct or what could be
the problem or How can I deploy services and use?

That would be great help.

Thanks
Vimal Mishra

**Comment by vimal11592** [comment]
Hi @dkoper 

Any suggestion!!!

Thanks
Vimal Mishra

**Comment by dkoper** [comment]
Hi @vimal11592

I'd suggest asking on CF Dev - sorry. This sounds more like a question about how to deploy a service with bosh, which I have little experience with.

**Comment by vimal11592** [comment]
Thanks!! @dkoper I will update the same on cf dev.

**Comment by dkoper** [comment]
Closing - the CLI team is not familiar with the mongo service. @Amit-PivotalLabs replied to your email to CF Dev.
