### ISSUE TITLE
Feature request: Pre- and post-command hooks

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/cli#801]
It would be useful to specify hooks to be executed before or after specific CLI commands, like npm's `prepublish`, `postpublish`, etc. This would be particularly handy for `cf push`, so that users could e.g. auto-build certain files before pushing, or run smoke tails and cancel the push if they fail. It could also be useful to attach chat notifications to arbitrary CLI commands, or to keep a log of commands run. Hooks could live in manifests, or in a separate JSON or YAML file.

Would this be of interest? It looks like it would be straightforward to add hooks to `RunCliCommand`. I'd be happy to give it a try if it would be useful.

**Comment by jmcarp** [comment]
Ping--would folks be interested in this feature?

**Comment by dkoper** [comment]
Hi @jmcarp,

I have never seen a request for such functionality. I am not from a Node.js background, so I'm not familiar with this feature.
I wonder if we're not complicating the cf CLI with something that could be just as easily addressed with aliases, scripts or plugins.
I'd suggest you bring it up on the CF Dev mailing list to reach a wider audience?

Cheers,
Dies Koper
CF CLI PM
