### ISSUE TITLE
specify health-check-type in manifest?

### ISSUE THREAD

**Issue by jaxonpickett** [cloudfoundry/cli#803]
Is it possible to set the cf push flag --health-heck-type via manifest.yml attribute?

running cf version 6.13.0-e68ce0f-2015-10-15T22:53:29+00:00

Thanks!

**Comment by dkoper** [comment]
Not yet. We'll take a look at it!

**Comment by cody-homedepot** [comment]
I, too, would like this feature.

**Comment by tsaleh** [comment]
I'm the second person who ran into this in the London office (@seadowg was the other one).  Could we prioritise this?  Purty please?

**Comment by tsaleh** [comment]
Actually, I just pushed a new app with `health-check-type: none` set in the manifest, and it seems to have worked swimmingly.  Maybe we should close this and the associated tracker story?

**Comment by pivotal-studionow** [comment]
`no-route: true` was once enough to get a non-web app to pass health check. I'm a little curious what happened. Is there missing documentation?

**Comment by tsaleh** [comment]
Yeah, I think it's just a case of missing docs for the `health-check-type:` manifest property.  I can imagine a use case where you have a worker app that shouldn't be routed to, but binds to `localhost:$PORT` *only* to tell the runtime when it's successfully come up.

**Comment by dkoper** [comment]
It's there now:
http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#health-check-type
