### ISSUE TITLE
cf service does not list apps bound to it

### ISSUE THREAD

**Issue by erjoalgo** [cloudfoundry/cli#806]
`cf services` includes a column for apps bound to each service, but `cf service SERVICE` does not. What is the proper way of getting this information? Can this be included in the `cf service SERVICE` output?
### CLI Version

cf version 6.15.0+fa1bfe2-2016-01-13

### CF Trace

For bugs related to HTTP requests, please run the command with env var `CF_TRACE=true`

### Platform Details

Debian Jessie

### Shell

e.g. Terminal, iTerm, Powershell, Cygwin, gnome-terminal, terminator

**Comment by dkoper** [comment]
Hi @erjoalgo 

We'll look at adding it to `cf service SERVICE` output.

Thanks!
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
This was added in cf CLI 6.18.1.
