### ISSUE TITLE
Compiled binaries are dynamically linked. Can we build them statically?

### ISSUE THREAD

**Issue by keymon** [cloudfoundry/cli#807]
### CLI Version

Any version, including 6.16.1

### Platform Details

Ubuntu 14.04.3 64-bit, Alpine linux

### Error

The distributed binaries in the github releases are dynamically compiled with the libc. Because that, it must run in a system with the same libraries that the build server.

This prevents the users to use alternative systems and distros, like [alpine](https://hub.docker.com/_/alpine/).

You can test this with:

```
$ docker run -it alpine sh
alpine$ apk --update curl tar gunzip openssl ca-certificates
...
alpine$ curl -L 'https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.16.1&source=github-rel' | tar -xvzf -
...
alpine$ ldd cf-kkk 
	/lib64/ld-linux-x86-64.so.2 (0x55b92070a000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x55b92070a000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x55b92070a000)
alpine$  ls -l /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2
ls: /lib64/ld-linux-x86-64.so.2: No such file or directory
ls: /lib64/ld-linux-x86-64.so.2: No such file or directory
ls: /lib64/ld-linux-x86-64.so.2: No such file or directory

alpine$ ./cf
sh: ./cf: not found
```

alpine says that `./cf: not found` but that is because it cannot exec the command.

# Proposed solution

Compile the project using `CGO_ENABLED=0`, as described in https://golang.org/cmd/cgo/

```
$ go get -d github.com/cloudfoundry/cli/
...
$ cd $GOPATH/src/github.com/cloudfoundry/cli
$ CGO_ENABLED=0 go build -o $GOPATH/bin/cf ./main/
...
$ ldd $GOPATH/bin/cf
	not a dynamic executable
$ file $GOPATH/bin/cf
/home/keymon/.gvm/pkgsets/go1.6/global/bin/cf: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

**Comment by dkoper** [comment]
Hi @keymon 

We have a story on that, but it's not prioritized as I wasn't sure of the impact of the change - especially since no-one had asked for this yet.
https://www.pivotaltracker.com/story/show/115376361

Thanks for your request and including all the details. I'll discuss it with the team next week.

Regards,
Dies Koper
CF CLI PM

**Comment by keymon** [comment]
Oh, thx! I have just done a PR. #808 

More cards for your pivotal backlog :wink:

**Comment by dkoper** [comment]
Linux 64bit cf CLI v6.17.1 is now statically linked. Please let us know how you go.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM
