### ISSUE TITLE
can we change 'Email' to 'User Name" when we do 'cf login'

### ISSUE THREAD

**Issue by boyang9527** [cloudfoundry/cli#810]
The user name is not necessary to be an Email ID when we log in Cloud Foundry.  It is confusing when email ID is not used as CF user name.

**Comment by dkoper** [comment]
Hi @boyang9527,

Take a look at CF trace of `cf login`: you'll find it makes a request to CF's login server, which returns a JSON string with a map called "prompts" that includes an attribute "username". Whatever you change your login server to return here is what the CLI will prompt its users for.

Regards,
Dies Koper
CF CLI PM

**Comment by boyang9527** [comment]
Got u, thanks Dies.
