### ISSUE TITLE
Something completely unexpected happened. This is a bug in cf.

### ISSUE THREAD

**Issue by shmundada93** [cloudfoundry/cli#823]
### Command

cf push smartcampus-bphc

### CLI Version

6.12.2-24abed3

### Error

runtime error: invalid memory address or nil pointer dereference

### Stack Trace

goroutine 1 [running]:
        main.generateBacktrace(0x0, 0x0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xce
        main.handlePanics(0x1b49dc0, 0xc0821e3ba0)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x1ab
        github.com/cloudfoundry/cli/cf/net.Gateway.performRequestForResponseBytes(0x1b4a188, 0xc082069b90, 0x131d8f8, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x1b49f28, 0xc0821784e0, ...)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/net/gateway.go:253 +0x2f7
        github.com/cloudfoundry/cli/cf/net.Gateway.PerformPollingRequestForJSONResponse(0x1b4a188, 0xc082069b90, 0x131d8f8, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x1b49f28, 0xc0821784e0, ...)
                C:/GoAgent/pipelines/Win64-Unit-Tests/src/github.com/cloudfoundry/cli/cf/net/gateway.go:292 +0x310
        github.com/cloudfoundry/cli/cf/net.Gateway.createUpdateOrDeleteResource(0x1b4a188, 0xc082069b90, 0x131d8f8, 0x1, 0x12a05f200, 0x0, 0x0, 0x0, 0x1b49f28, 0xc0821784e0, ...)
                C:/GoAgent/p

### CF Trace

For bugs related to HTTP requests, please run the command with env var `CF_TRACE=true`

### Platform Details

Windows 10 64-bit

### Shell

Windows command line

**Comment by dkoper** [comment]
Hi @shmundada93 

v6.12.2 is ten months old. Can you confirm you encounter this issue with the latest CLI release?
If so, can you include the cf trace?

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Closing. Feel free to reopen or open a new issue if you see the same issue occur on the latest CLI release and have a CF trace to share with us.
