### ISSUE TITLE
cf cups/uups with -p to specify path doesn't work as expected

### ISSUE THREAD

**Issue by dononelson** [cloudfoundry/cli#824]
[credentials.json.txt](https://github.com/cloudfoundry/cli/files/233852/credentials.json.txt)

### Command

cf cups my-service -p /home/here/pcf/
cf uups my-service -p /home/here/pcf/
cf uups my-service -p /home/here/pcf/credentials.json

### CLI Version

6.17.0+5d0be0a-2016-04-15

### Error

cf takes "/home/here/pcf/" (or whatever comes after -p) as a prompt, instead of looking there for credentials.json as documented in online help (under EXAMPLES: cf create-user-provided-service my-db-mine -p /path/to/credentials.json)

### Stack Trace
None

### CF Trace

[cftrace.txt](https://github.com/cloudfoundry/cli/files/233848/cftrace.txt)

For bugs related to HTTP requests, please run the command with env var `CF_TRACE=true`

### Platform Details

Centos 6.7 64-bit

### Shell

bash terminal

**Comment by dkoper** [comment]
Hi Don,

The CLI's JSON parser didn't find a valid JSON file with that filename, so it took the name as a parameter name.
If I copy & paste your attached file into http://jsonlint.com/, it complains about missing quotes around the url:
```
Error: Parse error on line 5:
...": "pass2",	"url": https: //url2.org,	
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```

If I add double quotes around the url, the user-provided service is created with the specified credentials successfully.

Regards,
Dies Koper
CF CLI PM

**Comment by dononelson** [comment]
Right you are!  I didn't realize that the CLI would do that kind of 
validation, which is very cool.  Thanks for taking the time to research 
this.

Don

**Comment by dkoper** [comment]
You're welcome. Thanks for getting back to us.
