### ISSUE TITLE
-v flag eaten in plugin args when using the 6.17 cf cli

### ISSUE THREAD

**Issue by jessexu20** [cloudfoundry/cli#825]
### CLI Version

e.g. 6.17.0

hello, I noticed that there was an update for the cf_trace option in 6.17(using -v for the cf debug).  Is there a way that we could avoid this happening and still get args for the -v value in the plugin...

Thank you...

**Comment by chendrix** [comment]
@jessexu20 is there a particular plugin you're trying to use that utilizes the `-v` flag itself?

You are right that this was an unexpected change in behavior, but we may look at restricting what flags plugins are allowed to use, saving some of them for "global" CF flags.

**Comment by jessexu20** [comment]
Yeah... We are using the IBM-Containers cf ic plugins... I believe people are using the -v for lots of stuffs... Is there a way that you check the -v but still put it into the args?

**Comment by dkoper** [comment]
Hi @jessexu20 

`-v` has been a CLI global option for a long time. We should improve plugin documentation to say `global option` means the CLI is using it so plugins shouldn't try to use it as well.

I'm not sure it would make sense for the CLI to pass in global options to plugins; it would be confusing if we would for one and not the other (e.g. `-h`, for which the CLI has enough info to handle it itself). Also, not sure how we could do validation if the CLI's `-v` takes no value while a plugin's `-v` would take one, or how your plugin would deal with the CLI passing in `-v` without an argument.

Regards,
Dies Koper
CF CLI PM

**Comment by jessexu20** [comment]
Hi @dkoper，
Well, I do understand your concern... But could it be possible that cf cli only check for -v next to it. 
For instance: 
`cf -v <plugin command>` call the cf debug options...
`cf <plugin command> -v ` will pass the -v to the plugin and for it to handle? 
If that can be done with -h, It could be better...

Thank you..

**Comment by dkoper** [comment]
Making global options less global is confusing, as `-h` and `-v` would then not give the expected behaviour for some plugin commands.
Leaving this issue open to look at our plugin docs if we can be more explicit that "global" also applies to plugin commands.

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Closing as we've updated our documentation.
