### ISSUE TITLE
cf create-app-manifest *AppName* returns Aww shucks on Bluemix

### ISSUE THREAD

**Issue by peterpoliwoda** [cloudfoundry/cli#827]
### Command
cf create-app-manifest PeterTest 

### CLI Version
6.12.2-24abed3

### Error
Aww shucks. :-)

### CC API Version
Bluemix 

### CF Trace

eters-mbp:PeterTest peterpoliwoda$ CF_TRACE=true cf create-app-manifest PeterTest

REQUEST: [2016-04-26T12:37:11+01:00]
GET /v2/spaces/f0d9a40f-0ae1-4e34-8d1c-000efee7f186/apps?q=name%3APeterTest&inline-relations-depth=1 HTTP/1.1
Host: api.w3ibm.bluemix.net
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.12.2-24abed3 / darwin

RESPONSE: [2016-04-26T12:37:12+01:00]
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Connection: Keep-Alive
Content-Type: application/json;charset=utf-8
Date: Tue, 26 Apr 2016 11:37:13 GMT
Server: nginx
Set-Cookie: DPJSESSIONID=PBC5YS:122083196; Path=/; Domain=.w3ibm.bluemix.net
X-Backside-Transport: OK OK
X-Cf-Requestid: 984c8849-0ac6-48df-63ee-433892b5585c
X-Client-Ip: 9.162.247.165
X-Content-Type-Options: nosniff
X-Global-Transaction-Id: 752357509
X-Vcap-Request-Id: b58f12a5-2163-49a9-7e43-fb9291b01e26::a27cda9f-6c98-410a-a0ee-95e21ed0772c

1268
{
  "total_results": 1,
  "total_pages": 1,
  "prev_url": null,
  "next_url": null,
  "resources": [
    {
      "metadata": {
        "guid": "79929ccb-10c3-4a01-a7d9-51b606f73604",
        "url": "/v2/apps/79929ccb-10c3-4a01-a7d9-51b606f73604",
        "created_at": "2016-04-22T14:04:09Z",
        "updated_at": "2016-04-22T14:04:51Z"
      },
      "entity": {
        "name": "PeterTest",
        "production": false,
        "space_guid": "f0d9a40f-0ae1-4e34-8d1c-000efee7f186",
        "stack_guid": "f3228524-3505-45a4-b825-7c212d9923a6",
        "buildpack": null,
        "detected_buildpack": "SDK for Node.js(TM) (ibm-node.js-4.2.4, buildpack-v3.0-20160125-1224)",
        "environment_json": {

        },
        "memory": 256,
        "instances": 1,
        "disk_quota": 1024,
        "state": "STARTED",
        "version": "4255a4c8-4432-4962-b196-0fc18b2f758d",
        "command": null,
        "console": false,
        "debug": null,
        "staging_task_id": "192914de1ecb41baa9494672d8d69ff3",
        "package_state": "STAGED",
        "health_check_type": "port",
        "health_check_timeout": null,
        "staging_failed_reason": null,
        "staging_failed_description": null,
        "diego": false,
        "docker_image": null,
        "package_updated_at": "2016-04-22T14:04:15Z",
        "detected_start_command": "./vendor/initial_startup.rb",
        "enable_ssh": true,
        "docker_credentials_json": {
          "redacted_message": "[PRIVATE DATA HIDDEN]"
        },
        "space_url": "/v2/spaces/f0d9a40f-0ae1-4e34-8d1c-000efee7f186",
        "space": {
          "metadata": {
            "guid": "f0d9a40f-0ae1-4e34-8d1c-000efee7f186",
            "url": "/v2/spaces/f0d9a40f-0ae1-4e34-8d1c-000efee7f186",
            "created_at": "2016-04-11T14:21:54Z",
            "updated_at": null
          },
          "entity": {
            "name": "dev",
            "organization_guid": "6f54f707-4a6b-4316-aa8c-9f76ca74ca5a",
            "space_quota_definition_guid": null,
            "allow_ssh": true,
            "organization_url": "/v2/organizations/6f54f707-4a6b-4316-aa8c-9f76ca74ca5a",
            "developers_url": "/v2/spaces/f0d9a40f-0ae1-4e34-8d1c-000efee7f186/developers",
            "managers_url": "/v2/spaces/f0d9a40f-0ae1-4e34-8d1c-000efee7f186/managers",
            "auditors_url": "/v2/spaces/f0d9a40f-0ae1-4e34-8d1c-000efee7f186/auditors",
            "apps_url": "/v2/spaces/f0d9a40f-0ae1-4e34-8d1c-000efee7f186/apps",
            "routes_url": "/v2/spaces/f0d9a40f-0ae1-4e34-8d1c-000efee7f186/routes",
            "domains_url": "/v2/spaces/f0d9a40f-0ae1-4e34-8d1c-000efee7f186/domains",
            "service_instances_url": "/v2/spaces/f0d9a40f-0ae1-4e34-8d1c-000efee7f186/service_instances",
            "app_events_url": "/v2/spaces/f0d9a40f-0ae1-4e34-8d1c-000efee7f186/app_events",
            "events_url": "/v2/spaces/f0d9a40f-0ae1-4e34-8d1c-000efee7f186/events",
            "security_groups_url": "/v2/spaces/f0d9a40f-0ae1-4e34-8d1c-000efee7f186/security_groups"
          }
        },
        "stack_url": "/v2/stacks/f3228524-3505-45a4-b825-7c212d9923a6",
        "stack": {
          "metadata": {
            "guid": "f3228524-3505-45a4-b825-7c212d9923a6",
            "url": "/v2/stacks/f3228524-3505-45a4-b825-7c212d9923a6",
            "created_at": "2015-06-24T18:24:05Z",
            "updated_at": null
          },
          "entity": {
            "name": "cflinuxfs2",
            "description": "Ubuntu 14.04.2 trusty"
          }
        },
        "events_url": "/v2/apps/79929ccb-10c3-4a01-a7d9-51b606f73604/events",
        "service_bindings_url": "/v2/apps/79929ccb-10c3-4a01-a7d9-51b606f73604/service_bindings",
        "service_bindings": [

        ],
        "routes_url": "/v2/apps/79929ccb-10c3-4a01-a7d9-51b606f73604/routes",
        "routes": [
          {
            "metadata": {
              "guid": "5dcc592e-e1d8-41ea-995a-01f3f9a35172",
              "url": "/v2/routes/5dcc592e-e1d8-41ea-995a-01f3f9a35172",
              "created_at": "2016-04-22T14:04:11Z",
              "updated_at": null
            },
            "entity": {
              "host": "petertest",
              "path": "",
              "domain_guid": "657e76ca-48b1-40a4-ae39-44a1f84d311e",
              "space_guid": "f0d9a40f-0ae1-4e34-8d1c-000efee7f186",
              "service_instance_guid": null,
              "port": 0,
              "domain_url": "/v2/domains/657e76ca-48b1-40a4-ae39-44a1f84d311e",
              "space_url": "/v2/spaces/f0d9a40f-0ae1-4e34-8d1c-000efee7f186",
              "apps_url": "/v2/routes/5dcc592e-e1d8-41ea-995a-01f3f9a35172/apps"
            }
          }
        ]
      }
    }
  ]
}
0

REQUEST: [2016-04-26T12:37:12+01:00]
GET /v2/apps/79929ccb-10c3-4a01-a7d9-51b606f73604/summary HTTP/1.1
Host: api.w3ibm.bluemix.net
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.12.2-24abed3 / darwin

RESPONSE: [2016-04-26T12:37:13+01:00]
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Connection: Keep-Alive
Content-Type: application/json;charset=utf-8
Date: Tue, 26 Apr 2016 11:37:14 GMT
Server: nginx
Set-Cookie: DPJSESSIONID=PBC5YS:122083196; Path=/; Domain=.w3ibm.bluemix.net
X-Backside-Transport: OK OK
X-Cf-Requestid: 072d836d-760a-4eca-692b-5bae334d5db6
X-Client-Ip: 9.162.247.165
X-Content-Type-Options: nosniff
X-Global-Transaction-Id: 599626281
X-Vcap-Request-Id: 47d2b8fa-e93a-4c0b-5369-013674a4fb17::157cce34-11e8-4569-8815-47726dd1a2df

4d6
{"guid":"79929ccb-10c3-4a01-a7d9-51b606f73604","name":"PeterTest","routes":[{"guid":"5dcc592e-e1d8-41ea-995a-01f3f9a35172","host":"petertest","domain":{"guid":"657e76ca-48b1-40a4-ae39-44a1f84d311e","name":"w3ibm.mybluemix.net"}}],"running_instances":1,"services":[],"available_domains":[{"guid":"657e76ca-48b1-40a4-ae39-44a1f84d311e","name":"w3ibm.mybluemix.net","router_group_guid":null}],"name":"PeterTest","production":false,"space_guid":"f0d9a40f-0ae1-4e34-8d1c-000efee7f186","stack_guid":"f3228524-3505-45a4-b825-7c212d9923a6","buildpack":null,"detected_buildpack":"SDK for Node.js(TM) (ibm-node.js-4.2.4, buildpack-v3.0-20160125-1224)","environment_json":{},"memory":256,"instances":1,"disk_quota":1024,"state":"STARTED","version":"4255a4c8-4432-4962-b196-0fc18b2f758d","command":null,"console":false,"debug":null,"staging_task_id":"192914de1ecb41baa9494672d8d69ff3","package_state":"STAGED","health_check_type":"port","health_check_timeout":null,"staging_failed_reason":null,"staging_failed_description":null,"diego":false,"docker_image":null,"package_updated_at":"2016-04-22T14:04:15Z","detected_start_command":"./vendor/initial_startup.rb","enable_ssh":true,"docker_credentials_json":{"redacted_message":"[PRIVATE DATA HIDDEN]"}}
0

Creating an app manifest from current settings of app PeterTest ...

	Aww shucks.

	Something completely unexpected happened. This is a bug in cf.
	Please file this bug : https://github.com/cloudfoundry/cli/issues
	Tell us that you ran this command:

		cf create-app-manifest PeterTest

	using this version of the CLI:

		6.12.2-24abed3

	and that this error occurred:

		runtime error: invalid memory address or nil pointer dereference

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x3)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xa9
	main.handlePanics(0x171ca00, 0xc210185b90)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x123
	runtime.panic(0x5a3660, 0xf09679)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).createManifest(0xc210292000, 0xc210293a50, 0x24, 0xc2103fcf60, 0x9, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:91 +0x57
	github.com/cloudfoundry/cli/cf/commands.(*CreateAppManifest).Execute(0xc210292000, 0x171d798, 0xc210273c80)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/create_app_manifest.go:87 +0x431
	main.main()
		/Us

### Platform Details

Mac OS X 10.11.4

### Shell
Terminal

**Comment by dkoper** [comment]
Hi @peterpoliwoda 

v6.12.2 is ten months old. Can you confirm you encounter this issue with the latest CLI release?

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Closing. Feel free to reopen or submit a new issue if it occurs with the latest CLI release.

**Comment by peterpoliwoda** [comment]
Hi, my bad, didn't realize there was a newer version.
Upgraded to **cf version 6.17.0+5d0be0a-2016-04-15** where issue does not occur any more.
Thanks!
