### ISSUE TITLE
cf push flag to push only if app doesn't exist

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/cli#830]
`cf push` will currently update an application if an application with the same name as the one specified in the manifest exists in the current org/space. This can cause unintended app downtime if the user is not careful (e.g. if she forgets to change the application name in the manifest, an attempt to perform a blue/green deployment will backfire). 

The safest behaviour for `cf push` would be to default to not update a running application unless a `-f/--force` flag is given. If the change to the default behaviour is deemed too invasive, at least adding a `--no-update`/`--no-force` or similar flag would give users that care about blue/green deployments an additional safeguard.

### Command
cf push

### CLI Version
cf version 6.17.0+5d0be0a-2016-04-15

### CC API Endpoint Version
2.39.0

**Comment by dkoper** [comment]
Hi @CAFxX 

This is the first time I hear of this concern. I'm reluctant to introduce a flag and change `cf push` behaviour (potentially breaking all scripts out there). I feel your use case can easily be implemented using an alias that runs e.g. `cf app your-app || cf push your-app` instead, so push is only performed if the app name does not exist.
At the moment we only have a `-f` option on destructive commands like `delete-xxx`.

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
We have an epic on declarative app manifests, which should introduce a diff between specified and (existing app's) manifests followed by a confirmation prompt (like bosh does). I believe this should address your use case.
