### ISSUE TITLE
cf set-env suggests restage without app name

### ISSUE THREAD

**Issue by apoydence** [cloudfoundry/cli#832]
### Command

```
$ cf set-env myapp SOME_ENV_VALUE http://10.0.0.2:8080
Setting env variable 'SOME_ENV_VALUE' to 'http://10.0.0.2:8080' for app myapp in org someorg / space somespace as someuser...
OK
TIP: Use 'cf restage' to ensure your env variable changes take effect
```

### CLI Version

cf version 6.16.1+924508c-2016-02-26

### Issue

It would be great if instead of `cf restage` it would say `cf restage myapp`. I've seen this when I push an app and it fails and suggests I do `cf logs myapp --recent`.

**Comment by dkoper** [comment]
Thanks for the suggestion! I'll ask the team to take a look.

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
We have added supported for this in cf CLI 6.19.0, released today. Thanks again for the suggestion!
https://github.com/cloudfoundry/cli#downloads

Regards,
Dies Koper
CF CLI PM
