### ISSUE TITLE
Error dialing loggregator server: dial tcp: missing address.

### ISSUE THREAD

**Issue by SamwiseGambgee** [cloudfoundry/cli#833]
Hi All!

I'm trying to access a Secure Salesforce SOAP url through a Java application- which calls a method from the SOAP web service.

Pushing the .jar file has issues.
I get the following error:

`Warning: error tailing logs
Error dialing loggregator server: dial tcp: missing address.
Please ask your Cloud Foundry Operator to check the platform configuration (loggregator endpoint is wss://loggregator.cloud.pcftest.com:4443).
Starting app appName in org sampleORG / space ASP-DEV as myemail@domain.com...`

**Comment by dkoper** [comment]
Hi @SamwiseGambgee 

What does `cf curl /v2/info` return you? And `cf -v`?

Cheers,
Dies Koper
CF CLI PM

**Comment by SamwiseGambgee** [comment]
Hi @dkoper , thanks for responding!

`cf -v` returns: `cf version 6.15.0+fa1bfe2-2016-01-12`

`cf curl /v2/info` 
returns:
`{
   "name": "vcap",
   "build": "2222",
   "support": "http://support.cloudfoundry.com",
   "version": 2,
   "description": "Cloud Foundry sponsored by Pivotal",
   "authorization_endpoint": "https://login.cloud.pcftest.com",
   "token_endpoint": "https://uaa.cloud.pcftest.com",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.25.0",
   "logging_endpoint": "wss://loggregator.cloud.pcftest.com:4443"
}`

**Comment by jasonkeene** [comment]
It seems like the `cf curl /v2/info` is missing a property called `doppler_logging_endpoint` which ideally would point to `wss:doppler.cloud.pcftest.com:4443`.

What version of CF are you using?

**Comment by dkoper** [comment]
api_version 2.25.0, so the CF version would be pretty old (v208?), possibly before the doppler endpoint was introduced. I thought the CLI would work fine with the loggregator endpoint.
So what is the problem exactly, and what command are you running?
I have seen a "Error dialing loggregator server" error when pushing an app or running `cf logs` while in a corporate network where outgoing traffic to port 4443 is blocked. Other than not being able to see logs and stats, apps should be pushed without impact.

**Comment by dkoper** [comment]
Closing due to lack of information on the issue. Feel free to reopen or submit a new issue if the above didn't help us and you have time to work with us to help us investigate.
