### ISSUE TITLE
Create-service-auth-token fails #azure #cf #mongodb #service

### ISSUE THREAD

**Issue by garv-nagarro** [cloudfoundry/cli#834]
i am working as an admin user on a deployment guided by azure mongodb release https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/tree/master/docs/advanced/deploy-mongodb

Am stuck on a step to create a service auth token.
Have successfully deployed mongodb as a deployment on my cf, but it doesnt show up on my cf marketplace.
Have included the security group so my mongo gateway network discovery must be doing good.

Am attaching the trace log on the failing step, please help!

--------------------------------------------------------------------------
`CF_TRACE=true cf create-service-auth-token mongodb core 12345678
Creating service auth token as admin...

REQUEST: [2016-05-05T14:46:03Z]
POST /v2/service_auth_tokens HTTP/1.1
Host: api.xx.xx.xx.xx.xip.io
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.14.1+dc6adf6 / linux

{"label":"mongodb","provider":"core","token":"[PRIVATE DATA HIDDEN]"}

RESPONSE: [2016-05-05T14:46:03Z]
HTTP/1.1 404 Not Found
Content-Length: 86
Content-Type: application/json;charset=utf-8
Date: Thu, 05 May 2016 14:46:06 GMT
Server: nginx
X-Cascade: pass
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 462b356f-5416-4d75-62cf-858920848ce3
X-Vcap-Request-Id: 0f65fe6a-3f31-46c2-7b90-e05e55b6b47f::bdd528e8-f26a-4516-bc53-7bc848673c12

{
  "code": 10000,
  "description": "Unknown request",
  "error_code": "CF-NotFound"
}
FAILED
Server error, status code: 404, error code: 10000, message: Unknown request`
---------------------------------------------------------------------------------

cf --version
cf version 6.14.1+dc6adf6-2015-12-22

cf api
API endpoint: https://api.xx.xx.xx.xx.xip.io (API version: 2.51.0)

**Comment by dkoper** [comment]
Hi @garv-nagarro 

This is probably not the best place to get help with issues with service broker registration. Please try on the CF Dev mailing list.

Regards,
Dies Koper
CF CLI PM

**Comment by bingosummer** [comment]
Hi @garv-nagarro 
Please refer to https://github.com/cloudfoundry/cf-release/issues/971.
We are trying to fix the issue.

And if you hit some other issues about bosh-azure-cpi-release or its docs, please feel free to open an issue in [bosh-azure-cpi-release issues](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/issues). We are glad to get your feedbacks.

**Comment by garv-nagarro** [comment]
thanks alot @bingosummer. I appreciate your response.
