### ISSUE TITLE
remove &s from download urls

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/cli#836]
As you probably know &s are interpreted by bash in a special way, which means users have to quote download urls. Majority of times I catch myself and quote urls before running the command, however, it's not a very pleasant experience when I forget to do so. Please switch to a more friendly url scheme such as:

https://cli.run.pivotal.io/stable?release=macosx64&source=github

becomes

https://cli.run.pivotal.io/stable/macosx64?source=github
https://cli.run.pivotal.io/stable/macosx64/6.17.1?source=github

**Comment by dkoper** [comment]
Hi Dmitriy,

Once we support routes-with-paths in app manifests, I'd like to replace the domain with a CFF one, which would offer an opportunity to revisit the use of query params too.
Please track the following story instead:
https://www.pivotaltracker.com/story/show/121031055
