### ISSUE TITLE
cf6 push caused index out of range

### ISSUE THREAD

**Issue by bart-blommaerts** [cloudfoundry/cli#837]
### Command

cf6 push jworks 

CI build from Codeship. Restarting the build a second time, works.

### CLI Version

6.11.2-2a26d55

### Error

runtime error: index out of range

### Stack Trace

goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x3)
		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xa9
	main.handlePanics(0x7f92928385d8, 0xc21006b540)
		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x123
	runtime.panic(0x962c00, 0x12590b7)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc210255b40, 0xc210c2be70, 0x24, 0xc210b944e0, 0x1, ...)
		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x275
	github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc210255de0, 0xc210c2be70, 0x24, 0xc2103eaca0, 0x6, ...)
		/var/vcap/data/gocd-agent/pipelines/Linux64-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:112 +0x68

**Comment by dkoper** [comment]
cf CLI 6.11.2 is over 6 months old. Please confirm it's reproducible on the latest release:
https://github.com/cloudfoundry/cli/releases/tag/v6.18.0

**Comment by bart-blommaerts** [comment]
Doesn't seem to happen again. I'll close for now. If it reappears, I will reopen.
