### ISSUE TITLE
showing null actor in 'cf events' when action is taken using a UAA client id

### ISSUE THREAD

**Issue by boyang9527** [cloudfoundry/cli#844]
when I am granted through client-credential and use CC API to update an application, the events shows null  actor.

Can we just show the actor field if actor_name is null? 

Here is a smple response from CC API that 'cf events' command invokes 

         "entity": {
            "type": "audit.app.update",
            "actor": "cf-xxx-client",
            "actor_type": "user",
            "actor_name": null,
            "actee": "9fd12ebf-efaf-4a12-b97c-3e9f8715a651",
            "actee_type": "app",
            "actee_name": "TestApp",
            "timestamp": "2016-04-15T22:27:12Z",
            "metadata": {
               "request": {
                  "instances": 1
               }
            },
            "space_guid": "f5915cd0-adc8-4644-9edc-d878d321c77b",
            "organization_guid": "93bc82dd-a981-4058-867b-721573e37f6a"
         }

### Command

cf events

**Comment by dkoper** [comment]
Hi @boyang9527 

We have addressed this in our **edge** release. Can you try it out and let us know it now does what you expect it to?

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
The fix was included in cf CLI 6.18.1.
