### ISSUE TITLE
Add GitHub Release Artifacts

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/cli#852]
Would it be possible to add the pre-built binaries of the CF cli as GitHub release artifacts to new releases? It would make it a lot easier to perform updates for internal processes via Concourse CI's [GitHub Release resource](https://github.com/concourse/github-release-resource).

**Comment by dkoper** [comment]
@geofffranks What internal processes? The cli-docs-scripts scripts are kicked off by concourse every time we do a release, by watching an S3 bucket. Please ping #cli on slack to ask if that can be done for other projects.
