### ISSUE TITLE
cf

### ISSUE THREAD

**Issue by bonfilsd** [cloudfoundry/cli#853]
High five for submitting a report!
To avoid additional back and forth, please include the following details as relevant:

### Command

e.g. cf org-users

### CLI Version

e.g. 6.13.0-dfba612 (visit the [releases page](https://github.com/cloudfoundry/cli/releases/) and confirm it's reproducible on the latest version)

### CC API Endpoint Version

see `cf api` output

### CF Trace

For bugs related to HTTP requests, please run the command with env var `CF_TRACE=true`

### Platform Details

e.g. Mac OS X 10.11, Windows 8.1 64-bit, Ubuntu 14.04.3 64-bit

### Shell

e.g. Terminal, iTerm, Powershell, Cygwin, gnome-terminal, terminator

**Comment by dkoper** [comment]
Closing as the bug report is empty.
