### ISSUE TITLE
Feature: Support Route's Context Path in bind-route-service command

### ISSUE THREAD

**Issue by dbeauregard-pivotal** [cloudfoundry/cli#856]
Add support in the bind-route-service command to specify the context path, in addition to the hostname.
i.e., "cf bind-route-service cfapps.io static-rs --hostname mysofeaapp **--path somepath**"

The CF API supports filtering on path when querying for the routes.
_"Valid filters: host, domain_guid, organization_guid, path, port"_
https://apidocs.cloudfoundry.org/237/routes/list_all_routes.html

May also want to consider adding support for 'port' while at it.

I was able to accomplish this via the REST API by querying for the routes and adding the 'q' port filter in the "GET /v2/routes" command then using the route's guid in the "/v2/user_provided_service_instances/<CUPS GUID>/routes/<Route GUID>" command

### Command

cf bind-route-service

### CLI Version

cf version 6.18.1+a1103f0-2016-05-24

### Error
N/A

### Stack Trace
N/A

### CC API Endpoint Version

API endpoint: https://api.run.pivotal.io (API version: 2.56.0)

### CF Trace
N/A

### Platform Details

Mac OS X 10.11.5

### Shell

iTerm 2

**Comment by dkoper** [comment]
This has been added in cf CLI 6.20.0.
https://github.com/cloudfoundry/cli#downloads

Thanks for bringing it to our attention!

Regards,
Dies Koper
CF CLI PM
