### ISSUE TITLE
plugin installation fail due to i18n problem

### ISSUE THREAD

**Issue by dixyes** [cloudfoundry/cli#857]
wrong file path in i18n.go?

i see there is "cf/i18n/resources/zh**-h**ans.all.json“
but it will check ”i18n\resources\zh**_H**ans.all.json“ ,then panic
### Command

    cf install-plugin https://static-ice.ng.bluemix.net/ibm-containers-windows_x64.exe
    #or just run the file:
    ibm-containers-windows_x64.exe

### CLI Version

cf version 6.19.0+b29b4e0-2016-06-08

### Error
    $ cf install-plugin https://static-ice.ng.bluemix.net/ibm-containers-windows_x64.exe

    **Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at your own risk.**

    Do you want to install the plugin https://static-ice.ng.bluemix.net/ibm-containers-windows_x64.exe? (y or n)> y

    Attempting to download binary file from internet address...
    10379264 bytes downloaded...
    Installing plugin ibm-containers-windows_x64.exe...
    FAILED
    exit status 2

run the exe, panic occur:

    $ ./ibm-containers-windows_x64.exe
    panic: Asset i18n\resources\zh_Hans.all.json not found

    goroutine 1 [running]:
    github.com/ibm-containers/i18n.initWithLocale(0x8ad7b0, 0x7, 0x8ad7b0)
            /home/jenkins/workspace/Containers-CCSCLI/containers-dcscli/plugins/src/github.com/ibm-containers/i18n/i18n.go:61 +0x79
    github.com/ibm-containers/i18n.Init(0x2925a0, 0xc0820065a0, 0x2926a0, 0xb01008, 0xe)
            /home/jenkins/workspace/Containers-CCSCLI/containers-dcscli/plugins/src/github.com/ibm-containers/i18n/i18n.go:55 +0x12b
    github.com/ibm-containers/i18n.init()
            /home/jenkins/workspace/Containers-CCSCLI/containers-dcscli/plugins/src/github.com/ibm-containers/i18n/i18n.go:41 +0x1a0
    request.init()
            /home/jenkins/workspace/Containers-CCSCLI/containers-dcscli/plugins/src/request/request.go:258 +0x4e
    main.init()
            /home/jenkins/workspace/Containers-CCSCLI/containers-dcscli/plugins/src/github.com/ibm-containers/wrapper_docker.go:78 +0x66

### Stack Trace
    panic: Asset i18n\resources\zh_Hans.all.json not found

    goroutine 1 [running]:
    github.com/ibm-containers/i18n.initWithLocale(0x8ad7b0, 0x7, 0x8ad7b0)
            /home/jenkins/workspace/Containers-CCSCLI/containers-dcscli/plugins/src/github.com/ibm-containers/i18n/i18n.go:61 +0x79
    github.com/ibm-containers/i18n.Init(0x2925a0, 0xc0820065a0, 0x2926a0, 0xb01008, 0xe)
            /home/jenkins/workspace/Containers-CCSCLI/containers-dcscli/plugins/src/github.com/ibm-containers/i18n/i18n.go:55 +0x12b
    github.com/ibm-containers/i18n.init()
            /home/jenkins/workspace/Containers-CCSCLI/containers-dcscli/plugins/src/github.com/ibm-containers/i18n/i18n.go:41 +0x1a0
    request.init()
            /home/jenkins/workspace/Containers-CCSCLI/containers-dcscli/plugins/src/request/request.go:258 +0x4e
    main.init()
            /home/jenkins/workspace/Containers-CCSCLI/containers-dcscli/plugins/src/github.com/ibm-containers/wrapper_docker.go:78 +0x66
### CC API Endpoint Version

    No api endpoint set. Use 'cf api' to set an endpoint

### Platform Details

Windows 8.1 pro (v6.3 build 9600) x64
using Chinese Simplified as default language

### Shell

msys2/cmd (same error)

**Comment by dkoper** [comment]
Hi @dixyes 

The plugin is not from us. I found the following page about this plugin which seems to indicate your cf CLI version is not in the supported version range?
https://console.ng.bluemix.net/docs/containers/container_cli_ov.html#container_cli_ov

Regards,
Dies Koper
CF CLI PM

**Comment by dixyes** [comment]
Hi @dkoper 

Thanks for you help ,I just download the lastest build ,and forget to check supported version...
and I don't know relation between cf-cli and ic plugin

I will close this issue and try proper version of cf-cli or just use my English language Archlinux
