### ISSUE TITLE
cf push gives '?' for number of instances if it is pushed with "--no-route" Option.

### ISSUE THREAD

**Issue by gsriniv** [cloudfoundry/cli#859]
Command Issued:
cf push applicationVer2 -f <source code Path> --no-route -n <hostName> -d <domainName>

Expected output:
================================================================================
Using manifest file C:\2016\Atlas\cliTest\alchemy-atlas-e2e\test\svt\common\bluemixapp\helloapp\ver2\manifest.yml
              Creating app ActiveDeploymentTestAppver2 in org <userOrg> / space <SPACE> as <LoginID>...
              OK
              App ActiveDeploymentTestAppver2 is a worker, skipping route creation
              Uploading ActiveDeploymentTestAppver2...
              Uploading app files from: C:\2016\Atlas\cliTest\alchemy-atlas-e2e\test\svt\common\bluemixapp\helloapp\ver2
              Uploading 18.1K, 9 files                            
              Done uploading
              OK
              Starting app ActiveDeploymentTestAppver2 in  Showing health and status for app ActiveDeploymentTestAppver2 in org <ORG> / spac<SPACE> as <Login ID>..
              -----> Downloaded app package (20K)
               .
              -----> IBM SDK for Node.js Buildpack v3.4-20160518-1653
                     Based on Cloud Foundry Node.js Buildpack v1.5.4
              -----> Creating runtime environment
               .
              -----> Installing binaries
              .       .
              -----> Restoring cache
                     Skipping cache restore (new runtime signature)
              -----> Building dependencies
                     Pruning any extraneous modules
                     Installing node modules (package.json      .
              -----> Installing App Management
              -----> Caching build
                     Clearing previous node cache
                     Saving 2 cacheDirectories (default):
                    .
              -----> Build succeeded!
                     .
              -----> Uploading droplet (15M)
              
              1 of 1 instances running
              
              App started
              OK
              App ActiveDeploymentTestAppver2 was started using this command `./vendor/initial_startup.rb`
              Showing health and status for app ActiveDeploymentTestAppver2 in org  Showing health and status for app ActiveDeploymentTestAppver2 in org <ORG> / spac<SPACE> as <Login ID>..
              OK
              
              requested state: started
              **_instances: 1/1_**
              usage: 128M x 1 instances
              urls:
              last uploaded: Mon Jun 13 06:42:19 UTC 2016
              stack: cflinuxfs2
              buildpack: SDK for Node.js(TM) (ibm-node.js-0.12.14, buildpack-v3.4-20160518-1653)
              
                   state     since                    cpu    memory          disk          details   
              #0   running   2016-06-13 12:13:07 PM   0.0%   14.3M of 128M   57M of 512M     
===============================================================================
Observed Output:
===============================================================================
Using manifest file /root/test_build/test/svt/common/bluemixapp/helloapp/ver2/manifest.yml
             Creating app ActiveDeploymentTestAppver2 in org <userOrg> / space <SPACE> as <LoginID>.....
              OK
              App ActiveDeploymentTestAppver2 is a worker, skipping route creation
              Uploading ActiveDeploymentTestAppver2...
              Uploading app files from: /root/test_build/test/svt/common/bluemixapp/helloapp/ver2
              Uploading 18K, 9 files
              Done uploading
              OK
              Starting app ActiveDeploymentTestAppver2 in  org <ORG> / spac<SPACE> as <Login ID>..
              -----> Downloaded app package (20K)
                  
              -----> IBM SDK for Node.js Buildpack v3.4-20160518-1653
                     Based on Cloud Foundry Node.js Buildpack v1.5.4
              -----> Creating runtime environment
              .
              -----> Installing binaries
              .
              -----> Restoring cache
                     Skipping cache restore (new runtime signature)
              -----> Building dependencies
                     Pruning any extraneous modules
                     Installing node modules (package.json)
              .
              -----> Installing App Management
              -----> Caching build
                     Clearing previous node cache
                     - node_modules
                     - bower_components (nothing to cache)
              -----> Build succeeded!
              .
              -----> Uploading droplet (15M)
              1 of 1 instances running
              App started
              OK
              App ActiveDeploymentTestAppver2 was started using this command `./vendor/initial_startup.rb`
              Showing health and status for app ActiveDeploymentTestAppver2 in org <ORG> / spac<SPACE> as <Login ID>
              OK
              requested state: started
              **_instances: ?/1_**
              usage: 128M x 1 instances
              urls:
              last uploaded: Tue Jun 14 15:27:18 UTC 2016
              stack: unknown
              buildpack: SDK for Node.js(TM) (ibm-node.js-0.12.14, buildpack-v3.4-20160518-1653)
                   state     since                    cpu    memory          disk          details
              #0   running   2016-06-14 03:28:11 PM   0.0%   14.3M of 128M   57M of 512M
===============================================================================

**Comment by dkoper** [comment]
Can you rerun with trace enabled and share that?

**Comment by dkoper** [comment]
Closing as I have not been able to reproduce the issue and we need the cf trace to investigate further.
