### ISSUE TITLE
cf push failed : cannot find package "github.com/cloudfoundry/loggregator_consumer" 

### ISSUE THREAD

**Issue by GAnuPriya** [cloudfoundry/cli#863]
cannot find package "github.com/cloudfoundry/loggregator_consumer" in any of:
        /tmp/cache/go1.6.2/go/src/github.com/cloudfoundry/loggregator_consumer (from $GOROOT)
        /tmp/staged/app/.heroku/go/src/github.com/cloudfoundry/loggregator_consumer (from $GOPATH)
Staging failed: Buildpack compilation step failed

**Comment by XenoPhex** [comment]
Hey there @GAnuPriya,

Can you please provide a bit more context about the issue above so we can debug further: 

1. What version of the CLI were you pushing?
1. How were you using the `cf push` command (which flags)?
1. If you were using a manifest, can you provide us with a sanitized version of it?
1. What kind of app is it? If it's open source, can you provide us a link so we can give it a try?

Without more information, this looks like more like a [Go Buildpack](https://github.com/cloudfoundry/go-buildpack) issue. If you need faster help debugging the issue, please use slack to contact the buildpacks team or our team.

**Comment by GAnuPriya** [comment]
@Anand Gaitonde,

Thanks for your reply.

I tried using latest version of CLI. And added a Procfile to start my app. Its working fine now.

**Comment by ccemeraldeyes** [comment]
I'm still having this issue with the updated CLI
