### ISSUE TITLE
`cf stack` prints out usage for `cf auth`

### ISSUE THREAD

**Issue by wfernandes** [cloudfoundry/cli#867]
### Command

`cf stack`

### CLI Version
```
±  |master ✗| → cf --version
cf version 6.12.4-b4b6af1-2015-09-18T17:54:54+00:00
```

### Error
When running the `cf stack` command the first line says it requires app name as argument but the remaining details are about the `cf auth` command.
```
±  |master ✗| → cf stack
FAILED
Incorrect Usage. Requires app name as argument

NAME:
   auth - Authenticate user non-interactively

USAGE:
   cf auth USERNAME PASSWORD

WARNING:
   Providing your password as a command line option is highly discouraged
   Your password may be visible to others and may be recorded in your shell history

EXAMPLE:
   cf auth name@example.com "my password" (use quotes for passwords with a space)
   cf auth name@example.com "\"password\"" (escape quotes if used in password)
```

### CC API Endpoint Version
API version: 2.57.0

### Platform Details

`Mac OS X 10.11.5 `

### Shell

` iTerm`

**Comment by wfernandes** [comment]
I'll try and create a PR for this over the weekend if you'll can't get to it sooner.

**Comment by wfernandes** [comment]
I just upgraded to the latest CLI. This is a non-issue. I'll close it myself. My Bad.

**Comment by dkoper** [comment]
Hi @wfernandes,

Somebody beat you to it over half a year ago, see #635! :)

Regards,
Dies Koper
CF CLI PM
