### ISSUE TITLE
.cfignore doesnt ignore anything on windows

### ISSUE THREAD

**Issue by el-davo** [cloudfoundry/cli#868]
I have been trying to get .cfignore file to work and ignore my node_modules and bower_components folder. The .cfignore files contains the following entrys

/node_modules
/bower_components

When i then try and do a cf push I am seeing that the .cfignore file entries are not being respected and it tries to upload the contents of those directories. 

I am using windows 7 Enterprise

### Command

cf push

### CLI Version

cf version 6.19.0+b29b4e0-2016-06-08

Any help appreciated

**Comment by el-davo** [comment]
Sorry my fault. Seems it is working

**Comment by dkoper** [comment]
Feel free to add more details so other people running into the same issue can learn from you?
