### ISSUE TITLE
cf files handles an empty file the same as an empty directory

### ISSUE THREAD

**Issue by jlstack** [cloudfoundry/cli#869]
There is an empty file in my application located at /app/empty.txt. When running ```cf files chocolate-eclair /app/empty.txt``` I get the following:

```
Getting files for app chocolate-eclair in org lstack@us.ibm.com / space dev as lstack@us.ibm.com...
OK

No files found
```

When I ran ```cf files chocolate-eclair /app/``` I get:

```
Getting files for app chocolate-eclair in org lstack@us.ibm.com / space dev as lstack@us.ibm.com...
OK

.app-management/                             -
.cfignore                                  13B
.git/                                        -
.gitignore                                 36B
.profile.d/                                  -
.project                                  361B
CHANGELOG.md                              112B
License.txt                                69B
Procfile                                   33B
README.md                                 1.4K
app.js                                    1.6K
custom/                                      -
empty.txt                                   0B
launchConfigurations/                        -
lib/                                         -
manifest.yml                              208B
node_modules/                                -
package.json                              461B
precipitation.csv                        12.3K
public/                                      -
runtime.pid                                 3B
vendor/                                      -
views/                                       -

```

As you can see, the file does exist, it just has no content. It would be nice if the message for an empty file was not the same as the message for an empty directory. It is slightly misleading since the file was indeed found, it just had no content.

I am using the the latest release of the CLI (6.19.0+b29b4e0-2016-06-08) on Mac OS X 10.11.3. This is being ran from Terminal. I have attached the output from CF_TRACE just incase this does not fall into the "Simple Bug" category.

[cf-trace.txt](https://github.com/cloudfoundry/cli/files/331876/cf-trace.txt)

**Comment by dkoper** [comment]
Hi @jlstack 

FYI, turns out we have no test environment anymore with DEAs. I have started building a new one to investigate.

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
@SocalNick When we get an empty response (i.e. Content-Length: 0), we print `No files found`.
Is there a way for us to distinguish between file and folder, so we could tailor the message accordingly?

@jlstack Depending on Nick's reply, the best we could do is change the message to something like `Empty file or folder`, which would not be misleading?

**Comment by SocalNick** [comment]
@dkoper is the HTTP status code the same for empty directory and empty file? You could just say `Empty file` as directories in Linux are really just files.

I currently don't have a deployment with DEAs either. The [files api](http://apidocs.cloudfoundry.org/239/files/retrieve_file.html) is only supported by DEA which the foundation has expressed desire to EOL by 2017. Not sure if we should spend any effort here.

**Comment by dkoper** [comment]
Thanks again for bringing this up. We have improved the message.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM
