### ISSUE TITLE
.* in .cfignore is treated as ignore everything.

### ISSUE THREAD

**Issue by rlk833** [cloudfoundry/cli#870]
### Command

cf push

### CLI Version

 6.19.0+b29b4e0-2016-06-08

### Error

We were stepping up from 6.12 to 6.19 and encountered this regression.
We have in our .cfignore  the line 
.*
This worked in 6.12, ignoring all files starting with period, but 6.19 is treating this as ignore ALL files. And we get the message no app files found.

This is a regression and breaks most of our built applications.

### Platform Details

Linux and Windows at least.

### Shell

bash or windows command prompt

**Comment by dkoper** [comment]
Hi @rlk833 

`.*` looks like the right pattern to use for ignoring files starting with a period. We'll take a look.

Regards,
Dies Koper
CF CLI PM

**Comment by nickwei84** [comment]
Looks like this broke between versions 6.13.0 and 6.14.0

**Comment by dkoper** [comment]
This has been fixed in cf CLI 6.20.0.
https://github.com/cloudfoundry/cli#downloads

Thanks for bringing it to our attention!

Regards,
Dies Koper
CF CLI PM
