### ISSUE TITLE
Cant connect in api.ng.bluemix.net with fedora 22

### ISSUE THREAD

**Issue by albertosouza** [cloudfoundry/cli#871]
## Command:
```sh
CF_TRACE=true cf login -a api.ng.bluemix.net
Terminal de API: api.ng.bluemix.net

SOLICITAÇÃO: [2016-06-25T12:36:31-04:00]
GET /v2/info HTTP/1.1
Host: api.ng.bluemix.net
Accept: application/json
Content-Type: application/json
User-Agent: go-cli 6.19.0+b29b4e0 / linux



SOLICITAÇÃO: [2016-06-25T12:36:46-04:00]
GET /v2/info HTTP/1.1
Host: api.ng.bluemix.net
Accept: application/json
Content-Type: application/json
User-Agent: go-cli 6.19.0+b29b4e0 / linux


COM FALHA
Erro ao executar solicitação: Get http://api.ng.bluemix.net/v2/info: dial tcp: i/o timeout
DICA: se você estiver protegido por um firewall e precisar de um proxy HTTP, verifique se a variável de ambiente https_proxy está configurada corretamente. Caso contrário, verifique sua conexão de rede.
```
## Version:
```sh
cf -v
cf version 6.19.0+b29b4e0-2016-06-08
```

**Comment by dkoper** [comment]
This looks like a network issue in your environment. Can you resolve and access the API endpoint using other tools (curl, ping, nslookup)? Is it possible that your primary DNS server was down at the time you ran the command?

**Comment by albertosouza** [comment]
Hi @dkoper , i was in AngelHack BR hackaton in IBM in Rio de Janeiro,

traceroute was not finding the route to the IBM API server in my laptop, now here in my house it is working.
The IBM team failed to solve the problem on site then i openned this issue because i belived that may be one problem related to Clound Foundry but i think may be some local network error.

It is working here in my house and i cant reproduce the problem then i will close this issue.
