### ISSUE TITLE
Unreadable text when using light background terminal 

### ISSUE THREAD

**Issue by verydapeng** [cloudfoundry/cli#873]
### Command

cf, cf logs 

### CLI Version

cf version 6.19.0+b29b4e0-2016-06-08

### CC API Endpoint Version

not relevant 

### CF Trace

not relevant

### Platform Details

Mac OS X 10.11.5 

### Shell

Terminal

![image](https://cloud.githubusercontent.com/assets/2149970/16445013/5ab1a0c4-3e13-11e6-8ba5-15c615f602e4.png)

iTerm2

![image](https://cloud.githubusercontent.com/assets/2149970/16445036/6c1bb796-3e13-11e6-98f6-886b4ea57ebf.png)

**Comment by imod** [comment]
I'm facing the exact same issue... I know I can disable coloring like this:
`CF_COLOR=false cf logs myapp` 
...but thats not very userfrendly 

I also palced the question on SO: http://stackoverflow.com/questions/38091319/useless-cloudfoundry-cli-color-scheme-on-mac/38124377

**Comment by challiwill** [comment]
Hi @verydapeng and @imod, We just tried running some commands in the default iTerm2 (v 3.0.4) 'Light Background' theme and don't notice any usability issues. 

![screen shot 2016-07-01 at 9 38 46 am](https://cloud.githubusercontent.com/assets/1977612/16528137/b95c74e8-3f6f-11e6-949c-238c56c5dadc.png)

We do use bright

**Comment by challiwill** [comment]
Hi @imod and @verydapeng, 

Have you tried updating to the latest version of iTerm2? Let us know how that looks.

**Comment by verydapeng** [comment]
![image](https://cloud.githubusercontent.com/assets/2149970/16548893/8693617c-41ca-11e6-8016-11ae815d5aac.png)

@challiwill I am already using the latest iTerm2 Build 3.0.2, the problem is not only present in iTerm2 but also in the mac builtin Terminal too

**Comment by imod** [comment]
I'm not using iTerm2 - just the buildin Terminal with the "Basic - Default" profile

**Comment by challiwill** [comment]
As a short term solution you can adjust the 'Bright White' color in your terminal profile to a medium grey (perhaps match the 'Normal White').

**Comment by dkoper** [comment]
@verydapeng @imod 
Can you try with the edge release? We've reverted the color to what it was in 6.14.0.

**Comment by verydapeng** [comment]
@dkoper Edge works for me! (cf version 6.20.0+32ef774-2016-07-06)

**Comment by imod** [comment]
yep, edge seems to be fine

**Comment by shouah** [comment]
I didn't experience this issue up to CLI 6.20.0, but with the latest 6.21.0 then I don't see some text. I'm using 64-bits CLI v6.21.0 on 64-bits Windows 7 and in a regular Command Prompt.

Setting "CF_COLOR=false" restore visibility of the text in the command prompt but that's not ideal as the colors really help with quickly reading the output.

**Comment by dkoper** [comment]
@shouah Can you please open a new issue and attach a screen capture?

**Comment by dkoper** [comment]
Closing as the original issue has been fixed in the cf CLI 6.21.0 release. Thanks again for bringing it up.
