### ISSUE TITLE
Error pushing app

### ISSUE THREAD

**Issue by smbyers** [cloudfoundry/cli#874]
High five for submitting a report!
To avoid additional back and forth, please include the following details as relevant:

### Command

cf push

### CLI Version

6.11.3-cebadc9

### Error

runtime error: index out of range

### Stack Trace

goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x2)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:177 +0xa9
	main.handlePanics(0x10c4678, 0xc2100665c0)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/main/main.go:161 +0x123
	runtime.panic(0x570540, 0xe7c917)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/api.(*logNoaaRepository).GetContainerMetrics(0xc210266660, 0xc210bf5690, 0x24, 0xc210950600, 0x1, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/api/logs_noaa.go:68 +0x275
	github.com/cloudfoundry/cli/cf/commands/application.(*ShowApp).ShowApp(0xc210266900, 0xc210bf5690, 0x24, 0xc21029f420, 0x13, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Unit-Tests/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/commands/application/app.go:112 +0x683
	github.com/

### CC API Endpoint Version

API version: 2.54.0

### CF Trace

Error did not occur on subsequent invocation.

### Platform Details

Mac OS X 10.10.5

### Shell

Terminal

**Comment by dkoper** [comment]
Hi @smbyers 

cf CLI 6.11.3 is over 8 months old. I believe this issue has been fixed since. Please try on the latest cf CLI release.

Cheers,
Dies Koper
CF CLI PM

**Comment by smbyers** [comment]
Hey @dkoper 

Will do.  That was the plan but wanted to pass along just in case.  After the initial failure it did not happen again on subsequent pushes.

Thanks

**Comment by dkoper** [comment]
OK. Closing, feel free to re-open if you see it again on a current cf CLI release.
