### ISSUE TITLE
`cf service-brokers` output inconsistent with other CF operations

### ISSUE THREAD

**Issue by APShirley** [cloudfoundry/cli#875]
The output from the `cf service-brokers` command doesn't say `OK` before displaying its results, unlike most other, similar commands in the CLI.

For example:

```
± ap+dl |master ✓| → cf service-brokers
Getting service brokers as admin...

name                                             url
asl-1043879f-1f23-4c37-792a-c1e4fc019715         http://asl-1043879f-1f23-4c37-792a-c1e4fc019715.bosh-lite.runtime-ci.cf-app.com
pblc-brkr-187be2c9-8720-4f0a-6a45-f748150b18bd   http://pblc-brkr-187be2c9-8720-4f0a-6a45-f748150b18bd.bosh-lite.runtime-ci.cf-app.com
```

For comparison:

```
± ap+dl |master ✓| → cf apps
Getting apps in org CATS-persistent-org / space CATS-persistent-space as admin...
OK

name                  requested state   instances   memory   disk   urls
CATS-persistent-app   started           1/1         256M     1G     cats-persistent-app.bosh-lite.com
```

We're on cf version `6.19.0+b29b4e0-2016-06-08`. The trace didn't seem relevant this time around.

Issue Signed-off-by: Jesse Alford jalford@pivotal.io

**Comment by dkoper** [comment]
Is this an issue for you?
I see the inconsistency: `cf orgs`, `cf spaces` also do not display `OK`, `cf apps` and `cf app myapp` on the other hand do.
I don't know if there was a rule at some point, e.g. we should display the result for non-idempotent API calls (in which case `cf app` and `cf apps` break the rule), or we should display the result if the command is an orchestration of multiple actions (like `push`, `map-route` when it creates a non-existing route).
I'd like to understand the impact/benefit to users of changing what we see now.

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
We are incrementally refactoring all CLI commands to ensure consistent styling, that will no longer display `OK` in this particular case.
