### ISSUE TITLE
Unexpected behavior with set-org-role/unset-org-role

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/cli#876]
### Command

precondition: `<user>` is NOT a user of `<org>`
precondition: `<user>` is NOT a OrgManager of `<org>`

`cf set-org-role <user> <org> OrgManager`

result: `<user>` is a user of `<org>`
result: `<user>` is a OrgManager of `<org>`

`cf unset-org-role <user> <org> OrgManager`

expected result: `<user>` is NOT a user of `<org>`
expected result: `<user>` is NOT a OrgManager of `<org>`
result: `<user>` is a user of `<org>`    <== UNEXPECTED
result: `<user>` is NOT a OrgManager of `<org>`

The problem of being left as a user is that when you `cf orgs` (and after successful `cf login`) it will show you also `<org>`, even though you don't have privileges over that org anymore.

### CLI Version

6.20.0

### CC API Endpoint Version

2.39.0

### CF Trace

During set-org-role the CLI adds the user to both /managers and /users
During unset-org-role the CLI only remove from /managers

**Comment by dkoper** [comment]
Hi @CAFxX 

I'd like to look into this further in #781, which I believe describes the same problem.
Closing this one so we have all communication in one place.

Regards,
Dies Koper
CF CLI PM
