### ISSUE TITLE
Route doesn't exist but cf cli thinks it does

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry/cli#883]
High five for submitting a report!
To avoid additional back and forth, please include the following details as relevant:

### Command
```
 2016-07-08 11:45:02 ☆  |2.3.0| lawry in ~/workspace/metrics-data/src/metrics-data/logqueue/build
±  |master U:2 ?:4 ✗| → cf check-route elasticsearch-logqueue metrics12.pcf-metrics.com
Checking for route...
OK
Route elasticsearch-logqueue.metrics12.pcf-metrics.com does exist

 2016-07-08 11:45:06 ☆  |2.3.0| lawry in ~/workspace/metrics-data/src/metrics-data/logqueue/build
±  |master U:2 ?:4 ✗| → cf unmap-route elasticsearch-logqueue metrics12.pcf-metrics.com
FAILED
Route  not found
```

e.g. cf org-users

### CLI Version

```
 2016-07-08 11:45:09 ☆  |2.3.0| lawry in ~/workspace/metrics-data/src/metrics-data/logqueue/build
±  |master U:2 ?:4 ✗| → cf -v
cf version 6.17.1+2ca614d-2016-05-02
```

e.g. 6.13.0-dfba612 (visit the [releases page](https://github.com/cloudfoundry/cli/releases/) and confirm it's reproducible on the latest version)

### Error

See above

### Stack Trace

See above

### CC API Endpoint Version

```
 2016-07-08 11:46:06 ☆  |2.3.0| lawry in ~/workspace/metrics-data/src/metrics-data/logqueue/build
±  |master U:2 ?:4 ✗| → cf api
API endpoint: https://api.acceptance.pcf-metrics.com (API version: 2.56.0)
```

see `cf api` output

### CF Trace

See above

For bugs related to HTTP requests, please run the command with env var `CF_TRACE=true`

### Platform Details

e.g. Mac OS X 10.11, Windows 8.1 64-bit, Ubuntu 14.04.3 64-bit

### Shell

iTerm

e.g. Terminal, iTerm, Powershell, Cygwin, gnome-terminal, terminator

**Comment by dkoper** [comment]
Hi @jadekler

Can you share with us the trace output when running those two commands?

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Closing. Feel free to reopen or submit a new issue if it reoccurs and you can share a trace with us.

**Comment by glyn** [comment]
For the record, this looks like a user error.

The syntax for `cf check-route` is:
```
cf check-route HOST DOMAIN [--path PATH]
```
whereas that for `cf unmap-route` is:
```
cf unmap-route APP_NAME DOMAIN [--hostname HOSTNAME] [--path PATH]
```

So, in this issue, `cf check-route` was issued with:
```
HOST=elasticsearch-logqueue
DOMAIN=metrics12.pcf-metrics.com
(PATH not specified)
```
whereas `cf unmap-route` was issued with:
```
APP_NAME=elasticsearch-logqueue
DOMAIN=metrics12.pcf-metrics.com
(HOSTNAME and PATH not specified)
```
but `HOSTNAME` should have been specified as `elasticsearch-logqueue`.

Note the extra space in the error message `Route  not found`, which presumably means that `HOSTNAME` is not defaulted. (It might have been helpful for `cf` to default `HOSTNAME` to `APP_NAME` to avoid this kind of mistake, but I'm not sure that could be retrofitted without breaking backwards compatibility.)

**Comment by dkoper** [comment]
Thanks @glyn, for setting the record straight :)

I'm thinking of changing all route commands to take one argument ROUTE, like how we support it in app manifest files, but it is indeed the retro-fitting that makes it complicated.
