### ISSUE TITLE
go format missing arguments

### ISSUE THREAD

**Issue by erjoalgo** [cloudfoundry/cli#885]
```Creating service instance my-test in org MYORG / space MYSPACE as me@example.com...
FAILED
Error performing request: Get https://api.system.host.name/v2/spaces/390807ae-647d-4b7a-96a9-05599abc186e/services?q=label%!A(MISSING)my-service: dial tcp: lookup api.system.host.domain: no such host```

command: cf create-service 

cf version 6.19.0+b29b4e0-2016-06-08

**Comment by dkoper** [comment]
We'll take a look!

**Comment by jeffpak** [comment]
Hi @erjoalgo,

I did some investigation into this, but I wasn't able to reproduce this bug from my end. Could you please fill out the template that you get from "New Issue"? I'm particularly interested in your platform/os as well as your CF_TRACE output. Feel free to fill out the rest to the best of your ability.

Thanks!
@jeffpak - CF CLI

**Comment by dkoper** [comment]
Closing as we don't have enough information to proceed.
