### ISSUE TITLE
stack is reported as "unknown" at the end of a push

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cli#887]
### Command

`cf push my-app`

### CLI Version

6.20.0+25b1961-2016-06-29

### Error

At the end of a `cf push`, I get the following output:

```
Showing health and status for app my-app in org my-org / space my-space as me@example.com...
OK

requested state: started
instances: 1/1
usage: 1G x 1 instances
urls: my-app.example.com
last uploaded: Mon Jul 11 17:18:49 UTC 2016
stack: unknown
buildpack: staticfile 1.3.9
```

where stack is "unknown". However, doing the same push with CF_TRACE enabled, many of the responses include either the stack guid or stack resource URL, so the stack can be known immediately.

### CC API Endpoint Version

2.57.0

### Platform Details

Mac OS X 10.11.5

### Shell

iTerm2 3.0.4

**Comment by dkoper** [comment]
Hi Dan! Please follow #799 instead.
