### ISSUE TITLE
Feature request: cf login - fast-fail/no retry option

### ISSUE THREAD

**Issue by abracadv8** [cloudfoundry/cli#890]
Our team has written scripts to automate deployments using the CF CLI.  We ran into an issue where if the login fails (eg, say a bad password), it re-prompts the user to re-enter the login.  

Since this is a script, it would be nice if the login attempt immediately failed and returned instead of prompting for retries.

**Comment by cppforlife** [comment]
alternatively login cmd should not retry asking in non interactive mode.

**Comment by dkoper** [comment]
Have you considered using 'cf auth' as a non-interactive way to log in?

**Comment by challiwill** [comment]
`cf auth` was designed as non-interactive login command for scripting, `cf login` is not intended for use in scripts.

**Comment by abracadv8** [comment]
Doh.  This is exactly what I was looking for!  Thanks!  Feel free to close this!
