### ISSUE TITLE
Installs .cf under root; permission denied error

### ISSUE THREAD

**Issue by dzcarter** [cloudfoundry/cli#891]
I installed the cli on my mac using the .pkg.

It installed the .cf directory in my home directory under root rather than my username:
> drwx------     3 root    staff    102 10 Jul 13:44 .cf

This results in the following error trying to use the cf command:
> FAILED; Error read/writing config:  open /Users/carter/.cf/config.json: permission denied

There are several solutions listed in the following link:
http://stackoverflow.com/questions/35669001/getting-permission-denied-error-when-running-cf-command-on-mac-os-x

If I `sudo chmod +xr` to the folder and `sudo chmod +r` the json file, it seems to work. But this feels hacky. Thoughts?

**Comment by dkoper** [comment]
Hi @dzcarter 

What cf CLI version are you installing? How did you install the .pkg? (GUI or in a shell?)

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Closing. Feel free to reopen or submit a new issue if you can provide us more details.
