### ISSUE TITLE
cf apps returns list of apps in unknown order

### ISSUE THREAD

**Issue by peefourtee** [cloudfoundry/cli#893]
### Command

cf apps

### CLI Version

cf version 6.18.0+b22884b-2016-05-10

We have ~20 apps in a single space.  Running `cf apps` returns all the apps but they don't seem to be sorted in any order in particular.  It would be helpful to have them sorted alphabetically.

**Comment by dkoper** [comment]
Hi @peefourtee 

`cf apps` I believe returns the apps in the order the CC API returns them.
We have requested CAPI to add support for sorting them on the server side.
I believe they have added a query parameter for this in the V3 API, which we intend to use when it's ready. In the meantime, @SocalNick has also indicated they're open to a PR to add such a parameter to the V3 API (see the comment in the following story):
https://www.pivotaltracker.com/story/show/97111908

Feel free to raise the request with CAPI again.

Regards,
Dies Koper
CF CLI PM

**Comment by SocalNick** [comment]
@peefourtee @dkoper - one small correction, we would be open to a PR for the V2 API:

http://apidocs.cloudfoundry.org/238/apps/list_all_apps.html

You can see a similar `order-by` param that was recently added for the list orgs endpoint:

http://apidocs.cloudfoundry.org/238/organizations/list_all_organizations.html

**Comment by dkoper** [comment]
Closing. Thanks for the correction Nick. We'd like to display the apps in sorted order but prefer to wait for CC to provide this functionality.
