### ISSUE TITLE
Manifest inheritance does not correctly override application properties

### ISSUE THREAD

**Issue by ipsi** [cloudfoundry/cli#895]
When attempting to push a manifest with inheritance, the child manifest does not appear to override the properties from the parent. e.g.:

parent:
```
---
applications:
- name: foo
  buildpack: teapot
```

child:
```
---
inherit: parent.yml
applications:
- name: foo
  buildpack: kettle
```

I would expect that pushing the child would result in the buildpack being `kettle`, but it is actually sending `teapot` to the server (see below). Looking at #479, this looks like something that should have been fixed, but it does not appear to be for me.

### Command

`cf push -f child.yml`

### CLI Version

`cf version 6.19.0+b29b4e0-2016-06-08`

### CC API Endpoint Version

`2.54.0`

### CF Trace

```
REQUEST: [2016-07-15T11:29:26+02:00]
POST /v2/apps?async=true HTTP/1.1
Host: api.local.pcfdev.io
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.19.0+b29b4e0 / darwin

{"name":"foo","space_guid":"10404677-f8c7-4ae2-b122-554cf5a24d4e","buildpack":"teapot","environment_json":{}}
```

### Platform Details

`Darwin MacBook-Pro.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64`

### Shell

iTerm, BASH.

**Comment by dkoper** [comment]
Hi @ipsi 

It's not intended to work that way. It should however work with the following parent manifest:
```
---
buildpack: teapot
```

The purpose of the manifest inheritance feature is to allow you to "promote" duplicate content from multiple apps to a parent manifest. Application names are unique, so are not intended to be promoted to the parent manifest.

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Closing. Feel free to reopen or submit a new question if you have follow-up questions.
