### ISSUE TITLE
cf curl fails with an unhelpful error message when no API endpoint is set

### ISSUE THREAD

**Issue by jaresty** [cloudfoundry/cli#896]
When no API endpoint has been set, `cf curl` says `unsupported protocol scheme`.

It should probably say something like this instead:
```
FAILED
No API endpoint set. Use 'cf login' or 'cf api' to target an endpoint.
```

### Command
cf curl

### CLI Version
cf version 6.17.1+2ca614d-2016-05-02

### Error
```
→ cf --version
cf version 6.20.0+25b1961-2016-06-29

→ cf api nonsense
Setting api endpoint to nonsense...
FAILED
Error performing request: Get http://nonsense/v2/info: dial tcp: lookup nonsense: no such host
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

→ cf target
FAILED
No API endpoint set. Use 'cf login' or 'cf api' to target an endpoint.

→ cf curl v2/info
FAILED
Error creating request:
Error performing request: Get /v2/info: unsupported protocol scheme ""
```

### Platform Details

e.g. Mac OS X 10.11.3

### Shell
iTerm2

Issue Signed-off-by: Jesse Alford <jalford@pivotal.io>

**Comment by dkoper** [comment]
Thanks , also for proposing a better message!

**Comment by dkoper** [comment]
Thanks again for bringing this up. This should be fixed now.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM
