### ISSUE TITLE
Jar size is twice what it should be on upload

### ISSUE THREAD

**Issue by MTyson** [cloudfoundry/cli#898]
I have a standalone jar with deps that on disk is around 26 megs:

`-rw-r--r-- 1 Matt Administ 26066171 Jul 18 17:54 new-app-1.0.0.jar`

However, when I go to upload, the size has exploded to 56 megs:

```
Uploading app files from: target\new-app-1.0.0.jar
Uploading 52.5M, 17765 files
```

Is the build_pack or CF actually unpacking the jar to upload it? Or am I missing something else?

**Comment by dkoper** [comment]
Hi @MTyson 

I believe the cli unpacks the jar locally and sends a list of files within to CC for "resource matching". If you pushed the app before and there are big files within that haven't changed, CC will detect that and the CLI will exclude them from the upload.
Not sure if the CLI is reporting the size and count of the files after unpacking, but still sending them repacked - would that explain the reported size?
We'll take a look.

**Comment by MTyson** [comment]
@dkoper I see what you are saying.  From what I can tell, it is sending them unpacked, because while uploading it counts all the way up to 52m:

`10.6M uploaded....`

All the way up.

**Comment by MTyson** [comment]
I should also mention that the caching mechanism doesn't seem to be working.  If I make a change to the manifest.yml, there seems to be no way to apply those changes (restage doesn't do it), and I have to cf push the whole app again, and the entire 52 megs is again

**Comment by dkoper** [comment]
Note that only files of a certain size are cached by the cloud controller (see #168).

**Comment by dkoper** [comment]
Thanks again for bringing this up. We have fixed it in the current release.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM
