### ISSUE TITLE
If an error occurs while creating a buildpack, an entry is still created in `cf buildpacks`

### ISSUE THREAD

**Issue by Dannyzen** [cloudfoundry/cli#899]
High five for submitting a report!
To avoid additional back and forth, please include the following details as relevant:

### Command
```
touch foo
cf create-buildpack test foo 1
```

### CLI Version

cf version 6.18.0+b22884b-2016-05-10

### Error

```
Uploading buildpack test...
FAILED
Couldn't write zip file: zip: not a valid zip file
------------------------------------------------------------
~/testing/buildpack_tomfoolery » cf create-buildpack test . 1                                                                                                 
Creating buildpack test...
OK
Buildpack test already exists
TIP: use 'cf update-buildpack' to update this buildpack
```

### CC API Endpoint Version
https://api.local.pcfdev.io

### Platform Details
Linux beKind 4.2.0-34-generic #39-Ubuntu SMP Thu Mar 10 22:13:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### Shell
`zsh` / konsole

**Comment by dkoper** [comment]
Thanks @Dannyzen . It seems we're checking if the zip file is valid after creating the buildpack, during the upload phase. We could try and put it before the creation.

**Comment by dkoper** [comment]
Thanks again for bringing this up. This should be fixed now.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM
