### ISSUE TITLE
Is it reasonable to return an error when run "cf update-buildpack" with no option?

### ISSUE THREAD

**Issue by David-Pivotal** [cloudfoundry/cli#904]
Current design is doing nothing when run "_cf update-buildpack_" with no option.  You can see when I tried _update-buildpack  buildpack_name_ it succeeded. So is it reasonable to say this should give an error instead of doing nothing? 

`ubuntu@pivotal-ops-manager:~$ cf update-buildpack david_binary_buildpack
Updating buildpack david_binary_buildpack...
OK
ubuntu@pivotal-ops-manager:~$ `

### CLI Version
cf version 6.14.1+dc6adf6-2015-12-22

**Comment by dkoper** [comment]
Interesting question.
I suppose it depends on what you wanted to do.
What if you did pass an argument, e.g. `cf update-buildpack java_buildpack -i 1` where the java buildpack was already at position one. Should it give an error?

Looking at other update commands (`update-quota`, `update-service`, `update-user-provided-service`) I see none return an error, althought some return a message `no changes were made`.
I see no benefit in changing these commands to return an error. At most we could look at providing a consistent UX, where `update-user-provided-service` seems to have the best one.

**Comment by David-Pivotal** [comment]
Thank you for your information. I will check with end user and get back to you soon.

**Comment by David-Pivotal** [comment]
Thanks for your help. Please feel free to close this issue.
