### ISSUE TITLE
"cf login" should exit with an error against invalid user name

### ISSUE THREAD

**Issue by David-Pivotal** [cloudfoundry/cli#905]
"-p" is not valid user name which is expected. Current design is when "cf login" with user name "-p", it waits for a password. Is it reasonable that "cf login" should exit with an error rather than asking for a password?

`Daivd-Office-Mac:~ ubuntu$ cf login -u -p
API endpoint: https://api.run.pivotal.io

Password> 
Authenticating...
Credentials were rejected, please try again.

Password> Daivd-Office-Mac:~ ubuntu$ 
Daivd-Office-Mac:~ ubuntu$ `

### CLI Version
cf version 6.14.1+dc6adf6-2015-12-22

**Comment by dkoper** [comment]
I don't know whether `-p` is a valid username or not, and whether this may change in the future.
We try not to hard-code validation rules in the CLI where we can avoid it, and let the backend (UAA in this case) be the judge. Sounds reasonable?

**Comment by David-Pivotal** [comment]
Thank you for your information. I will check with end user and get back to you soon.

**Comment by David-Pivotal** [comment]
Thanks for your help. Please feel free to close this issue.
