### ISSUE TITLE
wrong 'cf.exe' bitness

### ISSUE THREAD

**Issue by shouah** [cloudfoundry/cli#907]
Since release v6.20.0 the "windows 64-bit" installer is installing a 32-bit "cf.exe" file, this issue is also present in the latest v6.21.0 release -- I have to replace it with the 64-bit "cf.exe" that is provided in the "Windows 64 bit binary" download. 

Here are the stats for v6.21.0 64-bits windows installer download:

>sha1sum cf-cli-installer_6.21.0_winx64.zip
edf381d6483b0bc3a265f4827d43daf321a2f179 *cf-cli-installer_6.21.0_winx64.zip

>sha1sum cf_installer.exe
a7db0ed24ecd3c80af54852350e4d4c116c54376 *cf_installer.exe

Shouldn't the 64-bits download of the installer installs a 64-bit "cf.exe" binary? or is this 32-bit "cf.exe" intentional?

**Comment by dkoper** [comment]
@shouah Thanks! That is not intentional, we'll take a look.

**Comment by dkoper** [comment]
@shouah We've updated the Windows 64 bit installer for 6.21.0, still working on the older versions.

**Comment by shouah** [comment]
thank you
