### ISSUE TITLE
Invisible text with CLI v6.21.0

### ISSUE THREAD

**Issue by shouah** [cloudfoundry/cli#908]
High five for submitting a report!
To avoid additional back and forth, please include the following details as relevant:

### Command
cf logs [app_name]
cf logs [app_name] --recent

### CLI Version
cf version 6.21.0+dff2cf8-2016-07-27

### Error
With output coloring enabled, certain text are invisible / unreadable. Disabling color restore the display. See attached screenshot.

![invisible_text](https://cloud.githubusercontent.com/assets/13908947/17197274/f69c4a56-5430-11e6-8c82-bd4df0744219.jpg)

This display problem was not experienced with previous 6.20.0 version

### Stack Trace
N/A

### CC API Endpoint Version
[confidential]

### CF Trace
N/A

### Platform Details
Windows 7 Enterprise 64-bits

### Shell
Windows Command Prompt

**Comment by shouah** [comment]
For completeness, here is a screenshot from the previous CLI which shows that this issue was not present and hence 6.21.0 broke it (maybe the fix to issue #873 ?)

![cf620_visible_text](https://cloud.githubusercontent.com/assets/13908947/17216730/6d4e2a04-54a7-11e6-9b37-703685b68982.jpg)

**Comment by dkoper** [comment]
@shouah Thanks, I was able to reproduce it. We'll take a look and make sure it's fixed in the next release.

**Comment by dkoper** [comment]
Thanks again for bringing this up. This should be fixed now.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM
