### ISSUE TITLE
crash on cf login to http://localhost:8080/api

### ISSUE THREAD

**Issue by erjoalgo** [cloudfoundry/cli#912]
I get this when trying to login, my localhost:8080/api is running a mocked cf api from 
https://github.com/cloudfoundry/uaa

CF_TRACE=true cf login -a  http://localhost:8080/api -u marissa -p koala
API endpoint: http://localhost:8080/api

REQUEST: [2016-08-03T14:44:20-07:00]
GET /api/v2/info HTTP/1.1
Host: localhost:8080
Accept: application/json
Content-Type: application/json
User-Agent: go-cli 6.19.0+b29b4e0 / linux

	Something unexpected happened. This is a bug in cf.

	Please re-run the command that caused this exception with the environment
	variable CF_TRACE set to true.

	Also, please update to the latest cli and try the command again:
	https://github.com/cloudfoundry/cli/releases

	Please create an issue at: https://github.com/cloudfoundry/cli/issues

	Include the below information when creating the issue:

		Command
		cf login -a http://localhost:8080/api -u marissa -p koala

		CLI Version
		6.19.0+b29b4e0

		Error
		runtime error: index out of range

		Stack Trace
			goroutine 1 [running]:
	main.generateBacktrace(0x0, 0x0)
		/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/main/main.go:189 +0xb4
	main.handlePanics(0x7f3eca1c4640, 0xc8201f9320, 0x7f3eca1c4600, 0xc8201ccb00)
		/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/main/main.go:173 +0x22f
	panic(0xcb5ca0, 0xc82000e160)
		/usr/local/go/src/runtime/panic.go:443 +0x4e9
	github.com/cloudfoundry/cli/cf/net.getBaseDomain(0xc8204ec240, 0x1f, 0x0, 0x0)
		/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/net/http_client.go:106 +0x138
	github.com/cloudfoundry/cli/cf/net.(*client).checkRedirect(0xc820196b20, 0xc8203e82a0, 0xc820178108, 0x1, 0x1, 0x0, 0x0)
		/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/net/http_client.go:53 +0x1b7
	github.com/cloudfoundry/cli/cf/net.(*client).(github.com/cloudfoundry/cli/cf/net.checkRedirect)-fm(0xc8203e82a0, 0xc820178108, 0x1, 0x1, 0x0, 0x0)
		/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/cli/cf/net/http_client.go:38 +0x56
	net/http.(*Client).doFo

		Your Platform Details
		 $lsb_release -a
		 No LSB modules are available.
		 Distributor ID:	Debian
		 Description:	Debian GNU/Linux 8.4 (jessie)
		 Release:	8.4
		 Codename:	jessie

		Shell
		 echo $SHELL
		 /bin/bash

**Comment by dkoper** [comment]
Hi @erjoalgo 

We only support API endpoints of the form `api.example.com`. We'll improve the error message as part of #865.

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Closing. Although we don't support this, it may actually now work due to some unrelated changes of the code that was failing above.
