### ISSUE TITLE
Security request - digitally signed executable on Windows platform

### ISSUE THREAD

**Issue by shouah** [cloudfoundry/cli#913]
On the Windows platform, the installer for the CLI ("cf_installer.exe") is digitally signed by "Cloudfoundry.org Foundation, Inc".

For security concern, and to prevent tempering as well as ensuring authenticity, we'd also want the CLI itself ("cf.exe") to be digitally signed. This should be feasible with minimal disruption to your continuous integration process given that you are already doing it for the installer.

An example is that the previous version 6.20.0 was incorrectly flagged as infected and therefore we were unable to download it. Here is a screenshot from that time period:

![cli_blocked_av](https://cloud.githubusercontent.com/assets/13908947/17420381/e9b95aa8-5a67-11e6-91aa-77545e8272b6.jpg)

**Comment by dkoper** [comment]
Hi @shouah 

Thanks for raising this! We're working on it.

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Thanks again for bringing this up. Windows binaries are now signed.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM

**Comment by konklone** [comment]
Did something break here? It looks like neither the installer, nor the `cf.exe` binary inside it, are signed. This is causing some significant friction with installation in our environment.

**Comment by dkoper** [comment]
@konklone More details please? I just downloaded [the Windows 64 bit v6.23.1 installer](https://cli.run.pivotal.io/stable?release=windows64&version=6.23.1&source=github-rel) and both installer and binary appear signed.

**Comment by konklone** [comment]
My apologies, @dkoper -- we made a mistake while checking the signature of both files, and things look fine.

**Comment by dkoper** [comment]
@konklone No worries. Thanks for the quick reconfirmation!
(And glad to hear this feature has been useful to you!)

**Comment by mogul** [comment]
Well, it's enabling us to make the case that our environment should not be restricting its use. However, there's still a policy config somewhere that is causing it to be flagged and restricted when signed installers shouldn't be. If we find a problem whose resolution might generally help others using the CF CLI and installer in a restricted environment, we'll be sure to let you know.
