### ISSUE TITLE
“cf ssh" hang in cygwin

### ISSUE THREAD

**Issue by alicejiezhao** [cloudfoundry/cli#914]
CLI Version: 6.18.0+b22884b-2016-05-10

In cygwin, 'cf ssh' just hang. 

```
$ cf auth admin b306063fcdf9d27154c6
API endpoint: https://api.system.azhao.com
Authenticating...
OK
Use 'cf target' to view or set your target org and space

alice@Public-PC ~
$ cf target -o gss-apj

API endpoint:   https://api.system.azhao.com (API version: 2.43.0)
User:           admin
Org:            gss-apj
Space:          development

alice@Public-PC ~
$ cf ssh cook1
```

In the same windows, dos command line, 'cf ssh' works. 

```
C:\Users\alice>cf login -a https://api.system.azhao.com -u admin -p b306063fcdf9
d27154c6 --skip-ssl-validation
API endpoint: https://api.system.azhao.com
Authenticating...
OK

Select an org (or press enter to skip):
1. system
2. gss-apj
3. MySQLATS-ORG-1-2016_04_08-00h44m31.429s
4. CATS-persistent-org
5. CATS-ORG-1-2016_04_08-01h51m09.218s
6. CATS-ORG-2-2016_04_08-01h51m09.217s
7. p-spring-cloud-services

Org> 2
Targeted org gss-apj

Targeted space development



API endpoint:   https://api.system.azhao.com (API version: 2.43.0)
User:           admin
Org:            gss-apj
Space:          development

C:\Users\alice>cf ssh cook1
vcap@ib2acg2jbnr:~$
```

There're 'cf login' issues in cygwin reported here:
https://github.com/cloudfoundry/cli/issues/171
https://github.com/cloudfoundry/cli/issues/347

**Comment by dkoper** [comment]
Hi @alicejiezhao 

I tried on my Windows 7 box with `cf version 6.21.0+dff2cf8-2016-07-27` in Cygwin Bash (`GNU bash, version 4.3.42(4)-release (x86_64-unknown-cygwin)`) and I can `cf ssh` fine into my application.
Can you try with the latest cf CLI in cygwin (are you sure it's picking up the same version as is picked up in the command prompt?) Could there be some kind of DNS configuration issue in your cygwin environment?

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Closing. Feel free to reopen or submit a new issue if you can provide us enough details to investigate.
