### ISSUE TITLE
cf unbind-service & cf delete-space  response queued!

### ISSUE THREAD

**Issue by hjzhu** [cloudfoundry/cli#915]
High five for submitting a report!
To avoid additional back and forth, please include the following details as relevant:
### Command

cf unbind-service ;cf delete-space
### CLI Version

cf version 6.21.0+dff2cf8-2016-07-27
### Error

response queued
### CC API Endpoint Version

cf-release 237(API version 2.56.0)
### CF Trace
```
root@bosh:~# CF_TRACE=true cf unbind-service 333 testmysql01

RESPONSE: [2016-08-06T00:32:16+08:00]
HTTP/1.1 200 OK
Connection: close
Content-Length: 270
Content-Type: application/json;charset=utf-8
Date: Fri, 05 Aug 2016 08:32:20 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: ac1f3f31-c78b-4963-6256-0c363a0b8e2e
X-Vcap-Request-Id: ac1f3f31-c78b-4963-6256-0c363a0b8e2e::ed61d8fc-ed2a-4c75-8984-a80704b10fdf

{
  "metadata": {
    "guid": "7b6bc518-e710-498d-8954-b389a18e3808",
    "created_at": "2016-08-05T08:32:05Z",
    "url": "/v2/jobs/7b6bc518-e710-498d-8954-b389a18e3808"
  },
  "entity": {
    "guid": "7b6bc518-e710-498d-8954-b389a18e3808",
    "status": "queued"
  }
## }

CF_TRACE=true cf delete-space 3

RESPONSE: [2016-08-06T00:33:38+08:00]
HTTP/1.1 200 OK
Connection: close
Content-Length: 270
Content-Type: application/json;charset=utf-8
Date: Fri, 05 Aug 2016 08:33:41 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: f2911dd0-37e9-49b6-7c22-67ca455a06b2
X-Vcap-Request-Id: f2911dd0-37e9-49b6-7c22-67ca455a06b2::026589ba-418f-450a-a31b-5eb7b3e25c58

{
  "metadata": {
    "guid": "c2c65cf6-ee14-45f5-b813-91db61c4faf7",
    "created_at": "2016-08-05T08:33:36Z",
    "url": "/v2/jobs/c2c65cf6-ee14-45f5-b813-91db61c4faf7"
  },
  "entity": {
    "guid": "c2c65cf6-ee14-45f5-b813-91db61c4faf7",
    "status": "queued"
  }
}
```
### Platform Details

ubuntu14.04 LTS
### Shell

Terminal,SSH Secure Shell

**Comment by dkoper** [comment]
@hjzhu What is the full output of the cf CLI (without trace)?

@SocalNick The apidocs for this API don't say much about jobs. What would you expect a CC API consumer like the cf CLI to do with this response?

**Comment by SocalNick** [comment]
@dkoper could someone on your team ping our interrupt pair to help debug?

**Comment by hjzhu** [comment]
@dkoper  hi，thanks for your reply.the full output is as follows without trace(e.g.  cf unbind-service)
#cf services
name          service        plan   bound apps   last operation
testmysql01   Mysql-docker   125M   333          create succeeded

#cf unbind-service 333 testmysql01
Unbinding app 333 from service testmysql01 in org lli003@126.com-org / space 2 as lli003@126.com...

---------------------------------------------------------------------------------
it will be queueing and no other output in a long time.

**Comment by XenoPhex** [comment]
Hi @hjzhu we are closing this request due to inactivity.
