### ISSUE TITLE
cf set-space-role fails with V6.20 against CF 235

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/cli#916]
High five for submitting a report!
To avoid additional back and forth, please include the following details as relevant:

### Command

cf set-space-role <user> <org> <space> SpaceDeveloper

### CLI Version

Fails with v6.20
Works with v6.13 and below.

### Error

Server error, status code: 501, error code: 20005, message: The UAA endpoint needed is disabled
### CC API Endpoint Version

API version 2.54.0

### CF Trace

Unavailable

### Platform Details

Linux

### Shell

BASH

**Comment by dkoper** [comment]
Hi @andrew-edgar 

Could you give us the output of `cf feature-flags`?

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Also, are you running it as an admin? Or a non-admin with SpaceManager role on that space?
Can you include the trace when running it with cf 6.13.0?

**Comment by XenoPhex** [comment]
When we investigated where this error comes from, we found that it appears is returned from the CC when it gets a targeting error from it's UAA client while looking up the user.

Do other commands that require a user work, or is it just the `set-space-role`? Given the code path that this goes through we think it's more likely that this is a problem with the CC->UAA interaction rather than CLI->CC.

**Comment by dkoper** [comment]
Closing. Feel free to reopen or submit a new issue when ready to provide more details.

**Comment by gcoon151** [comment]
cli version 6.22.1+6b7af9c-2016-09-24
cf version 235. 

user_org_creation was disabled but I just enabled it for this account and it still failed

Current output: 
Features                               State
user_org_creation                      enabled
private_domain_creation                enabled
app_bits_upload                        enabled
app_scaling                            enabled
route_creation                         enabled
service_instance_creation              enabled
diego_docker                           disabled
set_roles_by_username                  enabled
unset_roles_by_username                enabled
task_creation                          disabled
space_scoped_private_broker_creation   enabled
space_developer_env_var_visibility     enabled

The part that probably matters most from the trace at the end 

Assigning role OrgManager to user adminuser@us.domain.com in org USERNAME@us.domain.com ...

REQUEST: [2016-09-30T15:47:32-05:00]
PUT /v2/organizations/bf30ce47-1c88-4d76-9011-7db99b3b8778/managers HTTP/1.1
Host: api.customer1.eu-gb.mydomain.net
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Connection: close
Content-Type: application/json
User-Agent: go-cli 6.22.1+6b7af9c / linux

{"username": "adminuser@us.domain.com"}

RESPONSE: [2016-09-30T15:47:32-05:00]
HTTP/1.1 501 Not Implemented
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json
Date: Fri, 30 Sep 2016 20:46:31 GMT
Server: nginx
X-Backside-Transport: FAIL FAIL
X-Content-Type-Options: nosniff
X-Global-Transaction-Id: 147218189

76
{
  "code": 20005,
  "description": "The UAA endpoint needed is disabled",
  "error_code": "CF-UaaEndpointDisabled"
}

0

FAILED
Failed assigning org role to user: Server error, status code: 501, error code: 20005, message: The UAA endpoint needed is disabled

**Comment by gcoon151** [comment]
Command I was running was cf create-org USERNAME@us.domain.com

**Comment by gcoon151** [comment]
The only place in UAA code I see this can be thrown is here: 
https://github.com/cloudfoundry/uaa/blob/85fbe8ee080c50a86ac2f90fcdc705e3db6e82eb/client-lib/src/main/java/org/cloudfoundry/identity/client/UaaContextFactory.java

Line 185. Looking in to why this would happen in my env.

**Comment by sagar20896** [comment]
I get this issue even with 6.13.0 or 6.12.4

**Comment by gcoon151** [comment]
Fix for me was -- 
userids_enabled: true
