### ISSUE TITLE
Failed to start application with 0 instances.

### ISSUE THREAD

**Issue by jfmyers9** [cloudfoundry/cli#917]
### Command

`cf stop app-name && cf scale app-name -i 0 && cf start app-name`

### CLI Version

v6.21.0

### Error

It waits for an instance to start until a timeout, but there are 0 instances so it never succeeds.

### CC API Endpoint Version

2.43.0

### Platform Details

Linux, OSX

### Shell

terminator, gnome terminal, iterm

**Comment by dkoper** [comment]
Hi @jfmyers9 

I think we can suppress polling the app instance state if the app is scaled to 0 instances. We'll take a look.

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Thanks again for bringing this up. We have addressed it in the current release.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM
