### ISSUE TITLE
unhelpful error message binding app/instance in different spaces

### ISSUE THREAD

**Issue by erjoalgo** [cloudfoundry/cli#918]
```sh
cf curl /v2/service_bindings\
		    -X POST\
		    -d '{"service_instance_guid" : "guid-in-space-a"',\
                        "app_guid" : "guid-in-space-b"}'
```

{u'code': 10001, u'error_code': u'UnknownError', u'description': u'An unknown error occurred.'}

$ cf -v
cf version 6.15.0+fa1bfe2-2016-01-13

**Comment by XenoPhex** [comment]
Have you tried updating to the latest version of `cf` to see if you get the same error?

**Comment by erjoalgo** [comment]
actually, this is not an issue with the cli, the message comes back from the api. I wasn't using `cf bs` but `cf curl`. Could you move this issue to the api?

**Comment by XenoPhex** [comment]
The API is handled by a separate team/separate github project so I can't move it over myself. Anything else I could do would be just straight copy/paste, but then it would look like I filed the ticket.

It would be easier for you to get the help you need if you moved it over yourself. Here's the project: https://github.com/cloudfoundry/cloud_controller_ng
