### ISSUE TITLE
`cf login` should allow reading password from filename or file descriptor

### ISSUE THREAD

**Issue by avarner** [cloudfoundry/cli#919]
```
$ cf login --help
...
WARNING:
   Providing your password as a command line option is highly discouraged
   Your password may be visible to others and may be recorded in your shell history
...
```

Non-interactive processes need good security, too. I'd suggest a "-P" parameter that accepts a filename (or a file descriptor number), which cf will open, and read until it reaches EOF, and use that as the password.

Right now, I have a script running on a mostly-single-purpose box, which runs non-interactive cf commands, and issues the password on the command line, using the "-p" option. The command line of a process is **visible to all processes**, so if I want to put this script on a general automation box, other people may look at the password, by running `cat /proc/$PID/cmdline  | tr '\0' '\n'`

```
$ cf --version
cf version 6.21.0+dff2cf8-2016-07-27
```

Platform: Debian Jessie (stable)
Shell: GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)
Terminal: MATE Terminal 1.10.1

**Comment by dkoper** [comment]
Hi @avarner 

UAA team is working on long-lived revokable tokens, which is the solution we want to go to. The cf CLI will be enhanced to make use of them, precisely for the use case you described.

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
We're working on proper documentation. Until then, refer to the following notes, for use with cf CLI 6.23.0+:

This topic covers how to automate CF CLI access. A typical example is a script or a pipeline to push other apps and services. It could be any app that you write which needs to use the [Cloud Foundry API](https://apidocs.cloudfoundry.org/). It needs access your resources without your presence and is non-interactive. Hardcoding your username and password is not a security best practice. Instead you can embed the offline token, which is essentially a refresh token associated with the OAuth Client that you register for your App or Script.

Please follow the steps below to accomplish this

### Step 1:  Create an OAuth Client for your App/Pipeline/Script

This is accomplished by using the [UAAC](https://github.com/cloudfoundry/cf-uaac) (UAA Command Line Utility).

The commands needed are listed below:

```sh
uaac client add -i
Client ID:  automation_client
New client secret:  ****
Verify new client secret:  ****
scope (list):  cloud_controller.read cloud_controller.write
authorized grant types (list):  password
authorities (list):   <enter>
access token validity (seconds): <enter>  
refresh token validity (seconds):  2592000
redirect uri (list):  <enter>  
autoapprove (list):  <enter>  
signup redirect url (url):  <enter>
```
**Note:** This command can only be executed if you are logged as a user or a client with permission of `clients.admin`

This will create a client an OAuth Client with refresh token validity of 30 Days.

### Step 2 : Create a Refresh Token for Offline Access 

Use `uaac` to get the refresh token.  

1.	Run uaac token sso get
2.	Enter the Client ID and Secret
3.	Perform your authentication in the browser and enter the passcode in UAAC
4.	Run uaac context
5.	Copy the value of the refresh token and enter that along with Client ID and Secret in the ~/.cf/config.json file of cf CLI 6.23.0+ ("see UAAOAuthClient", "UAAOAuthClientSecret" & "RefreshToken")

**Note:** Be careful not to run the `cf login` or `cf auth` commands after the modification of config.json.

### Step 3 : Revoking Access for your Apps using the Offline Tokens

This can be achieved by changing the OAuth Client Secret. Deleting the OAuth Client has the same effect.

**Comment by dkoper** [comment]
The steps above are now supported in cf CLI 6.23.0.
https://github.com/cloudfoundry/cli#downloads

Regards,
Dies Koper
CF CLI PM

**Comment by bleach** [comment]
@dkoper it's great to see that you're considering the use case of CI servers. We've been thinking about this [and wrote some guidance for our users based on our knowledge of how it works currently](https://government-paas-developer-docs.readthedocs.io/en/latest/deploying_apps/jenkins/)

Am I right in thinking that the refresh token would need to be renewed by a person every 30 days? This doesn't feel too dissimilar to how it worked if someone shelled onto the CI server and ran `cf login` each time the login session expired :)

**Comment by mwdb** [comment]
tokens can also be revoked by
uaac curl  https://login.XXX/oauth/token/revoke/client/<client id>

**Comment by dkoper** [comment]
@bleach Sorry for the late reply, for some reason GitHub doesn't always sends me an email on updates.

CC'ing @sreetummidi 
The refresh token would only need to be renewed every so many days. The key advantage is the "so many days":
You can have the tokens for "normal" CLI users expire after e.g. a day, while the long lived tokens can be configured to expire after e.g. 30 or 90 days. And during this time, as @mwdb pointed out, you can revoke the token if need be without needing to change your password.
