### ISSUE TITLE
Better "cf push" error message when omitting the app name

### ISSUE THREAD

**Issue by jbayer** [cloudfoundry/cli#920]
### Command

cf push

### CLI Version

cf version 6.17.0+5d0be0a-2016-04-15

### Error

`Manifest file is not found in the current directory, please provide either an app name or manifest`

### CC API Endpoint Version

API endpoint: https://api.run.pivotal.io (API version: 2.58.0)

### Platform Details

Mac OS X 10.11.6

### Shell

iTerm

### Details

an new user i was observing tried the static buildpack example from the docs, which was not very complete. the command recommended is `cf push -m 64m`. this will fail because it omits either an APPNAME or there is no `manifest.yml` in the directory. however, the error message does not indicate that the `push` command fails because it is missing the app name. [rather it focuses on the missing manifest](https://gist.github.com/jbayer/f4d6ca25b639f0674835d5a422f6e74b#file-cf-cli-output-txt-L3).

an improved error message in this case would be something like other commands like delete:

`Incorrect Usage. The push command requires an app name. The app name can be supplied as an argument or with a manifest.yml file.`

**Comment by dkoper** [comment]
Sounds like a great UX improvement, thanks for reporting!

**Comment by dkoper** [comment]
Thanks again for bringing this up. We have addressed it in the current release.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM

**Comment by jbayer** [comment]
great news! i look forward to trying it out.
