### ISSUE TITLE
[feature request] cf-cli allows client authentication grant type

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry/cli#925]
In some cases (such as PWS), clients have greater authentication scopes than users. It'd be extremely nice if the cf-cli supported this by allowing a user to specify a client_id/client_secret.

Note: some actions - such as creating security groups - require highly elevated scopes such as `cloud_controller.admin`.

**Comment by dkoper** [comment]
Hi @jadekler 

FYI, I'm approaching the UAA PM to check their roadmap and ensure we're aligned.

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
We have scheduled this as part of #881. I'll update that issue when the feature is available in a release.
