### ISSUE TITLE
Present plugin's stderr user.

### ISSUE THREAD

**Issue by squeedee** [cloudfoundry/cli#928]
### Command

e.g. cf myplugin somethig-that-doesnt-work 

### CLI Version

 6.21.0+dff2cf8-2016-07-27

### Error

Command does not output stderr message _myplugin_

### Platform Details

e.g. Mac OS X 10.11.6

### Shell
iTerm 2

**Comment by dkoper** [comment]
Hi @squeedee 

Would you mind trying it out with the latest to see if the issue is resolved?

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Thanks again for bringing this up. We have addressed it in the current release.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM
