### ISSUE TITLE
Lines prefixed with '!' in .cfignore are ignored

### ISSUE THREAD

**Issue by jmcvea** [cloudfoundry/cli#932]
### Description
The capability to override a previous exclusion rule in the `.cfignore` file doesn't seem to be working in the latest cf release.  The capability to include a line prefixed with '!' in the `.cfignore` file to identify globs to be included was supposed to be part of a previous commit (https://github.com/cloudfoundry/cli/commit/6f233d42cd3dbb1c21c6a803f654fc6c235537ff.

I can see in the latest source that there is still code in place to look for lines that start with '!' and there are tests which should verify that the functionality works as expected.

### Command
`cf push` (with .cfignore file)

### CLI Version
`cf version 6.21.1+6fd3c9f-2016-08-10`

### Error

Example directory structure for an app pushed to CF:

    myapp/
    +-- .cfignore
    +-- app.js
    +-- package.json
    +-- node_modules/
    +-- ignoreme/
        +-- dontPush.txt
        +-- pushMe.txt

Using the app structure above, the .cfignore file can contain:

    node_modules/
    ignoreme/
    !ignoreme/pushMe.txt

When pushing the app in this directory, the entire `ignoreme` folder is not pushed.  The expectation is that the `ignoreme/pushMe.txt` file will be pushed, but not the `ignoreme/dontPush.txt` file.  Output from the `cf files` command where I would expect to find the `ignoreme` folder

    $ cf files myapp app/
    Getting files for app myapp in org MyOrg / space repro as user1...
    OK
    
    .profile.d/                                  -
    app.js                                    247B
    cftrace.txt                              13.2K
    node_modules/                                -
    package.json                              249B
    vendor/                                      -

### Stack Trace
n/a

### CC API Endpoint Version
2.54.0

### CF Trace
see attached [cftrace.txt](https://github.com/cloudfoundry/cli/files/424029/cftrace.txt)
 file

### Platform Details
Mac OS X 10.11.6

### Shell
iTerm2 (Build 3.0.4)
zsh

**Comment by dkoper** [comment]
Hi @jmcvea 

Are you aware of a cf CLI release where your example `.cfignore` did work?

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
It should work if you add a *:
```
node_modules/*
ignoreme/*
!ignoreme/pushMe.txt
```
Please try.

**Comment by dkoper** [comment]
Closing, I believe the answer above resolves the issue.
