### ISSUE TITLE
CliCommandWithoutTerminalOutput returns VCAP_SERVICES output now split over multiple lines

### ISSUE THREAD

**Issue by jthomas** [cloudfoundry/cli#933]
This is related to the regression raised in https://github.com/cloudfoundry/cli/issues/866, which has stopped the https://github.com/jthomas/copyenv from working.

I think I've found the issue that the previous output from this command had the entire VCAP_SERVICES output within a single string in the output array, whereas now each field line within the JSON string is returned as a new line.

The returned output array now contains:
[..., '"VCAP_SERVICES": {', '"alertnotification": [...' 
rather than
[..., '"VCAP_SERVICES": {\n"alertnotification": [...'

In the plugin code, I was matching the output for the VCAP_SERVICES word to find the output line with the JSON for VCAP_SERVICES to parse. This now fails because that line doesn't contain the full VCAP_SERVICES JSON.

https://github.com/jthomas/copyenv/blob/master/copyenv.go#L45-L59

Is there a way to retrieve the VCAP_SERVICES env vars through the new plugin CLI? I can't find a way to do this. It would be preferable and less brittle than having to re-work my plugin to extract the JSON from the new terminal output format.

**Comment by dkoper** [comment]
Hi @jthomas 

From your report I'm not sure you're reporting a new regression, something that used to work many versions ago but not anymore, or just asking a question. I've asked my devs to take a look at your question in the final sentence of the report.

Regards,
Dies Koper
CF CLI PM

**Comment by jthomas** [comment]
It's both a regression and a question :) 

If I can find out about retrieving the VCAP_SERVICES env var another way, it'll make my issue redundant though!

**Comment by XenoPhex** [comment]
Is there any reason you can't call cf curl on `/v2/apps/:guid/env` and join on the rest of the output? Here's the [API Doc](http://apidocs.cloudfoundry.org/240/apps/get_the_env_for_an_app.html) for the endpoint, I believe it should give you exactly what you're looking for as it'll be raw JSON output which you can parse directly.

**Comment by dkoper** [comment]
Closing, as I believe the question was answered.
