### ISSUE TITLE
Passing user provided service parameters as JSON does not work on Windows

### ISSUE THREAD

**Issue by mayrstefan** [cloudfoundry/cli#934]
When I want to create or update a user provided service with a JSON string this does not work in Windows 7 (cmd.exe). The same command works on Linux and even on the same Windows host in the MINGW64 (mintty?) shell provided with git.

There are two different ways it fails
1. key:value is used as a wrong key
2. if spaces are included: the JSON parameters cannot be parsed

* Command  
`cf cups demo-issue -p '{"key1":"value1","key2":"value2"}'`

* What occurred, incl. error and/or stack trace
```
{key1:value1>
key2:value2}>
Creating user provided service demo-issue in org Test/ space demo as john.doe...
OK
```

* What you expected to occur
I expected a service beeing created with two keys. I did not expect a prompt as I provided a full JSON string. Also the cli uses the complete string "key1:value1" as key instead of splitting it. Swapping double and single quotes does not make a difference (-p "{'key1':'value1','key2':'value2'}")

* Command  with some spaces 
`cf cups demo-issue -p '{ "key1" : "value1", "key2" : "value2" }'`

* What occurred, incl. error and/or stack trace
```
FAILED
Incorrect Usage. Requires an argument
NAME:
   create-user-provided-service - Make a user-provided service instance available to CF app
USAGE:
....
```

* What you expected to occur
I expected a service beeing created with two keys. When I swap the double and single quotes it behaves like the first described error.

* CLI Version  
cf version 6.20.0+25b1961-2016-06-29 and cf version 6.21.1+6fd3c9f-2016-08-10, both fail the same way

* CC API Endpoint Version  
2.54.0

* CF Trace, if issue relates to HTTP requests or strange behavior  
run the command with `-v` and paste or attach the trace output

* Platform & Shell Details  
Windows 7 64bit, German

**Comment by dkoper** [comment]
Hi @mayrstefan 

You put single quotes around your json fragment to prevent symbols to be interpreted by your shell, common on Linux and Mac.
Windows has different escaping rules, see `cf cups -h` for an example.

Regards,
Dies Koper
CF CLI PM

**Comment by mayrstefan** [comment]
Thanks for this hint. I didn't recognize that the examples had a different quoting than the samples in the usage section.

**Comment by hardy1334** [comment]
CODE--------------------------------------------------------------------
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
</head>
<body>
<h1>Hello lets talk about Json</h1>
<script>
var x={" age ": 22};
document.write(x);


</script>

</body>
</html>
OUTPUT--------------------------------------------------------------------------------------
Hello lets talk about Json

[object Object]


WHY IT IS NOT WORKING?
