### ISSUE TITLE
Installing without superuser permissions

### ISSUE THREAD

**Issue by konklone** [cloudfoundry/cli#935]
Right now, it appears that some installation paths, at least the Windows one, require superuser/administrative permissions to install the Cloud Foundry CLI. 

Could the Cloud Foundry CLI be used without superuser permissions? This would make adoption and experimentation in enterprise settings much more easy and rapid.

**Comment by dkoper** [comment]
We'll support this in the next release. Thanks @konklone!

**Comment by dkoper** [comment]
Thanks again for bringing this up. We have addressed it in the current release.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM
