### ISSUE TITLE
cf binary name changed inside https://s3.amazonaws.com/go-cli/releases/v6.21.1/cf-cli_6.21.1_linux_x86-64.tgz

### ISSUE THREAD

**Issue by matthiaskubik** [cloudfoundry/cli#942]
High five for submitting a report!  
If you found an issue with the cf CLI, please visit the [releases page](https://github.com/cloudfoundry/cli/releases/) and confirm it's not fixed already in the latest release.  
To avoid additional back and forth, please include the following details as relevant:

* Command  
e.g. `cf push myapp -i 2 --no-route`
The content of the downloadable tar.gz. file for the ubuntu cli has changed over night. While the Releases page shows last change 12 days ago while the cf binary inside the gz file changed yesterday from '**cf**' to '**cf-cli_linux_x86-64**'. Not sure if this is by intend or not

* What occurred, incl. error and/or stack trace
wrong executable filename

* What you expected to occur
If you changed the structure of the gz file by intend, I'd expect at least a new version number so that one can identify that change more easily. 

* CLI Version  
e.g. 6.13.0-dfba612 (see `cf -v` output)
6.21.1_linux_x86-64, but also 32-bit

* CC API Endpoint Version  
see `cf api` output
n/a
* CF Trace, if issue relates to HTTP requests or strange behavior  
run the command with `-v` and paste or attach the trace output
n/a
* Platform & Shell Details  
e.g. Mac OS X 10.11 iTerm, Windows 8.1 64-bit with PowerShell, Ubuntu 14.04.3 64-bit with gnome-terminal
at least Ubuntu 32 and 64 bit

* Any other relevant information  
e.g. details of an environment, cf CLI version, flag or value it does work with, DNS/network configuration, etc.

**Comment by suhlig** [comment]
I see the same when using Travis to deploy to Cloud Foundry -  it expects `cf`, but gets `cf-cli_linux_x86-64`).

**Comment by GarfieldIsAPhilosopher** [comment]
We have reverted those uploads as they had happened by accident.
Downloading now should fix the issue.
