### ISSUE TITLE
Rebuild binary with go 1.7 for macOS Sierra

### ISSUE THREAD

**Issue by samhandev** [cloudfoundry/cli#944]
Looks like macOS Sierra has broken binaries built with go 1.6.3
https://github.com/golang/go/issues/16579

Just need to do a rebuild with Go 1.7 and release the binary.

**Comment by dkoper** [comment]
Hi @samhandev 

Our next release will be built using Go 1.7 (our edge binaries are already).
Are you on macOS Sierra? How is the current binary failing?

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Closing, feel free to reopen or submit a new issue if you're seeing issues with the latest cf CLI once MacOS Sierra has been officially released.

**Comment by micophilip** [comment]
@dkoper I installed the latest cf after installing the official release of macOS Sierra and I'm still seeing issues with the cf push command:
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xdce2c3d80ac pc=0xfb2b]
runtime stack:
runtime.throw(0xafe400, 0x2a)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:547

**Comment by dkoper** [comment]
@micophilip Is that with the edge binary? What does `cf -v` return?

**Comment by micophilip** [comment]
@dkoper no it's the package, cf -v returns cf version 6.21.1+6fd3c9f-2016-08-10.. Should I download the binary?

**Comment by dkoper** [comment]
Look for 'edge' binary on the https://github.com/cloudfoundry/cli page.

**Comment by micophilip** [comment]
@dkoper thank you! no longer see that error - just wondering when is the change planned to update the pkg installers?

**Comment by dkoper** [comment]
@micophilip cf version 6.22.0, expected to be released this week, will be built with golang 1.7.1 and that is what resolves the issue.

**Comment by micophilip** [comment]
Thank you so much for all your help really appreciate it

**Comment by imguilherme** [comment]
@dkoper I've found this error as well. Is there a workaround to do before the new release from CF ?

Regards.

**Comment by imguilherme** [comment]
@dkoper  I've downloaded the edge binary as you said above and solved the problem. Thanks =)
