### ISSUE TITLE
Error: interface conversion: interface is int64, not string

### ISSUE THREAD

**Issue by rungari** [cloudfoundry/cli#945]
I ran this command:

		cf push trackEvents -b https://github.com/cloudfoundry/go-buildpack.git

	using this version of the CLI:

		6.7.0-c38c991

	and that this error occurred:

		interface conversion: interface is int64, not string

	and this stack trace:

		goroutine 1 [running]:
	main.generateBacktrace(0xc21000a000, 0x5)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Testing/src/github.com/cloudfoundry/cli/main/main.go:147 +0xa9
	main.handlePanics(0xf9a700, 0xc2100694e0)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Testing/src/github.com/cloudfoundry/cli/main/main.go:131 +0x123
	runtime.panic(0x5203e0, 0xc2100cf6c0)
		/usr/local/go/src/pkg/runtime/panic.c:248 +0x106
	github.com/cloudfoundry/cli/cf/manifest.bytesVal(0xfa9738, 0xc21022e418, 0x5cdc90, 0x6, 0xc2100d1640, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Testing/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/manifest/manifest.go:216 +0xe2
	github.com/cloudfoundry/cli/cf/manifest.mapToAppParams(0xc2101c1ba0, 0x4c, 0xfa9738, 0xc21022e418, 0x0, ...)
		/Users/pivotal/go-agent/pipelines/Mac-OSX-Testing/src/github.com/cloudfoundry/cli/tmp/cli_gopath/src/github.com/cloudfoundry/cli/cf/manifest/manifest.go:144 +0x33b
	github.com/cloudfoundry/cli/cf/manifest.Manifest.Applications(0xc2101c1

**Comment by dkoper** [comment]
Hi @rungari 

v6.7.0 is about 20 months old. Please try with the latest version, I believe this issue has been fixed.
https://github.com/cloudfoundry/cli#downloads

Regards,
Dies Koper
CF CLI PM
