### ISSUE TITLE
cli plugins not installing because old plugin exists?

### ISSUE THREAD

**Issue by jbayer** [cloudfoundry/cli#946]
- Command  
  `cf install-plugin https://github.com/cloudfoundry/v3-cli-plugin/blob/master/bin/OSX_binary?raw=true`
- What occurred, incl. error and/or stack trace
  The file OSX_binary already exists under the plugin directory.
- What you expected to occur
  I had previously uninstalled the plugin successfully using the cf cli, so i expected the binary to be removed, but it appears to have been left behind.
- CLI Version  
  cf version 6.21.1+6fd3c9f-2016-08-10
- Platform & Shell Details  
  Mac OSX 10.11.6

```
$ cf uninstall-plugin v3_beta
Uninstalling plugin v3_beta...
OK
Plugin v3_beta successfully uninstalled.
pintail:~ jamesbayer$ cf install-plugin https://github.com/cloudfoundry/v3-cli-plugin/blob/master/bin/OSX_binary?raw=true

**Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at your own risk.**

Do you want to install the plugin https://github.com/cloudfoundry/v3-cli-plugin/blob/master/bin/OSX_binary?raw=true? (y or n)> y

Attempting to download binary file from internet address...
13258092 bytes downloaded...
Installing plugin OSX_binary...
FAILED
The file OSX_binary already exists under the plugin directory.

pintail:~ jamesbayer$ cf uninstall-plugin v3_beta
Uninstalling plugin v3_beta...
FAILED
Plugin name v3_beta does not exist
pintail:~ jamesbayer$ cf install-plugin https://github.com/cloudfoundry/v3-cli-plugin/blob/master/bin/OSX_binary?raw=true

**Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at your own risk.**

Do you want to install the plugin https://github.com/cloudfoundry/v3-cli-plugin/blob/master/bin/OSX_binary?raw=true? (y or n)> y

Attempting to download binary file from internet address...
13258092 bytes downloaded...
Installing plugin OSX_binary...
FAILED
The file OSX_binary already exists under the plugin directory.
```

**Comment by jbayer** [comment]
this may be a confusing error as i downloaded the plugin with wget and was able to install it by using the local executable.

**Comment by jbayer** [comment]
the original cf plugin location is here: https://github.com/cloudfoundry/v3-cli-plugin

**Comment by jeffpak** [comment]
@jbayer

I tried to reproduce this bug but I wasn't able to. My steps included:

1. Install the plugin locally using a downloaded binary. (cf install-plugin OSX_BINARY)
1. Uninstall the plugin (cf uninstall-plugin v3_beta)
1. Re-install the plugin using the git url (cf install-plugin https://github.com/cloudfoundry/v3-cli-plugin/blob/master/bin/OSX_binary?raw=true)
1. Re-uninstall the plugin (cf uninstall-plugin v3_beta)

After doing these steps, I saw no complaints about the binary already existing.

Do you recall doing anything else while discovering this bug? If you could help us reproduce this bug on our machines, that would be swell.

-@jeffpak

**Comment by jbayer** [comment]
i don't recall doing anything differently. if it's hard or not possible to reproduce, it's ok with me to close the issue and we can open a new one it if it surfaces again

**Comment by dkoper** [comment]
We have a story coming up allowing `install-plugin` to update plugins (i.e. no need to uninstall the old one yourself). I'll give it one more go to see if I can reproduce this issue after that story's been delivered.

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
We have significantly improved the install and uninstall logic of plugins in cf CLI 6.27.0, which should prevent you from getting into a situation like this again.
If you do, please submit a new issue and we'll investigate.
Thanks for reporting.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM

**Comment by yanama123** [comment]
Hi, i have a query
i executed cf plugins ,deploy version was 0.2.0 then i reinstalled with 0.3.0 version 
$cf plugins
plugin                  version   command name   command help
deploy                  **0.2.0**     deploy         Deploys all the things, including orgs, spaces, domains, users, services and applications
if i try to re install same plugin and **different version** that is **0.3.0** with the command **cf install-plugin deploy -f**
now it is showing as following messages.
Install and use plugins at your own risk.
Plugin deploy 0.3.0 is already installed. Uninstalling existing plugin...
OK
Plugin deploy successfully uninstalled.
Installing plugin deploy ...
OK
Plugin deploy  0.3.0 successfully installed.

but i need output like this
**Plugin deploy 0.2.0 is already installed. Uninstalling existing plugin...
OK
Plugin deploy successfully uninstalled.
Installing plugin deploy ...
OK
Plugin deploy  0.3.0 successfully installed.**

**Comment by jbpivotal** [comment]
@yanama123 We tested and confirmed this is a bug. Thanks for letting us know. You can track it in our backlog here: https://www.pivotaltracker.com/story/show/154010723

In the future, please submit potential bugs or feature requests as a new issue or in response to an open issue instead of on a closed issue.

**Comment by yanama123** [comment]
@jbpivotal Hi , any updates on # https://www.pivotaltracker.com/story/show/154010723?
please let me know ASAP

**Comment by jbpivotal** [comment]
@yanama123 It's prioritized in the backlog but not yet started. I invite you to track the status through that link.

**Comment by yanama123** [comment]
How to publish Tile in PCF public marketplace and What is the purpose of errand VMs?

**Comment by dkoper** [comment]
@yanama123 Please don't post new questions on existing, closed issues. With our tooling, questions on closed issues are easy to miss and difficult to track.

This tracker is for the open source Cloud Foundry CLI. My team has no knowledge of tiles and PCF. Try contacting Pivotal support.
Errand VMs I believe are a BOSH feature, see https://bosh.io/docs/errands.html. That page lists a slack channel to contact them.
