### ISSUE TITLE
cf logs and proxy since the move to the NOAA

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry/cli#949]
So since the CLI move the NOAA the same issue as https://github.com/cloudfoundry/cli/issues/216 is now occurring.

I made a PR on the NOAA side https://github.com/cloudfoundry/noaa/pull/22

So please update the CLI when the loggregator team will merge this PR.

* Command  
e.g. `cf push logs`

* What occurred, incl. error and/or stack trace

Could not connect to the Loggregator endpoint.

* What you expected to occur

See the logs.

* CLI Version  

Since 6.17.1

* CC API Endpoint Version  
2.59.0

* Platform & Shell Details  
All platform

**Comment by shinji62** [comment]
Hi,

The PR have been merged any chance to bump the noaa lib ? https://github.com/cloudfoundry/noaa/pull/22

**Comment by dkoper** [comment]
@shinji62 Cool Gwenn! Bumped, please try our edge binary and report back if things are working for you now?

**Comment by shinji62** [comment]
Will check thanks

**Comment by shinji62** [comment]
@dkoper Yes it works fine now.
thanks for bumping the lib.

Can't wait for the next release.

**Comment by dkoper** [comment]
Thanks again. We have published the release.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM
