### ISSUE TITLE
incorrect encoding on windows7 when login interactively

### ISSUE THREAD

**Issue by boyang9527** [cloudfoundry/cli#951]
* Command  
`cf login`

* What occurred, incl. error and/or stack trace
when I use
```
        cf auth é x
```
I see the correct %C3%A9 encoding

when I use
```
        cf login -u é
```
I also see the correct %C3%A9 encoding

But when I login interactive:
```
        cf login
        ...
        Email> é
```

I get the wrong %E2%80%9A

**Comment by dkoper** [comment]
@boyang9527 
It seems this is a [Golang issue, fixed in 1.8](https://github.com/golang/go/issues/16857).
Current cf CLI (6.22.1) is built using the latest stable 1.7.1.
Let's revisit when we've moved to Golang 1.8 once it's out.

**Comment by boyang9527** [comment]
Thanks Dies! 
yes I have seen the comments in Pivotal tracker. 
I saw Go 1.8 released is scheduled in Feb 2017.  So looks like it can only be fixed almost  half a year later...

Anyway I am going to close this issue

**Comment by dkoper** [comment]
@boyang9527 You may want to look into whether there is a way to propose to the Golang devs to backport this to a Golang 1.7.x to get it sooner? (I don't know Golang's release schedule or process)

**Comment by boyang9527** [comment]
I don't know the Golang release schedule either... while it is worth to try

**Comment by boyang9527** [comment]
thanks Dies!
