### ISSUE TITLE
cf curl should have an option to specify a --fail flag

### ISSUE THREAD

**Issue by jaresty** [cloudfoundry/cli#953]
- Command  
  `cf curl`
- CLI Version  
  cf version 6.20.0+25b1961-2016-06-29
- CC API Endpoint Version  
  API endpoint: https://api.bosh-lite.com (API version: 2.61.0)

`curl` supports a `--fail` flag which causes non-successful HTTP calls to also result in a non-zero exit status for the utility.  We would like `cf curl` to support the same flag, so that our cf test helpers won't fail silently when there is a bad request.

**Comment by Gerg** [comment]
This would be nice for writing automated tests against CF api endpoints that aren't supported by the CLI yet.

**Comment by ameowlia** [comment]
Ran into this issue today when trying to TDD some acceptance tests. Would love this feature.

**Comment by abbyachau** [comment]
Hey all, thanks for this feedback; we'd like to implement this but unfortunately we'll need to refactor this command before we can implement new features. If this changes I'll update this issue. For folks interested, here is the `curl` epic in our [backlog](https://www.pivotaltracker.com/story/show/153041734).

**Comment by abbyachau** [comment]
Hi @jaresty thanks for creating this feature request. Before we work on this request, we wanted to clarify whether you wanted the flag to also suppress standard output (this is how `curl` functions) - or if you were just interested in a unique error code? If you are interested in the former as well, could you please help us understand the use case? Thanks.

**Comment by jaresty** [comment]
Hi @abbyachau I think it would be preferable if it behaved exactly the same as `curl` since it would not be as surprising, but for the use case that led me to submit this issue all I would need is for the exit code to match `curl`'s behavior.

**Comment by abbyachau** [comment]
Hi @jaresty thanks for the response. Appreciate the feedback. We are refactoring `cf curl` soon so that we can implement this feature. Thanks again.

**Comment by abbyachau** [comment]
Hi @jaresty thanks again for creating this feature request. The CLI team implemented support for a new flag `--fail` for `cf curl`. However we've opted not to suppress standard output as we wanted to deliver this feature to users (high value) and implementing the flag and also suppressing standard output would be expensive (refactoring may be required). As there did not appear to be user requirements for the latter, we decided to implement the flag without suppressing standard output. 

The flag option for `cf curl` will be available in our next release. I'm closing this issue as done but please do not hesitate to get in touch/reopen if you have questions/feedback.
