### ISSUE TITLE
cf cli for armhf

### ISSUE THREAD

**Issue by rajaasim** [cloudfoundry/cli#954]
Can you please make cli for armhf and other architectures?

**Comment by dkoper** [comment]
Hi @rajaasim 

Which architectures are you after exactly?
Being implemented in Golang, we are limited to the Golang supported architectures listed here:
https://github.com/golang/go/wiki/GoArm

There is no `armf` in this list. Are you referring to `armhf` (ARMv7 architecture including additional VFP3-D16 floating-point hardware extension)? Is the current linux binary failing on that?

Regards,
Dies Koper
CF CLI PM

**Comment by rajaasim** [comment]
Yes i was referring to armhf. it was a typo.  i want to use cli with linux on android but it cannot work because of architecture difference.

**Comment by rajaasim** [comment]
it is failing on armhf. exec format error or syntax near ")"

**Comment by rajaasim** [comment]
installer also cannot run as it says installer has a different architecture (amd64 or i386 whatever) and system architecture is armhf.

**Comment by dkoper** [comment]
We won't add armhf releases as I don't see enough user demand at this stage for running the cf CLI on this platform.
I'd like to use this issue to review our build instructions to ensure they're clear enough to help developers build the cf CLI themselves for this platform.

**Comment by dkoper** [comment]
Hi @rajaasim 

We have detailed our build instructions here:
https://github.com/cloudfoundry/cli/blob/master/CONTRIBUTING.md#compiling-the-binary

To build a binary for armhf, use `GOARCH=arm GOOS=linux  go build -o out/cf-cli_arm .`
where `file out/cf-cli_arm` returns:
`out/cf-cli_arm: ELF 32-bit LSB executable, ARM, version 1 (SYSV), statically linked, not stripped`

There is no easy way for us to get access armhf hardware to try it out though. Please report back how you go.

**Comment by Solvarg** [comment]
Hi dkopter,
The link above to build instructions is broken:-(
Trying to install cf-cli on a Beaglebone and I need the armhf build.  

Thanks
Bert
