### ISSUE TITLE
"Did you mean?" support would be nice.

### ISSUE THREAD

**Issue by jchester** [cloudfoundry/cli#955]
So I'm noodling with using MySQL on PCFDev.

I go through the discovery process:

```
$ cf marketplace
Getting services from marketplace in org pcfdev-org / space pcfdev-space as admin...
OK

service      plans        description
p-mysql      512mb, 1gb   MySQL databases on demand
p-rabbitmq   standard     RabbitMQ is a robust and scalable high-performance multi-protocol messaging broker.
p-redis      shared-vm    Redis service to provide a key-value store

TIP:  Use 'cf marketplace -s SERVICE' to view descriptions of individual plans of a given service.
```

Great tip! OK, let's look more closely.

```
$ cf marketplace -s p-mysql
Getting service plan information for service p-mysql as admin...
OK

service plan   description            free or paid
512mb          PCF Dev MySQL Server   free
1gb            PCF Dev MySQL Server   free
```

Free is my favourite price. OK, now it's time to create the service (I try to bind it first, of course, because am used to services already being bound for me).

So I dance my favourite waltz, "Jacques doesn't pay close attention sometimes":

```
$ cf create-service p-mysql 500Mb pcfdev-mysql
Creating service instance pcfdev-mysql in org pcfdev-org / space pcfdev-space as admin...
FAILED
Could not find plan with name 500Mb
```

Oh, it's not **512**, it's **500**. Silly me. Why'd I even think 500 would be a thing, anyhow?

```
$ cf create-service p-mysql 512Mb pcfdev-mysql
Creating service instance pcfdev-mysql in org pcfdev-org / space pcfdev-space as admin...
FAILED
Could not find plan with name 512Mb
```

... huh? Oh! It's **mb**, not **Mb**.

```
$ cf create-service p-mysql 512mb pcfdev-mysql
Creating service instance pcfdev-mysql in org pcfdev-org / space pcfdev-space as admin...
OK
```

Awesome.

Here's what I wish had happened:

```
$ cf create-service p-mysql 500Mb pcfdev-mysql
Creating service instance pcfdev-mysql in org pcfdev-org / space pcfdev-space as admin...
FAILED
Could not find plan with name 500Mb
    Did you mean "512mb"?
```

**Comment by dkoper** [comment]
Interesting suggestion, thanks!
And I assume you'd like to see that for all argument and option values, not just this one. :)

**Comment by jchester** [comment]
For all the things, please. Commands, arguments, org/space/app/service names, they'd all be useful.

**Comment by jchester** [comment]
... though, of course, I just noticed there *is* DYM? support for commands.

**Comment by dkoper** [comment]
Yes, it's there for commands. We'll do some exploration in what's involved in support it for options and arguments.

**Comment by dkoper** [comment]
This seems to be a "nice-have" that we'll never get to. Closing.
