### ISSUE TITLE
You have exceeded the total reserved route ports for your organization's quota.

### ISSUE THREAD

**Issue by rajaasim** [cloudfoundry/cli#956]
cf create-route development cf-tcpapps.io --random-port

Creating route cf-tcpapps.io for org xxxx / space development as yyyyyy@zzz.com...
FAILED
Server error, status code: 400, error code: 310009, message: You have exceeded the total reserved route ports for your organization's quota.

**Comment by dkoper** [comment]
Hi @rajaasim 

Do you have a question?
Run `cf org xxxx` to check the quota set on your org. The "quota" field likely returns something like "0 route ports".
Your CF deployment needs a TCP router group configured with a port range (see `cf router-groups`), and your org needs a quota with a positive value for reserved route ports to use TCP ports.

Regards,
Dies Koper
CF CLI PM

**Comment by rajaasim** [comment]
cf router-groups
Getting router groups as am.scorpionking@gmail.com ...

FAILED
Failed fetching router groups.
Server error, status code: 401, error code: UnauthorizedError, message: Token does not have 'routing.router_groups.read' scope

**Comment by dkoper** [comment]
@ragaskar You need admin permissions to retrieve the router groups. Please ask someone with admin permissions to increase your quota.

**Comment by shaktisd** [comment]
I am using a trial account, are route ports disabled for trial accounts ?

          domains:        cfapps.io, cf-tcpapps.io
          quota:          trial (2048M memory limit, unlimited instance memory limit, 1000 routes, 10 services, paid services disallowed, unlimited app instance limit, 0 route ports)
          spaces:         development
          space quotas:

**Comment by dkoper** [comment]
@shaktisd It seems your org has been assigned a quota that does not allow you to create any routes with ports. Ask your Cloud Foundry operator/vendor what your trial account allows you to do.
