### ISSUE TITLE
color app names by status

### ISSUE THREAD

**Issue by ryanjones71** [cloudfoundry/cli#960]
I like the coloring in the latest CLI.  Please enhance the cf apps screen to show the app names colored by status.  Currently the started and instances columns show red when there is a problem.  Please change the app names to show green when started, red when started with errors and gray when stopped.

CLI Version: 6.21.1-lds+b4cf3cb-2016-09-06
API version: 2.59.0
Windows 10 64 bit

**Comment by dkoper** [comment]
@ryanjjones10 Thank you for the suggestion.
I've shared the idea with some people, but there are some concerns, both from UX (harder to scan a list of app names if they vary in color, especially when you're not too interested in their running state) and implementation (populating a table with colored elements, already quite complex to maintain for the state column).
Have you seen other common CLIs that color the key row according to the value of one of its elements?

**Comment by ryanjones71** [comment]
I haven't seen other CLI's that do this.  I took some time to mock it up
and I can see how it is some harder to scan through the app names.  I also
mocked up changing the color of the state column.  I've attached a sample
if that is helpful. Another idea is that coloring the names could be a flag
so that when you care about state it is easy to see.

**Comment by dkoper** [comment]
@ryanjones71 I don't see the attachment.

**Comment by ryanjones71** [comment]
Sorry, I replied via email and that didn't add the attachment to github.
I've added it now.

**Comment by dkoper** [comment]
@ryanjones71 Sorry, I still don't see it.

**Comment by ryanjones71** [comment]
I attached it to my previous comment.  The link is
https://github.com/cloudfoundry/cli/files/563418/cf.cli.state.coloring.xlsx

**Comment by dkoper** [comment]
This seems to be a "nice-have" that we'll never get to, combined with the feedback from our designer and red/green color-blind colleague, I think I'll close this as a wontfix.
