### ISSUE TITLE
Option to send CF_TRACE output to stderr

### ISSUE THREAD

**Issue by pdelagrave** [cloudfoundry/cli#962]
Hi

We have issues with a tile bosh errand that run a shell script making heavy usage of CF CLI on PCF1.8/Azure, where enabling `CF_TRACE` to diagnose the problem is necessary.

But this script and many others are designed to work when `CF_TRACE` is disabled or set to a filename, i.e. the CF CLI output must not be 'polluted' with the additional log messages or the script will fail.

Shell scripts often run with `-x` enabled so it's very easy to diagnose problems. Bash sends the output to stderr, hence it would make sense to also be able to send the `CF_TRACE` output to stderr  and have a single continuous readable log file.

Perhaps adding the option of specifying `CF_TRACE=stderr` (and `stdout` for consistency, which would be equal to using `1`) could be a way to do it.

Maybe it would have been better to send `CF_TRACE` output to stderr by default instead of stdout but changing that behaviour now might break a lot of existing script.

Thanks

Pierre Delagrave
IAAS Enablement Team at Pivotal

**Comment by keymon** [comment]
As a workaround, you might use `CF_TRACE=/dev/stderr`, like this

```
CF_TRACE=/dev/stderr cf apps | less
``` 

From [what I read](http://unix.stackexchange.com/questions/36403/portability-of-dev-stdout), it works on Linux, that creates these devices, and in most of the modern shells simulate it.

**Comment by pdelagrave** [comment]
Good workaround, I did not think of it!

Thanks
