### ISSUE TITLE
cf install-plugin -f is broken since 6.22.0

### ISSUE THREAD

**Issue by matthiaskubik** [cloudfoundry/cli#964]
High five for submitting a report!  
If you found an issue with the cf CLI, please visit the [releases page](https://github.com/cloudfoundry/cli/releases/) and confirm it's not fixed already in the latest release.  
To avoid additional back and forth, please include the following details as relevant:

* Command  
cf install-plugin active-deploy -r bluemix -f

* What occurred, incl. error and/or stack trace

Incorrect Usage: expected argument for flag `-f'

NAME:
   install-plugin - Install CLI plugin

USAGE:
   cf install-plugin (LOCAL-PATH/TO/PLUGIN | URL | -r REPO_NAME PLUGIN_NAME) [-f]

   Prompts for confirmation unless '-f' is provided.

EXAMPLES:
   cf install-plugin ~/Downloads/plugin-foobar
   cf install-plugin https://example.com/plugin-foobar_linux_amd64
   cf install-plugin -r My-Repo plugin-echo

OPTIONS:
   -f      Force install of plugin without confirmation
   -r      Name of a registered repository where the specified plugin is located

SEE ALSO:
   add-plugin-repo, list-plugin-repos, plugins

* What you expected to occur
with 6.21.1 it installed the plugin as expected

* CLI Version  
6.22.0

* CC API Endpoint Version  
API version: 2.54.0

* CF Trace, if issue relates to HTTP requests or strange behavior  
run the command with `-v` and paste or attach the trace output

* Platform & Shell Details  
Ubuntu 64-bit

* Any other relevant information  
n/a

**Comment by dkoper** [comment]
Hi @matthiaskubik 

Thanks for the prompt feedback! We'll take a look..

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Thanks again. Fixed in 6.22.1.
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM

**Comment by matthiaskubik** [comment]
That was fast. Thanks guys! 

Gesendet von IBM Verse


   Dies Koper --- Re: [cloudfoundry/cli] cf install-plugin -f is broken since 6.22.0 (#964) --- 
    Von:"Dies Koper" <notifications@github.com>An:"cloudfoundry/cli" <cli@noreply.github.com>Kopie:"Matthias Kubik" <KUBIK@de.ibm.com>, "Mention" <mention@noreply.github.com>Datum:Sa. 24.09.2016 06:14Betreff:Re: [cloudfoundry/cli] cf install-plugin -f is broken since 6.22.0 (#964)
  
  Thanks again. Fixed in 6.22.1. https://github.com/cloudfoundry/cli#downloads 
 Cheers, Dies Koper CF CLI PM
