### ISSUE TITLE
Unable to set api : Getting Timeout

### ISSUE THREAD

**Issue by pmaitra** [cloudfoundry/cli#968]
I am using Windows 7, I had downloaded the latest version of both cf and cf_edge, and here are the versions of each of them:
C:\Users\pradipta>cf --version
cf version 6.22.1+6b7af9c-2016-09-24

C:\Users\pradipta>cf_edge --version
cf version 6.22.1+13769fc-2016-09-30

As suggested I ran the following:
1) 
C:\Windows\system32>curl -vvv https://api.springcloudeureka.com
* Rebuilt URL to: https://api.springcloudeureka.com/
*   Trying 92.242.132.27...
* connect to 92.242.132.27 port 443 failed: Timed out
* Failed to connect to api.springcloudeureka.com port 443: Timed out
* Closing connection 0
curl: (7) Failed to connect to api.springcloudeureka.com port 443: Timed out

2) And had set the CF_DIAL_TIMEOUT to 20

However, I am still stuck with the same problem:
C:\Users\pradipta>cf_edge api https://api.springcloudeureka.com
Setting api endpoint to https://api.springcloudeureka.com...
FAILED
Error performing request: Get https://api.springcloudeureka.com/v2/info: dial tcp 92.242.132.27:443: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

I am new to CF, so could have missed any thing, please do let me know.

**Comment by dsabeti** [comment]
@pmaitra This is likely not an issue with the CLI. The fact that you can't run `curl  https://api.springcloudeureka.com` suggests that there's something wrong with your CF deployment, specifically your networking and DNS setup. For starters, I've noticed that your domain, api.springcloudeureka.com, does not resolve. Start by making sure that your DNS is set up correctly -- you should be able to run `nslookup api.springcloudeureka.com`.

Please also answer the following questions so I can help you figure out what's going on:
1. What IaaS is your CF deployment running on? (AWS, Openstack, Google, vSphere, etc.)
2. Please post your deployment manifest. **Be sure to remove any passwords or other sensitive information.**

**Comment by pmaitra** [comment]
@dsabeti 
1) I tried using IBM Bluemix to Build and Deploy my Code, after creating the ORG (QTS) and SPACE (dev). 
2) After that, I could use the CF CLI to login using the API endpoint: cf login -a api.ng.bluemix.net
3) I could then create the user provided service using the cf cups command: cf cups springcloudeureka -p '{"uri":"http://springcloudeureka.mybluemix.net/eureka/"}'
4) Next I could see my service at the dashboard and also could run the app http://springcloudeureka.mybluemix.net/

I had followed information available on the internet and all these went fine using the IBM Bluemix.

However, I would like to know, If I were to use CF CLI for the API end Point creation and then login and deploying my app, what are the steps required? Do I have to own a domain before hand? I had tried to follow the information available on the internet, however, it seems there is some gap which is causing me this trouble. In case you are in a position to help, please be kind enough. Thanks

**Comment by dsabeti** [comment]
@pmaitra I think I understand now: you want to push your app to a Cloud Foundry (in this case, Bluemix), but you'd like to use your own custom domain `springcloudeureka.com` instead of their default `*.mybluemix.net`. If that's what you'd like to, indeed you need to own the domain before hand. There's some additional work involved once you own the domain as well -- most likely, setting up DNS records so that your custom domain resolves to the Bluemix routers. You'll have to ask Bluemix support for specific instructions for that, but a quick Google search found [this to help you get started](http://ryanjbaxter.com/2014/06/23/using-custom-domain-names-in-bluemix/?cm_mc_uid=19697225838414755985366&cm_mc_sid_50200000=1475598536).

Hope that helps!
