### ISSUE TITLE
CLI commands hiding paginated results from API

### ISSUE THREAD

**Issue by staylor14** [cloudfoundry/cli#970]
- Command
  Any CF CLI command where the CF API paginates results.  e.g.:
  `cf marketplace`
  `cf service-broker`
- What occurred
  When there are more than 50 results possible from any of the above commands, the result we're looking for may or may not be in the result set.  There's no way to get at other pages of results via the CLI that we're aware of.
- What you expected to occur
  We expect some indication that there are further results with a means of obtaining them (i.e. a means of paginating via the CLI).  We could also accept a "get them all" flag to the CLI.  Maybe both?
- CLI Version
  6.22.1+6b7af9c-2016-09-24
- CC API Endpoint Version
  2.62.0
- Platform & Shell Details
  Mac OS X 10.11.6, iTerm2 3.0.9

**Comment by dkoper** [comment]
Hi @staylor14 

Apologies for looking into this so late.
`cf marketplace` and `cf service-brokers` should return all services and service brokers.
Are you seeing that it's not displaying more than 50?
I just tried `cf marketplace` on Bluemix and it's displaying 80 services.

Regards,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Closing. Feel free to reopen or submit a new issue when you have more details on the issue you are experiencing.
