### ISSUE TITLE
[feature-request] Plugin API should support validating scopes against AccessToken from UAA

### ISSUE THREAD

**Issue by tushar-dadlani** [cloudfoundry/cli#972]
As a plugin author, it would be helpful to be able to validate scopes on an access token so that the plugin can fail fast on lack of necessary scopes instead of attempting a certain request and failing on inadequate permissions.

**Comment by dkoper** [comment]
@tushar-dadlani `cf oauth-token` returns the access token, which you can pass through a jwt token decoder to retrieve the scopes. Not sure about "failing fast", as we refresh the token using the refresh token (call to UAA), so with an HTTP call made you may find it just as fast to make the API request you want to make.

**Comment by tushar-dadlani** [comment]
@dkoper : The use case I am targeting is the following:

As a plugin developer, I want to know if the user using the plugin has the `cloud_controller.read` or `cloud_controller.write` scope within his/her oauth-token so that if my plugin is performing an operation that needs that scope, I can validate before doing any operation.

**Comment by dkoper** [comment]
The way I mentioned above is how we recommend you'd do this. You can call our oauth-token command using [CliCommand](There is no other way than calling our oauth-token).
In the CLI we don't decode the jwt token so there is nothing there you could reuse.

Regards,
Dies Koper
CF CLI PM

**Comment by tushar-dadlani** [comment]
@dkoper Okay, will figure out a way to do it within the plugin if I need it.
