### ISSUE TITLE
[feature-request] `cf api` to currently-logged-in API should not prompt login

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry/cli#975]

**Comment by dkoper** [comment]
Can you provide more details?
```
D:\Users\koperd\Downloads\bin>.\cf --version
cf version 6.22.1+6b7af9c-2016-09-24

D:\Users\koperd\Downloads\bin>cf api
API endpoint: https://api.acceptance.cli.ci.cf-app.com (API version: 2.62.0)
```

It doesn't prompt.

**Comment by jadekler** [comment]
Ah, apologies @dkoper. This issue was with the wrong command (login) in mind. Retrospectively it doesn't make sense for `login` not to prompt you to login heh

**Comment by dkoper** [comment]
Sure. You can use `cf api` and `cf auth` to set your API endpoint and log in if you want to make sure not to be prompted (like in scripts).
