### ISSUE TITLE
cf cli tool for raspberry pi - raspbian-jessie os

### ISSUE THREAD

**Issue by hishara** [cloudfoundry/cli#979]
Hi, i tried installing the debain package for cf cli tool on my raspberry pi running on raspbian-jessie os but it doesn't support

**Comment by dkoper** [comment]
Hi @hishara 

The Debian binary we build does not support Raspberry Pi's architecture. You'd have to build it yourself, changing our [build instructions](https://github.com/cloudfoundry/cli/blob/master/CONTRIBUTING.md#compiling-the-binary) accordingly.
But may I ask, why would you want to run the cf CLI on your Raspberry Pi? Did you develop an app on the Raspberry Pi that you now want to push to the cloud from it?

Cheers,
Dies Koper
CF CLI PM

**Comment by dkoper** [comment]
Closing, trusting the instructions I linked to are helpful.

**Comment by bdbais** [comment]
@dkoper  your link is 404...
I followed ibm instruction for link repository but it didn't work on raspberry 3 .

```
root@raspberrypi:~# wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
OK
root@raspberrypi:~# echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list

root@raspberrypi:~# apt-get update
[...]

root@raspberrypi:~# apt-cache search cf-cli
<empty>
```
