### ISSUE TITLE
[feature-request] Manifest inheritance support merging single app

### ISSUE THREAD

**Issue by TiraO** [cloudfoundry/cli#982]
I would love the feature described in [issue #895](https://github.com/cloudfoundry/cli/issues/895#issuecomment-235262881). I'm trying to have some secrets stored in a separate repo be pulled in when I do a `cf push`. I would therefore like to set up something like 

manifest.yml

```

---
inherit: secrets-manifest.yml
applications:
- name: my-app
   buildpack: java_buildpack
```

secrets-manifest.yml

```

---
applications:
- name: my-app
   env:
     secret-password: secret123
```

Note that this works just fine when you have a single app and specify the manifests like so:

manifest.yml

```

---
inherit: secrets-manifest.yml
name: my-app
buildpack: java_buildpack
```

secrets-manifest.yml

```

---
name: my-app
env:
  secret-password: secret123
```

**Comment by uvzubovs** [comment]
Shouldn't secrets be stored in the user provided service instances and installed by the systems administrators in advance of the application deployment? It seems to me that treating secrets as application properties breaks the principle of separation of concerns.

**Comment by dkoper** [comment]
@TiraO We have decided to deprecate app manifest inheritance. We have shared an alternative solution that I believe would cater your use case better. Please take a look:
https://lists.cloudfoundry.org/g/cf-dev/message/7649
