### ISSUE TITLE
update-buildpack has an issue parsing `-p`

### ISSUE THREAD

**Issue by mhoran** [cloudfoundry/cli#983]
* Command
`cf update-buildpack ruby_buildpack -i 1 -p /Users/pivotal/Downloads/ruby_buildpack-cached-v1.6.27.zip`

* What occurred, incl. error and/or stack trace
Unexpected flag error
type: marshal
message: invalid argument for flag `-p' (expected int): strconv.ParseInt: parsing "/Users/pivotal/Downloads/ruby_buildpack-cached-v1.6.27.zip": invalid syntax

* What you expected to occur
For it to work

* CLI Version  
6.22.1 (as available in releases)

* CC API Endpoint Version  
2.54.0

* Platform & Shell Details  
Mac OS X 10.11.6 and bash in iTerm

* Any other relevant information  
Rolling back to 6.21.1+6fd3c9f-2016-08-10 works fine.

**Comment by dkoper** [comment]
We fixed this one [here](https://www.pivotaltracker.com/n/projects/892938/stories/131127335), will be part of our next release (very soon).
Thanks for reporting!

**Comment by dkoper** [comment]
Thanks again for your report.
The fix is part of the just published 6.22.2 release:
https://github.com/cloudfoundry/cli#downloads

Cheers,
Dies Koper
CF CLI PM
