### ISSUE TITLE
How do we allocate memory to circuit-breaker service 

### ISSUE THREAD

**Issue by sachkk76** [cloudfoundry/cli#984]
cf create-service p-circuit-breaker standard circuit-breaker standard 

Also tried by providing json with -c
   {
      "cluster_nodes": {
         "count": 5,
         "memory_mb": 1024
      }
   }
or
 -c '{\"ram_gb\":4}'

does not work. It says -  Please provide a valid JSON object or path to a file containing a valid JSON object.
Any documentation on correct syntax?

**Comment by dkoper** [comment]
What OS/platform are you on? What shell?

**Comment by dkoper** [comment]
Closing. Feel free to re-open or submit a new issue if the above didn't help and you have more information for us to investigate.
