### ISSUE TITLE
cf-cli-installer_6.22.1_win32 is not working

### ISSUE THREAD

**Issue by ubermensch37** [cloudfoundry/cli#985]
After installing cf-cli-installer_6.22.1_win32, when you try to execute "cf" commands, it throws an errror that says that cf.exe is not compatible with the current version of the OS, it recommends to validate if you need x32 or x64. So, I replaced the cf.exe (version 6.22.1) with the cf.exe (version 6.22.0) and now it is working.

Before replacing the cf, I tried several Windows compatibility options, ran it as administrator but no luck. My OS is Windows 7, Service Pack 1.

Regards

**Comment by dkoper** [comment]
Thanks for the report!
I have confirmed that the 32 bit installer seems to bundle the 64 bit binary for the cf CLI 6.22.1 Windows release.
The 6.21.1 32 bit installer bundles the 32 bit binary correctly. The team is on it.

**Comment by dkoper** [comment]
Hi,

This is fixed now. the recently released 6.22.2 didn't have this issue and was correct from the start.
Thanks again for reporting!

Regards,
Dies Koper
CF CLI PM
