### ISSUE TITLE
Previous release download links point to latest release

### ISSUE THREAD

**Issue by glyn** [cloudfoundry/cli#987]
To avoid a [regression](https://github.com/cf-tm-bot/cli/issues/86) with v6.22.1, I tried to download an earlier version. Unfortunately, the download links for the previous version v6.22.0 on the [releases page](https://github.com/cloudfoundry/cli/releases/) actually points to v6.22.1. 

This is the case at least for Mac OS X 64 bit binary and Linux 64 bit binary releases.

Also, some earlier releases such as v6.21.1 and v6.17.0 also point to v6.22.1 downloads. I didn't try all the versions in between, but I suspect the problem is true of all of them.

To reproduce this:

* Issue `wget https://cli.run.pivotal.io/stable?release=macosx64-binary&version=6.22.0&source=github-rel`
* Observe the output:
```
...
Location: https://s3-us-west-1.amazonaws.com/cf-cli-releases/releases/v6.22.1/cf-cli_6.22.1_osx.tgz [following]
...
```

(Fortunately, I had an old version lying around which I was able to use, but others may not be so fortunate.)

**Comment by dkoper** [comment]
Hi @glyn

Can you confirm you put quotes around that url to prevent your shell from interpreting the ampersand for something else and not including the version param in the request?

**Comment by glyn** [comment]
Ah pebcac. Apologies! It works with the quotes.
