### ISSUE TITLE
[feature request] cf cli should exit with the status code returned of terminated plugin process

### ISSUE THREAD

**Issue by MarkyMarkMcDonald** [cloudfoundry/cli#990]
[The cf cli always returns an exit status code 1](https://github.com/cloudfoundry/cli/blob/master/plugin/rpc/run_plugin.go#L29), even though we are terminating with an exit status code of `50` in our plugin. We would like that to be surfaced through the cf cli as well.

Does this sound like a feature that a PR would be accepted for?

Thanks!
@MarkyMarkMcDonald & @aemengo

**Comment by dkoper** [comment]
Yes, thanks!

**Comment by dkoper** [comment]
Closing in anticipation of the PR.
