### ISSUE TITLE
Provide version and SHA within released source tar balls

### ISSUE THREAD

**Issue by svollath** [cloudfoundry/cli#992]
When building the CLI "offline" (e.g. packaging from a released tar ball), 
```cf version``` would report ```cf version BUILT_FROM_SOURCE-BUILT_AT_UNKNOWN_TIME```
unless "cf/app_constants.go" is patched with the respective values.

While the version (e.g. 6.22.2) is provided within the tar ball, the short SHA of the last commit (e.g. "61ce394") isn't.
In addition, the source folder isn't a git repository, which makes scripts like ```
bin/replace_sha``` fail - and getting the "CURRENT_SHA" requires external network.

It would be nice, if you could provide a value for "CURRENT_SHA" within the source tar ball of a release.
Have this (offline) optional respected by bin/replace_sha, would also be good.

**Comment by dkoper** [comment]
Hi @svollath 

I don't think it makes sense to include the sha in `cf version` output when it's built from a downloaded tarball (i.e. no longer under git's control). How about we make it default to `6.22.2+unknown-2016-11-04`?

**Comment by svollath** [comment]
Hi @dkoper 
sure, in fact the release tag just points to the SHA that is shown from the version. However the current binaries you provide as installer packages, do report the SHA for the release tag.
If you are open to change this, I would suggest to (be able to) completely omit it like ```6.22.2-2016-11-04```, or at least not to choose "unknown", because it sounds a bit vague.

**Comment by dkoper** [comment]
Sure. Note that we'd recommend a plus sign between version and date for [SemVer](http://semver.org/) compliance.

**Comment by svollath** [comment]
Hi @dkoper 
great, if you would be fine with e.g. ```6.22.2+2016-11-04```, just considering the date as build meta data, or even just ```6.22.2```.
Then it would make sense to reflect it in "bin/replace_sha", "cf/app_constants.go" and its usage.
Currently it's not possible to have such string with patching "cf/app_constants.go". One is only able to achieve the following:
* ```6.22.2-2016-11-04```, or
* ```6.22.2+2016-11-11-```, or
* ```6.22.2-```
According to SemVer you want to optionally append build meta data with a plus, and then seperate identifiers with a dot.
But you expect the SHA (part1 of your build meta data) as "Version" (including the plus), and auto extend the date as "BuiltOnDate" (part2 of your build meta data) with a dash.

The easiest way would most likely be to have (cf/app_constants.go) be like:
```
package cf

var (
        Version     = "BUILT_FROM_SOURCE"
        BuildMetaData = "SHA-BUILT_AT_UNKNOWN_TIME"
        Name        = "cf"
)
```

and auto-extend "Version with a plus, if "BuildMetaData" isn't empty.

**Comment by dkoper** [comment]
Hi @svollath 

We made some changes in this area. Can you check again if your concerns have been addressed?

**Comment by svollath** [comment]
It's curently not in our sprint, but I'll have a look asap. Thx.

**Comment by dkoper** [comment]
Closing, I believe there is nothing left for us to do.
