### ISSUE TITLE
Don't ignore folders which only contain a .gitignore file

### ISSUE THREAD

**Issue by mastertinner** [cloudfoundry/cli#993]
* Command  
e.g. `cf push my-laravel-app`

* What occurred, incl. error and/or stack trace
`cf push` ignores all empty folders and treats folders which only contain a `.gitignore` file as empty. This leads to problems when pushing Laravel applications: https://github.com/laravel/framework/issues/16243

* What you expected to occur
I would expect the CLI to push folders which only contain a `.gitignore` file as empty folders.

* CLI Version  
6.22.2+a95e24c-2016-10-27

* CC API Endpoint Version  
2.63.0

* Platform & Shell Details  
Mac OS X 10.12.1, iTerm2

**Comment by dkoper** [comment]
Thanks! We'll investigate.
Note that if you add a `.cfignore` file in the root of the app with the following, the "cache" folder is pushed as well.
```
!/bootstrap/cache
```

**Comment by mastertinner** [comment]
good idea, thanks @dkoper!

**Comment by rogamoore** [comment]
This also happened to me today as Symfony is using .gitignore files too. See https://github.com/symfony/recipes/pull/83

The reason is this: https://docs.cloudfoundry.org/devguide/deploy-apps/prepare-to-deploy.html#exclude
I think CF should not magically ignore files - I would prefer to have full control.

**Comment by rogamoore** [comment]
@dkoper Any chance to get this fixed? Anything I can do? :)

**Comment by dkoper** [comment]
@rogamoore I hope to publish a refactored `push` that addresses this and other push related issues in the next few weeks. As for what you could do, try it out when we release (I'll add a comment in this story) and let us know if it resolves your issue!
`cf push` has been magically ignoring certain files for as long as I know. Maybe it should not have, but it does, I assume for good reasons, so I don't want to change that. Skipping folders with only a `.gitignore` file however sounds like something we should investigate as a bug.

**Comment by dkoper** [comment]
@rogamoore @mastertinner Do you mind trying with `v2-push` (cf CLI 6.33.0) for your specific use case?

**Comment by rogamoore** [comment]
@dkoper Will try this until the end of the week! Thanks!

**Comment by mastertinner** [comment]
@dkoper, I can confirm that `v2-push` doesn't ignore empty directories anymore. Yay! However, if I have a directory containing only a `.gitignore` file, the directory gets pushed but the `.gitignore` file it contains doesn't... So when I `cf ssh` into the container, I can see the directory which contained a `.gitignore` file on my local machine but I cannot see the `.gitignore` file it contained.

**Comment by dkoper** [comment]
@mastertinner `.gitignore` file is ignored by default, as expected according to http://docs.cloudfoundry.org/devguide/deploy-apps/prepare-to-deploy.html#ignore-unnecessary-files-when-pushing, right?

**Comment by mastertinner** [comment]
Thanks for the clarification, @dkoper.

**Comment by rogamoore** [comment]
Also works for me. Thanks @dkoper !

**Comment by dkoper** [comment]
This is now resolved in `push` in cf CLI 6.34.0.

Regards,
Dies Koper
CF CLI PM
