### ISSUE TITLE
Small language issue when confirming installation of a plugin

### ISSUE THREAD

**Issue by lbayerl** [cloudfoundry/cli#994]
**cf version 6.22.2**+a95e24c-2016-10-27
Kubuntu 14.04 LTS

Command:
**cf install-plugin https://example.com/some-plugin**
with a German language version of cf (don't know how I got this) asks me to confirm whether I really want to install the plugin:

"**Achtung: Plug-ins werden als Binärdateien von möglicherweise nicht vertrauenswürdigen Autoren geschrieben. Sie installieren und verwenden Plug-ins auf eigenes Risiko.**

Möchten Sie das Plug-in https://swisscom-plugin.scapp.io/linux64/swisscom-plugin installieren? (J oder N)"

**(J oder N)** is the same as the English **(Y or N)**, but in this case J won't be accepted and the error message is:

"FEHLGESCHLAGEN
Plug-in-Installation abgebrochen" (which means FAILED - plugin installation cancelled).

One has to know that you'll have to confirm with Y but with J.

**Comment by dkoper** [comment]
Hi @lbayerl 

It seems this is the only confirmation prompt where we displayed the `Y or N` and German was one of the p[;few locales where the translators did not leave that intact.

We're migrating commands to a new library that does the printing of [y/n] for us. I prefer to not localise this: it gets too confusing in some locales (like where they have no single-letter abbeviations on a QWERTY keyboard, like Japanese).

In cf CLI 6.23.1, this command no longer displays the `J oder N`, consistent with other confirmation prompts. In a future release, you'll see the `[y/n]` added.
https://github.com/cloudfoundry/cli#downloads

Thanks for your report!

Regards,
Dies Koper
CF CLI PM
